Three Cubes Game: irr::video::CColorConverter Class Reference
irr::video::CColorConverter Class Reference
Static Public Member Functions
static void convert1BitTo16Bit (const u8 *in, s16 *out, s32 width, s32 height, s32 linepad=0, bool flip=false)
converts a monochrome bitmap to A1R5G5B5
static void convert4BitTo16Bit (const u8 *in, s16 *out, s32 width, s32 height, const s32 *palette, s32 linepad=0, bool flip=false)
converts a 4 bit palettized image to A1R5G5B5
static void convert8BitTo16Bit (const u8 *in, s16 *out, s32 width, s32 height, const s32 *palette, s32 linepad=0, bool flip=false)
converts a 8 bit palettized image to A1R5G5B5
static void convert8BitTo24Bit (const u8 *in, u8 *out, s32 width, s32 height, const u8 *palette, s32 linepad=0, bool flip=false)
converts a 8 bit palettized or non palettized image (A8) into R8G8B8
static void convert8BitTo32Bit (const u8 *in, u8 *out, s32 width, s32 height, const u8 *palette, s32 linepad=0, bool flip=false)
converts a 8 bit palettized or non palettized image (A8) into A8R8G8B8
static void convert16BitTo16Bit (const s16 *in, s16 *out, s32 width, s32 height, s32 linepad=0, bool flip=false)
converts R8G8B8 16 bit data to A1R5G5B5 data
static void convert24BitTo24Bit (const u8 *in, u8 *out, s32 width, s32 height, s32 linepad=0, bool flip=false, bool bgr=false)
copies R8G8B8 24bit data to 24bit data
static void convert16bitToA8R8G8B8andResize (const s16 *in, s32 *out, s32 newWidth, s32 newHeight, s32 currentWidth, s32 currentHeight)
static void convert32BitTo32Bit (const s32 *in, s32 *out, s32 width, s32 height, s32 linepad, bool flip=false)
copies X8R8G8B8 32 bit data
static void convert_A1R5G5B5toR8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_A1R5G5B5toB8G8R8 (const void *sP, s32 sN, void *dP)
static void convert_A1R5G5B5toA8R8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_A1R5G5B5toA1R5G5B5 (const void *sP, s32 sN, void *dP)
static void convert_A1R5G5B5toR5G5B5A1 (const void *sP, s32 sN, void *dP)
static void convert_A1R5G5B5toR5G6B5 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toR8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toB8G8R8 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toA8R8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toA1R5G5B5 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toA1B5G5R5 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toR5G6B5 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toR3G3B2 (const void *sP, s32 sN, void *dP)
static void convert_R8G8B8toR8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_R8G8B8toA8R8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_R8G8B8toA1R5G5B5 (const void *sP, s32 sN, void *dP)
static void convert_R8G8B8toB8G8R8 (const void *sP, s32 sN, void *dP)
static void convert_R8G8B8toR5G6B5 (const void *sP, s32 sN, void *dP)
static void convert_B8G8R8toA8R8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_B8G8R8A8toA8R8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toR8G8B8A8 (const void *sP, s32 sN, void *dP)
static void convert_A8R8G8B8toA8B8G8R8 (const void *sP, s32 sN, void *dP)
static void convert_R5G6B5toR5G6B5 (const void *sP, s32 sN, void *dP)
static void convert_R5G6B5toR8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_R5G6B5toB8G8R8 (const void *sP, s32 sN, void *dP)
static void convert_R5G6B5toA8R8G8B8 (const void *sP, s32 sN, void *dP)
static void convert_R5G6B5toA1R5G5B5 (const void *sP, s32 sN, void *dP)
static void convert_viaFormat (const void *sP, ECOLOR_FORMAT sF, s32 sN, void *dP, ECOLOR_FORMAT dF)
static bool canConvertFormat (ECOLOR_FORMAT sourceFormat, ECOLOR_FORMAT destFormat)
Detailed Description
Definition at line 16 of file CColorConverter.h.
Member Function Documentation
convert16BitTo16Bit()
void irr::video::CColorConverter::convert16BitTo16Bit (const s16 * in, s16 * out, s32 width, s32 height, s32 linepad = 0, bool flip = false) static
converts R8G8B8 16 bit data to A1R5G5B5 data
converts 16bit data to 16bit data
Definition at line 205 of file CColorConverter.cpp.
Referenced by irr::video::CImageLoaderTGA::loadImage(), and irr::video::CImageLoaderBMP::loadImage().
convert16bitToA8R8G8B8andResize()
void irr::video::CColorConverter::convert16bitToA8R8G8B8andResize (const s16 * in, s32 * out, s32 newWidth, s32 newHeight, s32 currentWidth, s32 currentHeight) static
Resizes the surface to a new size and converts it at the same time to an A8R8G8B8 format, returning the pointer to the new buffer.
Definition at line 270 of file CColorConverter.cpp.
convert1BitTo16Bit()
void irr::video::CColorConverter::convert1BitTo16Bit (const u8 * in, s16 * out, s32 width, s32 height, s32 linepad = 0, bool flip = false) static
converts a monochrome bitmap to A1R5G5B5
converts a monochrome bitmap to A1R5G5B5 data
Definition at line 16 of file CColorConverter.cpp.
Referenced by irr::video::CImageLoaderBMP::loadImage().
convert24BitTo24Bit()
void irr::video::CColorConverter::convert24BitTo24Bit (const u8 * in, u8 * out, s32 width, s32 height, s32 linepad = 0, bool flip = false, bool bgr = false) static
copies R8G8B8 24bit data to 24bit data
copies R8G8B8 24 bit data to 24 data, and flips and mirrors the image during the process.
Definition at line 233 of file CColorConverter.cpp.
Referenced by irr::video::CImageLoaderTGA::loadImage(), and irr::video::CImageLoaderBMP::loadImage().
convert32BitTo32Bit()
void irr::video::CColorConverter::convert32BitTo32Bit (const s32 * in, s32 * out, s32 width, s32 height, s32 linepad, bool flip = false) static
copies X8R8G8B8 32 bit data
copies X8R8G8B8 32 bit data, and flips and mirrors the image during the process.
Definition at line 302 of file CColorConverter.cpp.
Referenced by irr::video::CImageLoaderTGA::loadImage(), and irr::video::CImageLoaderBMP::loadImage().
convert8BitTo16Bit()
void irr::video::CColorConverter::convert8BitTo16Bit (const u8 * in, s16 * out, s32 width, s32 height, const s32 * palette, s32 linepad = 0, bool flip = false) static
converts a 8 bit palettized image to A1R5G5B5
converts a 8 bit palettized image into A1R5G5B5
Definition at line 92 of file CColorConverter.cpp.
References irr::video::X8R8G8B8toA1R5G5B5().
Referenced by irr::video::CImageLoaderTGA::loadImage(), and irr::video::CImageLoaderBMP::loadImage().
convert8BitTo32Bit()
void irr::video::CColorConverter::convert8BitTo32Bit (const u8 * in, u8 * out, s32 width, s32 height, const u8 * palette, s32 linepad = 0, bool flip = false) static
converts a 8 bit palettized or non palettized image (A8) into A8R8G8B8
converts a 8 bit palettized or non palettized image (A8) into R8G8B8
Definition at line 158 of file CColorConverter.cpp.
convert_A1R5G5B5toR8G8B8()
void irr::video::CColorConverter::convert_A1R5G5B5toR8G8B8 (const void * sP, s32 sN, void * dP) static
Functions for converting one image format to another efficiently and hopefully correctly. Note that the format descriptions refer to the ECOLOR_FORMAT's and not to memory layout. Reasons for that go back to DX9 naming which tended to flip 32-bit and 16-bit byte orders so ARGB usually means BGRA.
Parameters
sP pointer to source pixel data
sN number of source pixels to copy
dP pointer to destination data buffer. must be big enough to hold sN pixels in the output format.
Definition at line 329 of file CColorConverter.cpp.
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CColorConverter.h
lib/irrlichtmt/source/Irrlicht/CColorConverter.cpp