Three Cubes Game: irr::core::vector3d< T > Class Template Reference
irr::core::vector3d< T > Class Template Reference
3d vector template class with lots of operators and methods.
#include <vector3d.h>
Public Member Functions
vector3d ()
Default constructor (null vector).
vector3d (T nx, T ny, T nz)
Constructor with three different values.
vector3d (T n)
Constructor with the same value for all elements.
vector3d< T > operator- () const
vector3d< T > operator+ (const vector3d< T > &other) const
vector3d< T > & operator+= (const vector3d< T > &other)
vector3d< T > operator+ (const T val) const
vector3d< T > & operator+= (const T val)
vector3d< T > operator- (const vector3d< T > &other) const
vector3d< T > & operator-= (const vector3d< T > &other)
vector3d< T > operator- (const T val) const
vector3d< T > & operator-= (const T val)
vector3d< T > operator* (const vector3d< T > &other) const
vector3d< T > & operator*= (const vector3d< T > &other)
vector3d< T > operator* (const T v) const
vector3d< T > & operator*= (const T v)
vector3d< T > operator/ (const vector3d< T > &other) const
vector3d< T > & operator/= (const vector3d< T > &other)
vector3d< T > operator/ (const T v) const
vector3d< T > & operator/= (const T v)
T & operator[] (u32 index)
const T & operator[] (u32 index) const
bool operator<= (const vector3d< T > &other) const
sort in order X, Y, Z. Equality with rounding tolerance.
bool operator>= (const vector3d< T > &other) const
sort in order X, Y, Z. Equality with rounding tolerance.
bool operator< (const vector3d< T > &other) const
sort in order X, Y, Z. Difference must be above rounding tolerance.
bool operator> (const vector3d< T > &other) const
sort in order X, Y, Z. Difference must be above rounding tolerance.
bool operator== (const vector3d< T > &other) const
use weak float compare
bool operator!= (const vector3d< T > &other) const
bool equals (const vector3d< T > &other, const T tolerance=(T) ROUNDING_ERROR_f32) const
returns if this vector equals the other one, taking floating point rounding errors into account
vector3d< T > & set (const T nx, const T ny, const T nz)
vector3d< T > & set (const vector3d< T > &p)
T getLength () const
Get length of the vector.
T getLengthSQ () const
Get squared length of the vector.
T dotProduct (const vector3d< T > &other) const
Get the dot product with another vector.
T getDistanceFrom (const vector3d< T > &other) const
Get distance from another point.
T getDistanceFromSQ (const vector3d< T > &other) const
Returns squared distance from another point.
vector3d< T > crossProduct (const vector3d< T > &p) const
Calculates the cross product with another vector.
bool isBetweenPoints (const vector3d< T > &begin, const vector3d< T > &end) const
Returns if this vector interpreted as a point is on a line between two other points.
vector3d< T > & normalize ()
Normalizes the vector.
vector3d< T > & setLength (T newlength)
Sets the length of the vector to a new value.
vector3d< T > & invert ()
Inverts the vector.
void rotateXZBy (f64 degrees, const vector3d< T > &center=vector3d< T >())
Rotates the vector by a specified number of degrees around the Y axis and the specified center.
void rotateXYBy (f64 degrees, const vector3d< T > &center=vector3d< T >())
Rotates the vector by a specified number of degrees around the Z axis and the specified center.
void rotateYZBy (f64 degrees, const vector3d< T > &center=vector3d< T >())
Rotates the vector by a specified number of degrees around the X axis and the specified center.
vector3d< T > getInterpolated (const vector3d< T > &other, f64 d) const
Creates an interpolated vector between this vector and another vector.
vector3d< T > getInterpolated_quadratic (const vector3d< T > &v2, const vector3d< T > &v3, f64 d) const
Creates a quadratically interpolated vector between this and two other vectors.
vector3d< T > & interpolate (const vector3d< T > &a, const vector3d< T > &b, f64 d)
Sets this vector to the linearly interpolated vector between a and b.
vector3d< T > getHorizontalAngle () const
Get the rotations that would make a (0,0,1) direction vector point in the same direction as this direction vector.
vector3d< T > getSphericalCoordinateAngles () const
Get the spherical coordinate angles.
vector3d< T > rotationToDirection (const vector3d< T > &forwards=vector3d< T >(0, 0, 1)) const
Builds a direction vector from (this) rotation vector.
void getAs4Values (T *array) const
Fills an array of 4 values with the vector data (usually floats).
void getAs3Values (T *array) const
Fills an array of 3 values with the vector data (usually floats).
vector3d< s32 > operator/ (s32 val) const
partial specialization for integer vectors
vector3d< s32 > & operator/= (s32 val)
vector3d< s32 > getSphericalCoordinateAngles () const
Public Attributes
T X
X coordinate of the vector.
T Y
Y coordinate of the vector.
T Z
Z coordinate of the vector.
Detailed Description
template<class T>
class irr::core::vector3d< T >
3d vector template class with lots of operators and methods.
The vector3d class is used in Irrlicht for three main purposes: 1) As a direction vector (most of the methods assume this). 2) As a position in 3d space (which is synonymous with a direction vector from the origin to this position). 3) To hold three Euler rotations, where X is pitch, Y is yaw and Z is roll.
Definition at line 24 of file vector3d.h.
Member Function Documentation
crossProduct()
template<class T > vector3d<T> irr::core::vector3d< T >::crossProduct (const vector3d< T > & p) const inline
Calculates the cross product with another vector.
Parameters
p Vector to multiply with.
Returns
Crossproduct of this vector with p.
Definition at line 159 of file vector3d.h.
Referenced by irr::core::CMatrix4< f32 >::buildAxisAlignedBillboard(), irr::core::CMatrix4< f32 >::buildCameraLookAtMatrixLH(), irr::core::CMatrix4< f32 >::buildCameraLookAtMatrixRH(), irr::core::CMatrix4< f32 >::buildRotateFromTo(), irr::core::quaternion::operator*(), and irr::core::quaternion::rotationFromTo().
getAs3Values()
template<class T > void irr::core::vector3d< T >::getAs3Values (T * array) const inline
Fills an array of 3 values with the vector data (usually floats).
Useful for setting in shader constants for example.
Definition at line 413 of file vector3d.h.
getAs4Values()
template<class T > void irr::core::vector3d< T >::getAs4Values (T * array) const inline
Fills an array of 4 values with the vector data (usually floats).
Useful for setting in shader constants for example. The fourth value will always be 0.
Definition at line 403 of file vector3d.h.
getDistanceFrom()
template<class T > T irr::core::vector3d< T >::getDistanceFrom (const vector3d< T > & other) const inline
Get distance from another point.
Here, the vector is interpreted as point in 3 dimensional space.
Definition at line 144 of file vector3d.h.
Referenced by irr::core::triangle3d< T >::closestPointOnTriangle(), and Client::CSMGetNode().
getDistanceFromSQ()
template<class T > T irr::core::vector3d< T >::getDistanceFromSQ (const vector3d< T > & other) const inline
Returns squared distance from another point.
Here, the vector is interpreted as point in 3 dimensional space.
Definition at line 151 of file vector3d.h.
Referenced by irr::core::vector3d< s16 >::isBetweenPoints().
getHorizontalAngle()
template<class T > vector3d<T> irr::core::vector3d< T >::getHorizontalAngle () const inline
Get the rotations that would make a (0,0,1) direction vector point in the same direction as this direction vector.
Thanks to Arras on the Irrlicht forums for this method. This utility method is very useful for orienting scene nodes towards specific targets. For example, if this vector represents the difference between two scene nodes, then applying the result of getHorizontalAngle() to one scene node will point it at the other one. Example code: Where target and seeker are of type ISceneNode* const vector3df toTarget(target->getAbsolutePosition() - seeker->getAbsolutePosition()); const vector3df requiredRotation = toTarget.getHorizontalAngle(); seeker->setRotation(requiredRotation);
Returns
A rotation vector containing the X (pitch) and Y (raw) rotations (in degrees) that when applied to a +Z (e.g. 0, 0, 1) direction vector would make it point in the same direction as this vector. The Z (roll) rotation is always 0, since two Euler rotations are sufficient to point in any given direction.
Definition at line 313 of file vector3d.h.
Referenced by irr::scene::CCameraSceneNode::setTarget().
getInterpolated()
template<class T > vector3d<T> irr::core::vector3d< T >::getInterpolated (const vector3d< T > & other, f64 d) const inline
Creates an interpolated vector between this vector and another vector.
Parameters
other The other vector to interpolate with.
d Interpolation value between 0.0f (all the other vector) and 1.0f (all this vector). Note that this is the opposite direction of interpolation to getInterpolated_quadratic()
Returns
An interpolated vector. This vector is not modified.
Definition at line 259 of file vector3d.h.
getInterpolated_quadratic()
template<class T > vector3d<T> irr::core::vector3d< T >::getInterpolated_quadratic (const vector3d< T > & v2, const vector3d< T > & v3, f64 d) const inline
Creates a quadratically interpolated vector between this and two other vectors.
Parameters
v2 Second vector to interpolate with.
v3 Third vector to interpolate with (maximum at 1.0f)
d Interpolation value between 0.0f (all this vector) and 1.0f (all the 3rd vector). Note that this is the opposite direction of interpolation to getInterpolated() and interpolate()
Returns
An interpolated vector. This vector is not modified.
Definition at line 271 of file vector3d.h.
getLengthSQ()
template<class T > T irr::core::vector3d< T >::getLengthSQ () const inline
Get squared length of the vector.
This is useful because it is much faster than getLength().
Returns
Squared length of the vector.
Definition at line 134 of file vector3d.h.
Referenced by irr::core::vector3d< s16 >::getDistanceFromSQ(), and irr::core::vector3d< s16 >::isBetweenPoints().
getSphericalCoordinateAngles()
template<class T > vector3d<T> irr::core::vector3d< T >::getSphericalCoordinateAngles () const inline
Get the spherical coordinate angles.
This returns Euler degrees for the point represented by this vector. The calculation assumes the pole at (0,1,0) and returns the angles in X and Y.
Definition at line 344 of file vector3d.h.
interpolate()
template<class T > vector3d<T>& irr::core::vector3d< T >::interpolate (const vector3d< T > & a, const vector3d< T > & b, f64 d) inline
Sets this vector to the linearly interpolated vector between a and b.
Parameters
a first vector to interpolate with, maximum at 1.0f
b second vector to interpolate with, maximum at 0.0f
d Interpolation value between 0.0f (all vector b) and 1.0f (all vector a) Note that this is the opposite direction of interpolation to getInterpolated_quadratic()
Definition at line 290 of file vector3d.h.
isBetweenPoints()
template<class T > bool irr::core::vector3d< T >::isBetweenPoints (const vector3d< T > & begin, const vector3d< T > & end) const inline
Returns if this vector interpreted as a point is on a line between two other points.
It is assumed that the point is on the line.
Parameters
begin Beginning vector to compare between.
end Ending vector to compare between.
Returns
True if this vector is between begin and end, false if not.
Definition at line 169 of file vector3d.h.
Referenced by irr::core::plane3d< f32 >::getIntersectionWithLimitedLine(), and irr::core::triangle3d< T >::getIntersectionWithLimitedLine().
normalize()
template<class T > vector3d<T>& irr::core::vector3d< T >::normalize () inline
Normalizes the vector.
In case of the 0 vector the result is still 0, otherwise the length of the vector will be 1.
Returns
Reference to this vector after normalization.
Definition at line 180 of file vector3d.h.
Referenced by irr::core::CMatrix4< f32 >::buildCameraLookAtMatrixLH(), irr::core::CMatrix4< f32 >::buildCameraLookAtMatrixRH(), irr::core::CMatrix4< f32 >::buildRotateFromTo(), irr::video::CNullDriver::drawMeshBufferNormals(), irr::core::quaternion::rotationFromTo(), irr::core::vector3d< s16 >::setLength(), irr::core::CMatrix4< f32 >::transformPlane(), and irr::scene::CCameraSceneNode::updateMatrices().
rotateXYBy()
template<class T > void irr::core::vector3d< T >::rotateXYBy (f64 degrees, const vector3d< T > & center = vector3d<T>()) inline
Rotates the vector by a specified number of degrees around the Z axis and the specified center.
Parameters
degrees Number of degrees to rotate around the Z axis.
center The center of the rotation.
Definition at line 227 of file vector3d.h.
rotateXZBy()
template<class T > void irr::core::vector3d< T >::rotateXZBy (f64 degrees, const vector3d< T > & center = vector3d<T>()) inline
Rotates the vector by a specified number of degrees around the Y axis and the specified center.
Parameters
degrees Number of degrees to rotate around the Y axis.
center The center of the rotation.
Definition at line 212 of file vector3d.h.
rotateYZBy()
template<class T > void irr::core::vector3d< T >::rotateYZBy (f64 degrees, const vector3d< T > & center = vector3d<T>()) inline
Rotates the vector by a specified number of degrees around the X axis and the specified center.
Parameters
degrees Number of degrees to rotate around the X axis.
center The center of the rotation.
Definition at line 242 of file vector3d.h.
rotationToDirection()
template<class T > vector3d<T> irr::core::vector3d< T >::rotationToDirection (const vector3d< T > & forwards = vector3d<T>(0, 0, 1)) const inline
Builds a direction vector from (this) rotation vector.
This vector is assumed to be a rotation vector composed of 3 Euler angle rotations, in degrees. The implementation performs the same calculations as using a matrix to do the rotation.
Parameters
[in] forwards The direction representing "forwards" which will be rotated by this vector. If you do not provide a direction, then the +Z axis (0, 0, 1) will be assumed to be forwards.
Returns
A direction vector calculated by rotating the forwards direction by the 3 Euler angles (in degrees) represented by this vector.
Definition at line 371 of file vector3d.h.
Referenced by irr::scene::CCameraSceneNode::setRotation().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/vector3d.h