Three Cubes Game: irr::gui::GUISkin Class Reference
irr::gui::GUISkin Class Reference
Public Member Functions
GUISkin (EGUI_SKIN_TYPE type, video::IVideoDriver *driver)
virtual ~GUISkin ()
destructor
virtual video::SColor getColor (EGUI_DEFAULT_COLOR color) const
returns default color
virtual void setColor (EGUI_DEFAULT_COLOR which, video::SColor newColor)
sets a default color
virtual s32 getSize (EGUI_DEFAULT_SIZE size) const
returns size for the given size type
virtual void setSize (EGUI_DEFAULT_SIZE which, s32 size)
sets a default size
virtual IGUIFont * getFont (EGUI_DEFAULT_FONT which=EGDF_DEFAULT) const
returns the default font
virtual void setFont (IGUIFont *font, EGUI_DEFAULT_FONT which=EGDF_DEFAULT)
sets a default font
virtual void setSpriteBank (IGUISpriteBank *bank)
sets the sprite bank used for drawing icons
virtual IGUISpriteBank * getSpriteBank () const
gets the sprite bank used for drawing icons
virtual u32 getIcon (EGUI_DEFAULT_ICON icon) const
Returns a default icon.
virtual void setIcon (EGUI_DEFAULT_ICON icon, u32 index)
Sets a default icon.
virtual const wchar_t * getDefaultText (EGUI_DEFAULT_TEXT text) const
Returns a default text.
virtual void setDefaultText (EGUI_DEFAULT_TEXT which, const wchar_t *newText)
Sets a default text.
virtual void draw3DButtonPaneStandard (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)
draws a standard 3d button pane
virtual void drawColored3DButtonPaneStandard (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, const video::SColor *colors=0)
draws a standard 3d button pane
virtual void draw3DButtonPanePressed (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)
draws a pressed 3d button pane
virtual void drawColored3DButtonPanePressed (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, const video::SColor *colors=0)
draws a pressed 3d button pane
virtual void draw3DSunkenPane (IGUIElement *element, video::SColor bgcolor, bool flat, bool fillBackGround, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)
draws a sunken 3d pane
virtual void drawColored3DSunkenPane (IGUIElement *element, video::SColor bgcolor, bool flat, bool fillBackGround, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, const video::SColor *colors=0)
draws a sunken 3d pane
virtual core::rect< s32 > draw3DWindowBackground (IGUIElement *element, bool drawTitleBar, video::SColor titleBarColor, const core::rect< s32 > &rect, const core::rect< s32 > *clip, core::rect< s32 > *checkClientArea)
draws a window background
virtual core::rect< s32 > drawColored3DWindowBackground (IGUIElement *element, bool drawTitleBar, video::SColor titleBarColor, const core::rect< s32 > &rect, const core::rect< s32 > *clip, core::rect< s32 > *checkClientArea, const video::SColor *colors=0)
draws a window background
virtual void draw3DMenuPane (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)
draws a standard 3d menu pane
virtual void drawColored3DMenuPane (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, const video::SColor *colors=0)
draws a standard 3d menu pane
virtual void draw3DToolBar (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)
draws a standard 3d tool bar
virtual void drawColored3DToolBar (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, const video::SColor *colors=0)
draws a standard 3d tool bar
virtual void draw3DTabButton (IGUIElement *element, bool active, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, EGUI_ALIGNMENT alignment=EGUIA_UPPERLEFT)
draws a tab button
virtual void drawColored3DTabButton (IGUIElement *element, bool active, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, EGUI_ALIGNMENT alignment=EGUIA_UPPERLEFT, const video::SColor *colors=0)
draws a tab button
virtual void draw3DTabBody (IGUIElement *element, bool border, bool background, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, s32 tabHeight=-1, EGUI_ALIGNMENT alignment=EGUIA_UPPERLEFT)
draws a tab control body
virtual void drawColored3DTabBody (IGUIElement *element, bool border, bool background, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, s32 tabHeight=-1, EGUI_ALIGNMENT alignment=EGUIA_UPPERLEFT, const video::SColor *colors=0)
draws a tab control body
virtual void drawIcon (IGUIElement *element, EGUI_DEFAULT_ICON icon, const core::position2di position, u32 starttime=0, u32 currenttime=0, bool loop=false, const core::rect< s32 > *clip=0)
draws an icon, usually from the skin's sprite bank
virtual void drawColoredIcon (IGUIElement *element, EGUI_DEFAULT_ICON icon, const core::position2di position, u32 starttime=0, u32 currenttime=0, bool loop=false, const core::rect< s32 > *clip=0, const video::SColor *colors=0)
draws an icon, usually from the skin's sprite bank
virtual void draw2DRectangle (IGUIElement *element, const video::SColor &color, const core::rect< s32 > &pos, const core::rect< s32 > *clip=0)
draws a 2d rectangle.
virtual EGUI_SKIN_TYPE getType () const
get the type of this skin
virtual void getColors (video::SColor *colors)
gets the colors
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Attributes
video::SColor Colors [EGDC_COUNT]
s32 Sizes [EGDS_COUNT]
u32 Icons [EGDI_COUNT]
IGUIFont * Fonts [EGDF_COUNT]
IGUISpriteBank * SpriteBank
core::stringw Texts [EGDT_COUNT]
video::IVideoDriver * Driver
bool UseGradient
EGUI_SKIN_TYPE Type
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Definition at line 21 of file guiSkin.h.
Member Function Documentation
draw2DRectangle()
void irr::gui::GUISkin::draw2DRectangle (IGUIElement * element, const video::SColor & color, const core::rect< s32 > & pos, const core::rect< s32 > * clip = 0) virtual
draws a 2d rectangle.
Parameters
element Pointer to the element which wishes to draw this icon. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
color Color of the rectangle to draw. The alpha component specifies how transparent the rectangle will be.
pos Position of the rectangle.
clip Pointer to rectangle against which the rectangle will be clipped. If the pointer is null, no clipping will be performed.
Implements irr::gui::IGUISkin.
Definition at line 1018 of file guiSkin.cpp.
draw3DButtonPanePressed()
virtual void irr::gui::GUISkin::draw3DButtonPanePressed (IGUIElement * element, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) inline virtual
draws a pressed 3d button pane
Used for drawing for example buttons in pressed state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
rect Defining area where to draw.
clip Clip area.
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
Implements irr::gui::IGUISkin.
Definition at line 105 of file guiSkin.h.
References drawColored3DButtonPanePressed().
draw3DButtonPaneStandard()
virtual void irr::gui::GUISkin::draw3DButtonPaneStandard (IGUIElement * element, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) inline virtual
draws a standard 3d button pane
Used for drawing for example buttons in normal state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
rect Defining area where to draw.
clip Clip area.
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
Implements irr::gui::IGUISkin.
Definition at line 84 of file guiSkin.h.
References drawColored3DButtonPaneStandard().
draw3DMenuPane()
virtual void irr::gui::GUISkin::draw3DMenuPane (IGUIElement * element, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) inline virtual
draws a standard 3d menu pane
Used for drawing for menus and context menus. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 183 of file guiSkin.h.
References drawColored3DMenuPane().
draw3DSunkenPane()
virtual void irr::gui::GUISkin::draw3DSunkenPane (IGUIElement * element, video::SColor bgcolor, bool flat, bool fillBackGround, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) inline virtual
draws a sunken 3d pane
Used for drawing the background of edit, combo or check boxes.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
bgcolor Background color.
flat Specifies if the sunken pane should be flat or displayed as sunken deep into the ground.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 127 of file guiSkin.h.
References drawColored3DSunkenPane().
draw3DTabBody()
virtual void irr::gui::GUISkin::draw3DTabBody (IGUIElement * element, bool border, bool background, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0, s32 tabHeight = -1, EGUI_ALIGNMENT alignment = EGUIA_UPPERLEFT) inline virtual
draws a tab control body
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
border Specifies if the border should be drawn.
background Specifies if the background should be drawn.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 240 of file guiSkin.h.
References drawColored3DTabBody().
draw3DTabButton()
virtual void irr::gui::GUISkin::draw3DTabButton (IGUIElement * element, bool active, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0, EGUI_ALIGNMENT alignment = EGUIA_UPPERLEFT) inline virtual
draws a tab button
Used for drawing for tab buttons on top of tabs.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
active Specifies if the tab is currently active.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 222 of file guiSkin.h.
References drawColored3DTabButton().
draw3DToolBar()
virtual void irr::gui::GUISkin::draw3DToolBar (IGUIElement * element, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) inline virtual
draws a standard 3d tool bar
Used for drawing for toolbars and menus.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 202 of file guiSkin.h.
References drawColored3DToolBar().
draw3DWindowBackground()
virtual core::rect<s32> irr::gui::GUISkin::draw3DWindowBackground (IGUIElement * element, bool drawTitleBar, video::SColor titleBarColor, const core::rect< s32 > & rect, const core::rect< s32 > * clip, core::rect< s32 > * checkClientArea) inline virtual
draws a window background
Used for drawing the background of dialogs and windows.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
titleBarColor Title color.
drawTitleBar True to enable title drawing.
rect Defining area where to draw.
clip Clip area.
checkClientArea When set to non-null the function will not draw anything, but will instead return the clientArea which can be used for drawing by the calling window. That is the area without borders and without titlebar.
Returns
Returns rect where it would be good to draw title bar text. This will work even when checkClientArea is set to a non-null value.
Implements irr::gui::IGUISkin.
Definition at line 157 of file guiSkin.h.
References drawColored3DWindowBackground().
drawColored3DButtonPanePressed()
void irr::gui::GUISkin::drawColored3DButtonPanePressed (IGUIElement * element, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0, const video::SColor * colors = 0) virtual
draws a pressed 3d button pane
Used for drawing for example buttons in pressed state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
rect Defining area where to draw.
clip Clip area.
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
Definition at line 376 of file guiSkin.cpp.
References irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::video::SColor::getInterpolated(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by GUIButton::draw(), and draw3DButtonPanePressed().
drawColored3DButtonPaneStandard()
void irr::gui::GUISkin::drawColored3DButtonPaneStandard (IGUIElement * element, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0, const video::SColor * colors = 0) virtual
draws a standard 3d button pane
Used for drawing for example buttons in normal state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
rect Defining area where to draw.
clip Clip area.
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
Definition at line 314 of file guiSkin.cpp.
References irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGDC_WINDOW, irr::gui::EGST_BURNING_SKIN, irr::video::SColor::getInterpolated(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by GUIButton::draw(), and draw3DButtonPaneStandard().
drawColored3DMenuPane()
void irr::gui::GUISkin::drawColored3DMenuPane (IGUIElement * element, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0, const video::SColor * colors = 0) virtual
draws a standard 3d menu pane
Used for drawing for menus and context menus. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Definition at line 670 of file guiSkin.cpp.
References irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGST_BURNING_SKIN, irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by draw3DMenuPane().
drawColored3DSunkenPane()
void irr::gui::GUISkin::drawColored3DSunkenPane (IGUIElement * element, video::SColor bgcolor, bool flat, bool fillBackGround, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0, const video::SColor * colors = 0) virtual
draws a sunken 3d pane
Used for drawing the background of edit, combo or check boxes.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
bgcolor Background color.
flat Specifies if the sunken pane should be flat or displayed as sunken deep into the ground.
rect Defining area where to draw.
clip Clip area.
Definition at line 426 of file guiSkin.cpp.
References irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by draw3DSunkenPane().
drawColored3DTabBody()
void irr::gui::GUISkin::drawColored3DTabBody (IGUIElement * element, bool border, bool background, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0, s32 tabHeight = -1, EGUI_ALIGNMENT alignment = EGUIA_UPPERLEFT, const video::SColor * colors = 0) virtual
draws a tab control body
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
border Specifies if the border should be drawn.
background Specifies if the background should be drawn.
rect Defining area where to draw.
clip Clip area.
Definition at line 894 of file guiSkin.cpp.
References irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGUIA_UPPERLEFT, irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by draw3DTabBody().
drawColored3DTabButton()
void irr::gui::GUISkin::drawColored3DTabButton (IGUIElement * element, bool active, const core::rect< s32 > & frameRect, const core::rect< s32 > * clip = 0, EGUI_ALIGNMENT alignment = EGUIA_UPPERLEFT, const video::SColor * colors = 0) virtual
draws a tab button
Used for drawing for tab buttons on top of tabs.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
active Specifies if the tab is currently active.
rect Defining area where to draw.
clip Clip area.
Definition at line 807 of file guiSkin.cpp.
References irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGUIA_UPPERLEFT, irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by draw3DTabButton().
drawColored3DToolBar()
void irr::gui::GUISkin::drawColored3DToolBar (IGUIElement * element, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0, const video::SColor * colors = 0) virtual
draws a standard 3d tool bar
Used for drawing for toolbars and menus.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Definition at line 754 of file guiSkin.cpp.
References irr::video::SColor::color, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_SHADOW, irr::gui::EGST_BURNING_SKIN, irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by draw3DToolBar().
drawColoredIcon()
void irr::gui::GUISkin::drawColoredIcon (IGUIElement * element, EGUI_DEFAULT_ICON icon, const core::position2di position, u32 starttime = 0, u32 currenttime = 0, bool loop = false, const core::rect< s32 > * clip = 0, const video::SColor * colors = 0) virtual
draws an icon, usually from the skin's sprite bank
Parameters
parent Pointer to the element which wishes to draw this icon. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
icon Specifies the icon to be drawn.
position The position to draw the icon
starttime The time at the start of the animation
currenttime The present time, used to calculate the frame number
loop Whether the animation should loop or not
clip Clip area.
Definition at line 992 of file guiSkin.cpp.
References irr::gui::EGDC_GRAY_WINDOW_SYMBOL, irr::gui::EGDC_WINDOW_SYMBOL, and irr::gui::IGUIElement::isEnabled().
Referenced by drawIcon().
drawIcon()
virtual void irr::gui::GUISkin::drawIcon (IGUIElement * element, EGUI_DEFAULT_ICON icon, const core::position2di position, u32 starttime = 0, u32 currenttime = 0, bool loop = false, const core::rect< s32 > * clip = 0) inline virtual
draws an icon, usually from the skin's sprite bank
Parameters
element Pointer to the element which wishes to draw this icon. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
icon Specifies the icon to be drawn.
position The position to draw the icon
starttime The time at the start of the animation
currenttime The present time, used to calculate the frame number
loop Whether the animation should loop or not
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 260 of file guiSkin.h.
References drawColoredIcon().
getDefaultText()
const wchar_t * irr::gui::GUISkin::getDefaultText (EGUI_DEFAULT_TEXT text) const virtual
Returns a default text.
For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Returns a default text. For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Implements irr::gui::IGUISkin.
Definition at line 286 of file guiSkin.cpp.
References irr::gui::EGDT_COUNT.
getIcon()
u32 irr::gui::GUISkin::getIcon (EGUI_DEFAULT_ICON icon) const virtual
Returns a default icon.
Returns the sprite index within the sprite bank
Implements irr::gui::IGUISkin.
Definition at line 267 of file guiSkin.cpp.
References irr::gui::EGDI_COUNT.
getSpriteBank()
IGUISpriteBank * irr::gui::GUISkin::getSpriteBank () const virtual
gets the sprite bank used for drawing icons
gets the sprite bank stored
Implements irr::gui::IGUISkin.
Definition at line 247 of file guiSkin.cpp.
setDefaultText()
void irr::gui::GUISkin::setDefaultText (EGUI_DEFAULT_TEXT which, const wchar_t * newText) virtual
Sets a default text.
For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Sets a default text. For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Implements irr::gui::IGUISkin.
Definition at line 297 of file guiSkin.cpp.
References irr::gui::EGDT_COUNT.
setIcon()
void irr::gui::GUISkin::setIcon (EGUI_DEFAULT_ICON icon, u32 index) virtual
Sets a default icon.
Sets the sprite index used for drawing icons like arrows, close buttons and ticks in checkboxes
Parameters
icon Enum specifying which icon to change
index The sprite index used to draw this icon
Implements irr::gui::IGUISkin.
Definition at line 277 of file guiSkin.cpp.
References irr::gui::EGDI_COUNT.
setSpriteBank()
void irr::gui::GUISkin::setSpriteBank (IGUISpriteBank * bank) virtual
sets the sprite bank used for drawing icons
set a new sprite bank or remove one by passing 0
Implements irr::gui::IGUISkin.
Definition at line 254 of file guiSkin.cpp.
References irr::IReferenceCounted::grab().
The documentation for this class was generated from the following files:
src/gui/guiSkin.h
src/gui/guiSkin.cpp