Three Cubes Game: irr::scene::COBJMeshFileLoader Class Reference
irr::scene::COBJMeshFileLoader Class Reference
Meshloader capable of loading obj meshes.
#include <COBJMeshFileLoader.h>
Classes
struct SObjMtl
Public Member Functions
COBJMeshFileLoader (scene::ISceneManager *smgr)
Constructor.
virtual ~COBJMeshFileLoader ()
destructor
bool isALoadableFileExtension (const io::path &filename) const override
IAnimatedMesh * createMesh (io::IReadFile *file) override
Public Member Functions inherited from irr::scene::IMeshLoader
IMeshLoader ()
Constructor.
virtual ~IMeshLoader ()
Destructor.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Member Functions
const c8 * goFirstWord (const c8 *buf, const c8 *const bufEnd, bool acrossNewlines=true)
skip space characters and stop on first non-space
const c8 * goNextWord (const c8 *buf, const c8 *const bufEnd, bool acrossNewlines=true)
skip current word and stop at beginning of next one
const c8 * goNextLine (const c8 *buf, const c8 *const bufEnd)
Read until line break is reached and stop at the next non-space character.
u32 copyWord (c8 *outBuf, const c8 *inBuf, u32 outBufLength, const c8 *const pBufEnd)
core::stringc copyLine (const c8 *inBuf, const c8 *const bufEnd)
const c8 * goAndCopyNextWord (c8 *outBuf, const c8 *inBuf, u32 outBufLength, const c8 *const pBufEnd)
SObjMtl * findMtl (const core::stringc &mtlName, const core::stringc &grpName)
Find and return the material with the given name.
const c8 * readColor (const c8 *bufPtr, video::SColor &color, const c8 *const pBufEnd)
Read RGB color.
const c8 * readVec3 (const c8 *bufPtr, core::vector3df &vec, const c8 *const pBufEnd)
Read 3d vector of floats.
const c8 * readUV (const c8 *bufPtr, core::vector2df &vec, const c8 *const pBufEnd)
Read 2d vector of floats.
const c8 * readBool (const c8 *bufPtr, bool &tf, const c8 *const bufEnd)
Read boolean value represented as 'on' or 'off'.
bool retrieveVertexIndices (c8 *vertexData, s32 *idx, const c8 *bufEnd, u32 vbsize, u32 vtsize, u32 vnsize)
void cleanUp ()
Private Attributes
scene::ISceneManager * SceneManager
core::array< SObjMtl * > Materials
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Meshloader capable of loading obj meshes.
Definition at line 20 of file COBJMeshFileLoader.h.
Member Function Documentation
createMesh()
IAnimatedMesh * irr::scene::COBJMeshFileLoader::createMesh (io::IReadFile * file) override virtual
creates/loads an animated mesh from the file.
Returns
Pointer to the created mesh. Returns 0 if loading failed. If you no longer need the mesh, you should call IAnimatedMesh::drop(). See IReferenceCounted::drop() for more information.
Implements irr::scene::IMeshLoader.
Definition at line 54 of file COBJMeshFileLoader.cpp.
References irr::scene::SAnimatedMesh::addMesh(), irr::scene::SMesh::addMeshBuffer(), irr::core::string< T >::c_str(), irr::video::S3DVertex::Color, irr::video::SMaterial::DiffuseColor, irr::IReferenceCounted::drop(), irr::scene::EAMT_OBJ, irr::ELL_DEBUG, irr::ELL_ERROR, irr::ELL_INFORMATION, findMtl(), irr::io::IAttributes::getAttributeAsBool(), irr::scene::SMesh::getMeshBufferCount(), irr::scene::ISceneManager::getMeshManipulator(), irr::scene::ISceneManager::getParameters(), goNextLine(), goNextWord(), irr::scene::CMeshBuffer< T >::Indices, irr::scene::CMeshBuffer< T >::Material, irr::video::S3DVertex::Normal, irr::scene::OBJ_LOADER_IGNORE_GROUPS, irr::scene::OBJ_LOADER_IGNORE_MATERIAL_FILES, irr::video::S3DVertex::Pos, irr::core::array< T >::push_back(), readUV(), readVec3(), irr::core::array< T >::reallocate(), irr::scene::SMesh::recalculateBoundingBox(), irr::scene::SAnimatedMesh::recalculateBoundingBox(), irr::scene::IMeshManipulator::recalculateNormals(), irr::core::array< T >::set_used(), irr::core::array< T >::size(), irr::core::string< T >::size(), irr::core::strtoul10(), irr::video::S3DVertex::TCoords, irr::scene::SAnimatedMesh::Type, and irr::scene::CMeshBuffer< T >::Vertices.
isALoadableFileExtension()
bool irr::scene::COBJMeshFileLoader::isALoadableFileExtension (const io::path & filename) const override virtual
returns true if the file maybe is able to be loaded by this class based on the file extension (e.g. ".obj")
returns true if the file maybe is able to be loaded by this class based on the file extension (e.g. ".bsp")
Implements irr::scene::IMeshLoader.
Definition at line 44 of file COBJMeshFileLoader.cpp.
References irr::core::hasFileExtension().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/COBJMeshFileLoader.h
lib/irrlichtmt/source/Irrlicht/COBJMeshFileLoader.cpp