Three Cubes Game: ScreenTarget Class Reference
ScreenTarget Class Reference
#include <pipeline.h>
Public Member Functions
virtual void activate (PipelineContext &context) override
virtual void reset (PipelineContext &context) override
Private Attributes
core::dimension2du size
Additional Inherited Members
Protected Attributes inherited from RenderTarget
bool m_clear {true}
Detailed Description
Implements direct output to screen framebuffer.
Definition at line 266 of file pipeline.h.
Member Function Documentation
activate()
void ScreenTarget::activate (PipelineContext & context) override virtual
Activate the render target and configure OpenGL state for the output. This is usually done by
See also
RenderStep implementations.
Reimplemented from RenderTarget.
Definition at line 226 of file pipeline.cpp.
References RenderTarget::activate(), irr::IrrlichtDevice::getVideoDriver(), and irr::video::IVideoDriver::setRenderTarget().
reset()
void ScreenTarget::reset (PipelineContext & context) override virtual
Resets the state of the object for the next pipeline iteration
Reimplemented from RenderTarget.
Definition at line 241 of file pipeline.cpp.
References irr::video::IVideoDriver::getScreenSize(), irr::IrrlichtDevice::getVideoDriver(), and RenderTarget::reset().
The documentation for this class was generated from the following files:
src/client/render/pipeline.h
src/client/render/pipeline.cpp