Three Cubes Game: irr::IrrlichtDevice Class Reference
irr::IrrlichtDevice Class Reference abstract
The Irrlicht device. You can create it with createDevice() or createDeviceEx().
#include <IrrlichtDevice.h>
Public Member Functions
virtual bool run ()=0
Runs the device.
virtual void yield ()=0
Cause the device to temporarily pause execution and let other processes run.
virtual void sleep (u32 timeMs, bool pauseTimer=false)=0
Pause execution and let other processes to run for a specified amount of time.
virtual video::IVideoDriver * getVideoDriver ()=0
Provides access to the video driver for drawing 3d and 2d geometry.
virtual io::IFileSystem * getFileSystem ()=0
Provides access to the virtual file system.
virtual gui::IGUIEnvironment * getGUIEnvironment ()=0
Provides access to the 2d user interface environment.
virtual scene::ISceneManager * getSceneManager ()=0
Provides access to the scene manager.
virtual gui::ICursorControl * getCursorControl ()=0
Provides access to the cursor control.
virtual ILogger * getLogger ()=0
Provides access to the message logger.
virtual video::IContextManager * getContextManager ()=0
Get context manager.
virtual IOSOperator * getOSOperator ()=0
Provides access to the operation system operator object.
virtual ITimer * getTimer ()=0
Provides access to the engine's timer.
virtual void setWindowCaption (const wchar_t *text)=0
Sets the caption of the window.
virtual bool setWindowIcon (const video::IImage *img)=0
Sets the window icon.
virtual bool isWindowActive () const =0
Returns if the window is active.
virtual bool isWindowFocused () const =0
Checks if the Irrlicht window has the input focus.
virtual bool isWindowMinimized () const =0
Checks if the Irrlicht window is minimized.
virtual bool isWindowMaximized () const =0
virtual bool isFullscreen () const =0
Checks if the Irrlicht window is running in fullscreen mode.
virtual video::ECOLOR_FORMAT getColorFormat () const =0
Get the current color format of the window.
virtual void closeDevice ()=0
Notifies the device that it should close itself.
virtual const c8 * getVersion () const =0
Get the version of the engine.
virtual void setEventReceiver (IEventReceiver *receiver)=0
Sets a new user event receiver which will receive events from the engine.
virtual IEventReceiver * getEventReceiver ()=0
Provides access to the current event receiver.
virtual bool postEventFromUser (const SEvent &event)=0
Sends a user created event to the engine.
virtual void setInputReceivingSceneManager (scene::ISceneManager *sceneManager)=0
Sets the input receiving scene manager.
virtual void setResizable (bool resize=false)=0
Sets if the window should be resizable in windowed mode.
virtual void setWindowSize (const irr::core::dimension2d< u32 > &size)=0
Resize the render window.
virtual void minimizeWindow ()=0
Minimizes the window if possible.
virtual void maximizeWindow ()=0
Maximizes the window if possible.
virtual void restoreWindow ()=0
Restore the window to normal size if possible.
virtual core::position2di getWindowPosition ()=0
Get the position of the frame on-screen.
virtual bool activateJoysticks (core::array< SJoystickInfo > &joystickInfo)=0
Activate any joysticks, and generate events for them.
virtual bool activateAccelerometer (float updateInterval=0.016666f)=0
Activate accelerometer.
virtual bool deactivateAccelerometer ()=0
Deactivate accelerometer.
virtual bool isAccelerometerActive ()=0
Is accelerometer active.
virtual bool isAccelerometerAvailable ()=0
Is accelerometer available.
virtual bool activateGyroscope (float updateInterval=0.016666f)=0
Activate gyroscope.
virtual bool deactivateGyroscope ()=0
Deactivate gyroscope.
virtual bool isGyroscopeActive ()=0
Is gyroscope active.
virtual bool isGyroscopeAvailable ()=0
Is gyroscope available.
virtual bool activateDeviceMotion (float updateInterval=0.016666f)=0
Activate device motion.
virtual bool deactivateDeviceMotion ()=0
Deactivate device motion.
virtual bool isDeviceMotionActive ()=0
Is device motion active.
virtual bool isDeviceMotionAvailable ()=0
Is device motion available.
virtual void setDoubleClickTime (u32 timeMs)=0
Set the maximal elapsed time between 2 clicks to generate doubleclicks for the mouse. It also affects tripleclick behavior.
virtual u32 getDoubleClickTime () const =0
Get the maximal elapsed time between 2 clicks to generate double- and tripleclicks for the mouse.
virtual void clearSystemMessages ()=0
Remove messages pending in the system message loop.
virtual E_DEVICE_TYPE getType () const =0
Get the type of the device.
virtual float getDisplayDensity () const =0
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Static Public Member Functions
static bool isDriverSupported (video::E_DRIVER_TYPE driver)
Check if a driver type is supported by the engine.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
The Irrlicht device. You can create it with createDevice() or createDeviceEx().
This is the most important class of the Irrlicht Engine. You can access everything in the engine if you have a pointer to an instance of this class. There should be only one instance of this class at any time.
Definition at line 47 of file IrrlichtDevice.h.
Member Function Documentation
activateJoysticks()
virtual bool irr::IrrlichtDevice::activateJoysticks (core::array< SJoystickInfo > & joystickInfo) pure virtual
Activate any joysticks, and generate events for them.
Irrlicht contains support for joysticks, but does not generate joystick events by default, as this would consume joystick info that 3rd party libraries might rely on. Call this method to activate joystick support in Irrlicht and to receive irr::SJoystickEvent events.
Parameters
joystickInfo On return, this will contain an array of each joystick that was found and activated.
Returns
true if joysticks are supported on this device, false if joysticks are not supported or support is compiled out.
Implemented in irr::CIrrDeviceStub.
clearSystemMessages()
virtual void irr::IrrlichtDevice::clearSystemMessages () pure virtual
Remove messages pending in the system message loop.
This function is usually used after messages have been buffered for a longer time, for example when loading a large scene. Clearing the message loop prevents that mouse- or buttonclicks which users have pressed in the meantime will now trigger unexpected actions in the gui.
So far the following messages are cleared:
Win32: All keyboard and mouse messages
Linux: All keyboard and mouse messages
All other devices are not yet supported here.
The function is still somewhat experimental, as the kind of messages we clear is based on just a few use-cases. If you think further messages should be cleared, or some messages should not be cleared here, then please tell us.
Implemented in irr::CIrrDeviceStub.
closeDevice()
virtual void irr::IrrlichtDevice::closeDevice () pure virtual
Notifies the device that it should close itself.
IrrlichtDevice::run() will always return false after closeDevice() was called.
getColorFormat()
virtual video::ECOLOR_FORMAT irr::IrrlichtDevice::getColorFormat () const pure virtual
Get the current color format of the window.
Returns
Color format of the window.
Implemented in irr::CIrrDeviceStub.
getCursorControl()
virtual gui::ICursorControl* irr::IrrlichtDevice::getCursorControl () pure virtual
Provides access to the cursor control.
Returns
Pointer to the mouse cursor control interface.
Implemented in irr::CIrrDeviceStub.
Referenced by GUIHyperText::OnEvent().
getDisplayDensity()
virtual float irr::IrrlichtDevice::getDisplayDensity () const pure virtual
Get the display density in dots per inch. Returns 0.0f on failure.
Implemented in irr::CIrrDeviceStub.
getDoubleClickTime()
virtual u32 irr::IrrlichtDevice::getDoubleClickTime () const pure virtual
Get the maximal elapsed time between 2 clicks to generate double- and tripleclicks for the mouse.
When return value is 0 no double- and tripleclicks will be generated.
Returns
maximal time in milliseconds for two consecutive clicks to be recognized as double click
Implemented in irr::CIrrDeviceStub.
getEventReceiver()
virtual IEventReceiver* irr::IrrlichtDevice::getEventReceiver () pure virtual
Provides access to the current event receiver.
Returns
Pointer to the current event receiver. Returns 0 if there is none.
Implemented in irr::CIrrDeviceStub.
getFileSystem()
virtual io::IFileSystem* irr::IrrlichtDevice::getFileSystem () pure virtual
Provides access to the virtual file system.
Returns
Pointer to the file system.
Implemented in irr::CIrrDeviceStub.
getGUIEnvironment()
virtual gui::IGUIEnvironment* irr::IrrlichtDevice::getGUIEnvironment () pure virtual
Provides access to the 2d user interface environment.
Returns
Pointer to the gui environment.
Implemented in irr::CIrrDeviceStub.
Referenced by DrawHUD::run().
getLogger()
virtual ILogger* irr::IrrlichtDevice::getLogger () pure virtual
Provides access to the message logger.
Returns
Pointer to the logger.
Implemented in irr::CIrrDeviceStub.
getOSOperator()
virtual IOSOperator* irr::IrrlichtDevice::getOSOperator () pure virtual
Provides access to the operation system operator object.
The OS operator provides methods for getting system specific information and doing system specific operations, such as exchanging data with the clipboard or reading the operation system version.
Returns
Pointer to the OS operator.
Implemented in irr::CIrrDeviceStub.
getSceneManager()
virtual scene::ISceneManager* irr::IrrlichtDevice::getSceneManager () pure virtual
Provides access to the scene manager.
Returns
Pointer to the scene manager.
Implemented in irr::CIrrDeviceStub.
Referenced by Draw3D::run(), and RenderShadowMapStep::run().
getTimer()
virtual ITimer* irr::IrrlichtDevice::getTimer () pure virtual
Provides access to the engine's timer.
The system time can be retrieved by it as well as the virtual time, which also can be manipulated.
Returns
Pointer to the ITimer object.
Implemented in irr::CIrrDeviceStub.
Referenced by RenderShadowMapStep::run().
getType()
virtual E_DEVICE_TYPE irr::IrrlichtDevice::getType () const pure virtual
Get the type of the device.
This allows the user to check which windowing system is currently being used.
getVersion()
virtual const c8* irr::IrrlichtDevice::getVersion () const pure virtual
Get the version of the engine.
The returned string will look like this: "1.2.3" or this: "1.2".
Returns
String which contains the version.
Implemented in irr::CIrrDeviceStub.
getVideoDriver()
virtual video::IVideoDriver* irr::IrrlichtDevice::getVideoDriver () pure virtual
Provides access to the video driver for drawing 3d and 2d geometry.
Returns
Pointer the video driver.
Implemented in irr::CIrrDeviceStub.
Referenced by ClearDepthBufferTarget::activate(), ConfigureOverrideMaterialTarget::activate(), TextureBufferOutput::activate(), ScreenTarget::activate(), ScreenTarget::reset(), SetColorMaskStep::run(), DrawImageStep::run(), Draw3D::run(), PostProcessingStep::run(), and UpscaleStep::run().
isDriverSupported()
static bool irr::IrrlichtDevice::isDriverSupported (video::E_DRIVER_TYPE driver) inline static
Check if a driver type is supported by the engine.
Even if true is returned the driver may not be available for a configuration requested when creating the device.
Definition at line 322 of file IrrlichtDevice.h.
isFullscreen()
virtual bool irr::IrrlichtDevice::isFullscreen () const pure virtual
Checks if the Irrlicht window is running in fullscreen mode.
Returns
True if window is fullscreen.
Implemented in irr::CIrrDeviceStub.
isWindowActive()
virtual bool irr::IrrlichtDevice::isWindowActive () const pure virtual
Returns if the window is active.
If the window is inactive, nothing needs to be drawn. So if you don't want to draw anything when the window is inactive, create your drawing loop this way:
while(device->run())
{
    if (device->isWindowActive())
    {
        // draw everything here
    }
    else
        device->yield();
}
Returns
True if window is active.
isWindowFocused()
virtual bool irr::IrrlichtDevice::isWindowFocused () const pure virtual
Checks if the Irrlicht window has the input focus.
Returns
True if window has focus.
Referenced by GUIEngine::run().
isWindowMaximized()
virtual bool irr::IrrlichtDevice::isWindowMaximized () const pure virtual
Checks if the Irrlicht window is maximized Only fully works on SDL. Returns false, or the last value set via maximizeWindow() and restoreWindow(), on other backends.
Returns
True if window is maximized.
Implemented in irr::CIrrDeviceStub.
isWindowMinimized()
virtual bool irr::IrrlichtDevice::isWindowMinimized () const pure virtual
Checks if the Irrlicht window is minimized.
Returns
True if window is minimized.
postEventFromUser()
virtual bool irr::IrrlichtDevice::postEventFromUser (const SEvent & event) pure virtual
Sends a user created event to the engine.
Is is usually not necessary to use this. However, if you are using an own input library for example for doing joystick input, you can use this to post key or mouse input events to the engine. Internally, this method only delegates the events further to the scene manager and the GUI environment.
Implemented in irr::CIrrDeviceStub.
run()
virtual bool irr::IrrlichtDevice::run () pure virtual
Runs the device.
Also increments the virtual timer by calling ITimer::tick();. You can prevent this by calling ITimer::stop(); before and ITimer::start() after calling IrrlichtDevice::run(). Returns false if device wants to be deleted. Use it in this way:
while(device->run())
{
    // draw everything here
}
If you want the device to do nothing if the window is inactive (recommended), use the slightly enhanced code shown at isWindowActive().
Note if you are running Irrlicht inside an external, custom created window: Calling Device->run() will cause Irrlicht to dispatch windows messages internally. If you are running Irrlicht in your own custom window, you can also simply use your own message loop using GetMessage, DispatchMessage and whatever and simply don't use this method. But note that Irrlicht will not be able to fetch user input then. See irr::SIrrlichtCreationParameters::WindowId for more information and example code.
setDoubleClickTime()
virtual void irr::IrrlichtDevice::setDoubleClickTime (u32 timeMs) pure virtual
Set the maximal elapsed time between 2 clicks to generate doubleclicks for the mouse. It also affects tripleclick behavior.
When set to 0 no double- and tripleclicks will be generated.
Parameters
timeMs maximal time in milliseconds for two consecutive clicks to be recognized as double click
Implemented in irr::CIrrDeviceStub.
setEventReceiver()
virtual void irr::IrrlichtDevice::setEventReceiver (IEventReceiver * receiver) pure virtual
Sets a new user event receiver which will receive events from the engine.
Return true in IEventReceiver::OnEvent to prevent the event from continuing along the chain of event receivers. The path that an event takes through the system depends on its type. See irr::EEVENT_TYPE for details.
Parameters
receiver New receiver to be used.
Implemented in irr::CIrrDeviceStub.
setInputReceivingSceneManager()
virtual void irr::IrrlichtDevice::setInputReceivingSceneManager (scene::ISceneManager * sceneManager) pure virtual
Sets the input receiving scene manager.
If set to null, the main scene manager (returned by GetSceneManager()) will receive the input
Parameters
sceneManager New scene manager to be used.
Implemented in irr::CIrrDeviceStub.
setResizable()
virtual void irr::IrrlichtDevice::setResizable (bool resize = false) pure virtual
Sets if the window should be resizable in windowed mode.
The default is false. This method only works in windowed mode.
Parameters
resize Flag whether the window should be resizable.
setWindowCaption()
virtual void irr::IrrlichtDevice::setWindowCaption (const wchar_t * text) pure virtual
Sets the caption of the window.
Parameters
text New text of the window caption.
setWindowIcon()
virtual bool irr::IrrlichtDevice::setWindowIcon (const video::IImage * img) pure virtual
Sets the window icon.
Parameters
img The icon texture.
Returns
False if no icon was set.
Implemented in irr::CIrrDeviceStub.
setWindowSize()
virtual void irr::IrrlichtDevice::setWindowSize (const irr::core::dimension2d< u32 > & size) pure virtual
Resize the render window.
This will only work in windowed mode and is not yet supported on all systems. It does set the drawing/clientDC size of the window, the window decorations are added to that. You get the current window size with IVideoDriver::getScreenSize() (might be unified in future)
Implemented in irr::CIrrDeviceStub.
sleep()
virtual void irr::IrrlichtDevice::sleep (u32 timeMs, bool pauseTimer = false) pure virtual
Pause execution and let other processes to run for a specified amount of time.
It may not wait the full given time, as sleep may be interrupted
Parameters
timeMs Time to sleep for in milliseconds.
pauseTimer If true, pauses the device timer while sleeping
Referenced by GUIEngine::cloudPostProcess().
yield()
virtual void irr::IrrlichtDevice::yield () pure virtual
Cause the device to temporarily pause execution and let other processes run.
This should bring down processor usage without major performance loss for Irrlicht
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IrrlichtDevice.h