Three Cubes Game: irr::gui::CGUISpriteBank Class Reference
irr::gui::CGUISpriteBank Class Reference
Sprite bank interface.
#include <CGUISpriteBank.h>
Classes
struct SDrawBatch
Public Member Functions
CGUISpriteBank (IGUIEnvironment *env)
core::array< core::rect< s32 > > & getPositions () override
Returns the list of rectangles held by the sprite bank.
core::array< SGUISprite > & getSprites () override
Returns the array of animated sprites within the sprite bank.
u32 getTextureCount () const override
Returns the number of textures held by the sprite bank.
video::ITexture * getTexture (u32 index) const override
Gets the texture with the specified index.
void addTexture (video::ITexture *texture) override
Adds a texture to the sprite bank.
void setTexture (u32 index, video::ITexture *texture) override
Changes one of the textures in the sprite bank.
s32 addTextureAsSprite (video::ITexture *texture) override
Add the texture and use it for a single non-animated sprite.
void clear () override
clears sprites, rectangles and textures
virtual void draw2DSprite (u32 index, const core::position2di &pos, const core::rect< s32 > *clip=0, const video::SColor &color=video::SColor(255, 255, 255, 255), u32 starttime=0, u32 currenttime=0, bool loop=true, bool center=false) override
Draws a sprite in 2d with position and color.
virtual void draw2DSprite (u32 index, const core::rect< s32 > &destRect, const core::rect< s32 > *clip=0, const video::SColor *const colors=0, u32 timeTicks=0, bool loop=true) override
Draws a sprite in 2d with destination rectangle and colors.
virtual void draw2DSpriteBatch (const core::array< u32 > &indices, const core::array< core::position2di > &pos, const core::rect< s32 > *clip=0, const video::SColor &color=video::SColor(255, 255, 255, 255), u32 starttime=0, u32 currenttime=0, bool loop=true, bool center=false) override
Draws a sprite batch in 2d using an array of positions and a color.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Protected Member Functions
bool getFrameNr (u32 &frameNr, u32 index, u32 time, bool loop) const
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
core::array< SGUISprite > Sprites
core::array< core::rect< s32 > > Rectangles
core::array< video::ITexture * > Textures
IGUIEnvironment * Environment
video::IVideoDriver * Driver
Detailed Description
Sprite bank interface.
Definition at line 25 of file CGUISpriteBank.h.
Member Function Documentation
clear()
void irr::gui::CGUISpriteBank::clear () override virtual
clears sprites, rectangles and textures
clear everything
Implements irr::gui::IGUISpriteBank.
Definition at line 94 of file CGUISpriteBank.cpp.
References irr::core::array< T >::clear(), and irr::core::array< T >::size().
draw2DSprite()
void irr::gui::CGUISpriteBank::draw2DSprite (u32 index, const core::position2di & pos, const core::rect< s32 > * clip = 0, const video::SColor & color = video::SColor(255,255,255,255), u32 starttime = 0, u32 currenttime = 0, bool loop = true, bool center = false) override virtual
Draws a sprite in 2d with position and color.
draws a sprite in 2d with scale and color
Implements irr::gui::IGUISpriteBank.
Definition at line 156 of file CGUISpriteBank.cpp.
References irr::video::IVideoDriver::draw2DImage(), irr::core::rect< T >::getSize(), and getTexture().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CGUISpriteBank.h
lib/irrlichtmt/source/Irrlicht/CGUISpriteBank.cpp