Three Cubes Game: irr::core::ustring16::_ustring16_iterator_access Class Reference
irr::core::ustring16::_ustring16_iterator_access Class Reference
Access an element in a unicode string, allowing one to change it.
#include <irrUString.h>
Public Member Functions
_ustring16_iterator_access (const ustring16 *s, u32 p)
operator uchar32_t () const
Allow the class to be interpreted as a single UTF-32 character.
_ustring16_iterator_access & operator= (const uchar32_t c)
_ustring16_iterator_access & operator++ ()
uchar32_t operator++ (int)
_ustring16_iterator_access & operator-- ()
uchar32_t operator-- (int)
_ustring16_iterator_access & operator+= (int val)
_ustring16_iterator_access & operator-= (int val)
_ustring16_iterator_access & operator*= (int val)
_ustring16_iterator_access & operator/= (int val)
_ustring16_iterator_access & operator%= (int val)
uchar32_t operator+ (int val) const
uchar32_t operator- (int val) const
uchar32_t operator* (int val) const
uchar32_t operator/ (int val) const
uchar32_t operator% (int val) const
Private Member Functions
uchar32_t _get () const
Gets a uchar32_t from our current position.
void _set (uchar32_t c)
Sets a uchar32_t at our current position.
Private Attributes
const ustring16 * ref
u32 pos
Detailed Description
Access an element in a unicode string, allowing one to change it.
---------------—/// iterator classes /// ---------------—///
Definition at line 238 of file irrUString.h.
Member Function Documentation
operator%()
uchar32_t irr::core::ustring16::_ustring16_iterator_access::operator% (int val) const inline
Modulos the value by a specified amount.
Parameters
val The amount to modulo this character by.
Returns
A unicode character.
Definition at line 372 of file irrUString.h.
References _get().
operator%=()
_ustring16_iterator_access& irr::core::ustring16::_ustring16_iterator_access::operator%= (int val) inline
Modulos the value by a specified amount.
Parameters
val The amount to modulo this character by.
Returns
Myself.
Definition at line 331 of file irrUString.h.
References _get(), and _set().
operator*()
uchar32_t irr::core::ustring16::_ustring16_iterator_access::operator* (int val) const inline
Multiplies the value by a specified amount.
Parameters
val The amount to multiply this character by.
Returns
A unicode character.
Definition at line 356 of file irrUString.h.
References _get().
operator*=()
_ustring16_iterator_access& irr::core::ustring16::_ustring16_iterator_access::operator*= (int val) inline
Multiples the value by a specified amount.
Parameters
val The amount to multiply this character by.
Returns
Myself.
Definition at line 313 of file irrUString.h.
References _get(), and _set().
operator+()
uchar32_t irr::core::ustring16::_ustring16_iterator_access::operator+ (int val) const inline
Adds to the value by a specified amount.
Parameters
val The amount to add to this character.
Returns
A unicode character.
Definition at line 340 of file irrUString.h.
References _get().
operator++() [1/2]
_ustring16_iterator_access& irr::core::ustring16::_ustring16_iterator_access::operator++ () inline
Increments the value by 1.
Returns
Myself.
Definition at line 260 of file irrUString.h.
References _get(), and _set().
operator++() [2/2]
uchar32_t irr::core::ustring16::_ustring16_iterator_access::operator++ (int) inline
Increments the value by 1, returning the old value.
Returns
A unicode character.
Definition at line 268 of file irrUString.h.
References _get(), and _set().
operator+=()
_ustring16_iterator_access& irr::core::ustring16::_ustring16_iterator_access::operator+= (int val) inline
Adds to the value by a specified amount.
Parameters
val The amount to add to this character.
Returns
Myself.
Definition at line 295 of file irrUString.h.
References _get(), and _set().
operator-()
uchar32_t irr::core::ustring16::_ustring16_iterator_access::operator- (int val) const inline
Subtracts from the value by a specified amount.
Parameters
val The amount to subtract from this character.
Returns
A unicode character.
Definition at line 348 of file irrUString.h.
References _get().
operator--() [1/2]
_ustring16_iterator_access& irr::core::ustring16::_ustring16_iterator_access::operator-- () inline
Decrements the value by 1.
Returns
Myself.
Definition at line 277 of file irrUString.h.
References _get(), and _set().
operator--() [2/2]
uchar32_t irr::core::ustring16::_ustring16_iterator_access::operator-- (int) inline
Decrements the value by 1, returning the old value.
Returns
A unicode character.
Definition at line 285 of file irrUString.h.
References _get(), and _set().
operator-=()
_ustring16_iterator_access& irr::core::ustring16::_ustring16_iterator_access::operator-= (int val) inline
Subtracts from the value by a specified amount.
Parameters
val The amount to subtract from this character.
Returns
Myself.
Definition at line 304 of file irrUString.h.
References _get(), and _set().
operator/()
uchar32_t irr::core::ustring16::_ustring16_iterator_access::operator/ (int val) const inline
Divides the value by a specified amount.
Parameters
val The amount to divide this character by.
Returns
A unicode character.
Definition at line 364 of file irrUString.h.
References _get().
operator/=()
_ustring16_iterator_access& irr::core::ustring16::_ustring16_iterator_access::operator/= (int val) inline
Divides the value by a specified amount.
Parameters
val The amount to divide this character by.
Returns
Myself.
Definition at line 322 of file irrUString.h.
References _get(), and _set().
operator=()
_ustring16_iterator_access& irr::core::ustring16::_ustring16_iterator_access::operator= (const uchar32_t c) inline
Allow one to change the character in the unicode string.
Parameters
c The new character to use.
Returns
Myself.
Definition at line 252 of file irrUString.h.
References _set().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/irrUString.h