Three Cubes Game: irr::video::COpenGL3Renderer2D Class Reference
irr::video::COpenGL3Renderer2D Class Reference
Public Member Functions
COpenGL3Renderer2D (const c8 *vertexShaderProgram, const c8 *pixelShaderProgram, COpenGL3DriverBase *driver, bool withTexture)
virtual void OnSetMaterial (const SMaterial &material, const SMaterial &lastMaterial, bool resetAllRenderstates, IMaterialRendererServices *services)
Called by the IVideoDriver implementation the let the renderer set its needed render states.
virtual bool OnRender (IMaterialRendererServices *service, E_VERTEX_TYPE vtxtype)
Called every time before a new bunch of geometry is being drawn using this material with for example drawIndexedTriangleList() call.
Public Member Functions inherited from irr::video::COpenGL3MaterialRenderer
COpenGL3MaterialRenderer (COpenGL3DriverBase *driver, s32 &outMaterialTypeNr, const c8 *vertexShaderProgram=0, const c8 *pixelShaderProgram=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=EMT_SOLID, s32 userData=0)
GLuint getProgram () const
virtual void OnUnsetMaterial ()
Called by the IVideoDriver to unset this material.
virtual bool isTransparent () const
Returns if the material is transparent.
virtual s32 getRenderCapability () const
Returns the render capability of the material.
void setBasicRenderStates (const SMaterial &material, const SMaterial &lastMaterial, bool resetAllRenderstates) override
Can be called by an IMaterialRenderer to make its work easier.
s32 getVertexShaderConstantID (const c8 *name) override
Return an index constant for the vertex shader based on a name.
s32 getPixelShaderConstantID (const c8 *name) override
Return an index constant for the pixel shader based on a name.
void setVertexShaderConstant (const f32 *data, s32 startRegister, s32 constantAmount=1) override
Sets a vertex shader constant.
void setPixelShaderConstant (const f32 *data, s32 startRegister, s32 constantAmount=1) override
Sets a pixel shader constant.
bool setVertexShaderConstant (s32 index, const f32 *floats, int count) override
Sets a constant for the vertex shader based on a name.
bool setVertexShaderConstant (s32 index, const s32 *ints, int count) override
Int interface for the above.
bool setVertexShaderConstant (s32 index, const u32 *ints, int count) override
Uint interface for the above.
bool setPixelShaderConstant (s32 index, const f32 *floats, int count) override
Sets a constant for the pixel shader based on a name.
bool setPixelShaderConstant (s32 index, const s32 *ints, int count) override
Int interface for the above.
bool setPixelShaderConstant (s32 index, const u32 *ints, int count) override
Uint interface for the above.
IVideoDriver * getVideoDriver () override
Get pointer to the IVideoDriver interface.
Public Member Functions inherited from irr::video::IMaterialRenderer
virtual IShaderConstantSetCallBack * getShaderConstantSetCallBack () const
Access the callback provided by the users when creating shader materials.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::video::IMaterialRendererServices
virtual ~IMaterialRendererServices ()
Destructor.
_IRR_DEPRECATED_ bool setVertexShaderConstant (const c8 *name, const f32 *floats, int count)
_IRR_DEPRECATED_ bool setVertexShaderConstant (const c8 *name, const s32 *ints, int count)
_IRR_DEPRECATED_ bool setPixelShaderConstant (const c8 *name, const f32 *floats, int count)
_IRR_DEPRECATED_ bool setPixelShaderConstant (const c8 *name, const s32 *ints, int count)
Protected Attributes
bool WithTexture
s32 ThicknessID
s32 TextureUsageID
Protected Attributes inherited from irr::video::COpenGL3MaterialRenderer
COpenGL3DriverBase * Driver
IShaderConstantSetCallBack * CallBack
bool Alpha
bool Blending
bool FixedBlending
GLuint Program
core::array< SUniformInfo > UniformInfo
s32 UserData
Additional Inherited Members
Protected Member Functions inherited from irr::video::COpenGL3MaterialRenderer
COpenGL3MaterialRenderer (COpenGL3DriverBase *driver, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=EMT_SOLID, s32 userData=0)
void init (s32 &outMaterialTypeNr, const c8 *vertexShaderProgram, const c8 *pixelShaderProgram, bool addMaterial=true)
bool createShader (GLenum shaderType, const char *shader)
bool linkProgram ()
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Definition at line 14 of file Renderer2D.h.
Member Function Documentation
OnRender()
bool irr::video::COpenGL3Renderer2D::OnRender (IMaterialRendererServices * service, E_VERTEX_TYPE vtxtype) virtual
Called every time before a new bunch of geometry is being drawn using this material with for example drawIndexedTriangleList() call.
OnSetMaterial should normally only be called if the renderer decides that the renderstates should be changed, it won't be called if for example two drawIndexedTriangleList() will be called with the same material set. This method will be called every time. This is useful for example for materials with shaders, which don't only set new renderstates but also shader constants.
Parameters
service Pointer to interface providing methods for setting constants and other things.
vtxtype Vertex type with which the next rendering will be done. This can be used by the material renderer to set some specific optimized shaders or if this is an incompatible vertex type for this renderer, to refuse rendering for example.
Returns
Returns true if everything is OK, and false if nothing should be rendered. The material renderer can choose to return false for example if he doesn't support the specified vertex type. This is actually done in D3D9 when using a normal mapped material with a vertex type other than EVT_TANGENTS.
Reimplemented from irr::video::COpenGL3MaterialRenderer.
Definition at line 77 of file Renderer2D.cpp.
Referenced by irr::video::COpenGL3DriverBase::setRenderStates2DMode().
OnSetMaterial()
void irr::video::COpenGL3Renderer2D::OnSetMaterial (const SMaterial & material, const SMaterial & lastMaterial, bool resetAllRenderstates, video::IMaterialRendererServices * services) virtual
Called by the IVideoDriver implementation the let the renderer set its needed render states.
This is called during the IVideoDriver::setMaterial() call. When overriding this, you can set some renderstates or for example a vertex or pixel shader if you like.
Parameters
material The new material parameters to be set. The renderer may change the material flags in this material. For example if this material does not accept the zbuffer = true, it can set it to false. This is useful, because in the next lastMaterial will be just the material in this call.
lastMaterial The material parameters which have been set before this material.
resetAllRenderstates True if all renderstates should really be reset. This is usually true if the last rendering mode was not a usual 3d rendering mode, but for example a 2d rendering mode. You should reset really all renderstates if this is true, no matter if the lastMaterial had some similar settings. This is used because in most cases, some common renderstates are not changed if they are already there, for example bilinear filtering, wireframe, gouraudshading, lighting, zbuffer, zwriteenable, backfaceculling and fogenable.
services Interface providing some methods for changing advanced, internal states of a IVideoDriver.
Reimplemented from irr::video::COpenGL3MaterialRenderer.
Definition at line 59 of file Renderer2D.cpp.
References irr::video::COpenGL3DriverBase::setBasicRenderStates(), irr::video::COpenGL3MaterialRenderer::setPixelShaderConstant(), irr::video::SMaterialLayer::Texture, irr::video::SMaterial::TextureLayer, and irr::video::SMaterial::Thickness.
Referenced by irr::video::COpenGL3DriverBase::setRenderStates2DMode().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/OpenGL/Renderer2D.h
lib/irrlichtmt/source/Irrlicht/OpenGL/Renderer2D.cpp