Three Cubes Game: irr::gui::CGUIImageList Class Reference
irr::gui::CGUIImageList Class Reference
Public Member Functions
CGUIImageList (video::IVideoDriver *Driver)
constructor
virtual ~CGUIImageList ()
destructor
bool createImageList (video::ITexture *texture, core::dimension2d< s32 > imageSize, bool useAlphaChannel)
Creates the image list from texture.
virtual void draw (s32 index, const core::position2d< s32 > &destPos, const core::rect< s32 > *clip=0) override
Draws an image and clips it to the specified rectangle if wanted.
s32 getImageCount () const override
core::dimension2d< s32 > getImageSize () const override
Public Member Functions inherited from irr::gui::IGUIImageList
virtual ~IGUIImageList ()
Destructor.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Attributes
video::IVideoDriver * Driver
video::ITexture * Texture
s32 ImageCount
core::dimension2d< s32 > ImageSize
s32 ImagesPerRow
bool UseAlphaChannel
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Definition at line 15 of file CGUIImageList.h.
Member Function Documentation
createImageList()
bool irr::gui::CGUIImageList::createImageList (video::ITexture * texture, core::dimension2d< s32 > imageSize, bool useAlphaChannel)
Creates the image list from texture.
Creates the image list from texture.
Parameters
texture The texture to use
imageSize Size of a single image
useAlphaChannel true if the alpha channel from the texture should be used
Returns
true if the image list was created
Definition at line 50 of file CGUIImageList.cpp.
References irr::video::ITexture::getSize(), irr::IReferenceCounted::grab(), irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
Referenced by irr::gui::CGUIEnvironment::createImageList().
draw()
void irr::gui::CGUIImageList::draw (s32 index, const core::position2d< s32 > & destPos, const core::rect< s32 > * clip = 0) override virtual
Draws an image and clips it to the specified rectangle if wanted.
Draws an image and clips it to the specified rectangle if wanted
Parameters
index Index of the image
destPos Position of the image to draw
clip Optional pointer to a rectangle against which the text will be clipped. If the pointer is null, no clipping will be done.
Implements irr::gui::IGUIImageList.
Definition at line 73 of file CGUIImageList.cpp.
References irr::video::IVideoDriver::draw2DImage(), irr::core::dimension2d< T >::Height, irr::core::rect< T >::LowerRightCorner, irr::core::rect< T >::UpperLeftCorner, and irr::core::dimension2d< T >::Width.
getImageCount()
s32 irr::gui::CGUIImageList::getImageCount () const inline override virtual
Returns the count of Images in the list.
Returns
Returns the count of Images in the list.
Implements irr::gui::IGUIImageList.
Definition at line 45 of file CGUIImageList.h.
getImageSize()
core::dimension2d<s32> irr::gui::CGUIImageList::getImageSize () const inline override virtual
Returns the size of the images in the list.
Returns
Returns the size of the images in the list.
Implements irr::gui::IGUIImageList.
Definition at line 50 of file CGUIImageList.h.
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CGUIImageList.h
lib/irrlichtmt/source/Irrlicht/CGUIImageList.cpp