Three Cubes Game: irr::video::COpenGLCoreTexture< TOpenGLDriver > Class Template Reference
irr::video::COpenGLCoreTexture< TOpenGLDriver > Class Template Reference
Classes
struct SStatesCache
Public Member Functions
COpenGLCoreTexture (const io::path &name, const core::array< IImage * > &images, E_TEXTURE_TYPE type, TOpenGLDriver *driver)
COpenGLCoreTexture (const io::path &name, const core::dimension2d< u32 > &size, E_TEXTURE_TYPE type, ECOLOR_FORMAT format, TOpenGLDriver *driver)
void * lock (E_TEXTURE_LOCK_MODE mode=ETLM_READ_WRITE, u32 mipmapLevel=0, u32 layer=0, E_TEXTURE_LOCK_FLAGS lockFlags=ETLF_FLIP_Y_UP_RTT) override
Lock function.
void unlock () override
Unlock function. Must be called after a lock() to the texture.
void regenerateMipMapLevels (void *data=0, u32 layer=0) override
Regenerates the mip map levels of the texture.
GLenum getOpenGLTextureType () const
GLuint getOpenGLTextureName () const
SStatesCache & getStatesCache () const
Public Member Functions inherited from irr::video::ITexture
ITexture (const io::path &name, E_TEXTURE_TYPE type)
constructor
const core::dimension2d< u32 > & getOriginalSize () const
Get original size of the texture.
const core::dimension2d< u32 > & getSize () const
Get dimension (=size) of the texture.
E_DRIVER_TYPE getDriverType () const
Get driver type of texture.
ECOLOR_FORMAT getColorFormat () const
Get the color format of texture.
ECOLOR_FORMAT getOriginalColorFormat () const
Get the original color format.
u32 getPitch () const
Get pitch of the main texture (in bytes).
bool hasMipMaps () const
Check whether the texture has MipMaps.
bool isRenderTarget () const
Check whether the texture is a render target.
const io::SNamedPath & getName () const
Get name of texture (in most cases this is the filename)
E_TEXTURE_SOURCE getSource () const
Check where the last IVideoDriver::getTexture found this texture.
void updateSource (E_TEXTURE_SOURCE source)
Used internally by the engine to update Source status on IVideoDriver::getTexture calls.
bool hasAlpha () const
Returns if the texture has an alpha channel.
E_TEXTURE_TYPE getType () const
Returns the type of texture.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Protected Member Functions
void * getLockImageData (irr::u32 miplevel) const
ECOLOR_FORMAT getBestColorFormat (ECOLOR_FORMAT format)
void getImageValues (const IImage *image)
void uploadTexture (bool initTexture, u32 layer, u32 level, void *data)
GLenum TextureTypeIrrToGL (E_TEXTURE_TYPE type) const
Protected Member Functions inherited from irr::video::ITexture
E_TEXTURE_CREATION_FLAG getTextureFormatFromFlags (u32 flags)
Helper function, helps to get the desired texture creation format from the flags.
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
TOpenGLDriver * Driver
GLenum TextureType
GLuint TextureName
GLint InternalFormat
GLenum PixelFormat
GLenum PixelType
void(* Converter)(const void *, s32, void *)
bool LockReadOnly
IImage * LockImage
u32 LockLayer
bool KeepImage
core::array< IImage * > Images
u8 MipLevelStored
bool LegacyAutoGenerateMipMaps
SStatesCache StatesCache
Protected Attributes inherited from irr::video::ITexture
io::SNamedPath NamedPath
core::dimension2d< u32 > OriginalSize
core::dimension2d< u32 > Size
E_DRIVER_TYPE DriverType
ECOLOR_FORMAT OriginalColorFormat
ECOLOR_FORMAT ColorFormat
u32 Pitch
bool HasMipMaps
bool IsRenderTarget
E_TEXTURE_SOURCE Source
E_TEXTURE_TYPE Type
Detailed Description
template<class TOpenGLDriver>
class irr::video::COpenGLCoreTexture< TOpenGLDriver >
Definition at line 28 of file COpenGLCoreTexture.h.
Member Function Documentation
lock()
template<class TOpenGLDriver > void* irr::video::COpenGLCoreTexture< TOpenGLDriver >::lock (E_TEXTURE_LOCK_MODE mode = ETLM_READ_WRITE, u32 mipmapLevel = 0, u32 layer = 0, E_TEXTURE_LOCK_FLAGS lockFlags = ETLF_FLIP_Y_UP_RTT) inline override virtual
Lock function.
Locks the Texture and returns a pointer to access the pixels. After lock() has been called and all operations on the pixels are done, you must call unlock(). Locks are not accumulating, hence one unlock will do for an arbitrary number of previous locks. You should avoid locking different levels without unlocking in between, though, because only the last level locked will be unlocked. The size of the i-th mipmap level is defined as max(getSize().Width>>i,1) and max(getSize().Height>>i,1)
Parameters
mode Specifies what kind of changes to the locked texture are allowed. Unspecified behavior will arise if texture is written in read only mode or read from in write only mode. Support for this feature depends on the driver, so don't rely on the texture being write-protected when locking with read-only, etc.
mipmapLevel NOTE: Currently broken, sorry, we try if we can repair it for 1.9 release. Number of the mipmapLevel to lock. 0 is main texture. Non-existing levels will silently fail and return 0.
layer It determines which cubemap face or texture array layer should be locked.
lockFlags See E_TEXTURE_LOCK_FLAGS documentation.
Returns
Returns a pointer to the pixel data. The format of the pixel can be determined by using getColorFormat(). 0 is returned, if the texture cannot be locked.
Implements irr::video::ITexture.
Definition at line 234 of file COpenGLCoreTexture.h.
References irr::IReferenceCounted::drop(), irr::video::ECF_A1R5G5B5, irr::video::ECF_A8R8G8B8, irr::video::ECF_R5G6B5, irr::video::ECF_R8G8B8, irr::video::ETLF_FLIP_Y_UP_RTT, irr::video::ETLM_READ_ONLY, irr::video::ETLM_WRITE_ONLY, irr::video::ETT_2D, irr::core::dimension2d< T >::getArea(), irr::video::IImage::getData(), irr::video::IImage::getDimension(), irr::video::IImage::getMipMapsSize(), irr::video::IImage::getPitch(), irr::IReferenceCounted::grab(), irr::core::dimension2d< T >::Height, irr::video::IImage::isCompressedFormat(), and irr::core::dimension2d< T >::Width.
regenerateMipMapLevels()
template<class TOpenGLDriver > void irr::video::COpenGLCoreTexture< TOpenGLDriver >::regenerateMipMapLevels (void * data = 0, u32 layer = 0) inline override virtual
Regenerates the mip map levels of the texture.
Required after modifying the texture, usually after calling unlock().
Parameters
data Optional parameter to pass in image data which will be used instead of the previously stored or automatically generated mipmap data. The data has to be a continuous pixel data for all mipmaps until 1x1 pixel. Each mipmap has to be half the width and height of the previous level. At least one pixel will be always kept.
layer It informs a texture about which cubemap or texture array layer needs mipmap regeneration.
Implements irr::video::ITexture.
Definition at line 398 of file COpenGLCoreTexture.h.
References irr::video::IImage::getDataSizeFromFormat(), irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
unlock()
template<class TOpenGLDriver > void irr::video::COpenGLCoreTexture< TOpenGLDriver >::unlock () inline override virtual
Unlock function. Must be called after a lock() to the texture.
One should avoid to call unlock more than once before another lock. The last locked mip level will be unlocked. You may want to call regenerateMipMapLevels() after this when you changed any data.
Implements irr::video::ITexture.
Definition at line 376 of file COpenGLCoreTexture.h.
References irr::IReferenceCounted::drop().
The documentation for this class was generated from the following file:
lib/irrlichtmt/source/Irrlicht/COpenGLCoreTexture.h