Three Cubes Game: irr::scene::CSceneManager Class Reference
irr::scene::CSceneManager Class Reference
#include <CSceneManager.h>
Classes
struct DefaultNodeEntry
struct DistanceNodeEntry
sort on distance (sphere) to camera
struct TransparentNodeEntry
sort on distance (center) to camera
Public Member Functions
CSceneManager (video::IVideoDriver *driver, gui::ICursorControl *cursorControl, IMeshCache *cache=0)
constructor
virtual ~CSceneManager ()
destructor
IAnimatedMesh * getMesh (io::IReadFile *file) override
gets an animateable mesh. loads it if needed. returned pointer must not be dropped.
IMeshCache * getMeshCache () override
Returns an interface to the mesh cache which is shared between all existing scene managers.
video::IVideoDriver * getVideoDriver () override
returns the video driver
virtual IAnimatedMeshSceneNode * addAnimatedMeshSceneNode (IAnimatedMesh *mesh, ISceneNode *parent=0, s32 id=-1, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f), bool alsoAddIfMeshPointerZero=false) override
adds a scene node for rendering an animated mesh model
virtual IMeshSceneNode * addMeshSceneNode (IMesh *mesh, ISceneNode *parent=0, s32 id=-1, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f), bool alsoAddIfMeshPointerZero=false) override
void render () override
renders the node.
const core::aabbox3d< f32 > & getBoundingBox () const override
returns the axis aligned bounding box of this node
u32 registerNodeForRendering (ISceneNode *node, E_SCENE_NODE_RENDER_PASS pass=ESNRP_AUTOMATIC) override
registers a node for rendering it at a specific time.
void clearAllRegisteredNodesForRendering () override
Clear all nodes which are currently registered for rendering.
void drawAll () override
draws all scene nodes
virtual ICameraSceneNode * addCameraSceneNode (ISceneNode *parent=0, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &lookat=core::vector3df(0, 0, 100), s32 id=-1, bool makeActive=true) override
virtual IBillboardSceneNode * addBillboardSceneNode (ISceneNode *parent=0, const core::dimension2d< f32 > &size=core::dimension2d< f32 >(10.0f, 10.0f), const core::vector3df &position=core::vector3df(0, 0, 0), s32 id=-1, video::SColor shadeTop=0xFFFFFFFF, video::SColor shadeBottom=0xFFFFFFFF) override
virtual IDummyTransformationSceneNode * addDummyTransformationSceneNode (ISceneNode *parent=0, s32 id=-1) override
Adds a dummy transformation scene node to the scene graph.
ISceneNode * addEmptySceneNode (ISceneNode *parent, s32 id=-1) override
Adds an empty scene node.
ISceneNode * getRootSceneNode () override
ICameraSceneNode * getActiveCamera () const override
void setActiveCamera (ICameraSceneNode *camera) override
void addExternalMeshLoader (IMeshLoader *externalLoader) override
Adds an external mesh loader.
u32 getMeshLoaderCount () const override
Returns the number of mesh loaders supported by Irrlicht at this time.
IMeshLoader * getMeshLoader (u32 index) const override
Retrieve the given mesh loader.
ISceneCollisionManager * getSceneCollisionManager () override
Returns a pointer to the scene collision manager.
IMeshManipulator * getMeshManipulator () override
Returns a pointer to the mesh manipulator.
void addToDeletionQueue (ISceneNode *node) override
Adds a scene node to the deletion queue.
ISceneNode * getSceneNodeFromId (s32 id, ISceneNode *start=0) override
Returns the first scene node with the specified id.
ISceneNode * getSceneNodeFromName (const c8 *name, ISceneNode *start=0) override
Returns the first scene node with the specified name.
ISceneNode * getSceneNodeFromType (scene::ESCENE_NODE_TYPE type, ISceneNode *start=0) override
Returns the first scene node with the specified type.
void getSceneNodesFromType (ESCENE_NODE_TYPE type, core::array< scene::ISceneNode * > &outNodes, ISceneNode *start=0) override
returns scene nodes by type.
bool postEventFromUser (const SEvent &event) override
void clear () override
Clears the whole scene. All scene nodes are removed.
void removeAll () override
Removes all children of this scene node.
io::IAttributes * getParameters () override
Returns interface to the parameters set in this scene.
E_SCENE_NODE_RENDER_PASS getSceneNodeRenderPass () const override
Returns current render pass.
ISceneManager * createNewSceneManager (bool cloneContent) override
Creates a new scene manager.
ESCENE_NODE_TYPE getType () const override
Returns type of the scene node.
IMeshWriter * createMeshWriter (EMESH_WRITER_TYPE type) override
Returns a mesh writer implementation if available.
ISkinnedMesh * createSkinnedMesh () override
Get a skinned mesh, which is not available as header-only code.
void setAmbientLight (const video::SColorf &ambientColor) override
Sets ambient color of the scene.
const video::SColorf & getAmbientLight () const override
Returns ambient color of the scene.
E_SCENE_NODE_RENDER_PASS getCurrentRenderPass () const override
Get current render time.
void setCurrentRenderPass (E_SCENE_NODE_RENDER_PASS nextPass) override
Set current render time.
bool isCulled (const ISceneNode *node) const override
returns if node is culled
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::scene::ISceneNode
ISceneNode (ISceneNode *parent, ISceneManager *mgr, s32 id=-1, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f))
Constructor.
virtual ~ISceneNode ()
Destructor.
virtual void OnRegisterSceneNode ()
This method is called just before the rendering process of the whole scene.
virtual void OnAnimate (u32 timeMs)
OnAnimate() is called just before rendering the whole scene.
virtual const c8 * getName () const
Returns the name of the node.
virtual void setName (const c8 *name)
Sets the name of the node.
virtual void setName (const core::stringc &name)
Sets the name of the node.
virtual const core::aabbox3d< f32 > getTransformedBoundingBox () const
Get the axis aligned, transformed and animated absolute bounding box of this node.
virtual void getTransformedBoundingBoxEdges (core::array< core::vector3d< f32 > > &edges) const
virtual const core::matrix4 & getAbsoluteTransformation () const
Get the absolute transformation of the node. Is recalculated every OnAnimate()-call.
virtual core::matrix4 getRelativeTransformation () const
Returns the relative transformation of the scene node.
virtual bool isVisible () const
Returns whether the node should be visible (if all of its parents are visible).
virtual bool isTrulyVisible () const
Check whether the node is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool isVisible)
Sets if the node should be visible or not.
virtual s32 getID () const
Get the id of the scene node.
virtual void setID (s32 id)
Sets the id of the scene node.
virtual void addChild (ISceneNode *child)
Adds a child to this scene node.
virtual bool removeChild (ISceneNode *child)
Removes a child from this scene node.
virtual void remove ()
Removes this scene node from the scene.
virtual video::SMaterial & getMaterial (u32 num)
Returns the material based on the zero based index i.
virtual u32 getMaterialCount () const
Get amount of materials used by this scene node.
void setMaterialFlag (video::E_MATERIAL_FLAG flag, bool newvalue)
Sets all material flags at once to a new value.
void setMaterialTexture (u32 textureLayer, video::ITexture *texture)
Sets the texture of the specified layer in all materials of this scene node to the new texture.
void setMaterialType (video::E_MATERIAL_TYPE newType)
Sets the material type of all materials in this scene node to a new material type.
virtual const core::vector3df & getScale () const
Gets the scale of the scene node relative to its parent.
virtual void setScale (const core::vector3df &scale)
Sets the relative scale of the scene node.
virtual const core::vector3df & getRotation () const
Gets the rotation of the node relative to its parent.
virtual void setRotation (const core::vector3df &rotation)
Sets the rotation of the node relative to its parent.
virtual const core::vector3df & getPosition () const
Gets the position of the node relative to its parent.
virtual void setPosition (const core::vector3df &newpos)
Sets the position of the node relative to its parent.
virtual core::vector3df getAbsolutePosition () const
Gets the absolute position of the node in world coordinates.
void setAutomaticCulling (u32 state)
Set a culling style or disable culling completely.
u32 getAutomaticCulling () const
Gets the automatic culling state.
virtual void setDebugDataVisible (u32 state)
Sets if debug data like bounding boxes should be drawn.
u32 isDebugDataVisible () const
Returns if debug data like bounding boxes are drawn.
void setIsDebugObject (bool debugObject)
Sets if this scene node is a debug object.
bool isDebugObject () const
Returns if this scene node is a debug object.
const std::list< ISceneNode * > & getChildren () const
Returns a const reference to the list of all children.
virtual void setParent (ISceneNode *newParent)
Changes the parent of the scene node.
virtual void updateAbsolutePosition ()
Updates the absolute position based on the relative and the parents position.
scene::ISceneNode * getParent () const
Returns the parent of this scene node.
virtual ISceneNode * clone (ISceneNode *newParent=0, ISceneManager *newManager=0)
Creates a clone of this scene node and its children.
virtual ISceneManager * getSceneManager (void) const
Retrieve the scene manager for this node.
Private Member Functions
IAnimatedMesh * getUncachedMesh (io::IReadFile *file, const io::path &filename, const io::path &cachename)
void clearDeletionList ()
clears the deletion list
Private Attributes
video::IVideoDriver * Driver
video driver
gui::ICursorControl * CursorControl
cursor control
ISceneCollisionManager * CollisionManager
collision manager
core::array< ISceneNode * > CameraList
render pass lists
core::array< ISceneNode * > SkyBoxList
core::array< DefaultNodeEntry > SolidNodeList
core::array< TransparentNodeEntry > TransparentNodeList
core::array< TransparentNodeEntry > TransparentEffectNodeList
core::array< ISceneNode * > GuiNodeList
core::array< IMeshLoader * > MeshLoaderList
core::array< ISceneNode * > DeletionList
ICameraSceneNode * ActiveCamera
current active camera
core::vector3df camWorldPos
video::SColor ShadowColor
video::SColorf AmbientLight
io::CAttributes * Parameters
String parameters.
IMeshCache * MeshCache
Mesh cache.
E_SCENE_NODE_RENDER_PASS CurrentRenderPass
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Member Functions inherited from irr::scene::ISceneNode
void cloneMembers (ISceneNode *toCopyFrom, ISceneManager *newManager)
A clone function for the ISceneNode members.
void setSceneManager (ISceneManager *newManager)
Protected Attributes inherited from irr::scene::ISceneNode
core::stringc Name
Name of the scene node.
core::matrix4 AbsoluteTransformation
Absolute transformation of the node.
core::vector3df RelativeTranslation
Relative translation of the scene node.
core::vector3df RelativeRotation
Relative rotation of the scene node.
core::vector3df RelativeScale
Relative scale of the scene node.
ISceneNode * Parent
Pointer to the parent.
std::list< ISceneNode * > Children
List of all children of this node.
ISceneManager * SceneManager
Pointer to the scene manager.
s32 ID
ID of the node.
u32 AutomaticCullingState
Automatic culling state.
u32 DebugDataVisible
Flag if debug data should be drawn, such as Bounding Boxes.
bool IsVisible
Is the node visible?
bool IsDebugObject
Is debug object?
Detailed Description
The Scene Manager manages scene nodes, mesh resources, cameras and all the other stuff.
Definition at line 29 of file CSceneManager.h.
Constructor & Destructor Documentation
~CSceneManager()
irr::scene::CSceneManager::~CSceneManager () virtual
destructor
force to remove hardwareTextures from the driver because Scenes may hold internally data bounded to sceneNodes which may be destroyed twice
Definition at line 82 of file CSceneManager.cpp.
References ActiveCamera, clearDeletionList(), CollisionManager, CursorControl, Driver, irr::IReferenceCounted::drop(), MeshCache, Parameters, removeAll(), and irr::video::IVideoDriver::removeAllHardwareBuffers().
Member Function Documentation
addBillboardSceneNode()
IBillboardSceneNode * irr::scene::CSceneManager::addBillboardSceneNode (ISceneNode * parent = 0, const core::dimension2d< f32 > & size = core::dimension2d<f32>(10.0f, 10.0f), const core::vector3df & position = core::vector3df(0,0,0), s32 id = -1, video::SColor colorTop = 0xFFFFFFFF, video::SColor colorBottom = 0xFFFFFFFF) override virtual
Adds a billboard scene node to the scene. A billboard is like a 3d sprite: A 2d element, which always looks to the camera. It is usually used for things like explosions, fire, lensflares and things like that.
Implements irr::scene::ISceneManager.
Definition at line 240 of file CSceneManager.cpp.
References irr::IReferenceCounted::drop().
addCameraSceneNode()
ICameraSceneNode * irr::scene::CSceneManager::addCameraSceneNode (ISceneNode * parent = 0, const core::vector3df & position = core::vector3df(0,0,0), const core::vector3df & lookat = core::vector3df(0,0,100), s32 id = -1, bool makeActive = true) override virtual
Adds a camera scene node to the tree and sets it as active camera.
Parameters
position Position of the space relative to its parent where the camera will be placed.
lookat Position where the camera will look at. Also known as target.
parent Parent scene node of the camera. Can be null. If the parent moves, the camera will move too.
Returns
Pointer to interface to camera
Adds a camera scene node to the tree and sets it as active camera.
Parameters
position Position of the space relative to its parent where the camera will be placed.
lookat Position where the camera will look at. Also known as target.
parent Parent scene node of the camera. Can be null. If the parent moves, the camera will move too.
Returns
Returns pointer to interface to camera
Implements irr::scene::ISceneManager.
Definition at line 220 of file CSceneManager.cpp.
References irr::IReferenceCounted::drop(), and setActiveCamera().
addMeshSceneNode()
IMeshSceneNode * irr::scene::CSceneManager::addMeshSceneNode (IMesh * mesh, ISceneNode * parent = 0, s32 id = -1, const core::vector3df & position = core::vector3df(0,0,0), const core::vector3df & rotation = core::vector3df(0,0,0), const core::vector3df & scale = core::vector3df(1.0f, 1.0f, 1.0f), bool alsoAddIfMeshPointerZero = false) override virtual
adds a scene node for rendering a static mesh the returned pointer must not be dropped.
Implements irr::scene::ISceneManager.
Definition at line 178 of file CSceneManager.cpp.
References irr::IReferenceCounted::drop().
drawAll()
void irr::scene::CSceneManager::drawAll () override virtual
draws all scene nodes
This method is called just before the rendering process of the whole scene. draws all scene nodes
First Scene Node for prerendering should be the active camera consistent Camera is needed for culling
Implements irr::scene::ISceneManager.
Definition at line 515 of file CSceneManager.cpp.
References ActiveCamera, irr::scene::ALLOW_ZWRITE_ON_TRANSPARENT, CameraList, clearDeletionList(), Driver, irr::video::SOverrideMaterial::Enabled, irr::video::SOverrideMaterial::EnablePasses, irr::scene::ESNRP_CAMERA, irr::scene::ESNRP_GUI, irr::scene::ESNRP_NONE, irr::scene::ESNRP_SKY_BOX, irr::scene::ESNRP_SOLID, irr::scene::ESNRP_TRANSPARENT, irr::scene::ESNRP_TRANSPARENT_EFFECT, irr::video::ETS_COUNT, irr::video::ETS_PROJECTION, irr::video::ETS_TEXTURE_0, irr::video::ETS_VIEW, irr::video::ETS_WORLD, irr::scene::ISceneNode::getAbsolutePosition(), irr::io::CAttributes::getAttributeAsBool(), irr::video::IVideoDriver::getOverrideMaterial(), irr::os::Timer::getTime(), irr::core::IdentityMatrix, irr::scene::ISceneNode::OnAnimate(), irr::scene::ISceneNode::OnRegisterSceneNode(), Parameters, render(), irr::scene::ISceneNode::render(), irr::video::IVideoDriver::setAllowZWriteOnTransparent(), irr::video::IVideoDriver::setMaterial(), and irr::video::IVideoDriver::setTransform().
getActiveCamera()
ICameraSceneNode * irr::scene::CSceneManager::getActiveCamera () const override virtual
Returns the current active camera.
Returns
The active camera is returned. Note that this can be NULL, if there was no camera created yet.
Implements irr::scene::ISceneManager.
Definition at line 298 of file CSceneManager.cpp.
References ActiveCamera.
Referenced by isCulled(), and postEventFromUser().
getRootSceneNode()
ISceneNode * irr::scene::CSceneManager::getRootSceneNode () override virtual
Returns the root scene node. This is the scene node which is parent of all scene nodes. The root scene node is a special scene node which only exists to manage all scene nodes. It is not rendered and cannot be removed from the scene.
Returns
Pointer to the root scene node.
Returns the root scene node. This is the scene node which is parent of all scene nodes. The root scene node is a special scene node which only exists to manage all scene nodes. It is not rendered and cannot be removed from the scene.
Returns
Returns a pointer to the root scene node.
Implements irr::scene::ISceneManager.
Definition at line 289 of file CSceneManager.cpp.
Referenced by getSceneNodeFromId(), getSceneNodeFromName(), getSceneNodeFromType(), and getSceneNodesFromType().
postEventFromUser()
bool irr::scene::CSceneManager::postEventFromUser (const SEvent & event) override virtual
Posts an input event to the environment. Usually you do not have to use this method, it is used by the internal engine.
Implements irr::scene::ISceneManager.
Definition at line 787 of file CSceneManager.cpp.
References getActiveCamera(), and irr::scene::ICameraSceneNode::OnEvent().
setActiveCamera()
void irr::scene::CSceneManager::setActiveCamera (ICameraSceneNode * camera) override virtual
Sets the active camera. The previous active camera will be deactivated.
Parameters
camera The new camera which should be active.
Implements irr::scene::ISceneManager.
Definition at line 306 of file CSceneManager.cpp.
References ActiveCamera, irr::IReferenceCounted::drop(), and irr::IReferenceCounted::grab().
Referenced by addCameraSceneNode(), and removeAll().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CSceneManager.h
lib/irrlichtmt/source/Irrlicht/CSceneManager.cpp