Three Cubes Game: irr::video::COpenGL3MaterialRenderer Class Reference
irr::video::COpenGL3MaterialRenderer Class Reference
Classes
struct SUniformInfo
Public Member Functions
COpenGL3MaterialRenderer (COpenGL3DriverBase *driver, s32 &outMaterialTypeNr, const c8 *vertexShaderProgram=0, const c8 *pixelShaderProgram=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=EMT_SOLID, s32 userData=0)
GLuint getProgram () const
virtual void OnSetMaterial (const SMaterial &material, const SMaterial &lastMaterial, bool resetAllRenderstates, IMaterialRendererServices *services)
Called by the IVideoDriver implementation the let the renderer set its needed render states.
virtual bool OnRender (IMaterialRendererServices *service, E_VERTEX_TYPE vtxtype)
Called every time before a new bunch of geometry is being drawn using this material with for example drawIndexedTriangleList() call.
virtual void OnUnsetMaterial ()
Called by the IVideoDriver to unset this material.
virtual bool isTransparent () const
Returns if the material is transparent.
virtual s32 getRenderCapability () const
Returns the render capability of the material.
void setBasicRenderStates (const SMaterial &material, const SMaterial &lastMaterial, bool resetAllRenderstates) override
Can be called by an IMaterialRenderer to make its work easier.
s32 getVertexShaderConstantID (const c8 *name) override
Return an index constant for the vertex shader based on a name.
s32 getPixelShaderConstantID (const c8 *name) override
Return an index constant for the pixel shader based on a name.
void setVertexShaderConstant (const f32 *data, s32 startRegister, s32 constantAmount=1) override
Sets a vertex shader constant.
void setPixelShaderConstant (const f32 *data, s32 startRegister, s32 constantAmount=1) override
Sets a pixel shader constant.
bool setVertexShaderConstant (s32 index, const f32 *floats, int count) override
Sets a constant for the vertex shader based on a name.
bool setVertexShaderConstant (s32 index, const s32 *ints, int count) override
Int interface for the above.
bool setVertexShaderConstant (s32 index, const u32 *ints, int count) override
Uint interface for the above.
bool setPixelShaderConstant (s32 index, const f32 *floats, int count) override
Sets a constant for the pixel shader based on a name.
bool setPixelShaderConstant (s32 index, const s32 *ints, int count) override
Int interface for the above.
bool setPixelShaderConstant (s32 index, const u32 *ints, int count) override
Uint interface for the above.
IVideoDriver * getVideoDriver () override
Get pointer to the IVideoDriver interface.
Public Member Functions inherited from irr::video::IMaterialRenderer
virtual IShaderConstantSetCallBack * getShaderConstantSetCallBack () const
Access the callback provided by the users when creating shader materials.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::video::IMaterialRendererServices
virtual ~IMaterialRendererServices ()
Destructor.
_IRR_DEPRECATED_ bool setVertexShaderConstant (const c8 *name, const f32 *floats, int count)
_IRR_DEPRECATED_ bool setVertexShaderConstant (const c8 *name, const s32 *ints, int count)
_IRR_DEPRECATED_ bool setPixelShaderConstant (const c8 *name, const f32 *floats, int count)
_IRR_DEPRECATED_ bool setPixelShaderConstant (const c8 *name, const s32 *ints, int count)
Protected Member Functions
COpenGL3MaterialRenderer (COpenGL3DriverBase *driver, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=EMT_SOLID, s32 userData=0)
void init (s32 &outMaterialTypeNr, const c8 *vertexShaderProgram, const c8 *pixelShaderProgram, bool addMaterial=true)
bool createShader (GLenum shaderType, const char *shader)
bool linkProgram ()
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
COpenGL3DriverBase * Driver
IShaderConstantSetCallBack * CallBack
bool Alpha
bool Blending
bool FixedBlending
GLuint Program
core::array< SUniformInfo > UniformInfo
s32 UserData
Detailed Description
Definition at line 23 of file MaterialRenderer.h.
Member Function Documentation
getRenderCapability()
s32 irr::video::COpenGL3MaterialRenderer::getRenderCapability () const virtual
Returns the render capability of the material.
Because some more complex materials are implemented in multiple ways and need special hardware capabilities, it is possible to query how the current material renderer is performing on the current hardware with this function.
Returns
Returns 0 if everything is running fine. Any other value is material renderer specific and means for example that the renderer switched back to a fall back material because it cannot use the latest shaders. More specific examples: Fixed function pipeline materials should return 0 in most cases, parallax mapped material will only return 0 when at least pixel shader 1.4 is available on that machine.
Reimplemented from irr::video::IMaterialRenderer.
Definition at line 202 of file MaterialRenderer.cpp.
getVideoDriver()
IVideoDriver * irr::video::COpenGL3MaterialRenderer::getVideoDriver () override virtual
Get pointer to the IVideoDriver interface.
Returns
Pointer to the IVideoDriver interface
Implements irr::video::IMaterialRendererServices.
Definition at line 475 of file MaterialRenderer.cpp.
isTransparent()
bool irr::video::COpenGL3MaterialRenderer::isTransparent () const virtual
Returns if the material is transparent.
The scene management needs to know this for being able to sort the materials by opaque and transparent.
Reimplemented from irr::video::IMaterialRenderer.
Definition at line 196 of file MaterialRenderer.cpp.
OnRender()
bool irr::video::COpenGL3MaterialRenderer::OnRender (IMaterialRendererServices * service, E_VERTEX_TYPE vtxtype) virtual
Called every time before a new bunch of geometry is being drawn using this material with for example drawIndexedTriangleList() call.
OnSetMaterial should normally only be called if the renderer decides that the renderstates should be changed, it won't be called if for example two drawIndexedTriangleList() will be called with the same material set. This method will be called every time. This is useful for example for materials with shaders, which don't only set new renderstates but also shader constants.
Parameters
service Pointer to interface providing methods for setting constants and other things.
vtxtype Vertex type with which the next rendering will be done. This can be used by the material renderer to set some specific optimized shaders or if this is an incompatible vertex type for this renderer, to refuse rendering for example.
Returns
Returns true if everything is OK, and false if nothing should be rendered. The material renderer can choose to return false for example if he doesn't support the specified vertex type. This is actually done in D3D9 when using a normal mapped material with a vertex type other than EVT_TANGENTS.
Reimplemented from irr::video::IMaterialRenderer.
Reimplemented in irr::video::COpenGL3Renderer2D.
Definition at line 143 of file MaterialRenderer.cpp.
References irr::video::IShaderConstantSetCallBack::OnSetConstants().
OnSetMaterial()
void irr::video::COpenGL3MaterialRenderer::OnSetMaterial (const SMaterial & material, const SMaterial & lastMaterial, bool resetAllRenderstates, video::IMaterialRendererServices * services) virtual
Called by the IVideoDriver implementation the let the renderer set its needed render states.
This is called during the IVideoDriver::setMaterial() call. When overriding this, you can set some renderstates or for example a vertex or pixel shader if you like.
Parameters
material The new material parameters to be set. The renderer may change the material flags in this material. For example if this material does not accept the zbuffer = true, it can set it to false. This is useful, because in the next lastMaterial will be just the material in this call.
lastMaterial The material parameters which have been set before this material.
resetAllRenderstates True if all renderstates should really be reset. This is usually true if the last rendering mode was not a usual 3d rendering mode, but for example a 2d rendering mode. You should reset really all renderstates if this is true, no matter if the lastMaterial had some similar settings. This is used because in most cases, some common renderstates are not changed if they are already there, for example bilinear filtering, wireframe, gouraudshading, lighting, zbuffer, zwriteenable, backfaceculling and fogenable.
services Interface providing some methods for changing advanced, internal states of a IVideoDriver.
Reimplemented from irr::video::IMaterialRenderer.
Reimplemented in irr::video::COpenGL3Renderer2D.
Definition at line 152 of file MaterialRenderer.cpp.
References irr::video::COpenGL3DriverBase::getGLBlend(), irr::video::SMaterial::MaterialTypeParam, irr::video::IShaderConstantSetCallBack::OnSetMaterial(), irr::video::COpenGL3DriverBase::setBasicRenderStates(), and irr::video::unpack_textureBlendFuncSeparate().
OnUnsetMaterial()
void irr::video::COpenGL3MaterialRenderer::OnUnsetMaterial () virtual
Called by the IVideoDriver to unset this material.
Called during the IVideoDriver::setMaterial() call before the new material will get the OnSetMaterial() call.
Reimplemented from irr::video::IMaterialRenderer.
Definition at line 191 of file MaterialRenderer.cpp.
Referenced by irr::video::COpenGL3DriverBase::setRenderStates2DMode(), and irr::video::COpenGL3DriverBase::setRenderStates3DMode().
setBasicRenderStates()
void irr::video::COpenGL3MaterialRenderer::setBasicRenderStates (const SMaterial & material, const SMaterial & lastMaterial, bool resetAllRenderstates) override virtual
Can be called by an IMaterialRenderer to make its work easier.
Sets all basic renderstates if needed. Basic render states are diffuse, ambient, specular, and emissive color, specular power, bilinear and trilinear filtering, wireframe mode, grouraudshading, lighting, zbuffer, zwriteenable, backfaceculling and fog enabling.
Parameters
material The new material to be used.
lastMaterial The material used until now.
resetAllRenderstates Set to true if all renderstates should be set, regardless of their current state.
Implements irr::video::IMaterialRendererServices.
Definition at line 334 of file MaterialRenderer.cpp.
References irr::video::COpenGL3DriverBase::setBasicRenderStates().
setPixelShaderConstant() [1/2]
void irr::video::COpenGL3MaterialRenderer::setPixelShaderConstant (const f32 * data, s32 startRegister, s32 constantAmount = 1) override virtual
Sets a pixel shader constant.
Can be used if you created a shader using pixel/vertex shader assembler or ARB_fragment_program or ARB_vertex_program.
Parameters
data Data to be set in the constants
startRegister First register to be set.
constantAmount Amount of registers to be set. One register consists of 4 floats.
Implements irr::video::IMaterialRendererServices.
Definition at line 362 of file MaterialRenderer.cpp.
References irr::ELL_WARNING.
Referenced by irr::video::COpenGL3Renderer2D::OnSetMaterial(), and setVertexShaderConstant().
setPixelShaderConstant() [2/2]
bool irr::video::COpenGL3MaterialRenderer::setPixelShaderConstant (s32 index, const f32 * floats, int count) override virtual
Sets a constant for the pixel shader based on a name.
This can be used if you used a high level shader language like GLSL or HLSL to create a shader. See setVertexShaderConstant() for an example on how to use this.
Parameters
index Index of the variable
floats Pointer to array of floats
count Amount of floats in array.
Returns
True if successful.
Implements irr::video::IMaterialRendererServices.
Definition at line 382 of file MaterialRenderer.cpp.
setVertexShaderConstant() [1/2]
void irr::video::COpenGL3MaterialRenderer::setVertexShaderConstant (const f32 * data, s32 startRegister, s32 constantAmount = 1) override virtual
Sets a vertex shader constant.
Can be used if you created a shader using pixel/vertex shader assembler or ARB_fragment_program or ARB_vertex_program.
Parameters
data Data to be set in the constants
startRegister First register to be set
constantAmount Amount of registers to be set. One register consists of 4 floats.
Implements irr::video::IMaterialRendererServices.
Definition at line 357 of file MaterialRenderer.cpp.
References irr::ELL_WARNING.
setVertexShaderConstant() [2/2]
bool irr::video::COpenGL3MaterialRenderer::setVertexShaderConstant (s32 index, const f32 * floats, int count) override virtual
Sets a constant for the vertex shader based on a name.
This can be used if you used a high level shader language like GLSL or HLSL to create a shader. Example: If you created a shader which has variables named 'mWorldViewProj' (containing the WorldViewProjection matrix) and another one named 'fTime' containing one float, you can set them in your IShaderConstantSetCallBack derived class like this:
virtual void OnSetConstants(video::IMaterialRendererServices* services, s32 userData)
{
    video::IVideoDriver* driver = services->getVideoDriver();
    f32 time = (f32)os::Timer::getTime()/100000.0f;
    services->setVertexShaderConstant("fTime", &time, 1);
    core::matrix4 worldViewProj(driver->getTransform(video::ETS_PROJECTION));
    worldViewProj *= driver->getTransform(video::ETS_VIEW);
    worldViewProj *= driver->getTransform(video::ETS_WORLD);
    services->setVertexShaderConstant("mWorldViewProj", worldViewProj.M, 16);
}
Parameters
index Index of the variable
floats Pointer to array of floats
count Amount of floats in array.
Returns
True if successful.
Implements irr::video::IMaterialRendererServices.
Definition at line 367 of file MaterialRenderer.cpp.
References setPixelShaderConstant().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/OpenGL/MaterialRenderer.h
lib/irrlichtmt/source/Irrlicht/OpenGL/MaterialRenderer.cpp