Three Cubes Game: AreaStore Class Reference
AreaStore Class Reference abstract
Public Member Functions
virtual void reserve (size_t count)
size_t size () const
virtual bool insertArea (Area *a)=0
virtual bool removeArea (u32 id)=0
void getAreasForPos (std::vector< Area * > *result, v3s16 pos)
virtual void getAreasInArea (std::vector< Area * > *result, v3s16 minedge, v3s16 maxedge, bool accept_overlap)=0
void setCacheParams (bool enabled, u8 block_radius, size_t limit)
Sets cache parameters.
const Area * getArea (u32 id) const
void serialize (std::ostream &is) const
Serializes the store's areas to a binary ostream.
void deserialize (std::istream &is)
Static Public Member Functions
static AreaStore * getOptimalImplementation ()
Protected Types
typedef std::map< u32, Area > AreaMap
Protected Member Functions
void invalidateCache ()
virtual void getAreasForPosImpl (std::vector< Area * > *result, v3s16 pos)=0
u32 getNextId () const
Returns the next area ID and increments it.
Protected Attributes
AreaMap areas_map
Static Private Member Functions
static void cacheMiss (void *data, const v3s16 &mpos, std::vector< Area * > *dest)
Called by the cache when a value isn't found in the cache.
Private Attributes
bool m_cache_enabled = true
u8 m_cacheblock_radius = 64
LRUCache< v3s16, std::vector< Area * > > m_res_cache
Detailed Description
Definition at line 54 of file areastore.h.
Member Function Documentation
deserialize()
void AreaStore::deserialize (std::istream & is)
Deserializes the Areas from a binary istream. This does not currently clear the AreaStore before adding the areas, making it possible to deserialize multiple serialized AreaStores.
Definition at line 89 of file areastore.cpp.
References insertArea().
getArea()
const Area * AreaStore::getArea (u32 id) const
Returns a pointer to the area coresponding to the passed ID, or NULL if it doesn't exist.
Definition at line 57 of file areastore.cpp.
getAreasForPos()
void AreaStore::getAreasForPos (std::vector< Area * > * result, v3s16 pos)
Finds areas that the passed position is contained in. Stores output in passed vector.
Definition at line 168 of file areastore.cpp.
References getAreasForPosImpl(), and m_cacheblock_radius.
getAreasForPosImpl()
virtual void AreaStore::getAreasForPosImpl (std::vector< Area * > * result, v3s16 pos) protected pure virtual
Implementation of getAreasForPos. getAreasForPos calls this if the cache is disabled.
Implemented in VectorAreaStore.
Referenced by getAreasForPos().
getAreasInArea()
virtual void AreaStore::getAreasInArea (std::vector< Area * > * result, v3s16 minedge, v3s16 maxedge, bool accept_overlap) pure virtual
Finds areas that are completely contained inside the area defined by the passed edges. If accept_overlap is true this finds any areas that intersect with the passed area at any point.
Implemented in VectorAreaStore.
Referenced by cacheMiss().
insertArea()
virtual bool AreaStore::insertArea (Area * a) pure virtual
Add an area to the store. Updates the area's ID if it hasn't already been set.
Returns
Whether the area insertion was successful.
Implemented in VectorAreaStore.
Referenced by deserialize().
invalidateCache()
void AreaStore::invalidateCache () protected
Invalidates the getAreasForPos cache. Call after adding or removing an area.
Definition at line 119 of file areastore.cpp.
Referenced by VectorAreaStore::insertArea(), VectorAreaStore::removeArea(), and setCacheParams().
removeArea()
virtual bool AreaStore::removeArea (u32 id) pure virtual
Removes an area from the store by ID.
Returns
Whether the area was in the store and removed.
Implemented in VectorAreaStore.
Member Data Documentation
m_cacheblock_radius
u8 AreaStore::m_cacheblock_radius = 64 private
Range, in nodes, of the getAreasForPos cache. If you modify this, call invalidateCache()
Definition at line 126 of file areastore.h.
Referenced by cacheMiss(), getAreasForPos(), and setCacheParams().
The documentation for this class was generated from the following files:
src/util/areastore.h
src/util/areastore.cpp