Three Cubes Game: DrawImageStep Class Reference
DrawImageStep Class Reference
Public Member Functions
DrawImageStep (u8 texture_index, v2f offset)
void setRenderSource (RenderSource *_source) override
void setRenderTarget (RenderTarget *_target) override
void reset (PipelineContext &context) override
void run (PipelineContext &context) override
Private Attributes
u8 texture_index
v2f offset
RenderSource * source
RenderTarget * target
Detailed Description
Definition at line 24 of file sidebyside.h.
Member Function Documentation
run()
void DrawImageStep::run (PipelineContext & context) override virtual
Runs the step. This method is invoked by the pipeline.
Implements RenderStep.
Definition at line 38 of file sidebyside.cpp.
References RenderTarget::activate(), irr::video::IVideoDriver::draw2DImage(), irr::video::IVideoDriver::getScreenSize(), RenderSource::getTexture(), irr::IrrlichtDevice::getVideoDriver(), irr::core::dimension2d< T >::Height, irr::core::dimension2d< T >::Width, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
setRenderSource()
void DrawImageStep::setRenderSource (RenderSource * source) override virtual
Assigns render source to this step.
Parameters
source source of rendering information
Implements RenderStep.
Definition at line 29 of file sidebyside.cpp.
setRenderTarget()
void DrawImageStep::setRenderTarget (RenderTarget * target) override virtual
Assigned render target to this step.
Parameters
target render target to send output to.
Implements RenderStep.
Definition at line 33 of file sidebyside.cpp.
The documentation for this class was generated from the following files:
src/client/render/sidebyside.h
src/client/render/sidebyside.cpp