Three Cubes Game: irr_ptr< ReferenceCounted, class > Class Template Reference
irr_ptr< ReferenceCounted, class > Class Template Reference
#include <irr_ptr.h>
Public Member Functions
irr_ptr (std::nullptr_t) noexcept
irr_ptr (const irr_ptr &b) noexcept
irr_ptr (irr_ptr &&b) noexcept
template<typename B , class = typename std::enable_if<std::is_convertible<B *, ReferenceCounted *>::value>::type>
irr_ptr (const irr_ptr< B > &b) noexcept
template<typename B , class = typename std::enable_if<std::is_convertible<B *, ReferenceCounted *>::value>::type>
irr_ptr (irr_ptr< B > &&b) noexcept
irr_ptr (ReferenceCounted *object) noexcept
irr_ptr & operator= (const irr_ptr &b) noexcept
irr_ptr & operator= (irr_ptr &&b) noexcept
template<typename B , class = typename std::enable_if<std::is_convertible<B *, ReferenceCounted *>::value>::type>
irr_ptr & operator= (const irr_ptr< B > &b) noexcept
template<typename B , class = typename std::enable_if<std::is_convertible<B *, ReferenceCounted *>::value>::type>
irr_ptr & operator= (irr_ptr< B > &&b) noexcept
ReferenceCounted & operator* () const noexcept
ReferenceCounted * operator-> () const noexcept
operator ReferenceCounted * () const noexcept
operator bool () const noexcept
ReferenceCounted * get () const noexcept
ReferenceCounted * release () noexcept
void reset (ReferenceCounted *object=nullptr) noexcept
void grab (ReferenceCounted *object) noexcept
Private Attributes
ReferenceCounted * value = nullptr
Detailed Description
template<class ReferenceCounted, class = typename std::enable_if<std::is_base_of<IReferenceCounted, ReferenceCounted>::value>::type>
class irr_ptr< ReferenceCounted, class >
Shared pointer for IrrLicht objects.
It should only be used for user-managed objects, i.e. those created with the new operator or create* functions, like: irr_ptr<scene::IMeshBuffer> buf{new scene::SMeshBuffer()}; The reference counting is not balanced as new objects have reference count set to one, and the irr_ptr constructor (and reset) assumes ownership of that reference.
It shouldn’t be used for engine-managed objects, including those created with addTexture and similar methods. Constructing irr_ptr directly from such object is a bug and may lead to a crash. Indirect construction is possible though; see the grab free function for details and use cases.
Definition at line 43 of file irr_ptr.h.
Constructor & Destructor Documentation
irr_ptr()
template<class ReferenceCounted , class = typename std::enable_if<std::is_base_of<IReferenceCounted, ReferenceCounted>::value>::type> irr_ptr< ReferenceCounted, class >::irr_ptr (ReferenceCounted * object) inline explicit noexcept
Constructs a shared pointer out of a plain one to control object lifetime.
Parameters
object The object, usually returned by some create* function.
Note
Move semantics: reference counter is not increased.
Warning
Never wrap any add* function with this!
Definition at line 75 of file irr_ptr.h.
Member Function Documentation
get()
template<class ReferenceCounted , class = typename std::enable_if<std::is_base_of<IReferenceCounted, ReferenceCounted>::value>::type> ReferenceCounted* irr_ptr< ReferenceCounted, class >::get () const inline noexcept
Returns the stored pointer.
Definition at line 114 of file irr_ptr.h.
Referenced by GUIButtonImage::GUIButtonImage().
grab()
template<class ReferenceCounted , class = typename std::enable_if<std::is_base_of<IReferenceCounted, ReferenceCounted>::value>::type> void irr_ptr< ReferenceCounted, class >::grab (ReferenceCounted * object) inline noexcept
Drops stored pointer replacing it with the given one.
Note
Copy semantics: reference counter is increased.
Definition at line 139 of file irr_ptr.h.
release()
template<class ReferenceCounted , class = typename std::enable_if<std::is_base_of<IReferenceCounted, ReferenceCounted>::value>::type> ReferenceCounted* irr_ptr< ReferenceCounted, class >::release () inline noexcept
Returns the stored pointer, erasing it from this class.
Note
Move semantics: reference counter is not changed.
Definition at line 119 of file irr_ptr.h.
reset()
template<class ReferenceCounted , class = typename std::enable_if<std::is_base_of<IReferenceCounted, ReferenceCounted>::value>::type> void irr_ptr< ReferenceCounted, class >::reset (ReferenceCounted * object = nullptr) inline noexcept
Drops stored pointer replacing it with the given one.
Note
Move semantics: reference counter is not increased.
Definition at line 129 of file irr_ptr.h.
Referenced by irr_ptr< GUIAnimatedImage >::grab(), GUIEngine::GUIEngine(), irr_ptr< GUIAnimatedImage >::irr_ptr(), and GUIEngine::~GUIEngine().
The documentation for this class was generated from the following file:
src/irr_ptr.h