Three Cubes Game: irr::scene::CMeshManipulator Class Reference
irr::scene::CMeshManipulator Class Reference
An interface for easy manipulation of meshes.
#include <CMeshManipulator.h>
Public Member Functions
void recalculateNormals (scene::IMesh *mesh, bool smooth=false, bool angleWeighted=false) const override
Recalculates all normals of the mesh.
void recalculateNormals (IMeshBuffer *buffer, bool smooth=false, bool angleWeighted=false) const override
Recalculates all normals of the mesh buffer.
SMesh * createMeshCopy (scene::IMesh *mesh) const override
Clones a static IMesh into a modifiable SMesh.
s32 getPolyCount (scene::IMesh *mesh) const override
Returns amount of polygons in mesh.
s32 getPolyCount (scene::IAnimatedMesh *mesh) const override
Returns amount of polygons in mesh.
IAnimatedMesh * createAnimatedMesh (scene::IMesh *mesh, scene::E_ANIMATED_MESH_TYPE type) const override
create a new AnimatedMesh and adds the mesh to it
Public Member Functions inherited from irr::scene::IMeshManipulator
void scale (IMesh *mesh, const core::vector3df &factor) const
Scales the actual mesh, not a scene node.
void scale (IMeshBuffer *buffer, const core::vector3df &factor) const
Scales the actual meshbuffer, not a scene node.
template<typename Functor >
bool apply (const Functor &func, IMeshBuffer *buffer, bool boundingBoxUpdate=false) const
Apply a manipulator on the Meshbuffer.
template<typename Functor >
bool apply (const Functor &func, IMesh *mesh, bool boundingBoxUpdate=false) const
Apply a manipulator on the Mesh.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Additional Inherited Members
Protected Member Functions inherited from irr::scene::IMeshManipulator
template<typename Functor >
bool apply_ (const Functor &func, IMeshBuffer *buffer, bool boundingBoxUpdate, const IVertexManipulator &typeTest) const
Apply a manipulator based on the type of the functor.
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
An interface for easy manipulation of meshes.
Scale, set alpha value, flip surfaces, and so on. This exists for fixing problems with wrong imported or exported meshes quickly after loading. It is not intended for doing mesh modifications and/or animations during runtime.
Definition at line 20 of file CMeshManipulator.h.
Member Function Documentation
createMeshCopy()
SMesh * irr::scene::CMeshManipulator::createMeshCopy (scene::IMesh * mesh) const override virtual
Clones a static IMesh into a modifiable SMesh.
Clones a static IMesh into a modifyable SMesh.
Implements irr::scene::IMeshManipulator.
Definition at line 132 of file CMeshManipulator.cpp.
References irr::scene::SMesh::addMeshBuffer(), irr::scene::SMesh::BoundingBox, irr::IReferenceCounted::drop(), irr::video::EVT_2TCOORDS, irr::video::EVT_STANDARD, irr::video::EVT_TANGENTS, irr::scene::IMesh::getBoundingBox(), irr::scene::IMeshBuffer::getIndexCount(), irr::scene::IMeshBuffer::getIndices(), irr::scene::IMeshBuffer::getMaterial(), irr::scene::IMesh::getMeshBuffer(), irr::scene::IMesh::getMeshBufferCount(), irr::scene::IMeshBuffer::getVertexCount(), irr::scene::IMeshBuffer::getVertexType(), irr::scene::IMeshBuffer::getVertices(), irr::scene::CMeshBuffer< T >::Indices, irr::scene::CMeshBuffer< T >::Material, irr::core::array< T >::push_back(), irr::core::array< T >::reallocate(), and irr::scene::CMeshBuffer< T >::Vertices.
recalculateNormals() [1/2]
void irr::scene::CMeshManipulator::recalculateNormals (IMeshBuffer * buffer, bool smooth = false, bool angleWeighted = false) const override virtual
Recalculates all normals of the mesh buffer.
Parameters
buffer Mesh buffer on which the operation is performed.
smooth Whether to use smoothed normals.
buffer Mesh buffer on which the operation is performed.
Implements irr::scene::IMeshManipulator.
Definition at line 93 of file CMeshManipulator.cpp.
References irr::scene::IMeshBuffer::getIndexType().
recalculateNormals() [2/2]
void irr::scene::CMeshManipulator::recalculateNormals (scene::IMesh * mesh, bool smooth = false, bool angleWeighted = false) const override virtual
Recalculates all normals of the mesh.
Parameters
mesh Mesh on which the operation is performed.
smooth Whether to use smoothed normals.
Recalculates all normals of the mesh.
Parameters
mesh Mesh on which the operation is performed.
Implements irr::scene::IMeshManipulator.
Definition at line 107 of file CMeshManipulator.cpp.
References irr::scene::EAMT_SKINNED, irr::scene::IMesh::getMeshBuffer(), irr::scene::IMesh::getMeshBufferCount(), irr::scene::IMesh::getMeshType(), irr::scene::ISkinnedMesh::refreshJointCache(), and irr::scene::ISkinnedMesh::resetAnimation().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CMeshManipulator.h
lib/irrlichtmt/source/Irrlicht/CMeshManipulator.cpp