Three Cubes Game: irr::gui::CGUIEditBox Class Reference
irr::gui::CGUIEditBox Class Reference
Public Member Functions
CGUIEditBox (const wchar_t *text, bool border, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle)
constructor
virtual ~CGUIEditBox ()
destructor
void setOverrideFont (IGUIFont *font=0) override
Sets another skin independent font.
IGUIFont * getOverrideFont () const override
Gets the override font (if any)
IGUIFont * getActiveFont () const override
Get the font which is used right now for drawing.
void setOverrideColor (video::SColor color) override
Sets another color for the text.
video::SColor getOverrideColor () const override
Gets the override color.
void enableOverrideColor (bool enable) override
Sets if the text should use the override color or the color in the gui skin.
bool isOverrideColorEnabled (void) const override
Checks if an override color is enabled.
void setDrawBackground (bool draw) override
Sets whether to draw the background.
bool isDrawBackgroundEnabled () const override
Checks if background drawing is enabled.
void setDrawBorder (bool border) override
Turns the border on or off.
bool isDrawBorderEnabled () const override
Checks if border drawing is enabled.
void setWordWrap (bool enable) override
Enables or disables word wrap for using the edit box as multiline text editor.
bool isWordWrapEnabled () const override
Checks if word wrap is enabled.
void setMultiLine (bool enable) override
Enables or disables newlines.
bool isMultiLineEnabled () const override
Checks if multi line editing is enabled.
void setAutoScroll (bool enable) override
bool isAutoScrollEnabled () const override
core::dimension2du getTextDimension () override
void setTextAlignment (EGUI_ALIGNMENT horizontal, EGUI_ALIGNMENT vertical) override
Sets text justification.
bool OnEvent (const SEvent &event) override
called if an event happened.
void draw () override
draws the element and its children
void setText (const wchar_t *text) override
Sets the new caption of this element.
void setMax (u32 max) override
u32 getMax () const override
Returns maximum amount of characters, previously set by setMax();.
void setCursorChar (const wchar_t cursorChar) override
Set the character used for the cursor.
wchar_t getCursorChar () const override
Get the character used for the cursor.
void setCursorBlinkTime (irr::u32 timeMs) override
Set the blinktime for the cursor. 2x blinktime is one full cycle.
irr::u32 getCursorBlinkTime () const override
Get the cursor blinktime.
void setPasswordBox (bool passwordBox, wchar_t passwordChar=L' *') override
Sets whether the edit box is a password box. Setting this to true will.
bool isPasswordBox () const override
Returns true if the edit box is currently a password box.
void updateAbsolutePosition () override
Updates the absolute position, splits text if required.
bool acceptsIME () override
Returns whether the element takes input from the IME.
Public Member Functions inherited from irr::gui::IGUIEditBox
IGUIEditBox (IGUIEnvironment *environment, IGUIElement *parent, s32 id, core::rect< s32 > rectangle)
constructor
Public Member Functions inherited from irr::gui::IGUIElement
IGUIElement (EGUI_ELEMENT_TYPE type, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle)
Constructor.
virtual ~IGUIElement ()
Destructor.
IGUIElement * getParent () const
Returns parent of this element.
core::rect< s32 > getRelativePosition () const
Returns the relative rectangle of this element.
void setRelativePosition (const core::rect< s32 > &r)
Sets the relative rectangle of this element.
void setRelativePosition (const core::position2di &position)
Sets the relative rectangle of this element, maintaining its current width and height.
void setRelativePositionProportional (const core::rect< f32 > &r)
Sets the relative rectangle of this element as a proportion of its parent's area.
core::rect< s32 > getAbsolutePosition () const
Gets the absolute rectangle of this element.
core::rect< s32 > getAbsoluteClippingRect () const
Returns the visible area of the element.
void setNotClipped (bool noClip)
Sets whether the element will ignore its parent's clipping rectangle.
bool isNotClipped () const
Gets whether the element will ignore its parent's clipping rectangle.
void setMaxSize (core::dimension2du size)
Sets the maximum size allowed for this element.
void setMinSize (core::dimension2du size)
Sets the minimum size allowed for this element.
void setAlignment (EGUI_ALIGNMENT left, EGUI_ALIGNMENT right, EGUI_ALIGNMENT top, EGUI_ALIGNMENT bottom)
The alignment defines how the borders of this element will be positioned when the parent element is resized.
EGUI_ALIGNMENT getAlignLeft () const
How left element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignRight () const
How right element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignTop () const
How top element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignBottom () const
How bottom element border is aligned when parent is resized.
virtual IGUIElement * getElementFromPoint (const core::position2d< s32 > &point)
Returns the topmost GUI element at the specific position.
virtual bool isPointInside (const core::position2d< s32 > &point) const
Returns true if a point is within this element.
virtual void addChild (IGUIElement *child)
Adds a GUI element as new child of this element.
virtual void removeChild (IGUIElement *child)
Removes a child.
virtual void removeAllChildren ()
Removes all children.
virtual void remove ()
Removes this element from its parent.
virtual void OnPostRender (u32 timeMs)
animate the element and its children.
virtual void move (core::position2d< s32 > absoluteMovement)
Moves this element.
virtual bool isVisible () const
Returns true if element is visible.
virtual bool isTrulyVisible () const
Check whether the element is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool visible)
Sets the visible state of this element.
virtual bool isSubElement () const
Returns true if this element was created as part of its parent control.
virtual void setSubElement (bool subElement)
Sets whether this control was created as part of its parent.
void setTabStop (bool enable)
If set to true, the focus will visit this element when using the tab key to cycle through elements.
bool isTabStop () const
Returns true if this element can be focused by navigating with the tab key.
void setTabOrder (s32 index)
Sets the priority of focus when using the tab key to navigate between a group of elements.
s32 getTabOrder () const
Returns the number in the tab order sequence.
void setTabGroup (bool isGroup)
Sets whether this element is a container for a group of elements which can be navigated using the tab key.
bool isTabGroup () const
Returns true if this element is a tab group.
IGUIElement * getTabGroup ()
Returns the container element which holds all elements in this element's tab group.
virtual bool isEnabled () const
Returns true if element is enabled.
virtual void setEnabled (bool enabled)
Sets the enabled state of this element.
virtual const wchar_t * getText () const
Returns caption of this element.
virtual void setToolTipText (const wchar_t *text)
Sets the new caption of this element.
virtual const core::stringw & getToolTipText () const
Returns caption of this element.
virtual s32 getID () const
Returns id. Can be used to identify the element.
virtual void setID (s32 id)
Sets the id of this element.
virtual bool bringToFront (IGUIElement *child)
Brings a child to front.
virtual bool sendToBack (IGUIElement *child)
Moves a child to the back, so it's siblings are drawn on top of it.
virtual const std::list< IGUIElement * > & getChildren () const
Returns list with children of this element.
virtual IGUIElement * getElementFromId (s32 id, bool searchchildren=false) const
Finds the first element with the given id.
bool isMyChild (IGUIElement *child) const
bool getNextElement (s32 startOrder, bool reverse, bool group, IGUIElement *&first, IGUIElement *&closest, bool includeInvisible=false, bool includeDisabled=false) const
searches elements to find the closest next element to tab to
EGUI_ELEMENT_TYPE getType () const
Returns the type of the gui element.
virtual bool hasType (EGUI_ELEMENT_TYPE type) const
Returns true if the gui element supports the given type.
virtual const c8 * getTypeName () const
Returns the type name of the gui element.
virtual const c8 * getName () const
Returns the name of the element.
virtual void setName (const c8 *name)
Sets the name of the element.
virtual void setName (const core::stringc &name)
Sets the name of the element.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::IEventReceiver
virtual ~IEventReceiver ()
Destructor.
Protected Member Functions
void breakText ()
Breaks the single text line.
void setTextRect (s32 line)
sets the area of the given line
s32 getLineFromPos (s32 pos)
returns the line number that the cursor is on
void inputChar (wchar_t c)
adds a letter to the edit box
void inputString (const core::stringw &str)
adds a string to the edit box
void calculateScrollPos ()
calculates the current scroll position
void calculateFrameRect ()
calculated the FrameRect
void sendGuiEvent (EGUI_EVENT_TYPE type)
send some gui event to parent
void setTextMarkers (s32 begin, s32 end)
set text markers
bool keyDelete ()
delete current selection or next char
bool processKey (const SEvent &event)
bool processMouse (const SEvent &event)
s32 getCursorPos (s32 x, s32 y)
Protected Member Functions inherited from irr::gui::IGUIElement
void addChildToEnd (IGUIElement *child)
void reorderChildren (std::list< IGUIElement * >::iterator from, std::list< IGUIElement * >::iterator to, const std::vector< IGUIElement * > &neworder)
void recalculateAbsolutePosition (bool recursive)
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
bool OverwriteMode
bool MouseMarking
bool Border
bool Background
bool OverrideColorEnabled
s32 MarkBegin
s32 MarkEnd
video::SColor OverrideColor
gui::IGUIFont * OverrideFont
gui::IGUIFont * LastBreakFont
IOSOperator * Operator
u32 BlinkStartTime
irr::u32 CursorBlinkTime
core::stringw CursorChar
s32 CursorPos
s32 HScrollPos
s32 VScrollPos
u32 Max
bool WordWrap
bool MultiLine
bool AutoScroll
bool PasswordBox
wchar_t PasswordChar
EGUI_ALIGNMENT HAlign
EGUI_ALIGNMENT VAlign
core::array< core::stringw > BrokenText
core::array< s32 > BrokenTextPositions
core::rect< s32 > CurrentTextRect
core::rect< s32 > FrameRect
Protected Attributes inherited from irr::gui::IGUIElement
std::list< IGUIElement * > Children
List of all children of this element.
IGUIElement * Parent
Pointer to the parent.
std::list< IGUIElement * >::iterator ParentPos
Our position in the parent list. Only valid when Parent != nullptr.
core::rect< s32 > RelativeRect
relative rect of element
core::rect< s32 > AbsoluteRect
absolute rect of element
core::rect< s32 > AbsoluteClippingRect
absolute clipping rect of element
core::rect< s32 > DesiredRect
core::rect< s32 > LastParentRect
for calculating the difference when resizing parent
core::rect< f32 > ScaleRect
relative scale of the element inside its parent
core::dimension2du MaxSize
maximum and minimum size of the element
core::dimension2du MinSize
bool IsVisible
is visible?
bool IsEnabled
is enabled?
bool IsSubElement
is a part of a larger whole and should not be serialized?
bool NoClip
does this element ignore its parent's clipping rectangle?
core::stringw Text
caption
core::stringw ToolTipText
tooltip
core::stringc Name
users can set this for identifying the element by string
s32 ID
users can set this for identifying the element by integer
bool IsTabStop
tab stop like in windows
s32 TabOrder
tab order
bool IsTabGroup
tab groups are containers like windows, use ctrl+tab to navigate
EGUI_ALIGNMENT AlignLeft
tells the element how to act when its parent is resized
EGUI_ALIGNMENT AlignRight
EGUI_ALIGNMENT AlignTop
EGUI_ALIGNMENT AlignBottom
IGUIEnvironment * Environment
GUI Environment.
EGUI_ELEMENT_TYPE Type
type of element
Additional Inherited Members
Static Protected Member Functions inherited from irr::gui::IGUIElement
template<typename Iterator >
static size_t _fastSetChecksum (Iterator begin, Iterator end)
Detailed Description
Definition at line 16 of file CGUIEditBox.h.
Member Function Documentation
enableOverrideColor()
void irr::gui::CGUIEditBox::enableOverrideColor (bool enable) override virtual
Sets if the text should use the override color or the color in the gui skin.
Sets if the text should use the override color or the color in the gui skin.
Implements irr::gui::IGUIEditBox.
Definition at line 148 of file CGUIEditBox.cpp.
getActiveFont()
IGUIFont * irr::gui::CGUIEditBox::getActiveFont () const override virtual
Get the font which is used right now for drawing.
Currently this is the override font when one is set and the font of the active skin otherwise
Implements irr::gui::IGUIEditBox.
Definition at line 99 of file CGUIEditBox.cpp.
References irr::gui::IGUIElement::Environment, irr::gui::IGUISkin::getFont(), and irr::gui::IGUIEnvironment::getSkin().
Referenced by breakText(), calculateScrollPos(), draw(), and setTextRect().
getOverrideFont()
IGUIFont * irr::gui::CGUIEditBox::getOverrideFont () const override virtual
Gets the override font (if any)
Returns
The override font (may be 0)
Implements irr::gui::IGUIEditBox.
Definition at line 93 of file CGUIEditBox.cpp.
getTextDimension()
core::dimension2du irr::gui::CGUIEditBox::getTextDimension () override virtual
Gets the size area of the text in the edit box
Returns
Returns the size in pixels of the text
Gets the area of the text in the edit box
Returns
Returns the size in pixels of the text
Implements irr::gui::IGUIEditBox.
Definition at line 1017 of file CGUIEditBox.cpp.
References irr::core::rect< T >::LowerRightCorner, setTextRect(), and irr::core::rect< T >::UpperLeftCorner.
isAutoScrollEnabled()
bool irr::gui::CGUIEditBox::isAutoScrollEnabled () const override virtual
Checks to see if automatic scrolling is enabled
Returns
true if automatic scrolling is enabled, false if not
Implements irr::gui::IGUIEditBox.
Definition at line 1009 of file CGUIEditBox.cpp.
isMultiLineEnabled()
bool irr::gui::CGUIEditBox::isMultiLineEnabled () const override virtual
Checks if multi line editing is enabled.
Checks if multi line editing is enabled
Returns
true if mult-line is enabled, false otherwise
Implements irr::gui::IGUIEditBox.
Definition at line 195 of file CGUIEditBox.cpp.
isOverrideColorEnabled()
bool irr::gui::CGUIEditBox::isOverrideColorEnabled (void) const override virtual
Checks if an override color is enabled.
Returns
true if the override color is enabled, false otherwise
Implements irr::gui::IGUIEditBox.
Definition at line 153 of file CGUIEditBox.cpp.
isWordWrapEnabled()
bool irr::gui::CGUIEditBox::isWordWrapEnabled () const override virtual
Checks if word wrap is enabled.
Checks if word wrap is enabled
Returns
true if word wrap is enabled, false otherwise
Implements irr::gui::IGUIEditBox.
Definition at line 180 of file CGUIEditBox.cpp.
setAutoScroll()
void irr::gui::CGUIEditBox::setAutoScroll (bool enable) override virtual
Enables or disables automatic scrolling with cursor position
Parameters
enable If set to true, the text will move around with the cursor position
Implements irr::gui::IGUIEditBox.
Definition at line 1001 of file CGUIEditBox.cpp.
setCursorChar()
void irr::gui::CGUIEditBox::setCursorChar (const wchar_t cursorChar) override virtual
Set the character used for the cursor.
By default it's "_"
Implements irr::gui::IGUIEditBox.
Definition at line 1055 of file CGUIEditBox.cpp.
setMax()
void irr::gui::CGUIEditBox::setMax (u32 max) override virtual
Sets the maximum amount of characters which may be entered in the box.
Parameters
max Maximum amount of characters. If 0, the character amount is infinity.
Implements irr::gui::IGUIEditBox.
Definition at line 1038 of file CGUIEditBox.cpp.
References irr::gui::IGUIElement::Text.
setMultiLine()
void irr::gui::CGUIEditBox::setMultiLine (bool enable) override virtual
Enables or disables newlines.
Parameters
enable If set to true, the EGET_EDITBOX_ENTER event will not be fired, instead a newline character will be inserted.
Implements irr::gui::IGUIEditBox.
Definition at line 187 of file CGUIEditBox.cpp.
References breakText().
Referenced by setPasswordBox().
setPasswordBox()
void irr::gui::CGUIEditBox::setPasswordBox (bool passwordBox, wchar_t passwordChar = L'*') override virtual
Sets whether the edit box is a password box. Setting this to true will.
disable MultiLine, WordWrap and the ability to copy with ctrl+c or ctrl+x
Parameters
passwordBox true to enable password, false to disable
passwordChar the character that is displayed instead of letters
Implements irr::gui::IGUIEditBox.
Definition at line 201 of file CGUIEditBox.cpp.
References setMultiLine(), and setWordWrap().
setWordWrap()
void irr::gui::CGUIEditBox::setWordWrap (bool enable) override virtual
Enables or disables word wrap for using the edit box as multiline text editor.
Enables or disables word wrap.
Implements irr::gui::IGUIEditBox.
Definition at line 159 of file CGUIEditBox.cpp.
References breakText().
Referenced by setPasswordBox().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CGUIEditBox.h
lib/irrlichtmt/source/Irrlicht/CGUIEditBox.cpp