Three Cubes Game: irr::video::IVideoDriver Class Reference
irr::video::IVideoDriver Class Reference abstract
Interface to driver which is able to perform 2d and 3d graphics functions.
#include <IVideoDriver.h>
Public Member Functions
virtual bool beginScene (u16 clearFlag=(u16)(ECBF_COLOR|ECBF_DEPTH), SColor clearColor=SColor(255, 0, 0, 0), f32 clearDepth=1.f, u8 clearStencil=0, const SExposedVideoData &videoData=SExposedVideoData(), core::rect< s32 > *sourceRect=0)=0
Applications must call this method before performing any rendering.
bool beginScene (bool backBuffer, bool zBuffer, SColor color=SColor(255, 0, 0, 0), const SExposedVideoData &videoData=SExposedVideoData(), core::rect< s32 > *sourceRect=0)
Alternative beginScene implementation. Can't clear stencil buffer, but otherwise identical to other beginScene.
virtual bool endScene ()=0
Presents the rendered image to the screen.
virtual bool queryFeature (E_VIDEO_DRIVER_FEATURE feature) const =0
Queries the features of the driver.
virtual void disableFeature (E_VIDEO_DRIVER_FEATURE feature, bool flag=true)=0
Disable a feature of the driver.
virtual const io::IAttributes & getDriverAttributes () const =0
Get attributes of the actual video driver.
virtual bool checkDriverReset ()=0
Check if the driver was recently reset.
virtual void setTransform (E_TRANSFORMATION_STATE state, const core::matrix4 &mat)=0
Sets transformation matrices.
virtual const core::matrix4 & getTransform (E_TRANSFORMATION_STATE state) const =0
Returns the transformation set by setTransform.
virtual u32 getImageLoaderCount () const =0
Retrieve the number of image loaders.
virtual IImageLoader * getImageLoader (u32 n)=0
Retrieve the given image loader.
virtual u32 getImageWriterCount () const =0
Retrieve the number of image writers.
virtual IImageWriter * getImageWriter (u32 n)=0
Retrieve the given image writer.
virtual void setMaterial (const SMaterial &material)=0
Sets a material.
virtual ITexture * getTexture (const io::path &filename)=0
Get access to a named texture.
virtual ITexture * getTexture (io::IReadFile *file)=0
Get access to a named texture.
virtual ITexture * getTextureByIndex (u32 index)=0
Returns a texture by index.
virtual u32 getTextureCount () const =0
Returns amount of textures currently loaded.
virtual void renameTexture (ITexture *texture, const io::path &newName)=0
Renames a texture.
virtual ITexture * addTexture (const core::dimension2d< u32 > &size, const io::path &name, ECOLOR_FORMAT format=ECF_A8R8G8B8)=0
Creates an empty texture of specified size.
_IRR_DEPRECATED_ ITexture * addTexture (const io::path &name, IImage *image, void *mipmapData)
Creates a texture from an IImage.
virtual ITexture * addTexture (const io::path &name, IImage *image)=0
Creates a texture from an IImage.
virtual ITexture * addTextureCubemap (const io::path &name, IImage *imagePosX, IImage *imageNegX, IImage *imagePosY, IImage *imageNegY, IImage *imagePosZ, IImage *imageNegZ)=0
Creates a cubemap texture from loaded IImages.
virtual ITexture * addTextureCubemap (const irr::u32 sideLen, const io::path &name, ECOLOR_FORMAT format=ECF_A8R8G8B8)=0
Creates an empty cubemap texture of specified size.
virtual ITexture * addRenderTargetTexture (const core::dimension2d< u32 > &size, const io::path &name="rt", const ECOLOR_FORMAT format=ECF_UNKNOWN)=0
Adds a new render target texture to the texture cache.
virtual ITexture * addRenderTargetTextureCubemap (const irr::u32 sideLen, const io::path &name="rt", const ECOLOR_FORMAT format=ECF_UNKNOWN)=0
Adds a new render target texture with 6 sides for a cubemap map to the texture cache.
virtual void removeTexture (ITexture *texture)=0
Removes a texture from the texture cache and deletes it.
virtual void removeAllTextures ()=0
Removes all textures from the texture cache and deletes them.
virtual void removeHardwareBuffer (const scene::IMeshBuffer *mb)=0
Remove hardware buffer.
virtual void removeAllHardwareBuffers ()=0
Remove all hardware buffers.
virtual void addOcclusionQuery (scene::ISceneNode *node, const scene::IMesh *mesh=0)=0
Create occlusion query.
virtual void removeOcclusionQuery (scene::ISceneNode *node)=0
Remove occlusion query.
virtual void removeAllOcclusionQueries ()=0
Remove all occlusion queries.
virtual void runOcclusionQuery (scene::ISceneNode *node, bool visible=false)=0
Run occlusion query. Draws mesh stored in query.
virtual void runAllOcclusionQueries (bool visible=false)=0
Run all occlusion queries. Draws all meshes stored in queries.
virtual void updateOcclusionQuery (scene::ISceneNode *node, bool block=true)=0
Update occlusion query. Retrieves results from GPU.
virtual void updateAllOcclusionQueries (bool block=true)=0
Update all occlusion queries. Retrieves results from GPU.
virtual u32 getOcclusionQueryResult (scene::ISceneNode *node) const =0
Return query result.
virtual IRenderTarget * addRenderTarget ()=0
Create render target.
virtual void removeRenderTarget (IRenderTarget *renderTarget)=0
Remove render target.
virtual void removeAllRenderTargets ()=0
Remove all render targets.
virtual void makeColorKeyTexture (video::ITexture *texture, video::SColor color, bool zeroTexels=false) const =0
Sets a boolean alpha channel on the texture based on a color key.
virtual void makeColorKeyTexture (video::ITexture *texture, core::position2d< s32 > colorKeyPixelPos, bool zeroTexels=false) const =0
Sets a boolean alpha channel on the texture based on the color at a position.
virtual bool setRenderTargetEx (IRenderTarget *target, u16 clearFlag, SColor clearColor=SColor(255, 0, 0, 0), f32 clearDepth=1.f, u8 clearStencil=0)=0
Set a render target.
virtual bool setRenderTarget (ITexture *texture, u16 clearFlag=ECBF_COLOR|ECBF_DEPTH, SColor clearColor=SColor(255, 0, 0, 0), f32 clearDepth=1.f, u8 clearStencil=0)=0
Sets a new render target.
bool setRenderTarget (ITexture *texture, bool clearBackBuffer, bool clearZBuffer, SColor color=SColor(255, 0, 0, 0))
virtual void setViewPort (const core::rect< s32 > &area)=0
Sets a new viewport.
virtual const core::rect< s32 > & getViewPort () const =0
Gets the area of the current viewport.
virtual void drawVertexPrimitiveList (const void *vertices, u32 vertexCount, const void *indexList, u32 primCount, E_VERTEX_TYPE vType=EVT_STANDARD, scene::E_PRIMITIVE_TYPE pType=scene::EPT_TRIANGLES, E_INDEX_TYPE iType=EIT_16BIT)=0
Draws a vertex primitive list.
virtual void draw2DVertexPrimitiveList (const void *vertices, u32 vertexCount, const void *indexList, u32 primCount, E_VERTEX_TYPE vType=EVT_STANDARD, scene::E_PRIMITIVE_TYPE pType=scene::EPT_TRIANGLES, E_INDEX_TYPE iType=EIT_16BIT)=0
Draws a vertex primitive list in 2d.
void drawIndexedTriangleList (const S3DVertex *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle list.
void drawIndexedTriangleList (const S3DVertex2TCoords *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle list.
void drawIndexedTriangleList (const S3DVertexTangents *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle list.
void drawIndexedTriangleFan (const S3DVertex *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle fan.
void drawIndexedTriangleFan (const S3DVertex2TCoords *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle fan.
void drawIndexedTriangleFan (const S3DVertexTangents *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle fan.
virtual void draw3DLine (const core::vector3df &start, const core::vector3df &end, SColor color=SColor(255, 255, 255, 255))=0
Draws a 3d line.
virtual void draw3DBox (const core::aabbox3d< f32 > &box, SColor color=SColor(255, 255, 255, 255))=0
Draws a 3d axis aligned box.
virtual void draw2DImage (const video::ITexture *texture, const core::position2d< s32 > &destPos, bool useAlphaChannelOfTexture=false)=0
Draws a 2d image without any special effects.
virtual void draw2DImage (const video::ITexture *texture, const core::position2d< s32 > &destPos, const core::rect< s32 > &sourceRect, const core::rect< s32 > *clipRect=0, SColor color=SColor(255, 255, 255, 255), bool useAlphaChannelOfTexture=false)=0
Draws a 2d image using a color.
virtual void draw2DImageBatch (const video::ITexture *texture, const core::array< core::position2d< s32 > > &positions, const core::array< core::rect< s32 > > &sourceRects, const core::rect< s32 > *clipRect=0, SColor color=SColor(255, 255, 255, 255), bool useAlphaChannelOfTexture=false)=0
Draws a set of 2d images, using a color and the alpha channel of the texture.
virtual void draw2DImage (const video::ITexture *texture, const core::rect< s32 > &destRect, const core::rect< s32 > &sourceRect, const core::rect< s32 > *clipRect=0, const video::SColor *const colors=0, bool useAlphaChannelOfTexture=false)=0
Draws a part of the texture into the rectangle. Note that colors must be an array of 4 colors if used.
virtual void draw2DRectangle (SColor color, const core::rect< s32 > &pos, const core::rect< s32 > *clip=0)=0
Draws a 2d rectangle.
virtual void draw2DRectangle (const core::rect< s32 > &pos, SColor colorLeftUp, SColor colorRightUp, SColor colorLeftDown, SColor colorRightDown, const core::rect< s32 > *clip=0)=0
Draws a 2d rectangle with a gradient.
virtual void draw2DLine (const core::position2d< s32 > &start, const core::position2d< s32 > &end, SColor color=SColor(255, 255, 255, 255))=0
Draws a 2d line.
virtual void drawMeshBuffer (const scene::IMeshBuffer *mb)=0
Draws a mesh buffer.
virtual void drawMeshBufferNormals (const scene::IMeshBuffer *mb, f32 length=10.f, SColor color=0xffffffff)=0
Draws normals of a mesh buffer.
virtual void setFog (SColor color=SColor(0, 255, 255, 255), E_FOG_TYPE fogType=EFT_FOG_LINEAR, f32 start=50.0f, f32 end=100.0f, f32 density=0.01f, bool pixelFog=false, bool rangeFog=false)=0
Sets the fog mode.
virtual void getFog (SColor &color, E_FOG_TYPE &fogType, f32 &start, f32 &end, f32 &density, bool &pixelFog, bool &rangeFog)=0
Gets the fog mode.
virtual ECOLOR_FORMAT getColorFormat () const =0
Get the current color format of the color buffer.
virtual const core::dimension2d< u32 > & getScreenSize () const =0
Get the size of the screen or render window.
virtual const core::dimension2d< u32 > & getCurrentRenderTargetSize () const =0
Get the size of the current render target.
virtual s32 getFPS () const =0
Returns current frames per second value.
virtual u32 getPrimitiveCountDrawn (u32 mode=0) const =0
Returns amount of primitives (mostly triangles) which were drawn in the last frame.
virtual const wchar_t * getName () const =0
Gets name of this video driver.
virtual void addExternalImageLoader (IImageLoader *loader)=0
Adds an external image loader to the engine.
virtual void addExternalImageWriter (IImageWriter *writer)=0
Adds an external image writer to the engine.
virtual u32 getMaximalPrimitiveCount () const =0
Returns the maximum amount of primitives.
virtual void setTextureCreationFlag (E_TEXTURE_CREATION_FLAG flag, bool enabled=true)=0
Enables or disables a texture creation flag.
virtual bool getTextureCreationFlag (E_TEXTURE_CREATION_FLAG flag) const =0
Returns if a texture creation flag is enabled or disabled.
virtual IImage * createImageFromFile (const io::path &filename)=0
Creates a software image from a file.
virtual IImage * createImageFromFile (io::IReadFile *file)=0
Creates a software image from a file.
virtual bool writeImageToFile (IImage *image, const io::path &filename, u32 param=0)=0
Writes the provided image to a file.
virtual bool writeImageToFile (IImage *image, io::IWriteFile *file, u32 param=0)=0
Writes the provided image to a file.
virtual IImage * createImageFromData (ECOLOR_FORMAT format, const core::dimension2d< u32 > &size, void *data, bool ownForeignMemory=false, bool deleteMemory=true)=0
Creates a software image from a byte array.
virtual IImage * createImage (ECOLOR_FORMAT format, const core::dimension2d< u32 > &size)=0
Creates an empty software image.
virtual _IRR_DEPRECATED_ IImage * createImage (ECOLOR_FORMAT format, IImage *imageToCopy)=0
Creates a software image by converting it to given format from another image.
virtual _IRR_DEPRECATED_ IImage * createImage (IImage *imageToCopy, const core::position2d< s32 > &pos, const core::dimension2d< u32 > &size)=0
Creates a software image from a part of another image.
virtual IImage * createImage (ITexture *texture, const core::position2d< s32 > &pos, const core::dimension2d< u32 > &size)=0
Creates a software image from a part of a texture.
virtual void OnResize (const core::dimension2d< u32 > &size)=0
Event handler for resize events. Only used by the engine internally.
virtual s32 addMaterialRenderer (IMaterialRenderer *renderer, const c8 *name=0)=0
Adds a new material renderer to the video device.
virtual IMaterialRenderer * getMaterialRenderer (u32 idx) const =0
Get access to a material renderer by index.
virtual u32 getMaterialRendererCount () const =0
Get amount of currently available material renderers.
virtual const c8 * getMaterialRendererName (u32 idx) const =0
Get name of a material renderer.
virtual void setMaterialRendererName (u32 idx, const c8 *name)=0
Sets the name of a material renderer.
virtual void swapMaterialRenderers (u32 idx1, u32 idx2, bool swapNames=true)=0
Swap the material renderers used for certain id's.
virtual const SExposedVideoData & getExposedVideoData ()=0
Returns driver and operating system specific data about the IVideoDriver.
virtual E_DRIVER_TYPE getDriverType () const =0
Get type of video driver.
virtual IGPUProgrammingServices * getGPUProgrammingServices ()=0
Gets the IGPUProgrammingServices interface.
virtual scene::IMeshManipulator * getMeshManipulator ()=0
Returns a pointer to the mesh manipulator.
virtual void clearBuffers (u16 flag, SColor color=SColor(255, 0, 0, 0), f32 depth=1.f, u8 stencil=0)=0
Clear the color, depth and/or stencil buffers.
_IRR_DEPRECATED_ void clearBuffers (bool backBuffer, bool depthBuffer, bool stencilBuffer, SColor color)
Clear the color, depth and/or stencil buffers.
void clearZBuffer ()
Clears the ZBuffer.
virtual IImage * createScreenShot (video::ECOLOR_FORMAT format=video::ECF_UNKNOWN, video::E_RENDER_TARGET target=video::ERT_FRAME_BUFFER)=0
Make a screenshot of the last rendered frame.
virtual video::ITexture * findTexture (const io::path &filename)=0
Check if the image is already loaded.
virtual bool setClipPlane (u32 index, const core::plane3df &plane, bool enable=false)=0
Set or unset a clipping plane.
virtual void enableClipPlane (u32 index, bool enable)=0
Enable or disable a clipping plane.
virtual void setMinHardwareBufferVertexCount (u32 count)=0
Set the minimum number of vertices for which a hw buffer will be created.
virtual SOverrideMaterial & getOverrideMaterial ()=0
Get the global Material, which might override local materials.
virtual SMaterial & getMaterial2D ()=0
Get the 2d override material for altering its values.
virtual void enableMaterial2D (bool enable=true)=0
Enable the 2d override material.
virtual core::stringc getVendorInfo ()=0
Get the graphics card vendor name.
virtual void setAmbientLight (const SColorf &color)=0
Only used by the engine internally.
virtual const SColorf & getAmbientLight () const =0
Get the global ambient light currently used by the driver.
virtual void setAllowZWriteOnTransparent (bool flag)=0
Only used by the engine internally.
virtual core::dimension2du getMaxTextureSize () const =0
Get the maximum texture size supported.
virtual void convertColor (const void *sP, ECOLOR_FORMAT sF, s32 sN, void *dP, ECOLOR_FORMAT dF) const =0
Color conversion convenience function.
virtual bool queryTextureFormat (ECOLOR_FORMAT format) const =0
Check if the driver supports creating textures with the given color format.
virtual bool needsTransparentRenderPass (const irr::video::SMaterial &material) const =0
Used by some SceneNodes to check if a material should be rendered in the transparent render pass.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Interface to driver which is able to perform 2d and 3d graphics functions.
This interface is one of the most important interfaces of the Irrlicht Engine: All rendering and texture manipulation is done with this interface. You are able to use the Irrlicht Engine by only invoking methods of this interface if you like to, although the irr::scene::ISceneManager interface provides a lot of powerful classes and methods to make the programmer's life easier.
Definition at line 128 of file IVideoDriver.h.
Member Function Documentation
addExternalImageLoader()
virtual void irr::video::IVideoDriver::addExternalImageLoader (IImageLoader * loader) pure virtual
Adds an external image loader to the engine.
This is useful if the Irrlicht Engine should be able to load textures of currently unsupported file formats (e.g. gif). The IImageLoader only needs to be implemented for loading this file format. A pointer to the implementation can be passed to the engine using this method.
Parameters
loader Pointer to the external loader created.
Implemented in irr::video::CNullDriver.
addExternalImageWriter()
virtual void irr::video::IVideoDriver::addExternalImageWriter (IImageWriter * writer) pure virtual
Adds an external image writer to the engine.
This is useful if the Irrlicht Engine should be able to write textures of currently unsupported file formats (e.g .gif). The IImageWriter only needs to be implemented for writing this file format. A pointer to the implementation can be passed to the engine using this method.
Parameters
writer Pointer to the external writer created.
Implemented in irr::video::CNullDriver.
addMaterialRenderer()
virtual s32 irr::video::IVideoDriver::addMaterialRenderer (IMaterialRenderer * renderer, const c8 * name = 0) pure virtual
Adds a new material renderer to the video device.
Use this method to extend the VideoDriver with new material types. To extend the engine using this method do the following: Derive a class from IMaterialRenderer and override the methods you need. For setting the right renderstates, you can try to get a pointer to the real rendering device using IVideoDriver::getExposedVideoData(). Add your class with IVideoDriver::addMaterialRenderer(). To use an object being displayed with your new material, set the MaterialType member of the SMaterial struct to the value returned by this method. If you simply want to create a new material using vertex and/or pixel shaders it would be easier to use the video::IGPUProgrammingServices interface which you can get using the getGPUProgrammingServices() method.
Parameters
renderer A pointer to the new renderer.
name Optional name for the material renderer entry.
Returns
The number of the material type which can be set in SMaterial::MaterialType to use the renderer. -1 is returned if an error occurred. For example if you tried to add an material renderer to the software renderer or the null device, which do not accept material renderers.
Implemented in irr::video::CNullDriver.
addOcclusionQuery()
virtual void irr::video::IVideoDriver::addOcclusionQuery (scene::ISceneNode * node, const scene::IMesh * mesh = 0) pure virtual
Create occlusion query.
Use node for identification and mesh for occlusion test.
Implemented in irr::video::CNullDriver.
addRenderTargetTexture()
virtual ITexture* irr::video::IVideoDriver::addRenderTargetTexture (const core::dimension2d< u32 > & size, const io::path & name = "rt", const ECOLOR_FORMAT format = ECF_UNKNOWN) pure virtual
Adds a new render target texture to the texture cache.
Parameters
size Size of the texture, in pixels. Width and height should be a power of two (e.g. 64, 128, 256, 512, ...) and it should not be bigger than the backbuffer, because it shares the zbuffer with the screen buffer.
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
format The color format of the render target. Floating point formats are supported.
Returns
Pointer to the created texture or 0 if the texture could not be created. This pointer should not be dropped. See IReferenceCounted::drop() for more information. You may want to remove it from driver texture cache with removeTexture if you no longer need it.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by TextureBuffer::ensureTexture().
addRenderTargetTextureCubemap()
virtual ITexture* irr::video::IVideoDriver::addRenderTargetTextureCubemap (const irr::u32 sideLen, const io::path & name = "rt", const ECOLOR_FORMAT format = ECF_UNKNOWN) pure virtual
Adds a new render target texture with 6 sides for a cubemap map to the texture cache.
NOTE: Only supported on D3D9 so far.
Parameters
sideLen Length of one cubemap side.
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
format The color format of the render target. Floating point formats are supported.
Returns
Pointer to the created texture or 0 if the texture could not be created. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
addTexture() [1/3]
virtual ITexture* irr::video::IVideoDriver::addTexture (const core::dimension2d< u32 > & size, const io::path & name, ECOLOR_FORMAT format = ECF_A8R8G8B8) pure virtual
Creates an empty texture of specified size.
Parameters
size Size of the texture.
name A name for the texture. Later calls to getTexture() with this name will return this texture. The name can not be empty.
format Desired color format of the texture. Please note that the driver may choose to create the texture in another color format.
Returns
Pointer to the newly created texture. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
Referenced by addTexture(), irr::gui::CGUITTGlyphPage::createPageTexture(), TextureBuffer::ensureTexture(), MenuTextureSource::getTexture(), and irr::gui::CGUIFont::loadTexture().
addTexture() [2/3]
virtual ITexture* irr::video::IVideoDriver::addTexture (const io::path & name, IImage * image) pure virtual
Creates a texture from an IImage.
Parameters
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
image Image the texture is created from.
Returns
Pointer to the newly created texture. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
addTexture() [3/3]
_IRR_DEPRECATED_ ITexture* irr::video::IVideoDriver::addTexture (const io::path & name, IImage * image, void * mipmapData) inline
Creates a texture from an IImage.
Parameters
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
image Image the texture is created from.
mipmapData Optional pointer to a mipmaps data. If this parameter is not given, the mipmaps are derived from image.
Returns
Pointer to the newly created texture. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Definition at line 310 of file IVideoDriver.h.
References addTexture(), and irr::video::IImage::setMipMapsData().
addTextureCubemap() [1/2]
virtual ITexture* irr::video::IVideoDriver::addTextureCubemap (const io::path & name, IImage * imagePosX, IImage * imageNegX, IImage * imagePosY, IImage * imageNegY, IImage * imagePosZ, IImage * imageNegZ) pure virtual
Creates a cubemap texture from loaded IImages.
Parameters
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
imagePosX Image (positive X) the texture is created from.
imageNegX Image (negative X) the texture is created from.
imagePosY Image (positive Y) the texture is created from.
imageNegY Image (negative Y) the texture is created from.
imagePosZ Image (positive Z) the texture is created from.
imageNegZ Image (negative Z) the texture is created from.
Returns
Pointer to the newly created texture. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
addTextureCubemap() [2/2]
virtual ITexture* irr::video::IVideoDriver::addTextureCubemap (const irr::u32 sideLen, const io::path & name, ECOLOR_FORMAT format = ECF_A8R8G8B8) pure virtual
Creates an empty cubemap texture of specified size.
Parameters
sideLen diameter of one side of the cube
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
format Desired color format of the texture. Please note that the driver may choose to create the texture in another color format.
Returns
Pointer to the newly created texture.
Implemented in irr::video::CNullDriver.
beginScene()
virtual bool irr::video::IVideoDriver::beginScene (u16 clearFlag = (u16)(ECBF_COLOR|ECBF_DEPTH), SColor clearColor = SColor(255, 0, 0, 0), f32 clearDepth = 1.f, u8 clearStencil = 0, const SExposedVideoData & videoData = SExposedVideoData(), core::rect< s32 > * sourceRect = 0) pure virtual
Applications must call this method before performing any rendering.
This method can clear the back- and the z-buffer.
Parameters
clearFlag A combination of the E_CLEAR_BUFFER_FLAG bit-flags.
clearColor The clear color for the color buffer.
clearDepth The clear value for the depth buffer.
clearStencil The clear value for the stencil buffer.
videoData Handle of another window, if you want the bitmap to be displayed on another window. If this is an empty element, everything will be displayed in the default window. Note: This feature is not fully implemented for all devices.
sourceRect Pointer to a rectangle defining the source rectangle of the area to be presented. Set to null to present everything. Note: not implemented in all devices.
Returns
False if failed.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by beginScene(), and GUIEngine::run().
checkDriverReset()
virtual bool irr::video::IVideoDriver::checkDriverReset () pure virtual
Check if the driver was recently reset.
For d3d devices you will need to recreate the RTTs if the driver was reset. Should be queried right after beginScene().
Implemented in irr::video::CNullDriver.
clearZBuffer()
void irr::video::IVideoDriver::clearZBuffer () inline
Clears the ZBuffer.
Note that you usually need not to call this method, as it is automatically done in IVideoDriver::beginScene() or IVideoDriver::setRenderTarget() if you enable zBuffer. But if you have to render some special things, you can clear the zbuffer during the rendering process with this method any time.
Definition at line 1183 of file IVideoDriver.h.
References clearBuffers().
Referenced by setRenderTarget().
convertColor()
virtual void irr::video::IVideoDriver::convertColor (const void * sP, ECOLOR_FORMAT sF, s32 sN, void * dP, ECOLOR_FORMAT dF) const pure virtual
Color conversion convenience function.
Convert an image (as array of pixels) from source to destination array, thereby converting the color format. The pixel size is determined by the color formats.
Parameters
sP Pointer to source
sF Color format of source
sN Number of pixels to convert, both array must be large enough
dP Pointer to destination
dF Color format of destination
Implemented in irr::video::CNullDriver.
createImage() [1/4]
virtual IImage* irr::video::IVideoDriver::createImage (ECOLOR_FORMAT format, const core::dimension2d< u32 > & size) pure virtual
Creates an empty software image.
Parameters
format Desired color format of the image.
size Size of the image to create.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
Referenced by irr::gui::SGUITTGlyph::createGlyphImage(), irr::gui::CGUITTFont::createTextureFromChar(), TextureBuffer::ensureTexture(), and irr::gui::CGUIFont::loadTexture().
createImage() [2/4]
virtual _IRR_DEPRECATED_ IImage* irr::video::IVideoDriver::createImage (ECOLOR_FORMAT format, IImage * imageToCopy) pure virtual
Creates a software image by converting it to given format from another image.
Deprecated:
Create an empty image and use copyTo(). This method may be removed by Irrlicht 1.9.
Parameters
format Desired color format of the image.
imageToCopy Image to copy to the new image.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
createImage() [3/4]
virtual _IRR_DEPRECATED_ IImage* irr::video::IVideoDriver::createImage (IImage * imageToCopy, const core::position2d< s32 > & pos, const core::dimension2d< u32 > & size) pure virtual
Creates a software image from a part of another image.
Deprecated:
Create an empty image and use copyTo(). This method may be removed by Irrlicht 1.9.
Parameters
imageToCopy Image to copy to the new image in part.
pos Position of rectangle to copy.
size Extents of rectangle to copy.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
createImage() [4/4]
virtual IImage* irr::video::IVideoDriver::createImage (ITexture * texture, const core::position2d< s32 > & pos, const core::dimension2d< u32 > & size) pure virtual
Creates a software image from a part of a texture.
Parameters
texture Texture to copy to the new image in part.
pos Position of rectangle to copy.
size Extents of rectangle to copy.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
createImageFromData()
virtual IImage* irr::video::IVideoDriver::createImageFromData (ECOLOR_FORMAT format, const core::dimension2d< u32 > & size, void * data, bool ownForeignMemory = false, bool deleteMemory = true) pure virtual
Creates a software image from a byte array.
No hardware texture will be created for this image. This method is useful for example if you want to read a heightmap for a terrain renderer.
Parameters
format Desired color format of the texture
size Desired size of the image
data A byte array with pixel color information
ownForeignMemory If true, the image will use the data pointer directly and own it afterward. If false, the memory will by copied internally. WARNING: Setting this to 'true' will not work across dll boundaries. So unless you link Irrlicht statically you should keep this to 'false'. The parameter is mainly for internal usage.
deleteMemory Whether the memory is deallocated upon destruction.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
Referenced by irr::gui::CGUITTFont::createTextureFromChar(), and irr::gui::CGUITTGlyphPage::updateTexture().
createImageFromFile() [1/2]
virtual IImage* irr::video::IVideoDriver::createImageFromFile (const io::path & filename) pure virtual
Creates a software image from a file.
No hardware texture will be created for this image. This method is useful for example if you want to read a heightmap for a terrain renderer.
Parameters
filename Name of the file from which the image is created.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
Referenced by MenuTextureSource::getTexture(), and irr::gui::CGUIFont::load().
createImageFromFile() [2/2]
virtual IImage* irr::video::IVideoDriver::createImageFromFile (io::IReadFile * file) pure virtual
Creates a software image from a file.
No hardware texture will be created for this image. This method is useful for example if you want to read a heightmap for a terrain renderer.
Parameters
file File from which the image is created.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
createScreenShot()
virtual IImage* irr::video::IVideoDriver::createScreenShot (video::ECOLOR_FORMAT format = video::ECF_UNKNOWN, video::E_RENDER_TARGET target = video::ERT_FRAME_BUFFER) pure virtual
Make a screenshot of the last rendered frame.
Returns
An image created from the last rendered frame.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
disableFeature()
virtual void irr::video::IVideoDriver::disableFeature (E_VIDEO_DRIVER_FEATURE feature, bool flag = true) pure virtual
Disable a feature of the driver.
Can also be used to enable the features again. It is not possible to enable unsupported features this way, though.
Parameters
feature Feature to disable.
flag When true the feature is disabled, otherwise it is enabled.
Implemented in irr::video::CNullDriver.
draw2DImage() [1/3]
virtual void irr::video::IVideoDriver::draw2DImage (const video::ITexture * texture, const core::position2d< s32 > & destPos, bool useAlphaChannelOfTexture = false) pure virtual
Draws a 2d image without any special effects.
Parameters
texture Pointer to texture to use.
destPos Upper left 2d destination position where the image will be drawn.
useAlphaChannelOfTexture If true, the alpha channel of the texture is used to draw the image.
Implemented in irr::video::CNullDriver.
Referenced by irr::gui::CGUIButton::draw(), GUIButton::draw(), irr::gui::CGUIImage::draw(), irr::gui::CGUIImageList::draw(), irr::gui::CGUISpriteBank::draw2DSprite(), DrawImageStep::run(), and UpscaleStep::run().
draw2DImage() [2/3]
virtual void irr::video::IVideoDriver::draw2DImage (const video::ITexture * texture, const core::position2d< s32 > & destPos, const core::rect< s32 > & sourceRect, const core::rect< s32 > * clipRect = 0, SColor color = SColor(255, 255, 255, 255), bool useAlphaChannelOfTexture = false) pure virtual
Draws a 2d image using a color.
(if color is other than Color(255,255,255,255)) and the alpha channel of the texture.
Parameters
texture Texture to be drawn.
destPos Upper left 2d destination position where the image will be drawn.
sourceRect Source rectangle in the texture (based on it's OriginalSize)
clipRect Pointer to rectangle on the screen where the image is clipped to. If this pointer is NULL the image is not clipped.
color Color with which the image is drawn. If the color equals Color(255,255,255,255) it is ignored. Note that the alpha component is used: If alpha is other than 255, the image will be transparent.
useAlphaChannelOfTexture If true, the alpha channel of the texture is used to draw the image.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
draw2DImage() [3/3]
virtual void irr::video::IVideoDriver::draw2DImage (const video::ITexture * texture, const core::rect< s32 > & destRect, const core::rect< s32 > & sourceRect, const core::rect< s32 > * clipRect = 0, const video::SColor *const colors = 0, bool useAlphaChannelOfTexture = false) pure virtual
Draws a part of the texture into the rectangle. Note that colors must be an array of 4 colors if used.
Suggested and first implemented by zola.
Parameters
texture The texture to draw from
destRect The rectangle to draw into
sourceRect The rectangle denoting a part of the texture (based on it's OriginalSize)
clipRect Clips the destination rectangle (may be 0)
colors Array of 4 colors denoting the color values of the corners of the destRect
useAlphaChannelOfTexture True if alpha channel will be blended.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
draw2DImageBatch()
virtual void irr::video::IVideoDriver::draw2DImageBatch (const video::ITexture * texture, const core::array< core::position2d< s32 > > & positions, const core::array< core::rect< s32 > > & sourceRects, const core::rect< s32 > * clipRect = 0, SColor color = SColor(255, 255, 255, 255), bool useAlphaChannelOfTexture = false) pure virtual
Draws a set of 2d images, using a color and the alpha channel of the texture.
All drawings are clipped against clipRect (if != 0). The subtextures are defined by the array of sourceRects and are positioned using the array of positions.
Parameters
texture Texture to be drawn.
positions Array of upper left 2d destinations where the images will be drawn.
sourceRects Source rectangles of the texture (based on it's OriginalSize)
clipRect Pointer to rectangle on the screen where the images are clipped to. If this pointer is 0 then the image is not clipped.
color Color with which the image is drawn. Note that the alpha component is used. If alpha is other than 255, the image will be transparent.
useAlphaChannelOfTexture If true, the alpha channel of the texture is used to draw the image.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by irr::gui::CGUISpriteBank::draw2DSpriteBatch().
draw2DLine()
virtual void irr::video::IVideoDriver::draw2DLine (const core::position2d< s32 > & start, const core::position2d< s32 > & end, SColor color = SColor(255, 255, 255, 255)) pure virtual
Draws a 2d line.
In theory both start and end will be included in coloring. BUG: Currently d3d ignores the last pixel (it uses the so called "diamond exit rule" for drawing lines).
Parameters
start Screen coordinates of the start of the line in pixels.
end Screen coordinates of the start of the line in pixels.
color Color of the line to draw.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
draw2DRectangle() [1/2]
virtual void irr::video::IVideoDriver::draw2DRectangle (const core::rect< s32 > & pos, SColor colorLeftUp, SColor colorRightUp, SColor colorLeftDown, SColor colorRightDown, const core::rect< s32 > * clip = 0) pure virtual
Draws a 2d rectangle with a gradient.
Parameters
colorLeftUp Color of the upper left corner to draw. The alpha component will not be ignored and specifies how transparent the rectangle will be.
colorRightUp Color of the upper right corner to draw. The alpha component will not be ignored and specifies how transparent the rectangle will be.
colorLeftDown Color of the lower left corner to draw. The alpha component will not be ignored and specifies how transparent the rectangle will be.
colorRightDown Color of the lower right corner to draw. The alpha component will not be ignored and specifies how transparent the rectangle will be.
pos Position of the rectangle.
clip Pointer to rectangle against which the rectangle will be clipped. If the pointer is null, no clipping will be performed.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
draw2DRectangle() [2/2]
virtual void irr::video::IVideoDriver::draw2DRectangle (SColor color, const core::rect< s32 > & pos, const core::rect< s32 > * clip = 0) pure virtual
Draws a 2d rectangle.
Parameters
color Color of the rectangle to draw. The alpha component will not be ignored and specifies how transparent the rectangle will be.
pos Position of the rectangle.
clip Pointer to rectangle against which the rectangle will be clipped. If the pointer is null, no clipping will be performed.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by irr::gui::CGUIStaticText::draw(), GUIBox::draw(), irr::gui::CGUICheckBox::draw(), GUIInventoryList::draw(), irr::gui::StaticText::draw(), irr::gui::CGUITabControl::draw(), irr::gui::CGUISkin::draw2DRectangle(), irr::gui::CGUISkin::draw3DButtonPanePressed(), irr::gui::CGUISkin::draw3DButtonPaneStandard(), irr::gui::CGUISkin::draw3DMenuPane(), irr::gui::CGUISkin::draw3DSunkenPane(), irr::gui::CGUISkin::draw3DTabBody(), irr::gui::CGUISkin::draw3DTabButton(), irr::gui::CGUISkin::draw3DToolBar(), irr::gui::CGUISkin::draw3DWindowBackground(), and GUIEngine::drawBackground().
draw2DVertexPrimitiveList()
virtual void irr::video::IVideoDriver::draw2DVertexPrimitiveList (const void * vertices, u32 vertexCount, const void * indexList, u32 primCount, E_VERTEX_TYPE vType = EVT_STANDARD, scene::E_PRIMITIVE_TYPE pType = scene::EPT_TRIANGLES, E_INDEX_TYPE iType = EIT_16BIT) pure virtual
Draws a vertex primitive list in 2d.
Compared to the general (3d) version of this method, this one sets up a 2d render mode, and uses only x and y of vectors. Note that, depending on the index type, some vertices might be not accessible through the index list. The limit is at 65535 vertices for 16bit indices. Please note that currently not all primitives are available for all drivers, and some might be emulated via triangle renders. This function is not available for the sw drivers.
Parameters
vertices Pointer to array of vertices.
vertexCount Amount of vertices in the array.
indexList Pointer to array of indices. These define the vertices used for each primitive. Depending on the pType, indices are interpreted as single objects (for point like primitives), pairs (for lines), triplets (for triangles), or quads.
primCount Amount of Primitives
vType Vertex type, e.g. video::EVT_STANDARD for S3DVertex.
pType Primitive type, e.g. scene::EPT_TRIANGLE_FAN for a triangle fan.
iType Index type, e.g. video::EIT_16BIT for 16bit indices.
Implemented in irr::video::CNullDriver.
draw3DBox()
virtual void irr::video::IVideoDriver::draw3DBox (const core::aabbox3d< f32 > & box, SColor color = SColor(255, 255, 255, 255)) pure virtual
Draws a 3d axis aligned box.
This method simply calls draw3DLine for the edges of the box. Note that the box is drawn using the current transformation matrix and material. So if you need to draw it independently of the current transformation, use
driver->setMaterial(someMaterial);
driver->setTransform(video::ETS_WORLD, core::IdentityMatrix);
for some properly set up material before drawing the box.
Parameters
box The axis aligned box to draw
color Color to use while drawing the box.
Implemented in irr::video::CNullDriver.
Referenced by irr::scene::CMeshSceneNode::render(), irr::scene::CBillboardSceneNode::render(), and irr::scene::CAnimatedMeshSceneNode::render().
draw3DLine()
virtual void irr::video::IVideoDriver::draw3DLine (const core::vector3df & start, const core::vector3df & end, SColor color = SColor(255, 255, 255, 255)) pure virtual
Draws a 3d line.
For some implementations, this method simply calls drawVertexPrimitiveList for some triangles. Note that the line is drawn using the current transformation matrix and material. So if you need to draw the 3D line independently of the current transformation, use
driver->setMaterial(someMaterial);
driver->setTransform(video::ETS_WORLD, core::IdentityMatrix);
for some properly set up material before drawing the line. Some drivers support line thickness set in the material.
Parameters
start Start of the 3d line.
end End of the 3d line.
color Color of the line.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::CNullDriver.
Referenced by irr::scene::CAnimatedMeshSceneNode::render().
drawIndexedTriangleFan() [1/3]
void irr::video::IVideoDriver::drawIndexedTriangleFan (const S3DVertex * vertices, u32 vertexCount, const u16 * indexList, u32 triangleCount) inline
Draws an indexed triangle fan.
Note that there may be at maximum 65536 vertices, because the index list is an array of 16 bit values each with a maximum value of 65536. If there are more than 65536 vertices in the list, results of this operation are not defined.
Parameters
vertices Pointer to array of vertices.
vertexCount Amount of vertices in the array.
indexList Pointer to array of indices.
triangleCount Amount of Triangles. Usually amount of indices - 2.
Definition at line 666 of file IVideoDriver.h.
References drawVertexPrimitiveList(), irr::scene::EPT_TRIANGLE_FAN, and irr::video::EVT_STANDARD.
drawIndexedTriangleFan() [2/3]
void irr::video::IVideoDriver::drawIndexedTriangleFan (const S3DVertex2TCoords * vertices, u32 vertexCount, const u16 * indexList, u32 triangleCount) inline
Draws an indexed triangle fan.
Note that there may be at maximum 65536 vertices, because the index list is an array of 16 bit values each with a maximum value of 65536. If there are more than 65536 vertices in the list, results of this operation are not defined.
Parameters
vertices Pointer to array of vertices.
vertexCount Amount of vertices in the array.
indexList Pointer to array of indices.
triangleCount Amount of Triangles. Usually amount of indices - 2.
Definition at line 681 of file IVideoDriver.h.
References drawVertexPrimitiveList(), irr::scene::EPT_TRIANGLE_FAN, and irr::video::EVT_2TCOORDS.
drawIndexedTriangleFan() [3/3]
void irr::video::IVideoDriver::drawIndexedTriangleFan (const S3DVertexTangents * vertices, u32 vertexCount, const u16 * indexList, u32 triangleCount) inline
Draws an indexed triangle fan.
Note that there may be at maximum 65536 vertices, because the index list is an array of 16 bit values each with a maximum value of 65536. If there are more than 65536 vertices in the list, results of this operation are not defined.
Parameters
vertices Pointer to array of vertices.
vertexCount Amount of vertices in the array.
indexList Pointer to array of indices.
triangleCount Amount of Triangles. Usually amount of indices - 2.
Definition at line 696 of file IVideoDriver.h.
References drawVertexPrimitiveList(), irr::scene::EPT_TRIANGLE_FAN, and irr::video::EVT_TANGENTS.
drawIndexedTriangleList() [1/3]
void irr::video::IVideoDriver::drawIndexedTriangleList (const S3DVertex * vertices, u32 vertexCount, const u16 * indexList, u32 triangleCount) inline
Draws an indexed triangle list.
Note that there may be at maximum 65536 vertices, because the index list is an array of 16 bit values each with a maximum value of 65536. If there are more than 65536 vertices in the list, results of this operation are not defined.
Parameters
vertices Pointer to array of vertices.
vertexCount Amount of vertices in the array.
indexList Pointer to array of indices.
triangleCount Amount of Triangles. Usually amount of indices / 3.
Definition at line 621 of file IVideoDriver.h.
References drawVertexPrimitiveList(), irr::scene::EPT_TRIANGLES, and irr::video::EVT_STANDARD.
Referenced by Sky::render().
drawIndexedTriangleList() [2/3]
void irr::video::IVideoDriver::drawIndexedTriangleList (const S3DVertex2TCoords * vertices, u32 vertexCount, const u16 * indexList, u32 triangleCount) inline
Draws an indexed triangle list.
Note that there may be at maximum 65536 vertices, because the index list is an array of 16 bit values each with a maximum value of 65536. If there are more than 65536 vertices in the list, results of this operation are not defined.
Parameters
vertices Pointer to array of vertices.
vertexCount Amount of vertices in the array.
indexList Pointer to array of indices.
triangleCount Amount of Triangles. Usually amount of indices / 3.
Definition at line 636 of file IVideoDriver.h.
References drawVertexPrimitiveList(), irr::scene::EPT_TRIANGLES, and irr::video::EVT_2TCOORDS.
drawIndexedTriangleList() [3/3]
void irr::video::IVideoDriver::drawIndexedTriangleList (const S3DVertexTangents * vertices, u32 vertexCount, const u16 * indexList, u32 triangleCount) inline
Draws an indexed triangle list.
Note that there may be at maximum 65536 vertices, because the index list is an array of 16 bit values each with a maximum value of 65536. If there are more than 65536 vertices in the list, results of this operation are not defined.
Parameters
vertices Pointer to array of vertices.
vertexCount Amount of vertices in the array.
indexList Pointer to array of indices.
triangleCount Amount of Triangles. Usually amount of indices / 3.
Definition at line 651 of file IVideoDriver.h.
References drawVertexPrimitiveList(), irr::scene::EPT_TRIANGLES, and irr::video::EVT_TANGENTS.
drawMeshBuffer()
virtual void irr::video::IVideoDriver::drawMeshBuffer (const scene::IMeshBuffer * mb) pure virtual
Draws a mesh buffer.
Parameters
mb Buffer to draw
Implemented in irr::video::CNullDriver.
Referenced by irr::scene::CMeshSceneNode::render(), irr::scene::CBillboardSceneNode::render(), and irr::scene::CAnimatedMeshSceneNode::render().
drawMeshBufferNormals()
virtual void irr::video::IVideoDriver::drawMeshBufferNormals (const scene::IMeshBuffer * mb, f32 length = 10.f, SColor color = 0xffffffff) pure virtual
Draws normals of a mesh buffer.
Parameters
mb Buffer to draw the normals of
length length scale factor of the normals
color Color the normals are rendered with
Implemented in irr::video::CNullDriver.
Referenced by irr::scene::CMeshSceneNode::render(), and irr::scene::CAnimatedMeshSceneNode::render().
drawVertexPrimitiveList()
virtual void irr::video::IVideoDriver::drawVertexPrimitiveList (const void * vertices, u32 vertexCount, const void * indexList, u32 primCount, E_VERTEX_TYPE vType = EVT_STANDARD, scene::E_PRIMITIVE_TYPE pType = scene::EPT_TRIANGLES, E_INDEX_TYPE iType = EIT_16BIT) pure virtual
Draws a vertex primitive list.
Note that, depending on the index type, some vertices might be not accessible through the index list. The limit is at 65535 vertices for 16bit indices. Please note that currently not all primitives are available for all drivers, and some might be emulated via triangle renders.
Parameters
vertices Pointer to array of vertices.
vertexCount Amount of vertices in the array.
indexList Pointer to array of indices. These define the vertices used for each primitive. Depending on the pType, indices are interpreted as single objects (for point like primitives), pairs (for lines), triplets (for triangles), or quads.
primCount Amount of Primitives
vType Vertex type, e.g. video::EVT_STANDARD for S3DVertex.
pType Primitive type, e.g. scene::EPT_TRIANGLE_FAN for a triangle fan.
iType Index type, e.g. video::EIT_16BIT for 16bit indices.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by drawIndexedTriangleFan(), drawIndexedTriangleList(), Clouds::render(), and Particle::render().
enableClipPlane()
virtual void irr::video::IVideoDriver::enableClipPlane (u32 index, bool enable) pure virtual
Enable or disable a clipping plane.
There are at least 6 clipping planes available for the user to set at will.
Parameters
index The plane index. Must be between 0 and MaxUserClipPlanes.
enable If true, enable the clipping plane else disable it.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
enableMaterial2D()
virtual void irr::video::IVideoDriver::enableMaterial2D (bool enable = true) pure virtual
Enable the 2d override material.
Parameters
enable Flag which tells whether the material shall be enabled or disabled.
Implemented in irr::video::CNullDriver.
endScene()
virtual bool irr::video::IVideoDriver::endScene () pure virtual
Presents the rendered image to the screen.
Applications must call this method after performing any rendering.
Returns
False if failed and true if succeeded.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by GUIEngine::run().
findTexture()
virtual video::ITexture* irr::video::IVideoDriver::findTexture (const io::path & filename) pure virtual
Check if the image is already loaded.
Works similar to getTexture(), but does not load the texture if it is not currently loaded.
Parameters
filename Name of the texture.
Returns
Pointer to loaded texture, or 0 if not found.
Implemented in irr::video::CNullDriver.
Referenced by MenuTextureSource::getTexture().
getColorFormat()
virtual ECOLOR_FORMAT irr::video::IVideoDriver::getColorFormat () const pure virtual
Get the current color format of the color buffer.
Returns
Color format of the color buffer.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
getCurrentRenderTargetSize()
virtual const core::dimension2d<u32>& irr::video::IVideoDriver::getCurrentRenderTargetSize () const pure virtual
Get the size of the current render target.
This method will return the screen size if the driver doesn't support render to texture, or if the current render target is the screen.
Returns
Size of render target or screen/window
Implemented in irr::video::CNullDriver.
Referenced by irr::scene::CCameraSceneNode::CCameraSceneNode().
getDriverAttributes()
virtual const io::IAttributes& irr::video::IVideoDriver::getDriverAttributes () const pure virtual
Get attributes of the actual video driver.
The following names can be queried for the given types: MaxTextures (int) The maximum number of simultaneous textures supported by the driver. This can be less than the supported number of textures of the driver. Use IRR_MATERIAL_MAX_TEXTURES to adapt the number. MaxSupportedTextures (int) The maximum number of simultaneous textures supported by the fixed function pipeline of the (hw) driver. The actual supported number of textures supported by the engine can be lower. MaxLights (int) Number of hardware lights supported in the fixed function pipeline of the driver, typically 6-8. Use light manager or deferred shading for more. MaxAnisotropy (int) Number of anisotropy levels supported for filtering. At least 1, max is typically at 16 or 32. MaxUserClipPlanes (int) Number of additional clip planes, which can be set by the user via dedicated driver methods. MaxAuxBuffers (int) Special render buffers, which are currently not really usable inside Irrlicht. Only supported by OpenGL MaxMultipleRenderTargets (int) Number of render targets which can be bound simultaneously. Rendering to MRTs is done via shaders. MaxIndices (int) Number of indices which can be used in one render call (i.e. one mesh buffer). MaxTextureSize (int) Dimension that a texture may have, both in width and height. MaxGeometryVerticesOut (int) Number of vertices the geometry shader can output in one pass. Only OpenGL so far. MaxTextureLODBias (float) Maximum value for LOD bias. Is usually at around 16, but can be lower on some systems. Version (int) Version of the driver. Should be Major*100+Minor ShaderLanguageVersion (int) Version of the high level shader language. Should be Major*100+Minor. AntiAlias (int) Number of Samples the driver uses for each pixel. 0 and 1 means anti aliasing is off, typical values are 2,4,8,16,32
Implemented in irr::video::CNullDriver.
getDriverType()
virtual E_DRIVER_TYPE irr::video::IVideoDriver::getDriverType () const pure virtual
Get type of video driver.
Returns
Type of driver.
Implemented in irr::video::CNullDriver, irr::video::COpenGL3DriverBase, irr::video::COpenGL3Driver, and irr::video::COpenGLES2Driver.
Referenced by irr::scene::CCameraSceneNode::CCameraSceneNode().
getExposedVideoData()
virtual const SExposedVideoData& irr::video::IVideoDriver::getExposedVideoData () pure virtual
Returns driver and operating system specific data about the IVideoDriver.
This method should only be used if the engine should be extended without having to modify the source of the engine.
Returns
Collection of device dependent pointers.
Implemented in irr::video::CNullDriver.
getFPS()
virtual s32 irr::video::IVideoDriver::getFPS () const pure virtual
Returns current frames per second value.
This value is updated approximately every 1.5 seconds and is only intended to provide a rough guide to the average frame rate. It is not suitable for use in performing timing calculations or framerate independent movement.
Returns
Approximate amount of frames per second drawn.
Implemented in irr::video::CNullDriver.
getGPUProgrammingServices()
virtual IGPUProgrammingServices* irr::video::IVideoDriver::getGPUProgrammingServices () pure virtual
Gets the IGPUProgrammingServices interface.
Returns
Pointer to the IGPUProgrammingServices. Returns 0 if the video driver does not support this. For example the Software driver and the Null driver will always return 0.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
getImageLoader()
virtual IImageLoader* irr::video::IVideoDriver::getImageLoader (u32 n) pure virtual
Retrieve the given image loader.
Parameters
n The index of the loader to retrieve. This parameter is an 0-based array index.
Returns
A pointer to the specified loader, 0 if the index is incorrect.
Implemented in irr::video::CNullDriver.
getImageLoaderCount()
virtual u32 irr::video::IVideoDriver::getImageLoaderCount () const pure virtual
Retrieve the number of image loaders.
Returns
Number of image loaders
Implemented in irr::video::CNullDriver.
getImageWriter()
virtual IImageWriter* irr::video::IVideoDriver::getImageWriter (u32 n) pure virtual
Retrieve the given image writer.
Parameters
n The index of the writer to retrieve. This parameter is an 0-based array index.
Returns
A pointer to the specified writer, 0 if the index is incorrect.
Implemented in irr::video::CNullDriver.
getImageWriterCount()
virtual u32 irr::video::IVideoDriver::getImageWriterCount () const pure virtual
Retrieve the number of image writers.
Returns
Number of image writers
Implemented in irr::video::CNullDriver.
getMaterial2D()
virtual SMaterial& irr::video::IVideoDriver::getMaterial2D () pure virtual
Get the 2d override material for altering its values.
The 2d override material allows to alter certain render states of the 2d methods. Not all members of SMaterial are honored, especially not MaterialType and Textures. Moreover, the zbuffer is always ignored, and lighting is always off. All other flags can be changed, though some might have to effect in most cases. Please note that you have to enable/disable this effect with enableMaterial2D(). This effect is costly, as it increases the number of state changes considerably. Always reset the values when done.
Returns
Material reference which should be altered to reflect the new settings.
Implemented in irr::video::CNullDriver.
getMaterialRenderer()
virtual IMaterialRenderer* irr::video::IVideoDriver::getMaterialRenderer (u32 idx) const pure virtual
Get access to a material renderer by index.
Parameters
idx Id of the material renderer. Can be a value of the E_MATERIAL_TYPE enum or a value which was returned by addMaterialRenderer().
Returns
Pointer to material renderer or null if not existing.
Implemented in irr::video::CNullDriver.
getMaterialRendererCount()
virtual u32 irr::video::IVideoDriver::getMaterialRendererCount () const pure virtual
Get amount of currently available material renderers.
Returns
Amount of currently available material renderers.
Implemented in irr::video::CNullDriver.
getMaterialRendererName()
virtual const c8* irr::video::IVideoDriver::getMaterialRendererName (u32 idx) const pure virtual
Get name of a material renderer.
This string can, e.g., be used to test if a specific renderer already has been registered/created, or use this string to store data about materials: This returned name will be also used when serializing materials.
Parameters
idx Id of the material renderer. Can be a value of the E_MATERIAL_TYPE enum or a value which was returned by addMaterialRenderer().
Returns
String with the name of the renderer, or 0 if not exisiting
Implemented in irr::video::CNullDriver.
getMaximalPrimitiveCount()
virtual u32 irr::video::IVideoDriver::getMaximalPrimitiveCount () const pure virtual
Returns the maximum amount of primitives.
(mostly vertices) which the device is able to render with one drawVertexPrimitiveList call.
Returns
Maximum amount of primitives.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
getName()
virtual const wchar_t* irr::video::IVideoDriver::getName () const pure virtual
Gets name of this video driver.
Returns
Returns the name of the video driver, e.g. in case of the Direct3D8 driver, it would return "Direct3D 8.1".
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
getOcclusionQueryResult()
virtual u32 irr::video::IVideoDriver::getOcclusionQueryResult (scene::ISceneNode * node) const pure virtual
Return query result.
Return value is the number of visible pixels/fragments. The value is a safe approximation, i.e. can be larger than the actual value of pixels.
Implemented in irr::video::CNullDriver.
Referenced by irr::scene::CSceneManager::isCulled().
getOverrideMaterial()
virtual SOverrideMaterial& irr::video::IVideoDriver::getOverrideMaterial () pure virtual
Get the global Material, which might override local materials.
Depending on the enable flags, values from this Material are used to override those of local materials of some meshbuffer being rendered.
Returns
Reference to the Override Material.
Implemented in irr::video::CNullDriver.
Referenced by ConfigureOverrideMaterialTarget::activate(), irr::scene::CSceneManager::drawAll(), and SetColorMaskStep::run().
getPrimitiveCountDrawn()
virtual u32 irr::video::IVideoDriver::getPrimitiveCountDrawn (u32 mode = 0) const pure virtual
Returns amount of primitives (mostly triangles) which were drawn in the last frame.
Together with getFPS() very useful method for statistics.
Parameters
mode Defines if the primitives drawn are accumulated or counted per frame.
Returns
Amount of primitives drawn in the last frame.
Implemented in irr::video::CNullDriver.
getScreenSize()
virtual const core::dimension2d<u32>& irr::video::IVideoDriver::getScreenSize () const pure virtual
Get the size of the screen or render window.
Returns
Size of screen or render window.
Implemented in irr::video::CNullDriver.
Referenced by GUIModalMenu::draw(), GUIChatConsole::draw(), irr::gui::CGUIEnvironment::drawAll(), GUIEngine::drawBackground(), GUIEngine::drawFooter(), GUIEngine::drawHeader(), GUIEngine::drawOverlay(), ScreenTarget::reset(), and DrawImageStep::run().
getTexture() [1/2]
virtual ITexture* irr::video::IVideoDriver::getTexture (const io::path & filename) pure virtual
Get access to a named texture.
Loads the texture from disk if it is not already loaded and generates mipmap levels if desired. Texture loading can be influenced using the setTextureCreationFlag() method. The texture can be in several imageformats, such as BMP, JPG, TGA, PCX, PNG, and PSD.
Parameters
filename Filename of the texture to be loaded.
Returns
Pointer to the texture, or 0 if the texture could not be loaded. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
Referenced by GUIEngine::setTexture().
getTexture() [2/2]
virtual ITexture* irr::video::IVideoDriver::getTexture (io::IReadFile * file) pure virtual
Get access to a named texture.
Loads the texture from disk if it is not already loaded and generates mipmap levels if desired. Texture loading can be influenced using the setTextureCreationFlag() method. The texture can be in several imageformats, such as BMP, JPG, TGA, PCX, PNG, and PSD.
Parameters
file Pointer to an already opened file.
Returns
Pointer to the texture, or 0 if the texture could not be loaded. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
getTextureByIndex()
virtual ITexture* irr::video::IVideoDriver::getTextureByIndex (u32 index) pure virtual
Returns a texture by index.
Parameters
index Index of the texture, must be smaller than getTextureCount() Please note that this index might change when adding or removing textures
Returns
Pointer to the texture, or 0 if the texture was not set or index is out of bounds. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::video::CNullDriver.
getTextureCount()
virtual u32 irr::video::IVideoDriver::getTextureCount () const pure virtual
Returns amount of textures currently loaded.
Returns
Amount of textures currently loaded
Implemented in irr::video::CNullDriver.
Referenced by MenuTextureSource::~MenuTextureSource().
getTextureCreationFlag()
virtual bool irr::video::IVideoDriver::getTextureCreationFlag (E_TEXTURE_CREATION_FLAG flag) const pure virtual
Returns if a texture creation flag is enabled or disabled.
You can change this value using setTextureCreationFlag().
Parameters
flag Texture creation flag.
Returns
The current texture creation flag enabled mode.
Implemented in irr::video::CNullDriver.
Referenced by irr::gui::CGUITTGlyphPage::createPageTexture().
getTransform()
virtual const core::matrix4& irr::video::IVideoDriver::getTransform (E_TRANSFORMATION_STATE state) const pure virtual
Returns the transformation set by setTransform.
Parameters
state Transformation type to query
Returns
Matrix describing the transformation.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by irr::video::COpenGL3MaterialBaseCB::OnSetConstants(), irr::video::COpenGL3MaterialSolidCB::OnSetConstants(), and irr::video::COpenGL3MaterialOneTextureBlendCB::OnSetConstants().
getViewPort()
virtual const core::rect<s32>& irr::video::IVideoDriver::getViewPort () const pure virtual
Gets the area of the current viewport.
Returns
Rectangle of the current viewport.
Implemented in irr::video::CNullDriver.
Referenced by GUIScene::draw(), and irr::scene::CSceneCollisionManager::getRayFromScreenCoordinates().
makeColorKeyTexture() [1/2]
virtual void irr::video::IVideoDriver::makeColorKeyTexture (video::ITexture * texture, core::position2d< s32 > colorKeyPixelPos, bool zeroTexels = false) const pure virtual
Sets a boolean alpha channel on the texture based on the color at a position.
This makes the texture fully transparent at the texels where the color key can be found when using for example draw2DImage with useAlphachannel==true. The alpha of other texels is not modified.
Parameters
texture Texture whose alpha channel is modified.
colorKeyPixelPos Position of a pixel with the color key color. Every texel with this color will become fully transparent as described above.
zeroTexels (deprecated) If set to true, then any texels that match the color key will have their color, as well as their alpha, set to zero (i.e. black). This behavior matches the legacy (buggy) behavior prior to release 1.5 and is provided for backwards compatibility only. This parameter may be removed by Irrlicht 1.9.
Implemented in irr::video::CNullDriver.
makeColorKeyTexture() [2/2]
virtual void irr::video::IVideoDriver::makeColorKeyTexture (video::ITexture * texture, video::SColor color, bool zeroTexels = false) const pure virtual
Sets a boolean alpha channel on the texture based on a color key.
This makes the texture fully transparent at the texels where this color key can be found when using for example draw2DImage with useAlphachannel==true. The alpha of other texels is not modified.
Parameters
texture Texture whose alpha channel is modified.
color Color key color. Every texel with this color will become fully transparent as described above. Please note that the colors of a texture may be converted when loading it, so the color values may not be exactly the same in the engine and for example in picture edit programs. To avoid this problem, you could use the makeColorKeyTexture method, which takes the position of a pixel instead a color value.
zeroTexels (deprecated) If set to true, then any texels that match the color key will have their color, as well as their alpha, set to zero (i.e. black). This behavior matches the legacy (buggy) behavior prior to release 1.5 and is provided for backwards compatibility only. This parameter may be removed by Irrlicht 1.9.
Implemented in irr::video::CNullDriver.
OnResize()
virtual void irr::video::IVideoDriver::OnResize (const core::dimension2d< u32 > & size) pure virtual
Event handler for resize events. Only used by the engine internally.
Used to notify the driver that the window was resized. Usually, there is no need to call this method.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by TextureBufferOutput::activate().
queryFeature()
virtual bool irr::video::IVideoDriver::queryFeature (E_VIDEO_DRIVER_FEATURE feature) const pure virtual
Queries the features of the driver.
Returns true if a feature is available
Parameters
feature Feature to query.
Returns
True if the feature is available, false if not.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::CNullDriver.
Referenced by irr::gui::SGUITTGlyph::createGlyphImage().
queryTextureFormat()
virtual bool irr::video::IVideoDriver::queryTextureFormat (ECOLOR_FORMAT format) const pure virtual
Check if the driver supports creating textures with the given color format.
Returns
True if the format is available, false if not.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
removeAllTextures()
virtual void irr::video::IVideoDriver::removeAllTextures () pure virtual
Removes all textures from the texture cache and deletes them.
This method can free a lot of memory! Please note that after calling this, the pointer to the ITexture may no longer be valid, if it was not grabbed before by other parts of the engine for storing it longer. So it is a good idea to set all materials which are using this texture to 0 or another texture first.
Implemented in irr::video::CNullDriver.
removeTexture()
virtual void irr::video::IVideoDriver::removeTexture (ITexture * texture) pure virtual
Removes a texture from the texture cache and deletes it.
This method can free a lot of memory! Please note that after calling this, the pointer to the ITexture may no longer be valid, if it was not grabbed before by other parts of the engine for storing it longer. So it is a good idea to set all materials which are using this texture to 0 or another texture first.
Parameters
texture Texture to delete from the engine cache.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by TextureBuffer::ensureTexture(), GUIEngine::setTexture(), GUIEngine::~GUIEngine(), and MenuTextureSource::~MenuTextureSource().
renameTexture()
virtual void irr::video::IVideoDriver::renameTexture (ITexture * texture, const io::path & newName) pure virtual
Renames a texture.
Parameters
texture Pointer to the texture to rename.
newName New name for the texture. This should be a unique name.
Implemented in irr::video::CNullDriver.
runAllOcclusionQueries()
virtual void irr::video::IVideoDriver::runAllOcclusionQueries (bool visible = false) pure virtual
Run all occlusion queries. Draws all meshes stored in queries.
If the meshes shall not be rendered visible, use overrideMaterial to disable the color and depth buffer.
Implemented in irr::video::CNullDriver.
runOcclusionQuery()
virtual void irr::video::IVideoDriver::runOcclusionQuery (scene::ISceneNode * node, bool visible = false) pure virtual
Run occlusion query. Draws mesh stored in query.
If the mesh shall not be rendered visible, use overrideMaterial to disable the color and depth buffer.
Implemented in irr::video::CNullDriver.
setAllowZWriteOnTransparent()
virtual void irr::video::IVideoDriver::setAllowZWriteOnTransparent (bool flag) pure virtual
Only used by the engine internally.
Passes the global material flag AllowZWriteOnTransparent. Use the SceneManager attribute to set this value from your app.
Parameters
flag Default behavior is to disable ZWrite, i.e. false.
Implemented in irr::video::CNullDriver.
Referenced by irr::scene::CSceneManager::drawAll().
setAmbientLight()
virtual void irr::video::IVideoDriver::setAmbientLight (const SColorf & color) pure virtual
Only used by the engine internally.
The ambient color is set in the scene manager, see scene::ISceneManager::setAmbientLight().
Parameters
color New color of the ambient light.
Implemented in irr::video::CNullDriver.
setClipPlane()
virtual bool irr::video::IVideoDriver::setClipPlane (u32 index, const core::plane3df & plane, bool enable = false) pure virtual
Set or unset a clipping plane.
There are at least 6 clipping planes available for the user to set at will.
Parameters
index The plane index. Must be between 0 and MaxUserClipPlanes.
plane The plane itself.
enable If true, enable the clipping plane else disable it.
Returns
True if the clipping plane is usable.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
setFog()
virtual void irr::video::IVideoDriver::setFog (SColor color = SColor(0, 255, 255, 255), E_FOG_TYPE fogType = EFT_FOG_LINEAR, f32 start = 50.0f, f32 end = 100.0f, f32 density = 0.01f, bool pixelFog = false, bool rangeFog = false) pure virtual
Sets the fog mode.
These are global values attached to each 3d object rendered, which has the fog flag enabled in its material.
Parameters
color Color of the fog
fogType Type of fog used
start Only used in linear fog mode (linearFog=true). Specifies where fog starts.
end Only used in linear fog mode (linearFog=true). Specifies where fog ends.
density Only used in exponential fog mode (linearFog=false). Must be a value between 0 and 1.
pixelFog Set this to false for vertex fog, and true if you want per-pixel fog.
rangeFog Set this to true to enable range-based vertex fog. The distance from the viewer is used to compute the fog, not the z-coordinate. This is better, but slower. This might not be available with all drivers and fog settings.
Implemented in irr::video::CNullDriver.
Referenced by Clouds::render(), and GUIEngine::run().
setMaterial()
virtual void irr::video::IVideoDriver::setMaterial (const SMaterial & material) pure virtual
Sets a material.
All 3d drawing functions will draw geometry using this material thereafter.
Parameters
material Material to be used from now on.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::CNullDriver.
Referenced by irr::scene::CSceneManager::drawAll(), irr::scene::CSceneManager::removeAll(), irr::scene::CMeshSceneNode::render(), irr::scene::CBillboardSceneNode::render(), irr::scene::CAnimatedMeshSceneNode::render(), Sky::render(), Clouds::render(), and Particle::render().
setMaterialRendererName()
virtual void irr::video::IVideoDriver::setMaterialRendererName (u32 idx, const c8 * name) pure virtual
Sets the name of a material renderer.
Will have no effect on built-in material renderers.
Parameters
idx Id of the material renderer. Can be a value of the E_MATERIAL_TYPE enum or a value which was returned by addMaterialRenderer().
name New name of the material renderer.
Implemented in irr::video::CNullDriver.
setMinHardwareBufferVertexCount()
virtual void irr::video::IVideoDriver::setMinHardwareBufferVertexCount (u32 count) pure virtual
Set the minimum number of vertices for which a hw buffer will be created.
Parameters
count Number of vertices to set as minimum.
Implemented in irr::video::CNullDriver.
setRenderTarget() [1/2]
bool irr::video::IVideoDriver::setRenderTarget (ITexture * texture, bool clearBackBuffer, bool clearZBuffer, SColor color = SColor(255,0,0,0)) inline
Sets a new render target. Prefer to use the setRenderTarget function taking flags as parameter as this one can't clear the stencil buffer. It's still offered for backward compatibility.
Definition at line 542 of file IVideoDriver.h.
References clearZBuffer(), and setRenderTarget().
setRenderTarget() [2/2]
virtual bool irr::video::IVideoDriver::setRenderTarget (ITexture * texture, u16 clearFlag = ECBF_COLOR|ECBF_DEPTH, SColor clearColor = SColor(255, 0, 0, 0), f32 clearDepth = 1.f, u8 clearStencil = 0) pure virtual
Sets a new render target.
This will only work if the driver supports the EVDF_RENDER_TO_TARGET feature, which can be queried with queryFeature(). Usually, rendering to textures is done in this way:
// create render target
ITexture* target = driver->addRenderTargetTexture(core::dimension2d<u32>(128,128), "rtt1");
// ...
driver->setRenderTarget(target); // set render target
// .. draw stuff here
driver->setRenderTarget(0); // set previous render target
Please note that you cannot render 3D or 2D geometry with a render target as texture on it when you are rendering the scene into this render target at the same time. It is usually only possible to render into a texture between the IVideoDriver::beginScene() and endScene() method calls.
Parameters
texture New render target. Must be a texture created with IVideoDriver::addRenderTargetTexture(). If set to nullptr, it makes the window the current render target.
clearFlag A combination of the E_CLEAR_BUFFER_FLAG bit-flags.
clearColor The clear color for the color buffer.
clearDepth The clear value for the depth buffer.
clearStencil The clear value for the stencil buffer.
Returns
True if successful and false if not.
Implemented in irr::video::CNullDriver.
Referenced by TextureBufferOutput::activate(), ScreenTarget::activate(), and setRenderTarget().
setRenderTargetEx()
virtual bool irr::video::IVideoDriver::setRenderTargetEx (IRenderTarget * target, u16 clearFlag, SColor clearColor = SColor(255, 0, 0, 0), f32 clearDepth = 1.f, u8 clearStencil = 0) pure virtual
Set a render target.
This will only work if the driver supports the EVDF_RENDER_TO_TARGET feature, which can be queried with queryFeature(). Please note that you cannot render 3D or 2D geometry with a render target as texture on it when you are rendering the scene into this render target at the same time. It is usually only possible to render into a texture between the IVideoDriver::beginScene() and endScene() method calls. If you need the best performance use this method instead of setRenderTarget.
Parameters
target Render target object. If set to nullptr, it makes the window the current render target.
clearFlag A combination of the E_CLEAR_BUFFER_FLAG bit-flags.
clearColor The clear color for the color buffer.
clearDepth The clear value for the depth buffer.
clearStencil The clear value for the stencil buffer.
Returns
True if successful and false if not.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::CNullDriver.
Referenced by TextureBufferOutput::activate().
setTextureCreationFlag()
virtual void irr::video::IVideoDriver::setTextureCreationFlag (E_TEXTURE_CREATION_FLAG flag, bool enabled = true) pure virtual
Enables or disables a texture creation flag.
These flags define how textures should be created. By changing this value, you can influence for example the speed of rendering a lot. But please note that the video drivers take this value only as recommendation. It could happen that you enable the ETCF_ALWAYS_16_BIT mode, but the driver still creates 32 bit textures.
Parameters
flag Texture creation flag.
enabled Specifies if the given flag should be enabled or disabled.
Implemented in irr::video::CNullDriver.
Referenced by irr::gui::CGUITTGlyphPage::createPageTexture().
setTransform()
virtual void irr::video::IVideoDriver::setTransform (E_TRANSFORMATION_STATE state, const core::matrix4 & mat) pure virtual
Sets transformation matrices.
Parameters
state Transformation type to be set, e.g. view, world, or projection.
mat Matrix describing the transformation.
Implemented in irr::video::CNullDriver, and irr::video::COpenGL3DriverBase.
Referenced by irr::scene::CSceneManager::drawAll(), irr::scene::CMeshSceneNode::render(), irr::scene::CBillboardSceneNode::render(), irr::scene::CAnimatedMeshSceneNode::render(), Sky::render(), Clouds::render(), Particle::render(), ClientMap::render(), irr::scene::CCameraSceneNode::render(), and Draw3D::run().
setViewPort()
virtual void irr::video::IVideoDriver::setViewPort (const core::rect< s32 > & area) pure virtual
Sets a new viewport.
Every rendering operation is done into this new area.
Parameters
area Rectangle defining the new area of rendering operations.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::CNullDriver.
Referenced by GUIScene::draw().
swapMaterialRenderers()
virtual void irr::video::IVideoDriver::swapMaterialRenderers (u32 idx1, u32 idx2, bool swapNames = true) pure virtual
Swap the material renderers used for certain id's.
Swap the IMaterialRenderers responsible for rendering specific material-id's. This means every SMaterial using a MaterialType with one of the indices involved here will now render differently.
Parameters
idx1 First material index to swap. It must already exist or nothing happens.
idx2 Second material index to swap. It must already exist or nothing happens.
swapNames When true the renderer names also swap When false the names will stay at the original index
Implemented in irr::video::CNullDriver.
updateAllOcclusionQueries()
virtual void irr::video::IVideoDriver::updateAllOcclusionQueries (bool block = true) pure virtual
Update all occlusion queries. Retrieves results from GPU.
If the query shall not block, set the flag to false. Update might not occur in this case, though
Implemented in irr::video::CNullDriver.
updateOcclusionQuery()
virtual void irr::video::IVideoDriver::updateOcclusionQuery (scene::ISceneNode * node, bool block = true) pure virtual
Update occlusion query. Retrieves results from GPU.
If the query shall not block, set the flag to false. Update might not occur in this case, though
Implemented in irr::video::CNullDriver.
writeImageToFile() [1/2]
virtual bool irr::video::IVideoDriver::writeImageToFile (IImage * image, const io::path & filename, u32 param = 0) pure virtual
Writes the provided image to a file.
Requires that there is a suitable image writer registered for writing the image.
Parameters
image Image to write.
filename Name of the file to write.
param Control parameter for the backend (e.g. compression level).
Returns
True on successful write.
Implemented in irr::video::CNullDriver.
writeImageToFile() [2/2]
virtual bool irr::video::IVideoDriver::writeImageToFile (IImage * image, io::IWriteFile * file, u32 param = 0) pure virtual
Writes the provided image to a file.
Requires that there is a suitable image writer registered for writing the image.
Parameters
image Image to write.
file An already open io::IWriteFile object. The name will be used to determine the appropriate image writer to use.
param Control parameter for the backend (e.g. compression level).
Returns
True on successful write.
Implemented in irr::video::CNullDriver.
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IVideoDriver.h