Three Cubes Game: irr::video::COpenGL3MaterialBaseCB Class Reference
irr::video::COpenGL3MaterialBaseCB Class Reference
Public Member Functions
virtual void OnSetMaterial (const SMaterial &material)
Called to let the callBack know the used material (optional method)
virtual void OnSetConstants (IMaterialRendererServices *services, s32 userData)
Called by the engine when the vertex and/or pixel shader constants for an material renderer should be set.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Protected Attributes
bool FirstUpdateBase
s32 WVPMatrixID
s32 WVMatrixID
s32 NMatrixID
s32 FogEnableID
s32 FogTypeID
s32 FogColorID
s32 FogStartID
s32 FogEndID
s32 FogDensityID
s32 ThicknessID
bool LightEnable
SColorf GlobalAmbient
SColorf MaterialAmbient
SColorf MaterialDiffuse
SColorf MaterialEmissive
SColorf MaterialSpecular
f32 MaterialShininess
s32 FogEnable
s32 FogType
SColorf FogColor
f32 FogStart
f32 FogEnd
f32 FogDensity
f32 Thickness
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Definition at line 16 of file FixedPipelineRenderer.h.
Member Function Documentation
OnSetConstants()
void irr::video::COpenGL3MaterialBaseCB::OnSetConstants (IMaterialRendererServices * services, s32 userData) virtual
Called by the engine when the vertex and/or pixel shader constants for an material renderer should be set.
Implement the IShaderConstantSetCallBack in an own class and implement your own OnSetConstants method using the given IMaterialRendererServices interface. Pass a pointer to this class to one of the methods in IGPUProgrammingServices when creating a shader. The OnSetConstants method will now be called every time before geometry is being drawn using your shader material. A sample implementation would look like this:
virtual void OnSetConstants(video::IMaterialRendererServices* services, s32 userData)
{
    video::IVideoDriver* driver = services->getVideoDriver();
    // set clip matrix at register 4
    core::matrix4 worldViewProj(driver->getTransform(video::ETS_PROJECTION));
    worldViewProj *= driver->getTransform(video::ETS_VIEW);
    worldViewProj *= driver->getTransform(video::ETS_WORLD);
    services->setVertexShaderConstant(&worldViewProj.M[0], 4, 4);
    // for high level shading languages, this would be another solution:
    //services->setVertexShaderConstant("mWorldViewProj", worldViewProj.M, 16);
    // set some light color at register 9
    video::SColorf col(0.0f,1.0f,1.0f,0.0f);
    services->setVertexShaderConstant(reinterpret_cast<const f32*>(&col), 9, 1);
    // for high level shading languages, this would be another solution:
    //services->setVertexShaderConstant("myColor", reinterpret_cast<f32*>(&col), 4);
}
Parameters
services Pointer to an interface providing methods to set the constants for the shader.
userData Userdata int which can be specified when creating the shader.
Implements irr::video::IShaderConstantSetCallBack.
Reimplemented in irr::video::COpenGL3MaterialOneTextureBlendCB, and irr::video::COpenGL3MaterialSolidCB.
Definition at line 39 of file FixedPipelineRenderer.cpp.
References irr::video::ETS_PROJECTION, irr::video::ETS_VIEW, irr::video::ETS_WORLD, irr::video::IVideoDriver::getFog(), irr::video::IVideoDriver::getTransform(), irr::core::CMatrix4< T >::getTransposed(), irr::video::IMaterialRendererServices::getVertexShaderConstantID(), irr::video::IMaterialRendererServices::getVideoDriver(), irr::core::CMatrix4< T >::makeInverse(), irr::core::CMatrix4< T >::pointer(), and irr::video::IMaterialRendererServices::setPixelShaderConstant().
Referenced by irr::video::COpenGL3MaterialSolidCB::OnSetConstants(), and irr::video::COpenGL3MaterialOneTextureBlendCB::OnSetConstants().
OnSetMaterial()
void irr::video::COpenGL3MaterialBaseCB::OnSetMaterial (const SMaterial & material) virtual
Called to let the callBack know the used material (optional method)
class MyCallBack : public IShaderConstantSetCallBack
{
    const video::SMaterial *UsedMaterial;
    OnSetMaterial(const video::SMaterial& material)
    {
        UsedMaterial=&material;
    }
    OnSetConstants(IMaterialRendererServices* services, s32 userData)
    {
        services->setVertexShaderConstant("myColor", reinterpret_cast<f32*>(&UsedMaterial->color), 4);
    }
}
Reimplemented from irr::video::IShaderConstantSetCallBack.
Reimplemented in irr::video::COpenGL3MaterialOneTextureBlendCB, and irr::video::COpenGL3MaterialSolidCB.
Definition at line 25 of file FixedPipelineRenderer.cpp.
References irr::video::SMaterial::AmbientColor, irr::video::SMaterial::DiffuseColor, irr::video::SMaterial::EmissiveColor, irr::video::SMaterial::FogEnable, irr::video::SMaterial::Lighting, irr::video::SMaterial::Shininess, irr::video::SMaterial::SpecularColor, and irr::video::SMaterial::Thickness.
Referenced by irr::video::COpenGL3MaterialSolidCB::OnSetMaterial(), and irr::video::COpenGL3MaterialOneTextureBlendCB::OnSetMaterial().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/OpenGL/FixedPipelineRenderer.h
lib/irrlichtmt/source/Irrlicht/OpenGL/FixedPipelineRenderer.cpp