Three Cubes Game: irr::core::ustring16 Class Reference
irr::core::ustring16 Class Reference
UTF-16 string class.
#include <irrUString.h>
Classes
class _ustring16_const_iterator
Iterator to iterate through a UTF-16 string.
class _ustring16_iterator
Iterator to iterate through a UTF-16 string.
class _ustring16_iterator_access
Access an element in a unicode string, allowing one to change it.
Public Types
typedef ustring16::_ustring16_iterator_access access
typedef ustring16::_ustring16_iterator iterator
typedef ustring16::_ustring16_const_iterator const_iterator
Public Member Functions
ustring16 ()
Default constructor.
ustring16 (const ustring16 &other)
Constructor.
template<class B >
ustring16 (const string< B > &other)
Constructor from other string types.
template<class B , class A , typename Alloc >
ustring16 (const std::basic_string< B, A, Alloc > &other)
Constructor from std::string.
template<typename Itr >
ustring16 (Itr first, Itr last)
Constructor from iterator.
ustring16 (const uchar8_t *const c)
Constructor for copying a UTF-8 string from a pointer.
ustring16 (const char c)
Constructor for copying a UTF-8 string from a single char.
ustring16 (const uchar8_t *const c, u32 length)
Constructor for copying a UTF-8 string from a pointer with a given length.
ustring16 (const uchar16_t *const c)
Constructor for copying a UTF-16 string from a pointer.
ustring16 (const uchar16_t *const c, u32 length)
Constructor for copying a UTF-16 string from a pointer with a given length.
ustring16 (const uchar32_t *const c)
Constructor for copying a UTF-32 string from a pointer.
ustring16 (const uchar32_t *const c, u32 length)
Constructor for copying a UTF-32 from a pointer with a given length.
ustring16 (const wchar_t *const c)
Constructor for copying a wchar_t string from a pointer.
ustring16 (const wchar_t *const c, u32 length)
Constructor for copying a wchar_t string from a pointer with a given length.
ustring16 (ustring16 &&other)
Constructor for moving a ustring16.
~ustring16 ()
Destructor.
ustring16 & operator= (const ustring16 &other)
Assignment operator.
ustring16 & operator= (ustring16 &&other)
Move assignment operator.
template<class B >
ustring16 & operator= (const string< B > &other)
Assignment operator for other string types.
ustring16 & operator= (const uchar8_t *const c)
Assignment operator for UTF-8 strings.
ustring16 & operator= (const uchar16_t *const c)
Assignment operator for UTF-16 strings.
ustring16 & operator= (const uchar32_t *const c)
Assignment operator for UTF-32 strings.
ustring16 & operator= (const wchar_t *const c)
Assignment operator for wchar_t strings.
template<class B >
ustring16 & operator= (const B *const c)
Assignment operator for other strings.
access operator[] (const u32 index)
Direct access operator.
const access operator[] (const u32 index) const
Direct access operator.
bool operator== (const uchar16_t *const str) const
Equality operator.
bool operator== (const ustring16 &other) const
Equality operator.
bool operator< (const ustring16 &other) const
Is smaller comparator.
bool operator!= (const uchar16_t *const str) const
Inequality operator.
bool operator!= (const ustring16 &other) const
Inequality operator.
u32 size () const
bool empty () const
const uchar16_t * c_str () const
bool equalsn (const ustring16 &other, u32 n) const
bool equalsn (const uchar16_t *const str, u32 n) const
ustring16 & append (uchar32_t character)
ustring16 & append (const uchar8_t *const other, u32 length=0xffffffff)
ustring16 & append (const uchar16_t *const other, u32 length=0xffffffff)
ustring16 & append (const uchar32_t *const other, u32 length=0xffffffff)
ustring16 & append (const ustring16 &other)
ustring16 & append (const ustring16 &other, u32 length)
void reserve (u32 count)
s32 findFirst (uchar32_t c) const
s32 findFirstChar (const uchar32_t *const c, u32 count=1) const
s32 findFirstCharNotInList (const uchar32_t *const c, u32 count=1) const
s32 findLastCharNotInList (const uchar32_t *const c, u32 count=1) const
s32 findNext (uchar32_t c, u32 startPos) const
s32 findLast (uchar32_t c, s32 start=-1) const
s32 findLastChar (const uchar32_t *const c, u32 count=1) const
s32 find (const ustring16 &str, const u32 start=0) const
s32 find_raw (const ustring16 &str, const u32 start=0) const
ustring16 subString (u32 begin, s32 length) const
ustring16 & operator+= (char c)
ustring16 & operator+= (uchar32_t c)
ustring16 & operator+= (short c)
ustring16 & operator+= (unsigned short c)
ustring16 & operator+= (int c)
ustring16 & operator+= (unsigned int c)
ustring16 & operator+= (long c)
ustring16 & operator+= (unsigned long c)
ustring16 & operator+= (double c)
ustring16 & operator+= (const uchar16_t *const c)
ustring16 & operator+= (const ustring16 &other)
ustring16 & replace (uchar32_t toReplace, uchar32_t replaceWith)
ustring16 & replace (const ustring16 &toReplace, const ustring16 &replaceWith)
ustring16 & remove (uchar32_t c)
ustring16 & remove (const ustring16 &toRemove)
ustring16 & removeChars (const ustring16 &characters)
ustring16 & trim (const ustring16 &whitespace=" \t\n\r")
ustring16 & erase (u32 index)
ustring16 & validate ()
uchar32_t lastChar () const
template<class container >
u32 split (container &ret, const uchar32_t *const c, u32 count=1, bool ignoreEmptyTokens=true, bool keepSeparators=false) const
Split the ustring16 into parts.
template<class container >
u32 split (container &ret, const ustring16 &c, bool ignoreEmptyTokens=true, bool keepSeparators=false) const
Split the ustring16 into parts.
u32 capacity () const
u32 size_raw () const
ustring16 & insert (uchar32_t c, u32 pos)
ustring16 & insert (const ustring16 &c, u32 pos)
ustring16 & insert_raw (uchar16_t c, u32 pos)
ustring16 & erase_raw (u32 pos)
ustring16 & replace_raw (uchar16_t c, u32 pos)
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
core::string< uchar8_t > toUTF8_s (const bool addBOM=false) const
core::array< uchar8_t > toUTF8 (const bool addBOM=false) const
core::array< uchar16_t > toUTF16 (const unicode::EUTF_ENDIAN endian=unicode::EUTFEE_NATIVE, const bool addBOM=false) const
core::array< uchar32_t > toUTF32 (const unicode::EUTF_ENDIAN endian=unicode::EUTFEE_NATIVE, const bool addBOM=false) const
core::string< wchar_t > toWCHAR_s (const unicode::EUTF_ENDIAN endian=unicode::EUTFEE_NATIVE, const bool addBOM=false) const
Converts the string to a wchar_t encoded string.
core::array< wchar_t > toWCHAR (const unicode::EUTF_ENDIAN endian=unicode::EUTFEE_NATIVE, const bool addBOM=false) const
Converts the string to a wchar_t encoded string array.
io::path toPATH_s (const unicode::EUTF_ENDIAN endian=unicode::EUTFEE_NATIVE, const bool addBOM=false) const
ustring16 & loadDataStream (const char *data, size_t data_size)
unicode::EUTF_ENCODE getEncoding () const
unicode::EUTF_ENDIAN getEndianness () const
Private Member Functions
void reallocate (u32 new_size)
Private Attributes
uchar16_t * array
unicode::EUTF_ENCODE encoding
u32 allocated
u32 used
Detailed Description
UTF-16 string class.
Definition at line 229 of file irrUString.h.
Constructor & Destructor Documentation
ustring16()
irr::core::ustring16::ustring16 () inline
Default constructor.
-------------------—/// end iterator classes /// -------------------—///
Definition at line 787 of file irrUString.h.
Referenced by split(), and subString().
Member Function Documentation
append() [1/6]
ustring16& irr::core::ustring16::append (const uchar16_t *const other, u32 length = 0xffffffff) inline
Appends a UTF-16 string to this ustring16
Parameters
other The UTF-16 string to append.
length The length of the string to append.
Returns
A reference to our current string.
Definition at line 1495 of file irrUString.h.
References getEndianness(), reallocate(), and validate().
append() [2/6]
ustring16& irr::core::ustring16::append (const uchar32_t *const other, u32 length = 0xffffffff) inline
Appends a UTF-32 string to this ustring16
Parameters
other The UTF-32 string to append.
length The length of the string to append.
Returns
A reference to our current string.
Definition at line 1560 of file irrUString.h.
References getEndianness(), reallocate(), and validate().
append() [3/6]
ustring16& irr::core::ustring16::append (const uchar8_t *const other, u32 length = 0xffffffff) inline
Appends a UTF-8 string to this ustring16
Parameters
other The UTF-8 string to append.
length The length of the string to append.
Returns
A reference to our current string.
Definition at line 1319 of file irrUString.h.
References reallocate(), and validate().
append() [4/6]
ustring16& irr::core::ustring16::append (const ustring16 & other) inline
Appends a ustring16 to this ustring16
Parameters
other The string to append to this one.
Returns
A reference to our current string.
Definition at line 1636 of file irrUString.h.
References c_str(), reallocate(), and size_raw().
append() [5/6]
ustring16& irr::core::ustring16::append (const ustring16 & other, u32 length) inline
Appends a certain amount of characters of a ustring16 to this ustring16.
Parameters
other The string to append to this one.
length How many characters of the other string to add to this one.
Returns
A reference to our current string.
Definition at line 1659 of file irrUString.h.
References append(), irr::core::ustring16::_ustring16_const_iterator::atEnd(), reallocate(), and size().
append() [6/6]
ustring16& irr::core::ustring16::append (uchar32_t character) inline
Appends a character to this ustring16
Parameters
character The character to append.
Returns
A reference to our current string.
Definition at line 1288 of file irrUString.h.
References reallocate().
Referenced by append(), loadDataStream(), operator+=(), operator=(), subString(), and ustring16().
begin() [1/2]
iterator irr::core::ustring16::begin () inline
Returns an iterator to the beginning of the string.
Returns
An iterator to the beginning of the string.
Definition at line 2653 of file irrUString.h.
Referenced by subString(), and trim().
begin() [2/2]
const_iterator irr::core::ustring16::begin () const inline
Returns an iterator to the beginning of the string.
Returns
An iterator to the beginning of the string.
Definition at line 2662 of file irrUString.h.
c_str()
const uchar16_t* irr::core::ustring16::c_str () const inline
Returns a pointer to the raw UTF-16 string data.
Returns
pointer to C-style NUL terminated array of UTF-16 code points.
Definition at line 1242 of file irrUString.h.
Referenced by irr::core::ustring16::_ustring16_iterator_access::_get(), irr::core::ustring16::_ustring16_iterator_access::_set(), append(), irr::core::ustring16::_ustring16_const_iterator::atEnd(), equalsn(), find_raw(), insert(), irr::core::ustring16::_ustring16_const_iterator::operator*(), irr::core::ustring16::_ustring16_iterator::operator*(), irr::core::ustring16::_ustring16_const_iterator::operator++(), irr::core::ustring16::_ustring16_const_iterator::operator+=(), irr::core::ustring16::_ustring16_const_iterator::operator--(), irr::core::ustring16::_ustring16_const_iterator::operator-=(), operator=(), remove(), and replace().
capacity()
u32 irr::core::ustring16::capacity () const inline
Gets the size of the allocated memory buffer for the string.
Returns
The size of the allocated memory buffer.
Definition at line 2526 of file irrUString.h.
cbegin()
const_iterator irr::core::ustring16::cbegin () const inline
Returns an iterator to the beginning of the string.
Returns
An iterator to the beginning of the string.
Definition at line 2671 of file irrUString.h.
cend()
const_iterator irr::core::ustring16::cend () const inline
Returns an iterator to the end of the string.
Returns
An iterator to the end of the string.
Definition at line 2700 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::toEnd().
empty()
bool irr::core::ustring16::empty () const inline
Informs if the ustring is empty or not.
Returns
True if the ustring is empty, false if not.
Definition at line 1234 of file irrUString.h.
References size_raw().
end() [1/2]
iterator irr::core::ustring16::end () inline
Returns an iterator to the end of the string.
Returns
An iterator to the end of the string.
Definition at line 2680 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::toEnd().
Referenced by findLastChar(), findLastCharNotInList(), replace(), and trim().
end() [2/2]
const_iterator irr::core::ustring16::end () const inline
Returns an iterator to the end of the string.
Returns
An iterator to the end of the string.
Definition at line 2690 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::toEnd().
equalsn() [1/2]
bool irr::core::ustring16::equalsn (const uchar16_t *const str, u32 n) const inline
Compares the first n characters of this string with another.
Parameters
str Other string to compare to.
n Number of characters to compare.
Returns
True if the n first characters of both strings are equal.
Definition at line 1270 of file irrUString.h.
equalsn() [2/2]
bool irr::core::ustring16::equalsn (const ustring16 & other, u32 n) const inline
Compares the first n characters of this string with another.
Parameters
other Other string to compare to.
n Number of characters to compare.
Returns
True if the n first characters of both strings are equal.
Definition at line 1252 of file irrUString.h.
References c_str().
erase()
ustring16& irr::core::ustring16::erase (u32 index) inline
Erases a character from the ustring16. May be slow, because all elements following after the erased element have to be copied.
Parameters
index Index of element to be erased.
Returns
A reference to our current string.
Definition at line 2359 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::getPos().
erase_raw()
ustring16& irr::core::ustring16::erase_raw (u32 pos) inline
Removes a character from string.
Parameters
pos Position of the character to remove.
Returns
A reference to our current string.
Definition at line 2628 of file irrUString.h.
Referenced by irr::core::ustring16::_ustring16_iterator_access::_set().
find()
s32 irr::core::ustring16::find (const ustring16 & str, const u32 start = 0) const inline
Finds another ustring16 in this ustring16.
Parameters
str The string to find.
start The start position of the search.
Returns
Positions where the ustring16 has been found, or -1 if not found.
Definition at line 1879 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd(), and size().
find_raw()
s32 irr::core::ustring16::find_raw (const ustring16 & str, const u32 start = 0) const inline
Finds another ustring16 in this ustring16.
Parameters
str The string to find.
start The start position of the search.
Returns
Positions where the string has been found, or -1 if not found.
Definition at line 1917 of file irrUString.h.
References c_str().
Referenced by replace().
findFirst()
s32 irr::core::ustring16::findFirst (uchar32_t c) const inline
Finds first occurrence of character.
Parameters
c The character to search for.
Returns
Position where the character has been found, or -1 if not found.
Definition at line 1701 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd().
findFirstChar()
s32 irr::core::ustring16::findFirstChar (const uchar32_t *const c, u32 count = 1) const inline
Finds first occurrence of a character of a list.
Parameters
c A list of characters to find. For example if the method should find the first occurrence of 'a' or 'b', this parameter should be "ab".
count The amount of characters in the list. Usually, this should be strlen(c).
Returns
Position where one of the characters has been found, or -1 if not found.
Definition at line 1722 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd().
findFirstCharNotInList()
s32 irr::core::ustring16::findFirstCharNotInList (const uchar32_t *const c, u32 count = 1) const inline
Finds first position of a character not in a given list.
Parameters
c A list of characters to NOT find. For example if the method should find the first occurrence of a character not 'a' or 'b', this parameter should be "ab".
count The amount of characters in the list. Usually, this should be strlen(c).
Returns
Position where the character has been found, or -1 if not found.
Definition at line 1748 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd().
Referenced by trim().
findLast()
s32 irr::core::ustring16::findLast (uchar32_t c, s32 start = -1) const inline
Finds last occurrence of character.
Parameters
c The character to search for.
start The start position of the reverse search (default = -1, on end).
Returns
Position where the character has been found, or -1 if not found.
Definition at line 1829 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atStart(), irr::core::clamp(), and size().
findLastChar()
s32 irr::core::ustring16::findLastChar (const uchar32_t *const c, u32 count = 1) const inline
Finds last occurrence of a character in a list.
Parameters
c A list of strings to find. For example if the method should find the last occurrence of 'a' or 'b', this parameter should be "ab".
count The amount of characters in the list. Usually, this should be strlen(c).
Returns
Position where one of the characters has been found, or -1 if not found.
Definition at line 1852 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atStart(), end(), and size().
findLastCharNotInList()
s32 irr::core::ustring16::findLastCharNotInList (const uchar32_t *const c, u32 count = 1) const inline
Finds last position of a character not in a given list.
Parameters
c A list of characters to NOT find. For example if the method should find the first occurrence of a character not 'a' or 'b', this parameter should be "ab".
count The amount of characters in the list. Usually, this should be strlen(c).
Returns
Position where the character has been found, or -1 if not found.
Definition at line 1777 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atStart(), end(), and size().
Referenced by trim().
findNext()
s32 irr::core::ustring16::findNext (uchar32_t c, u32 startPos) const inline
Finds next occurrence of character.
Parameters
c The character to search for.
startPos The position in the string to start searching.
Returns
Position where the character has been found, or -1 if not found.
Definition at line 1807 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd().
getEncoding()
unicode::EUTF_ENCODE irr::core::ustring16::getEncoding () const inline
Gets the encoding of the Unicode string this class contains.
Returns
An enum describing the current encoding of this string.
Definition at line 3052 of file irrUString.h.
getEndianness()
unicode::EUTF_ENDIAN irr::core::ustring16::getEndianness () const inline
Gets the endianness of the Unicode string this class contains.
Returns
An enum describing the endianness of this string.
Definition at line 3059 of file irrUString.h.
Referenced by append(), toUTF16(), and toUTF32().
insert() [1/2]
ustring16& irr::core::ustring16::insert (const ustring16 & c, u32 pos) inline
Inserts a string into the string.
Parameters
c The string to insert.
pos The position to insert the string.
Returns
A reference to our current string.
Definition at line 2579 of file irrUString.h.
References c_str(), irr::core::ustring16::_ustring16_const_iterator::getPos(), reallocate(), and size_raw().
insert() [2/2]
ustring16& irr::core::ustring16::insert (uchar32_t c, u32 pos) inline
Inserts a character into the string.
Parameters
c The character to insert.
pos The position to insert the character.
Returns
A reference to our current string.
Definition at line 2544 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::getPos(), and reallocate().
insert_raw()
ustring16& irr::core::ustring16::insert_raw (uchar16_t c, u32 pos) inline
Inserts a character into the string.
Parameters
c The character to insert.
pos The position to insert the character.
Returns
A reference to our current string.
Definition at line 2609 of file irrUString.h.
References reallocate().
Referenced by irr::core::ustring16::_ustring16_iterator_access::_set().
lastChar()
uchar32_t irr::core::ustring16::lastChar () const inline
Gets the last char of the ustring16, or 0.
Returns
The last char of the ustring16, or 0.
Definition at line 2416 of file irrUString.h.
loadDataStream()
ustring16& irr::core::ustring16::loadDataStream (const char * data, size_t data_size) inline
Loads an unknown stream of data. Will attempt to determine if the stream is unicode data. Useful for loading from files.
Parameters
data The data stream to load from.
data_size The length of the data string.
Returns
A reference to our current string.
Definition at line 3019 of file irrUString.h.
References append().
operator+=() [1/11]
ustring16& irr::core::ustring16::operator+= (char c) inline
Appends a character to this ustring16.
Parameters
c Character to append.
Returns
A reference to our current string.
Definition at line 1979 of file irrUString.h.
References append().
operator+=() [2/11]
ustring16& irr::core::ustring16::operator+= (const uchar16_t *const c) inline
Appends a char ustring16 to this ustring16.
Parameters
c Char ustring16 to append.
Returns
A reference to our current string.
Definition at line 2069 of file irrUString.h.
References append().
operator+=() [3/11]
ustring16& irr::core::ustring16::operator+= (const ustring16 & other) inline
Appends a ustring16 to this ustring16.
Parameters
other ustring16 to append.
Returns
A reference to our current string.
Definition at line 2079 of file irrUString.h.
References append().
operator+=() [4/11]
ustring16& irr::core::ustring16::operator+= (double c) inline
Appends a number to this ustring16.
Parameters
c Number to append.
Returns
A reference to our current string.
Definition at line 2059 of file irrUString.h.
References append().
operator+=() [5/11]
ustring16& irr::core::ustring16::operator+= (int c) inline
Appends a number to this ustring16.
Parameters
c Number to append.
Returns
A reference to our current string.
Definition at line 2019 of file irrUString.h.
References append().
operator+=() [6/11]
ustring16& irr::core::ustring16::operator+= (long c) inline
Appends a number to this ustring16.
Parameters
c Number to append.
Returns
A reference to our current string.
Definition at line 2039 of file irrUString.h.
References append().
operator+=() [7/11]
ustring16& irr::core::ustring16::operator+= (short c) inline
Appends a number to this ustring16.
Parameters
c Number to append.
Returns
A reference to our current string.
Definition at line 1999 of file irrUString.h.
References append().
operator+=() [8/11]
ustring16& irr::core::ustring16::operator+= (uchar32_t c) inline
Appends a character to this ustring16.
Parameters
c Character to append.
Returns
A reference to our current string.
Definition at line 1989 of file irrUString.h.
References append().
operator+=() [9/11]
ustring16& irr::core::ustring16::operator+= (unsigned int c) inline
Appends a number to this ustring16.
Parameters
c Number to append.
Returns
A reference to our current string.
Definition at line 2029 of file irrUString.h.
References append().
operator+=() [10/11]
ustring16& irr::core::ustring16::operator+= (unsigned long c) inline
Appends a number to this ustring16.
Parameters
c Number to append.
Returns
A reference to our current string.
Definition at line 2049 of file irrUString.h.
References append().
operator+=() [11/11]
ustring16& irr::core::ustring16::operator+= (unsigned short c) inline
Appends a number to this ustring16.
Parameters
c Number to append.
Returns
A reference to our current string.
Definition at line 2009 of file irrUString.h.
References append().
operator=() [1/2]
template<class B > ustring16& irr::core::ustring16::operator= (const B *const c) inline
Assignment operator for other strings.
Note that this assumes that a correct unicode string is stored in the string.
Definition at line 1132 of file irrUString.h.
operator=() [2/2]
ustring16& irr::core::ustring16::operator= (const wchar_t *const c) inline
Assignment operator for wchar_t strings.
Note that this assumes that a correct unicode string is stored in the wchar_t string. Since wchar_t changes depending on its platform, it could either be a UTF-8, -16, or -32 string. This function assumes you are storing the correct unicode encoding inside the wchar_t string.
Definition at line 1116 of file irrUString.h.
reallocate()
void irr::core::ustring16::reallocate (u32 new_size) inline private
Reallocate the string, making it bigger or smaller.
Parameters
new_size The new size of the string.
Definition at line 3071 of file irrUString.h.
Referenced by append(), insert(), insert_raw(), replace(), and reserve().
remove() [1/2]
ustring16& irr::core::ustring16::remove (const ustring16 & toRemove) inline
Removes a ustring16 from the ustring16.
Parameters
toRemove The string to remove.
Returns
A reference to our current string.
Definition at line 2255 of file irrUString.h.
References c_str(), size(), and size_raw().
remove() [2/2]
ustring16& irr::core::ustring16::remove (uchar32_t c) inline
Removes characters from a ustring16..
Parameters
c The character to remove.
Returns
A reference to our current string.
Definition at line 2219 of file irrUString.h.
removeChars()
ustring16& irr::core::ustring16::removeChars (const ustring16 & characters) inline
Removes characters from the ustring16.
Parameters
characters The characters to remove.
Returns
A reference to our current string.
Definition at line 2290 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd(), size_raw(), and irr::core::ustring16::_ustring16_const_iterator::toStart().
replace() [1/2]
ustring16& irr::core::ustring16::replace (const ustring16 & toReplace, const ustring16 & replaceWith) inline
Replaces all instances of a string with another one.
Parameters
toReplace The string to replace.
replaceWith The string replacing the old one.
Returns
A reference to our current string.
Definition at line 2108 of file irrUString.h.
References c_str(), end(), find_raw(), reallocate(), replace(), size(), and size_raw().
replace() [2/2]
ustring16& irr::core::ustring16::replace (uchar32_t toReplace, uchar32_t replaceWith) inline
Replaces all characters of a given type with another one.
Parameters
toReplace Character to replace.
replaceWith Character replacing the old one.
Returns
A reference to our current string.
Definition at line 2090 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd().
Referenced by replace().
replace_raw()
ustring16& irr::core::ustring16::replace_raw (uchar16_t c, u32 pos) inline
Replaces a character in the string.
Parameters
c The new character.
pos The position of the character to replace.
Returns
A reference to our current string.
Definition at line 2644 of file irrUString.h.
Referenced by irr::core::ustring16::_ustring16_iterator_access::_set().
reserve()
void irr::core::ustring16::reserve (u32 count) inline
Reserves some memory.
Parameters
count The amount of characters to reserve.
Definition at line 1689 of file irrUString.h.
References reallocate().
Referenced by subString(), and ustring16().
size()
u32 irr::core::ustring16::size () const inline
Returns the length of a ustring16 in full characters.
Returns
Length of a ustring16 in full characters.
Definition at line 1219 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd().
Referenced by append(), find(), findLast(), findLastChar(), findLastCharNotInList(), operator[](), remove(), replace(), split(), subString(), and toUTF32().
size_raw()
u32 irr::core::ustring16::size_raw () const inline
Returns the raw number of UTF-16 code points in the string which includes the individual surrogates.
Returns
The raw number of UTF-16 code points, excluding the trialing NUL.
Definition at line 2534 of file irrUString.h.
Referenced by irr::core::ustring16::_ustring16_iterator_access::_get(), irr::core::ustring16::_ustring16_iterator_access::_set(), append(), irr::core::ustring16::_ustring16_const_iterator::atEnd(), empty(), insert(), irr::core::ustring16::_ustring16_const_iterator::operator*(), irr::core::ustring16::_ustring16_iterator::operator*(), irr::core::ustring16::_ustring16_const_iterator::operator++(), irr::core::ustring16::_ustring16_const_iterator::operator+=(), operator=(), remove(), removeChars(), replace(), and irr::core::ustring16::_ustring16_const_iterator::toEnd().
split() [1/2]
template<class container > u32 irr::core::ustring16::split (container & ret, const uchar32_t *const c, u32 count = 1, bool ignoreEmptyTokens = true, bool keepSeparators = false) const inline
Split the ustring16 into parts.
This method will split a ustring16 at certain delimiter characters into the container passed in as reference. The type of the container has to be given as template parameter. It must provide a push_back and a size method.
Parameters
ret The result container
c C-style ustring16 of delimiter characters
count Number of delimiter characters
ignoreEmptyTokens Flag to avoid empty substrings in the result container. If two delimiters occur without a character in between, an empty substring would be placed in the result. If this flag is set, only non-empty strings are stored.
keepSeparators Flag which allows to add the separator to the result ustring16. If this flag is true, the concatenation of the substrings results in the original ustring16. Otherwise, only the characters between the delimiters are returned.
Returns
The number of resulting substrings
Definition at line 2460 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd(), irr::core::ustring16::_ustring16_const_iterator::getPos(), size(), and ustring16().
Referenced by split().
split() [2/2]
template<class container > u32 irr::core::ustring16::split (container & ret, const ustring16 & c, bool ignoreEmptyTokens = true, bool keepSeparators = false) const inline
Split the ustring16 into parts.
This method will split a ustring16 at certain delimiter characters into the container passed in as reference. The type of the container has to be given as template parameter. It must provide a push_back and a size method.
Parameters
ret The result container
c A unicode string of delimiter characters
ignoreEmptyTokens Flag to avoid empty substrings in the result container. If two delimiters occur without a character in between, an empty substring would be placed in the result. If this flag is set, only non-empty strings are stored.
keepSeparators Flag which allows to add the separator to the result ustring16. If this flag is true, the concatenation of the substrings results in the original ustring16. Otherwise, only the characters between the delimiters are returned.
Returns
The number of resulting substrings
Definition at line 2517 of file irrUString.h.
References irr::core::array< T >::pointer(), irr::core::array< T >::size(), split(), and toUTF32().
subString()
ustring16 irr::core::ustring16::subString (u32 begin, s32 length) const inline
Returns a substring.
Parameters
begin Start of substring.
length Length of substring.
Returns
A reference to our current string.
Definition at line 1950 of file irrUString.h.
References append(), irr::core::ustring16::_ustring16_const_iterator::atEnd(), begin(), reserve(), size(), and ustring16().
Referenced by trim().
toPATH_s()
io::path irr::core::ustring16::toPATH_s (const unicode::EUTF_ENDIAN endian = unicode::EUTFEE_NATIVE, const bool addBOM = false) const inline
Converts the string to a properly encoded io::path string.
Parameters
endian The desired endianness of the string.
addBOM If true, the proper unicode byte-order mark will be prefixed to the string.
Returns
An io::path string containing the properly encoded string.
Definition at line 3009 of file irrUString.h.
References toUTF8_s().
toUTF16()
core::array<uchar16_t> irr::core::ustring16::toUTF16 (const unicode::EUTF_ENDIAN endian = unicode::EUTFEE_NATIVE, const bool addBOM = false) const inline
Converts the string to a UTF-16 encoded string array. Unfortunately, no toUTF16_s() version exists due to limitations with Irrlicht's string class.
Parameters
endian The desired endianness of the string.
addBOM If true, the proper unicode byte-order mark will be prefixed to the string.
Returns
An array containing the UTF-16 encoded string.
Definition at line 2827 of file irrUString.h.
References getEndianness().
toUTF32()
core::array<uchar32_t> irr::core::ustring16::toUTF32 (const unicode::EUTF_ENDIAN endian = unicode::EUTFEE_NATIVE, const bool addBOM = false) const inline
Converts the string to a UTF-32 encoded string array. Unfortunately, no toUTF32_s() version exists due to limitations with Irrlicht's string class.
Parameters
endian The desired endianness of the string.
addBOM If true, the proper unicode byte-order mark will be prefixed to the string.
Returns
An array containing the UTF-32 encoded string.
Definition at line 2869 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd(), getEndianness(), and size().
Referenced by split().
toUTF8()
core::array<uchar8_t> irr::core::ustring16::toUTF8 (const bool addBOM = false) const inline
Converts the string to a UTF-8 encoded string array.
Parameters
addBOM If true, the proper unicode byte-order mark will be prefixed to the string.
Returns
An array containing the UTF-8 encoded string.
Definition at line 2768 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd().
toUTF8_s()
core::string<uchar8_t> irr::core::ustring16::toUTF8_s (const bool addBOM = false) const inline
Converts the string to a UTF-8 encoded string.
Parameters
addBOM If true, the proper unicode byte-order mark will be prefixed to the string.
Returns
A string containing the UTF-8 encoded string.
Definition at line 2711 of file irrUString.h.
References irr::core::ustring16::_ustring16_const_iterator::atEnd().
Referenced by irr::core::operator<<(), and toPATH_s().
toWCHAR()
core::array<wchar_t> irr::core::ustring16::toWCHAR (const unicode::EUTF_ENDIAN endian = unicode::EUTFEE_NATIVE, const bool addBOM = false) const inline
Converts the string to a wchar_t encoded string array.
The size of a wchar_t changes depending on the platform. This function will store a correct UTF-8, -16, or -32 encoded string depending on the size of a wchar_t.
Parameters
endian The desired endianness of the string.
addBOM If true, the proper unicode byte-order mark will be prefixed to the string.
Returns
An array containing the wchar_t encoded string.
Definition at line 2964 of file irrUString.h.
toWCHAR_s()
core::string<wchar_t> irr::core::ustring16::toWCHAR_s (const unicode::EUTF_ENDIAN endian = unicode::EUTFEE_NATIVE, const bool addBOM = false) const inline
Converts the string to a wchar_t encoded string.
The size of a wchar_t changes depending on the platform. This function will store a correct UTF-8, -16, or -32 encoded string depending on the size of a wchar_t.
Parameters
endian The desired endianness of the string.
addBOM If true, the proper unicode byte-order mark will be prefixed to the string.
Returns
A string containing the wchar_t encoded string.
Definition at line 2924 of file irrUString.h.
Referenced by irr::core::operator<<().
trim()
ustring16& irr::core::ustring16::trim (const ustring16 & whitespace = " \t\n\r") inline
Trims the ustring16. Removes the specified characters (by default, Latin-1 whitespace) from the begining and the end of the ustring16.
Parameters
whitespace The characters that are to be considered as whitespace.
Returns
A reference to our current string.
Definition at line 2340 of file irrUString.h.
References begin(), irr::core::array< T >::const_pointer(), end(), findFirstCharNotInList(), findLastCharNotInList(), and subString().
validate()
ustring16& irr::core::ustring16::validate () inline
Validate the existing ustring16, checking for valid surrogate pairs and checking for proper termination.
Returns
A reference to our current string.
Definition at line 2380 of file irrUString.h.
Referenced by append(), and operator=().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/irrUString.h