Three Cubes Game: irr::video::CImage Class Reference
irr::video::CImage Class Reference
#include <CImage.h>
Public Member Functions
CImage (ECOLOR_FORMAT format, const core::dimension2d< u32 > &size, void *data, bool ownForeignMemory=true, bool deleteMemory=true)
constructor from raw image data
CImage (ECOLOR_FORMAT format, const core::dimension2d< u32 > &size)
constructor for empty image
SColor getPixel (u32 x, u32 y) const override
returns a pixel
void setPixel (u32 x, u32 y, const SColor &color, bool blend=false) override
sets a pixel
bool copyToNoScaling (void *target, u32 width, u32 height, ECOLOR_FORMAT format, u32 pitch=0) const override
copies this surface into another, if it has the exact same size and format.
void copyToScaling (void *target, u32 width, u32 height, ECOLOR_FORMAT format, u32 pitch=0) override
copies this surface into another, scaling it to fit.
void copyToScaling (IImage *target) override
copies this surface into another, scaling it to fit.
void copyTo (IImage *target, const core::position2d< s32 > &pos=core::position2d< s32 >(0, 0)) override
copies this surface into another
void copyTo (IImage *target, const core::position2d< s32 > &pos, const core::rect< s32 > &sourceRect, const core::rect< s32 > *clipRect=0) override
copies this surface into another
virtual void copyToWithAlpha (IImage *target, const core::position2d< s32 > &pos, const core::rect< s32 > &sourceRect, const SColor &color, const core::rect< s32 > *clipRect=0, bool combineAlpha=false) override
copies this surface into another, using the alpha mask, an cliprect and a color to add with
void copyToScalingBoxFilter (IImage *target, s32 bias=0, bool blend=false) override
copies this surface into another, scaling it to fit, applying a box filter
void fill (const SColor &color) override
fills the surface with given color
Public Member Functions inherited from irr::video::IImage
IImage (ECOLOR_FORMAT format, const core::dimension2d< u32 > &size, bool deleteMemory)
constructor
virtual ~IImage ()
destructor
ECOLOR_FORMAT getColorFormat () const
Returns the color format.
const core::dimension2d< u32 > & getDimension () const
Returns width and height of image data.
u32 getBitsPerPixel () const
Returns bits per pixel.
u32 getBytesPerPixel () const
Returns bytes per pixel.
u32 getImageDataSizeInBytes () const
Returns image data size in bytes.
u32 getImageDataSizeInPixels () const
Returns image data size in pixels.
u32 getPitch () const
Returns pitch of image.
u32 getRedMask () const
Returns mask for red value of a pixel.
u32 getGreenMask () const
Returns mask for green value of a pixel.
u32 getBlueMask () const
Returns mask for blue value of a pixel.
u32 getAlphaMask () const
Returns mask for alpha value of a pixel.
void * getData () const
Use this to get a pointer to the image data.
_IRR_DEPRECATED_ void * lock ()
Lock function. Use this to get a pointer to the image data.
_IRR_DEPRECATED_ void unlock ()
Unlock function.
core::dimension2du getMipMapsSize (u32 mipmapLevel) const
Get the mipmap size for this image for a certain mipmap level.
void * getMipMapsData (irr::u32 mipLevel=1) const
Get mipmaps data.
void setMipMapsData (void *data, bool ownForeignMemory)
Set mipmaps data.
_IRR_DEPRECATED_ bool isCompressed () const
Inform whether the image is compressed.
_IRR_DEPRECATED_ bool hasMipMaps () const
Check whether the image has MipMaps.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Member Functions
SColor getPixelBox (s32 x, s32 y, s32 fx, s32 fy, s32 bias) const
get a filtered pixel
Additional Inherited Members
Static Public Member Functions inherited from irr::video::IImage
static core::dimension2du getMipMapsSize (const core::dimension2du &sizeLevel0, u32 mipmapLevel)
Calculate mipmap size for a certain level.
static u32 getBitsPerPixelFromFormat (const ECOLOR_FORMAT format)
get the amount of Bits per Pixel of the given color format
static u32 getDataSizeFromFormat (ECOLOR_FORMAT format, u32 width, u32 height)
calculate image data size in bytes for selected format, width and height.
static bool isCompressedFormat (const ECOLOR_FORMAT format)
check if this is compressed color format
static bool isDepthFormat (const ECOLOR_FORMAT format)
check if the color format is only viable for depth/stencil textures
static bool isFloatingPointFormat (const ECOLOR_FORMAT format)
Check if the color format uses floating point values for pixels.
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes inherited from irr::video::IImage
ECOLOR_FORMAT Format
core::dimension2d< u32 > Size
u8 * Data
u8 * MipMapsData
u32 BytesPerPixel
u32 Pitch
bool DeleteMemory
bool DeleteMipMapsMemory
Detailed Description
IImage implementation with a lot of special image operations for 16 bit A1R5G5B5/32 Bit A8R8G8B8 images, which are used by the SoftwareDevice.
Definition at line 25 of file CImage.h.
Constructor & Destructor Documentation
CImage() [1/2]
irr::video::CImage::CImage (ECOLOR_FORMAT format, const core::dimension2d< u32 > & size, void * data, bool ownForeignMemory = true, bool deleteMemory = true)
constructor from raw image data
Constructor from raw data.
Parameters
useForeignMemory If true, the image will use the data pointer directly and own it from now on, which means it will also try to delete [] the data when the image will be destructed. If false, the memory will by copied.
Definition at line 18 of file CImage.cpp.
References irr::video::IImage::getDataSizeFromFormat(), irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
CImage() [2/2]
irr::video::CImage::CImage (ECOLOR_FORMAT format, const core::dimension2d< u32 > & size)
constructor for empty image
Constructor of empty image.
Definition at line 37 of file CImage.cpp.
References irr::video::IImage::getDataSizeFromFormat(), irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
Member Function Documentation
copyTo() [1/2]
void irr::video::CImage::copyTo (IImage * target, const core::position2d< s32 > & pos, const core::rect< s32 > & sourceRect, const core::rect< s32 > * clipRect = 0) override virtual
copies this surface into another
copies this surface partially into another at given position
Implements irr::video::IImage.
Definition at line 149 of file CImage.cpp.
References irr::Blit(), irr::ELL_WARNING, and irr::video::IImage::isCompressedFormat().
copyTo() [2/2]
void irr::video::CImage::copyTo (IImage * target, const core::position2d< s32 > & pos = core::position2d<s32>(0,0)) override virtual
copies this surface into another
copies this surface into another at given position
Implements irr::video::IImage.
Definition at line 129 of file CImage.cpp.
References irr::Blit(), copyToScaling(), irr::ELL_WARNING, irr::video::IImage::getColorFormat(), irr::video::IImage::getData(), irr::video::IImage::getDimension(), irr::video::IImage::getPitch(), irr::core::dimension2d< T >::Height, irr::video::IImage::isCompressedFormat(), and irr::core::dimension2d< T >::Width.
Referenced by copyToScaling().
copyToScaling() [1/2]
void irr::video::CImage::copyToScaling (IImage * target) override virtual
copies this surface into another, scaling it to fit.
copies this surface into another, scaling it to the target image size
Implements irr::video::IImage.
Definition at line 285 of file CImage.cpp.
References copyTo(), copyToScaling(), irr::ELL_WARNING, irr::video::IImage::getColorFormat(), irr::video::IImage::getData(), irr::video::IImage::getDimension(), irr::core::dimension2d< T >::Height, irr::video::IImage::isCompressedFormat(), and irr::core::dimension2d< T >::Width.
copyToScaling() [2/2]
void irr::video::CImage::copyToScaling (void * target, u32 width, u32 height, ECOLOR_FORMAT format, u32 pitch = 0) override virtual
copies this surface into another, scaling it to fit.
copies this surface into another, scaling it to the target image size
Implements irr::video::IImage.
Definition at line 222 of file CImage.cpp.
References copyToNoScaling(), irr::ELL_WARNING, irr::video::IImage::getBitsPerPixelFromFormat(), irr::core::dimension2d< T >::Height, irr::video::IImage::isCompressedFormat(), and irr::core::dimension2d< T >::Width.
Referenced by copyTo(), and copyToScaling().
copyToScalingBoxFilter()
void irr::video::CImage::copyToScalingBoxFilter (IImage * target, s32 bias = 0, bool blend = false) override virtual
copies this surface into another, scaling it to fit, applying a box filter
copies this surface into another, scaling it to fit it.
Implements irr::video::IImage.
Definition at line 309 of file CImage.cpp.
References irr::ELL_WARNING, irr::video::IImage::getDimension(), getPixelBox(), irr::core::dimension2d< T >::Height, irr::video::IImage::isCompressedFormat(), irr::video::IImage::setPixel(), and irr::core::dimension2d< T >::Width.
copyToWithAlpha()
void irr::video::CImage::copyToWithAlpha (IImage * target, const core::position2d< s32 > & pos, const core::rect< s32 > & sourceRect, const SColor & color, const core::rect< s32 > * clipRect = 0, bool combineAlpha = false) override virtual
copies this surface into another, using the alpha mask, an cliprect and a color to add with
copies this surface into another, using the alpha mask, a cliprect and a color to add with
Implements irr::video::IImage.
Definition at line 162 of file CImage.cpp.
References irr::Blit(), irr::video::SColor::color, irr::ELL_WARNING, and irr::video::IImage::isCompressedFormat().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CImage.h
lib/irrlichtmt/source/Irrlicht/CImage.cpp