Three Cubes Game: irr::os::Timer Class Reference
irr::os::Timer Class Reference
Static Public Member Functions
static u32 getTime ()
returns the current time in milliseconds
static ITimer::RealTimeDate getRealTimeAndDate ()
get current time and date in calendar form
static void initTimer (bool usePerformanceTimer=true)
initializes the real timer
static void setTime (u32 time)
sets the current virtual (game) time
static void stopTimer ()
stops the virtual (game) timer
static void startTimer ()
starts the game timer
static void setSpeed (f32 speed)
sets the speed of the virtual timer
static f32 getSpeed ()
gets the speed of the virtual timer
static bool isStopped ()
returns if the timer currently is stopped
static void tick ()
makes the virtual timer update the time value based on the real time
static u32 getRealTime ()
returns the current real time in milliseconds
Static Private Member Functions
static void initVirtualTimer ()
Static Private Attributes
static f32 VirtualTimerSpeed = 1.0f
static s32 VirtualTimerStopCounter = 0
static u32 StartRealTime = 0
static u32 LastVirtualTime = 0
static u32 StaticTime = 0
Detailed Description
Definition at line 48 of file os.h.
Member Function Documentation
getRealTimeAndDate()
ITimer::RealTimeDate irr::os::Timer::getRealTimeAndDate () static
get current time and date in calendar form
Get real time and date in calendar form.
Definition at line 301 of file os.cpp.
Referenced by irr::CTimer::getRealTimeAndDate().
getTime()
u32 irr::os::Timer::getTime () static
returns the current time in milliseconds
returns current virtual time
Definition at line 330 of file os.cpp.
References isStopped().
Referenced by irr::gui::CGUICheckBox::draw(), irr::gui::CGUIListBox::draw(), irr::gui::CGUIEditBox::draw(), irr::gui::CGUIEnvironment::drawAll(), irr::scene::CSceneManager::drawAll(), irr::CTimer::getTime(), irr::gui::CGUIEditBox::inputString(), irr::gui::CGUIButton::OnEvent(), irr::gui::CGUICheckBox::OnEvent(), irr::gui::CGUIListBox::OnEvent(), irr::gui::CGUIListBox::removeItem(), irr::gui::CGUIButton::setPressed(), irr::gui::CGUIListBox::setSelected(), setSpeed(), and stopTimer().
setTime()
void irr::os::Timer::setTime (u32 time) static
sets the current virtual (game) time
sets the current virtual time
Definition at line 345 of file os.cpp.
References getRealTime().
Referenced by setSpeed(), irr::CTimer::setTime(), and startTimer().
startTimer()
void irr::os::Timer::startTimer () static
starts the game timer
starts the virtual timer
Definition at line 365 of file os.cpp.
References isStopped(), and setTime().
Referenced by irr::CTimer::start().
stopTimer()
void irr::os::Timer::stopTimer () static
stops the virtual (game) timer
stops the virtual timer
Definition at line 353 of file os.cpp.
References getTime(), and isStopped().
Referenced by irr::CTimer::stop().
tick()
void irr::os::Timer::tick () static
makes the virtual timer update the time value based on the real time
ticks, advances the virtual timer
Definition at line 339 of file os.cpp.
References getRealTime().
Referenced by irr::CTimer::tick().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/os.h
lib/irrlichtmt/source/Irrlicht/os.cpp