Three Cubes Game: irr::IOSOperator Class Reference
irr::IOSOperator Class Reference abstract
The Operating system operator provides operation system specific methods and information.
#include <IOSOperator.h>
Public Member Functions
virtual const core::stringc & getOperatingSystemVersion () const =0
Get the current operation system version as string.
const _IRR_DEPRECATED_ wchar_t * getOperationSystemVersion () const
Get the current operation system version as string.
virtual void copyToClipboard (const c8 *text) const =0
virtual void copyToPrimarySelection (const c8 *text) const =0
virtual const c8 * getTextFromClipboard () const =0
virtual const c8 * getTextFromPrimarySelection () const =0
virtual bool getSystemMemory (u32 *totalBytes, u32 *availableBytes) const =0
Get the total and available system RAM.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
The Operating system operator provides operation system specific methods and information.
Definition at line 15 of file IOSOperator.h.
Member Function Documentation
copyToClipboard()
virtual void irr::IOSOperator::copyToClipboard (const c8 * text) const pure virtual
Copies text to the clipboard
Parameters
text text in utf-8
Implemented in irr::COSOperator.
Referenced by GUIChatConsole::OnEvent().
copyToPrimarySelection()
virtual void irr::IOSOperator::copyToPrimarySelection (const c8 * text) const pure virtual
Copies text to the primary selection This is a no-op on some platforms.
Parameters
text text in utf-8
Implemented in irr::COSOperator.
Referenced by GUIEditBox::setTextMarkers(), and irr::gui::CGUIEditBox::setTextMarkers().
getOperationSystemVersion()
const _IRR_DEPRECATED_ wchar_t* irr::IOSOperator::getOperationSystemVersion () const inline
Get the current operation system version as string.
Deprecated:
Use getOperatingSystemVersion instead. This method will be removed in Irrlicht 1.9.
Definition at line 23 of file IOSOperator.h.
References getOperatingSystemVersion().
getSystemMemory()
virtual bool irr::IOSOperator::getSystemMemory (u32 * totalBytes, u32 * availableBytes) const pure virtual
Get the total and available system RAM.
Parameters
totalBytes will contain the total system memory in Kilobytes (1024 B)
availableBytes will contain the available memory in Kilobytes (1024 B)
Returns
True if successful, false if not
Implemented in irr::COSOperator.
getTextFromClipboard()
virtual const c8* irr::IOSOperator::getTextFromClipboard () const pure virtual
Get text from the clipboard
Returns
Returns 0 if no string is in there, otherwise an utf-8 string.
Implemented in irr::COSOperator.
Referenced by GUIChatConsole::OnEvent().
getTextFromPrimarySelection()
virtual const c8* irr::IOSOperator::getTextFromPrimarySelection () const pure virtual
Get text from the primary selection This is a no-op on some platforms.
Returns
Returns 0 if no string is in there, otherwise an utf-8 string.
Implemented in irr::COSOperator.
Referenced by GUIChatConsole::OnEvent().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IOSOperator.h