Three Cubes Game: ServerModManager Class Reference
ServerModManager Class Reference
#include <mods.h>
Public Member Functions
ServerModManager (const std::string &worldpath)
void loadMods (ServerScripting *script)
const ModSpec * getModSpec (const std::string &modname) const
void getModNames (std::vector< std::string > &modlist) const
const std::vector< ModSpec > & getMods () const
const std::vector< ModSpec > & getUnsatisfiedMods () const
bool isConsistent () const
std::string getUnsatisfiedModsError () const
void getModsMediaPaths (std::vector< std::string > &paths) const
Private Attributes
ModConfiguration configuration
Detailed Description
Manage server mods
All new calls to this class must be tested in test_servermodmanager.cpp
Definition at line 34 of file mods.h.
Constructor & Destructor Documentation
ServerModManager()
ServerModManager::ServerModManager (const std::string & worldpath)
Creates a ServerModManager which targets worldpath
Parameters
worldpath Manage server mods
All new calls to this class must be tested in test_servermodmanager.cpp Creates a ServerModManager which targets worldpath
Parameters
worldpath
Definition at line 37 of file mods.cpp.
References ModConfiguration::addGameMods(), ModConfiguration::addModsFromConfig(), ModConfiguration::addModsInPath(), SubgameSpec::addon_mods_paths, and ModConfiguration::checkConflictsAndDeps().
Member Function Documentation
getModsMediaPaths()
void ServerModManager::getModsMediaPaths (std::vector< std::string > & paths) const
Recursively gets all paths of mod folders that can contain media files.
Result is ordered in descending priority, ie. files from an earlier path should not be replaced by files from a latter one.
Parameters
paths result vector
Definition at line 95 of file mods.cpp.
References ModConfiguration::getMods().
The documentation for this class was generated from the following files:
src/server/mods.h
src/server/mods.cpp