Three Cubes Game: RenderTarget Class Reference
RenderTarget Class Reference
#include <pipeline.h>
Public Member Functions
virtual void activate (PipelineContext &context)
virtual void reset (PipelineContext &context) override
Protected Attributes
bool m_clear {true}
Detailed Description
Represents a render target (screen or framebuffer)
Definition at line 86 of file pipeline.h.
Member Function Documentation
activate()
virtual void RenderTarget::activate (PipelineContext & context) inline virtual
Activate the render target and configure OpenGL state for the output. This is usually done by
See also
RenderStep implementations.
Reimplemented in DynamicTarget, ScreenTarget, TextureBufferOutput, ConfigureOverrideMaterialTarget, and ClearDepthBufferTarget.
Definition at line 93 of file pipeline.h.
Referenced by ClearDepthBufferTarget::activate(), ConfigureOverrideMaterialTarget::activate(), TextureBufferOutput::activate(), ScreenTarget::activate(), DynamicTarget::activate(), DrawImageStep::run(), Draw3D::run(), PostProcessingStep::run(), DrawWield::run(), MapPostFxStep::run(), and UpscaleStep::run().
reset()
virtual void RenderTarget::reset (PipelineContext & context) inline override virtual
Resets the state of the object for the next pipeline iteration
Reimplemented from RenderPipelineObject.
Reimplemented in ScreenTarget, and ClearDepthBufferTarget.
Definition at line 101 of file pipeline.h.
Referenced by ScreenTarget::reset().
The documentation for this class was generated from the following file:
src/client/render/pipeline.h