Three Cubes Game: VectorAreaStore Class Reference
VectorAreaStore Class Reference
Public Member Functions
virtual void reserve (size_t count)
virtual bool insertArea (Area *a)
virtual bool removeArea (u32 id)
virtual void getAreasInArea (std::vector< Area * > *result, v3s16 minedge, v3s16 maxedge, bool accept_overlap)
Public Member Functions inherited from AreaStore
size_t size () const
void getAreasForPos (std::vector< Area * > *result, v3s16 pos)
void setCacheParams (bool enabled, u8 block_radius, size_t limit)
Sets cache parameters.
const Area * getArea (u32 id) const
void serialize (std::ostream &is) const
Serializes the store's areas to a binary ostream.
void deserialize (std::istream &is)
Protected Member Functions
virtual void getAreasForPosImpl (std::vector< Area * > *result, v3s16 pos)
Protected Member Functions inherited from AreaStore
void invalidateCache ()
u32 getNextId () const
Returns the next area ID and increments it.
Private Attributes
std::vector< Area * > m_areas
Additional Inherited Members
Static Public Member Functions inherited from AreaStore
static AreaStore * getOptimalImplementation ()
Protected Types inherited from AreaStore
typedef std::map< u32, Area > AreaMap
Protected Attributes inherited from AreaStore
AreaMap areas_map
Detailed Description
Definition at line 131 of file areastore.h.
Member Function Documentation
getAreasForPosImpl()
void VectorAreaStore::getAreasForPosImpl (std::vector< Area * > * result, v3s16 pos) protected virtual
Implementation of getAreasForPos. getAreasForPos calls this if the cache is disabled.
Implements AreaStore.
Definition at line 224 of file areastore.cpp.
getAreasInArea()
void VectorAreaStore::getAreasInArea (std::vector< Area * > * result, v3s16 minedge, v3s16 maxedge, bool accept_overlap) virtual
Finds areas that are completely contained inside the area defined by the passed edges. If accept_overlap is true this finds any areas that intersect with the passed area at any point.
Implements AreaStore.
Definition at line 233 of file areastore.cpp.
insertArea()
bool VectorAreaStore::insertArea (Area * a) virtual
Add an area to the store. Updates the area's ID if it hasn't already been set.
Returns
Whether the area insertion was successful.
Implements AreaStore.
Definition at line 192 of file areastore.cpp.
References AreaStore::getNextId(), and AreaStore::invalidateCache().
removeArea()
bool VectorAreaStore::removeArea (u32 id) virtual
Removes an area from the store by ID.
Returns
Whether the area was in the store and removed.
Implements AreaStore.
Definition at line 206 of file areastore.cpp.
References AreaStore::invalidateCache().
The documentation for this class was generated from the following files:
src/util/areastore.h
src/util/areastore.cpp