Three Cubes Game: PostProcessingStep Class Reference
PostProcessingStep Class Reference
#include <secondstage.h>
Public Member Functions
PostProcessingStep (u32 shader_id, const std::vector< u8 > &texture_map)
void setRenderSource (RenderSource *source) override
void setRenderTarget (RenderTarget *target) override
void reset (PipelineContext &context) override
void run (PipelineContext &context) override
void setBilinearFilter (u8 index, bool value)
Private Member Functions
void configureMaterial ()
Private Attributes
u32 shader_id
std::vector< u8 > texture_map
RenderSource * source { nullptr }
RenderTarget * target { nullptr }
video::SMaterial material
Detailed Description
Step to apply post-processing filter to the rendered image
Definition at line 28 of file secondstage.h.
Constructor & Destructor Documentation
PostProcessingStep()
PostProcessingStep::PostProcessingStep (u32 shader_id, const std::vector< u8 > & texture_map)
Construct a new PostProcessingStep object
Parameters
shader_id ID of the shader in IShaderSource
texture_map Map of textures to be chosen from the render source
Definition at line 28 of file secondstage.cpp.
Member Function Documentation
run()
void PostProcessingStep::run (PipelineContext & context) override virtual
Runs the step. This method is invoked by the pipeline.
Implements RenderStep.
Definition at line 63 of file secondstage.cpp.
References RenderTarget::activate(), RenderSource::getTexture(), irr::IrrlichtDevice::getVideoDriver(), irr::video::SMaterial::MaterialType, irr::video::SMaterialLayer::Texture, and irr::video::SMaterial::TextureLayer.
setBilinearFilter()
void PostProcessingStep::setBilinearFilter (u8 index, bool value)
Configure bilinear filtering for a specific texture layer
Parameters
index Index of the texture layer
value true to enable the bilinear filter, false to disable
Definition at line 92 of file secondstage.cpp.
References irr::video::SMaterialLayer::BilinearFilter, and irr::video::SMaterial::TextureLayer.
setRenderSource()
void PostProcessingStep::setRenderSource (RenderSource * source) override virtual
Assigns render source to this step.
Parameters
source source of rendering information
Implements RenderStep.
Definition at line 49 of file secondstage.cpp.
setRenderTarget()
void PostProcessingStep::setRenderTarget (RenderTarget * target) override virtual
Assigned render target to this step.
Parameters
target render target to send output to.
Implements RenderStep.
Definition at line 54 of file secondstage.cpp.
The documentation for this class was generated from the following files:
src/client/render/secondstage.h
src/client/render/secondstage.cpp