Three Cubes Game: irr::core::rect< T > Class Template Reference
irr::core::rect< T > Class Template Reference
Rectangle template.
#include <rect.h>
Public Member Functions
rect ()
Default constructor creating empty rectangle at (0,0)
rect (T x, T y, T x2, T y2)
Constructor with two corners.
rect (const position2d< T > &upperLeft, const position2d< T > &lowerRight)
Constructor with two corners.
template<class U >
rect (const position2d< T > &pos, const dimension2d< U > &size)
Constructor with upper left corner and dimension.
template<class U >
rect (const dimension2d< U > &size)
Constructor with upper left at 0,0 and lower right using dimension.
rect< T > operator+ (const position2d< T > &pos) const
move right by given numbers
rect< T > & operator+= (const position2d< T > &pos)
move right by given numbers
rect< T > operator- (const position2d< T > &pos) const
move left by given numbers
rect< T > & operator-= (const position2d< T > &pos)
move left by given numbers
bool operator== (const rect< T > &other) const
equality operator
bool operator!= (const rect< T > &other) const
inequality operator
bool operator< (const rect< T > &other) const
compares size of rectangles
T getArea () const
Returns size of rectangle.
bool isPointInside (const position2d< T > &pos) const
Returns if a 2d point is within this rectangle.
bool isRectCollided (const rect< T > &other) const
Check if the rectangle collides with another rectangle.
void clipAgainst (const rect< T > &other)
Clips this rectangle with another one.
bool constrainTo (const rect< T > &other)
Moves this rectangle to fit inside another one.
T getWidth () const
Get width of rectangle.
T getHeight () const
Get height of rectangle.
void repair ()
If the lower right corner of the rect is smaller then the upper left, the points are swapped.
bool isValid () const
Returns if the rect is valid to draw.
position2d< T > getCenter () const
Get the center of the rectangle.
dimension2d< T > getSize () const
Get the dimensions of the rectangle.
void addInternalPoint (const position2d< T > &p)
Adds a point to the rectangle.
void addInternalPoint (T x, T y)
Adds a point to the bounding rectangle.
Public Attributes
position2d< T > UpperLeftCorner
Upper left corner.
position2d< T > LowerRightCorner
Lower right corner.
Detailed Description
template<class T>
class irr::core::rect< T >
Rectangle template.
Mostly used by 2D GUI elements and for 2D drawing methods. It has 2 positions instead of position and dimension and a fast method for collision detection with other rectangles and points.
Coordinates are (0,0) for top-left corner, and increasing to the right and to the bottom.
Definition at line 26 of file rect.h.
Member Function Documentation
addInternalPoint() [1/2]
template<class T > void irr::core::rect< T >::addInternalPoint (const position2d< T > & p) inline
Adds a point to the rectangle.
Causes the rectangle to grow bigger if point is outside of the box
Parameters
p Point to add to the box.
Definition at line 250 of file rect.h.
Referenced by irr::core::rect< f32 >::addInternalPoint().
addInternalPoint() [2/2]
template<class T > void irr::core::rect< T >::addInternalPoint (T x, T y) inline
Adds a point to the bounding rectangle.
Causes the rectangle to grow bigger if point is outside of the box
Parameters
x X-Coordinate of the point to add to this box.
y Y-Coordinate of the point to add to this box.
Definition at line 260 of file rect.h.
clipAgainst()
template<class T > void irr::core::rect< T >::clipAgainst (const rect< T > & other) inline
Clips this rectangle with another one.
Parameters
other Rectangle to clip with
Definition at line 131 of file rect.h.
Referenced by GUIEditBoxWithScrollBar::draw(), irr::gui::CGUIImage::draw(), irr::gui::CGUIFont::draw(), irr::gui::CGUIListBox::draw(), irr::gui::CGUIEditBox::draw(), irr::gui::CGUITabControl::draw(), GUITable::draw(), and irr::video::COpenGL3DriverBase::setViewPort().
constrainTo()
template<class T > bool irr::core::rect< T >::constrainTo (const rect< T > & other) inline
Moves this rectangle to fit inside another one.
Returns
True on success, false if not possible
Definition at line 156 of file rect.h.
isPointInside()
template<class T > bool irr::core::rect< T >::isPointInside (const position2d< T > & pos) const inline
Returns if a 2d point is within this rectangle.
Parameters
pos Position to test if it lies within this rectangle.
Returns
True if the position is within the rectangle, false if not.
Definition at line 110 of file rect.h.
Referenced by irr::gui::CGUITabControl::getTabAt(), irr::gui::IGUIElement::isPointInside(), irr::gui::CGUIScrollBar::OnEvent(), irr::gui::CGUIButton::OnEvent(), GUIButton::OnEvent(), GUIScrollBar::OnEvent(), irr::gui::CGUICheckBox::OnEvent(), irr::gui::CGUIComboBox::OnEvent(), and GUIFormSpecMenu::OnEvent().
isRectCollided()
template<class T > bool irr::core::rect< T >::isRectCollided (const rect< T > & other) const inline
Check if the rectangle collides with another rectangle.
Parameters
other Rectangle to test collision with
Returns
True if the rectangles collide.
Definition at line 121 of file rect.h.
Referenced by GUIScrollContainer::draw().
isValid()
template<class T > bool irr::core::rect< T >::isValid () const inline
Returns if the rect is valid to draw.
It would be invalid if the UpperLeftCorner is lower or more right than the LowerRightCorner.
Definition at line 225 of file rect.h.
Referenced by irr::video::CNullDriver::createImage(), GUIEditBoxWithScrollBar::draw(), irr::gui::CGUIFont::draw(), irr::gui::CGUIEditBox::draw(), irr::video::COpenGL3DriverBase::draw2DImage(), irr::video::CNullDriver::draw2DImage(), and irr::video::COpenGL3DriverBase::draw2DImageBatch().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/rect.h