Three Cubes Game: irr::gui::CGUITabControl Class Reference
irr::gui::CGUITabControl Class Reference
A standard tab control.
#include <CGUITabControl.h>
Public Member Functions
CGUITabControl (IGUIEnvironment *environment, IGUIElement *parent, const core::rect< s32 > &rectangle, bool fillbackground=true, bool border=true, s32 id=-1)
destructor
virtual ~CGUITabControl ()
destructor
IGUITab * addTab (const wchar_t *caption, s32 id=-1) override
Adds a tab.
s32 addTab (IGUITab *tab) override
Adds an existing tab.
IGUITab * insertTab (s32 idx, const wchar_t *caption, s32 id=-1) override
Insert the tab at the given index.
s32 insertTab (s32 idx, IGUITab *tab, bool serializationMode) override
Insert an existing tab.
void removeTab (s32 idx) override
Removes a tab from the tabcontrol.
void clear () override
Clears the tabcontrol removing all tabs.
s32 getTabCount () const override
Returns amount of tabs in the tabcontrol.
IGUITab * getTab (s32 idx) const override
Returns a tab based on zero based index.
bool setActiveTab (s32 idx) override
Brings a tab to front.
bool setActiveTab (IGUITab *tab) override
Brings a tab to front.
s32 getTabIndex (const IGUIElement *tab) const override
For given given tab find it's zero-based index (or -1 for not found)
s32 getActiveTab () const override
Returns which tab is currently active.
s32 getTabAt (s32 xpos, s32 ypos) const override
get the the id of the tab at the given absolute coordinates
bool OnEvent (const SEvent &event) override
called if an event happened.
void draw () override
draws the element and its children
void removeChild (IGUIElement *child) override
Removes a child.
void setTabHeight (s32 height) override
Set the height of the tabs.
s32 getTabHeight () const override
Get the height of the tabs.
void setTabMaxWidth (s32 width) override
set the maximal width of a tab. Per default width is 0 which means "no width restriction".
s32 getTabMaxWidth () const override
get the maximal width of a tab
void setTabVerticalAlignment (gui::EGUI_ALIGNMENT alignment) override
Set the alignment of the tabs.
gui::EGUI_ALIGNMENT getTabVerticalAlignment () const override
Get the alignment of the tabs.
void setTabExtraWidth (s32 extraWidth) override
Set the extra width added to tabs on each side of the text.
s32 getTabExtraWidth () const override
Get the extra width added to tabs on each side of the text.
void updateAbsolutePosition () override
Update the position of the element, decides scroll button status.
Public Member Functions inherited from irr::gui::IGUITabControl
IGUITabControl (IGUIEnvironment *environment, IGUIElement *parent, s32 id, core::rect< s32 > rectangle)
constructor
Public Member Functions inherited from irr::gui::IGUIElement
IGUIElement (EGUI_ELEMENT_TYPE type, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle)
Constructor.
virtual ~IGUIElement ()
Destructor.
IGUIElement * getParent () const
Returns parent of this element.
core::rect< s32 > getRelativePosition () const
Returns the relative rectangle of this element.
void setRelativePosition (const core::rect< s32 > &r)
Sets the relative rectangle of this element.
void setRelativePosition (const core::position2di &position)
Sets the relative rectangle of this element, maintaining its current width and height.
void setRelativePositionProportional (const core::rect< f32 > &r)
Sets the relative rectangle of this element as a proportion of its parent's area.
core::rect< s32 > getAbsolutePosition () const
Gets the absolute rectangle of this element.
core::rect< s32 > getAbsoluteClippingRect () const
Returns the visible area of the element.
void setNotClipped (bool noClip)
Sets whether the element will ignore its parent's clipping rectangle.
bool isNotClipped () const
Gets whether the element will ignore its parent's clipping rectangle.
void setMaxSize (core::dimension2du size)
Sets the maximum size allowed for this element.
void setMinSize (core::dimension2du size)
Sets the minimum size allowed for this element.
void setAlignment (EGUI_ALIGNMENT left, EGUI_ALIGNMENT right, EGUI_ALIGNMENT top, EGUI_ALIGNMENT bottom)
The alignment defines how the borders of this element will be positioned when the parent element is resized.
EGUI_ALIGNMENT getAlignLeft () const
How left element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignRight () const
How right element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignTop () const
How top element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignBottom () const
How bottom element border is aligned when parent is resized.
virtual IGUIElement * getElementFromPoint (const core::position2d< s32 > &point)
Returns the topmost GUI element at the specific position.
virtual bool isPointInside (const core::position2d< s32 > &point) const
Returns true if a point is within this element.
virtual void addChild (IGUIElement *child)
Adds a GUI element as new child of this element.
virtual void removeAllChildren ()
Removes all children.
virtual void remove ()
Removes this element from its parent.
virtual void OnPostRender (u32 timeMs)
animate the element and its children.
virtual void move (core::position2d< s32 > absoluteMovement)
Moves this element.
virtual bool isVisible () const
Returns true if element is visible.
virtual bool isTrulyVisible () const
Check whether the element is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool visible)
Sets the visible state of this element.
virtual bool isSubElement () const
Returns true if this element was created as part of its parent control.
virtual void setSubElement (bool subElement)
Sets whether this control was created as part of its parent.
void setTabStop (bool enable)
If set to true, the focus will visit this element when using the tab key to cycle through elements.
bool isTabStop () const
Returns true if this element can be focused by navigating with the tab key.
void setTabOrder (s32 index)
Sets the priority of focus when using the tab key to navigate between a group of elements.
s32 getTabOrder () const
Returns the number in the tab order sequence.
void setTabGroup (bool isGroup)
Sets whether this element is a container for a group of elements which can be navigated using the tab key.
bool isTabGroup () const
Returns true if this element is a tab group.
IGUIElement * getTabGroup ()
Returns the container element which holds all elements in this element's tab group.
virtual bool isEnabled () const
Returns true if element is enabled.
virtual void setEnabled (bool enabled)
Sets the enabled state of this element.
virtual void setText (const wchar_t *text)
Sets the new caption of this element.
virtual const wchar_t * getText () const
Returns caption of this element.
virtual void setToolTipText (const wchar_t *text)
Sets the new caption of this element.
virtual const core::stringw & getToolTipText () const
Returns caption of this element.
virtual s32 getID () const
Returns id. Can be used to identify the element.
virtual void setID (s32 id)
Sets the id of this element.
virtual bool bringToFront (IGUIElement *child)
Brings a child to front.
virtual bool sendToBack (IGUIElement *child)
Moves a child to the back, so it's siblings are drawn on top of it.
virtual const std::list< IGUIElement * > & getChildren () const
Returns list with children of this element.
virtual IGUIElement * getElementFromId (s32 id, bool searchchildren=false) const
Finds the first element with the given id.
bool isMyChild (IGUIElement *child) const
bool getNextElement (s32 startOrder, bool reverse, bool group, IGUIElement *&first, IGUIElement *&closest, bool includeInvisible=false, bool includeDisabled=false) const
searches elements to find the closest next element to tab to
EGUI_ELEMENT_TYPE getType () const
Returns the type of the gui element.
virtual bool hasType (EGUI_ELEMENT_TYPE type) const
Returns true if the gui element supports the given type.
virtual const c8 * getTypeName () const
Returns the type name of the gui element.
virtual const c8 * getName () const
Returns the name of the element.
virtual void setName (const c8 *name)
Sets the name of the element.
virtual void setName (const core::stringc &name)
Sets the name of the element.
virtual bool acceptsIME ()
Returns whether the element takes input from the IME.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::IEventReceiver
virtual ~IEventReceiver ()
Destructor.
Private Member Functions
void scrollLeft ()
void scrollRight ()
bool needScrollControl (s32 startIndex=0, bool withScrollControl=false, s32 *pos_rightmost=nullptr)
Indicates whether the tabs overflow in X direction.
s32 calculateScrollIndexFromActive ()
Left index calculation based on the selected tab.
s32 calcTabWidth (IGUIFont *font, const wchar_t *text) const
core::rect< s32 > calcTabPos ()
void setVisibleTab (s32 idx)
void removeTabButNotChild (s32 idx)
void recalculateScrollButtonPlacement ()
void recalculateScrollBar ()
void refreshSprites ()
Private Attributes
core::array< IGUITab * > Tabs
s32 ActiveTabIndex
bool Border
bool FillBackground
bool ScrollControl
s32 TabHeight
gui::EGUI_ALIGNMENT VerticalAlignment
IGUIButton * UpButton
IGUIButton * DownButton
s32 TabMaxWidth
s32 CurrentScrollTabIndex
s32 TabExtraWidth
Additional Inherited Members
Protected Member Functions inherited from irr::gui::IGUIElement
void addChildToEnd (IGUIElement *child)
void reorderChildren (std::list< IGUIElement * >::iterator from, std::list< IGUIElement * >::iterator to, const std::vector< IGUIElement * > &neworder)
void recalculateAbsolutePosition (bool recursive)
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Static Protected Member Functions inherited from irr::gui::IGUIElement
template<typename Iterator >
static size_t _fastSetChecksum (Iterator begin, Iterator end)
Protected Attributes inherited from irr::gui::IGUIElement
std::list< IGUIElement * > Children
List of all children of this element.
IGUIElement * Parent
Pointer to the parent.
std::list< IGUIElement * >::iterator ParentPos
Our position in the parent list. Only valid when Parent != nullptr.
core::rect< s32 > RelativeRect
relative rect of element
core::rect< s32 > AbsoluteRect
absolute rect of element
core::rect< s32 > AbsoluteClippingRect
absolute clipping rect of element
core::rect< s32 > DesiredRect
core::rect< s32 > LastParentRect
for calculating the difference when resizing parent
core::rect< f32 > ScaleRect
relative scale of the element inside its parent
core::dimension2du MaxSize
maximum and minimum size of the element
core::dimension2du MinSize
bool IsVisible
is visible?
bool IsEnabled
is enabled?
bool IsSubElement
is a part of a larger whole and should not be serialized?
bool NoClip
does this element ignore its parent's clipping rectangle?
core::stringw Text
caption
core::stringw ToolTipText
tooltip
core::stringc Name
users can set this for identifying the element by string
s32 ID
users can set this for identifying the element by integer
bool IsTabStop
tab stop like in windows
s32 TabOrder
tab order
bool IsTabGroup
tab groups are containers like windows, use ctrl+tab to navigate
EGUI_ALIGNMENT AlignLeft
tells the element how to act when its parent is resized
EGUI_ALIGNMENT AlignRight
EGUI_ALIGNMENT AlignTop
EGUI_ALIGNMENT AlignBottom
IGUIEnvironment * Environment
GUI Environment.
EGUI_ELEMENT_TYPE Type
type of element
Detailed Description
A standard tab control.
Definition at line 59 of file CGUITabControl.h.
Constructor & Destructor Documentation
CGUITabControl()
irr::gui::CGUITabControl::CGUITabControl (IGUIEnvironment * environment, IGUIElement * parent, const core::rect< s32 > & rectangle, bool fillbackground = true, bool border = true, s32 id = -1)
destructor
constructor
Definition at line 105 of file CGUITabControl.cpp.
References irr::gui::IGUIEnvironment::addButton(), irr::gui::EGDS_BUTTON_HEIGHT, irr::gui::EGUIA_LOWERRIGHT, irr::gui::EGUIA_UPPERLEFT, irr::gui::IGUIElement::Environment, irr::gui::IGUIEnvironment::getBuiltInFont(), irr::gui::IGUISkin::getSize(), irr::gui::IGUIEnvironment::getSkin(), irr::gui::IGUISkin::getSpriteBank(), irr::IReferenceCounted::grab(), irr::gui::IGUIElement::setAlignment(), irr::IReferenceCounted::setDebugName(), irr::gui::IGUIButton::setOverrideFont(), irr::gui::IGUIButton::setSpriteBank(), irr::gui::IGUIElement::setSubElement(), setTabVerticalAlignment(), and irr::gui::IGUIElement::setVisible().
Member Function Documentation
addTab()
s32 irr::gui::CGUITabControl::addTab (IGUITab * tab) override virtual
Adds an existing tab.
adds a tab which has been created elsewhere
Implements irr::gui::IGUITabControl.
Definition at line 216 of file CGUITabControl.cpp.
References insertTab().
insertTab()
s32 irr::gui::CGUITabControl::insertTab (s32 idx, IGUITab * tab, bool serializationMode) override virtual
Insert an existing tab.
Note that it will also add the tab as a child of this TabControl.
Returns
Index of added tab (should be same as the one passed) or -1 for failure
Implements irr::gui::IGUITabControl.
Definition at line 250 of file CGUITabControl.cpp.
References irr::gui::IGUIElement::getParent(), getTabIndex(), irr::IReferenceCounted::grab(), and irr::gui::IGUIElement::setVisible().
setTabVerticalAlignment()
void irr::gui::CGUITabControl::setTabVerticalAlignment (gui::EGUI_ALIGNMENT alignment) override virtual
Set the alignment of the tabs.
Set the alignment of the tabs note: EGUIA_CENTER is not an option
Implements irr::gui::IGUITabControl.
Definition at line 851 of file CGUITabControl.cpp.
Referenced by CGUITabControl().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CGUITabControl.h
lib/irrlichtmt/source/Irrlicht/CGUITabControl.cpp