Three Cubes Game: irr::core::line2d< T > Class Template Reference
irr::core::line2d< T > Class Template Reference
2D line between two points with intersection methods.
#include <line2d.h>
Public Member Functions
line2d ()
Default constructor for line going from (0,0) to (1,1).
line2d (T xa, T ya, T xb, T yb)
Constructor for line between the two points.
line2d (const vector2d< T > &start, const vector2d< T > &end)
Constructor for line between the two points given as vectors.
line2d< T > operator+ (const vector2d< T > &point) const
line2d< T > & operator+= (const vector2d< T > &point)
line2d< T > operator- (const vector2d< T > &point) const
line2d< T > & operator-= (const vector2d< T > &point)
bool operator== (const line2d< T > &other) const
bool operator!= (const line2d< T > &other) const
void setLine (const T &xa, const T &ya, const T &xb, const T &yb)
Set this line to new line going through the two points.
void setLine (const vector2d< T > &nstart, const vector2d< T > &nend)
Set this line to new line going through the two points.
void setLine (const line2d< T > &line)
Set this line to new line given as parameter.
T getLength () const
Get length of line.
T getLengthSQ () const
Get squared length of the line.
vector2d< T > getMiddle () const
Get middle of the line.
vector2d< T > getVector () const
Get the vector of the line.
bool intersectAsSegments (const line2d< T > &other) const
bool incidentSegments (const line2d< T > &other) const
bool nearlyParallel (const line2d< T > &line, const T factor=relativeErrorFactor< T >()) const
vector2d< T > fastLinesIntersection (const line2d< T > &l) const
bool lineIntersectSegment (const line2d< T > &segment, vector2d< T > &out) const
bool intersectWith (const line2d< T > &l, vector2d< T > &out, bool checkOnlySegments=true, bool ignoreCoincidentLines=false) const
Tests if this line intersects with another line.
vector2d< T > getUnitVector () const
Get unit vector of the line.
f64 getAngleWith (const line2d< T > &l) const
Get angle between this line and given line.
T getPointOrientation (const vector2d< T > &point) const
Tells us if the given point lies to the left, right, or on the line.
bool isPointOnLine (const vector2d< T > &point) const
Check if the given point is a member of the line.
bool isPointBetweenStartAndEnd (const vector2d< T > &point) const
Check if the given point is between start and end of the line.
vector2d< T > getClosestPoint (const vector2d< T > &point, bool checkOnlySegments=true) const
Get the closest point on this line to a point.
vector2df getClosestPoint (const vector2df &point, bool checkOnlySegments) const
Public Attributes
vector2d< T > start
Start point of the line.
vector2d< T > end
End point of the line.
Detailed Description
template<class T>
class irr::core::line2d< T >
2D line between two points with intersection methods.
Definition at line 18 of file line2d.h.
Member Function Documentation
fastLinesIntersection()
template<class T > vector2d<T> irr::core::line2d< T >::fastLinesIntersection (const line2d< T > & l) const inline
returns a intersection point of 2 lines (if lines are not parallel). Behaviour undefined if lines are parallel or coincident. It's on optimized intersectWith with checkOnlySegments=false and ignoreCoincidentLines=true
Definition at line 116 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
Referenced by irr::core::line2d< T >::lineIntersectSegment().
getAngleWith()
template<class T > f64 irr::core::line2d< T >::getAngleWith (const line2d< T > & l) const inline
Get angle between this line and given line.
Parameters
l Other line for test.
Returns
Angle in degrees.
Definition at line 266 of file line2d.h.
References irr::core::vector2d< T >::getAngleWith(), and irr::core::line2d< T >::getVector().
getClosestPoint()
template<class T > vector2d<T> irr::core::line2d< T >::getClosestPoint (const vector2d< T > & point, bool checkOnlySegments = true) const inline
Get the closest point on this line to a point.
Parameters
point Starting search at this point
checkOnlySegments Default (true) is to return a point on the line-segment (between begin and end) of the line. When set to false the function will check for the first the closest point on the the line even when outside the segment.
Definition at line 301 of file line2d.h.
References irr::core::vector2d< T >::dotProduct(), irr::core::line2d< T >::end, irr::core::vector2d< T >::getLength(), irr::core::line2d< T >::start, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
getLength()
template<class T > T irr::core::line2d< T >::getLength () const inline
Get length of line.
Returns
Length of the line.
Definition at line 51 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
Referenced by irr::core::line2d< T >::getUnitVector().
getLengthSQ()
template<class T > T irr::core::line2d< T >::getLengthSQ () const inline
Get squared length of the line.
Returns
Squared length of line.
Definition at line 55 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
getMiddle()
template<class T > vector2d<T> irr::core::line2d< T >::getMiddle () const inline
Get middle of the line.
Returns
center of the line.
Definition at line 59 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
getPointOrientation()
template<class T > T irr::core::line2d< T >::getPointOrientation (const vector2d< T > & point) const inline
Tells us if the given point lies to the left, right, or on the line.
Returns
0 if the point is on the line <0 if to the left, or >0 if to the right.
Definition at line 276 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
Referenced by irr::core::line2d< T >::isPointOnLine().
getUnitVector()
template<class T > vector2d<T> irr::core::line2d< T >::getUnitVector () const inline
Get unit vector of the line.
Returns
Unit vector of this line.
Definition at line 257 of file line2d.h.
References irr::core::line2d< T >::end, irr::core::line2d< T >::getLength(), and irr::core::line2d< T >::start.
getVector()
template<class T > vector2d<T> irr::core::line2d< T >::getVector () const inline
Get the vector of the line.
Returns
The vector of the line.
Definition at line 66 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
Referenced by irr::core::line2d< T >::getAngleWith(), and irr::core::line2d< T >::nearlyParallel().
incidentSegments()
template<class T > bool irr::core::line2d< T >::incidentSegments (const line2d< T > & other) const inline
Check if 2 segments are incident (intersects in exactly 1 point).
Definition at line 96 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
intersectAsSegments()
template<class T > bool irr::core::line2d< T >::intersectAsSegments (const line2d< T > & other) const inline
Check if this segment intersects another segment, or if segments are coincindent (colinear).
Definition at line 70 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
intersectWith()
template<class T > bool irr::core::line2d< T >::intersectWith (const line2d< T > & l, vector2d< T > & out, bool checkOnlySegments = true, bool ignoreCoincidentLines = false) const inline
Tests if this line intersects with another line.
Parameters
l Other line to test intersection with.
checkOnlySegments Default is to check intersection between the begin and endpoints. When set to false the function will check for the first intersection point when extending the lines.
out If there is an intersection, the location of the intersection will be stored in this vector.
ignoreCoincidentLines When true coincident lines (lines above each other) are never considered as intersecting. When false the center of the overlapping part is returned.
Returns
True if there is an intersection, false if not.
Definition at line 158 of file line2d.h.
References irr::core::line2d< T >::end, irr::core::equals(), irr::core::line2d< T >::start, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
isPointBetweenStartAndEnd()
template<class T > bool irr::core::line2d< T >::isPointBetweenStartAndEnd (const vector2d< T > & point) const inline
Check if the given point is between start and end of the line.
Assumes that the point is already somewhere on the line.
Definition at line 292 of file line2d.h.
References irr::core::line2d< T >::end, and irr::core::line2d< T >::start.
isPointOnLine()
template<class T > bool irr::core::line2d< T >::isPointOnLine (const vector2d< T > & point) const inline
Check if the given point is a member of the line.
Returns
True if point is between start and end, else false.
Definition at line 284 of file line2d.h.
References irr::core::line2d< T >::end, irr::core::line2d< T >::getPointOrientation(), and irr::core::line2d< T >::start.
lineIntersectSegment()
template<class T > bool irr::core::line2d< T >::lineIntersectSegment (const line2d< T > & segment, vector2d< T > & out) const inline
Check if this line intersect a segment. The eventual intersection point is returned in "out".
Definition at line 139 of file line2d.h.
References irr::core::line2d< T >::end, irr::core::line2d< T >::fastLinesIntersection(), irr::core::vector2d< T >::isBetweenPoints(), irr::core::line2d< T >::nearlyParallel(), and irr::core::line2d< T >::start.
nearlyParallel()
template<class T > bool irr::core::line2d< T >::nearlyParallel (const line2d< T > & line, const T factor = relativeErrorFactor<T>()) const inline
Check if 2 lines/segments are parallel or nearly parallel.
Definition at line 104 of file line2d.h.
References irr::core::line2d< T >::getVector(), and irr::core::vector2d< T >::nearlyParallel().
Referenced by irr::core::line2d< T >::lineIntersectSegment().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/line2d.h