Three Cubes Game: Mapgen Class Reference
Mapgen Class Reference
Public Member Functions
Mapgen (int mapgenid, MapgenParams *params, EmergeParams *emerge)
DISABLE_CLASS_COPY (Mapgen)
virtual MapgenType getType () const
s16 findGroundLevel (v2s16 p2d, s16 ymin, s16 ymax)
s16 findLiquidSurface (v2s16 p2d, s16 ymin, s16 ymax)
void updateHeightmap (v3s16 nmin, v3s16 nmax)
void getSurfaces (v2s16 p2d, s16 ymin, s16 ymax, std::vector< s16 > &floors, std::vector< s16 > &ceilings)
void updateLiquid (UniqueQueue< v3s16 > *trans_liquid, v3s16 nmin, v3s16 nmax)
void setLighting (u8 light, v3s16 nmin, v3s16 nmax)
void calcLighting (v3s16 nmin, v3s16 nmax, v3s16 full_nmin, v3s16 full_nmax, bool propagate_shadow=true)
void propagateSunlight (v3s16 nmin, v3s16 nmax, bool propagate_shadow)
void spreadLight (const v3s16 &nmin, const v3s16 &nmax)
virtual void makeChunk (BlockMakeData *data)
virtual int getGroundLevelAtPoint (v2s16 p)
virtual int getSpawnLevelAtPoint (v2s16 p)
Static Public Member Functions
static u32 getBlockSeed (v3s16 p, s32 seed)
static u32 getBlockSeed2 (v3s16 p, s32 seed)
static MapgenType getMapgenType (const std::string &mgname)
static const char * getMapgenName (MapgenType mgtype)
static Mapgen * createMapgen (MapgenType mgtype, MapgenParams *params, EmergeParams *emerge)
static MapgenParams * createMapgenParams (MapgenType mgtype)
static void getMapgenNames (std::vector< const char * > *mgnames, bool include_hidden)
static void setDefaultSettings (Settings *settings)
Public Attributes
s32 seed = 0
int water_level = 0
int mapgen_limit = 0
u32 flags = 0
bool generating = false
int id = -1
MMVManip * vm = nullptr
const NodeDefManager * ndef = nullptr
u32 blockseed
s16 * heightmap = nullptr
biome_t * biomemap = nullptr
v3s16 csize
BiomeGen * biomegen = nullptr
GenerateNotifier gennotify
Private Member Functions
void lightSpread (VoxelArea &a, std::queue< std::pair< v3s16, u8 >> &queue, const v3s16 &p, u8 light)
bool isLiquidHorizontallyFlowable (u32 vi, v3s16 em)
Detailed Description
Definition at line 156 of file mapgen.h.
Member Function Documentation
calcLighting()
void Mapgen::calcLighting (v3s16 nmin, v3s16 nmax, v3s16 full_nmin, v3s16 full_nmax, bool propagate_shadow = true)
Run all lighting calculations.
Parameters
nmin Area to spread sunlight in
nmax ^
full_nmin Area to recalculate light in
full_nmax ^
propagate_shadow see propagateSunlight()
Definition at line 468 of file mapgen.cpp.
References propagateSunlight(), and spreadLight().
lightSpread()
void Mapgen::lightSpread (VoxelArea & a, std::queue< std::pair< v3s16, u8 >> & queue, const v3s16 & p, u8 light) private
Spread light to the node at the given position, add to queue if changed. The given light value is diminished once.
Parameters
a VoxelArea being operated on
queue Queue for later lightSpread() calls
p Node position
light Light value (contains both banks)
Definition at line 431 of file mapgen.cpp.
Referenced by spreadLight().
propagateSunlight()
void Mapgen::propagateSunlight (v3s16 nmin, v3s16 nmax, bool propagate_shadow)
Spread sunlight from the area above downwards. Note that affected nodes have their night bank cleared so you want to run a light spread afterwards.
Parameters
nmin Area to operate on
nmax ^
propagate_shadow Ignore obstructions above and spread sun anyway
Definition at line 478 of file mapgen.cpp.
References VoxelArea::add_y(), irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
Referenced by calcLighting().
setLighting()
void Mapgen::setLighting (u8 light, v3s16 nmin, v3s16 nmax)
Set light in entire area to fixed value.
Parameters
light Light value (contains both banks)
nmin Area to operate on
nmax ^
Definition at line 416 of file mapgen.cpp.
References irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
spreadLight()
void Mapgen::spreadLight (const v3s16 & nmin, const v3s16 & nmax)
Spread light in the given area. Artificial light is taken from nodedef, sunlight must already be set.
Parameters
nmin Area to operate on
nmax ^
Definition at line 514 of file mapgen.cpp.
References lightSpread(), irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
Referenced by calcLighting().
The documentation for this class was generated from the following files:
src/mapgen/mapgen.h
src/mapgen/mapgen.cpp