Three Cubes Game: irr::core::array< T > Class Template Reference
irr::core::array< T > Class Template Reference
Self reallocating template array (like stl vector) with additional features.
#include <irrArray.h>
Public Types
typedef T value_type
typedef u32 size_type
Public Member Functions
array ()
Default constructor for empty array.
array (u32 start_count)
Constructs an array and allocates an initial chunk of memory.
array (const array< T > &other)
Copy constructor.
void reallocate (u32 new_size, bool canShrink=true)
Reallocates the array, make it bigger or smaller.
void push_back (const T &element)
Adds an element at back of array.
void push_back (T &&element)
void push_front (const T &element)
Adds an element at the front of the array.
void push_front (T &&element)
void insert (const T &element, u32 index=0)
Insert item into array at specified position.
void clear ()
Clears the array and deletes all allocated memory.
void set_data (const T *newData, u32 newSize, bool newDataIsSorted=false, bool canShrink=false)
Set (copy) data from given memory block.
bool equals (const T *otherData, u32 size) const
Compare if given data block is identical to the data in our array.
void set_used (u32 usedNow)
Sets the size of the array and allocates new elements if necessary.
const array< T > & operator= (const array< T > &other)
Assignment operator.
array< T > & operator= (const std::vector< T > &other)
array< T > & operator= (std::vector< T > &&other)
bool operator== (const array< T > &other) const
Equality operator.
bool operator!= (const array< T > &other) const
Inequality operator.
T & operator[] (u32 index)
Direct access operator.
const T & operator[] (u32 index) const
Direct const access operator.
T & getLast ()
Gets last element.
const T & getLast () const
Gets last element.
T * pointer ()
Gets a pointer to the array.
const T * const_pointer () const
Gets a const pointer to the array.
u32 size () const
Get number of occupied elements of the array.
u32 allocated_size () const
Get amount of memory allocated.
bool empty () const
Check if array is empty.
void sort ()
Sorts the array using heapsort.
s32 binary_search (const T &element)
Performs a binary search for an element, returns -1 if not found.
s32 binary_search (const T &element) const
Performs a binary search for an element if possible, returns -1 if not found.
s32 binary_search (const T &element, s32 left, s32 right) const
Performs a binary search for an element, returns -1 if not found.
s32 binary_search_multi (const T &element, s32 &last)
s32 linear_search (const T &element) const
Finds an element in linear time, which is very slow.
s32 linear_reverse_search (const T &element) const
Finds an element in linear time, which is very slow.
void erase (u32 index)
Erases an element from the array.
void erase (u32 index, s32 count)
Erases some elements from the array.
void set_sorted (bool _is_sorted)
Sets if the array is sorted.
void swap (array< T > &other)
Swap the content of this array container with the content of another array.
std::vector< T > steal ()
Pull the contents of this array as a vector.
Private Attributes
std::vector< T > m_data
bool is_sorted
Detailed Description
template<class T>
class irr::core::array< T >
Self reallocating template array (like stl vector) with additional features.
Some features are: Heap sorting, binary search methods, easier debugging.
Definition at line 24 of file irrArray.h.
Constructor & Destructor Documentation
array()
template<class T > irr::core::array< T >::array (u32 start_count) inline explicit
Constructs an array and allocates an initial chunk of memory.
Parameters
start_count Amount of elements to pre-allocate.
Definition at line 36 of file irrArray.h.
Member Function Documentation
allocated_size()
template<class T > u32 irr::core::array< T >::allocated_size () const inline
Get amount of memory allocated.
Returns
Amount of memory allocated. The amount of bytes allocated would be allocated_size() * sizeof(ElementTypeUsed);
Definition at line 253 of file irrArray.h.
binary_search() [1/3]
template<class T > s32 irr::core::array< T >::binary_search (const T & element) inline
Performs a binary search for an element, returns -1 if not found.
The array will be sorted before the binary search if it is not already sorted. Caution is advised! Be careful not to call this on unsorted const arrays, or the slower method will be used.
Parameters
element Element to search for.
Returns
Position of the searched element if it was found, otherwise -1 is returned.
Definition at line 286 of file irrArray.h.
Referenced by irr::core::array< irr::scene::IMeshBuffer * >::binary_search().
binary_search() [2/3]
template<class T > s32 irr::core::array< T >::binary_search (const T & element) const inline
Performs a binary search for an element if possible, returns -1 if not found.
This method is for const arrays and so cannot call sort(), if the array is not sorted then linear_search will be used instead. Potentially very slow!
Parameters
element Element to search for.
Returns
Position of the searched element if it was found, otherwise -1 is returned.
Definition at line 298 of file irrArray.h.
binary_search() [3/3]
template<class T > s32 irr::core::array< T >::binary_search (const T & element, s32 left, s32 right) const inline
Performs a binary search for an element, returns -1 if not found.
Parameters
element Element to search for.
left First left index
right Last right index.
Returns
Position of the searched element if it was found, otherwise -1 is returned.
Definition at line 312 of file irrArray.h.
binary_search_multi()
template<class T > s32 irr::core::array< T >::binary_search_multi (const T & element, s32 & last) inline
Performs a binary search for an element, returns -1 if not found. it is used for searching a multiset The array will be sorted before the binary search if it is not already sorted.
Parameters
element Element to search for.
&last return lastIndex of equal elements
Returns
Position of the first searched element if it was found, otherwise -1 is returned.
Definition at line 334 of file irrArray.h.
const_pointer()
template<class T > const T* irr::core::array< T >::const_pointer () const inline
Gets a const pointer to the array.
Returns
Pointer to the array.
Definition at line 236 of file irrArray.h.
Referenced by irr::video::COpenGL3DriverBase::draw2DImageBatch(), irr::scene::CMeshBuffer< T >::getIndices(), irr::scene::SSkinMeshBuffer::getIndices(), irr::core::array< irr::scene::IMeshBuffer * >::operator==(), irr::video::IRenderTarget::setTexture(), and irr::core::ustring16::trim().
empty()
template<class T > bool irr::core::array< T >::empty () const inline
Check if array is empty.
Returns
True if the array is empty false if not.
Definition at line 261 of file irrArray.h.
Referenced by irr::gui::CGUISpriteBank::draw2DSpriteBatch().
equals()
template<class T > bool irr::core::array< T >::equals (const T * otherData, u32 size) const inline
Compare if given data block is identical to the data in our array.
Like operator ==, but without the need to create the array
Parameters
otherData Address to data against which we compare, must contain size elements
size Amount of elements in otherData
Definition at line 138 of file irrArray.h.
Referenced by irr::core::array< irr::scene::IMeshBuffer * >::operator==(), and irr::video::COpenGLCoreRenderTarget< TOpenGLDriver, TOpenGLTexture >::setTextures().
erase() [1/2]
template<class T > void irr::core::array< T >::erase (u32 index) inline
Erases an element from the array.
May be slow, because all elements following after the erased element have to be copied.
Parameters
index Index of element to be erased.
Definition at line 380 of file irrArray.h.
erase() [2/2]
template<class T > void irr::core::array< T >::erase (u32 index, s32 count) inline
Erases some elements from the array.
May be slow, because all elements following after the erased element have to be copied.
Parameters
index Index of the first element to be erased.
count Amount of elements to be erased.
Definition at line 393 of file irrArray.h.
insert()
template<class T > void irr::core::array< T >::insert (const T & element, u32 index = 0) inline
Insert item into array at specified position.
Parameters
element Element to be inserted
index Where position to insert the new element.
Definition at line 100 of file irrArray.h.
linear_reverse_search()
template<class T > s32 irr::core::array< T >::linear_reverse_search (const T & element) const inline
Finds an element in linear time, which is very slow.
Use binary_search for faster finding. Only works if ==operator is implemented.
Parameters
element Element to search for.
Returns
Position of the searched element if it was found, otherwise -1 is returned.
Definition at line 366 of file irrArray.h.
linear_search()
template<class T > s32 irr::core::array< T >::linear_search (const T & element) const inline
Finds an element in linear time, which is very slow.
Use binary_search for faster finding. Only works if ==operator is implemented.
Parameters
element Element to search for.
Returns
Position of the searched element if it was found, otherwise -1 is returned.
Definition at line 351 of file irrArray.h.
Referenced by irr::core::array< irr::scene::IMeshBuffer * >::binary_search().
pointer()
template<class T > T* irr::core::array< T >::pointer () inline
Gets a pointer to the array.
Returns
Pointer to the array.
Definition at line 228 of file irrArray.h.
Referenced by irr::scene::CMeshBuffer< T >::getIndices(), irr::scene::SSkinMeshBuffer::getIndices(), and irr::core::ustring16::split().
push_back()
template<class T > void irr::core::array< T >::push_back (const T & element) inline
Adds an element at back of array.
If the array is too small to add this new element it is made bigger.
Parameters
element Element to add at the back of the array.
Definition at line 65 of file irrArray.h.
Referenced by TextureBufferOutput::activate(), irr::scene::CSkinnedMesh::addJoint(), irr::scene::CSkinnedMesh::addJoints(), irr::gui::CGUISpriteBank::addTexture(), irr::video::CNullDriver::addTextureCubemap(), irr::scene::CMeshBuffer< T >::append(), irr::scene::COBJMeshFileLoader::createMesh(), irr::scene::CMeshManipulator::createMeshCopy(), irr::gui::CGUIFont::draw(), irr::video::COpenGL3DriverBase::draw2DImageBatch(), irr::gui::CGUISpriteBank::draw2DSpriteBatch(), irr::scene::CSkinnedMesh::finalize(), irr::scene::CSceneManager::getSceneNodesFromType(), irr::gui::CGUISpriteBank::setTexture(), and irr::scene::CB3DMeshWriter::writeMesh().
push_front()
template<class T > void irr::core::array< T >::push_front (const T & element) inline
Adds an element at the front of the array.
If the array is to small to add this new element, the array is made bigger. Please note that this is slow, because the whole array needs to be copied for this.
Parameters
element Element to add at the back of the array.
Definition at line 83 of file irrArray.h.
Referenced by irr::scene::CSkinnedMesh::finalize().
reallocate()
template<class T > void irr::core::array< T >::reallocate (u32 new_size, bool canShrink = true) inline
Reallocates the array, make it bigger or smaller.
Parameters
new_size New size of array.
canShrink Specifies whether the array is reallocated even if enough space is available. Setting this flag to false can speed up array usage, but may use more memory than required by the data.
Definition at line 51 of file irrArray.h.
Referenced by irr::scene::CMeshBuffer< T >::append(), irr::scene::COBJMeshFileLoader::createMesh(), irr::scene::CMeshManipulator::createMeshCopy(), and irr::gui::CGUISpriteBank::draw2DSpriteBatch().
set_data()
template<class T > void irr::core::array< T >::set_data (const T * newData, u32 newSize, bool newDataIsSorted = false, bool canShrink = false) inline
Set (copy) data from given memory block.
Parameters
newData data to set, must have newSize elements
newSize Amount of elements in newData
canShrink When true we reallocate the array even it can shrink. May reduce memory usage, but call is more whenever size changes.
newDataIsSorted Info if you pass sorted/unsorted data
Definition at line 124 of file irrArray.h.
Referenced by irr::video::COpenGLCoreRenderTarget< TOpenGLDriver, TOpenGLTexture >::setTextures().
set_used()
template<class T > void irr::core::array< T >::set_used (u32 usedNow) inline
Sets the size of the array and allocates new elements if necessary.
Parameters
usedNow Amount of elements now used.
Definition at line 147 of file irrArray.h.
Referenced by irr::scene::COBJMeshFileLoader::createMesh().
size()
template<class T > u32 irr::core::array< T >::size () const inline
Get number of occupied elements of the array.
Returns
Size of elements in the array which are actually occupied.
Definition at line 244 of file irrArray.h.
Referenced by TextureBufferOutput::activate(), irr::scene::CSkinnedMesh::addJoints(), irr::scene::CSkinnedMesh::animateMesh(), irr::gui::CGUISpriteBank::clear(), irr::scene::COBJMeshFileLoader::createMesh(), irr::video::COpenGL3DriverBase::draw2DImageBatch(), irr::gui::CGUISpriteBank::draw2DSpriteBatch(), irr::core::array< irr::scene::IMeshBuffer * >::equals(), irr::core::string< c8 >::equals_ignore_case(), irr::scene::CSkinnedMesh::finalize(), irr::scene::CMeshBuffer< T >::getIndexCount(), irr::scene::SSkinMeshBuffer::getIndexCount(), irr::scene::CSkinnedMesh::getJointCount(), irr::scene::CSkinnedMesh::getJointName(), irr::scene::CSkinnedMesh::getJointNumber(), irr::gui::CGUISpriteBank::getTexture(), TextureBuffer::getTexture(), irr::gui::CGUISpriteBank::getTextureCount(), TextureBuffer::getTextureCount(), irr::core::string< c8 >::lower_ignore_case(), irr::core::array< irr::scene::IMeshBuffer * >::operator==(), irr::scene::CSkinnedMesh::recoverJointsFromMesh(), irr::scene::CSkinnedMesh::refreshJointCache(), irr::scene::CAnimatedMeshSceneNode::render(), irr::scene::CSkinnedMesh::resetAnimation(), irr::scene::CSkinnedMesh::setHardwareSkinning(), irr::gui::CGUISpriteBank::setTexture(), irr::video::IRenderTarget::setTexture(), irr::video::COpenGLCoreRenderTarget< TOpenGLDriver, TOpenGLTexture >::setTextures(), irr::scene::CSkinnedMesh::skinMesh(), irr::core::ustring16::split(), irr::scene::CSkinnedMesh::transferJointsToMesh(), irr::scene::CSkinnedMesh::transferOnlyJointsHintsToMesh(), irr::scene::CSkinnedMesh::useAnimationFrom(), irr::scene::CB3DMeshWriter::writeMesh(), and irr::scene::CSkinnedMesh::~CSkinnedMesh().
sort()
template<class T > void irr::core::array< T >::sort () inline
Sorts the array using heapsort.
There is no additional memory waste and the algorithm performs O(n*log n) in worst case.
Definition at line 270 of file irrArray.h.
Referenced by irr::core::array< irr::scene::IMeshBuffer * >::binary_search(), and irr::core::array< irr::scene::IMeshBuffer * >::binary_search_multi().
swap()
template<class T > void irr::core::array< T >::swap (array< T > & other) inline
Swap the content of this array container with the content of another array.
Afterward this object will contain the content of the other object and the other object will contain the content of this object.
Parameters
other Swap content with this object
Definition at line 414 of file irrArray.h.
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/irrArray.h