Three Cubes Game: TextureBuffer Class Reference
TextureBuffer Class Reference
#include <pipeline.h>
Classes
struct TextureDefinition
Public Member Functions
void setTexture (u8 index, core::dimension2du size, const std::string &name, video::ECOLOR_FORMAT format, bool clear=false)
void setTexture (u8 index, v2f scale_factor, const std::string &name, video::ECOLOR_FORMAT format, bool clear=false)
virtual u8 getTextureCount () override
virtual video::ITexture * getTexture (u8 index) override
virtual void reset (PipelineContext &context) override
void swapTextures (u8 texture_a, u8 texture_b)
Private Member Functions
bool ensureTexture (video::ITexture **textureSlot, const TextureDefinition &definition, PipelineContext &context)
Private Attributes
video::IVideoDriver * m_driver { nullptr }
std::vector< TextureDefinition > m_definitions
core::array< video::ITexture * > m_textures
Static Private Attributes
static const u8 NO_DEPTH_TEXTURE = 255
Detailed Description
Texture buffer represents a framebuffer with a multiple attached textures.
Note
Use of TextureBuffer requires use of gl_FragData[] in the shader
Definition at line 115 of file pipeline.h.
Member Function Documentation
ensureTexture()
bool TextureBuffer::ensureTexture (video::ITexture ** textureSlot, const TextureDefinition & definition, PipelineContext & context) private
Make sure the texture in the given slot matches the texture definition given the current context.
Parameters
textureSlot address of the texture pointer to verify and populate.
definition logical definition of the texture
context current context of the rendering pipeline
Returns
true if a new texture was created and put into the slot
false if the slot was not modified
Definition at line 117 of file pipeline.cpp.
References irr::video::IVideoDriver::addRenderTargetTexture(), irr::video::IVideoDriver::addTexture(), irr::video::IVideoDriver::createImage(), irr::IReferenceCounted::drop(), irr::video::IImage::getData(), irr::video::IImage::getDataSizeFromFormat(), irr::core::dimension2d< T >::Height, irr::video::IVideoDriver::removeTexture(), irr::core::dimension2d< T >::Width, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
getTexture()
video::ITexture * TextureBuffer::getTexture (u8 index) override virtual
Get a texture by index. Returns nullptr is the texture does not exist.
Implements RenderSource.
Definition at line 36 of file pipeline.cpp.
References irr::core::array< T >::size().
Referenced by TextureBufferOutput::activate(), and InitInterlacedMaskStep::run().
getTextureCount()
virtual u8 TextureBuffer::getTextureCount () inline override virtual
Return the number of textures in the source.
Implements RenderSource.
Definition at line 141 of file pipeline.h.
References irr::core::array< T >::size().
setTexture() [1/2]
void TextureBuffer::setTexture (u8 index, core::dimension2du size, const std::string & name, video::ECOLOR_FORMAT format, bool clear = false)
Configure fixed-size texture for the specific index
Parameters
index index of the texture
size width and height of the texture in pixels
height height of the texture in pixels
name unique name of the texture
format color format
Definition at line 44 of file pipeline.cpp.
setTexture() [2/2]
void TextureBuffer::setTexture (u8 index, v2f scale_factor, const std::string & name, video::ECOLOR_FORMAT format, bool clear = false)
Configure relative-size texture for the specific index
Parameters
index index of the texture
scale_factor relation of the texture dimensions to the screen dimensions
name unique name of the texture
format color format
Definition at line 61 of file pipeline.cpp.
The documentation for this class was generated from the following files:
src/client/render/pipeline.h
src/client/render/pipeline.cpp