Three Cubes Game: NodeDefManager Class Reference
NodeDefManager Class Reference
This class is for getting the actual properties of nodes from their content ID.
#include <nodedef.h>
Public Member Functions
NodeDefManager ()
const ContentFeatures & get (content_t c) const
const ContentFeatures & get (const MapNode &n) const
ContentLightingFlags getLightingFlags (content_t c) const
ContentLightingFlags getLightingFlags (const MapNode &n) const
const ContentFeatures & get (const std::string &name) const
bool getId (const std::string &name, content_t &result) const
content_t getId (const std::string &name) const
bool getIds (const std::string &name, std::vector< content_t > &result) const
core::aabbox3d< s16 > getSelectionBoxIntUnion () const
bool nodeboxConnects (MapNode from, MapNode to, u8 connect_face) const
void pendNodeResolve (NodeResolver *nr) const
bool cancelNodeResolveCallback (NodeResolver *nr) const
content_t set (const std::string &name, const ContentFeatures &def)
content_t allocateDummy (const std::string &name)
void removeNode (const std::string &name)
void updateAliases (IItemDefManager *idef)
void applyTextureOverrides (const std::vector< TextureOverride > &overrides)
void updateTextures (IGameDef *gamedef, void *progress_cbk_args)
void serialize (std::ostream &os, u16 protocol_version) const
void deSerialize (std::istream &is, u16 protocol_version)
void setNodeRegistrationStatus (bool completed)
void runNodeResolveCallbacks ()
void resetNodeResolveState ()
void resolveCrossrefs ()
Private Member Functions
void clear ()
content_t allocateId ()
void addNameIdMapping (content_t i, const std::string &name)
void eraseIdFromGroups (content_t id)
void fixSelectionBoxIntUnion ()
Private Attributes
std::vector< ContentFeatures > m_content_features
Features indexed by ID.
NameIdMapping m_name_id_mapping
A mapping for fast conversion between names and IDs.
std::unordered_map< std::string, content_t > m_name_id_mapping_with_aliases
std::unordered_map< std::string, std::vector< content_t > > m_group_to_items
content_t m_next_id
bool m_node_registration_complete
True if all nodes have been registered.
aabb3f m_selection_box_union
core::aabbox3d< s16 > m_selection_box_int_union
std::vector< NodeResolver * > m_pending_resolve_callbacks
ContentLightingFlags m_content_lighting_flag_cache [CONTENT_MAX+1L]
Detailed Description
This class is for getting the actual properties of nodes from their content ID.
The nodes on the map are represented by three numbers (see MapNode). The first number (param0) is the type of a node. All node types have own properties (see ContentFeatures). This class is for storing and getting the properties of nodes. The manager is first filled with registered nodes, then as the game begins, functions only get const pointers to it, to prevent modification of registered nodes.
Definition at line 558 of file nodedef.h.
Constructor & Destructor Documentation
NodeDefManager()
NodeDefManager::NodeDefManager ()
Creates a NodeDefManager, and registers three ContentFeatures: CONTENT_AIR, CONTENT_UNKNOWN and CONTENT_IGNORE.
Definition at line 1055 of file nodedef.cpp.
References clear().
Member Function Documentation
addNameIdMapping()
void NodeDefManager::addNameIdMapping (content_t i, const std::string & name) private
Binds the given content ID and node name. Registers them in m_name_id_mapping and m_name_id_mapping_with_aliases.
Parameters
i a content ID
name a node name
Definition at line 1625 of file nodedef.cpp.
References m_name_id_mapping, and m_name_id_mapping_with_aliases.
Referenced by clear(), deSerialize(), and set().
allocateDummy()
content_t NodeDefManager::allocateDummy (const std::string & name)
Allocates a blank node ID for the given name.
Parameters
name name of a node
Returns
allocated ID or CONTENT_IGNORE if could not allocate an ID.
Definition at line 1414 of file nodedef.cpp.
References set().
allocateId()
content_t NodeDefManager::allocateId () private
Allocates a new content ID, and returns it.
Returns
the allocated ID or CONTENT_IGNORE if could not allocate
Definition at line 1202 of file nodedef.cpp.
References m_content_features, and m_next_id.
Referenced by set().
applyTextureOverrides()
void NodeDefManager::applyTextureOverrides (const std::vector< TextureOverride > & overrides)
Replaces the textures of registered nodes with the ones specified in the texturepack's override.txt file
Parameters
overrides the texture overrides
Definition at line 1454 of file nodedef.cpp.
References getId(), and m_content_features.
cancelNodeResolveCallback()
bool NodeDefManager::cancelNodeResolveCallback (NodeResolver * nr) const
Stops listening to the NodeDefManager.
Returns
true if the listener was registered before, false otherwise
Definition at line 1648 of file nodedef.cpp.
References m_pending_resolve_callbacks.
clear()
void NodeDefManager::clear () private
Resets the manager to its initial state. See the documentation of the constructor.
Definition at line 1074 of file nodedef.cpp.
References addNameIdMapping(), m_content_features, m_content_lighting_flag_cache, m_group_to_items, m_name_id_mapping, m_name_id_mapping_with_aliases, m_next_id, m_selection_box_int_union, m_selection_box_union, irr::core::aabbox3d< T >::reset(), and resetNodeResolveState().
Referenced by deSerialize(), and NodeDefManager().
deSerialize()
void NodeDefManager::deSerialize (std::istream & is, u16 protocol_version)
Restores the manager from a serialized stream. This clears the previous state.
Parameters
is input stream containing a serialized NodeDefManager
protocol_version Active network protocol version
Definition at line 1568 of file nodedef.cpp.
References addNameIdMapping(), clear(), fixSelectionBoxIntUnion(), m_content_features, m_content_lighting_flag_cache, m_name_id_mapping, m_selection_box_union, and resolveCrossrefs().
eraseIdFromGroups()
void NodeDefManager::eraseIdFromGroups (content_t id) private
Removes a content ID from all groups. Erases content IDs from vectors in m_group_to_items and removes empty vectors.
Parameters
id Content ID
Definition at line 1350 of file nodedef.cpp.
References m_group_to_items.
Referenced by removeNode(), and set().
fixSelectionBoxIntUnion()
void NodeDefManager::fixSelectionBoxIntUnion () inline private
Recalculates m_selection_box_int_union based on m_selection_box_union.
Definition at line 1333 of file nodedef.cpp.
References m_selection_box_int_union, m_selection_box_union, irr::core::aabbox3d< T >::MaxEdge, irr::core::aabbox3d< T >::MinEdge, irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
Referenced by deSerialize(), and set().
get() [1/3]
const ContentFeatures& NodeDefManager::get (const MapNode & n) const inline
Returns the properties of the given node.
Parameters
n a map node
Returns
properties of the given node or CONTENT_UNKNOWN if the given content type is not registered.
Definition at line 585 of file nodedef.h.
References get().
get() [2/3]
const ContentFeatures & NodeDefManager::get (const std::string & name) const
Returns the node properties for a node name.
Parameters
name name of a node
Returns
properties of the given node or CONTENT_UNKNOWN if not found
Definition at line 1193 of file nodedef.cpp.
References get(), and getId().
get() [3/3]
const ContentFeatures& NodeDefManager::get (content_t c) const inline
Returns the properties for the given content type.
Parameters
c content type of a node
Returns
properties of the given content type, or CONTENT_UNKNOWN if the given content type is not registered.
Definition at line 573 of file nodedef.h.
References m_content_features.
Referenced by Pathfinder::calcCost(), get(), MapNode::getDegRotate(), MapNode::getNeighbors(), Pathfinder::getPath(), nodeboxConnects(), and Pathfinder::walkDownwards().
getId() [1/2]
content_t NodeDefManager::getId (const std::string & name) const
Returns the content ID for the given name.
Parameters
name a node name
Returns
ID of the node or CONTENT_IGNORE if not found
Definition at line 1160 of file nodedef.cpp.
References getId().
getId() [2/2]
bool NodeDefManager::getId (const std::string & name, content_t & result) const
Returns the content ID for the given name.
Parameters
name a node name
[out] result will contain the content ID if found, otherwise remains unchanged
Returns
true if the ID was found, false otherwise
Definition at line 1149 of file nodedef.cpp.
References m_name_id_mapping_with_aliases.
Referenced by applyTextureOverrides(), get(), getId(), getIds(), and resolveCrossrefs().
getIds()
bool NodeDefManager::getIds (const std::string & name, std::vector< content_t > & result) const
Returns the content IDs of the given node name or node group name. Group names start with "group:".
Parameters
name a node name or node group name
[out] result will be appended with matching IDs
Returns
true if name is a valid node name or a (not necessarily valid) group name
Definition at line 1168 of file nodedef.cpp.
References getId(), and m_group_to_items.
Referenced by resolveCrossrefs().
getSelectionBoxIntUnion()
core::aabbox3d<s16> NodeDefManager::getSelectionBoxIntUnion () const inline
Returns the smallest box in integer node coordinates that contains all nodes' selection boxes. The returned box might be larger than the minimal size if the largest node is removed from the manager.
Definition at line 637 of file nodedef.h.
References m_selection_box_int_union.
Referenced by Environment::continueRaycast().
nodeboxConnects()
bool NodeDefManager::nodeboxConnects (MapNode from, MapNode to, u8 connect_face) const
Checks whether a node connects to an adjacent node.
Parameters
from the node to be checked
to the adjacent node
connect_face a bit field indicating which face of the node is adjacent to the other node. Bits: +y (least significant), -y, -z, -x, +z, +x (most significant).
Returns
true if the node connects, false otherwise
Definition at line 1707 of file nodedef.cpp.
References get().
pendNodeResolve()
void NodeDefManager::pendNodeResolve (NodeResolver * nr) const
Registers a NodeResolver to wait for the registration of ContentFeatures. Once the node registration finishes, all listeners are notified.
Definition at line 1638 of file nodedef.cpp.
References m_node_registration_complete, and m_pending_resolve_callbacks.
removeNode()
void NodeDefManager::removeNode (const std::string & name)
Removes the given node name from the manager. The node ID will remain in the manager, but won't be linked to any name.
Parameters
name name to be removed
Definition at line 1423 of file nodedef.cpp.
References eraseIdFromGroups(), m_name_id_mapping, and m_name_id_mapping_with_aliases.
resetNodeResolveState()
void NodeDefManager::resetNodeResolveState ()
Sets the registration completion flag to false and unregisters all NodeResolver instances listening to the manager.
Definition at line 1676 of file nodedef.cpp.
References m_node_registration_complete, and m_pending_resolve_callbacks.
Referenced by clear().
resolveCrossrefs()
void NodeDefManager::resolveCrossrefs ()
Resolves (caches the IDs) cross-references between nodes, like liquid alternatives. Must be called after node registration has finished!
Definition at line 1689 of file nodedef.cpp.
References getId(), getIds(), and m_content_features.
Referenced by deSerialize().
runNodeResolveCallbacks()
void NodeDefManager::runNodeResolveCallbacks ()
Notifies the registered NodeResolver instances that node registration has finished, then unregisters all listeners. Must be called after node registration has finished!
Definition at line 1665 of file nodedef.cpp.
References m_pending_resolve_callbacks.
serialize()
void NodeDefManager::serialize (std::ostream & os, u16 protocol_version) const
Writes the content of this manager to the given output stream.
Parameters
protocol_version Active network protocol version
Definition at line 1539 of file nodedef.cpp.
References m_content_features.
set()
content_t NodeDefManager::set (const std::string & name, const ContentFeatures & def)
Registers a new node type with the given name and allocates a new content ID. Should not be called with an already existing name.
Parameters
name name of the node, must match with def.name.
def definition of the registered node type.
Returns
ID of the registered node or CONTENT_IGNORE if the function could not allocate an ID.
Definition at line 1371 of file nodedef.cpp.
References addNameIdMapping(), allocateId(), eraseIdFromGroups(), fixSelectionBoxIntUnion(), m_content_features, m_content_lighting_flag_cache, m_group_to_items, m_name_id_mapping, and m_selection_box_union.
Referenced by allocateDummy().
setNodeRegistrationStatus()
void NodeDefManager::setNodeRegistrationStatus (bool completed) inline
Used to indicate that node registration has finished.
Parameters
completed tells whether registration is complete
Definition at line 735 of file nodedef.h.
References m_node_registration_complete.
updateAliases()
void NodeDefManager::updateAliases (IItemDefManager * idef)
Regenerates the alias list (a map from names to node IDs).
Parameters
idef the item definition manager containing alias information
Definition at line 1439 of file nodedef.cpp.
References m_name_id_mapping, and m_name_id_mapping_with_aliases.
updateTextures()
void NodeDefManager::updateTextures (IGameDef * gamedef, void * progress_cbk_args)
Only the client uses this. Loads textures and shaders required for rendering the nodes.
Parameters
gamedef must be a Client.
progress_cbk called each time a node is loaded. Arguments: progress_cbk_args, number of loaded ContentFeatures, number of total ContentFeatures.
progress_cbk_args passed to the callback function
Definition at line 1515 of file nodedef.cpp.
References m_content_features.
Member Data Documentation
m_content_lighting_flag_cache
ContentLightingFlags NodeDefManager::m_content_lighting_flag_cache[CONTENT_MAX+1L] private
Fast cache of content lighting flags.
Definition at line 848 of file nodedef.h.
Referenced by clear(), deSerialize(), and set().
m_group_to_items
std::unordered_map<std::string, std::vector<content_t> > NodeDefManager::m_group_to_items private
A mapping from group names to a vector of content types that belong to it. Necessary for a direct lookup in getIds(). Note: Not serialized.
Definition at line 813 of file nodedef.h.
Referenced by clear(), eraseIdFromGroups(), getIds(), and set().
m_name_id_mapping_with_aliases
std::unordered_map<std::string, content_t> NodeDefManager::m_name_id_mapping_with_aliases private
Like m_name_id_mapping, but maps only from names to IDs, and includes aliases too. Updated by updateAliases(). Note: Not serialized.
Definition at line 806 of file nodedef.h.
Referenced by addNameIdMapping(), clear(), getId(), removeNode(), and updateAliases().
m_next_id
content_t NodeDefManager::m_next_id private
The next ID that might be free to allocate. It can be allocated already, because CONTENT_AIR, CONTENT_UNKNOWN and CONTENT_IGNORE are registered when the manager is initialized, and new IDs are allocated from 0.
Definition at line 821 of file nodedef.h.
Referenced by allocateId(), and clear().
m_pending_resolve_callbacks
std::vector<NodeResolver *> NodeDefManager::m_pending_resolve_callbacks mutable private
NodeResolver instances to notify once node registration has finished. Even constant NodeDefManager instances can register listeners.
Definition at line 843 of file nodedef.h.
Referenced by cancelNodeResolveCallback(), pendNodeResolve(), resetNodeResolveState(), and runNodeResolveCallbacks().
m_selection_box_int_union
core::aabbox3d<s16> NodeDefManager::m_selection_box_int_union private
The smallest box in integer node coordinates that contains all nodes' selection boxes. Might be larger if big nodes are removed from the manager.
Definition at line 837 of file nodedef.h.
Referenced by clear(), fixSelectionBoxIntUnion(), and getSelectionBoxIntUnion().
m_selection_box_union
aabb3f NodeDefManager::m_selection_box_union private
The union of all nodes' selection boxes. Might be larger if big nodes are removed from the manager.
Definition at line 830 of file nodedef.h.
Referenced by clear(), deSerialize(), fixSelectionBoxIntUnion(), and set().
The documentation for this class was generated from the following files:
src/nodedef.h
src/nodedef.cpp