Three Cubes Game: irr::gui::IGUISkin Class Reference
irr::gui::IGUISkin Class Reference abstract
A skin modifies the look of the GUI elements.
#include <IGUISkin.h>
Public Member Functions
virtual video::SColor getColor (EGUI_DEFAULT_COLOR color) const =0
returns default color
virtual void setColor (EGUI_DEFAULT_COLOR which, video::SColor newColor)=0
sets a default color
virtual s32 getSize (EGUI_DEFAULT_SIZE size) const =0
returns size for the given size type
virtual const wchar_t * getDefaultText (EGUI_DEFAULT_TEXT text) const =0
Returns a default text.
virtual void setDefaultText (EGUI_DEFAULT_TEXT which, const wchar_t *newText)=0
Sets a default text.
virtual void setSize (EGUI_DEFAULT_SIZE which, s32 size)=0
sets a default size
virtual IGUIFont * getFont (EGUI_DEFAULT_FONT which=EGDF_DEFAULT) const =0
returns the default font
virtual void setFont (IGUIFont *font, EGUI_DEFAULT_FONT which=EGDF_DEFAULT)=0
sets a default font
virtual IGUISpriteBank * getSpriteBank () const =0
returns the sprite bank
virtual void setSpriteBank (IGUISpriteBank *bank)=0
sets the sprite bank
virtual u32 getIcon (EGUI_DEFAULT_ICON icon) const =0
Returns a default icon.
virtual void setIcon (EGUI_DEFAULT_ICON icon, u32 index)=0
Sets a default icon.
virtual void draw3DButtonPaneStandard (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)=0
draws a standard 3d button pane
virtual void draw3DButtonPanePressed (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)=0
draws a pressed 3d button pane
virtual void draw3DSunkenPane (IGUIElement *element, video::SColor bgcolor, bool flat, bool fillBackGround, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)=0
draws a sunken 3d pane
virtual core::rect< s32 > draw3DWindowBackground (IGUIElement *element, bool drawTitleBar, video::SColor titleBarColor, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, core::rect< s32 > *checkClientArea=0)=0
draws a window background
virtual void draw3DMenuPane (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)=0
draws a standard 3d menu pane
virtual void draw3DToolBar (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0)=0
draws a standard 3d tool bar
virtual void draw3DTabButton (IGUIElement *element, bool active, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, gui::EGUI_ALIGNMENT alignment=EGUIA_UPPERLEFT)=0
draws a tab button
virtual void draw3DTabBody (IGUIElement *element, bool border, bool background, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, s32 tabHeight=-1, gui::EGUI_ALIGNMENT alignment=EGUIA_UPPERLEFT)=0
draws a tab control body
virtual void drawIcon (IGUIElement *element, EGUI_DEFAULT_ICON icon, const core::position2di position, u32 starttime=0, u32 currenttime=0, bool loop=false, const core::rect< s32 > *clip=0)=0
draws an icon, usually from the skin's sprite bank
virtual void draw2DRectangle (IGUIElement *element, const video::SColor &color, const core::rect< s32 > &pos, const core::rect< s32 > *clip=0)=0
draws a 2d rectangle.
virtual EGUI_SKIN_TYPE getType () const
get the type of this skin
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
A skin modifies the look of the GUI elements.
Definition at line 384 of file IGUISkin.h.
Member Function Documentation
draw2DRectangle()
virtual void irr::gui::IGUISkin::draw2DRectangle (IGUIElement * element, const video::SColor & color, const core::rect< s32 > & pos, const core::rect< s32 > * clip = 0) pure virtual
draws a 2d rectangle.
Parameters
element Pointer to the element which wishes to draw this icon. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
color Color of the rectangle to draw. The alpha component specifies how transparent the rectangle will be.
pos Position of the rectangle.
clip Pointer to rectangle against which the rectangle will be clipped. If the pointer is null, no clipping will be performed.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by GUIEditBoxWithScrollBar::draw(), irr::gui::CGUITab::draw(), irr::gui::CGUIScrollBar::draw(), GUIScrollBar::draw(), irr::gui::CGUIImage::draw(), irr::gui::CGUIListBox::draw(), irr::gui::CGUIEditBox::draw(), and GUITable::draw().
draw3DButtonPanePressed()
virtual void irr::gui::IGUISkin::draw3DButtonPanePressed (IGUIElement * element, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) pure virtual
draws a pressed 3d button pane
Used for drawing for example buttons in pressed state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by irr::gui::CGUIButton::draw().
draw3DButtonPaneStandard()
virtual void irr::gui::IGUISkin::draw3DButtonPaneStandard (IGUIElement * element, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) pure virtual
draws a standard 3d button pane
Used for drawing for example buttons in normal state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by irr::gui::CGUIScrollBar::draw(), GUIScrollBar::draw(), and irr::gui::CGUIButton::draw().
draw3DMenuPane()
virtual void irr::gui::IGUISkin::draw3DMenuPane (IGUIElement * element, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) pure virtual
draws a standard 3d menu pane
Used for drawing for menus and context menus. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
draw3DSunkenPane()
virtual void irr::gui::IGUISkin::draw3DSunkenPane (IGUIElement * element, video::SColor bgcolor, bool flat, bool fillBackGround, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) pure virtual
draws a sunken 3d pane
Used for drawing the background of edit, combo or check boxes.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
bgcolor Background color.
flat Specifies if the sunken pane should be flat or displayed as sunken deep into the ground.
fillBackGround Specifies if the background should be filled with the background color or not be drawn at all.
rect Defining area where to draw.
clip Clip area.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by GUIEditBoxWithScrollBar::draw(), irr::gui::CGUIStaticText::draw(), irr::gui::CGUICheckBox::draw(), GUIScene::draw(), irr::gui::CGUIListBox::draw(), irr::gui::CGUIComboBox::draw(), irr::gui::StaticText::draw(), irr::gui::CGUIEditBox::draw(), and GUITable::draw().
draw3DTabBody()
virtual void irr::gui::IGUISkin::draw3DTabBody (IGUIElement * element, bool border, bool background, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0, s32 tabHeight = -1, gui::EGUI_ALIGNMENT alignment = EGUIA_UPPERLEFT) pure virtual
draws a tab control body
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
border Specifies if the border should be drawn.
background Specifies if the background should be drawn.
rect Defining area where to draw.
clip Clip area.
tabHeight Height of tab.
alignment Alignment of GUI element.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by irr::gui::CGUITabControl::draw().
draw3DTabButton()
virtual void irr::gui::IGUISkin::draw3DTabButton (IGUIElement * element, bool active, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0, gui::EGUI_ALIGNMENT alignment = EGUIA_UPPERLEFT) pure virtual
draws a tab button
Used for drawing for tab buttons on top of tabs.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
active Specifies if the tab is currently active.
rect Defining area where to draw.
clip Clip area.
alignment Alignment of GUI element.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by irr::gui::CGUITabControl::draw().
draw3DToolBar()
virtual void irr::gui::IGUISkin::draw3DToolBar (IGUIElement * element, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0) pure virtual
draws a standard 3d tool bar
Used for drawing for toolbars and menus.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
draw3DWindowBackground()
virtual core::rect<s32> irr::gui::IGUISkin::draw3DWindowBackground (IGUIElement * element, bool drawTitleBar, video::SColor titleBarColor, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0, core::rect< s32 > * checkClientArea = 0) pure virtual
draws a window background
Used for drawing the background of dialogs and windows.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
titleBarColor Title color.
drawTitleBar True to enable title drawing.
rect Defining area where to draw.
clip Clip area.
checkClientArea When set to non-null the function will not draw anything, but will instead return the clientArea which can be used for drawing by the calling window. That is the area without borders and without titlebar.
Returns
Returns rect where it would be good to draw title bar text. This will work even when checkClientArea is set to a non-null value.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by irr::gui::CGUIFileOpenDialog::draw().
drawIcon()
virtual void irr::gui::IGUISkin::drawIcon (IGUIElement * element, EGUI_DEFAULT_ICON icon, const core::position2di position, u32 starttime = 0, u32 currenttime = 0, bool loop = false, const core::rect< s32 > * clip = 0) pure virtual
draws an icon, usually from the skin's sprite bank
Parameters
element Pointer to the element which wishes to draw this icon. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
icon Specifies the icon to be drawn.
position The position to draw the icon
starttime The time at the start of the animation
currenttime The present time, used to calculate the frame number
loop Whether the animation should loop or not
clip Clip area.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by irr::gui::CGUICheckBox::draw().
getDefaultText()
virtual const wchar_t* irr::gui::IGUISkin::getDefaultText (EGUI_DEFAULT_TEXT text) const pure virtual
Returns a default text.
For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog().
getIcon()
virtual u32 irr::gui::IGUISkin::getIcon (EGUI_DEFAULT_ICON icon) const pure virtual
Returns a default icon.
Returns the sprite index within the sprite bank
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
Referenced by irr::gui::CGUIComboBox::CGUIComboBox(), irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog(), irr::gui::CGUIComboBox::draw(), irr::gui::CGUIFileOpenDialog::fillListBox(), and irr::gui::CGUIScrollBar::refreshControls().
setDefaultText()
virtual void irr::gui::IGUISkin::setDefaultText (EGUI_DEFAULT_TEXT which, const wchar_t * newText) pure virtual
Sets a default text.
For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
setIcon()
virtual void irr::gui::IGUISkin::setIcon (EGUI_DEFAULT_ICON icon, u32 index) pure virtual
Sets a default icon.
Sets the sprite index used for drawing icons like arrows, close buttons and ticks in checkboxes
Parameters
icon Enum specifying which icon to change
index The sprite index used to draw this icon
Implemented in irr::gui::CGUISkin, and irr::gui::GUISkin.
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IGUISkin.h