Three Cubes Game: MenuTextureSource Class Reference
MenuTextureSource Class Reference
#include <guiEngine.h>
Public Member Functions
MenuTextureSource (video::IVideoDriver *driver)
virtual ~MenuTextureSource ()
video::ITexture * getTexture (const std::string &name, u32 *id=NULL)
Private Attributes
video::IVideoDriver * m_driver = nullptr
std::vector< video::ITexture * > m_to_delete
Detailed Description
GUIEngine specific implementation of ISimpleTextureSource
Definition at line 90 of file guiEngine.h.
Constructor & Destructor Documentation
MenuTextureSource()
MenuTextureSource::MenuTextureSource (video::IVideoDriver * driver) inline
default constructor
Parameters
driver the video driver to load textures from
Definition at line 97 of file guiEngine.h.
~MenuTextureSource()
MenuTextureSource::~MenuTextureSource () virtual
destructor, removes all loaded textures
Definition at line 57 of file guiEngine.cpp.
References irr::video::IVideoDriver::getTextureCount(), m_driver, m_to_delete, and irr::video::IVideoDriver::removeTexture().
Member Function Documentation
getTexture()
video::ITexture * MenuTextureSource::getTexture (const std::string & name, u32 * id = NULL) virtual
get a texture, loading it if required
Parameters
name path to the texture
id receives the texture ID, always 0 in this implementation
Implements ISimpleTextureSource.
Definition at line 71 of file guiEngine.cpp.
References irr::video::IVideoDriver::addTexture(), irr::video::IVideoDriver::createImageFromFile(), irr::IReferenceCounted::drop(), irr::video::IVideoDriver::findTexture(), m_driver, and m_to_delete.
Member Data Documentation
m_driver
video::IVideoDriver* MenuTextureSource::m_driver = nullptr private
driver to get textures from
Definition at line 113 of file guiEngine.h.
Referenced by getTexture(), and ~MenuTextureSource().
m_to_delete
std::vector<video::ITexture*> MenuTextureSource::m_to_delete private
set of textures to delete
Definition at line 115 of file guiEngine.h.
Referenced by getTexture(), and ~MenuTextureSource().
The documentation for this class was generated from the following files:
src/gui/guiEngine.h
src/gui/guiEngine.cpp