Three Cubes Game: irr::gui::CGUISkin Class Reference
irr::gui::CGUISkin Class Reference
Public Member Functions
CGUISkin (EGUI_SKIN_TYPE type, video::IVideoDriver *driver)
virtual ~CGUISkin ()
destructor
video::SColor getColor (EGUI_DEFAULT_COLOR color) const override
returns default color
void setColor (EGUI_DEFAULT_COLOR which, video::SColor newColor) override
sets a default color
s32 getSize (EGUI_DEFAULT_SIZE size) const override
returns size for the given size type
void setSize (EGUI_DEFAULT_SIZE which, s32 size) override
sets a default size
IGUIFont * getFont (EGUI_DEFAULT_FONT which=EGDF_DEFAULT) const override
returns the default font
void setFont (IGUIFont *font, EGUI_DEFAULT_FONT which=EGDF_DEFAULT) override
sets a default font
void setSpriteBank (IGUISpriteBank *bank) override
sets the sprite bank used for drawing icons
IGUISpriteBank * getSpriteBank () const override
gets the sprite bank used for drawing icons
u32 getIcon (EGUI_DEFAULT_ICON icon) const override
Returns a default icon.
void setIcon (EGUI_DEFAULT_ICON icon, u32 index) override
Sets a default icon.
const wchar_t * getDefaultText (EGUI_DEFAULT_TEXT text) const override
Returns a default text.
void setDefaultText (EGUI_DEFAULT_TEXT which, const wchar_t *newText) override
Sets a default text.
virtual void draw3DButtonPaneStandard (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0) override
draws a standard 3d button pane
virtual void draw3DButtonPanePressed (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0) override
draws a pressed 3d button pane
virtual void draw3DSunkenPane (IGUIElement *element, video::SColor bgcolor, bool flat, bool fillBackGround, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0) override
draws a sunken 3d pane
virtual core::rect< s32 > draw3DWindowBackground (IGUIElement *element, bool drawTitleBar, video::SColor titleBarColor, const core::rect< s32 > &rect, const core::rect< s32 > *clip, core::rect< s32 > *checkClientArea) override
draws a window background
virtual void draw3DMenuPane (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0) override
draws a standard 3d menu pane
virtual void draw3DToolBar (IGUIElement *element, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0) override
draws a standard 3d tool bar
virtual void draw3DTabButton (IGUIElement *element, bool active, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, EGUI_ALIGNMENT alignment=EGUIA_UPPERLEFT) override
draws a tab button
virtual void draw3DTabBody (IGUIElement *element, bool border, bool background, const core::rect< s32 > &rect, const core::rect< s32 > *clip=0, s32 tabHeight=-1, EGUI_ALIGNMENT alignment=EGUIA_UPPERLEFT) override
draws a tab control body
virtual void drawIcon (IGUIElement *element, EGUI_DEFAULT_ICON icon, const core::position2di position, u32 starttime=0, u32 currenttime=0, bool loop=false, const core::rect< s32 > *clip=0) override
draws an icon, usually from the skin's sprite bank
virtual void draw2DRectangle (IGUIElement *element, const video::SColor &color, const core::rect< s32 > &pos, const core::rect< s32 > *clip=0) override
draws a 2d rectangle.
EGUI_SKIN_TYPE getType () const override
get the type of this skin
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Attributes
video::SColor Colors [EGDC_COUNT]
s32 Sizes [EGDS_COUNT]
u32 Icons [EGDI_COUNT]
IGUIFont * Fonts [EGDF_COUNT]
IGUISpriteBank * SpriteBank
core::stringw Texts [EGDT_COUNT]
video::IVideoDriver * Driver
bool UseGradient
EGUI_SKIN_TYPE Type
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Definition at line 20 of file CGUISkin.h.
Member Function Documentation
draw2DRectangle()
void irr::gui::CGUISkin::draw2DRectangle (IGUIElement * element, const video::SColor & color, const core::rect< s32 > & pos, const core::rect< s32 > * clip = 0) override virtual
draws a 2d rectangle.
Parameters
element Pointer to the element which wishes to draw this icon. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
color Color of the rectangle to draw. The alpha component specifies how transparent the rectangle will be.
pos Position of the rectangle.
clip Pointer to rectangle against which the rectangle will be clipped. If the pointer is null, no clipping will be performed.
Implements irr::gui::IGUISkin.
Definition at line 966 of file CGUISkin.cpp.
References irr::video::IVideoDriver::draw2DRectangle().
draw3DButtonPanePressed()
void irr::gui::CGUISkin::draw3DButtonPanePressed (IGUIElement * element, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0) override virtual
draws a pressed 3d button pane
Used for drawing for example buttons in pressed state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
rect Defining area where to draw.
clip Clip area.
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
Implements irr::gui::IGUISkin.
Definition at line 369 of file CGUISkin.cpp.
References irr::video::IVideoDriver::draw2DRectangle(), irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, getColor(), irr::video::SColor::getInterpolated(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
draw3DButtonPaneStandard()
void irr::gui::CGUISkin::draw3DButtonPaneStandard (IGUIElement * element, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0) override virtual
draws a standard 3d button pane
Used for drawing for example buttons in normal state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
rect Defining area where to draw.
clip Clip area.
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
Implements irr::gui::IGUISkin.
Definition at line 313 of file CGUISkin.cpp.
References irr::video::IVideoDriver::draw2DRectangle(), draw3DSunkenPane(), irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGDC_WINDOW, irr::gui::EGST_BURNING_SKIN, getColor(), irr::video::SColor::getInterpolated(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by draw3DMenuPane().
draw3DMenuPane()
void irr::gui::CGUISkin::draw3DMenuPane (IGUIElement * element, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0) override virtual
draws a standard 3d menu pane
Used for drawing for menus and context menus. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 646 of file CGUISkin.cpp.
References irr::video::IVideoDriver::draw2DRectangle(), draw3DButtonPaneStandard(), irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGST_BURNING_SKIN, getColor(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
draw3DSunkenPane()
void irr::gui::CGUISkin::draw3DSunkenPane (IGUIElement * element, video::SColor bgcolor, bool flat, bool fillBackGround, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0) override virtual
draws a sunken 3d pane
Used for drawing the background of edit, combo or check boxes.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
bgcolor Background color.
flat Specifies if the sunken pane should be flat or displayed as sunken deep into the ground.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 413 of file CGUISkin.cpp.
References irr::video::IVideoDriver::draw2DRectangle(), irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_LIGHT, irr::gui::EGDC_3D_SHADOW, getColor(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
Referenced by draw3DButtonPaneStandard().
draw3DTabBody()
void irr::gui::CGUISkin::draw3DTabBody (IGUIElement * element, bool border, bool background, const core::rect< s32 > & rect, const core::rect< s32 > * clip = 0, s32 tabHeight = -1, EGUI_ALIGNMENT alignment = EGUIA_UPPERLEFT) override virtual
draws a tab control body
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
border Specifies if the border should be drawn.
background Specifies if the background should be drawn.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 853 of file CGUISkin.cpp.
References irr::video::IVideoDriver::draw2DRectangle(), irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGDS_BUTTON_HEIGHT, irr::gui::EGUIA_UPPERLEFT, getColor(), getSize(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
draw3DTabButton()
void irr::gui::CGUISkin::draw3DTabButton (IGUIElement * element, bool active, const core::rect< s32 > & frameRect, const core::rect< s32 > * clip = 0, EGUI_ALIGNMENT alignment = EGUIA_UPPERLEFT) override virtual
draws a tab button
Used for drawing for tab buttons on top of tabs.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
active Specifies if the tab is currently active.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 772 of file CGUISkin.cpp.
References irr::video::IVideoDriver::draw2DRectangle(), irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGUIA_UPPERLEFT, getColor(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
draw3DToolBar()
void irr::gui::CGUISkin::draw3DToolBar (IGUIElement * element, const core::rect< s32 > & r, const core::rect< s32 > * clip = 0) override virtual
draws a standard 3d tool bar
Used for drawing for toolbars and menus.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
rect Defining area where to draw.
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 724 of file CGUISkin.cpp.
References irr::video::SColor::color, irr::video::IVideoDriver::draw2DRectangle(), irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_SHADOW, irr::gui::EGST_BURNING_SKIN, getColor(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
draw3DWindowBackground()
core::rect< s32 > irr::gui::CGUISkin::draw3DWindowBackground (IGUIElement * element, bool drawTitleBar, video::SColor titleBarColor, const core::rect< s32 > & rect, const core::rect< s32 > * clip, core::rect< s32 > * checkClientArea) override virtual
draws a window background
Used for drawing the background of dialogs and windows.
Parameters
element Pointer to the element which wishes to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
titleBarColor Title color.
drawTitleBar True to enable title drawing.
rect Defining area where to draw.
clip Clip area.
checkClientArea When set to non-null the function will not draw anything, but will instead return the clientArea which can be used for drawing by the calling window. That is the area without borders and without titlebar.
Returns
Returns rect where it would be good to draw title bar text. This will work even when checkClientArea is set to a non-null value.
Implements irr::gui::IGUISkin.
Definition at line 497 of file CGUISkin.cpp.
References irr::video::IVideoDriver::draw2DRectangle(), irr::gui::EGDC_3D_DARK_SHADOW, irr::gui::EGDC_3D_FACE, irr::gui::EGDC_3D_HIGH_LIGHT, irr::gui::EGDC_3D_SHADOW, irr::gui::EGDC_WINDOW, irr::gui::EGDS_WINDOW_BUTTON_WIDTH, irr::gui::EGST_BURNING_SKIN, irr::video::SColor::getAlpha(), getColor(), irr::video::SColor::getInterpolated(), getSize(), irr::core::rect< T >::LowerRightCorner, and irr::core::rect< T >::UpperLeftCorner.
drawIcon()
void irr::gui::CGUISkin::drawIcon (IGUIElement * element, EGUI_DEFAULT_ICON icon, const core::position2di position, u32 starttime = 0, u32 currenttime = 0, bool loop = false, const core::rect< s32 > * clip = 0) override virtual
draws an icon, usually from the skin's sprite bank
Parameters
element Pointer to the element which wishes to draw this icon. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
icon Specifies the icon to be drawn.
position The position to draw the icon
starttime The time at the start of the animation
currenttime The present time, used to calculate the frame number
loop Whether the animation should loop or not
clip Clip area.
parent Pointer to the element which wishes to draw this icon. This parameter is usually not used by IGUISkin, but can be used for example by more complex implementations to find out how to draw the part exactly.
icon Specifies the icon to be drawn.
position The position to draw the icon
starttime The time at the start of the animation
currenttime The present time, used to calculate the frame number
loop Whether the animation should loop or not
clip Clip area.
Implements irr::gui::IGUISkin.
Definition at line 945 of file CGUISkin.cpp.
References irr::gui::IGUISpriteBank::draw2DSprite(), irr::gui::EGDC_GRAY_WINDOW_SYMBOL, irr::gui::EGDC_WINDOW_SYMBOL, and irr::gui::IGUIElement::isEnabled().
getDefaultText()
const wchar_t * irr::gui::CGUISkin::getDefaultText (EGUI_DEFAULT_TEXT text) const override virtual
Returns a default text.
For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Returns a default text. For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Implements irr::gui::IGUISkin.
Definition at line 286 of file CGUISkin.cpp.
References irr::gui::EGDT_COUNT.
getIcon()
u32 irr::gui::CGUISkin::getIcon (EGUI_DEFAULT_ICON icon) const override virtual
Returns a default icon.
Returns the sprite index within the sprite bank
Implements irr::gui::IGUISkin.
Definition at line 267 of file CGUISkin.cpp.
References irr::gui::EGDI_COUNT.
getSpriteBank()
IGUISpriteBank * irr::gui::CGUISkin::getSpriteBank () const override virtual
gets the sprite bank used for drawing icons
gets the sprite bank stored
Implements irr::gui::IGUISkin.
Definition at line 247 of file CGUISkin.cpp.
setDefaultText()
void irr::gui::CGUISkin::setDefaultText (EGUI_DEFAULT_TEXT which, const wchar_t * newText) override virtual
Sets a default text.
For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Sets a default text. For example for Message box button captions: "OK", "Cancel", "Yes", "No" and so on.
Implements irr::gui::IGUISkin.
Definition at line 297 of file CGUISkin.cpp.
References irr::gui::EGDT_COUNT.
setIcon()
void irr::gui::CGUISkin::setIcon (EGUI_DEFAULT_ICON icon, u32 index) override virtual
Sets a default icon.
Sets the sprite index used for drawing icons like arrows, close buttons and ticks in checkboxes
Parameters
icon Enum specifying which icon to change
index The sprite index used to draw this icon
Implements irr::gui::IGUISkin.
Definition at line 277 of file CGUISkin.cpp.
References irr::gui::EGDI_COUNT.
setSpriteBank()
void irr::gui::CGUISkin::setSpriteBank (IGUISpriteBank * bank) override virtual
sets the sprite bank used for drawing icons
set a new sprite bank or remove one by passing 0
Implements irr::gui::IGUISkin.
Definition at line 254 of file CGUISkin.cpp.
References irr::IReferenceCounted::drop(), and irr::IReferenceCounted::grab().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CGUISkin.h
lib/irrlichtmt/source/Irrlicht/CGUISkin.cpp