Three Cubes Game: irr::gui::CGUITTFont Class Reference
irr::gui::CGUITTFont Class Reference
Class representing a TrueType font.
#include <CGUITTFont.h>
Public Member Functions
virtual ~CGUITTFont ()
Destructor.
virtual void setBatchLoadSize (u32 batch_size)
Sets the amount of glyphs to batch load.
virtual void setMaxPageTextureSize (const core::dimension2du &texture_size)
Sets the maximum texture size for a page of glyphs.
virtual u32 getFontSize () const
Get the font size.
virtual bool isTransparent () const
Check the font's transparency.
virtual bool useAutoHinting () const
virtual bool useHinting () const
Check if the font hinting is enabled.
virtual bool useMonochrome () const
virtual void setTransparency (const bool flag)
virtual void setMonochrome (const bool flag)
virtual void setFontHinting (const bool enable, const bool enable_auto_hinting=true)
virtual void draw (const core::stringw &text, const core::rect< s32 > &position, video::SColor color, bool hcenter=false, bool vcenter=false, const core::rect< s32 > *clip=0)
Draws some text and clips it to the specified rectangle if wanted.
void draw (const EnrichedString &text, const core::rect< s32 > &position, bool hcenter=false, bool vcenter=false, const core::rect< s32 > *clip=0)
virtual core::dimension2d< u32 > getCharDimension (const wchar_t ch) const
Returns the dimension of a character produced by this font.
virtual core::dimension2d< u32 > getDimension (const wchar_t *text) const
Returns the dimension of a text string.
virtual core::dimension2d< u32 > getDimension (const core::ustring &text) const
virtual s32 getCharacterFromPos (const wchar_t *text, s32 pixel_x) const
Calculates the index of the character in the text which is on a specific position.
virtual s32 getCharacterFromPos (const core::ustring &text, s32 pixel_x) const
virtual void setKerningWidth (s32 kerning)
Sets global kerning width for the font.
virtual void setKerningHeight (s32 kerning)
Sets global kerning height for the font.
virtual s32 getKerningWidth (const wchar_t *thisLetter=0, const wchar_t *previousLetter=0) const
Gets kerning values (distance between letters) for the font. If no parameters are provided,.
virtual s32 getKerningWidth (const uchar32_t thisLetter=0, const uchar32_t previousLetter=0) const
virtual s32 getKerningHeight () const
Returns the distance between letters.
virtual void setInvisibleCharacters (const wchar_t *s)
Define which characters should not be drawn by the font.
virtual void setInvisibleCharacters (const core::ustring &s)
CGUITTGlyphPage * getLastGlyphPage () const
CGUITTGlyphPage * createGlyphPage (const u8 &pixel_mode)
u32 getLastGlyphPageIndex () const
Get the last glyph page's index.
void setFallback (gui::IGUIFont *font)
Set font that should be used for glyphs not present in ours.
virtual video::IImage * createTextureFromChar (const uchar32_t &ch)
virtual video::ITexture * getPageTextureByIndex (const u32 &page_index) const
virtual core::array< scene::ISceneNode * > addTextSceneNode (const wchar_t *text, scene::ISceneManager *smgr, scene::ISceneNode *parent=0, const video::SColor &color=video::SColor(255, 0, 0, 0), bool center=false)
Add a list of scene nodes generated by putting font textures on the 3D planes.
s32 getAscender () const
Public Member Functions inherited from irr::gui::IGUIFont
virtual EGUI_FONT_TYPE getType () const
Returns the type of this font.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Static Public Member Functions
static CGUITTFont * createTTFont (IGUIEnvironment *env, const io::path &filename, const u32 size, const bool antialias=true, const bool transparency=true, const u32 shadow=0, const u32 shadow_alpha=255)
static CGUITTFont * createTTFont (IrrlichtDevice *device, const io::path &filename, const u32 size, const bool antialias=true, const bool transparency=true)
static CGUITTFont * create (IGUIEnvironment *env, const io::path &filename, const u32 size, const bool antialias=true, const bool transparency=true)
static CGUITTFont * create (IrrlichtDevice *device, const io::path &filename, const u32 size, const bool antialias=true, const bool transparency=true)
Protected Attributes
bool use_monochrome
bool use_transparency
bool use_hinting
bool use_auto_hinting
u32 size
u32 batch_load_size
core::dimension2du max_page_texture_size
Private Member Functions
CGUITTFont (IGUIEnvironment *env)
Constructor.
bool load (const io::path &filename, const u32 size, const bool antialias, const bool transparency)
void reset_images ()
void update_glyph_pages () const
void update_load_flags ()
u32 getWidthFromCharacter (wchar_t c) const
u32 getWidthFromCharacter (uchar32_t c) const
u32 getHeightFromCharacter (wchar_t c) const
u32 getHeightFromCharacter (uchar32_t c) const
u32 getGlyphIndexByChar (wchar_t c) const
u32 getGlyphIndexByChar (uchar32_t c) const
core::vector2di getKerning (const wchar_t thisLetter, const wchar_t previousLetter) const
core::vector2di getKerning (const uchar32_t thisLetter, const uchar32_t previousLetter) const
core::dimension2d< u32 > getDimensionUntilEndOfLine (const wchar_t *p) const
void createSharedPlane ()
Private Attributes
irr::IrrlichtDevice * Device
gui::IGUIEnvironment * Environment
video::IVideoDriver * Driver
io::path filename
FT_Face tt_face
FT_Size_Metrics font_metrics
FT_Int32 load_flags
core::array< CGUITTGlyphPage * > Glyph_Pages
core::array< SGUITTGlyph > Glyphs
s32 GlobalKerningWidth
s32 GlobalKerningHeight
core::ustring Invisible
u32 shadow_offset
u32 shadow_alpha
gui::IGUIFont * fallback
Static Private Attributes
static FT_Library c_library
static std::map< io::path, SGUITTFace * > c_faces
static bool c_libraryLoaded = false
static scene::IMesh * shared_plane_ptr_ = 0
static scene::SMesh shared_plane_
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Class representing a TrueType font.
Definition at line 221 of file CGUITTFont.h.
Member Function Documentation
addTextSceneNode()
core::array< scene::ISceneNode * > irr::gui::CGUITTFont::addTextSceneNode (const wchar_t * text, scene::ISceneManager * smgr, scene::ISceneNode * parent = 0, const video::SColor & color = video::SColor(255, 0, 0, 0), bool center = false) virtual
Add a list of scene nodes generated by putting font textures on the 3D planes.
NOTICE: Because we are considering adding texts into 3D world, all Y axis vectors are inverted.
Definition at line 1088 of file CGUITTFont.cpp.
References irr::scene::ISceneManager::addEmptySceneNode(), irr::scene::ISceneManager::addMeshSceneNode(), irr::scene::IMeshManipulator::createMeshCopy(), irr::IReferenceCounted::drop(), irr::video::ECM_NONE, irr::video::EMF_LIGHTING, irr::video::EMF_NORMALIZE_NORMALS, irr::video::EMF_ZWRITE_ENABLE, irr::video::EMT_SOLID, irr::video::EMT_TRANSPARENT_ALPHA_CHANNEL, getDimension(), irr::core::rect< T >::getHeight(), irr::scene::ISceneManager::getMeshManipulator(), irr::scene::ISceneManager::getRootSceneNode(), irr::core::rect< T >::getWidth(), irr::gui::SGUITTGlyph::glyph_page, irr::gui::SGUITTGlyph::offset, irr::gui::SGUITTGlyph::source_rect, irr::core::rect< T >::UpperLeftCorner, irr::core::vector2d< T >::X, irr::core::vector3d< T >::X, and irr::core::vector2d< T >::Y.
createGlyphPage()
CGUITTGlyphPage * irr::gui::CGUITTFont::createGlyphPage (const u8 & pixel_mode)
Create a new glyph page texture.
Parameters
pixel_mode the pixel mode defined by FT_Pixel_Mode
Definition at line 474 of file CGUITTFont.cpp.
References irr::gui::CGUITTGlyphPage::createPageTexture(), irr::video::IVideoDriver::getMaxTextureSize(), irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
Referenced by irr::gui::SGUITTGlyph::preload().
createTextureFromChar()
video::IImage * irr::gui::CGUITTFont::createTextureFromChar (const uchar32_t & ch) virtual
Create corresponding character's software image copy from the font, so you can use this data just like any ordinary video::IImage.
Parameters
ch The character you need
Definition at line 1012 of file CGUITTFont.cpp.
References irr::video::IImage::copyTo(), irr::video::IVideoDriver::createImage(), irr::video::IVideoDriver::createImageFromData(), irr::video::ETLM_READ_ONLY, irr::video::ITexture::getColorFormat(), irr::video::ITexture::getOriginalSize(), irr::core::rect< T >::getSize(), irr::gui::SGUITTGlyph::glyph_page, irr::video::ITexture::lock(), irr::gui::SGUITTGlyph::source_rect, irr::video::ITexture::unlock(), and irr::gui::CGUITTGlyphPage::updateTexture().
createTTFont()
CGUITTFont * irr::gui::CGUITTFont::createTTFont (IGUIEnvironment * env, const io::path & filename, const u32 size, const bool antialias = true, const bool transparency = true, const u32 shadow = 0, const u32 shadow_alpha = 255) static
Creates a new TrueType font and returns a pointer to it. The pointer must be drop()'ed when finished.
Parameters
env The IGUIEnvironment the font loads out of.
filename The filename of the font.
size The size of the font glyphs in pixels. Since this is the size of the individual glyphs, the true height of the font may change depending on the characters used.
antialias set the use_monochrome (opposite to antialias) flag
transparency set the use_transparency flag
Returns
Returns a pointer to a CGUITTFont. Will return 0 if the font failed to load.
Definition at line 219 of file CGUITTFont.cpp.
References CGUITTFont(), and irr::IReferenceCounted::drop().
getLastGlyphPage()
CGUITTGlyphPage * irr::gui::CGUITTFont::getLastGlyphPage () const
Get the last glyph page if there's still available slots. If not, it will return zero.
Definition at line 460 of file CGUITTFont.cpp.
References getLastGlyphPageIndex().
Referenced by irr::gui::SGUITTGlyph::preload().
getPageTextureByIndex()
video::ITexture * irr::gui::CGUITTFont::getPageTextureByIndex (const u32 & page_index) const virtual
This function is for debugging mostly. If the page doesn't exist it returns zero.
Parameters
page_index Simply return the texture handle of a given page index.
Definition at line 1042 of file CGUITTFont.cpp.
setFontHinting()
void irr::gui::CGUITTFont::setFontHinting (const bool enable, const bool enable_auto_hinting = true) virtual
Enables or disables font hinting. Default: Hinting and auto-hinting true.
Parameters
enable If false, font hinting is turned off. If true, font hinting is turned on.
enable_auto_hinting If true, FreeType uses its own auto-hinting algorithm. If false, it tries to use the algorithm specified by the font.
Definition at line 537 of file CGUITTFont.cpp.
setMonochrome()
void irr::gui::CGUITTFont::setMonochrome (const bool flag) virtual
Tells the font to use monochrome rendering. Default: false.
Parameters
flag If true, the font draws using a monochrome image. If false, the font uses a grayscale image.
Definition at line 531 of file CGUITTFont.cpp.
setTransparency()
void irr::gui::CGUITTFont::setTransparency (const bool flag) virtual
Tells the font to allow transparency when rendering. Default: true.
Parameters
flag If true, the font draws using transparency.
Definition at line 525 of file CGUITTFont.cpp.
useAutoHinting()
virtual bool irr::gui::CGUITTFont::useAutoHinting () const inline virtual
Check if the font auto-hinting is enabled. Auto-hinting is FreeType's built-in font hinting engine.
Definition at line 253 of file CGUITTFont.h.
useMonochrome()
virtual bool irr::gui::CGUITTFont::useMonochrome () const inline virtual
Check if the font is being loaded as a monochrome font. The font can either be a 256 color grayscale font, or a 2 color monochrome font.
Definition at line 260 of file CGUITTFont.h.
The documentation for this class was generated from the following files:
src/irrlicht_changes/CGUITTFont.h
src/irrlicht_changes/CGUITTFont.cpp