Three Cubes Game: irr::video::SColor Class Reference
irr::video::SColor Class Reference
Class representing a 32 bit ARGB color.
#include <SColor.h>
Public Member Functions
SColor ()
Constructor of the Color. Does nothing.
SColor (u32 a, u32 r, u32 g, u32 b)
Constructs the color from 4 values representing the alpha, red, green and blue component.
SColor (u32 clr)
Constructs the color from a 32 bit value. Could be another color.
u32 getAlpha () const
Returns the alpha component of the color.
u32 getRed () const
Returns the red component of the color.
u32 getGreen () const
Returns the green component of the color.
u32 getBlue () const
Returns the blue component of the color.
f32 getLightness () const
Get lightness of the color in the range [0,255].
f32 getLuminance () const
Get luminance of the color in the range [0,255].
u32 getAverage () const
Get average intensity of the color in the range [0,255].
void setAlpha (u32 a)
Sets the alpha component of the Color.
void setRed (u32 r)
Sets the red component of the Color.
void setGreen (u32 g)
Sets the green component of the Color.
void setBlue (u32 b)
Sets the blue component of the Color.
u16 toA1R5G5B5 () const
Calculates a 16 bit A1R5G5B5 value of this color.
void toOpenGLColor (u8 *dest) const
Converts color to OpenGL color format.
void set (u32 a, u32 r, u32 g, u32 b)
Sets all four components of the color at once.
void set (u32 col)
bool operator== (const SColor &other) const
Compares the color to another color.
bool operator!= (const SColor &other) const
Compares the color to another color.
bool operator< (const SColor &other) const
comparison operator
SColor operator+ (const SColor &other) const
Adds two colors, result is clamped to 0..255 values.
SColor getInterpolated (const SColor &other, f32 d) const
Interpolates the color with a f32 value to another color.
SColor getInterpolated_quadratic (const SColor &c1, const SColor &c2, f32 d) const
Returns interpolated color. (quadratic)
void setData (const void *data, ECOLOR_FORMAT format)
set the color by expecting data in the given format
void getData (void *data, ECOLOR_FORMAT format) const
Write the color to data in the defined format.
Public Attributes
u32 color
color in A8R8G8B8 Format
Detailed Description
Class representing a 32 bit ARGB color.
The color values for alpha, red, green, and blue are stored in a single u32. So all four values may be between 0 and 255. Alpha in Irrlicht is opacity, so 0 is fully transparent, 255 is fully opaque (solid). This class is used by most parts of the Irrlicht Engine to specify a color. Another way is using the class SColorf, which stores the color values in 4 floats. This class must consist of only one u32 and must not use virtual functions.
Definition at line 316 of file SColor.h.
Constructor & Destructor Documentation
SColor() [1/2]
irr::video::SColor::SColor () inline
Constructor of the Color. Does nothing.
The color value is not initialized to save time.
Definition at line 322 of file SColor.h.
Referenced by getInterpolated(), getInterpolated_quadratic(), and operator+().
SColor() [2/2]
irr::video::SColor::SColor (u32 a, u32 r, u32 g, u32 b) inline
Constructs the color from 4 values representing the alpha, red, green and blue component.
Must be values between 0 and 255.
Definition at line 326 of file SColor.h.
Member Function Documentation
getAlpha()
u32 irr::video::SColor::getAlpha () const inline
Returns the alpha component of the color.
The alpha component defines how opaque a color is.
Returns
The alpha value of the color. 0 is fully transparent, 255 is fully opaque.
Definition at line 336 of file SColor.h.
References color.
Referenced by irr::video::COpenGL3DriverBase::clearBuffers(), GUITable::draw(), irr::video::COpenGL3DriverBase::draw2DImageBatch(), irr::video::COpenGL3DriverBase::draw2DLine(), irr::video::COpenGL3DriverBase::draw2DRectangle(), irr::gui::CGUISkin::draw3DWindowBackground(), irr::gui::GUISkin::drawColored3DWindowBackground(), irr::video::COpenGL3DriverBase::drawPixel(), getInterpolated(), getInterpolated_quadratic(), irr::video::CImage::getPixelBox(), operator+(), irr::video::SColorf::SColorf(), and toOpenGLColor().
getBlue()
u32 irr::video::SColor::getBlue () const inline
Returns the blue component of the color.
Returns
Value between 0 and 255, specifying how blue the color is. 0 means no blue, 255 means full blue.
Definition at line 351 of file SColor.h.
References color.
Referenced by irr::video::COpenGL3DriverBase::clearBuffers(), getAverage(), getData(), getInterpolated(), getInterpolated_quadratic(), getLightness(), getLuminance(), irr::video::CImage::getPixelBox(), operator+(), Sky::render(), irr::video::SColorf::SColorf(), irr::video::CImage::setPixel(), irr::setShading(), toOpenGLColor(), and Game::updatePointedThing().
getData()
void irr::video::SColor::getData (void * data, ECOLOR_FORMAT format) const inline
Write the color to data in the defined format.
Parameters
data target to write the color. Must contain sufficiently large memory to receive the number of bytes neede for format
format tells the format used to write the color into data
Definition at line 522 of file SColor.h.
References irr::video::A8R8G8B8toA1R5G5B5(), irr::video::A8R8G8B8toR5G6B5(), color, irr::video::ECF_A1R5G5B5, irr::video::ECF_A8R8G8B8, irr::video::ECF_R5G6B5, irr::video::ECF_R8G8B8, getBlue(), getGreen(), and getRed().
getGreen()
u32 irr::video::SColor::getGreen () const inline
Returns the green component of the color.
Returns
Value between 0 and 255, specifying how green the color is. 0 means no green, 255 means full green.
Definition at line 346 of file SColor.h.
References color.
Referenced by irr::video::COpenGL3DriverBase::clearBuffers(), getAverage(), getData(), getInterpolated(), getInterpolated_quadratic(), getLightness(), getLuminance(), irr::video::CImage::getPixelBox(), operator+(), Sky::render(), irr::video::SColorf::SColorf(), irr::video::CImage::setPixel(), irr::setShading(), toOpenGLColor(), and Game::updatePointedThing().
getInterpolated()
SColor irr::video::SColor::getInterpolated (const SColor & other, f32 d) const inline
Interpolates the color with a f32 value to another color.
Parameters
other Other color
d value between 0.0f and 1.0f. d=0 returns other, d=1 returns this, values between interpolate.
Returns
Interpolated color.
Definition at line 455 of file SColor.h.
References irr::core::clamp(), getAlpha(), getBlue(), getGreen(), getRed(), and SColor().
Referenced by irr::gui::CGUISkin::draw3DButtonPanePressed(), irr::gui::CGUISkin::draw3DButtonPaneStandard(), irr::gui::CGUISkin::draw3DWindowBackground(), irr::gui::GUISkin::drawColored3DButtonPanePressed(), irr::gui::GUISkin::drawColored3DButtonPaneStandard(), and irr::gui::GUISkin::drawColored3DWindowBackground().
getInterpolated_quadratic()
SColor irr::video::SColor::getInterpolated_quadratic (const SColor & c1, const SColor & c2, f32 d) const inline
Returns interpolated color. (quadratic)
Parameters
c1 first color to interpolate with
c2 second color to interpolate with
d value between 0.0f and 1.0f.
Definition at line 469 of file SColor.h.
References irr::core::clamp(), getAlpha(), getBlue(), getGreen(), getRed(), and SColor().
getRed()
u32 irr::video::SColor::getRed () const inline
Returns the red component of the color.
Returns
Value between 0 and 255, specifying how red the color is. 0 means no red, 255 means full red.
Definition at line 341 of file SColor.h.
References color.
Referenced by irr::video::COpenGL3DriverBase::clearBuffers(), getAverage(), getData(), getInterpolated(), getInterpolated_quadratic(), getLightness(), getLuminance(), irr::video::CImage::getPixelBox(), operator+(), Sky::render(), irr::video::SColorf::SColorf(), irr::video::CImage::setPixel(), irr::setShading(), toOpenGLColor(), and Game::updatePointedThing().
operator!=()
bool irr::video::SColor::operator!= (const SColor & other) const inline
Compares the color to another color.
Returns
True if the colors are different, and false if they are the same.
Definition at line 434 of file SColor.h.
References color.
operator+()
SColor irr::video::SColor::operator+ (const SColor & other) const inline
Adds two colors, result is clamped to 0..255 values.
Parameters
other Color to add to this color
Returns
Addition of the two colors, clamped to 0..255 values
Definition at line 443 of file SColor.h.
References getAlpha(), getBlue(), getGreen(), getRed(), irr::core::min_(), and SColor().
operator<()
bool irr::video::SColor::operator< (const SColor & other) const inline
comparison operator
Returns
True if this color is smaller than the other one
Definition at line 438 of file SColor.h.
References color.
operator==()
bool irr::video::SColor::operator== (const SColor & other) const inline
Compares the color to another color.
Returns
True if the colors are the same, and false if not.
Definition at line 430 of file SColor.h.
References color.
set()
void irr::video::SColor::set (u32 a, u32 r, u32 g, u32 b) inline
Sets all four components of the color at once.
Constructs the color from 4 values representing the alpha, red, green and blue components of the color. Must be values between 0 and 255.
Parameters
a Alpha component of the color. The alpha component defines how transparent a color should be. Has to be a value between 0 and 255. 255 means not transparent (opaque), 0 means fully transparent.
r Sets the red component of the Color. Has to be a value between 0 and 255. 0 means no red, 255 means full red.
g Sets the green component of the Color. Has to be a value between 0 and 255. 0 means no green, 255 means full green.
b Sets the blue component of the Color. Has to be a value between 0 and 255. 0 means no blue, 255 means full blue.
Definition at line 422 of file SColor.h.
References color.
Referenced by irr::video::CImage::getPixelBox(), Clouds::render(), and setData().
setAlpha()
void irr::video::SColor::setAlpha (u32 a) inline
Sets the alpha component of the Color.
The alpha component defines how transparent a color should be.
Parameters
a The alpha value of the color. 0 is fully transparent, 255 is fully opaque.
Definition at line 374 of file SColor.h.
References color.
setBlue()
void irr::video::SColor::setBlue (u32 b) inline
Sets the blue component of the Color.
Parameters
b Has to be a value between 0 and 255. 0 means no blue, 255 means full blue.
Definition at line 389 of file SColor.h.
References color.
Referenced by irr::scene::COBJMeshFileLoader::readColor(), irr::setShading(), and Game::updatePointedThing().
setData()
void irr::video::SColor::setData (const void * data, ECOLOR_FORMAT format) inline
set the color by expecting data in the given format
Parameters
data must point to valid memory containing color information in the given format
format tells the format in which data is available
Definition at line 493 of file SColor.h.
References irr::video::A1R5G5B5toA8R8G8B8(), color, irr::video::ECF_A1R5G5B5, irr::video::ECF_A8R8G8B8, irr::video::ECF_R5G6B5, irr::video::ECF_R8G8B8, irr::video::R5G6B5toA8R8G8B8(), and set().
setGreen()
void irr::video::SColor::setGreen (u32 g) inline
Sets the green component of the Color.
Parameters
g Has to be a value between 0 and 255. 0 means no green, 255 means full green.
Definition at line 384 of file SColor.h.
References color.
Referenced by irr::scene::COBJMeshFileLoader::readColor(), irr::setShading(), and Game::updatePointedThing().
setRed()
void irr::video::SColor::setRed (u32 r) inline
Sets the red component of the Color.
Parameters
r Has to be a value between 0 and 255. 0 means no red, 255 means full red.
Definition at line 379 of file SColor.h.
References color.
Referenced by irr::scene::COBJMeshFileLoader::readColor(), irr::setShading(), and Game::updatePointedThing().
toA1R5G5B5()
u16 irr::video::SColor::toA1R5G5B5 () const inline
Calculates a 16 bit A1R5G5B5 value of this color.
Returns
16 bit A1R5G5B5 value of this color.
Definition at line 393 of file SColor.h.
References irr::video::A8R8G8B8toA1R5G5B5(), and color.
Referenced by irr::video::CImage::fill(), and irr::video::CNullDriver::makeColorKeyTexture().
toOpenGLColor()
void irr::video::SColor::toOpenGLColor (u8 * dest) const inline
Converts color to OpenGL color format.
From ARGB to RGBA in 4 byte components for endian aware passing to OpenGL
Parameters
dest address where the 4x8 bit OpenGL color is stored.
Definition at line 399 of file SColor.h.
References getAlpha(), getBlue(), getGreen(), and getRed().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/SColor.h