Three Cubes Game: irr::core::ustring16::_ustring16_const_iterator Class Reference
irr::core::ustring16::_ustring16_const_iterator Class Reference
Iterator to iterate through a UTF-16 string.
#include <irrUString.h>
Public Types
typedef _ustring16_const_iterator _Iter
typedef std::iterator< std::bidirectional_iterator_tag, access, ptrdiff_t, const access, const access > _Base
typedef _Base::value_type value_type
typedef _Base::difference_type difference_type
typedef _Base::difference_type distance_type
typedef _Base::pointer pointer
typedef const_reference reference
Public Member Functions
_ustring16_const_iterator (const _Iter &i)
Constructors.
_ustring16_const_iterator (const ustring16 &s)
_ustring16_const_iterator (const ustring16 &s, const u32 p)
bool operator== (const _Iter &iter) const
Test for equalness.
bool operator!= (const _Iter &iter) const
Test for unequalness.
_Iter & operator++ ()
Switch to the next full character in the string.
_Iter operator++ (int)
Switch to the next full character in the string, returning the previous position.
_Iter & operator-- ()
Switch to the previous full character in the string.
_Iter operator-- (int)
Switch to the previous full character in the string, returning the previous position.
_Iter & operator+= (const difference_type v)
_Iter & operator-= (const difference_type v)
_Iter operator+ (const difference_type v) const
Return a new iterator that is a variable number of full characters forward from the current position.
_Iter operator- (const difference_type v) const
Return a new iterator that is a variable number of full characters backward from the current position.
difference_type operator- (const _Iter &iter) const
Returns the distance between two iterators.
const_reference operator* () const
Accesses the full character at the iterator's position.
reference operator* ()
Accesses the full character at the iterator's position.
const_pointer operator-> () const
Accesses the full character at the iterator's position.
pointer operator-> ()
Accesses the full character at the iterator's position.
bool atStart () const
Is the iterator at the start of the string?
bool atEnd () const
Is the iterator at the end of the string?
void toStart ()
Moves the iterator to the start of the string.
void toEnd ()
Moves the iterator to the end of the string.
u32 getPos () const
Public Attributes
const typedef access const_pointer
const typedef access const_reference
Protected Attributes
const ustring16 * ref
u32 pos
Detailed Description
Iterator to iterate through a UTF-16 string.
Definition at line 432 of file irrUString.h.
Member Function Documentation
getPos()
u32 irr::core::ustring16::_ustring16_const_iterator::getPos () const inline
Returns the iterator's position.
Returns
The iterator's position.
Definition at line 700 of file irrUString.h.
Referenced by irr::core::ustring16::erase(), irr::core::ustring16::insert(), and irr::core::ustring16::split().
operator+=()
_Iter& irr::core::ustring16::_ustring16_const_iterator::operator+= (const difference_type v) inline
Advance a specified number of full characters in the string.
Returns
Myself.
Definition at line 530 of file irrUString.h.
References irr::core::ustring16::c_str(), operator-=(), and irr::core::ustring16::size_raw().
Referenced by operator-=().
operator-=()
_Iter& irr::core::ustring16::_ustring16_const_iterator::operator-= (const difference_type v) inline
Go back a specified number of full characters in the string.
Returns
Myself.
Definition at line 558 of file irrUString.h.
References irr::core::ustring16::c_str(), and operator+=().
Referenced by operator+=().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/irrUString.h