Three Cubes Game: irr::scene::CXMeshFileLoader Class Reference
irr::scene::CXMeshFileLoader Class Reference
Meshloader capable of loading x meshes.
#include <CXMeshFileLoader.h>
Classes
struct SXMesh
Public Member Functions
CXMeshFileLoader (scene::ISceneManager *smgr)
Constructor.
bool isALoadableFileExtension (const io::path &filename) const override
IAnimatedMesh * createMesh (io::IReadFile *file) override
Public Member Functions inherited from irr::scene::IMeshLoader
IMeshLoader ()
Constructor.
virtual ~IMeshLoader ()
Destructor.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Member Functions
bool load (io::IReadFile *file)
bool readFileIntoMemory (io::IReadFile *file)
Reads file into memory.
bool parseFile ()
Parses the file.
bool parseDataObject ()
Parses the next Data object in the file.
bool parseDataObjectTemplate ()
bool parseDataObjectFrame (CSkinnedMesh::SJoint *parent)
bool parseDataObjectTransformationMatrix (core::matrix4 &mat)
bool parseDataObjectMesh (SXMesh &mesh)
bool parseDataObjectSkinWeights (SXMesh &mesh)
bool parseDataObjectSkinMeshHeader (SXMesh &mesh)
bool parseDataObjectMeshNormals (SXMesh &mesh)
bool parseDataObjectMeshTextureCoords (SXMesh &mesh)
bool parseDataObjectMeshVertexColors (SXMesh &mesh)
bool parseDataObjectMeshMaterialList (SXMesh &mesh)
bool parseDataObjectAnimationSet ()
bool parseDataObjectAnimationTicksPerSecond ()
bool parseDataObjectAnimation ()
bool parseDataObjectAnimationKey (ISkinnedMesh::SJoint *joint)
bool parseDataObjectTextureFilename (core::stringc &texturename)
bool parseUnknownDataObject ()
void findNextNoneWhiteSpace ()
places pointer to next begin of a token, and ignores comments
void findNextNoneWhiteSpaceNumber ()
places pointer to next begin of a token, which must be a number,
core::stringc getNextToken ()
returns next parseable token. Returns empty string if no token there
bool readHeadOfDataObject (core::stringc *outname=0)
bool checkForClosingBrace ()
checks for closing curly brace, returns false if not there
bool checkForOneFollowingSemicolons ()
checks for one following semicolons, returns false if not there
bool checkForTwoFollowingSemicolons ()
checks for two following semicolons, returns false if they are not there
bool getNextTokenAsString (core::stringc &out)
reads a x file style string
void readUntilEndOfLine ()
u16 readBinWord ()
u32 readBinDWord ()
u32 readInt ()
f32 readFloat ()
bool readVector2 (core::vector2df &vec)
bool readVector3 (core::vector3df &vec)
bool readMatrix (core::matrix4 &mat)
bool readRGB (video::SColor &color)
bool readRGBA (video::SColor &color)
Private Attributes
CSkinnedMesh * AnimatedMesh
c8 * Buffer
const c8 * P
c8 * End
u32 BinaryNumCount
u32 Line
io::path FilePath
CSkinnedMesh::SJoint * CurFrame
core::array< SXMesh * > Meshes
u32 MajorVersion
u32 MinorVersion
bool BinaryFormat
c8 FloatSize
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Meshloader capable of loading x meshes.
Definition at line 24 of file CXMeshFileLoader.h.
Member Function Documentation
checkForOneFollowingSemicolons()
bool irr::scene::CXMeshFileLoader::checkForOneFollowingSemicolons () private
checks for one following semicolons, returns false if not there
checks for one following semicolon, returns false if not there
Definition at line 1933 of file CXMeshFileLoader.cpp.
References getNextToken().
createMesh()
IAnimatedMesh * irr::scene::CXMeshFileLoader::createMesh (io::IReadFile * file) override virtual
creates/loads an animated mesh from the file.
Returns
Pointer to the created mesh. Returns 0 if loading failed. If you no longer need the mesh, you should call IAnimatedMesh::drop(). See IReferenceCounted::drop() for more information.
Implements irr::scene::IMeshLoader.
Definition at line 48 of file CXMeshFileLoader.cpp.
References irr::core::string< T >::c_str(), irr::IReferenceCounted::drop(), irr::scene::CSkinnedMesh::finalize(), and irr::os::Timer::getRealTime().
isALoadableFileExtension()
bool irr::scene::CXMeshFileLoader::isALoadableFileExtension (const io::path & filename) const override virtual
returns true if the file maybe is able to be loaded by this class based on the file extension (e.g. ".cob")
returns true if the file maybe is able to be loaded by this class based on the file extension (e.g. ".bsp")
Implements irr::scene::IMeshLoader.
Definition at line 38 of file CXMeshFileLoader.cpp.
References irr::core::hasFileExtension().
readFileIntoMemory()
bool irr::scene::CXMeshFileLoader::readFileIntoMemory (io::IReadFile * file) private
Reads file into memory.
read all into memory
check header "xof "
read minor and major version, e.g. 0302 or 0303
read format
read float size
Definition at line 390 of file CXMeshFileLoader.cpp.
References irr::ELL_WARNING, and irr::core::strtoul10().
readHeadOfDataObject()
bool irr::scene::CXMeshFileLoader::readHeadOfDataObject (core::stringc * outname = 0) private
reads header of dataobject including the opening brace. returns false if error happened, and writes name of object if there is one
Definition at line 1970 of file CXMeshFileLoader.cpp.
References getNextToken().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CXMeshFileLoader.h
lib/irrlichtmt/source/Irrlicht/CXMeshFileLoader.cpp