Three Cubes Game: GUIButton Class Reference
GUIButton Class Reference
Classes
struct ButtonImage
struct ButtonSprite
Public Member Functions
GUIButton (gui::IGUIEnvironment *environment, gui::IGUIElement *parent, s32 id, core::rect< s32 > rectangle, ISimpleTextureSource *tsrc, bool noclip=false)
constructor
virtual ~GUIButton ()
destructor
virtual bool OnEvent (const SEvent &event) override
called if an event happened.
virtual void draw () override
draws the element and its children
virtual void setOverrideFont (gui::IGUIFont *font=0) override
sets another skin independent font. if this is set to zero, the button uses the font of the skin.
virtual gui::IGUIFont * getOverrideFont () const override
Gets the override font (if any)
virtual gui::IGUIFont * getActiveFont () const override
Get the font which is used right now for drawing.
virtual void setOverrideColor (video::SColor color) override
Sets another color for the button text.
virtual video::SColor getOverrideColor () const override
Gets the override color.
virtual video::SColor getActiveColor () const override
Gets the currently used text color.
virtual void enableOverrideColor (bool enable) override
Sets if the button text should use the override color or the color in the gui skin.
virtual bool isOverrideColorEnabled (void) const override
Checks if an override color is enabled.
virtual void setImage (gui::EGUI_BUTTON_IMAGE_STATE state, video::ITexture *image=nullptr, const core::rect< s32 > &sourceRect=core::rect< s32 >(0, 0, 0, 0)) override
Sets an image which should be displayed on the button when it is in the given state.
virtual void setImage (video::ITexture *image=nullptr) override
Sets an image which should be displayed on the button when it is in normal state.
virtual void setImage (video::ITexture *image, const core::rect< s32 > &pos) override
Sets an image which should be displayed on the button when it is in normal state.
virtual void setPressedImage (video::ITexture *image=nullptr) override
Sets an image which should be displayed on the button when it is in pressed state.
virtual void setPressedImage (video::ITexture *image, const core::rect< s32 > &pos) override
Sets an image which should be displayed on the button when it is in pressed state.
virtual void setText (const wchar_t *text) override
Sets the text displayed by the button.
virtual void setSpriteBank (gui::IGUISpriteBank *bank=0) override
Sets the sprite bank used by the button.
virtual void setSprite (gui::EGUI_BUTTON_STATE state, s32 index, video::SColor color=video::SColor(255, 255, 255, 255), bool loop=false, bool scale=false) override
Sets the animated sprite for a specific button state.
virtual s32 getSpriteIndex (gui::EGUI_BUTTON_STATE state) const override
Get the sprite-index for the given state or -1 when no sprite is set.
virtual video::SColor getSpriteColor (gui::EGUI_BUTTON_STATE state) const override
Get the sprite color for the given state. Color is only used when a sprite is set.
virtual bool getSpriteLoop (gui::EGUI_BUTTON_STATE state) const override
Returns if the sprite in the given state does loop.
virtual bool getSpriteScale (gui::EGUI_BUTTON_STATE state) const override
Returns if the sprite in the given state is scaled.
virtual void setIsPushButton (bool isPushButton=true) override
virtual bool isPushButton () const override
Checks whether the button is a push button.
virtual void setPressed (bool pressed=true) override
Sets the pressed state of the button if this is a pushbutton.
virtual bool isPressed () const override
Returns if the button is currently pressed.
bool isHovered () const
Returns if this element (or one of its direct children) is hovered.
bool isFocused () const
Returns if this element (or one of its direct children) is focused.
virtual void setDrawBorder (bool border=true) override
Sets if the button should use the skin to draw its border.
virtual bool isDrawingBorder () const override
Checks if the button face and border are being drawn.
virtual void setUseAlphaChannel (bool useAlphaChannel=true) override
Sets if the alpha channel should be used for drawing images on the button (default is false)
virtual bool isAlphaChannelUsed () const override
Checks if the alpha channel should be used for drawing images on the button.
virtual void setScaleImage (bool scaleImage=true) override
Sets if the button should scale the button images to fit.
virtual bool isScalingImage () const override
Checks whether the button scales the used images.
virtual bool getClickShiftState () const override
Get if the shift key was pressed in last EGET_BUTTON_CLICKED event.
virtual bool getClickControlState () const override
Get if the control key was pressed in last EGET_BUTTON_CLICKED event.
void setColor (video::SColor color)
void setFromState ()
Set element properties from a StyleSpec corresponding to the button state.
virtual void setFromStyle (const StyleSpec &style)
Set element properties from a StyleSpec.
void setStyles (const std::array< StyleSpec, StyleSpec::NUM_STATES > &styles)
Set the styles used for each state.
Public Member Functions inherited from irr::gui::IGUIButton
IGUIButton (IGUIEnvironment *environment, IGUIElement *parent, s32 id, core::rect< s32 > rectangle)
constructor
virtual void setImage (EGUI_BUTTON_IMAGE_STATE state, video::ITexture *image=0, const core::rect< s32 > &sourceRect=core::rect< s32 >(0, 0, 0, 0))=0
Sets an image which should be displayed on the button when it is in the given state.
virtual void setImage (video::ITexture *image, const core::rect< s32 > &sourceRect)=0
Sets a background image for the button when it is in normal state.
virtual void setPressedImage (video::ITexture *image, const core::rect< s32 > &sourceRect)=0
Sets an image which should be displayed on the button when it is in pressed state.
virtual void setSprite (EGUI_BUTTON_STATE state, s32 index, video::SColor color=video::SColor(255, 255, 255, 255), bool loop=false, bool scale=false)=0
Sets the animated sprite for a specific button state.
Public Member Functions inherited from irr::gui::IGUIElement
IGUIElement (EGUI_ELEMENT_TYPE type, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle)
Constructor.
virtual ~IGUIElement ()
Destructor.
IGUIElement * getParent () const
Returns parent of this element.
core::rect< s32 > getRelativePosition () const
Returns the relative rectangle of this element.
void setRelativePosition (const core::rect< s32 > &r)
Sets the relative rectangle of this element.
void setRelativePosition (const core::position2di &position)
Sets the relative rectangle of this element, maintaining its current width and height.
void setRelativePositionProportional (const core::rect< f32 > &r)
Sets the relative rectangle of this element as a proportion of its parent's area.
core::rect< s32 > getAbsolutePosition () const
Gets the absolute rectangle of this element.
core::rect< s32 > getAbsoluteClippingRect () const
Returns the visible area of the element.
void setNotClipped (bool noClip)
Sets whether the element will ignore its parent's clipping rectangle.
bool isNotClipped () const
Gets whether the element will ignore its parent's clipping rectangle.
void setMaxSize (core::dimension2du size)
Sets the maximum size allowed for this element.
void setMinSize (core::dimension2du size)
Sets the minimum size allowed for this element.
void setAlignment (EGUI_ALIGNMENT left, EGUI_ALIGNMENT right, EGUI_ALIGNMENT top, EGUI_ALIGNMENT bottom)
The alignment defines how the borders of this element will be positioned when the parent element is resized.
EGUI_ALIGNMENT getAlignLeft () const
How left element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignRight () const
How right element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignTop () const
How top element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignBottom () const
How bottom element border is aligned when parent is resized.
virtual void updateAbsolutePosition ()
Updates the absolute position.
virtual IGUIElement * getElementFromPoint (const core::position2d< s32 > &point)
Returns the topmost GUI element at the specific position.
virtual bool isPointInside (const core::position2d< s32 > &point) const
Returns true if a point is within this element.
virtual void addChild (IGUIElement *child)
Adds a GUI element as new child of this element.
virtual void removeChild (IGUIElement *child)
Removes a child.
virtual void removeAllChildren ()
Removes all children.
virtual void remove ()
Removes this element from its parent.
virtual void OnPostRender (u32 timeMs)
animate the element and its children.
virtual void move (core::position2d< s32 > absoluteMovement)
Moves this element.
virtual bool isVisible () const
Returns true if element is visible.
virtual bool isTrulyVisible () const
Check whether the element is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool visible)
Sets the visible state of this element.
virtual bool isSubElement () const
Returns true if this element was created as part of its parent control.
virtual void setSubElement (bool subElement)
Sets whether this control was created as part of its parent.
void setTabStop (bool enable)
If set to true, the focus will visit this element when using the tab key to cycle through elements.
bool isTabStop () const
Returns true if this element can be focused by navigating with the tab key.
void setTabOrder (s32 index)
Sets the priority of focus when using the tab key to navigate between a group of elements.
s32 getTabOrder () const
Returns the number in the tab order sequence.
void setTabGroup (bool isGroup)
Sets whether this element is a container for a group of elements which can be navigated using the tab key.
bool isTabGroup () const
Returns true if this element is a tab group.
IGUIElement * getTabGroup ()
Returns the container element which holds all elements in this element's tab group.
virtual bool isEnabled () const
Returns true if element is enabled.
virtual void setEnabled (bool enabled)
Sets the enabled state of this element.
virtual const wchar_t * getText () const
Returns caption of this element.
virtual void setToolTipText (const wchar_t *text)
Sets the new caption of this element.
virtual const core::stringw & getToolTipText () const
Returns caption of this element.
virtual s32 getID () const
Returns id. Can be used to identify the element.
virtual void setID (s32 id)
Sets the id of this element.
virtual bool bringToFront (IGUIElement *child)
Brings a child to front.
virtual bool sendToBack (IGUIElement *child)
Moves a child to the back, so it's siblings are drawn on top of it.
virtual const std::list< IGUIElement * > & getChildren () const
Returns list with children of this element.
virtual IGUIElement * getElementFromId (s32 id, bool searchchildren=false) const
Finds the first element with the given id.
bool isMyChild (IGUIElement *child) const
bool getNextElement (s32 startOrder, bool reverse, bool group, IGUIElement *&first, IGUIElement *&closest, bool includeInvisible=false, bool includeDisabled=false) const
searches elements to find the closest next element to tab to
EGUI_ELEMENT_TYPE getType () const
Returns the type of the gui element.
virtual bool hasType (EGUI_ELEMENT_TYPE type) const
Returns true if the gui element supports the given type.
virtual const c8 * getTypeName () const
Returns the type name of the gui element.
virtual const c8 * getName () const
Returns the name of the element.
virtual void setName (const c8 *name)
Sets the name of the element.
virtual void setName (const core::stringc &name)
Sets the name of the element.
virtual bool acceptsIME ()
Returns whether the element takes input from the IME.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::IEventReceiver
virtual ~IEventReceiver ()
Destructor.
Static Public Member Functions
static GUIButton * addButton (gui::IGUIEnvironment *environment, const core::rect< s32 > &rectangle, ISimpleTextureSource *tsrc, IGUIElement *parent, s32 id, const wchar_t *text, const wchar_t *tooltiptext=L"")
Do not drop returned handle.
Protected Member Functions
void drawSprite (gui::EGUI_BUTTON_STATE state, u32 startTime, const core::position2di &center)
gui::EGUI_BUTTON_IMAGE_STATE getImageState (bool pressed) const
ISimpleTextureSource * getTextureSource ()
gui::EGUI_BUTTON_IMAGE_STATE getImageState (bool pressed, const ButtonImage *images) const
Protected Member Functions inherited from irr::gui::IGUIElement
void addChildToEnd (IGUIElement *child)
void reorderChildren (std::list< IGUIElement * >::iterator from, std::list< IGUIElement * >::iterator to, const std::vector< IGUIElement * > &neworder)
void recalculateAbsolutePosition (bool recursive)
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Private Attributes
ButtonSprite ButtonSprites [gui::EGBS_COUNT]
gui::IGUISpriteBank * SpriteBank
ButtonImage ButtonImages [gui::EGBIS_COUNT]
std::array< StyleSpec, StyleSpec::NUM_STATES > Styles
gui::IGUIFont * OverrideFont
bool OverrideColorEnabled
video::SColor OverrideColor
u32 ClickTime
u32 HoverTime
u32 FocusTime
bool ClickShiftState
bool ClickControlState
bool IsPushButton
bool Pressed
bool UseAlphaChannel
bool DrawBorder
bool ScaleImage
video::SColor Colors [4]
bool WasHovered = false
bool WasFocused = false
ISimpleTextureSource * TSrc
gui::IGUIStaticText * StaticText
core::rect< s32 > BgMiddle
core::rect< s32 > Padding
core::vector2d< s32 > ContentOffset
video::SColor BgColor
Additional Inherited Members
Static Protected Member Functions inherited from irr::gui::IGUIElement
template<typename Iterator >
static size_t _fastSetChecksum (Iterator begin, Iterator end)
Protected Attributes inherited from irr::gui::IGUIElement
std::list< IGUIElement * > Children
List of all children of this element.
IGUIElement * Parent
Pointer to the parent.
std::list< IGUIElement * >::iterator ParentPos
Our position in the parent list. Only valid when Parent != nullptr.
core::rect< s32 > RelativeRect
relative rect of element
core::rect< s32 > AbsoluteRect
absolute rect of element
core::rect< s32 > AbsoluteClippingRect
absolute clipping rect of element
core::rect< s32 > DesiredRect
core::rect< s32 > LastParentRect
for calculating the difference when resizing parent
core::rect< f32 > ScaleRect
relative scale of the element inside its parent
core::dimension2du MaxSize
maximum and minimum size of the element
core::dimension2du MinSize
bool IsVisible
is visible?
bool IsEnabled
is enabled?
bool IsSubElement
is a part of a larger whole and should not be serialized?
bool NoClip
does this element ignore its parent's clipping rectangle?
core::stringw Text
caption
core::stringw ToolTipText
tooltip
core::stringc Name
users can set this for identifying the element by string
s32 ID
users can set this for identifying the element by integer
bool IsTabStop
tab stop like in windows
s32 TabOrder
tab order
bool IsTabGroup
tab groups are containers like windows, use ctrl+tab to navigate
EGUI_ALIGNMENT AlignLeft
tells the element how to act when its parent is resized
EGUI_ALIGNMENT AlignRight
EGUI_ALIGNMENT AlignTop
EGUI_ALIGNMENT AlignBottom
IGUIEnvironment * Environment
GUI Environment.
EGUI_ELEMENT_TYPE Type
type of element
Detailed Description
Definition at line 20 of file guiButton.h.
Member Function Documentation
isAlphaChannelUsed()
bool GUIButton::isAlphaChannelUsed () const override virtual
Checks if the alpha channel should be used for drawing images on the button.
Returns if the alpha channel should be used for drawing images on the button.
Implements irr::gui::IGUIButton.
Definition at line 623 of file guiButton.cpp.
isPushButton()
bool GUIButton::isPushButton () const override virtual
Checks whether the button is a push button.
Returns whether the button is a push button.
Implements irr::gui::IGUIButton.
Definition at line 609 of file guiButton.cpp.
Referenced by setIsPushButton().
isScalingImage()
bool GUIButton::isScalingImage () const override virtual
Checks whether the button scales the used images.
Returns whether the button scale the used images.
Implements irr::gui::IGUIButton.
Definition at line 74 of file guiButton.cpp.
setIsPushButton()
void GUIButton::setIsPushButton (bool isPushButton = true) override virtual
Sets if the button should behave like a push button. Which means it can be in two states: Normal or Pressed. With a click on the button, the user can change the state of the button.
Implements irr::gui::IGUIButton.
Definition at line 569 of file guiButton.cpp.
References isPushButton().
setOverrideColor()
void GUIButton::setOverrideColor (video::SColor color) override virtual
Sets another color for the button text.
Sets another color for the text.
Implements irr::gui::IGUIButton.
Definition at line 492 of file guiButton.cpp.
References irr::gui::StaticText::setOverrideColor().
Referenced by setFromStyle().
setScaleImage()
void GUIButton::setScaleImage (bool scaleImage = true) override virtual
Sets if the button should scale the button images to fit.
Sets if the images should be scaled to fit the button.
Implements irr::gui::IGUIButton.
Definition at line 67 of file guiButton.cpp.
Referenced by GUIButtonImage::GUIButtonImage(), and setFromStyle().
setSprite()
void GUIButton::setSprite (gui::EGUI_BUTTON_STATE state, s32 index, video::SColor color = video::SColor(255,255,255,255), bool loop = false, bool scale = false) override virtual
Sets the animated sprite for a specific button state.
Parameters
index Number of the sprite within the sprite bank, use -1 for no sprite
state State of the button to set the sprite for
index The sprite number from the current sprite bank
color The color of the sprite
Definition at line 98 of file guiButton.cpp.
The documentation for this class was generated from the following files:
src/gui/guiButton.h
src/gui/guiButton.cpp