Three Cubes Game: irr::scene::CAnimatedMeshSceneNode Class Reference
irr::scene::CAnimatedMeshSceneNode Class Reference
Public Member Functions
CAnimatedMeshSceneNode (IAnimatedMesh *mesh, ISceneNode *parent, ISceneManager *mgr, s32 id, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f))
constructor
virtual ~CAnimatedMeshSceneNode ()
destructor
void setCurrentFrame (f32 frame) override
sets the current frame. from now on the animation is played from this frame.
void OnRegisterSceneNode () override
frame
void OnAnimate (u32 timeMs) override
OnAnimate() is called just before rendering the whole scene.
void render () override
renders the node.
const core::aabbox3d< f32 > & getBoundingBox () const override
returns the axis aligned bounding box of this node
bool setFrameLoop (s32 begin, s32 end) override
void setLoopMode (bool playAnimationLooped) override
bool getLoopMode () const override
returns the current loop mode
void setAnimationEndCallback (IAnimationEndCallBack *callback=0) override
void setAnimationSpeed (f32 framesPerSecond) override
sets the speed with witch the animation is played
f32 getAnimationSpeed () const override
gets the speed with which the animation is played
video::SMaterial & getMaterial (u32 i) override
returns the material based on the zero based index i.
u32 getMaterialCount () const override
returns amount of materials used by this scene node.
IBoneSceneNode * getJointNode (const c8 *jointName) override
IBoneSceneNode * getJointNode (u32 jointID) override
same as getJointNode(const c8* jointName), but based on id
u32 getJointCount () const override
Gets joint count.
bool removeChild (ISceneNode *child) override
f32 getFrameNr () const override
Returns the current displayed frame number.
s32 getStartFrame () const override
Returns the current start frame number.
s32 getEndFrame () const override
Returns the current end frame number.
void setReadOnlyMaterials (bool readonly) override
Sets if the scene node should not copy the materials of the mesh but use them in a read only style.
bool isReadOnlyMaterials () const override
Returns if the scene node should not copy the materials of the mesh but use them in a read only style.
void setMesh (IAnimatedMesh *mesh) override
Sets a new mesh.
IAnimatedMesh * getMesh (void) override
Returns the current mesh.
ESCENE_NODE_TYPE getType () const override
Returns type of the scene node.
void updateAbsolutePosition () override
updates the absolute position based on the relative and the parents position
void setJointMode (E_JOINT_UPDATE_ON_RENDER mode) override
Set the joint update mode (0-unused, 1-get joints only, 2-set joints only, 3-move and set)
void setTransitionTime (f32 Time) override
void animateJoints (bool CalculateAbsolutePositions=true) override
updates the joint positions of this mesh
void setRenderFromIdentity (bool On) override
render mesh ignoring its transformation. Used with ragdolls. (culling is unaffected)
ISceneNode * clone (ISceneNode *newParent=0, ISceneManager *newManager=0) override
Creates a clone of this scene node and its children.
Public Member Functions inherited from irr::scene::IAnimatedMeshSceneNode
IAnimatedMeshSceneNode (ISceneNode *parent, ISceneManager *mgr, s32 id, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f))
Constructor.
virtual ~IAnimatedMeshSceneNode ()
Destructor.
Public Member Functions inherited from irr::scene::ISceneNode
ISceneNode (ISceneNode *parent, ISceneManager *mgr, s32 id=-1, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f))
Constructor.
virtual ~ISceneNode ()
Destructor.
virtual const c8 * getName () const
Returns the name of the node.
virtual void setName (const c8 *name)
Sets the name of the node.
virtual void setName (const core::stringc &name)
Sets the name of the node.
virtual const core::aabbox3d< f32 > getTransformedBoundingBox () const
Get the axis aligned, transformed and animated absolute bounding box of this node.
virtual void getTransformedBoundingBoxEdges (core::array< core::vector3d< f32 > > &edges) const
virtual const core::matrix4 & getAbsoluteTransformation () const
Get the absolute transformation of the node. Is recalculated every OnAnimate()-call.
virtual core::matrix4 getRelativeTransformation () const
Returns the relative transformation of the scene node.
virtual bool isVisible () const
Returns whether the node should be visible (if all of its parents are visible).
virtual bool isTrulyVisible () const
Check whether the node is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool isVisible)
Sets if the node should be visible or not.
virtual s32 getID () const
Get the id of the scene node.
virtual void setID (s32 id)
Sets the id of the scene node.
virtual void addChild (ISceneNode *child)
Adds a child to this scene node.
virtual void removeAll ()
Removes all children of this scene node.
virtual void remove ()
Removes this scene node from the scene.
void setMaterialFlag (video::E_MATERIAL_FLAG flag, bool newvalue)
Sets all material flags at once to a new value.
void setMaterialTexture (u32 textureLayer, video::ITexture *texture)
Sets the texture of the specified layer in all materials of this scene node to the new texture.
void setMaterialType (video::E_MATERIAL_TYPE newType)
Sets the material type of all materials in this scene node to a new material type.
virtual const core::vector3df & getScale () const
Gets the scale of the scene node relative to its parent.
virtual void setScale (const core::vector3df &scale)
Sets the relative scale of the scene node.
virtual const core::vector3df & getRotation () const
Gets the rotation of the node relative to its parent.
virtual void setRotation (const core::vector3df &rotation)
Sets the rotation of the node relative to its parent.
virtual const core::vector3df & getPosition () const
Gets the position of the node relative to its parent.
virtual void setPosition (const core::vector3df &newpos)
Sets the position of the node relative to its parent.
virtual core::vector3df getAbsolutePosition () const
Gets the absolute position of the node in world coordinates.
void setAutomaticCulling (u32 state)
Set a culling style or disable culling completely.
u32 getAutomaticCulling () const
Gets the automatic culling state.
virtual void setDebugDataVisible (u32 state)
Sets if debug data like bounding boxes should be drawn.
u32 isDebugDataVisible () const
Returns if debug data like bounding boxes are drawn.
void setIsDebugObject (bool debugObject)
Sets if this scene node is a debug object.
bool isDebugObject () const
Returns if this scene node is a debug object.
const std::list< ISceneNode * > & getChildren () const
Returns a const reference to the list of all children.
virtual void setParent (ISceneNode *newParent)
Changes the parent of the scene node.
scene::ISceneNode * getParent () const
Returns the parent of this scene node.
virtual ISceneManager * getSceneManager (void) const
Retrieve the scene manager for this node.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Member Functions
IMesh * getMeshForCurrentFrame ()
Get a static mesh for the current frame of this animated mesh.
void buildFrameNr (u32 timeMs)
Get CurrentFrameNr and update transiting settings.
void checkJoints ()
void beginTransition ()
Private Attributes
core::array< video::SMaterial > Materials
core::aabbox3d< f32 > Box
IAnimatedMesh * Mesh
s32 StartFrame
s32 EndFrame
f32 FramesPerSecond
f32 CurrentFrameNr
u32 LastTimeMs
u32 TransitionTime
f32 Transiting
f32 TransitingBlend
E_JOINT_UPDATE_ON_RENDER JointMode
bool JointsUsed
bool Looping
bool ReadOnlyMaterials
bool RenderFromIdentity
IAnimationEndCallBack * LoopCallBack
s32 PassCount
core::array< IBoneSceneNode * > JointChildSceneNodes
core::array< core::matrix4 > PretransitingSave
Additional Inherited Members
Protected Member Functions inherited from irr::scene::ISceneNode
void cloneMembers (ISceneNode *toCopyFrom, ISceneManager *newManager)
A clone function for the ISceneNode members.
void setSceneManager (ISceneManager *newManager)
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes inherited from irr::scene::ISceneNode
core::stringc Name
Name of the scene node.
core::matrix4 AbsoluteTransformation
Absolute transformation of the node.
core::vector3df RelativeTranslation
Relative translation of the scene node.
core::vector3df RelativeRotation
Relative rotation of the scene node.
core::vector3df RelativeScale
Relative scale of the scene node.
ISceneNode * Parent
Pointer to the parent.
std::list< ISceneNode * > Children
List of all children of this node.
ISceneManager * SceneManager
Pointer to the scene manager.
s32 ID
ID of the node.
u32 AutomaticCullingState
Automatic culling state.
u32 DebugDataVisible
Flag if debug data should be drawn, such as Bounding Boxes.
bool IsVisible
Is the node visible?
bool IsDebugObject
Is debug object?
Detailed Description
Definition at line 20 of file CAnimatedMeshSceneNode.h.
Member Function Documentation
clone()
ISceneNode * irr::scene::CAnimatedMeshSceneNode::clone (ISceneNode * newParent = 0, ISceneManager * newManager = 0) override virtual
Creates a clone of this scene node and its children.
Parameters
newParent An optional new parent.
newManager An optional new scene manager.
Returns
The newly created clone of this node.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 868 of file CAnimatedMeshSceneNode.cpp.
References CAnimatedMeshSceneNode(), irr::scene::ISceneNode::cloneMembers(), irr::IReferenceCounted::drop(), irr::IReferenceCounted::grab(), irr::scene::ISceneNode::ID, irr::scene::ISceneNode::Parent, irr::scene::ISceneNode::RelativeRotation, irr::scene::ISceneNode::RelativeScale, irr::scene::ISceneNode::RelativeTranslation, irr::scene::ISceneNode::SceneManager, and irr::scene::ISceneNode::setParent().
getEndFrame()
s32 irr::scene::CAnimatedMeshSceneNode::getEndFrame () const override virtual
Returns the current end frame number.
Returns the current start frame number.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 428 of file CAnimatedMeshSceneNode.cpp.
getFrameNr()
f32 irr::scene::CAnimatedMeshSceneNode::getFrameNr () const override virtual
Returns the current displayed frame number.
Returns the currently displayed frame number.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 70 of file CAnimatedMeshSceneNode.cpp.
Referenced by animateJoints(), and getMeshForCurrentFrame().
getJointNode() [1/2]
IBoneSceneNode * irr::scene::CAnimatedMeshSceneNode::getJointNode (const c8 * jointName) override virtual
Returns a pointer to a child node, which has the same transformation as the corresponding joint, if the mesh in this scene node is a skinned mesh.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 498 of file CAnimatedMeshSceneNode.cpp.
References irr::scene::EAMT_SKINNED, irr::ELL_DEBUG, irr::ELL_WARNING, irr::scene::ISkinnedMesh::getJointNumber(), and irr::scene::IAnimatedMesh::getMeshType().
getJointNode() [2/2]
IBoneSceneNode * irr::scene::CAnimatedMeshSceneNode::getJointNode (u32 jointID) override virtual
same as getJointNode(const c8* jointName), but based on id
Returns a pointer to a child node, which has the same transformation as the corresponding joint, if the mesh in this scene node is a skinned mesh.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 537 of file CAnimatedMeshSceneNode.cpp.
References irr::scene::EAMT_SKINNED, irr::ELL_WARNING, and irr::scene::IAnimatedMesh::getMeshType().
getMaterial()
video::SMaterial & irr::scene::CAnimatedMeshSceneNode::getMaterial (u32 i) override virtual
returns the material based on the zero based index i.
returns the material based on the zero based index i. To get the amount of materials used by this scene node, use getMaterialCount(). This function is needed for inserting the node into the scene hierarchy on a optimal position for minimizing renderstate changes, but can also be used to directly modify the material of a scene node.
Reimplemented from irr::scene::ISceneNode.
Definition at line 479 of file CAnimatedMeshSceneNode.cpp.
References irr::scene::ISceneNode::getMaterial().
removeChild()
bool irr::scene::CAnimatedMeshSceneNode::removeChild (ISceneNode * child) override virtual
Removes a child from this scene node. Implemented here, to be able to remove the shadow properly, if there is one, or to remove attached child.
Removes a child from this scene node. Implemented here, to be able to remove the shadow properly, if there is one, or to remove attached childs.
Reimplemented from irr::scene::ISceneNode.
Definition at line 582 of file CAnimatedMeshSceneNode.cpp.
References irr::scene::ISceneNode::removeChild().
setAnimationEndCallback()
void irr::scene::CAnimatedMeshSceneNode::setAnimationEndCallback (IAnimationEndCallBack * callback = 0) override virtual
Sets a callback interface which will be called if an animation playback has ended. Set this to 0 to disable the callback again.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 620 of file CAnimatedMeshSceneNode.cpp.
References irr::IReferenceCounted::drop(), and irr::IReferenceCounted::grab().
setAnimationSpeed()
void irr::scene::CAnimatedMeshSceneNode::setAnimationSpeed (f32 framesPerSecond) override virtual
sets the speed with witch the animation is played
sets the speed with which the animation is played NOTE: setMesh will also change this value and set it to the default speed of the mesh
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 459 of file CAnimatedMeshSceneNode.cpp.
Referenced by setMesh().
setCurrentFrame()
void irr::scene::CAnimatedMeshSceneNode::setCurrentFrame (f32 frame) override virtual
sets the current frame. from now on the animation is played from this frame.
Sets the current frame. From now on the animation is played from this frame.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 60 of file CAnimatedMeshSceneNode.cpp.
References irr::core::clamp().
Referenced by setFrameLoop().
setFrameLoop()
bool irr::scene::CAnimatedMeshSceneNode::setFrameLoop (s32 begin, s32 end) override virtual
sets the frames between the animation is looped. the default is 0 - MaximalFrameCount of the mesh. NOTE: setMesh will also change this value and set it to the full range of animations of the mesh
sets the frames between the animation is looped. the default is 0 - MaximalFrameCount of the mesh.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 436 of file CAnimatedMeshSceneNode.cpp.
References irr::scene::IAnimatedMesh::getFrameCount(), and setCurrentFrame().
Referenced by setMesh().
setLoopMode()
void irr::scene::CAnimatedMeshSceneNode::setLoopMode (bool playAnimationLooped) override virtual
Sets looping mode which is on by default. If set to false, animations will not be looped.
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 606 of file CAnimatedMeshSceneNode.cpp.
setTransitionTime()
void irr::scene::CAnimatedMeshSceneNode::setTransitionTime (f32 time) override virtual
Sets the transition time in seconds (note: This needs to enable joints, and setJointmode maybe set to 2) you must call animateJoints(), or the mesh will not animate
Implements irr::scene::IAnimatedMeshSceneNode.
Definition at line 713 of file CAnimatedMeshSceneNode.cpp.
References irr::scene::EJUOR_CONTROL, irr::scene::EJUOR_NONE, and setJointMode().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CAnimatedMeshSceneNode.h
lib/irrlichtmt/source/Irrlicht/CAnimatedMeshSceneNode.cpp