Three Cubes Game: irr::io::CZipReader Class Reference
irr::io::CZipReader Class Reference
#include <CZipReader.h>
Public Member Functions
CZipReader (IFileSystem *fs, IReadFile *file, bool ignoreCase, bool ignorePaths, bool isGZip=false)
constructor
virtual ~CZipReader ()
destructor
IReadFile * createAndOpenFile (const io::path &filename) override
opens a file by file name
IReadFile * createAndOpenFile (u32 index) override
opens a file by index
const IFileList * getFileList () const override
returns the list of files
E_FILE_ARCHIVE_TYPE getType () const override
get the archive type
const io::path & getArchiveName () const override
return the id of the file Archive
Public Member Functions inherited from irr::io::IFileArchive
virtual void addDirectoryToFileList (const io::path &filename)
Add a directory in the archive and all it's files to the FileList.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Protected Member Functions
bool scanZipHeader (bool ignoreGPBits=false)
reads the next file header from a ZIP file, returns false if there are no more headers.
bool scanGZipHeader ()
the same but for gzip files
bool scanCentralDirectoryHeader ()
scans for a local header, returns false if there is no more local file header.
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
io::IFileSystem * FileSystem
IReadFile * File
core::array< SZipFileEntry > FileInfo
bool IsGZip
Additional Inherited Members
Public Attributes inherited from irr::io::IFileArchive
core::stringc Password
An optionally used password string.
Private Member Functions inherited from irr::io::CFileList
CFileList (const io::path &path, bool ignoreCase, bool ignorePaths)
Constructor.
virtual ~CFileList ()
Destructor.
u32 addItem (const io::path &fullPath, u32 offset, u32 size, bool isDirectory, u32 id=0) override
Add as a file or folder to the list.
void sort () override
Sorts the file list. You should call this after adding any items to the file list.
u32 getFileCount () const override
Returns the amount of files in the filelist.
const io::path & getFileName (u32 index) const override
Gets the name of a file in the list, based on an index.
const io::path & getFullFileName (u32 index) const override
Gets the full name of a file in the list, path included, based on an index.
u32 getID (u32 index) const override
Returns the ID of a file in the file list, based on an index.
bool isDirectory (u32 index) const override
Returns true if the file is a directory.
u32 getFileSize (u32 index) const override
Returns the size of a file.
u32 getFileOffset (u32 index) const override
Returns the offset of a file.
s32 findFile (const io::path &filename, bool isFolder) const override
Searches for a file or folder within the list, returns the index.
const io::path & getPath () const override
Returns the base path of the file list.
Private Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Private Attributes inherited from irr::io::CFileList
bool IgnorePaths
Ignore paths when adding or searching for files.
bool IgnoreCase
Ignore case when adding or searching for files.
io::path Path
Path to the file list.
core::array< SFileListEntry > Files
List of files.
Detailed Description
Zip file Reader written April 2002 by N.Gebhardt.
Definition at line 175 of file CZipReader.h.
Member Function Documentation
scanGZipHeader()
bool irr::io::CZipReader::scanGZipHeader () protected
the same but for gzip files
scans for a local header, returns false if there is no more local file header. The gzip file format seems to think that there can be multiple files in a gzip file but none
Definition at line 155 of file CZipReader.cpp.
References irr::io::CFileList::addItem(), irr::core::string< T >::append(), irr::core::deletePathFromFilename(), irr::io::IReadFile::getPos(), irr::io::IReadFile::getSize(), irr::core::hasFileExtension(), irr::io::SZipFileEntry::header, irr::io::SZipFileEntry::Offset, irr::io::CFileList::Path, irr::io::IReadFile::read(), irr::io::IReadFile::seek(), irr::core::string< T >::size(), and irr::core::string< T >::validate().
Referenced by CZipReader().
scanZipHeader()
bool irr::io::CZipReader::scanZipHeader (bool ignoreGPBits = false) protected
reads the next file header from a ZIP file, returns false if there are no more headers.
scans for a local header, returns false if there is no more local file header.
Definition at line 263 of file CZipReader.cpp.
References irr::io::CFileList::addItem(), irr::io::CFileList::Files, irr::io::IReadFile::getPos(), irr::io::IReadFile::getSize(), irr::io::SZipFileEntry::header, irr::core::string< T >::lastChar(), irr::io::SZipFileEntry::Offset, irr::io::IReadFile::read(), scanCentralDirectoryHeader(), and irr::io::IReadFile::seek().
Referenced by CZipReader(), and scanCentralDirectoryHeader().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CZipReader.h
lib/irrlichtmt/source/Irrlicht/CZipReader.cpp