Three Cubes Game: irr::core::vector2d< T > Class Template Reference
irr::core::vector2d< T > Class Template Reference
2d vector template class with lots of operators and methods.
#include <vector2d.h>
Public Member Functions
vector2d ()
Default constructor (null vector)
vector2d (T nx, T ny)
Constructor with two different values.
vector2d (T n)
Constructor with the same value for both members.
vector2d (const dimension2d< T > &other)
vector2d< T > operator- () const
vector2d< T > & operator= (const dimension2d< T > &other)
vector2d< T > operator+ (const vector2d< T > &other) const
vector2d< T > operator+ (const dimension2d< T > &other) const
vector2d< T > & operator+= (const vector2d< T > &other)
vector2d< T > operator+ (const T v) const
vector2d< T > & operator+= (const T v)
vector2d< T > & operator+= (const dimension2d< T > &other)
vector2d< T > operator- (const vector2d< T > &other) const
vector2d< T > operator- (const dimension2d< T > &other) const
vector2d< T > & operator-= (const vector2d< T > &other)
vector2d< T > operator- (const T v) const
vector2d< T > & operator-= (const T v)
vector2d< T > & operator-= (const dimension2d< T > &other)
vector2d< T > operator* (const vector2d< T > &other) const
vector2d< T > & operator*= (const vector2d< T > &other)
vector2d< T > operator* (const T v) const
vector2d< T > & operator*= (const T v)
vector2d< T > operator/ (const vector2d< T > &other) const
vector2d< T > & operator/= (const vector2d< T > &other)
vector2d< T > operator/ (const T v) const
vector2d< T > & operator/= (const T v)
T & operator[] (u32 index)
const T & operator[] (u32 index) const
bool operator<= (const vector2d< T > &other) const
sort in order X, Y. Equality with rounding tolerance.
bool operator>= (const vector2d< T > &other) const
sort in order X, Y. Equality with rounding tolerance.
bool operator< (const vector2d< T > &other) const
sort in order X, Y. Difference must be above rounding tolerance.
bool operator> (const vector2d< T > &other) const
sort in order X, Y. Difference must be above rounding tolerance.
bool operator== (const vector2d< T > &other) const
bool operator!= (const vector2d< T > &other) const
bool equals (const vector2d< T > &other, const T tolerance=(T) ROUNDING_ERROR_f32) const
Checks if this vector equals the other one.
vector2d< T > & set (T nx, T ny)
vector2d< T > & set (const vector2d< T > &p)
T getLength () const
Gets the length of the vector.
T getLengthSQ () const
Get the squared length of this vector.
T dotProduct (const vector2d< T > &other) const
Get the dot product of this vector with another.
bool nearlyParallel (const vector2d< T > &other, const T factor=relativeErrorFactor< T >()) const
check if this vector is parallel to another vector
T getDistanceFrom (const vector2d< T > &other) const
Gets distance from another point.
T getDistanceFromSQ (const vector2d< T > &other) const
Returns squared distance from another point.
vector2d< T > & rotateBy (f64 degrees, const vector2d< T > &center=vector2d< T >())
rotates the point anticlockwise around a center by an amount of degrees.
vector2d< T > & normalize ()
Normalize the vector.
f64 getAngleTrig () const
Calculates the angle of this vector in degrees in the trigonometric sense.
f64 getAngle () const
Calculates the angle of this vector in degrees in the counter trigonometric sense.
f64 getAngleWith (const vector2d< T > &b) const
Calculates the angle between this vector and another one in degree.
bool isBetweenPoints (const vector2d< T > &begin, const vector2d< T > &end) const
Returns if this vector interpreted as a point is on a line between two other points.
vector2d< T > getInterpolated (const vector2d< T > &other, f64 d) const
Creates an interpolated vector between this vector and another vector.
vector2d< T > getInterpolated_quadratic (const vector2d< T > &v2, const vector2d< T > &v3, f64 d) const
Creates a quadratically interpolated vector between this and two other vectors.
s32 checkOrientation (const vector2d< T > &b, const vector2d< T > &c) const
bool areClockwise (const vector2d< T > &b, const vector2d< T > &c) const
bool areCounterClockwise (const vector2d< T > &b, const vector2d< T > &c) const
vector2d< T > & interpolate (const vector2d< T > &a, const vector2d< T > &b, f64 d)
Sets this vector to the linearly interpolated vector between a and b.
Public Attributes
T X
X coordinate of vector.
T Y
Y coordinate of vector.
Detailed Description
template<class T>
class irr::core::vector2d< T >
2d vector template class with lots of operators and methods.
As of Irrlicht 1.6, this class supersedes position2d, which should be considered deprecated.
Definition at line 16 of file dimension2d.h.
Member Function Documentation
areClockwise()
template<class T > bool irr::core::vector2d< T >::areClockwise (const vector2d< T > & b, const vector2d< T > & c) const inline
Returns true if points (a,b,c) are clockwise on the X,Y plane
Definition at line 363 of file vector2d.h.
areCounterClockwise()
template<class T > bool irr::core::vector2d< T >::areCounterClockwise (const vector2d< T > & b, const vector2d< T > & c) const inline
Returns true if points (a,b,c) are counterclockwise on the X,Y plane
Definition at line 372 of file vector2d.h.
checkOrientation()
template<class T > s32 irr::core::vector2d< T >::checkOrientation (const vector2d< T > & b, const vector2d< T > & c) const inline
Test if this point and another 2 points taken as triplet are colinear, clockwise, anticlockwise. This can be used also to check winding order in triangles for 2D meshes.
Returns
0 if points are colinear, 1 if clockwise, 2 if anticlockwise
Definition at line 343 of file vector2d.h.
dotProduct()
template<class T > T irr::core::vector2d< T >::dotProduct (const vector2d< T > & other) const inline
Get the dot product of this vector with another.
Parameters
other Other vector to take dot product with.
Returns
The dot product of the two vectors.
Definition at line 137 of file vector2d.h.
Referenced by irr::core::line2d< T >::getClosestPoint().
equals()
template<class T > bool irr::core::vector2d< T >::equals (const vector2d< T > & other, const T tolerance = (T)ROUNDING_ERROR_f32) const inline
Checks if this vector equals the other one.
Takes floating point rounding errors into account.
Parameters
other Vector to compare with.
tolerance Epsilon value for both - comparing X and Y.
Returns
True if the two vector are (almost) equal, else false.
Definition at line 117 of file vector2d.h.
getAngle()
template<class T > f64 irr::core::vector2d< T >::getAngle () const inline
Calculates the angle of this vector in degrees in the counter trigonometric sense.
0 is to the right (3 o'clock), values increase clockwise.
Returns
Returns a value between 0 and 360.
Definition at line 235 of file vector2d.h.
getAngleTrig()
template<class T > f64 irr::core::vector2d< T >::getAngleTrig () const inline
Calculates the angle of this vector in degrees in the trigonometric sense.
0 is to the right (3 o'clock), values increase counter-clockwise. This method has been suggested by Pr3t3nd3r.
Returns
Returns a value between 0 and 360.
Definition at line 212 of file vector2d.h.
getAngleWith()
template<class T > f64 irr::core::vector2d< T >::getAngleWith (const vector2d< T > & b) const inline
Calculates the angle between this vector and another one in degree.
Parameters
b Other vector to test with.
Returns
Returns a value between 0 and 90.
Definition at line 265 of file vector2d.h.
Referenced by irr::core::line2d< T >::getAngleWith().
getDistanceFrom()
template<class T > T irr::core::vector2d< T >::getDistanceFrom (const vector2d< T > & other) const inline
Gets distance from another point.
Here, the vector is interpreted as a point in 2-dimensional space.
Parameters
other Other vector to measure from.
Returns
Distance from other point.
Definition at line 160 of file vector2d.h.
getDistanceFromSQ()
template<class T > T irr::core::vector2d< T >::getDistanceFromSQ (const vector2d< T > & other) const inline
Returns squared distance from another point.
Here, the vector is interpreted as a point in 2-dimensional space.
Parameters
other Other vector to measure from.
Returns
Squared distance from other point.
Definition at line 169 of file vector2d.h.
getInterpolated()
template<class T > vector2d<T> irr::core::vector2d< T >::getInterpolated (const vector2d< T > & other, f64 d) const inline
Creates an interpolated vector between this vector and another vector.
Parameters
other The other vector to interpolate with.
d Interpolation value between 0.0f (all the other vector) and 1.0f (all this vector). Note that this is the opposite direction of interpolation to getInterpolated_quadratic()
Returns
An interpolated vector. This vector is not modified.
Definition at line 314 of file vector2d.h.
getInterpolated_quadratic()
template<class T > vector2d<T> irr::core::vector2d< T >::getInterpolated_quadratic (const vector2d< T > & v2, const vector2d< T > & v3, f64 d) const inline
Creates a quadratically interpolated vector between this and two other vectors.
Parameters
v2 Second vector to interpolate with.
v3 Third vector to interpolate with (maximum at 1.0f)
d Interpolation value between 0.0f (all this vector) and 1.0f (all the 3rd vector). Note that this is the opposite direction of interpolation to getInterpolated() and interpolate()
Returns
An interpolated vector. This vector is not modified.
Definition at line 326 of file vector2d.h.
getLength()
template<class T > T irr::core::vector2d< T >::getLength () const inline
Gets the length of the vector.
Returns
The length of the vector.
Definition at line 127 of file vector2d.h.
Referenced by irr::core::line2d< T >::getClosestPoint(), and irr::core::vector2d< s16 >::getDistanceFrom().
getLengthSQ()
template<class T > T irr::core::vector2d< T >::getLengthSQ () const inline
Get the squared length of this vector.
This is useful because it is much faster than getLength().
Returns
The squared length of the vector.
Definition at line 132 of file vector2d.h.
Referenced by irr::core::vector2d< s16 >::getDistanceFromSQ().
interpolate()
template<class T > vector2d<T>& irr::core::vector2d< T >::interpolate (const vector2d< T > & a, const vector2d< T > & b, f64 d) inline
Sets this vector to the linearly interpolated vector between a and b.
Parameters
a first vector to interpolate with, maximum at 1.0f
b second vector to interpolate with, maximum at 0.0f
d Interpolation value between 0.0f (all vector b) and 1.0f (all vector a) Note that this is the opposite direction of interpolation to getInterpolated_quadratic()
Definition at line 386 of file vector2d.h.
isBetweenPoints()
template<class T > bool irr::core::vector2d< T >::isBetweenPoints (const vector2d< T > & begin, const vector2d< T > & end) const inline
Returns if this vector interpreted as a point is on a line between two other points.
It is assumed that the point is on the line.
Parameters
begin Beginning vector to compare between.
end Ending vector to compare between.
Returns
True if this vector is between begin and end, false if not.
Definition at line 286 of file vector2d.h.
Referenced by irr::core::line2d< T >::lineIntersectSegment().
normalize()
template<class T > vector2d<T>& irr::core::vector2d< T >::normalize () inline
Normalize the vector.
The null vector is left untouched.
Returns
Reference to this vector, after normalization.
Definition at line 197 of file vector2d.h.
rotateBy()
template<class T > vector2d<T>& irr::core::vector2d< T >::rotateBy (f64 degrees, const vector2d< T > & center = vector2d<T>()) inline
rotates the point anticlockwise around a center by an amount of degrees.
Parameters
degrees Amount of degrees to rotate by, anticlockwise.
center Rotation center.
Returns
This vector after transformation.
Definition at line 178 of file vector2d.h.
The documentation for this class was generated from the following files:
lib/irrlichtmt/include/dimension2d.h
lib/irrlichtmt/include/vector2d.h