Three Cubes Game: Environment Class Reference
Environment Class Reference abstract
Public Member Functions
Environment (IGameDef *gamedef)
DISABLE_CLASS_COPY (Environment)
virtual void step (f32 dtime)=0
virtual Map & getMap ()=0
u32 getDayNightRatio ()
virtual void setTimeOfDay (u32 time)
u32 getTimeOfDay ()
float getTimeOfDayF ()
void stepTimeOfDay (float dtime)
void setTimeOfDaySpeed (float speed)
void setDayNightRatioOverride (bool enable, u32 value)
u32 getDayCount ()
bool line_of_sight (v3f pos1, v3f pos2, v3s16 *p=nullptr)
virtual void getSelectedActiveObjects (const core::line3d< f32 > &shootline_on_map, std::vector< PointedThing > &objects)=0
void continueRaycast (RaycastState *state, PointedThing *result)
IGameDef * getGameDef ()
Public Attributes
u32 m_added_objects
Protected Attributes
std::atomic< float > m_time_of_day_speed
u32 m_time_of_day
float m_time_of_day_f
float m_time_conversion_skew = 0.0f
bool m_enable_day_night_ratio_override = false
u32 m_day_night_ratio_override = 0.0f
std::atomic< u32 > m_day_count
bool m_cache_enable_shaders
float m_cache_active_block_mgmt_interval
float m_cache_abm_interval
float m_cache_nodetimer_interval
float m_cache_abm_time_budget
IGameDef * m_gamedef
Private Attributes
std::mutex m_time_lock
Detailed Description
Definition at line 46 of file environment.h.
Member Function Documentation
continueRaycast()
void Environment::continueRaycast (RaycastState * state, PointedThing * result)
Returns the next node or object the shootline meets.
Parameters
state current state of the raycast
Returns
output, will contain the next pointed thing
Definition at line 115 of file environment.cpp.
References PointedThing::box_id, PointedThing::distanceSq, voxalgo::VoxelLineIterator::getIndex(), MapNode::getNeighbors(), NodeDefManager::getSelectionBoxIntUnion(), irr::core::line3d< T >::getVector(), PointedThing::intersection_normal, PointedThing::intersection_point, voxalgo::VoxelLineIterator::m_current_index, voxalgo::VoxelLineIterator::m_current_node_pos, RaycastState::m_found, RaycastState::m_initialization_needed, RaycastState::m_iterator, voxalgo::VoxelLineIterator::m_last_index, RaycastState::m_previous_node, RaycastState::m_search_range, RaycastState::m_shootline, irr::core::aabbox3d< T >::MaxEdge, irr::core::aabbox3d< T >::MinEdge, voxalgo::VoxelLineIterator::next(), PointedThing::node_abovesurface, PointedThing::node_real_undersurface, PointedThing::node_undersurface, irr::core::line3d< T >::start, PointedThing::type, irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
getSelectedActiveObjects()
virtual void Environment::getSelectedActiveObjects (const core::line3d< f32 > & shootline_on_map, std::vector< PointedThing > & objects) pure virtual
Gets the objects pointed by the shootline as pointed things. If this is a client environment, the local player won't be returned.
Parameters
[in] shootline_on_map the shootline for the test in world coordinates
[out] objects found objects
line_of_sight()
bool Environment::line_of_sight (v3f pos1, v3f pos2, v3s16 * p = nullptr)
Returns false if the given line intersects with a non-air node, true otherwise.
Parameters
pos1 start of the line
pos2 end of the line
p output, position of the first non-air node the line intersects
Definition at line 86 of file environment.cpp.
References voxalgo::VoxelLineIterator::m_current_index, voxalgo::VoxelLineIterator::m_current_node_pos, voxalgo::VoxelLineIterator::m_last_index, and voxalgo::VoxelLineIterator::next().
The documentation for this class was generated from the following files:
src/environment.h
src/environment.cpp