Three Cubes Game: irr::scene::CB3DMeshFileLoader Class Reference
irr::scene::CB3DMeshFileLoader Class Reference
Meshloader for B3D format.
#include <CB3DMeshFileLoader.h>
Public Member Functions
CB3DMeshFileLoader (scene::ISceneManager *smgr)
Constructor.
bool isALoadableFileExtension (const io::path &filename) const override
IAnimatedMesh * createMesh (io::IReadFile *file) override
Public Member Functions inherited from irr::scene::IMeshLoader
IMeshLoader ()
Constructor.
virtual ~IMeshLoader ()
Destructor.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Member Functions
bool load ()
bool readChunkNODE (CSkinnedMesh::SJoint *InJoint)
bool readChunkMESH (CSkinnedMesh::SJoint *InJoint)
bool readChunkVRTS (CSkinnedMesh::SJoint *InJoint)
bool readChunkTRIS (scene::SSkinMeshBuffer *MeshBuffer, u32 MeshBufferID, s32 Vertices_Start)
bool readChunkBONE (CSkinnedMesh::SJoint *InJoint)
bool readChunkKEYS (CSkinnedMesh::SJoint *InJoint)
bool readChunkANIM ()
bool readChunkTEXS ()
bool readChunkBRUS ()
void readString (core::stringc &newstring)
void readFloats (f32 *vec, u32 count)
Private Attributes
core::array< SB3dChunk > B3dStack
core::array< SB3dMaterial > Materials
core::array< SB3dTexture > Textures
core::array< s32 > AnimatedVertices_VertexID
core::array< s32 > AnimatedVertices_BufferID
core::array< video::S3DVertex2TCoords > BaseVertices
CSkinnedMesh * AnimatedMesh
io::IReadFile * B3DFile
u32 VerticesStart
bool NormalsInFile
bool HasVertexColors
bool ShowWarning
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Meshloader for B3D format.
Definition at line 26 of file CB3DMeshFileLoader.h.
Member Function Documentation
createMesh()
IAnimatedMesh * irr::scene::CB3DMeshFileLoader::createMesh (io::IReadFile * file) override virtual
creates/loads an animated mesh from the file.
Returns
Pointer to the created mesh. Returns 0 if loading failed. If you no longer need the mesh, you should call IAnimatedMesh::drop(). See IReferenceCounted::drop() for more information.
Implements irr::scene::IMeshLoader.
Definition at line 47 of file CB3DMeshFileLoader.cpp.
References irr::IReferenceCounted::drop(), and irr::scene::CSkinnedMesh::finalize().
isALoadableFileExtension()
bool irr::scene::CB3DMeshFileLoader::isALoadableFileExtension (const io::path & filename) const override virtual
returns true if the file maybe is able to be loaded by this class based on the file extension (e.g. ".bsp")
Implements irr::scene::IMeshLoader.
Definition at line 37 of file CB3DMeshFileLoader.cpp.
References irr::core::hasFileExtension().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CB3DMeshFileLoader.h
lib/irrlichtmt/source/Irrlicht/CB3DMeshFileLoader.cpp