Three Cubes Game: TextureBufferOutput Class Reference
TextureBufferOutput Class Reference
#include <pipeline.h>
Public Member Functions
TextureBufferOutput (TextureBuffer *buffer, u8 texture_index)
TextureBufferOutput (TextureBuffer *buffer, const std::vector< u8 > &texture_map)
TextureBufferOutput (TextureBuffer *buffer, const std::vector< u8 > &texture_map, u8 depth_stencil)
void activate (PipelineContext &context) override
Public Member Functions inherited from RenderTarget
virtual void reset (PipelineContext &context) override
Private Attributes
TextureBuffer * buffer
std::vector< u8 > texture_map
u8 depth_stencil { NO_DEPTH_TEXTURE }
video::IRenderTarget * render_target { nullptr }
video::IVideoDriver * driver { nullptr }
Static Private Attributes
static const u8 NO_DEPTH_TEXTURE = 255
Additional Inherited Members
Protected Attributes inherited from RenderTarget
bool m_clear {true}
Detailed Description
Targets output to designated texture in texture buffer
Definition at line 178 of file pipeline.h.
Member Function Documentation
activate()
void TextureBufferOutput::activate (PipelineContext & context) override virtual
Activate the render target and configure OpenGL state for the output. This is usually done by
See also
RenderStep implementations.
Reimplemented from RenderTarget.
Definition at line 178 of file pipeline.cpp.
References RenderTarget::activate(), irr::video::IVideoDriver::addRenderTarget(), irr::video::ITexture::getSize(), TextureBuffer::getTexture(), irr::IrrlichtDevice::getVideoDriver(), irr::video::IVideoDriver::OnResize(), irr::core::array< T >::push_back(), irr::video::IVideoDriver::setRenderTarget(), irr::video::IVideoDriver::setRenderTargetEx(), irr::video::IRenderTarget::setTexture(), irr::core::array< T >::size(), and irr::core::dimension2d< T >::Width.
The documentation for this class was generated from the following files:
src/client/render/pipeline.h
src/client/render/pipeline.cpp