Three Cubes Game: TextureSource Class Reference
TextureSource Class Reference
Public Member Functions
u32 getTextureId (const std::string &name)
std::string getTextureName (u32 id)
video::ITexture * getTexture (u32 id)
video::ITexture * getTexture (const std::string &name, u32 *id=NULL)
video::ITexture * getTextureForMesh (const std::string &name, u32 *id)
virtual Palette * getPalette (const std::string &name)
bool isKnownSourceImage (const std::string &name)
void processQueue ()
void insertSourceImage (const std::string &name, video::IImage *img)
void rebuildImagesAndTextures ()
video::ITexture * getNormalTexture (const std::string &name)
video::SColor getTextureAverageColor (const std::string &name)
video::ITexture * getShaderFlagsTexture (bool normamap_present)
Private Member Functions
void rebuildTexture (video::IVideoDriver *driver, TextureInfo &ti)
u32 generateTexture (const std::string &name)
bool generateImagePart (std::string part_of_name, video::IImage *&baseimg, std::set< std::string > &source_image_names)
video::IImage * generateImage (const std::string &name, std::set< std::string > &source_image_names)
Private Attributes
std::thread::id m_main_thread
SourceImageCache m_sourcecache
MutexedMap< std::string, bool > m_source_image_existence
std::vector< TextureInfo > m_textureinfo_cache
std::map< std::string, u32 > m_name_to_id
std::mutex m_textureinfo_cache_mutex
RequestQueue< std::string, u32, std::thread::id, u8 > m_get_texture_queue
std::vector< video::ITexture * > m_texture_trash
std::unordered_map< std::string, Palette > m_palettes
bool m_setting_mipmap
bool m_setting_trilinear_filter
bool m_setting_bilinear_filter
Detailed Description
Definition at line 285 of file tile.cpp.
Member Function Documentation
generateImage()
video::IImage * TextureSource::generateImage (const std::string & name, std::set< std::string > & source_image_names) private
Generates an image from a full string like "stone.png^mineral_coal.png^[crack:1:0". Shall be called from the main thread. The returned Image should be dropped. source_image_names is important to determine when to flush the image from a cache (dynamic media)
Definition at line 979 of file tile.cpp.
References irr::IReferenceCounted::drop(), and irr::video::IImage::getDimension().
Referenced by getPalette().
getPalette()
Palette * TextureSource::getPalette (const std::string & name) virtual
Returns a palette from the given texture name. The pointer is valid until the texture source is destructed. Should be called from the main thread.
Implements ITextureSource.
Definition at line 714 of file tile.cpp.
References irr::IReferenceCounted::drop(), generateImage(), irr::video::IImage::getDimension(), irr::video::IImage::getPixel(), irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
The documentation for this class was generated from the following file:
src/client/tile.cpp