Three Cubes Game: AsyncEngine Class Reference
AsyncEngine Class Reference
Public Member Functions
AsyncEngine (Server *server)
void registerStateInitializer (StateInitializer func)
void initialize (unsigned int numEngines)
u32 queueAsyncJob (std::string &&func, std::string &&params, const std::string &mod_origin="")
u32 queueAsyncJob (std::string &&func, PackedValue *params, const std::string &mod_origin="")
void step (lua_State *L)
Protected Member Functions
bool getJob (LuaJobInfo *job)
void putJobResult (LuaJobInfo &&result)
void addWorkerThread ()
void stepJobResults (lua_State *L)
void stepAutoscale ()
bool prepareEnvironment (lua_State *L, int top)
Private Types
typedef void(* StateInitializer) (lua_State *L, int top)
Private Attributes
bool initDone = false
unsigned int autoscaleMaxWorkers = 0
u64 autoscaleTimer = 0
std::unordered_set< u32 > autoscaleSeenJobs
Server * server = nullptr
std::vector< StateInitializer > stateInitializers
u32 jobIdCounter = 0
std::mutex jobQueueMutex
std::deque< LuaJobInfo > jobQueue
std::mutex resultQueueMutex
std::deque< LuaJobInfo > resultQueue
std::vector< AsyncWorkerThread * > workerThreads
Semaphore jobQueueCounter
Friends
class AsyncWorkerThread
Detailed Description
Definition at line 79 of file s_async.h.
Member Function Documentation
addWorkerThread()
void AsyncEngine::addWorkerThread () protected
Start an additional worker thread
Definition at line 95 of file s_async.cpp.
Referenced by initialize(), and stepAutoscale().
getJob()
bool AsyncEngine::getJob (LuaJobInfo * job) protected
Get a Job from queue to be processed this function blocks until a job is ready
Parameters
job a job to be processed
Returns
whether a job was available
Definition at line 139 of file s_async.cpp.
initialize()
void AsyncEngine::initialize (unsigned int numEngines)
Create async engine tasks and lock function registration
Parameters
numEngines Number of worker threads, 0 for automatic scaling
Definition at line 76 of file s_async.cpp.
References addWorkerThread().
prepareEnvironment()
bool AsyncEngine::prepareEnvironment (lua_State * L, int top) protected
Initialize environment with current registred functions this function adds all functions registred by registerFunction to the passed lua stack
Parameters
L Lua stack to initialize
top Stack position
Returns
false if a mod error ocurred
Definition at line 240 of file s_async.cpp.
putJobResult()
void AsyncEngine::putJobResult (LuaJobInfo && result) protected
Put a Job result back to result queue
Parameters
result result of completed job
Definition at line 157 of file s_async.cpp.
queueAsyncJob() [1/2]
u32 AsyncEngine::queueAsyncJob (std::string && func, PackedValue * params, const std::string & mod_origin = "")
Queue an async job
Parameters
func Serialized lua function
params Serialized parameters (takes ownership!)
Returns
ID of queued job
Definition at line 121 of file s_async.cpp.
queueAsyncJob() [2/2]
u32 AsyncEngine::queueAsyncJob (std::string && func, std::string && params, const std::string & mod_origin = "")
Queue an async job
Parameters
func Serialized lua function
params Serialized parameters
Returns
jobid The job is queued
Definition at line 104 of file s_async.cpp.
registerStateInitializer()
void AsyncEngine::registerStateInitializer (StateInitializer func)
Register function to be called on new states
Parameters
func C function to be called
Definition at line 69 of file s_async.cpp.
step()
void AsyncEngine::step (lua_State * L)
Engine step to process finished jobs
Parameters
L The Lua stack
Definition at line 165 of file s_async.cpp.
References stepAutoscale(), and stepJobResults().
stepAutoscale()
void AsyncEngine::stepAutoscale () protected
Handle automatic scaling of worker threads
Definition at line 205 of file s_async.cpp.
References addWorkerThread().
Referenced by step().
stepJobResults()
void AsyncEngine::stepJobResults (lua_State * L) protected
Process finished jobs callbacks
Definition at line 171 of file s_async.cpp.
Referenced by step().
The documentation for this class was generated from the following files:
src/script/cpp_api/s_async.h
src/script/cpp_api/s_async.cpp