Three Cubes Game: Pathfinder Class Reference
Pathfinder Class Reference
Public Member Functions
Pathfinder (Map *map, const NodeDefManager *ndef)
std::vector< v3s16 > getPath (v3s16 source, v3s16 destination, unsigned int searchdistance, unsigned int max_jump, unsigned int max_drop, PathAlgorithm algo)
Private Member Functions
v3s16 getRealPos (v3s16 ipos)
v3s16 getIndexPos (v3s16 pos)
PathGridnode & getIndexElement (v3s16 ipos)
PathGridnode & getIdxElem (s16 x, s16 y, s16 z)
v3s16 invert (v3s16 pos)
bool isValidIndex (v3s16 index)
int getXZManhattanDist (v3s16 pos)
PathCost calcCost (v3s16 pos, v3s16 dir)
bool updateAllCosts (v3s16 ipos, v3s16 srcdir, int current_cost, int level)
bool updateCostHeuristic (v3s16 isource, v3s16 idestination)
bool buildPath (std::vector< v3s16 > &path, v3s16 ipos)
v3s16 walkDownwards (v3s16 pos, unsigned int max_down)
Private Attributes
int m_max_index_x = 0
int m_max_index_y = 0
int m_max_index_z = 0
int m_maxdrop = 0
int m_maxjump = 0
int m_min_target_distance = 0
bool m_prefetch = true
v3s16 m_start
v3s16 m_destination
core::aabbox3d< s16 > m_limits
GridNodeContainer * m_nodes_container = nullptr
Map * m_map = nullptr
const NodeDefManager * m_ndef = nullptr
Friends
class GridNodeContainer
class PathfinderCompareHeuristic
Detailed Description
class doing pathfinding
Definition at line 178 of file pathfinder.cpp.
Member Function Documentation
buildPath()
bool Pathfinder::buildPath (std::vector< v3s16 > & path, v3s16 ipos) private
build a vector containing all nodes from destination to source; to be called after the node costs have been processed
Parameters
path vector to add nodes to
ipos initial pos to check (index pos)
Returns
true/false path has been fully built
Definition at line 1203 of file pathfinder.cpp.
References getIndexElement(), PathGridnode::is_element, PathGridnode::source, PathGridnode::sourcedir, and PathGridnode::valid.
Referenced by getPath().
calcCost()
PathCost Pathfinder::calcCost (v3s16 pos, v3s16 dir) private
calculate cost of movement
Parameters
pos real world position to start movement
dir direction to move to
Returns
cost information
Definition at line 826 of file pathfinder.cpp.
References NodeDefManager::get(), irr::core::aabbox3d< T >::isPointInside(), m_limits, m_maxdrop, m_maxjump, irr::core::aabbox3d< T >::MaxEdge, irr::core::aabbox3d< T >::MinEdge, PathCost::updated, PathCost::valid, PathCost::value, irr::core::vector3d< T >::Y, and PathCost::y_change.
Referenced by updateCostHeuristic().
getIdxElem()
PathGridnode & Pathfinder::getIdxElem (s16 x, s16 y, s16 z) inline private
Get gridnode at a specific index position
Returns
gridnode for index
Definition at line 973 of file pathfinder.cpp.
getIndexElement()
PathGridnode & Pathfinder::getIndexElement (v3s16 ipos) private
get gridnode at a specific index position
Parameters
ipos index position
Returns
gridnode for index
Definition at line 967 of file pathfinder.cpp.
Referenced by buildPath(), getPath(), updateAllCosts(), and updateCostHeuristic().
getIndexPos()
v3s16 Pathfinder::getIndexPos (v3s16 pos) private
transform mappos to index pos
Parameters
pos a real pos
Returns
index position
Definition at line 961 of file pathfinder.cpp.
References m_limits, and irr::core::aabbox3d< T >::MinEdge.
Referenced by getPath(), updateCostHeuristic(), and walkDownwards().
getPath()
std::vector< v3s16 > Pathfinder::getPath (v3s16 source, v3s16 destination, unsigned int searchdistance, unsigned int max_jump, unsigned int max_drop, PathAlgorithm algo)
path evaluation function
Parameters
env environment to look for path
source origin of path
destination end position of path
searchdistance maximum number of nodes to look in each direction
max_jump maximum number of blocks a path may jump up
max_drop maximum number of blocks a path may drop
algo Algorithm to use for finding a path
Definition at line 605 of file pathfinder.cpp.
References buildPath(), NodeDefManager::get(), getIndexElement(), getIndexPos(), irr::core::vector3d< T >::getLength(), getRealPos(), m_destination, m_limits, m_max_index_x, m_max_index_y, m_max_index_z, m_maxdrop, m_maxjump, m_min_target_distance, m_prefetch, m_start, irr::core::aabbox3d< T >::MaxEdge, irr::core::aabbox3d< T >::MinEdge, PathGridnode::pos, PathGridnode::source, PathGridnode::target, PathGridnode::totalcost, updateAllCosts(), updateCostHeuristic(), PathGridnode::valid, walkDownwards(), irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
getRealPos()
v3s16 Pathfinder::getRealPos (v3s16 ipos) private
transform index pos to mappos
Parameters
ipos an index position
Returns
map position
Definition at line 820 of file pathfinder.cpp.
References m_limits, and irr::core::aabbox3d< T >::MinEdge.
Referenced by getPath(), updateCostHeuristic(), and walkDownwards().
getXZManhattanDist()
int Pathfinder::getXZManhattanDist (v3s16 pos) private
calculate 2D Manhattan distance to target
Parameters
pos position to calc distance
Returns
integer distance
Definition at line 1093 of file pathfinder.cpp.
References m_destination, irr::core::vector3d< T >::X, and irr::core::vector3d< T >::Z.
Referenced by updateCostHeuristic().
invert()
v3s16 Pathfinder::invert (v3s16 pos) private
invert a 3D position (change sign of coordinates)
Parameters
pos 3D position
Returns
pos *-1
Definition at line 993 of file pathfinder.cpp.
References irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
Referenced by updateAllCosts(), and updateCostHeuristic().
isValidIndex()
bool Pathfinder::isValidIndex (v3s16 index) private
check if an index is within current search area
Parameters
index position to validate
Returns
true/false
Definition at line 979 of file pathfinder.cpp.
References m_max_index_x, m_max_index_y, m_max_index_z, irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
Referenced by updateAllCosts(), and updateCostHeuristic().
updateAllCosts()
bool Pathfinder::updateAllCosts (v3s16 ipos, v3s16 srcdir, int current_cost, int level) private
recursive update whole search areas total cost information
Parameters
ipos position to check next
srcdir positionc checked last time
total_cost cost of moving to ipos
level current recursion depth
Returns
true/false path to destination has been found
Definition at line 1005 of file pathfinder.cpp.
References PathGridnode::getCost(), getIndexElement(), invert(), isValidIndex(), m_limits, m_min_target_distance, irr::core::aabbox3d< T >::MaxEdge, PathGridnode::sourcedir, PathGridnode::target, PathGridnode::totalcost, PathCost::valid, PathGridnode::valid, PathCost::value, and PathCost::y_change.
Referenced by getPath().
updateCostHeuristic()
bool Pathfinder::updateCostHeuristic (v3s16 isource, v3s16 idestination) private
try to find a path to destination using a heuristic function to estimate distance to target (A* search algorithm)
Parameters
isource start position (index pos)
idestination end position (index pos)
Returns
true/false path to destination has been found
Definition at line 1106 of file pathfinder.cpp.
References calcCost(), PathGridnode::estimated_cost, PathGridnode::getCost(), getIndexElement(), getIndexPos(), getRealPos(), getXZManhattanDist(), invert(), PathGridnode::is_closed, PathGridnode::is_open, isValidIndex(), m_limits, irr::core::aabbox3d< T >::MaxEdge, PathGridnode::setCost(), PathGridnode::source, PathGridnode::sourcedir, PathGridnode::target, PathGridnode::totalcost, PathCost::updated, PathCost::valid, PathGridnode::valid, PathCost::value, irr::core::vector3d< T >::Y, and PathCost::y_change.
Referenced by getPath().
walkDownwards()
v3s16 Pathfinder::walkDownwards (v3s16 pos, unsigned int max_down) private
go downwards from a position until some barrier is hit.
Parameters
pos position from which to go downwards
max_down maximum distance to go downwards
Returns
new position after movement; if too far down, pos is returned
Definition at line 1234 of file pathfinder.cpp.
References NodeDefManager::get(), getIndexPos(), getRealPos(), m_limits, irr::core::aabbox3d< T >::MinEdge, and irr::core::vector3d< T >::Y.
Referenced by getPath().
Friends And Related Function Documentation
GridNodeContainer
friend class GridNodeContainer friend
contains all map data already collected and analyzed. Access it via the getIndexElement/getIdxElem methods.
Definition at line 321 of file pathfinder.cpp.
Member Data Documentation
m_destination
v3s16 Pathfinder::m_destination private
destination position
Definition at line 315 of file pathfinder.cpp.
Referenced by getPath(), and getXZManhattanDist().
m_limits
core::aabbox3d<s16> Pathfinder::m_limits private
position limits in real map coordinates
Definition at line 317 of file pathfinder.cpp.
Referenced by calcCost(), getIndexPos(), getPath(), getRealPos(), updateAllCosts(), updateCostHeuristic(), and walkDownwards().
m_max_index_x
int Pathfinder::m_max_index_x = 0 private
max index of search area in x direction
Definition at line 304 of file pathfinder.cpp.
Referenced by getPath(), and isValidIndex().
m_max_index_y
int Pathfinder::m_max_index_y = 0 private
max index of search area in y direction
Definition at line 305 of file pathfinder.cpp.
Referenced by getPath(), and isValidIndex().
m_max_index_z
int Pathfinder::m_max_index_z = 0 private
max index of search area in z direction
Definition at line 306 of file pathfinder.cpp.
Referenced by getPath(), and isValidIndex().
m_maxdrop
int Pathfinder::m_maxdrop = 0 private
maximum number of blocks a path may drop
Definition at line 308 of file pathfinder.cpp.
Referenced by calcCost(), and getPath().
m_maxjump
int Pathfinder::m_maxjump = 0 private
maximum number of blocks a path may jump
Definition at line 309 of file pathfinder.cpp.
Referenced by calcCost(), and getPath().
m_min_target_distance
int Pathfinder::m_min_target_distance = 0 private
current smalest path to target
Definition at line 310 of file pathfinder.cpp.
Referenced by getPath(), and updateAllCosts().
m_prefetch
bool Pathfinder::m_prefetch = true private
prefetch cost data
Definition at line 312 of file pathfinder.cpp.
Referenced by getPath().
m_start
v3s16 Pathfinder::m_start private
source position
Definition at line 314 of file pathfinder.cpp.
Referenced by getPath().
The documentation for this class was generated from the following file:
src/pathfinder.cpp