Three Cubes Game: InitInterlacedMaskStep Class Reference
InitInterlacedMaskStep Class Reference
Public Member Functions
InitInterlacedMaskStep (TextureBuffer *buffer, u8 index)
void run (PipelineContext &context)
Public Member Functions inherited from TrivialRenderStep
virtual void setRenderSource (RenderSource *source) override
virtual void setRenderTarget (RenderTarget *target) override
virtual void reset (PipelineContext &) override
Private Attributes
TextureBuffer * buffer
video::ITexture * last_mask { nullptr }
u8 index
Detailed Description
Definition at line 24 of file interlaced.h.
Member Function Documentation
run()
void InitInterlacedMaskStep::run (PipelineContext & context) virtual
Runs the step. This method is invoked by the pipeline.
Implements RenderStep.
Definition at line 32 of file interlaced.cpp.
References irr::video::ITexture::getSize(), TextureBuffer::getTexture(), irr::video::ITexture::lock(), and irr::video::ITexture::unlock().
The documentation for this class was generated from the following files:
src/client/render/interlaced.h
src/client/render/interlaced.cpp