Three Cubes Game: irr::video::CNullDriver Class Reference
irr::video::CNullDriver Class Reference
Classes
struct SDummyTexture
struct SHWBufferLink
struct SMaterialRenderer
struct SOccQuery
struct SSurface
Public Member Functions
CNullDriver (io::IFileSystem *io, const core::dimension2d< u32 > &screenSize)
constructor
virtual ~CNullDriver ()
destructor
virtual bool beginScene (u16 clearFlag, SColor clearColor=SColor(255, 0, 0, 0), f32 clearDepth=1.f, u8 clearStencil=0, const SExposedVideoData &videoData=SExposedVideoData(), core::rect< s32 > *sourceRect=0) override
Applications must call this method before performing any rendering.
bool endScene () override
Presents the rendered image to the screen.
void disableFeature (E_VIDEO_DRIVER_FEATURE feature, bool flag=true) override
Disable a feature of the driver.
bool queryFeature (E_VIDEO_DRIVER_FEATURE feature) const override
queries the features of the driver, returns true if feature is available
const io::IAttributes & getDriverAttributes () const override
Get attributes of the actual video driver.
void setTransform (E_TRANSFORMATION_STATE state, const core::matrix4 &mat) override
sets transformation
u32 getImageLoaderCount () const override
Retrieve the number of image loaders.
IImageLoader * getImageLoader (u32 n) override
Retrieve the given image loader.
u32 getImageWriterCount () const override
Retrieve the number of image writers.
IImageWriter * getImageWriter (u32 n) override
Retrieve the given image writer.
void setMaterial (const SMaterial &material) override
sets a material
ITexture * getTexture (const io::path &filename) override
loads a Texture
ITexture * getTexture (io::IReadFile *file) override
loads a Texture
ITexture * getTextureByIndex (u32 index) override
Returns a texture by index.
u32 getTextureCount () const override
Returns amount of textures currently loaded.
void renameTexture (ITexture *texture, const io::path &newName) override
Renames a texture.
ITexture * addTexture (const core::dimension2d< u32 > &size, const io::path &name, ECOLOR_FORMAT format=ECF_A8R8G8B8) override
Creates an empty texture of specified size.
ITexture * addTexture (const io::path &name, IImage *image) override
Creates a texture from an IImage.
virtual ITexture * addTextureCubemap (const io::path &name, IImage *imagePosX, IImage *imageNegX, IImage *imagePosY, IImage *imageNegY, IImage *imagePosZ, IImage *imageNegZ) override
Creates a cubemap texture from loaded IImages.
ITexture * addTextureCubemap (const irr::u32 sideLen, const io::path &name, ECOLOR_FORMAT format=ECF_A8R8G8B8) override
Creates an empty cubemap texture of specified size.
virtual bool setRenderTargetEx (IRenderTarget *target, u16 clearFlag, SColor clearColor=SColor(255, 0, 0, 0), f32 clearDepth=1.f, u8 clearStencil=0) override
Set a render target.
virtual bool setRenderTarget (ITexture *texture, u16 clearFlag, SColor clearColor=SColor(255, 0, 0, 0), f32 clearDepth=1.f, u8 clearStencil=0) override
Sets a new render target.
void setViewPort (const core::rect< s32 > &area) override
sets a viewport
const core::rect< s32 > & getViewPort () const override
gets the area of the current viewport
virtual void drawVertexPrimitiveList (const void *vertices, u32 vertexCount, const void *indexList, u32 primitiveCount, E_VERTEX_TYPE vType=EVT_STANDARD, scene::E_PRIMITIVE_TYPE pType=scene::EPT_TRIANGLES, E_INDEX_TYPE iType=EIT_16BIT) override
draws a vertex primitive list
virtual void draw2DVertexPrimitiveList (const void *vertices, u32 vertexCount, const void *indexList, u32 primitiveCount, E_VERTEX_TYPE vType=EVT_STANDARD, scene::E_PRIMITIVE_TYPE pType=scene::EPT_TRIANGLES, E_INDEX_TYPE iType=EIT_16BIT) override
draws a vertex primitive list in 2d
virtual void draw3DLine (const core::vector3df &start, const core::vector3df &end, SColor color=SColor(255, 255, 255, 255)) override
Draws a 3d line.
virtual void draw3DTriangle (const core::triangle3df &triangle, SColor color=SColor(255, 255, 255, 255))
virtual void draw3DBox (const core::aabbox3d< f32 > &box, SColor color=SColor(255, 255, 255, 255)) override
Draws a 3d axis aligned box.
void draw2DImage (const video::ITexture *texture, const core::position2d< s32 > &destPos, bool useAlphaChannelOfTexture) override
draws an 2d image
virtual void draw2DImageBatch (const video::ITexture *texture, const core::position2d< s32 > &pos, const core::array< core::rect< s32 > > &sourceRects, const core::array< s32 > &indices, s32 kerningWidth=0, const core::rect< s32 > *clipRect=0, SColor color=SColor(255, 255, 255, 255), bool useAlphaChannelOfTexture=false)
draws a set of 2d images, using a color and the alpha
virtual void draw2DImageBatch (const video::ITexture *texture, const core::array< core::position2d< s32 > > &positions, const core::array< core::rect< s32 > > &sourceRects, const core::rect< s32 > *clipRect=0, SColor color=SColor(255, 255, 255, 255), bool useAlphaChannelOfTexture=false) override
Draws a set of 2d images, using a color and the alpha channel of the texture.
virtual void draw2DImage (const video::ITexture *texture, const core::position2d< s32 > &destPos, const core::rect< s32 > &sourceRect, const core::rect< s32 > *clipRect=0, SColor color=SColor(255, 255, 255, 255), bool useAlphaChannelOfTexture=false) override
Draws a 2d image, using a color (if color is other then Color(255,255,255,255)) and the alpha channel of the texture if wanted.
virtual void draw2DImage (const video::ITexture *texture, const core::rect< s32 > &destRect, const core::rect< s32 > &sourceRect, const core::rect< s32 > *clipRect=0, const video::SColor *const colors=0, bool useAlphaChannelOfTexture=false) override
Draws a part of the texture into the rectangle.
void draw2DRectangle (SColor color, const core::rect< s32 > &pos, const core::rect< s32 > *clip=0) override
Draws a 2d rectangle.
virtual void draw2DRectangle (const core::rect< s32 > &pos, SColor colorLeftUp, SColor colorRightUp, SColor colorLeftDown, SColor colorRightDown, const core::rect< s32 > *clip=0) override
Draws a 2d rectangle with a gradient.
virtual void draw2DRectangleOutline (const core::recti &pos, SColor color=SColor(255, 255, 255, 255))
Draws the outline of a 2d rectangle.
virtual void draw2DLine (const core::position2d< s32 > &start, const core::position2d< s32 > &end, SColor color=SColor(255, 255, 255, 255)) override
Draws a 2d line.
virtual void drawPixel (u32 x, u32 y, const SColor &color)
Draws a pixel.
virtual void draw2DPolygon (core::position2d< s32 > center, f32 radius, video::SColor Color, s32 vertexCount)
Draws a non filled concyclic reqular 2d polygon.
virtual void setFog (SColor color=SColor(0, 255, 255, 255), E_FOG_TYPE fogType=EFT_FOG_LINEAR, f32 start=50.0f, f32 end=100.0f, f32 density=0.01f, bool pixelFog=false, bool rangeFog=false) override
Sets the fog mode.
virtual void getFog (SColor &color, E_FOG_TYPE &fogType, f32 &start, f32 &end, f32 &density, bool &pixelFog, bool &rangeFog) override
Gets the fog mode.
ECOLOR_FORMAT getColorFormat () const override
get color format of the current color buffer
const core::dimension2d< u32 > & getScreenSize () const override
get screen size
IRenderTarget * getCurrentRenderTarget () const
get current render target
const core::dimension2d< u32 > & getCurrentRenderTargetSize () const override
get render target size
s32 getFPS () const override
Returns current frames per second value.
u32 getPrimitiveCountDrawn (u32 param=0) const override
const wchar_t * getName () const override
void setAmbientLight (const SColorf &color) override
const SColorf & getAmbientLight () const override
Get the global ambient light currently used by the driver.
void addExternalImageLoader (IImageLoader *loader) override
Adds an external image loader to the engine.
void addExternalImageWriter (IImageWriter *writer) override
Adds an external image writer to the engine.
virtual void drawStencilShadowVolume (const core::array< core::vector3df > &triangles, bool zfail=true, u32 debugDataVisible=0)
virtual void drawStencilShadow (bool clearStencilBuffer=false, video::SColor leftUpEdge=video::SColor(0, 0, 0, 0), video::SColor rightUpEdge=video::SColor(0, 0, 0, 0), video::SColor leftDownEdge=video::SColor(0, 0, 0, 0), video::SColor rightDownEdge=video::SColor(0, 0, 0, 0))
void removeTexture (ITexture *texture) override
void removeAllTextures () override
virtual ITexture * addRenderTargetTexture (const core::dimension2d< u32 > &size, const io::path &name, const ECOLOR_FORMAT format=ECF_UNKNOWN) override
Creates a render target texture.
ITexture * addRenderTargetTextureCubemap (const irr::u32 sideLen, const io::path &name, const ECOLOR_FORMAT format) override
Creates a render target texture for a cubemap.
void makeColorKeyTexture (video::ITexture *texture, video::SColor color, bool zeroTexels) const override
Creates an 1bit alpha channel of the texture based of an color key.
virtual void makeColorKeyTexture (video::ITexture *texture, core::position2d< s32 > colorKeyPixelPos, bool zeroTexels) const override
Creates an 1bit alpha channel of the texture based of an color key position.
u32 getMaximalPrimitiveCount () const override
void setTextureCreationFlag (E_TEXTURE_CREATION_FLAG flag, bool enabled) override
Enables or disables a texture creation flag.
bool getTextureCreationFlag (E_TEXTURE_CREATION_FLAG flag) const override
Returns if a texture creation flag is enabled or disabled.
IImage * createImageFromFile (const io::path &filename) override
Creates a software image from a file.
IImage * createImageFromFile (io::IReadFile *file) override
Creates a software image from a file.
virtual IImage * createImageFromData (ECOLOR_FORMAT format, const core::dimension2d< u32 > &size, void *data, bool ownForeignMemory=false, bool deleteMemory=true) override
Creates a software image from a byte array.
IImage * createImage (ECOLOR_FORMAT format, const core::dimension2d< u32 > &size) override
Creates an empty software image.
IImage * createImage (ECOLOR_FORMAT format, IImage *imageToCopy) override
Creates a software image from another image.
virtual IImage * createImage (IImage *imageToCopy, const core::position2d< s32 > &pos, const core::dimension2d< u32 > &size) override
Creates a software image from part of another image.
virtual IImage * createImage (ITexture *texture, const core::position2d< s32 > &pos, const core::dimension2d< u32 > &size) override
Creates a software image from part of a texture.
void drawMeshBuffer (const scene::IMeshBuffer *mb) override
Draws a mesh buffer.
virtual void drawMeshBufferNormals (const scene::IMeshBuffer *mb, f32 length=10.f, SColor color=0xffffffff) override
Draws the normals of a mesh buffer.
bool queryTextureFormat (ECOLOR_FORMAT format) const override
Check if the driver supports creating textures with the given color format.
void removeHardwareBuffer (const scene::IMeshBuffer *mb) override
Remove hardware buffer.
void removeAllHardwareBuffers () override
Remove all hardware buffers.
virtual void updateAllHardwareBuffers ()
Update all hardware buffers, remove unused ones.
virtual bool isHardwareBufferRecommend (const scene::IMeshBuffer *mb)
is vbo recommended on this mesh?
virtual void addOcclusionQuery (scene::ISceneNode *node, const scene::IMesh *mesh=0) override
Create occlusion query.
void removeOcclusionQuery (scene::ISceneNode *node) override
Remove occlusion query.
void removeAllOcclusionQueries () override
Remove all occlusion queries.
void runOcclusionQuery (scene::ISceneNode *node, bool visible=false) override
Run occlusion query. Draws mesh stored in query.
void runAllOcclusionQueries (bool visible=false) override
Run all occlusion queries. Draws all meshes stored in queries.
void updateOcclusionQuery (scene::ISceneNode *node, bool block=true) override
Update occlusion query. Retrieves results from GPU.
void updateAllOcclusionQueries (bool block=true) override
Update all occlusion queries. Retrieves results from GPU.
u32 getOcclusionQueryResult (scene::ISceneNode *node) const override
Return query result.
IRenderTarget * addRenderTarget () override
Create render target.
void removeRenderTarget (IRenderTarget *renderTarget) override
Remove render target.
void removeAllRenderTargets () override
Remove all render targets.
void OnResize (const core::dimension2d< u32 > &size) override
Only used by the engine internally.
virtual s32 addMaterialRenderer (IMaterialRenderer *renderer, const char *name=0) override
Adds a new material renderer to the video device.
const SExposedVideoData & getExposedVideoData () override
Returns driver and operating system specific data about the IVideoDriver.
E_DRIVER_TYPE getDriverType () const override
Returns type of video driver.
const core::matrix4 & getTransform (E_TRANSFORMATION_STATE state) const override
Returns the transformation set by setTransform.
IGPUProgrammingServices * getGPUProgrammingServices () override
Returns pointer to the IGPUProgrammingServices interface.
virtual s32 addShaderMaterial (const c8 *vertexShaderProgram=0, const c8 *pixelShaderProgram=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0) override
virtual s32 addShaderMaterialFromFiles (io::IReadFile *vertexShaderProgram=0, io::IReadFile *pixelShaderProgram=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0) override
virtual s32 addShaderMaterialFromFiles (const io::path &vertexShaderProgramFileName, const io::path &pixelShaderProgramFileName, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0) override
IMaterialRenderer * getMaterialRenderer (u32 idx) const override
Returns pointer to material renderer or null.
u32 getMaterialRendererCount () const override
Returns amount of currently available material renderers.
const char * getMaterialRendererName (u32 idx) const override
Returns name of the material renderer.
virtual s32 addHighLevelShaderMaterial (const c8 *vertexShaderProgram, const c8 *vertexShaderEntryPointName=0, E_VERTEX_SHADER_TYPE vsCompileTarget=EVST_VS_1_1, const c8 *pixelShaderProgram=0, const c8 *pixelShaderEntryPointName=0, E_PIXEL_SHADER_TYPE psCompileTarget=EPST_PS_1_1, const c8 *geometryShaderProgram=0, const c8 *geometryShaderEntryPointName="main", E_GEOMETRY_SHADER_TYPE gsCompileTarget=EGST_GS_4_0, scene::E_PRIMITIVE_TYPE inType=scene::EPT_TRIANGLES, scene::E_PRIMITIVE_TYPE outType=scene::EPT_TRIANGLE_STRIP, u32 verticesOut=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0) override
Adds a new material renderer to the VideoDriver, based on a high level shading language.
virtual s32 addHighLevelShaderMaterialFromFiles (const io::path &vertexShaderProgramFile, const c8 *vertexShaderEntryPointName="main", E_VERTEX_SHADER_TYPE vsCompileTarget=EVST_VS_1_1, const io::path &pixelShaderProgramFile="", const c8 *pixelShaderEntryPointName="main", E_PIXEL_SHADER_TYPE psCompileTarget=EPST_PS_1_1, const io::path &geometryShaderProgramFileName="", const c8 *geometryShaderEntryPointName="main", E_GEOMETRY_SHADER_TYPE gsCompileTarget=EGST_GS_4_0, scene::E_PRIMITIVE_TYPE inType=scene::EPT_TRIANGLES, scene::E_PRIMITIVE_TYPE outType=scene::EPT_TRIANGLE_STRIP, u32 verticesOut=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0) override
virtual s32 addHighLevelShaderMaterialFromFiles (io::IReadFile *vertexShaderProgram, const c8 *vertexShaderEntryPointName="main", E_VERTEX_SHADER_TYPE vsCompileTarget=EVST_VS_1_1, io::IReadFile *pixelShaderProgram=0, const c8 *pixelShaderEntryPointName="main", E_PIXEL_SHADER_TYPE psCompileTarget=EPST_PS_1_1, io::IReadFile *geometryShaderProgram=0, const c8 *geometryShaderEntryPointName="main", E_GEOMETRY_SHADER_TYPE gsCompileTarget=EGST_GS_4_0, scene::E_PRIMITIVE_TYPE inType=scene::EPT_TRIANGLES, scene::E_PRIMITIVE_TYPE outType=scene::EPT_TRIANGLE_STRIP, u32 verticesOut=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0) override
scene::IMeshManipulator * getMeshManipulator () override
Returns a pointer to the mesh manipulator.
void clearBuffers (u16 flag, SColor color=SColor(255, 0, 0, 0), f32 depth=1.f, u8 stencil=0) override
Clear the color, depth and/or stencil buffers.
IImage * createScreenShot (video::ECOLOR_FORMAT format=video::ECF_UNKNOWN, video::E_RENDER_TARGET target=video::ERT_FRAME_BUFFER) override
Returns an image created from the last rendered frame.
bool writeImageToFile (IImage *image, const io::path &filename, u32 param=0) override
Writes the provided image to disk file.
bool writeImageToFile (IImage *image, io::IWriteFile *file, u32 param=0) override
Writes the provided image to a file.
void setMaterialRendererName (u32 idx, const char *name) override
Sets the name of a material renderer.
void swapMaterialRenderers (u32 idx1, u32 idx2, bool swapNames) override
Swap the material renderers used for certain id's.
video::ITexture * findTexture (const io::path &filename) override
looks if the image is already loaded
bool setClipPlane (u32 index, const core::plane3df &plane, bool enable=false) override
void enableClipPlane (u32 index, bool enable) override
Enable/disable a clipping plane.
core::stringc getVendorInfo () override
Returns the graphics card vendor name.
void setMinHardwareBufferVertexCount (u32 count) override
Set the minimum number of vertices for which a hw buffer will be created.
SOverrideMaterial & getOverrideMaterial () override
Get the global Material, which might override local materials.
SMaterial & getMaterial2D () override
Get the 2d override material for altering its values.
void enableMaterial2D (bool enable=true) override
Enable the 2d override material.
void setAllowZWriteOnTransparent (bool flag) override
Only used by the engine internally.
core::dimension2du getMaxTextureSize () const override
Returns the maximum texture size supported.
bool needsTransparentRenderPass (const irr::video::SMaterial &material) const override
Used by some SceneNodes to check if a material should be rendered in the transparent render pass.
virtual void convertColor (const void *sP, ECOLOR_FORMAT sF, s32 sN, void *dP, ECOLOR_FORMAT dF) const override
Color conversion convenience function.
virtual ITexture * createRenderTargetTexture (const core::dimension2d< u32 > &size, const c8 *name=0)
deprecated method
bool checkDriverReset () override
Check if the driver was recently reset.
Public Member Functions inherited from irr::video::IVideoDriver
bool beginScene (bool backBuffer, bool zBuffer, SColor color=SColor(255, 0, 0, 0), const SExposedVideoData &videoData=SExposedVideoData(), core::rect< s32 > *sourceRect=0)
Alternative beginScene implementation. Can't clear stencil buffer, but otherwise identical to other beginScene.
_IRR_DEPRECATED_ ITexture * addTexture (const io::path &name, IImage *image, void *mipmapData)
Creates a texture from an IImage.
bool setRenderTarget (ITexture *texture, bool clearBackBuffer, bool clearZBuffer, SColor color=SColor(255, 0, 0, 0))
void drawIndexedTriangleList (const S3DVertex *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle list.
void drawIndexedTriangleList (const S3DVertex2TCoords *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle list.
void drawIndexedTriangleList (const S3DVertexTangents *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle list.
void drawIndexedTriangleFan (const S3DVertex *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle fan.
void drawIndexedTriangleFan (const S3DVertex2TCoords *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle fan.
void drawIndexedTriangleFan (const S3DVertexTangents *vertices, u32 vertexCount, const u16 *indexList, u32 triangleCount)
Draws an indexed triangle fan.
_IRR_DEPRECATED_ void clearBuffers (bool backBuffer, bool depthBuffer, bool stencilBuffer, SColor color)
Clear the color, depth and/or stencil buffers.
void clearZBuffer ()
Clears the ZBuffer.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::video::IGPUProgrammingServices
virtual ~IGPUProgrammingServices ()
Destructor.
s32 addHighLevelShaderMaterial (const c8 *vertexShaderProgram, const c8 *vertexShaderEntryPointName="main", E_VERTEX_SHADER_TYPE vsCompileTarget=EVST_VS_1_1, const c8 *pixelShaderProgram=0, const c8 *pixelShaderEntryPointName="main", E_PIXEL_SHADER_TYPE psCompileTarget=EPST_PS_1_1, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0)
convenience function for use without geometry shaders
s32 addHighLevelShaderMaterial (const c8 *vertexShaderProgram, const c8 *pixelShaderProgram=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0)
convenience function for use with many defaults, without geometry shader
s32 addHighLevelShaderMaterial (const c8 *vertexShaderProgram, const c8 *pixelShaderProgram=0, const c8 *geometryShaderProgram=0, scene::E_PRIMITIVE_TYPE inType=scene::EPT_TRIANGLES, scene::E_PRIMITIVE_TYPE outType=scene::EPT_TRIANGLE_STRIP, u32 verticesOut=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0)
convenience function for use with many defaults, with geometry shader
s32 addHighLevelShaderMaterialFromFiles (const io::path &vertexShaderProgramFileName, const c8 *vertexShaderEntryPointName="main", E_VERTEX_SHADER_TYPE vsCompileTarget=EVST_VS_1_1, const io::path &pixelShaderProgramFileName="", const c8 *pixelShaderEntryPointName="main", E_PIXEL_SHADER_TYPE psCompileTarget=EPST_PS_1_1, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0)
convenience function for use without geometry shaders
s32 addHighLevelShaderMaterialFromFiles (const io::path &vertexShaderProgramFileName, const io::path &pixelShaderProgramFileName="", IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0)
convenience function for use with many defaults, without geometry shader
s32 addHighLevelShaderMaterialFromFiles (const io::path &vertexShaderProgramFileName, const io::path &pixelShaderProgramFileName="", const io::path &geometryShaderProgramFileName="", scene::E_PRIMITIVE_TYPE inType=scene::EPT_TRIANGLES, scene::E_PRIMITIVE_TYPE outType=scene::EPT_TRIANGLE_STRIP, u32 verticesOut=0, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0)
convenience function for use with many defaults, with geometry shader
s32 addHighLevelShaderMaterialFromFiles (io::IReadFile *vertexShaderProgram, const c8 *vertexShaderEntryPointName="main", E_VERTEX_SHADER_TYPE vsCompileTarget=EVST_VS_1_1, io::IReadFile *pixelShaderProgram=0, const c8 *pixelShaderEntryPointName="main", E_PIXEL_SHADER_TYPE psCompileTarget=EPST_PS_1_1, IShaderConstantSetCallBack *callback=0, E_MATERIAL_TYPE baseMaterial=video::EMT_SOLID, s32 userData=0)
convenience function for use without geometry shaders
Protected Member Functions
virtual SHWBufferLink * getBufferLink (const scene::IMeshBuffer *mb)
Gets hardware buffer link from a meshbuffer (may create or update buffer)
virtual bool updateHardwareBuffer (SHWBufferLink *HWBuffer)
updates hardware buffer if needed (only some drivers can)
virtual void drawHardwareBuffer (SHWBufferLink *HWBuffer)
Draw hardware buffer (only some drivers can)
virtual void deleteHardwareBuffer (SHWBufferLink *HWBuffer)
Delete hardware buffer.
virtual SHWBufferLink * createHardwareBuffer (const scene::IMeshBuffer *mb)
Create hardware buffer from mesh (only some drivers can)
void deleteAllTextures ()
deletes all textures
ITexture * loadTextureFromFile (io::IReadFile *file, const io::path &hashName="")
opens the file and loads it into the surface
void addTexture (ITexture *surface)
adds a surface, not loaded or created by the Irrlicht Engine
virtual ITexture * createDeviceDependentTexture (const io::path &name, IImage *image)
virtual ITexture * createDeviceDependentTextureCubemap (const io::path &name, const core::array< IImage * > &image)
bool checkPrimitiveCount (u32 prmcnt) const
checks triangle count and print warning if wrong
bool checkImage (IImage *image) const
bool checkImage (const core::array< IImage * > &image) const
s32 addAndDropMaterialRenderer (IMaterialRenderer *m)
void deleteMaterialRenders ()
deletes all material renderers
void printVersion ()
bool getWriteZBuffer (const SMaterial &material) const
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
core::array< SSurface > Textures
core::array< SOccQuery > OcclusionQueries
core::array< IRenderTarget * > RenderTargets
IRenderTarget * SharedRenderTarget
core::array< ITexture * > SharedDepthTextures
IRenderTarget * CurrentRenderTarget
core::dimension2d< u32 > CurrentRenderTargetSize
core::array< video::IImageLoader * > SurfaceLoader
core::array< video::IImageWriter * > SurfaceWriter
core::array< SMaterialRenderer > MaterialRenderers
std::list< SHWBufferLink * > HWBufferList
io::IFileSystem * FileSystem
scene::IMeshManipulator * MeshManipulator
mesh manipulator
core::rect< s32 > ViewPort
core::dimension2d< u32 > ScreenSize
core::matrix4 TransformationMatrix
CFPSCounter FPSCounter
u32 PrimitivesDrawn
u32 MinVertexCountForVBO
u32 TextureCreationFlags
f32 FogStart
f32 FogEnd
f32 FogDensity
SColor FogColor
SExposedVideoData ExposedData
io::IAttributes * DriverAttributes
SOverrideMaterial OverrideMaterial
SMaterial OverrideMaterial2D
SMaterial InitMaterial2D
bool OverrideMaterial2DEnabled
E_FOG_TYPE FogType
bool PixelFog
bool RangeFog
bool AllowZWriteOnTransparent
bool FeatureEnabled [video::EVDF_COUNT]
SColorf AmbientLight
Detailed Description
Definition at line 35 of file CNullDriver.h.
Member Function Documentation
addExternalImageLoader()
void irr::video::CNullDriver::addExternalImageLoader (IImageLoader * loader) override virtual
Adds an external image loader to the engine.
Adds an external surface loader to the engine.
Implements irr::video::IVideoDriver.
Definition at line 148 of file CNullDriver.cpp.
addExternalImageWriter()
void irr::video::CNullDriver::addExternalImageWriter (IImageWriter * writer) override virtual
Adds an external image writer to the engine.
Adds an external surface writer to the engine.
Implements irr::video::IVideoDriver.
Definition at line 159 of file CNullDriver.cpp.
References irr::IReferenceCounted::grab().
addHighLevelShaderMaterial()
s32 irr::video::CNullDriver::addHighLevelShaderMaterial (const c8 * vertexShaderProgram, const c8 * vertexShaderEntryPointName = 0, E_VERTEX_SHADER_TYPE vsCompileTarget = EVST_VS_1_1, const c8 * pixelShaderProgram = 0, const c8 * pixelShaderEntryPointName = 0, E_PIXEL_SHADER_TYPE psCompileTarget = EPST_PS_1_1, const c8 * geometryShaderProgram = 0, const c8 * geometryShaderEntryPointName = "main", E_GEOMETRY_SHADER_TYPE gsCompileTarget = EGST_GS_4_0, scene::E_PRIMITIVE_TYPE inType = scene::EPT_TRIANGLES, scene::E_PRIMITIVE_TYPE outType = scene::EPT_TRIANGLE_STRIP, u32 verticesOut = 0, IShaderConstantSetCallBack * callback = 0, E_MATERIAL_TYPE baseMaterial = video::EMT_SOLID, s32 userData = 0) override virtual
Adds a new material renderer to the VideoDriver, based on a high level shading language.
Adds a new material renderer to the VideoDriver, based on a high level shading language. Currently only HLSL in D3D9 is supported.
Implements irr::video::IGPUProgrammingServices.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 1739 of file CNullDriver.cpp.
Referenced by addHighLevelShaderMaterialFromFiles().
addHighLevelShaderMaterialFromFiles() [1/2]
s32 irr::video::CNullDriver::addHighLevelShaderMaterialFromFiles (const io::path & vertexShaderProgramFileName, const c8 * vertexShaderEntryPointName = "main", E_VERTEX_SHADER_TYPE vsCompileTarget = EVST_VS_1_1, const io::path & pixelShaderProgramFileName = "", const c8 * pixelShaderEntryPointName = "main", E_PIXEL_SHADER_TYPE psCompileTarget = EPST_PS_1_1, const io::path & geometryShaderProgramFileName = "", const c8 * geometryShaderEntryPointName = "main", E_GEOMETRY_SHADER_TYPE gsCompileTarget = EGST_GS_4_0, scene::E_PRIMITIVE_TYPE inType = scene::EPT_TRIANGLES, scene::E_PRIMITIVE_TYPE outType = scene::EPT_TRIANGLE_STRIP, u32 verticesOut = 0, IShaderConstantSetCallBack * callback = 0, E_MATERIAL_TYPE baseMaterial = video::EMT_SOLID, s32 userData = 0) override virtual
Like IGPUProgrammingServices::addShaderMaterial() (look there for a detailed description), but tries to load the programs from files.
Implements irr::video::IGPUProgrammingServices.
Definition at line 1762 of file CNullDriver.cpp.
References irr::io::IFileSystem::createAndOpenFile(), irr::IReferenceCounted::drop(), irr::ELL_WARNING, and irr::core::string< T >::size().
addHighLevelShaderMaterialFromFiles() [2/2]
s32 irr::video::CNullDriver::addHighLevelShaderMaterialFromFiles (io::IReadFile * vertexShaderProgram, const c8 * vertexShaderEntryPointName = "main", E_VERTEX_SHADER_TYPE vsCompileTarget = EVST_VS_1_1, io::IReadFile * pixelShaderProgram = 0, const c8 * pixelShaderEntryPointName = "main", E_PIXEL_SHADER_TYPE psCompileTarget = EPST_PS_1_1, io::IReadFile * geometryShaderProgram = 0, const c8 * geometryShaderEntryPointName = "main", E_GEOMETRY_SHADER_TYPE gsCompileTarget = EGST_GS_4_0, scene::E_PRIMITIVE_TYPE inType = scene::EPT_TRIANGLES, scene::E_PRIMITIVE_TYPE outType = scene::EPT_TRIANGLE_STRIP, u32 verticesOut = 0, IShaderConstantSetCallBack * callback = 0, E_MATERIAL_TYPE baseMaterial = video::EMT_SOLID, s32 userData = 0) override virtual
Like IGPUProgrammingServices::addShaderMaterial() (look there for a detailed description), but tries to load the programs from files.
Implements irr::video::IGPUProgrammingServices.
Definition at line 1834 of file CNullDriver.cpp.
References addHighLevelShaderMaterial(), irr::io::IReadFile::getSize(), irr::io::IReadFile::read(), and irr::io::IReadFile::seek().
addOcclusionQuery()
void irr::video::CNullDriver::addOcclusionQuery (scene::ISceneNode * node, const scene::IMesh * mesh = 0) override virtual
Create occlusion query.
Use node for identification and mesh for occlusion test.
Implements irr::video::IVideoDriver.
Definition at line 1435 of file CNullDriver.cpp.
References irr::scene::ESNT_ANIMATED_MESH, irr::scene::ESNT_MESH, irr::scene::ISceneNode::getAutomaticCulling(), irr::scene::IAnimatedMeshSceneNode::getMesh(), irr::scene::ISceneNode::getType(), irr::IReferenceCounted::grab(), and irr::scene::ISceneNode::setAutomaticCulling().
addShaderMaterial()
s32 irr::video::CNullDriver::addShaderMaterial (const c8 * vertexShaderProgram = 0, const c8 * pixelShaderProgram = 0, IShaderConstantSetCallBack * callback = 0, E_MATERIAL_TYPE baseMaterial = video::EMT_SOLID, s32 userData = 0) override virtual
Adds a new material renderer to the VideoDriver, using pixel and/or vertex shaders to render geometry.
Implements irr::video::IGPUProgrammingServices.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 1911 of file CNullDriver.cpp.
Referenced by addShaderMaterialFromFiles().
addShaderMaterialFromFiles() [1/2]
s32 irr::video::CNullDriver::addShaderMaterialFromFiles (const io::path & vertexShaderProgramFileName, const io::path & pixelShaderProgramFileName, IShaderConstantSetCallBack * callback = 0, E_MATERIAL_TYPE baseMaterial = video::EMT_SOLID, s32 userData = 0) override virtual
Like IGPUProgrammingServices::addShaderMaterial(), but tries to load the programs from files.
Implements irr::video::IGPUProgrammingServices.
Definition at line 1966 of file CNullDriver.cpp.
References addShaderMaterialFromFiles(), irr::io::IFileSystem::createAndOpenFile(), irr::IReferenceCounted::drop(), irr::ELL_WARNING, and irr::core::string< T >::size().
addShaderMaterialFromFiles() [2/2]
s32 irr::video::CNullDriver::addShaderMaterialFromFiles (io::IReadFile * vertexShaderProgram = 0, io::IReadFile * pixelShaderProgram = 0, IShaderConstantSetCallBack * callback = 0, E_MATERIAL_TYPE baseMaterial = video::EMT_SOLID, s32 userData = 0) override virtual
Like IGPUProgrammingServices::addShaderMaterial(), but tries to load the programs from files.
Implements irr::video::IGPUProgrammingServices.
Definition at line 1924 of file CNullDriver.cpp.
References addShaderMaterial(), irr::io::IReadFile::getSize(), and irr::io::IReadFile::read().
Referenced by addShaderMaterialFromFiles().
addTexture() [1/2]
ITexture * irr::video::CNullDriver::addTexture (const core::dimension2d< u32 > & size, const io::path & name, ECOLOR_FORMAT format = ECF_A8R8G8B8) override virtual
Creates an empty texture of specified size.
Parameters
size Size of the texture.
name A name for the texture. Later calls to getTexture() with this name will return this texture. The name can not be empty.
format Desired color format of the texture. Please note that the driver may choose to create the texture in another color format.
Returns
Pointer to the newly created texture. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implements irr::video::IVideoDriver.
Definition at line 336 of file CNullDriver.cpp.
References irr::IReferenceCounted::drop(), and irr::ELL_WARNING.
Referenced by irr::video::COpenGL3DriverBase::addRenderTargetTexture(), irr::video::COpenGL3DriverBase::addRenderTargetTextureCubemap(), addTexture(), addTextureCubemap(), and getTexture().
addTexture() [2/2]
ITexture * irr::video::CNullDriver::addTexture (const io::path & name, IImage * image) override virtual
Creates a texture from an IImage.
Parameters
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
image Image the texture is created from.
Returns
Pointer to the newly created texture. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implements irr::video::IVideoDriver.
Definition at line 363 of file CNullDriver.cpp.
References addTexture(), irr::IReferenceCounted::drop(), and irr::ELL_WARNING.
addTextureCubemap() [1/2]
ITexture * irr::video::CNullDriver::addTextureCubemap (const io::path & name, IImage * imagePosX, IImage * imageNegX, IImage * imagePosY, IImage * imageNegY, IImage * imagePosZ, IImage * imageNegZ) override virtual
Creates a cubemap texture from loaded IImages.
Parameters
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
imagePosX Image (positive X) the texture is created from.
imageNegX Image (negative X) the texture is created from.
imagePosY Image (positive Y) the texture is created from.
imageNegY Image (negative Y) the texture is created from.
imagePosZ Image (positive Z) the texture is created from.
imageNegZ Image (negative Z) the texture is created from.
Returns
Pointer to the newly created texture. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implements irr::video::IVideoDriver.
Definition at line 390 of file CNullDriver.cpp.
References addTexture(), irr::IReferenceCounted::drop(), and irr::core::array< T >::push_back().
addTextureCubemap() [2/2]
ITexture * irr::video::CNullDriver::addTextureCubemap (const irr::u32 sideLen, const io::path & name, ECOLOR_FORMAT format = ECF_A8R8G8B8) override virtual
Creates an empty cubemap texture of specified size.
Parameters
sideLen diameter of one side of the cube
name A name for the texture. Later calls of getTexture() with this name will return this texture. The name can not be empty.
format Desired color format of the texture. Please note that the driver may choose to create the texture in another color format.
Returns
Pointer to the newly created texture.
Implements irr::video::IVideoDriver.
Definition at line 420 of file CNullDriver.cpp.
References addTexture(), irr::IReferenceCounted::drop(), irr::ELL_WARNING, and irr::core::array< T >::push_back().
beginScene()
bool irr::video::CNullDriver::beginScene (u16 clearFlag, SColor clearColor = SColor(255, 0, 0, 0), f32 clearDepth = 1.f, u8 clearStencil = 0, const SExposedVideoData & videoData = SExposedVideoData(), core::rect< s32 > * sourceRect = 0) override virtual
Applications must call this method before performing any rendering.
This method can clear the back- and the z-buffer.
Parameters
clearFlag A combination of the E_CLEAR_BUFFER_FLAG bit-flags.
clearColor The clear color for the color buffer.
clearDepth The clear value for the depth buffer.
clearStencil The clear value for the stencil buffer.
videoData Handle of another window, if you want the bitmap to be displayed on another window. If this is an empty element, everything will be displayed in the default window. Note: This feature is not fully implemented for all devices.
sourceRect Pointer to a rectangle defining the source rectangle of the area to be presented. Set to null to present everything. Note: not implemented in all devices.
Returns
False if failed.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 223 of file CNullDriver.cpp.
Referenced by irr::video::COpenGL3DriverBase::beginScene().
checkDriverReset()
bool irr::video::CNullDriver::checkDriverReset () inline override virtual
Check if the driver was recently reset.
For d3d devices you will need to recreate the RTTs if the driver was reset. Should be queried right after beginScene().
Implements irr::video::IVideoDriver.
Definition at line 654 of file CNullDriver.h.
convertColor()
void irr::video::CNullDriver::convertColor (const void * sP, ECOLOR_FORMAT sF, s32 sN, void * dP, ECOLOR_FORMAT dF) const override virtual
Color conversion convenience function.
Convert an image (as array of pixels) from source to destination array, thereby converting the color format. The pixel size is determined by the color formats.
Parameters
sP Pointer to source
sF Color format of source
sN Number of pixels to convert, both array must be large enough
dP Pointer to destination
dF Color format of destination
Implements irr::video::IVideoDriver.
Definition at line 2158 of file CNullDriver.cpp.
createImageFromData()
IImage * irr::video::CNullDriver::createImageFromData (ECOLOR_FORMAT format, const core::dimension2d< u32 > & size, void * data, bool ownForeignMemory = false, bool deleteMemory = true) override virtual
Creates a software image from a byte array.
Parameters
useForeignMemory If true, the image will use the data pointer directly and own it from now on, which means it will also try to delete [] the data when the image will be destructed. If false, the memory will by copied.
Implements irr::video::IVideoDriver.
Definition at line 1228 of file CNullDriver.cpp.
createImageFromFile() [1/2]
IImage * irr::video::CNullDriver::createImageFromFile (const io::path & filename) override virtual
Creates a software image from a file.
No hardware texture will be created for this image. This method is useful for example if you want to read a heightmap for a terrain renderer.
Parameters
filename Name of the file from which the image is created.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implements irr::video::IVideoDriver.
Definition at line 1147 of file CNullDriver.cpp.
References irr::io::IFileSystem::createAndOpenFile(), irr::ELL_WARNING, and irr::core::string< T >::size().
Referenced by loadTextureFromFile().
createImageFromFile() [2/2]
IImage * irr::video::CNullDriver::createImageFromFile (io::IReadFile * file) override virtual
Creates a software image from a file.
No hardware texture will be created for this image. This method is useful for example if you want to read a heightmap for a terrain renderer.
Parameters
file File from which the image is created.
Returns
The created image. If you no longer need the image, you should call IImage::drop(). See IReferenceCounted::drop() for more information.
Implements irr::video::IVideoDriver.
Definition at line 1163 of file CNullDriver.cpp.
draw2DImageBatch() [1/2]
void irr::video::CNullDriver::draw2DImageBatch (const video::ITexture * texture, const core::array< core::position2d< s32 > > & positions, const core::array< core::rect< s32 > > & sourceRects, const core::rect< s32 > * clipRect = 0, SColor color = SColor(255,255,255,255), bool useAlphaChannelOfTexture = false) override virtual
Draws a set of 2d images, using a color and the alpha channel of the texture.
All drawings are clipped against clipRect (if != 0). The subtextures are defined by the array of sourceRects and are positioned using the array of positions.
Parameters
texture Texture to be drawn.
pos Array of upper left 2d destinations where the images will be drawn.
sourceRects Source rectangles of the image.
clipRect Pointer to rectangle on the screen where the images are clipped to. If this pointer is 0 then the image is not clipped.
color Color with which the image is drawn. Note that the alpha component is used. If alpha is other than 255, the image will be transparent.
useAlphaChannelOfTexture If true, the alpha channel of the texture is used to draw the image.
draws a set of 2d images, using a color and the alpha channel of the texture if desired.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 737 of file CNullDriver.cpp.
References draw2DImage().
draw2DImageBatch() [2/2]
virtual void irr::video::CNullDriver::draw2DImageBatch (const video::ITexture * texture, const core::position2d< s32 > & pos, const core::array< core::rect< s32 > > & sourceRects, const core::array< s32 > & indices, s32 kerningWidth = 0, const core::rect< s32 > * clipRect = 0, SColor color = SColor(255,255,255,255), bool useAlphaChannelOfTexture = false) inline virtual
draws a set of 2d images, using a color and the alpha
channel of the texture if desired. The images are drawn beginning at pos and concatenated in one line. All drawings are clipped against clipRect (if != 0). The subtextures are defined by the array of sourceRects and are chosen by the indices given.
Parameters
texture Texture to be drawn.
pos Upper left 2d destination position where the image will be drawn.
sourceRects Source rectangles of the image.
indices List of indices which choose the actual rectangle used each time.
kerningWidth offset on position
clipRect Pointer to rectangle on the screen where the image is clipped to. This pointer can be 0. Then the image is not clipped.
color Color with which the image is colored. Note that the alpha component is used: If alpha is other than 255, the image will be transparent.
useAlphaChannelOfTexture If true, the alpha channel of the texture is used to draw the image.
Definition at line 156 of file CNullDriver.h.
draw2DRectangle()
void irr::video::CNullDriver::draw2DRectangle (SColor color, const core::rect< s32 > & pos, const core::rect< s32 > * clip = 0) override virtual
Draws a 2d rectangle.
Draw a 2d rectangle.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 776 of file CNullDriver.cpp.
drawStencilShadow()
virtual void irr::video::CNullDriver::drawStencilShadow (bool clearStencilBuffer = false, video::SColor leftUpEdge = video::SColor(0,0,0,0), video::SColor rightUpEdge = video::SColor(0,0,0,0), video::SColor leftDownEdge = video::SColor(0,0,0,0), video::SColor rightDownEdge = video::SColor(0,0,0,0)) inline virtual
Fills the stencil shadow with color. After the shadow volume has been drawn into the stencil buffer using IVideoDriver::drawStencilShadowVolume(), use this to draw the color of the shadow.
Definition at line 276 of file CNullDriver.h.
drawStencilShadowVolume()
virtual void irr::video::CNullDriver::drawStencilShadowVolume (const core::array< core::vector3df > & triangles, bool zfail = true, u32 debugDataVisible = 0) inline virtual
Draws a shadow volume into the stencil buffer. To draw a stencil shadow, do this: First, draw all geometry. Then use this method, to draw the shadow volume. Then, use IVideoDriver::drawStencilShadow() to visualize the shadow.
Definition at line 270 of file CNullDriver.h.
enableClipPlane()
void irr::video::CNullDriver::enableClipPlane (u32 index, bool enable) override virtual
Enable/disable a clipping plane.
Enable/disable a clipping plane. There are at least 6 clipping planes available for the user to set at will.
Parameters
index The plane index. Must be between 0 and MaxUserClipPlanes.
enable If true, enable the clipping plane else disable it.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 2082 of file CNullDriver.cpp.
endScene()
bool irr::video::CNullDriver::endScene () override virtual
Presents the rendered image to the screen.
Applications must call this method after performing any rendering.
Returns
False if failed and true if succeeded.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 229 of file CNullDriver.cpp.
References irr::os::Timer::getRealTime(), irr::video::CFPSCounter::registerFrame(), updateAllHardwareBuffers(), and updateAllOcclusionQueries().
Referenced by irr::video::COpenGL3DriverBase::endScene().
getColorFormat()
ECOLOR_FORMAT irr::video::CNullDriver::getColorFormat () const override virtual
get color format of the current color buffer
returns color format
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 800 of file CNullDriver.cpp.
References irr::video::ECF_R5G6B5.
getFPS()
s32 irr::video::CNullDriver::getFPS () const override virtual
Returns current frames per second value.
This value is updated approximately every 1.5 seconds and is only intended to provide a rough guide to the average frame rate. It is not suitable for use in performing timing calculations or framerate independent movement.
Returns
Approximate amount of frames per second drawn.
Implements irr::video::IVideoDriver.
Definition at line 830 of file CNullDriver.cpp.
References irr::video::CFPSCounter::getFPS().
getMaximalPrimitiveCount()
u32 irr::video::CNullDriver::getMaximalPrimitiveCount () const override virtual
Returns the maximum amount of primitives (mostly vertices) which the device is able to render with one drawIndexedTriangleList call.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 1012 of file CNullDriver.cpp.
Referenced by checkPrimitiveCount().
getName()
const wchar_t * irr::video::CNullDriver::getName () const override virtual
Returns
Returns the name of the video driver. Example: In case of the DIRECT3D8 driver, it would return "Direct3D8.1".
Returns the name of the video driver. Example: In case of the DIRECT3D8 driver, it would return "Direct3D8".
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 862 of file CNullDriver.cpp.
getOcclusionQueryResult()
u32 irr::video::CNullDriver::getOcclusionQueryResult (scene::ISceneNode * node) const override virtual
Return query result.
Return value is the number of visible pixels/fragments. The value is a safe approximation, i.e. can be larger than the actual value of pixels.
Return value is the number of visible pixels/fragments. The value is a safe approximation, i.e. can be larger then the actual value of pixels.
Implements irr::video::IVideoDriver.
Definition at line 1564 of file CNullDriver.cpp.
getOverrideMaterial()
SOverrideMaterial & irr::video::CNullDriver::getOverrideMaterial () override virtual
Get the global Material, which might override local materials.
Depending on the enable flags, values from this Material are used to override those of local materials of some meshbuffer being rendered.
Implements irr::video::IVideoDriver.
Definition at line 2104 of file CNullDriver.cpp.
getPrimitiveCountDrawn()
u32 irr::video::CNullDriver::getPrimitiveCountDrawn (u32 param = 0) const override virtual
returns amount of primitives (mostly triangles) were drawn in the last frame. very useful method for statistics.
Implements irr::video::IVideoDriver.
Definition at line 839 of file CNullDriver.cpp.
References irr::video::CFPSCounter::getPrimitive(), irr::video::CFPSCounter::getPrimitiveAverage(), and irr::video::CFPSCounter::getPrimitiveTotal().
getScreenSize()
const core::dimension2d< u32 > & irr::video::CNullDriver::getScreenSize () const override virtual
get screen size
returns screen size
Implements irr::video::IVideoDriver.
Definition at line 807 of file CNullDriver.cpp.
makeColorKeyTexture() [1/2]
void irr::video::CNullDriver::makeColorKeyTexture (video::ITexture * texture, core::position2d< s32 > colorKeyPixelPos, bool zeroTexels) const override virtual
Creates an 1bit alpha channel of the texture based of an color key position.
Creates an boolean alpha channel of the texture based of an color key position.
Implements irr::video::IVideoDriver.
Definition at line 958 of file CNullDriver.cpp.
References irr::video::A1R5G5B5toA8R8G8B8(), irr::video::ECF_A1R5G5B5, irr::video::ECF_A8R8G8B8, irr::ELL_ERROR, irr::video::ETLM_READ_ONLY, irr::video::ITexture::getColorFormat(), irr::video::ITexture::getPitch(), irr::video::ITexture::lock(), makeColorKeyTexture(), and irr::video::ITexture::unlock().
makeColorKeyTexture() [2/2]
void irr::video::CNullDriver::makeColorKeyTexture (video::ITexture * texture, video::SColor color, bool zeroTexels) const override virtual
Creates an 1bit alpha channel of the texture based of an color key.
Creates a boolean alpha channel of the texture based of an color key.
Implements irr::video::IVideoDriver.
Definition at line 869 of file CNullDriver.cpp.
References irr::video::SColor::color, irr::video::ECF_A1R5G5B5, irr::video::ECF_A8R8G8B8, irr::ELL_ERROR, irr::video::ITexture::getColorFormat(), irr::video::ITexture::getPitch(), irr::video::ITexture::getSize(), irr::core::dimension2d< T >::Height, irr::video::ITexture::lock(), irr::video::ITexture::regenerateMipMapLevels(), irr::video::SColor::toA1R5G5B5(), and irr::video::ITexture::unlock().
Referenced by makeColorKeyTexture().
OnResize()
void irr::video::CNullDriver::OnResize (const core::dimension2d< u32 > & size) override virtual
Only used by the engine internally.
Used to notify the driver that the window was resized.
Only used by the internal engine. Used to notify the driver that the window was resized.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 1610 of file CNullDriver.cpp.
References irr::core::rect< T >::getHeight(), irr::core::rect< T >::getWidth(), irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
Referenced by irr::video::COpenGL3DriverBase::OnResize().
removeAllTextures()
void irr::video::CNullDriver::removeAllTextures () override virtual
Removes all texture from the texture cache and deletes them, freeing lot of memory.
Implements irr::video::IVideoDriver.
Definition at line 299 of file CNullDriver.cpp.
References deleteAllTextures(), and setMaterial().
removeTexture()
void irr::video::CNullDriver::removeTexture (ITexture * texture) override virtual
Removes a texture from the texture cache and deletes it, freeing lot of memory.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 280 of file CNullDriver.cpp.
References irr::IReferenceCounted::drop().
Referenced by irr::video::COpenGL3DriverBase::removeTexture().
runAllOcclusionQueries()
void irr::video::CNullDriver::runAllOcclusionQueries (bool visible = false) override virtual
Run all occlusion queries. Draws all meshes stored in queries.
If the meshes shall not be rendered visible, use overrideMaterial to disable the color and depth buffer.
Implements irr::video::IVideoDriver.
Definition at line 1528 of file CNullDriver.cpp.
References runOcclusionQuery().
runOcclusionQuery()
void irr::video::CNullDriver::runOcclusionQuery (scene::ISceneNode * node, bool visible = false) override virtual
Run occlusion query. Draws mesh stored in query.
If the mesh shall not be rendered visible, use overrideMaterial to disable the color and depth buffer.
If the mesh shall be rendered visible, use flag to enable the proper material setting.
Implements irr::video::IVideoDriver.
Definition at line 1496 of file CNullDriver.cpp.
References irr::video::SMaterial::AntiAliasing, irr::video::SMaterial::ColorMask, drawMeshBuffer(), irr::video::ECP_NONE, irr::video::ETS_WORLD, irr::video::EZW_OFF, irr::scene::ISceneNode::getAbsoluteTransformation(), irr::scene::IMeshBuffer::getMaterial(), irr::scene::IMesh::getMeshBuffer(), irr::scene::IMesh::getMeshBufferCount(), irr::video::SMaterial::GouraudShading, irr::video::SMaterial::Lighting, setMaterial(), setTransform(), and irr::video::SMaterial::ZWriteEnable.
Referenced by runAllOcclusionQueries().
setAmbientLight()
void irr::video::CNullDriver::setAmbientLight (const SColorf & color) override virtual
Sets the dynamic ambient light color. The default color is (0,0,0,0) which means it is dark.
Parameters
color New color of the ambient light.
Implements irr::video::IVideoDriver.
Definition at line 849 of file CNullDriver.cpp.
Referenced by irr::video::COpenGL3DriverBase::genericDriverInit().
setClipPlane()
bool irr::video::CNullDriver::setClipPlane (u32 index, const core::plane3df & plane, bool enable = false) override virtual
Set/unset a clipping plane. There are at least 6 clipping planes available for the user to set at will.
Parameters
index The plane index. Must be between 0 and MaxUserClipPlanes.
plane The plane itself.
enable If true, enable the clipping plane else disable it.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 2075 of file CNullDriver.cpp.
setMinHardwareBufferVertexCount()
void irr::video::CNullDriver::setMinHardwareBufferVertexCount (u32 count) override virtual
Set the minimum number of vertices for which a hw buffer will be created.
Parameters
count Number of vertices to set as minimum.
Implements irr::video::IVideoDriver.
Definition at line 2098 of file CNullDriver.cpp.
setRenderTarget()
bool irr::video::CNullDriver::setRenderTarget (ITexture * texture, u16 clearFlag, SColor clearColor = SColor(255, 0, 0, 0), f32 clearDepth = 1.f, u8 clearStencil = 0) override virtual
Sets a new render target.
This will only work if the driver supports the EVDF_RENDER_TO_TARGET feature, which can be queried with queryFeature(). Usually, rendering to textures is done in this way:
// create render target
ITexture* target = driver->addRenderTargetTexture(core::dimension2d<u32>(128,128), "rtt1");
// ...
driver->setRenderTarget(target); // set render target
// .. draw stuff here
driver->setRenderTarget(0); // set previous render target
Please note that you cannot render 3D or 2D geometry with a render target as texture on it when you are rendering the scene into this render target at the same time. It is usually only possible to render into a texture between the IVideoDriver::beginScene() and endScene() method calls.
Parameters
texture New render target. Must be a texture created with IVideoDriver::addRenderTargetTexture(). If set to nullptr, it makes the window the current render target.
clearFlag A combination of the E_CLEAR_BUFFER_FLAG bit-flags.
clearColor The clear color for the color buffer.
clearDepth The clear value for the depth buffer.
clearStencil The clear value for the stencil buffer.
Returns
True if successful and false if not.
Implements irr::video::IVideoDriver.
Definition at line 620 of file CNullDriver.cpp.
References addRenderTarget(), addRenderTargetTexture(), irr::video::ECF_D24S8, irr::video::ITexture::getSize(), setRenderTargetEx(), and irr::video::IRenderTarget::setTexture().
setRenderTargetEx()
bool irr::video::CNullDriver::setRenderTargetEx (IRenderTarget * target, u16 clearFlag, SColor clearColor = SColor(255, 0, 0, 0), f32 clearDepth = 1.f, u8 clearStencil = 0) override virtual
Set a render target.
This will only work if the driver supports the EVDF_RENDER_TO_TARGET feature, which can be queried with queryFeature(). Please note that you cannot render 3D or 2D geometry with a render target as texture on it when you are rendering the scene into this render target at the same time. It is usually only possible to render into a texture between the IVideoDriver::beginScene() and endScene() method calls. If you need the best performance use this method instead of setRenderTarget.
Parameters
target Render target object. If set to nullptr, it makes the window the current render target.
clearFlag A combination of the E_CLEAR_BUFFER_FLAG bit-flags.
clearColor The clear color for the color buffer.
clearDepth The clear value for the depth buffer.
clearStencil The clear value for the stencil buffer.
Returns
True if successful and false if not.
Implements irr::video::IVideoDriver.
Reimplemented in irr::video::COpenGL3DriverBase.
Definition at line 615 of file CNullDriver.cpp.
Referenced by setRenderTarget().
updateAllOcclusionQueries()
void irr::video::CNullDriver::updateAllOcclusionQueries (bool block = true) override virtual
Update all occlusion queries. Retrieves results from GPU.
If the query shall not block, set the flag to false. Update might not occur in this case, though
Implements irr::video::IVideoDriver.
Definition at line 1546 of file CNullDriver.cpp.
References removeOcclusionQuery(), and updateOcclusionQuery().
Referenced by endScene().
updateOcclusionQuery()
void irr::video::CNullDriver::updateOcclusionQuery (scene::ISceneNode * node, bool block = true) override virtual
Update occlusion query. Retrieves results from GPU.
If the query shall not block, set the flag to false. Update might not occur in this case, though
Implements irr::video::IVideoDriver.
Definition at line 1538 of file CNullDriver.cpp.
Referenced by updateAllOcclusionQueries().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CNullDriver.h
lib/irrlichtmt/source/Irrlicht/CNullDriver.cpp