Three Cubes Game: irr::core::string< T > Class Template Reference
irr::core::string< T > Class Template Reference
Very simple string class with some useful features.
#include <irrString.h>
Public Types
typedef T char_type
Public Member Functions
string ()
Default constructor.
string (const string< T > &other)
Copy constructor.
template<class B >
string (const string< B > &other)
Constructor from other string types.
string (const double number)
Constructs a string from a float.
string (int number)
Constructs a string from an int.
string (unsigned int number)
Constructs a string from an unsigned int.
string (long number)
Constructs a string from a long.
string (unsigned long number)
Constructs a string from an unsigned long.
template<class B >
string (const B *const c, u32 length)
Constructor for copying a string from a pointer with a given length.
template<class B >
string (const B *const c)
Constructor for Unicode and ASCII strings.
~string ()
Destructor.
string< T > & operator= (const string< T > &other)
Assignment operator.
template<class B >
string< T > & operator= (const string< B > &other)
Assignment operator for other string types.
template<class B >
string< T > & operator= (const B *const c)
Assignment operator for strings, ASCII and Unicode.
string< T > operator+ (const string< T > &other) const
Append operator for other strings.
template<class B >
string< T > operator+ (const B *const c) const
Append operator for strings, ASCII and Unicode.
T & operator[] (const u32 index)
Direct access operator.
const T & operator[] (const u32 index) const
Direct access operator.
bool operator== (const T *const other) const
Equality operator.
bool operator== (const string< T > &other) const
Equality operator.
bool operator< (const string< T > &other) const
Is smaller comparator.
bool operator!= (const T *const other) const
Inequality operator.
bool operator!= (const string< T > &other) const
Inequality operator.
u32 size () const
Returns length of the string's content.
bool empty () const
void clear (bool releaseMemory=true)
const T * c_str () const
Returns character string.
string< T > & make_lower ()
Makes the string lower case.
string< T > & make_upper ()
Makes the string upper case.
bool equals_ignore_case (const string< T > &other) const
Compares the strings ignoring case.
bool equals_substring_ignore_case (const string< T > &other, const u32 sourcePos=0) const
Compares the strings ignoring case.
bool lower_ignore_case (const string< T > &other) const
Compares the strings ignoring case.
bool equalsn (const string< T > &other, u32 n) const
compares the first n characters of the strings
bool equalsn (const T *const other, u32 n) const
compares the first n characters of the strings
string< T > & append (T character)
Appends a character to this string.
string< T > & append (const T *const other, u32 length=0xffffffff)
Appends a char string to this string.
string< T > & append (const string< T > &other)
Appends a string to this string.
string< T > & append (const string< T > &other, u32 length)
Appends a string of the length l to this string.
string< T > & insert (u32 pos, const T *s, u32 n)
Insert a certain amount of characters into the string before the given index.
void reserve (u32 count)
Reserves some memory.
s32 findFirst (T c) const
finds first occurrence of character in string
s32 findFirstChar (const T *const c, u32 count=1) const
finds first occurrence of a character of a list in string
s32 findFirstCharNotInList (const T *const c, u32 count=1) const
Finds first position of a character not in a given list.
s32 findLastCharNotInList (const T *const c, u32 count=1) const
Finds last position of a character not in a given list.
s32 findNext (T c, u32 startPos) const
finds next occurrence of character in string
s32 findLast (T c, s32 start=-1) const
finds last occurrence of character in string
s32 findLastChar (const T *const c, u32 count=1) const
finds last occurrence of a character of a list in string
s32 find (const T *const other, const u32 start=0) const
finds another string in this string
string< T > subString (u32 begin, s32 length, bool make_lower=false) const
Returns a substring.
string< T > & operator+= (T c)
Appends a character to this string.
string< T > & operator+= (const T *const c)
Appends a char string to this string.
string< T > & operator+= (const string< T > &other)
Appends a string to this string.
string< T > & operator+= (const int i)
Appends a string representation of a number to this string.
string< T > & operator+= (const unsigned int i)
Appends a string representation of a number to this string.
string< T > & operator+= (const long i)
Appends a string representation of a number to this string.
string< T > & operator+= (const unsigned long i)
Appends a string representation of a number to this string.
string< T > & operator+= (const double i)
Appends a string representation of a number to this string.
string< T > & operator+= (const float i)
Appends a string representation of a number to this string.
string< T > & replace (T toReplace, T replaceWith)
Replaces all characters of a special type with another one.
string< T > & replace (const string< T > &toReplace, const string< T > &replaceWith)
Replaces all instances of a string with another one.
string< T > & remove (T c)
Removes a character from a string.
string< T > & remove (const string< T > &toRemove)
Removes a string from the string.
string< T > & removeChars (const string< T > &characters)
Removes characters from a string.
string< T > & trim (const string< T > &whitespace=" \t\n\r")
Trims the string.
string< T > & erase (u32 index)
Erases a character from the string.
string< T > & validate ()
verify the existing string.
T lastChar () const
gets the last char of a string or null
template<class container >
u32 split (container &ret, const T *const delimiter, u32 countDelimiters=1, bool ignoreEmptyTokens=true, bool keepSeparators=false) const
Split string into parts (tokens).
Private Types
typedef std::basic_string< T > stl_type
typedef stl_type::size_type size_type
Private Member Functions
string (stl_type &&str)
Private constructor.
Static Private Member Functions
template<typename U >
static u32 calclen (const U *p)
strlen wrapper
static u32 calclen (const char *p)
static u32 calclen (const wchar_t *p)
template<typename U >
static int cmp (const U *p, const U *p2)
strcmp wrapper
static int cmp (const char *p, const char *p2)
static int cmp (const wchar_t *p, const wchar_t *p2)
static s32 pos_from_stl (size_type pos)
static size_type pos_to_stl (s32 pos)
Private Attributes
stl_type str
Static Private Attributes
static const size_type npos = stl_type::npos
Friends
size_t multibyteToWString (string< wchar_t > &destination, const char *source, u32 sourceSize)
Internally used by the other multibyteToWString functions.
size_t wStringToMultibyte (string< c8 > &destination, const wchar_t *source, u32 sourceSize)
Same as multibyteToWString, but the other way around.
Detailed Description
template<typename T>
class irr::core::string< T >
Very simple string class with some useful features.
string<c8> and string<wchar_t> both accept Unicode AND ASCII/Latin-1, so you can assign Unicode to string<c8> and ASCII/Latin-1 to string<wchar_t> (and the other way round) if you want to.
However, note that the conversation between both is not done using any encoding. This means that c8 strings are treated as ASCII/Latin-1, not UTF-8, and are simply expanded to the equivalent wchar_t, while Unicode/wchar_t characters are truncated to 8-bit ASCII/Latin-1 characters, discarding all other information in the wchar_t.
Helper functions for converting between UTF-8 and wchar_t are provided outside the string class for explicit use.
Definition at line 37 of file irrString.h.
Member Function Documentation
append() [1/4]
template<typename T > string<T>& irr::core::string< T >::append (const string< T > & other) inline
Appends a string to this string.
Parameters
other String to append.
Definition at line 426 of file irrString.h.
append() [2/4]
template<typename T > string<T>& irr::core::string< T >::append (const string< T > & other, u32 length) inline
Appends a string of the length l to this string.
Parameters
other other String to append to this string.
length How much characters of the other string to add to this one.
Definition at line 436 of file irrString.h.
append() [3/4]
template<typename T > string<T>& irr::core::string< T >::append (const T *const other, u32 length = 0xffffffff) inline
Appends a char string to this string.
Parameters
other Char string to append.
length The length of the string to append.
Definition at line 410 of file irrString.h.
append() [4/4]
template<typename T > string<T>& irr::core::string< T >::append (T character) inline
Appends a character to this string.
Parameters
character Character to append.
Definition at line 400 of file irrString.h.
Referenced by irr::core::string< c8 >::append(), irr::CIrrDeviceStub::CIrrDeviceStub(), irr::io::CFileSystem::createFileList(), irr::io::CFileSystem::flattenFilename(), irr::scene::CXMeshFileLoader::getNextToken(), irr::scene::CXMeshFileLoader::getNextTokenAsString(), irr::core::string< c8 >::operator+=(), and irr::io::CZipReader::scanGZipHeader().
c_str()
template<typename T > const T* irr::core::string< T >::c_str () const inline
Returns character string.
Returns
pointer to C-style NUL terminated string.
Definition at line 285 of file irrString.h.
Referenced by irr::io::CFileSystem::changeWorkingDirectoryTo(), irr::CIrrDeviceStub::checkVersion(), irr::CIrrDeviceStub::CIrrDeviceStub(), irr::io::CFileSystem::createFileList(), irr::scene::COBJMeshFileLoader::createMesh(), irr::scene::CXMeshFileLoader::createMesh(), irr::core::deletePathFromFilename(), irr::core::string< c8 >::equals_ignore_case(), irr::core::string< c8 >::equals_substring_ignore_case(), irr::core::string< c8 >::equalsn(), irr::io::CFileSystem::existFile(), irr::io::CFileSystem::getAbsolutePath(), irr::scene::ISceneNode::getName(), irr::gui::IGUIElement::getName(), irr::CLogger::log(), irr::core::string< c8 >::lower_ignore_case(), irr::core::multibyteToWString(), irr::core::string< c8 >::operator=(), irr::core::ustring16::operator=(), irr::core::string< c8 >::operator==(), irr::scene::CXMeshFileLoader::parseDataObject(), irr::gui::CGUIComboBox::setSelected(), irr::gui::CGUIEditBox::setTextMarkers(), irr::core::string< c8 >::validate(), and irr::core::wStringToMultibyte().
empty()
template<typename T > bool irr::core::string< T >::empty () const inline
Informs if the string is empty or not.
Returns
True if the string is empty, false if not.
Definition at line 268 of file irrString.h.
Referenced by irr::io::CFileSystem::createAndOpenFile(), irr::io::CFileSystem::createFileList(), irr::io::CFileSystem::getAbsolutePath(), irr::io::CFileSystem::getRelativeFilename(), and irr::core::mergeFilename().
equals_ignore_case()
template<typename T > bool irr::core::string< T >::equals_ignore_case (const string< T > & other) const inline
Compares the strings ignoring case.
Parameters
other Other string to compare.
Returns
True if the strings are equal ignoring case.
Definition at line 314 of file irrString.h.
Referenced by irr::io::SFileListEntry::operator==().
equals_substring_ignore_case()
template<typename T > bool irr::core::string< T >::equals_substring_ignore_case (const string< T > & other, const u32 sourcePos = 0) const inline
Compares the strings ignoring case.
Parameters
other Other string to compare.
sourcePos where to start to compare in the string
Returns
True if the strings are equal ignoring case.
Definition at line 328 of file irrString.h.
Referenced by irr::core::isFileExtension().
equalsn() [1/2]
template<typename T > bool irr::core::string< T >::equalsn (const string< T > & other, u32 n) const inline
compares the first n characters of the strings
Parameters
other Other string to compare.
n Number of characters to compare
Returns
True if the n first characters of both strings are equal.
Definition at line 364 of file irrString.h.
Referenced by irr::core::isInSameDirectory().
equalsn() [2/2]
template<typename T > bool irr::core::string< T >::equalsn (const T *const other, u32 n) const inline
compares the first n characters of the strings
Parameters
str Other string to compare.
n Number of characters to compare
Returns
True if the n first characters of both strings are equal.
Definition at line 382 of file irrString.h.
erase()
template<typename T > string<T>& irr::core::string< T >::erase (u32 index) inline
Erases a character from the string.
May be slow, because all elements following after the erased element have to be copied.
Parameters
index Index of element to be erased.
Definition at line 783 of file irrString.h.
find()
template<typename T > s32 irr::core::string< T >::find (const T *const other, const u32 start = 0) const inline
finds another string in this string
Parameters
str Another string
start Start position of the search
Returns
Positions where the string has been found, or -1 if not found.
Definition at line 574 of file irrString.h.
findFirst()
template<typename T > s32 irr::core::string< T >::findFirst (T c) const inline
finds first occurrence of character in string
Parameters
c Character to search for.
Returns
Position where the character has been found, or -1 if not found.
Definition at line 474 of file irrString.h.
findFirstChar()
template<typename T > s32 irr::core::string< T >::findFirstChar (const T *const c, u32 count = 1) const inline
finds first occurrence of a character of a list in string
Parameters
c List of characters to find. For example if the method should find the first occurrence of 'a' or 'b', this parameter should be "ab".
count Amount of characters in the list. Usually, this should be strlen(c)
Returns
Position where one of the characters has been found, or -1 if not found.
Definition at line 487 of file irrString.h.
findFirstCharNotInList()
template<typename T > s32 irr::core::string< T >::findFirstCharNotInList (const T *const c, u32 count = 1) const inline
Finds first position of a character not in a given list.
Parameters
c List of characters not to find. For example if the method should find the first occurrence of a character not 'a' or 'b', this parameter should be "ab".
count Amount of characters in the list. Usually, this should be strlen(c)
Returns
Position where the character has been found, or -1 if not found.
Definition at line 504 of file irrString.h.
Referenced by irr::core::string< c8 >::trim().
findLast()
template<typename T > s32 irr::core::string< T >::findLast (T c, s32 start = -1) const inline
finds last occurrence of character in string
Parameters
c Character to search for.
start start to search reverse (default = -1, on end)
Returns
Position where the character has been found, or -1 if not found.
Definition at line 546 of file irrString.h.
Referenced by irr::core::cutFilenameExtension(), irr::io::CFileSystem::getFileBasename(), irr::io::CFileSystem::getFileDir(), irr::core::getFileNameExtension(), and irr::core::isFileExtension().
findLastChar()
template<typename T > s32 irr::core::string< T >::findLastChar (const T *const c, u32 count = 1) const inline
finds last occurrence of a character of a list in string
Parameters
c List of strings to find. For example if the method should find the last occurrence of 'a' or 'b', this parameter should be "ab".
count Amount of characters in the list. Usually, this should be strlen(c)
Returns
Position where one of the characters has been found, or -1 if not found.
Definition at line 559 of file irrString.h.
findLastCharNotInList()
template<typename T > s32 irr::core::string< T >::findLastCharNotInList (const T *const c, u32 count = 1) const inline
Finds last position of a character not in a given list.
Parameters
c List of characters not to find. For example if the method should find the first occurrence of a character not 'a' or 'b', this parameter should be "ab".
count Amount of characters in the list. Usually, this should be strlen(c)
Returns
Position where the character has been found, or -1 if not found.
Definition at line 520 of file irrString.h.
Referenced by irr::core::string< c8 >::trim().
findNext()
template<typename T > s32 irr::core::string< T >::findNext (T c, u32 startPos) const inline
finds next occurrence of character in string
Parameters
c Character to search for.
startPos Position in string to start searching.
Returns
Position where the character has been found, or -1 if not found.
Definition at line 534 of file irrString.h.
Referenced by irr::core::isInSameDirectory().
lower_ignore_case()
template<typename T > bool irr::core::string< T >::lower_ignore_case (const string< T > & other) const inline
Compares the strings ignoring case.
Parameters
other Other string to compare.
Returns
True if this string is smaller ignoring case.
Definition at line 346 of file irrString.h.
Referenced by irr::io::SFileListEntry::operator<().
operator+=() [1/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (const double i) inline
Appends a string representation of a number to this string.
Parameters
i Number to append.
Definition at line 669 of file irrString.h.
operator+=() [2/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (const float i) inline
Appends a string representation of a number to this string.
Parameters
i Number to append.
Definition at line 678 of file irrString.h.
operator+=() [3/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (const int i) inline
Appends a string representation of a number to this string.
Parameters
i Number to append.
Definition at line 633 of file irrString.h.
operator+=() [4/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (const long i) inline
Appends a string representation of a number to this string.
Parameters
i Number to append.
Definition at line 651 of file irrString.h.
operator+=() [5/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (const string< T > & other) inline
Appends a string to this string.
Parameters
other String to append.
Definition at line 624 of file irrString.h.
operator+=() [6/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (const T *const c) inline
Appends a char string to this string.
Parameters
c Char string to append.
Definition at line 615 of file irrString.h.
operator+=() [7/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (const unsigned int i) inline
Appends a string representation of a number to this string.
Parameters
i Number to append.
Definition at line 642 of file irrString.h.
operator+=() [8/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (const unsigned long i) inline
Appends a string representation of a number to this string.
Parameters
i Number to append.
Definition at line 660 of file irrString.h.
operator+=() [9/9]
template<typename T > string<T>& irr::core::string< T >::operator+= (T c) inline
Appends a character to this string.
Parameters
c Character to append.
Definition at line 606 of file irrString.h.
remove() [1/2]
template<typename T > string<T>& irr::core::string< T >::remove (const string< T > & toRemove) inline
Removes a string from the string.
Parameters
toRemove String to remove.
Definition at line 721 of file irrString.h.
remove() [2/2]
template<typename T > string<T>& irr::core::string< T >::remove (T c) inline
Removes a character from a string.
Parameters
c Character to remove.
Definition at line 712 of file irrString.h.
Referenced by irr::core::string< c8 >::removeChars().
removeChars()
template<typename T > string<T>& irr::core::string< T >::removeChars (const string< T > & characters) inline
Removes characters from a string.
Parameters
characters Characters to remove.
Definition at line 753 of file irrString.h.
replace() [1/2]
template<typename T > string<T>& irr::core::string< T >::replace (const string< T > & toReplace, const string< T > & replaceWith) inline
Replaces all instances of a string with another one.
Parameters
toReplace The string to replace.
replaceWith The string replacing the old one.
Definition at line 698 of file irrString.h.
replace() [2/2]
template<typename T > string<T>& irr::core::string< T >::replace (T toReplace, T replaceWith) inline
Replaces all characters of a special type with another one.
Parameters
toReplace Character to replace.
replaceWith Character replacing the old one.
Definition at line 688 of file irrString.h.
Referenced by irr::io::CFileList::addItem(), irr::io::CFileList::CFileList(), irr::io::CFileSystem::createFileList(), irr::io::CFileList::findFile(), irr::io::CFileSystem::getAbsolutePath(), irr::io::CFileSystem::getWorkingDirectory(), and irr::core::splitFilename().
reserve()
template<typename T > void irr::core::string< T >::reserve (u32 count) inline
Reserves some memory.
Parameters
count Amount of characters to reserve, including the trailing NUL.
Definition at line 462 of file irrString.h.
size()
template<typename T > u32 irr::core::string< T >::size () const inline
Returns length of the string's content.
Returns
Length of the string's content in characters, excluding the trailing NUL.
Definition at line 261 of file irrString.h.
Referenced by irr::video::CNullDriver::addHighLevelShaderMaterialFromFiles(), irr::io::CFileList::addItem(), irr::video::CNullDriver::addShaderMaterialFromFiles(), irr::io::CFileSystem::createFileList(), irr::video::CNullDriver::createImageFromFile(), irr::scene::COBJMeshFileLoader::createMesh(), irr::core::cutFilenameExtension(), irr::core::deletePathFromFilename(), irr::core::deletePathFromPath(), irr::core::string< c8 >::equals_ignore_case(), irr::core::string< c8 >::equals_substring_ignore_case(), irr::core::string< c8 >::equalsn(), irr::io::CFileList::findFile(), irr::scene::COBJMeshFileLoader::findMtl(), irr::io::CFileSystem::flattenFilename(), irr::io::CFileSystem::getAbsolutePath(), irr::io::CFileSystem::getFileBasename(), irr::io::CFileSystem::getFileDir(), irr::core::getFileNameExtension(), irr::scene::CXMeshFileLoader::getNextToken(), irr::io::CFileSystem::getRelativeFilename(), irr::core::string< c8 >::insert(), irr::core::isInSameDirectory(), irr::video::CNullDriver::loadTextureFromFile(), irr::core::string< c8 >::lower_ignore_case(), irr::core::multibyteToWString(), irr::scene::CXMeshFileLoader::parseDataObject(), irr::core::string< c8 >::remove(), irr::io::CZipReader::scanGZipHeader(), irr::core::string< c8 >::split(), irr::core::string< c8 >::subString(), irr::core::string< c8 >::validate(), irr::scene::CB3DMeshWriter::writeMesh(), irr::core::wStringToMultibyte(), and irr::gui::CGUIFileOpenDialog::~CGUIFileOpenDialog().
split()
template<typename T > template<class container > u32 irr::core::string< T >::split (container & ret, const T *const delimiter, u32 countDelimiters = 1, bool ignoreEmptyTokens = true, bool keepSeparators = false) const inline
Split string into parts (tokens).
This method will split a string at certain delimiter characters into the container passed in as reference. The type of the container has to be given as template parameter. It must provide a push_back and a size method.
Parameters
ret The result container. Tokens are added, the container is not cleared.
delimiter C-style string of delimiter characters
countDelimiters Number of delimiter characters
ignoreEmptyTokens Flag to avoid empty substrings in the result container. If two delimiters occur without a character in between or an empty substring would be placed in the result. Or if a delimiter is the last character an empty substring would be added at the end. If this flag is set, only non-empty strings are stored.
keepSeparators Flag which allows to add the separator to the result string. If this flag is true, the concatenation of the substrings results in the original string. Otherwise, only the characters between the delimiters are returned.
Returns
The number of resulting substrings
Definition at line 826 of file irrString.h.
Referenced by irr::io::CFileSystem::getRelativeFilename().
subString()
template<typename T > string<T> irr::core::string< T >::subString (u32 begin, s32 length, bool make_lower = false) const inline
Returns a substring.
Parameters
begin Start of substring.
length Length of substring.
make_lower copy only lower case
Definition at line 590 of file irrString.h.
Referenced by irr::core::cutFilenameExtension(), irr::io::CFileSystem::getFileBasename(), irr::io::CFileSystem::getFileDir(), irr::core::getFileNameExtension(), and irr::core::string< c8 >::trim().
trim()
template<typename T > string<T>& irr::core::string< T >::trim (const string< T > & whitespace = " \t\n\r") inline
Trims the string.
Removes the specified characters (by default, Latin-1 whitespace) from the beginning and the end of the string.
Definition at line 767 of file irrString.h.
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/irrString.h