Three Cubes Game: UpscaleStep Class Reference
UpscaleStep Class Reference
#include <plain.h>
Public Member Functions
virtual void setRenderSource (RenderSource *source) override
virtual void setRenderTarget (RenderTarget *target) override
virtual void reset (PipelineContext &context) override
virtual void run (PipelineContext &context) override
Private Attributes
RenderSource * m_source
RenderTarget * m_target
Detailed Description
UpscaleStep step performs rescaling of the image in the source texture 0 to the size of the target.
Definition at line 86 of file plain.h.
Member Function Documentation
run()
void UpscaleStep::run (PipelineContext & context) override virtual
Runs the step. This method is invoked by the pipeline.
Implements RenderStep.
Definition at line 97 of file plain.cpp.
References RenderTarget::activate(), irr::video::IVideoDriver::draw2DImage(), irr::video::ITexture::getSize(), RenderSource::getTexture(), irr::IrrlichtDevice::getVideoDriver(), irr::core::dimension2d< T >::Height, irr::core::dimension2d< T >::Width, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
setRenderSource()
virtual void UpscaleStep::setRenderSource (RenderSource * source) inline override virtual
Assigns render source to this step.
Parameters
source source of rendering information
Implements RenderStep.
Definition at line 90 of file plain.h.
setRenderTarget()
virtual void UpscaleStep::setRenderTarget (RenderTarget * target) inline override virtual
Assigned render target to this step.
Parameters
target render target to send output to.
Implements RenderStep.
Definition at line 91 of file plain.h.
The documentation for this class was generated from the following files:
src/client/render/plain.h
src/client/render/plain.cpp