Three Cubes Game: irr::io::IReadFile Class Reference
irr::io::IReadFile Class Reference abstract
Interface providing read access to a file.
#include <IReadFile.h>
Public Member Functions
virtual size_t read (void *buffer, size_t sizeToRead)=0
Reads an amount of bytes from the file.
virtual bool seek (long finalPos, bool relativeMovement=false)=0
Changes position in file.
virtual long getSize () const =0
Get size of file.
virtual long getPos () const =0
Get the current position in the file.
virtual const io::path & getFileName () const =0
Get name of file.
virtual EREAD_FILE_TYPE getType () const
Get the type of the class implementing this interface.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Interface providing read access to a file.
Definition at line 18 of file IReadFile.h.
Member Function Documentation
getFileName()
virtual const io::path& irr::io::IReadFile::getFileName () const pure virtual
Get name of file.
Returns
File name as zero terminated character string.
Implemented in irr::io::CReadFile, irr::io::CLimitReadFile, and irr::io::CMemoryReadFile.
getPos()
virtual long irr::io::IReadFile::getPos () const pure virtual
Get the current position in the file.
Returns
Current position in the file in bytes on success or -1L on failure.
Implemented in irr::io::CReadFile, irr::io::CLimitReadFile, and irr::io::CMemoryReadFile.
Referenced by irr::io::CZipReader::scanCentralDirectoryHeader(), irr::io::CZipReader::scanGZipHeader(), and irr::io::CZipReader::scanZipHeader().
getSize()
virtual long irr::io::IReadFile::getSize () const pure virtual
Get size of file.
Returns
Size of the file in bytes.
Implemented in irr::io::CLimitReadFile, irr::io::CMemoryReadFile, and irr::io::CReadFile.
Referenced by irr::video::CNullDriver::addHighLevelShaderMaterialFromFiles(), irr::video::CNullDriver::addShaderMaterialFromFiles(), irr::io::CZipReader::scanGZipHeader(), and irr::io::CZipReader::scanZipHeader().
read()
virtual size_t irr::io::IReadFile::read (void * buffer, size_t sizeToRead) pure virtual
Reads an amount of bytes from the file.
Parameters
buffer Pointer to buffer where read bytes are written to.
sizeToRead Amount of bytes to read from the file.
Returns
How many bytes were read.
Implemented in irr::io::CLimitReadFile, irr::io::CMemoryReadFile, and irr::io::CReadFile.
Referenced by irr::video::CNullDriver::addHighLevelShaderMaterialFromFiles(), irr::video::CNullDriver::addShaderMaterialFromFiles(), irr::io::CZipReader::createAndOpenFile(), irr::io::CZipReader::scanCentralDirectoryHeader(), irr::io::CZipReader::scanGZipHeader(), and irr::io::CZipReader::scanZipHeader().
seek()
virtual bool irr::io::IReadFile::seek (long finalPos, bool relativeMovement = false) pure virtual
Changes position in file.
Parameters
finalPos Destination position in the file.
relativeMovement If set to true, the position in the file is changed relative to current position. Otherwise the position is changed from beginning of file.
Returns
True if successful, otherwise false.
Implemented in irr::io::CLimitReadFile, irr::io::CMemoryReadFile, and irr::io::CReadFile.
Referenced by irr::video::CNullDriver::addHighLevelShaderMaterialFromFiles(), irr::io::CZipReader::createAndOpenFile(), irr::io::CZipReader::scanCentralDirectoryHeader(), irr::io::CZipReader::scanGZipHeader(), and irr::io::CZipReader::scanZipHeader().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IReadFile.h