Three Cubes Game: irr::video::IRenderTarget Class Reference
irr::video::IRenderTarget Class Reference abstract
Interface of a Render Target.
#include <IRenderTarget.h>
Public Member Functions
IRenderTarget ()
constructor
const core::array< ITexture * > & getTexture () const
Returns an array of previously set textures.
ITexture * getDepthStencil () const
Returns a of previously set depth / depth-stencil texture.
const core::array< E_CUBE_SURFACE > & getCubeSurfaces () const
Returns an array of active surface for cube textures.
void setTexture (const core::array< ITexture * > &texture, ITexture *depthStencil, const core::array< E_CUBE_SURFACE > &cubeSurfaces=core::array< E_CUBE_SURFACE >())
Set multiple textures.
void setTexture (ITexture *texture, ITexture *depthStencil)
void setTexture (ITexture *texture, ITexture *depthStencil, E_CUBE_SURFACE cubeSurface)
Set one cube surface texture.
E_DRIVER_TYPE getDriverType () const
Get driver type of render target.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Protected Member Functions
virtual void setTextures (ITexture *const *textures, u32 numTextures, ITexture *depthStencil, const E_CUBE_SURFACE *cubeSurfaces=0, u32 numCubeSurfaces=0)=0
Set multiple textures.
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
core::array< ITexture * > Textures
Textures assigned to render target.
ITexture * DepthStencil
Depth or packed depth-stencil texture assigned to render target.
core::array< E_CUBE_SURFACE > CubeSurfaces
Active surface of cube textures.
E_DRIVER_TYPE DriverType
Driver type of render target.
Private Member Functions
IRenderTarget (const IRenderTarget &)
IRenderTarget & operator= (const IRenderTarget &)
Detailed Description
Interface of a Render Target.
Definition at line 30 of file IRenderTarget.h.
Member Function Documentation
setTexture() [1/2]
void irr::video::IRenderTarget::setTexture (const core::array< ITexture * > & texture, ITexture * depthStencil, const core::array< E_CUBE_SURFACE > & cubeSurfaces = core::array<E_CUBE_SURFACE>()) inline
Set multiple textures.
Set multiple textures for the render target.
Parameters
texture Array of texture objects. These textures are used for a color outputs.
depthStencil Depth or packed depth-stencil texture. This texture is used as depth or depth-stencil buffer. You can pass getDepthStencil() if you don't want to change it.
cubeSurfaces When rendering to cube textures, set the surface to be used for each texture. Can be empty otherwise.
Definition at line 64 of file IRenderTarget.h.
References irr::core::array< T >::const_pointer(), setTextures(), and irr::core::array< T >::size().
Referenced by TextureBufferOutput::activate(), and irr::video::CNullDriver::setRenderTarget().
setTexture() [2/2]
void irr::video::IRenderTarget::setTexture (ITexture * texture, ITexture * depthStencil) inline
Sets one texture + depthStencil You can pass getDepthStencil() for depthStencil if you don't want to change that one
Definition at line 71 of file IRenderTarget.h.
References setTextures().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IRenderTarget.h