Three Cubes Game: irr::core::plane3d< T > Class Template Reference
irr::core::plane3d< T > Class Template Reference
Template plane class with some intersection testing methods.
#include <plane3d.h>
Public Member Functions
plane3d (const vector3d< T > &MPoint, const vector3d< T > &Normal)
plane3d (T px, T py, T pz, T nx, T ny, T nz)
plane3d (const vector3d< T > &point1, const vector3d< T > &point2, const vector3d< T > &point3)
plane3d (const vector3d< T > &normal, const T d)
bool operator== (const plane3d< T > &other) const
bool operator!= (const plane3d< T > &other) const
void setPlane (const vector3d< T > &point, const vector3d< T > &nvector)
void setPlane (const vector3d< T > &nvect, T d)
void setPlane (const vector3d< T > &point1, const vector3d< T > &point2, const vector3d< T > &point3)
bool getIntersectionWithLine (const vector3d< T > &linePoint, const vector3d< T > &lineVect, vector3d< T > &outIntersection) const
Get an intersection with a 3d line.
f32 getKnownIntersectionWithLine (const vector3d< T > &linePoint1, const vector3d< T > &linePoint2) const
Get percentage of line between two points where an intersection with this plane happens.
bool getIntersectionWithLimitedLine (const vector3d< T > &linePoint1, const vector3d< T > &linePoint2, vector3d< T > &outIntersection) const
Get an intersection with a 3d line, limited between two 3d points.
EIntersectionRelation3D classifyPointRelation (const vector3d< T > &point) const
Classifies the relation of a point to this plane.
void recalculateD (const vector3d< T > &MPoint)
Recalculates the distance from origin by applying a new member point to the plane.
vector3d< T > getMemberPoint () const
Gets a member point of the plane.
bool existsIntersection (const plane3d< T > &other) const
Tests if there is an intersection with the other plane.
bool getIntersectionWithPlane (const plane3d< T > &other, vector3d< T > &outLinePoint, vector3d< T > &outLineVect) const
Intersects this plane with another.
bool getIntersectionWithPlanes (const plane3d< T > &o1, const plane3d< T > &o2, vector3d< T > &outPoint) const
Get the intersection point with two other planes if there is one.
bool isFrontFacing (const vector3d< T > &lookDirection) const
Test if the triangle would be front or backfacing from any point.
T getDistanceTo (const vector3d< T > &point) const
Get the distance to a point.
Public Attributes
vector3d< T > Normal
Normal vector of the plane.
T D
Distance from origin.
Detailed Description
template<class T>
class irr::core::plane3d< T >
Template plane class with some intersection testing methods.
It has to be ensured, that the normal is always normalized. The constructors and setters of this class will not ensure this automatically. So any normal passed in has to be normalized in advance. No change to the normal will be made by any of the class methods.
Definition at line 33 of file plane3d.h.
Member Function Documentation
classifyPointRelation()
template<class T > EIntersectionRelation3D irr::core::plane3d< T >::classifyPointRelation (const vector3d< T > & point) const inline
Classifies the relation of a point to this plane.
Parameters
point Point to classify its relation.
Returns
ISREL3D_FRONT if the point is in front of the plane, ISREL3D_BACK if the point is behind of the plane, and ISREL3D_PLANAR if the point is within the plane.
Definition at line 135 of file plane3d.h.
Referenced by irr::scene::CSceneManager::isCulled().
existsIntersection()
template<class T > bool irr::core::plane3d< T >::existsIntersection (const plane3d< T > & other) const inline
Tests if there is an intersection with the other plane.
Returns
True if there is a intersection.
Definition at line 162 of file plane3d.h.
getDistanceTo()
template<class T > T irr::core::plane3d< T >::getDistanceTo (const vector3d< T > & point) const inline
Get the distance to a point.
Note that this only works if the normal is normalized.
Definition at line 222 of file plane3d.h.
getIntersectionWithLimitedLine()
template<class T > bool irr::core::plane3d< T >::getIntersectionWithLimitedLine (const vector3d< T > & linePoint1, const vector3d< T > & linePoint2, vector3d< T > & outIntersection) const inline
Get an intersection with a 3d line, limited between two 3d points.
Parameters
linePoint1 Point 1 of the line.
linePoint2 Point 2 of the line.
outIntersection Place to store the intersection point, if there is one.
Returns
True if there was an intersection, false if there was not.
Definition at line 121 of file plane3d.h.
getIntersectionWithLine()
template<class T > bool irr::core::plane3d< T >::getIntersectionWithLine (const vector3d< T > & linePoint, const vector3d< T > & lineVect, vector3d< T > & outIntersection) const inline
Get an intersection with a 3d line.
Parameters
lineVect Vector of the line to intersect with.
linePoint Point of the line to intersect with.
outIntersection Place to store the intersection point, if there is one.
Returns
True if there was an intersection, false if there was not.
Definition at line 86 of file plane3d.h.
Referenced by irr::core::plane3d< f32 >::getIntersectionWithLimitedLine(), and irr::core::plane3d< f32 >::getIntersectionWithPlanes().
getIntersectionWithPlane()
template<class T > bool irr::core::plane3d< T >::getIntersectionWithPlane (const plane3d< T > & other, vector3d< T > & outLinePoint, vector3d< T > & outLineVect) const inline
Intersects this plane with another.
Parameters
other Other plane to intersect with.
outLinePoint Base point of intersection line.
outLineVect Vector of intersection.
Returns
True if there is a intersection, false if not.
Definition at line 173 of file plane3d.h.
Referenced by irr::core::plane3d< f32 >::getIntersectionWithPlanes().
getKnownIntersectionWithLine()
template<class T > f32 irr::core::plane3d< T >::getKnownIntersectionWithLine (const vector3d< T > & linePoint1, const vector3d< T > & linePoint2) const inline
Get percentage of line between two points where an intersection with this plane happens.
Only useful if known that there is an intersection.
Parameters
linePoint1 Point1 of the line to intersect with.
linePoint2 Point2 of the line to intersect with.
Returns
Where on a line between two points an intersection with this plane happened. For example, 0.5 is returned if the intersection happened exactly in the middle of the two points.
Definition at line 107 of file plane3d.h.
Referenced by irr::scene::SViewFrustum::clipLine().
isFrontFacing()
template<class T > bool irr::core::plane3d< T >::isFrontFacing (const vector3d< T > & lookDirection) const inline
Test if the triangle would be front or backfacing from any point.
Thus, this method assumes a camera position from which the triangle is definitely visible when looking into the given direction. Note that this only works if the normal is Normalized. Do not use this method with points as it will give wrong results!
Parameters
lookDirection Look direction.
Returns
True if the plane is front facing and false if it is backfacing.
Definition at line 214 of file plane3d.h.
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/plane3d.h