Three Cubes Game: irr::gui::CGUIEnvironment Class Reference
irr::gui::CGUIEnvironment Class Reference
Classes
struct SFont
struct SSpriteBank
struct SToolTip
Public Member Functions
CGUIEnvironment (io::IFileSystem *fs, video::IVideoDriver *driver, IOSOperator *op)
constructor
virtual ~CGUIEnvironment ()
destructor
void drawAll (bool useScreenSize) override
draws all gui elements
video::IVideoDriver * getVideoDriver () const override
returns the current video driver
io::IFileSystem * getFileSystem () const override
returns pointer to the filesystem
IOSOperator * getOSOperator () const override
returns a pointer to the OS operator
bool postEventFromUser (const SEvent &event) override
posts an input event to the environment
void setUserEventReceiver (IEventReceiver *evr) override
void clear () override
removes all elements from the environment
bool OnEvent (const SEvent &event) override
called if an event happened.
IGUISkin * getSkin () const override
returns the current gui skin
void setSkin (IGUISkin *skin) override
Sets a new GUI Skin.
IGUISkin * createSkin (EGUI_SKIN_TYPE type) override
Creates a new GUI Skin based on a template.
virtual IGUIImageList * createImageList (video::ITexture *texture, core::dimension2d< s32 > imageSize, bool useAlphaChannel) override
Creates the image list from the given texture.
IGUIFont * getFont (const io::path &filename) override
returns the font
IGUIFont * addFont (const io::path &name, IGUIFont *font) override
add an externally loaded font
void removeFont (IGUIFont *font) override
remove loaded font
IGUIFont * getBuiltInFont () const override
returns default font
IGUISpriteBank * getSpriteBank (const io::path &filename) override
returns the sprite bank
IGUISpriteBank * addEmptySpriteBank (const io::path &name) override
returns the sprite bank
IGUIButton * addButton (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1, const wchar_t *text=0, const wchar_t *tooltiptext=0) override
adds an button. The returned pointer must not be dropped.
virtual IGUIScrollBar * addScrollBar (bool horizontal, const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1) override
adds a scrollbar. The returned pointer must not be dropped.
virtual IGUIImage * addImage (video::ITexture *image, core::position2d< s32 > pos, bool useAlphaChannel=true, IGUIElement *parent=0, s32 id=-1, const wchar_t *text=0) override
Adds an image element.
virtual IGUIImage * addImage (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1, const wchar_t *text=0, bool useAlphaChannel=true) override
adds an image. The returned pointer must not be dropped.
virtual IGUICheckBox * addCheckBox (bool checked, const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1, const wchar_t *text=0) override
adds a checkbox
virtual IGUIListBox * addListBox (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1, bool drawBackground=false) override
adds a list box
virtual IGUIFileOpenDialog * addFileOpenDialog (const wchar_t *title=0, bool modal=true, IGUIElement *parent=0, s32 id=-1, bool restoreCWD=false, io::path::char_type *startDir=0) override
Adds a file open dialog.
virtual IGUIStaticText * addStaticText (const wchar_t *text, const core::rect< s32 > &rectangle, bool border=false, bool wordWrap=true, IGUIElement *parent=0, s32 id=-1, bool drawBackground=false) override
adds a static text. The returned pointer must not be dropped.
virtual IGUIEditBox * addEditBox (const wchar_t *text, const core::rect< s32 > &rectangle, bool border=false, IGUIElement *parent=0, s32 id=-1) override
Adds an edit box. The returned pointer must not be dropped.
virtual IGUITabControl * addTabControl (const core::rect< s32 > &rectangle, IGUIElement *parent=0, bool fillbackground=false, bool border=true, s32 id=-1) override
Adds a tab control to the environment.
virtual IGUITab * addTab (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1) override
Adds tab to the environment.
virtual IGUIComboBox * addComboBox (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1) override
Adds a combo box to the environment.
bool setFocus (IGUIElement *element) override
sets the focus to an element
bool removeFocus (IGUIElement *element) override
removes the focus from an element
bool hasFocus (const IGUIElement *element, bool checkSubElements=false) const override
Returns if the element has focus.
IGUIElement * getFocus () const override
Returns the element with the focus.
IGUIElement * getHovered () const override
Returns the element last known to be under the mouse.
IGUIElement * getRootGUIElement () override
Returns the root gui element.
void OnPostRender (u32 time) override
animate the element and its children.
IGUIElement * getNextElement (bool reverse=false, bool group=false) override
Find the next element which would be selected when pressing the tab-key.
void setFocusBehavior (u32 flags) override
Set the way the gui will handle focus changes.
u32 getFocusBehavior () const override
Get the way the gui does handle focus changes.
void addToDeletionQueue (IGUIElement *element) override
Adds a IGUIElement to deletion queue.
Public Member Functions inherited from irr::gui::IGUIEnvironment
virtual IGUIFileOpenDialog * addFileOpenDialog (const wchar_t *title=0, bool modal=true, IGUIElement *parent=0, s32 id=-1, bool restoreCWD=false, io::path::char_type *startDir=0)=0
Adds a file open dialog.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::gui::IGUIElement
IGUIElement (EGUI_ELEMENT_TYPE type, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle)
Constructor.
virtual ~IGUIElement ()
Destructor.
IGUIElement * getParent () const
Returns parent of this element.
core::rect< s32 > getRelativePosition () const
Returns the relative rectangle of this element.
void setRelativePosition (const core::rect< s32 > &r)
Sets the relative rectangle of this element.
void setRelativePosition (const core::position2di &position)
Sets the relative rectangle of this element, maintaining its current width and height.
void setRelativePositionProportional (const core::rect< f32 > &r)
Sets the relative rectangle of this element as a proportion of its parent's area.
core::rect< s32 > getAbsolutePosition () const
Gets the absolute rectangle of this element.
core::rect< s32 > getAbsoluteClippingRect () const
Returns the visible area of the element.
void setNotClipped (bool noClip)
Sets whether the element will ignore its parent's clipping rectangle.
bool isNotClipped () const
Gets whether the element will ignore its parent's clipping rectangle.
void setMaxSize (core::dimension2du size)
Sets the maximum size allowed for this element.
void setMinSize (core::dimension2du size)
Sets the minimum size allowed for this element.
void setAlignment (EGUI_ALIGNMENT left, EGUI_ALIGNMENT right, EGUI_ALIGNMENT top, EGUI_ALIGNMENT bottom)
The alignment defines how the borders of this element will be positioned when the parent element is resized.
EGUI_ALIGNMENT getAlignLeft () const
How left element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignRight () const
How right element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignTop () const
How top element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignBottom () const
How bottom element border is aligned when parent is resized.
virtual void updateAbsolutePosition ()
Updates the absolute position.
virtual IGUIElement * getElementFromPoint (const core::position2d< s32 > &point)
Returns the topmost GUI element at the specific position.
virtual bool isPointInside (const core::position2d< s32 > &point) const
Returns true if a point is within this element.
virtual void addChild (IGUIElement *child)
Adds a GUI element as new child of this element.
virtual void removeChild (IGUIElement *child)
Removes a child.
virtual void removeAllChildren ()
Removes all children.
virtual void remove ()
Removes this element from its parent.
virtual void draw ()
Draws the element and its children.
virtual void move (core::position2d< s32 > absoluteMovement)
Moves this element.
virtual bool isVisible () const
Returns true if element is visible.
virtual bool isTrulyVisible () const
Check whether the element is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool visible)
Sets the visible state of this element.
virtual bool isSubElement () const
Returns true if this element was created as part of its parent control.
virtual void setSubElement (bool subElement)
Sets whether this control was created as part of its parent.
void setTabStop (bool enable)
If set to true, the focus will visit this element when using the tab key to cycle through elements.
bool isTabStop () const
Returns true if this element can be focused by navigating with the tab key.
void setTabOrder (s32 index)
Sets the priority of focus when using the tab key to navigate between a group of elements.
s32 getTabOrder () const
Returns the number in the tab order sequence.
void setTabGroup (bool isGroup)
Sets whether this element is a container for a group of elements which can be navigated using the tab key.
bool isTabGroup () const
Returns true if this element is a tab group.
IGUIElement * getTabGroup ()
Returns the container element which holds all elements in this element's tab group.
virtual bool isEnabled () const
Returns true if element is enabled.
virtual void setEnabled (bool enabled)
Sets the enabled state of this element.
virtual void setText (const wchar_t *text)
Sets the new caption of this element.
virtual const wchar_t * getText () const
Returns caption of this element.
virtual void setToolTipText (const wchar_t *text)
Sets the new caption of this element.
virtual const core::stringw & getToolTipText () const
Returns caption of this element.
virtual s32 getID () const
Returns id. Can be used to identify the element.
virtual void setID (s32 id)
Sets the id of this element.
virtual bool bringToFront (IGUIElement *child)
Brings a child to front.
virtual bool sendToBack (IGUIElement *child)
Moves a child to the back, so it's siblings are drawn on top of it.
virtual const std::list< IGUIElement * > & getChildren () const
Returns list with children of this element.
virtual IGUIElement * getElementFromId (s32 id, bool searchchildren=false) const
Finds the first element with the given id.
bool isMyChild (IGUIElement *child) const
bool getNextElement (s32 startOrder, bool reverse, bool group, IGUIElement *&first, IGUIElement *&closest, bool includeInvisible=false, bool includeDisabled=false) const
searches elements to find the closest next element to tab to
EGUI_ELEMENT_TYPE getType () const
Returns the type of the gui element.
virtual bool hasType (EGUI_ELEMENT_TYPE type) const
Returns true if the gui element supports the given type.
virtual const c8 * getTypeName () const
Returns the type name of the gui element.
virtual const c8 * getName () const
Returns the name of the element.
virtual void setName (const c8 *name)
Sets the name of the element.
virtual void setName (const core::stringc &name)
Sets the name of the element.
virtual bool acceptsIME ()
Returns whether the element takes input from the IME.
Public Member Functions inherited from irr::IEventReceiver
virtual ~IEventReceiver ()
Destructor.
Private Member Functions
void clearDeletionQueue ()
clears the deletion queue
void updateHoveredElement (core::position2d< s32 > mousePos)
void loadBuiltInFont ()
Private Attributes
SToolTip ToolTip
core::array< SFont > Fonts
core::array< SSpriteBank > Banks
video::IVideoDriver * Driver
IGUIElement * Hovered
IGUIElement * HoveredNoSubelement
IGUIElement * Focus
core::position2d< s32 > LastHoveredMousePos
IGUISkin * CurrentSkin
io::IFileSystem * FileSystem
IEventReceiver * UserReceiver
IOSOperator * Operator
u32 FocusFlags
core::array< IGUIElement * > DeletionQueue
Static Private Attributes
static const io::path DefaultFontName = "#DefaultFont"
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Member Functions inherited from irr::gui::IGUIElement
void addChildToEnd (IGUIElement *child)
void reorderChildren (std::list< IGUIElement * >::iterator from, std::list< IGUIElement * >::iterator to, const std::vector< IGUIElement * > &neworder)
void recalculateAbsolutePosition (bool recursive)
Static Protected Member Functions inherited from irr::gui::IGUIElement
template<typename Iterator >
static size_t _fastSetChecksum (Iterator begin, Iterator end)
Protected Attributes inherited from irr::gui::IGUIElement
std::list< IGUIElement * > Children
List of all children of this element.
IGUIElement * Parent
Pointer to the parent.
std::list< IGUIElement * >::iterator ParentPos
Our position in the parent list. Only valid when Parent != nullptr.
core::rect< s32 > RelativeRect
relative rect of element
core::rect< s32 > AbsoluteRect
absolute rect of element
core::rect< s32 > AbsoluteClippingRect
absolute clipping rect of element
core::rect< s32 > DesiredRect
core::rect< s32 > LastParentRect
for calculating the difference when resizing parent
core::rect< f32 > ScaleRect
relative scale of the element inside its parent
core::dimension2du MaxSize
maximum and minimum size of the element
core::dimension2du MinSize
bool IsVisible
is visible?
bool IsEnabled
is enabled?
bool IsSubElement
is a part of a larger whole and should not be serialized?
bool NoClip
does this element ignore its parent's clipping rectangle?
core::stringw Text
caption
core::stringw ToolTipText
tooltip
core::stringc Name
users can set this for identifying the element by string
s32 ID
users can set this for identifying the element by integer
bool IsTabStop
tab stop like in windows
s32 TabOrder
tab order
bool IsTabGroup
tab groups are containers like windows, use ctrl+tab to navigate
EGUI_ALIGNMENT AlignLeft
tells the element how to act when its parent is resized
EGUI_ALIGNMENT AlignRight
EGUI_ALIGNMENT AlignTop
EGUI_ALIGNMENT AlignBottom
IGUIEnvironment * Environment
GUI Environment.
EGUI_ELEMENT_TYPE Type
type of element
Detailed Description
Definition at line 20 of file CGUIEnvironment.h.
Member Function Documentation
addButton()
IGUIButton * irr::gui::CGUIEnvironment::addButton (const core::rect< s32 > & rectangle, IGUIElement * parent = 0, s32 id = -1, const wchar_t * text = 0, const wchar_t * tooltiptext = 0) override virtual
adds an button. The returned pointer must not be dropped.
adds a button. The returned pointer must not be dropped.
Implements irr::gui::IGUIEnvironment.
Definition at line 689 of file CGUIEnvironment.cpp.
References irr::IReferenceCounted::drop(), irr::gui::IGUIElement::setText(), and irr::gui::IGUIElement::setToolTipText().
addFileOpenDialog()
IGUIFileOpenDialog * irr::gui::CGUIEnvironment::addFileOpenDialog (const wchar_t * title = 0, bool modal = true, IGUIElement * parent = 0, s32 id = -1, bool restoreCWD = false, io::path::char_type * startDir = 0) override virtual
Adds a file open dialog.
adds a file open dialog. The returned pointer must not be dropped.
Definition at line 790 of file CGUIEnvironment.cpp.
References irr::IReferenceCounted::drop().
clear()
void irr::gui::CGUIEnvironment::clear () override virtual
removes all elements from the environment
clear all GUI elements
Implements irr::gui::IGUIEnvironment.
Definition at line 348 of file CGUIEnvironment.cpp.
References irr::IReferenceCounted::drop(), getRootGUIElement(), and irr::gui::IGUIElement::removeAllChildren().
createSkin()
IGUISkin * irr::gui::CGUIEnvironment::createSkin (EGUI_SKIN_TYPE type) override virtual
Creates a new GUI Skin based on a template.
Returns
Returns a pointer to the created skin. If you no longer need the skin, you should call IGUISkin::drop(). See IReferenceCounted::drop() for more information.
Implements irr::gui::IGUIEnvironment.
Definition at line 667 of file CGUIEnvironment.cpp.
References irr::gui::EGFT_BITMAP, getBuiltInFont(), irr::gui::IGUIFontBitmap::getSpriteBank(), irr::gui::IGUIFont::getType(), irr::gui::IGUISkin::setFont(), and irr::gui::IGUISkin::setSpriteBank().
Referenced by CGUIEnvironment().
getFileSystem()
io::IFileSystem * irr::gui::CGUIEnvironment::getFileSystem () const override virtual
returns pointer to the filesystem
returns the current file system
Implements irr::gui::IGUIEnvironment.
Definition at line 334 of file CGUIEnvironment.cpp.
getFocus()
IGUIElement * irr::gui::CGUIEnvironment::getFocus () const override virtual
Returns the element with the focus.
returns the element with the focus
Implements irr::gui::IGUIEnvironment.
Definition at line 269 of file CGUIEnvironment.cpp.
getHovered()
IGUIElement * irr::gui::CGUIEnvironment::getHovered () const override virtual
Returns the element last known to be under the mouse.
returns the element last known to be under the mouse cursor
Implements irr::gui::IGUIEnvironment.
Definition at line 275 of file CGUIEnvironment.cpp.
getNextElement()
IGUIElement * irr::gui::CGUIEnvironment::getNextElement (bool reverse = false, bool group = false) override virtual
Find the next element which would be selected when pressing the tab-key.
Returns the next element in the tab group starting at the focused element.
Implements irr::gui::IGUIEnvironment.
Definition at line 1043 of file CGUIEnvironment.cpp.
References irr::gui::EFF_CAN_FOCUS_DISABLED, irr::gui::IGUIElement::getNextElement(), irr::gui::IGUIElement::getParent(), irr::gui::IGUIElement::getTabGroup(), irr::gui::IGUIElement::getTabOrder(), and irr::gui::IGUIElement::isTabGroup().
Referenced by postEventFromUser().
hasFocus()
bool irr::gui::CGUIEnvironment::hasFocus (const IGUIElement * element, bool checkSubElements = false) const override virtual
Returns if the element has focus.
Returns whether the element has focus.
Implements irr::gui::IGUIEnvironment.
Definition at line 307 of file CGUIEnvironment.cpp.
OnEvent()
bool irr::gui::CGUIEnvironment::OnEvent (const SEvent & event) override virtual
called if an event happened.
called by ui if an event happened.
Reimplemented from irr::gui::IGUIElement.
Definition at line 373 of file CGUIEnvironment.cpp.
References irr::SEvent::SGUIEvent::Caller, irr::EET_GUI_EVENT, irr::EET_KEY_INPUT_EVENT, irr::EET_MOUSE_INPUT_EVENT, and irr::IEventReceiver::OnEvent().
setUserEventReceiver()
void irr::gui::CGUIEnvironment::setUserEventReceiver (IEventReceiver * evr) override virtual
This sets a new event receiver for gui events. Usually you do not have to use this method, it is used by the internal engine.
Implements irr::gui::IGUIEnvironment.
Definition at line 549 of file CGUIEnvironment.cpp.
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CGUIEnvironment.h
lib/irrlichtmt/source/Irrlicht/CGUIEnvironment.cpp