Three Cubes Game: GUIEditBoxWithScrollBar Class Reference
GUIEditBoxWithScrollBar Class Reference
Public Member Functions
GUIEditBoxWithScrollBar (const wchar_t *text, bool border, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle, bool writable=true, bool has_vscrollbar=true)
constructor
virtual ~GUIEditBoxWithScrollBar ()
destructor
virtual void setDrawBackground (bool draw)
Sets whether to draw the background.
virtual void draw ()
draws the element and its children
virtual void updateAbsolutePosition ()
Updates the absolute position, splits text if required.
virtual void setBackgroundColor (const video::SColor &bg_color)
Change the background color.
virtual bool isDrawBackgroundEnabled () const
Checks if background drawing is enabled.
virtual bool isDrawBorderEnabled () const
Checks if border drawing is enabled.
virtual void setCursorChar (const wchar_t cursorChar)
Set the character used for the cursor.
virtual wchar_t getCursorChar () const
Get the character used for the cursor.
virtual void setCursorBlinkTime (irr::u32 timeMs)
Set the blinktime for the cursor. 2x blinktime is one full cycle.
virtual irr::u32 getCursorBlinkTime () const
Get the cursor blinktime.
Public Member Functions inherited from GUIEditBox
GUIEditBox (IGUIEnvironment *environment, IGUIElement *parent, s32 id, core::rect< s32 > rectangle, bool border, bool writable)
virtual void setOverrideFont (IGUIFont *font=0)
Sets another skin independent font.
virtual IGUIFont * getOverrideFont () const
Gets the override font (if any)
virtual IGUIFont * getActiveFont () const
Get the font which is used right now for drawing.
virtual void setOverrideColor (video::SColor color)
Sets another color for the text.
virtual video::SColor getOverrideColor () const
Gets the override color.
virtual void enableOverrideColor (bool enable)
Sets if the text should use the overide color or the color in the gui skin.
virtual bool isOverrideColorEnabled (void) const
Checks if an override color is enabled.
virtual void setWordWrap (bool enable)
Enables or disables word wrap for using the edit box as multiline text editor.
virtual bool isWordWrapEnabled () const
virtual void setDrawBorder (bool border)
Turns the border on or off.
virtual void setMultiLine (bool enable)
Enables or disables newlines.
virtual bool isMultiLineEnabled () const
virtual void setAutoScroll (bool enable)
virtual bool isAutoScrollEnabled () const
virtual void setPasswordBox (bool passwordBox, wchar_t passwordChar=L' *')
Sets whether the edit box is a password box. Setting this to true will.
virtual bool isPasswordBox () const
Returns true if the edit box is currently a password box.
virtual void setTextAlignment (EGUI_ALIGNMENT horizontal, EGUI_ALIGNMENT vertical)
Sets text justification.
virtual void setText (const wchar_t *text)
Sets the new caption of this element.
virtual void setMax (u32 max)
virtual u32 getMax () const
Returns maximum amount of characters, previously set by setMax();.
virtual core::dimension2du getTextDimension ()
virtual void setWritable (bool can_write_text)
set true if this EditBox is writable
virtual bool OnEvent (const SEvent &event)
called if an event happened.
virtual bool acceptsIME ()
Returns whether the element takes input from the IME.
Public Member Functions inherited from irr::gui::IGUIEditBox
IGUIEditBox (IGUIEnvironment *environment, IGUIElement *parent, s32 id, core::rect< s32 > rectangle)
constructor
virtual void setMax (u32 max)=0
Sets the maximum amount of characters which may be entered in the box.
Public Member Functions inherited from irr::gui::IGUIElement
IGUIElement (EGUI_ELEMENT_TYPE type, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle)
Constructor.
virtual ~IGUIElement ()
Destructor.
IGUIElement * getParent () const
Returns parent of this element.
core::rect< s32 > getRelativePosition () const
Returns the relative rectangle of this element.
void setRelativePosition (const core::rect< s32 > &r)
Sets the relative rectangle of this element.
void setRelativePosition (const core::position2di &position)
Sets the relative rectangle of this element, maintaining its current width and height.
void setRelativePositionProportional (const core::rect< f32 > &r)
Sets the relative rectangle of this element as a proportion of its parent's area.
core::rect< s32 > getAbsolutePosition () const
Gets the absolute rectangle of this element.
core::rect< s32 > getAbsoluteClippingRect () const
Returns the visible area of the element.
void setNotClipped (bool noClip)
Sets whether the element will ignore its parent's clipping rectangle.
bool isNotClipped () const
Gets whether the element will ignore its parent's clipping rectangle.
void setMaxSize (core::dimension2du size)
Sets the maximum size allowed for this element.
void setMinSize (core::dimension2du size)
Sets the minimum size allowed for this element.
void setAlignment (EGUI_ALIGNMENT left, EGUI_ALIGNMENT right, EGUI_ALIGNMENT top, EGUI_ALIGNMENT bottom)
The alignment defines how the borders of this element will be positioned when the parent element is resized.
EGUI_ALIGNMENT getAlignLeft () const
How left element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignRight () const
How right element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignTop () const
How top element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignBottom () const
How bottom element border is aligned when parent is resized.
virtual IGUIElement * getElementFromPoint (const core::position2d< s32 > &point)
Returns the topmost GUI element at the specific position.
virtual bool isPointInside (const core::position2d< s32 > &point) const
Returns true if a point is within this element.
virtual void addChild (IGUIElement *child)
Adds a GUI element as new child of this element.
virtual void removeChild (IGUIElement *child)
Removes a child.
virtual void removeAllChildren ()
Removes all children.
virtual void remove ()
Removes this element from its parent.
virtual void OnPostRender (u32 timeMs)
animate the element and its children.
virtual void move (core::position2d< s32 > absoluteMovement)
Moves this element.
virtual bool isVisible () const
Returns true if element is visible.
virtual bool isTrulyVisible () const
Check whether the element is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool visible)
Sets the visible state of this element.
virtual bool isSubElement () const
Returns true if this element was created as part of its parent control.
virtual void setSubElement (bool subElement)
Sets whether this control was created as part of its parent.
void setTabStop (bool enable)
If set to true, the focus will visit this element when using the tab key to cycle through elements.
bool isTabStop () const
Returns true if this element can be focused by navigating with the tab key.
void setTabOrder (s32 index)
Sets the priority of focus when using the tab key to navigate between a group of elements.
s32 getTabOrder () const
Returns the number in the tab order sequence.
void setTabGroup (bool isGroup)
Sets whether this element is a container for a group of elements which can be navigated using the tab key.
bool isTabGroup () const
Returns true if this element is a tab group.
IGUIElement * getTabGroup ()
Returns the container element which holds all elements in this element's tab group.
virtual bool isEnabled () const
Returns true if element is enabled.
virtual void setEnabled (bool enabled)
Sets the enabled state of this element.
virtual const wchar_t * getText () const
Returns caption of this element.
virtual void setToolTipText (const wchar_t *text)
Sets the new caption of this element.
virtual const core::stringw & getToolTipText () const
Returns caption of this element.
virtual s32 getID () const
Returns id. Can be used to identify the element.
virtual void setID (s32 id)
Sets the id of this element.
virtual bool bringToFront (IGUIElement *child)
Brings a child to front.
virtual bool sendToBack (IGUIElement *child)
Moves a child to the back, so it's siblings are drawn on top of it.
virtual const std::list< IGUIElement * > & getChildren () const
Returns list with children of this element.
virtual IGUIElement * getElementFromId (s32 id, bool searchchildren=false) const
Finds the first element with the given id.
bool isMyChild (IGUIElement *child) const
bool getNextElement (s32 startOrder, bool reverse, bool group, IGUIElement *&first, IGUIElement *&closest, bool includeInvisible=false, bool includeDisabled=false) const
searches elements to find the closest next element to tab to
EGUI_ELEMENT_TYPE getType () const
Returns the type of the gui element.
virtual bool hasType (EGUI_ELEMENT_TYPE type) const
Returns true if the gui element supports the given type.
virtual const c8 * getTypeName () const
Returns the type name of the gui element.
virtual const c8 * getName () const
Returns the name of the element.
virtual void setName (const c8 *name)
Sets the name of the element.
virtual void setName (const core::stringc &name)
Sets the name of the element.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::IEventReceiver
virtual ~IEventReceiver ()
Destructor.
Protected Member Functions
virtual void breakText ()
Breaks the single text line.
virtual void setTextRect (s32 line)
sets the area of the given line
void calculateScrollPos ()
calculates the current scroll position
void calculateFrameRect ()
calculated the FrameRect
void createVScrollBar ()
create a Vertical ScrollBar
s32 getCursorPos (s32 x, s32 y)
Protected Member Functions inherited from GUIEditBox
void setTextMarkers (s32 begin, s32 end)
set text markers
void sendGuiEvent (EGUI_EVENT_TYPE type)
send some gui event to parent
bool processKey (const SEvent &event)
virtual void inputString (const core::stringw &str)
virtual void inputChar (wchar_t c)
s32 getLineFromPos (s32 pos)
returns the line number that the cursor is on
void updateVScrollBar ()
update the vertical scrollBar (visibilty & position)
Protected Member Functions inherited from irr::gui::IGUIElement
void addChildToEnd (IGUIElement *child)
void reorderChildren (std::list< IGUIElement * >::iterator from, std::list< IGUIElement * >::iterator to, const std::vector< IGUIElement * > &neworder)
void recalculateAbsolutePosition (bool recursive)
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
bool m_background
bool m_bg_color_used
video::SColor m_bg_color
Protected Attributes inherited from GUIEditBox
gui::IGUIFont * m_override_font = nullptr
bool m_override_color_enabled = false
bool m_word_wrap = false
bool m_multiline = false
bool m_autoscroll = true
bool m_border
bool m_passwordbox = false
wchar_t m_passwordchar = L'*'
std::vector< core::stringw > m_broken_text
std::vector< s32 > m_broken_text_positions
EGUI_ALIGNMENT m_halign = EGUIA_UPPERLEFT
EGUI_ALIGNMENT m_valign = EGUIA_CENTER
u32 m_blink_start_time = 0
s32 m_cursor_pos = 0
s32 m_hscroll_pos = 0
s32 m_vscroll_pos = 0
u32 m_max = 0
video::SColor m_override_color = video::SColor(101, 255, 255, 255)
core::rect< s32 > m_current_text_rect = core::rect<s32>(0, 0, 1, 1)
bool m_writable
bool m_mouse_marking = false
s32 m_mark_begin = 0
s32 m_mark_end = 0
gui::IGUIFont * m_last_break_font = nullptr
IOSOperator * m_operator = nullptr
core::rect< s32 > m_frame_rect
u32 m_scrollbar_width = 0
GUIScrollBar * m_vscrollbar = nullptr
Protected Attributes inherited from irr::gui::IGUIElement
std::list< IGUIElement * > Children
List of all children of this element.
IGUIElement * Parent
Pointer to the parent.
std::list< IGUIElement * >::iterator ParentPos
Our position in the parent list. Only valid when Parent != nullptr.
core::rect< s32 > RelativeRect
relative rect of element
core::rect< s32 > AbsoluteRect
absolute rect of element
core::rect< s32 > AbsoluteClippingRect
absolute clipping rect of element
core::rect< s32 > DesiredRect
core::rect< s32 > LastParentRect
for calculating the difference when resizing parent
core::rect< f32 > ScaleRect
relative scale of the element inside its parent
core::dimension2du MaxSize
maximum and minimum size of the element
core::dimension2du MinSize
bool IsVisible
is visible?
bool IsEnabled
is enabled?
bool IsSubElement
is a part of a larger whole and should not be serialized?
bool NoClip
does this element ignore its parent's clipping rectangle?
core::stringw Text
caption
core::stringw ToolTipText
tooltip
core::stringc Name
users can set this for identifying the element by string
s32 ID
users can set this for identifying the element by integer
bool IsTabStop
tab stop like in windows
s32 TabOrder
tab order
bool IsTabGroup
tab groups are containers like windows, use ctrl+tab to navigate
EGUI_ALIGNMENT AlignLeft
tells the element how to act when its parent is resized
EGUI_ALIGNMENT AlignRight
EGUI_ALIGNMENT AlignTop
EGUI_ALIGNMENT AlignBottom
IGUIEnvironment * Environment
GUI Environment.
EGUI_ELEMENT_TYPE Type
type of element
Additional Inherited Members
Static Protected Member Functions inherited from irr::gui::IGUIElement
template<typename Iterator >
static size_t _fastSetChecksum (Iterator begin, Iterator end)
Detailed Description
Definition at line 10 of file guiEditBoxWithScrollbar.h.
Member Function Documentation
createVScrollBar()
void GUIEditBoxWithScrollBar::createVScrollBar () protected
create a Vertical ScrollBar
create a vertical scroll bar
Definition at line 617 of file guiEditBoxWithScrollbar.cpp.
References irr::gui::IGUIElement::Environment, irr::gui::IGUIFont::getDimension(), irr::gui::IGUISkin::getFont(), irr::gui::IGUIElement::getParent(), irr::gui::IGUISkin::getSize(), irr::gui::IGUIEnvironment::getSkin(), irr::core::rect< T >::getWidth(), irr::core::dimension2d< T >::Height, irr::gui::IGUIElement::setVisible(), and irr::core::rect< T >::UpperLeftCorner.
Referenced by GUIEditBoxWithScrollBar().
isDrawBackgroundEnabled()
bool GUIEditBoxWithScrollBar::isDrawBackgroundEnabled () const virtual
Checks if background drawing is enabled.
Returns
true if background drawing is enabled, false otherwise
Implements irr::gui::IGUIEditBox.
Definition at line 655 of file guiEditBoxWithScrollbar.cpp.
isDrawBorderEnabled()
bool GUIEditBoxWithScrollBar::isDrawBorderEnabled () const virtual
Checks if border drawing is enabled.
Returns
true if border drawing is enabled, false otherwise
Reimplemented from GUIEditBox.
Definition at line 656 of file guiEditBoxWithScrollbar.cpp.
setCursorChar()
void GUIEditBoxWithScrollBar::setCursorChar (const wchar_t cursorChar) virtual
Set the character used for the cursor.
By default it's "_"
Implements irr::gui::IGUIEditBox.
Definition at line 657 of file guiEditBoxWithScrollbar.cpp.
The documentation for this class was generated from the following files:
src/gui/guiEditBoxWithScrollbar.h
src/gui/guiEditBoxWithScrollbar.cpp