Three Cubes Game: irr::video::CImageLoaderBMP Class Reference
irr::video::CImageLoaderBMP Class Reference
#include <CImageLoaderBMP.h>
Public Member Functions
CImageLoaderBMP ()
constructor
bool isALoadableFileExtension (const io::path &filename) const override
bool isALoadableFileFormat (io::IReadFile *file) const override
returns true if the file maybe is able to be loaded by this class
IImage * loadImage (io::IReadFile *file) const override
creates a surface from the file
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Member Functions
void decompress8BitRLE (u8 *&BmpData, s32 size, s32 width, s32 height, s32 pitch) const
void decompress4BitRLE (u8 *&BmpData, s32 size, s32 width, s32 height, s32 pitch) const
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Surface Loader for Windows bitmaps
Definition at line 61 of file CImageLoaderBMP.h.
Member Function Documentation
isALoadableFileExtension()
bool irr::video::CImageLoaderBMP::isALoadableFileExtension (const io::path & filename) const override virtual
returns true if the file maybe is able to be loaded by this class based on the file extension (e.g. ".tga")
Implements irr::video::IImageLoader.
Definition at line 31 of file CImageLoaderBMP.cpp.
References irr::core::hasFileExtension().
loadImage()
IImage * irr::video::CImageLoaderBMP::loadImage (io::IReadFile * file) const override virtual
creates a surface from the file
return if the header is false
Implements irr::video::IImageLoader.
Definition at line 217 of file CImageLoaderBMP.cpp.
References irr::video::checkImageDimensions(), irr::video::CColorConverter::convert16BitTo16Bit(), irr::video::CColorConverter::convert1BitTo16Bit(), irr::video::CColorConverter::convert24BitTo24Bit(), irr::video::CColorConverter::convert32BitTo32Bit(), irr::video::CColorConverter::convert4BitTo16Bit(), irr::video::CColorConverter::convert8BitTo16Bit(), irr::video::ECF_A1R5G5B5, irr::video::ECF_A8R8G8B8, irr::video::ECF_R8G8B8, irr::ELL_ERROR, irr::video::IImage::getData(), irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CImageLoaderBMP.h
lib/irrlichtmt/source/Irrlicht/CImageLoaderBMP.cpp