Three Cubes Game: RenderPipeline Class Reference
RenderPipeline Class Reference
#include <pipeline.h>
Public Member Functions
RenderStep * addStep (RenderStep *step)
template<typename T >
T * own (std::unique_ptr< T > &&object)
template<typename T , typename... Args>
T * createOwned (Args &&... args)
template<typename T , typename... Args>
T * addStep (Args &&... args)
RenderSource * getInput ()
RenderTarget * getOutput ()
v2f getScale ()
void setScale (v2f value)
virtual void reset (PipelineContext &context) override
virtual void run (PipelineContext &context) override
virtual void setRenderSource (RenderSource *source) override
virtual void setRenderTarget (RenderTarget *target) override
Private Attributes
std::vector< RenderStep * > m_pipeline
std::vector< std::unique_ptr< RenderPipelineObject > > m_objects
DynamicSource m_input
DynamicTarget m_output
v2f scale { 1.0f, 1.0f }
Detailed Description
Render Pipeline provides a flexible way to execute rendering steps in the engine.
RenderPipeline also implements
See also
RenderStep, allowing for nesting of the pipelines.
Definition at line 357 of file pipeline.h.
Member Function Documentation
addStep() [1/2]
template<typename T , typename... Args> T* RenderPipeline::addStep (Args &&... args) inline
Create and add a step managed by the pipeline and return a pointer to the step for further configuration.
Template Parameters
T Type of the step to be added.
Args Types of the constructor parameters
Parameters
args Constructor parameters
Returns
RenderStep* Pointer to the created step for further configuration.
Definition at line 410 of file pipeline.h.
References addStep(), and own().
addStep() [2/2]
RenderStep* RenderPipeline::addStep (RenderStep * step) inline
Add a step to the end of the pipeline
Parameters
step reference to a
See also
RenderStep implementation.
Definition at line 365 of file pipeline.h.
Referenced by addStep().
createOwned()
template<typename T , typename... Args> T* RenderPipeline::createOwned (Args &&... args) inline
Create a new object that will be managed by the pipeline
Template Parameters
T type of the object to be created
Args types of constructor arguments
Parameters
args constructor arguments
Returns
T* pointer to the newly created object
Definition at line 396 of file pipeline.h.
References own().
own()
template<typename T > T* RenderPipeline::own (std::unique_ptr< T > && object) inline
Capture ownership of a dynamically created
See also
RenderStep instance.
RenderPipeline will delete the instance when the pipeline is destroyed.
Parameters
step reference to the instance.
Returns
RenderStep* value of the 'step' parameter.
Definition at line 380 of file pipeline.h.
Referenced by addStep(), and createOwned().
run()
void RenderPipeline::run (PipelineContext & context) override virtual
Runs the step. This method is invoked by the pipeline.
Implements RenderStep.
Definition at line 277 of file pipeline.cpp.
References irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
setRenderSource()
void RenderPipeline::setRenderSource (RenderSource * source) override virtual
Assigns render source to this step.
Parameters
source source of rendering information
Implements RenderStep.
Definition at line 291 of file pipeline.cpp.
setRenderTarget()
void RenderPipeline::setRenderTarget (RenderTarget * target) override virtual
Assigned render target to this step.
Parameters
target render target to send output to.
Implements RenderStep.
Definition at line 296 of file pipeline.cpp.
The documentation for this class was generated from the following files:
src/client/render/pipeline.h
src/client/render/pipeline.cpp