Three Cubes Game: irr::CIrrDeviceStub Class Reference
irr::CIrrDeviceStub Class Reference
Stub for an Irrlicht Device implementation.
#include <CIrrDeviceStub.h>
Classes
struct SMouseMultiClicks
Public Member Functions
CIrrDeviceStub (const SIrrlichtCreationParameters &param)
constructor
virtual ~CIrrDeviceStub ()
destructor
video::IVideoDriver * getVideoDriver () override
returns the video driver
io::IFileSystem * getFileSystem () override
return file system
gui::IGUIEnvironment * getGUIEnvironment () override
returns the gui environment
scene::ISceneManager * getSceneManager () override
returns the scene manager
gui::ICursorControl * getCursorControl () override
video::IContextManager * getContextManager () override
return the context manager
ITimer * getTimer () override
Returns a pointer to the ITimer object. With it the current Time can be received.
bool setWindowIcon (const video::IImage *img) override
Sets the window icon.
const char * getVersion () const override
Returns the version of the engine.
bool postEventFromUser (const SEvent &event) override
send the event to the right receiver
void setEventReceiver (IEventReceiver *receiver) override
Sets a new event receiver to receive events.
IEventReceiver * getEventReceiver () override
Returns pointer to the current event receiver. Returns 0 if there is none.
void setInputReceivingSceneManager (scene::ISceneManager *sceneManager) override
Sets the input receiving scene manager.
ILogger * getLogger () override
Returns a pointer to the logger.
IOSOperator * getOSOperator () override
Returns the operation system opertator object.
bool isWindowMaximized () const override
Checks if the window is maximized.
bool isFullscreen () const override
Checks if the window is running in fullscreen mode.
video::ECOLOR_FORMAT getColorFormat () const override
get color format of the current window
bool activateJoysticks (core::array< SJoystickInfo > &joystickInfo) override
Activate any joysticks, and generate events for them.
bool activateAccelerometer (float updateInterval=0.016666f) override
Activate accelerometer.
bool deactivateAccelerometer () override
Deactivate accelerometer.
bool isAccelerometerActive () override
Is accelerometer active.
bool isAccelerometerAvailable () override
Is accelerometer available.
bool activateGyroscope (float updateInterval=0.016666f) override
Activate gyroscope.
bool deactivateGyroscope () override
Deactivate gyroscope.
bool isGyroscopeActive () override
Is gyroscope active.
bool isGyroscopeAvailable () override
Is gyroscope available.
bool activateDeviceMotion (float updateInterval=0.016666f) override
Activate device motion.
bool deactivateDeviceMotion () override
Deactivate device motion.
bool isDeviceMotionActive () override
Is device motion active.
bool isDeviceMotionAvailable () override
Is device motion available.
void setDoubleClickTime (u32 timeMs) override
Set the maximal elapsed time between 2 clicks to generate doubleclicks for the mouse. It also affects tripleclick behavior.
u32 getDoubleClickTime () const override
Get the maximal elapsed time between 2 clicks to generate double- and tripleclicks for the mouse.
void clearSystemMessages () override
Remove all messages pending in the system message loop.
float getDisplayDensity () const override
Get the display density in dots per inch.
void setWindowSize (const irr::core::dimension2d< u32 > &size) override
Resize the render window.
Public Member Functions inherited from irr::IrrlichtDevice
virtual bool run ()=0
Runs the device.
virtual void yield ()=0
Cause the device to temporarily pause execution and let other processes run.
virtual void sleep (u32 timeMs, bool pauseTimer=false)=0
Pause execution and let other processes to run for a specified amount of time.
virtual void setWindowCaption (const wchar_t *text)=0
Sets the caption of the window.
virtual bool isWindowActive () const =0
Returns if the window is active.
virtual bool isWindowFocused () const =0
Checks if the Irrlicht window has the input focus.
virtual bool isWindowMinimized () const =0
Checks if the Irrlicht window is minimized.
virtual void closeDevice ()=0
Notifies the device that it should close itself.
virtual void setResizable (bool resize=false)=0
Sets if the window should be resizable in windowed mode.
virtual void minimizeWindow ()=0
Minimizes the window if possible.
virtual void maximizeWindow ()=0
Maximizes the window if possible.
virtual void restoreWindow ()=0
Restore the window to normal size if possible.
virtual core::position2di getWindowPosition ()=0
Get the position of the frame on-screen.
virtual E_DEVICE_TYPE getType () const =0
Get the type of the device.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Protected Member Functions
void createGUIAndScene ()
bool checkVersion (const char *version)
checks version of SDK and prints warning if there might be a problem
virtual u32 checkSuccessiveClicks (s32 mouseX, s32 mouseY, EMOUSE_INPUT_EVENT inputEvent)
Compares to the last call of this function to return double and triple clicks.
bool acceptsIME ()
Checks whether the input device should take input from the IME.
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
video::IVideoDriver * VideoDriver
gui::IGUIEnvironment * GUIEnvironment
scene::ISceneManager * SceneManager
ITimer * Timer
gui::ICursorControl * CursorControl
IEventReceiver * UserReceiver
CLogger * Logger
IOSOperator * Operator
io::IFileSystem * FileSystem
scene::ISceneManager * InputReceivingSceneManager
SMouseMultiClicks MouseMultiClicks
video::IContextManager * ContextManager
SIrrlichtCreationParameters CreationParams
bool Close
Additional Inherited Members
Static Public Member Functions inherited from irr::IrrlichtDevice
static bool isDriverSupported (video::E_DRIVER_TYPE driver)
Check if a driver type is supported by the engine.
Detailed Description
Stub for an Irrlicht Device implementation.
Definition at line 43 of file CIrrDeviceStub.h.
Member Function Documentation
activateAccelerometer()
bool irr::CIrrDeviceStub::activateAccelerometer (float updateInterval = 0.016666f) override virtual
Activate accelerometer.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 307 of file CIrrDeviceStub.cpp.
activateDeviceMotion()
bool irr::CIrrDeviceStub::activateDeviceMotion (float updateInterval = 0.016666f) override virtual
Activate device motion.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 355 of file CIrrDeviceStub.cpp.
activateGyroscope()
bool irr::CIrrDeviceStub::activateGyroscope (float updateInterval = 0.016666f) override virtual
Activate gyroscope.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 331 of file CIrrDeviceStub.cpp.
activateJoysticks()
bool irr::CIrrDeviceStub::activateJoysticks (core::array< SJoystickInfo > & joystickInfo) override virtual
Activate any joysticks, and generate events for them.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 301 of file CIrrDeviceStub.cpp.
checkSuccessiveClicks()
u32 irr::CIrrDeviceStub::checkSuccessiveClicks (s32 mouseX, s32 mouseY, EMOUSE_INPUT_EVENT inputEvent) protected virtual
Compares to the last call of this function to return double and triple clicks.
Needed for win32 device event handling
Returns
Returns only 1,2 or 3. A 4th click will start with 1 again.
Definition at line 186 of file CIrrDeviceStub.cpp.
References irr::core::abs_(), irr::ITimer::getRealTime(), and getTimer().
checkVersion()
bool irr::CIrrDeviceStub::checkVersion (const char * version) protected
checks version of SDK and prints warning if there might be a problem
checks version of sdk and prints warning if there might be a problem
Definition at line 166 of file CIrrDeviceStub.cpp.
References irr::core::string< T >::c_str(), irr::ELL_WARNING, and getVersion().
Referenced by CIrrDeviceStub().
deactivateAccelerometer()
bool irr::CIrrDeviceStub::deactivateAccelerometer () override virtual
Deactivate accelerometer.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 313 of file CIrrDeviceStub.cpp.
deactivateDeviceMotion()
bool irr::CIrrDeviceStub::deactivateDeviceMotion () override virtual
Deactivate device motion.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 361 of file CIrrDeviceStub.cpp.
deactivateGyroscope()
bool irr::CIrrDeviceStub::deactivateGyroscope () override virtual
Deactivate gyroscope.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 337 of file CIrrDeviceStub.cpp.
getColorFormat()
video::ECOLOR_FORMAT irr::CIrrDeviceStub::getColorFormat () const override virtual
get color format of the current window
returns color format
Implements irr::IrrlichtDevice.
Definition at line 295 of file CIrrDeviceStub.cpp.
References irr::video::ECF_R5G6B5.
getCursorControl()
gui::ICursorControl * irr::CIrrDeviceStub::getCursorControl () override virtual
Returns
Returns a pointer to the mouse cursor control interface.
Implements irr::IrrlichtDevice.
Definition at line 153 of file CIrrDeviceStub.cpp.
getEventReceiver()
IEventReceiver * irr::CIrrDeviceStub::getEventReceiver () override virtual
Returns pointer to the current event receiver. Returns 0 if there is none.
Returns poinhter to the current event receiver. Returns 0 if there is none.
Implements irr::IrrlichtDevice.
Definition at line 248 of file CIrrDeviceStub.cpp.
getLogger()
ILogger * irr::CIrrDeviceStub::getLogger () override virtual
Returns a pointer to the logger.
Returns
Returns a pointer to the logger.
Implements irr::IrrlichtDevice.
Definition at line 255 of file CIrrDeviceStub.cpp.
getTimer()
ITimer * irr::CIrrDeviceStub::getTimer () override virtual
Returns a pointer to the ITimer object. With it the current Time can be received.
Returns
Returns a pointer to the ITimer object. With it the current Time can be received.
Implements irr::IrrlichtDevice.
Definition at line 133 of file CIrrDeviceStub.cpp.
Referenced by checkSuccessiveClicks().
isAccelerometerActive()
bool irr::CIrrDeviceStub::isAccelerometerActive () override virtual
Is accelerometer active.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 319 of file CIrrDeviceStub.cpp.
isAccelerometerAvailable()
bool irr::CIrrDeviceStub::isAccelerometerAvailable () override virtual
Is accelerometer available.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 325 of file CIrrDeviceStub.cpp.
isDeviceMotionActive()
bool irr::CIrrDeviceStub::isDeviceMotionActive () override virtual
Is device motion active.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 367 of file CIrrDeviceStub.cpp.
isDeviceMotionAvailable()
bool irr::CIrrDeviceStub::isDeviceMotionAvailable () override virtual
Is device motion available.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 373 of file CIrrDeviceStub.cpp.
isGyroscopeActive()
bool irr::CIrrDeviceStub::isGyroscopeActive () override virtual
Is gyroscope active.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 343 of file CIrrDeviceStub.cpp.
isGyroscopeAvailable()
bool irr::CIrrDeviceStub::isGyroscopeAvailable () override virtual
Is gyroscope available.
No-op in this implementation.
Implements irr::IrrlichtDevice.
Definition at line 349 of file CIrrDeviceStub.cpp.
setDoubleClickTime()
void irr::CIrrDeviceStub::setDoubleClickTime (u32 timeMs) override virtual
Set the maximal elapsed time between 2 clicks to generate doubleclicks for the mouse. It also affects tripleclick behavior.
Set the maximal elapsed time between 2 clicks to generate doubleclicks for the mouse. It also affects tripleclick behavior. When set to 0 no double- and tripleclicks will be generated.
Implements irr::IrrlichtDevice.
Definition at line 379 of file CIrrDeviceStub.cpp.
setInputReceivingSceneManager()
void irr::CIrrDeviceStub::setInputReceivingSceneManager (scene::ISceneManager * sceneManager) override virtual
Sets the input receiving scene manager.
If set to null, the main scene manager (returned by GetSceneManager()) will receive the input
Implements irr::IrrlichtDevice.
Definition at line 269 of file CIrrDeviceStub.cpp.
References irr::IReferenceCounted::drop(), and irr::IReferenceCounted::grab().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CIrrDeviceStub.h
lib/irrlichtmt/source/Irrlicht/CIrrDeviceStub.cpp