Three Cubes Game: irr::scene::CCameraSceneNode Class Reference
irr::scene::CCameraSceneNode Class Reference
Public Member Functions
CCameraSceneNode (ISceneNode *parent, ISceneManager *mgr, s32 id, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &lookat=core::vector3df(0, 0, 100))
constructor
void setProjectionMatrix (const core::matrix4 &projection, bool isOrthogonal=false) override
Sets the projection matrix of the camera.
const core::matrix4 & getProjectionMatrix () const override
const core::matrix4 & getViewMatrix () const override
void setViewMatrixAffector (const core::matrix4 &affector) override
Sets a custom view matrix affector.
const core::matrix4 & getViewMatrixAffector () const override
Gets the custom view matrix affector.
bool OnEvent (const SEvent &event) override
void setTarget (const core::vector3df &pos) override
Sets the look at target of the camera.
void setRotation (const core::vector3df &rotation) override
Sets the rotation of the node.
const core::vector3df & getTarget () const override
Gets the current look at target of the camera.
void setUpVector (const core::vector3df &pos) override
const core::vector3df & getUpVector () const override
f32 getNearValue () const override
f32 getFarValue () const override
f32 getAspectRatio () const override
f32 getFOV () const override
void setNearValue (f32 zn) override
Sets the value of the near clipping plane. (default: 1.0f)
void setFarValue (f32 zf) override
Sets the value of the far clipping plane (default: 2000.0f)
void setAspectRatio (f32 aspect) override
Sets the aspect ratio (default: 4.0f / 3.0f)
void setFOV (f32 fovy) override
Sets the field of view (Default: PI / 3.5f)
void OnRegisterSceneNode () override
PreRender event.
void render () override
Render.
void updateMatrices () override
Update.
const core::aabbox3d< f32 > & getBoundingBox () const override
Returns the axis aligned bounding box of this node.
const SViewFrustum * getViewFrustum () const override
Returns the view area.
void setInputReceiverEnabled (bool enabled) override
Disables or enables the camera to get key or mouse inputs.
bool isInputReceiverEnabled () const override
Returns if the input receiver of the camera is currently enabled.
ESCENE_NODE_TYPE getType () const override
Returns type of the scene node.
void bindTargetAndRotation (bool bound) override
Binds the camera scene node's rotation to its target position and vice versa, or unbinds them.
bool getTargetAndRotationBinding (void) const override
Queries if the camera scene node's rotation and its target position are bound together.
ISceneNode * clone (ISceneNode *newParent=0, ISceneManager *newManager=0) override
Creates a clone of this scene node and its children.
Public Member Functions inherited from irr::scene::ICameraSceneNode
ICameraSceneNode (ISceneNode *parent, ISceneManager *mgr, s32 id, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f))
Constructor.
virtual bool isOrthogonal () const
Checks if a camera is orthogonal.
Public Member Functions inherited from irr::scene::ISceneNode
ISceneNode (ISceneNode *parent, ISceneManager *mgr, s32 id=-1, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f))
Constructor.
virtual ~ISceneNode ()
Destructor.
virtual void OnAnimate (u32 timeMs)
OnAnimate() is called just before rendering the whole scene.
virtual const c8 * getName () const
Returns the name of the node.
virtual void setName (const c8 *name)
Sets the name of the node.
virtual void setName (const core::stringc &name)
Sets the name of the node.
virtual const core::aabbox3d< f32 > getTransformedBoundingBox () const
Get the axis aligned, transformed and animated absolute bounding box of this node.
virtual void getTransformedBoundingBoxEdges (core::array< core::vector3d< f32 > > &edges) const
virtual const core::matrix4 & getAbsoluteTransformation () const
Get the absolute transformation of the node. Is recalculated every OnAnimate()-call.
virtual core::matrix4 getRelativeTransformation () const
Returns the relative transformation of the scene node.
virtual bool isVisible () const
Returns whether the node should be visible (if all of its parents are visible).
virtual bool isTrulyVisible () const
Check whether the node is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool isVisible)
Sets if the node should be visible or not.
virtual s32 getID () const
Get the id of the scene node.
virtual void setID (s32 id)
Sets the id of the scene node.
virtual void addChild (ISceneNode *child)
Adds a child to this scene node.
virtual bool removeChild (ISceneNode *child)
Removes a child from this scene node.
virtual void removeAll ()
Removes all children of this scene node.
virtual void remove ()
Removes this scene node from the scene.
virtual video::SMaterial & getMaterial (u32 num)
Returns the material based on the zero based index i.
virtual u32 getMaterialCount () const
Get amount of materials used by this scene node.
void setMaterialFlag (video::E_MATERIAL_FLAG flag, bool newvalue)
Sets all material flags at once to a new value.
void setMaterialTexture (u32 textureLayer, video::ITexture *texture)
Sets the texture of the specified layer in all materials of this scene node to the new texture.
void setMaterialType (video::E_MATERIAL_TYPE newType)
Sets the material type of all materials in this scene node to a new material type.
virtual const core::vector3df & getScale () const
Gets the scale of the scene node relative to its parent.
virtual void setScale (const core::vector3df &scale)
Sets the relative scale of the scene node.
virtual const core::vector3df & getRotation () const
Gets the rotation of the node relative to its parent.
virtual const core::vector3df & getPosition () const
Gets the position of the node relative to its parent.
virtual void setPosition (const core::vector3df &newpos)
Sets the position of the node relative to its parent.
virtual core::vector3df getAbsolutePosition () const
Gets the absolute position of the node in world coordinates.
void setAutomaticCulling (u32 state)
Set a culling style or disable culling completely.
u32 getAutomaticCulling () const
Gets the automatic culling state.
virtual void setDebugDataVisible (u32 state)
Sets if debug data like bounding boxes should be drawn.
u32 isDebugDataVisible () const
Returns if debug data like bounding boxes are drawn.
void setIsDebugObject (bool debugObject)
Sets if this scene node is a debug object.
bool isDebugObject () const
Returns if this scene node is a debug object.
const std::list< ISceneNode * > & getChildren () const
Returns a const reference to the list of all children.
virtual void setParent (ISceneNode *newParent)
Changes the parent of the scene node.
virtual void updateAbsolutePosition ()
Updates the absolute position based on the relative and the parents position.
scene::ISceneNode * getParent () const
Returns the parent of this scene node.
virtual ISceneManager * getSceneManager (void) const
Retrieve the scene manager for this node.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::IEventReceiver
virtual ~IEventReceiver ()
Destructor.
Protected Member Functions
void recalculateProjectionMatrix ()
void recalculateViewArea ()
Protected Member Functions inherited from irr::scene::ICameraSceneNode
void cloneMembers (const ICameraSceneNode *toCopyFrom)
Protected Member Functions inherited from irr::scene::ISceneNode
void cloneMembers (ISceneNode *toCopyFrom, ISceneManager *newManager)
A clone function for the ISceneNode members.
void setSceneManager (ISceneManager *newManager)
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Protected Attributes
core::aabbox3d< f32 > BoundingBox
core::vector3df Target
core::vector3df UpVector
f32 Fovy
f32 Aspect
f32 ZNear
f32 ZFar
SViewFrustum ViewArea
core::matrix4 Affector
bool InputReceiverEnabled
bool TargetAndRotationAreBound
bool HasD3DStyleProjectionMatrix
Protected Attributes inherited from irr::scene::ICameraSceneNode
bool IsOrthogonal
Protected Attributes inherited from irr::scene::ISceneNode
core::stringc Name
Name of the scene node.
core::matrix4 AbsoluteTransformation
Absolute transformation of the node.
core::vector3df RelativeTranslation
Relative translation of the scene node.
core::vector3df RelativeRotation
Relative rotation of the scene node.
core::vector3df RelativeScale
Relative scale of the scene node.
ISceneNode * Parent
Pointer to the parent.
std::list< ISceneNode * > Children
List of all children of this node.
ISceneManager * SceneManager
Pointer to the scene manager.
s32 ID
ID of the node.
u32 AutomaticCullingState
Automatic culling state.
u32 DebugDataVisible
Flag if debug data should be drawn, such as Bounding Boxes.
bool IsVisible
Is the node visible?
bool IsDebugObject
Is debug object?
Detailed Description
Definition at line 16 of file CCameraSceneNode.h.
Member Function Documentation
bindTargetAndRotation()
void irr::scene::CCameraSceneNode::bindTargetAndRotation (bool bound) override virtual
Binds the camera scene node's rotation to its target position and vice versa, or unbinds them.
Set the binding between the camera's rotation adn target.
Implements irr::scene::ICameraSceneNode.
Definition at line 304 of file CCameraSceneNode.cpp.
getAspectRatio()
f32 irr::scene::CCameraSceneNode::getAspectRatio () const override virtual
Get the aspect ratio of the camera.
Returns
The aspect ratio of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 182 of file CCameraSceneNode.cpp.
getBoundingBox()
const core::aabbox3d< f32 > & irr::scene::CCameraSceneNode::getBoundingBox () const override virtual
Returns the axis aligned bounding box of this node.
returns the axis aligned bounding box of this node
Implements irr::scene::ISceneNode.
Definition at line 279 of file CCameraSceneNode.cpp.
getFarValue()
f32 irr::scene::CCameraSceneNode::getFarValue () const override virtual
Gets the distance from the camera to the far plane.
Returns
Value of the far plane of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 176 of file CCameraSceneNode.cpp.
getFOV()
f32 irr::scene::CCameraSceneNode::getFOV () const override virtual
Gets the field of view of the camera.
Returns
Field of view of the camera
Implements irr::scene::ICameraSceneNode.
Definition at line 188 of file CCameraSceneNode.cpp.
getNearValue()
f32 irr::scene::CCameraSceneNode::getNearValue () const override virtual
Gets distance from the camera to the near plane.
Returns
Value of the near plane of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 170 of file CCameraSceneNode.cpp.
getProjectionMatrix()
const core::matrix4 & irr::scene::CCameraSceneNode::getProjectionMatrix () const override virtual
Gets the current projection matrix of the camera
Returns
Returns the current projection matrix of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 75 of file CCameraSceneNode.cpp.
References irr::video::ETS_PROJECTION, and irr::scene::SViewFrustum::getTransform().
getTarget()
const core::vector3df & irr::scene::CCameraSceneNode::getTarget () const override virtual
Gets the current look at target of the camera.
Returns
The current look at target of the camera
Gets the current look at target of the camera
Returns
Returns the current look at target of the camera
Implements irr::scene::ICameraSceneNode.
Definition at line 148 of file CCameraSceneNode.cpp.
getTargetAndRotationBinding()
bool irr::scene::CCameraSceneNode::getTargetAndRotationBinding (void) const override virtual
Queries if the camera scene node's rotation and its target position are bound together.
Gets the binding between the camera's rotation and target.
Implements irr::scene::ICameraSceneNode.
Definition at line 311 of file CCameraSceneNode.cpp.
getUpVector()
const core::vector3df & irr::scene::CCameraSceneNode::getUpVector () const override virtual
Gets the up vector of the camera.
Returns
Returns the up vector of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 164 of file CCameraSceneNode.cpp.
getViewFrustum()
const SViewFrustum * irr::scene::CCameraSceneNode::getViewFrustum () const override virtual
Returns the view area.
returns the view frustum.
Implements irr::scene::ICameraSceneNode.
Definition at line 286 of file CCameraSceneNode.cpp.
getViewMatrix()
const core::matrix4 & irr::scene::CCameraSceneNode::getViewMatrix () const override virtual
Gets the current view matrix of the camera
Returns
Returns the current view matrix of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 83 of file CCameraSceneNode.cpp.
References irr::video::ETS_VIEW, and irr::scene::SViewFrustum::getTransform().
OnEvent()
bool irr::scene::CCameraSceneNode::OnEvent (const SEvent & event) override virtual
It is possible to send mouse and key events to the camera. Most cameras may ignore this input, but camera scene nodes which are created for example with scene::ISceneManager::addMayaCameraSceneNode or scene::ISceneManager::addMeshViewerCameraSceneNode, may want to get this input for changing their position, look at target or whatever.
It is possible to send mouse and key events to the camera. Most cameras may ignore this input, but camera scene nodes which are created for example with scene::ISceneManager::addMayaCameraSceneNode or scene::ISceneManager::addFPSCameraSceneNode, may want to get this input for changing their position, look at target or whatever.
Implements irr::scene::ICameraSceneNode.
Definition at line 111 of file CCameraSceneNode.cpp.
OnRegisterSceneNode()
void irr::scene::CCameraSceneNode::OnRegisterSceneNode () override virtual
PreRender event.
prerender
Reimplemented from irr::scene::ISceneNode.
Definition at line 232 of file CCameraSceneNode.cpp.
References irr::scene::ESNRP_CAMERA, irr::scene::ISceneManager::getActiveCamera(), irr::scene::ISceneNode::OnRegisterSceneNode(), irr::scene::ISceneManager::registerNodeForRendering(), and irr::scene::ISceneNode::SceneManager.
render()
void irr::scene::CCameraSceneNode::render () override virtual
Render.
render
Implements irr::scene::ISceneNode.
Definition at line 242 of file CCameraSceneNode.cpp.
References irr::video::ETS_PROJECTION, irr::video::ETS_VIEW, irr::scene::SViewFrustum::getTransform(), irr::scene::ISceneManager::getVideoDriver(), irr::scene::ISceneNode::SceneManager, irr::video::IVideoDriver::setTransform(), and updateMatrices().
setInputReceiverEnabled()
void irr::scene::CCameraSceneNode::setInputReceiverEnabled (bool enabled) override virtual
Disables or enables the camera to get key or mouse inputs.
Disables or enables the camera to get key or mouse inputs. If this is set to true, the camera will respond to key inputs otherwise not.
Implements irr::scene::ICameraSceneNode.
Definition at line 49 of file CCameraSceneNode.cpp.
setProjectionMatrix()
void irr::scene::CCameraSceneNode::setProjectionMatrix (const core::matrix4 & projection, bool isOrthogonal = false) override virtual
Sets the projection matrix of the camera.
The core::matrix4 class has some methods to build a projection matrix. e.g: core::matrix4::buildProjectionMatrixPerspectiveFovLH. Note that the matrix will only stay as set by this method until one of the following Methods are called: setNearValue, setFarValue, setAspectRatio, setFOV.
Parameters
projection The new projection matrix of the camera.
isOrthogonal Set this to true if the matrix is an orthogonal one (e.g. from matrix4::buildProjectionMatrixOrthoLH().
The core::matrix4 class has some methods to build a projection matrix. e.g: core::matrix4::buildProjectionMatrixPerspectiveFovLH
Parameters
projection The new projection matrix of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 66 of file CCameraSceneNode.cpp.
References irr::video::ETS_PROJECTION, irr::scene::SViewFrustum::getTransform(), and irr::scene::ICameraSceneNode::isOrthogonal().
setRotation()
void irr::scene::CCameraSceneNode::setRotation (const core::vector3df & rotation) override virtual
Sets the rotation of the node.
This only modifies the relative rotation of the node. If the camera's target and rotation are bound (
See also
bindTargetAndRotation()) then calling this will also change the camera's target to match the rotation.
Parameters
rotation New rotation of the node in degrees.
Implements irr::scene::ICameraSceneNode.
Definition at line 137 of file CCameraSceneNode.cpp.
References irr::scene::ISceneNode::getAbsolutePosition(), irr::core::vector3d< T >::rotationToDirection(), and irr::scene::ISceneNode::setRotation().
setTarget()
void irr::scene::CCameraSceneNode::setTarget (const core::vector3df & pos) override virtual
Sets the look at target of the camera.
If the camera's target and rotation are bound (
See also
bindTargetAndRotation()) then calling this will also change the camera's scene node rotation to match the target.
Parameters
pos Look at target of the camera.
sets the look at target of the camera
Parameters
pos Look at target of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 120 of file CCameraSceneNode.cpp.
References irr::scene::ISceneNode::getAbsolutePosition(), irr::core::vector3d< T >::getHorizontalAngle(), and irr::scene::ISceneNode::setRotation().
setUpVector()
void irr::scene::CCameraSceneNode::setUpVector (const core::vector3df & pos) override virtual
Sets the up vector of the camera.
Parameters
pos New upvector of the camera.
sets the up vector of the camera
Parameters
pos New upvector of the camera.
Implements irr::scene::ICameraSceneNode.
Definition at line 156 of file CCameraSceneNode.cpp.
setViewMatrixAffector()
void irr::scene::CCameraSceneNode::setViewMatrixAffector (const core::matrix4 & affector) override virtual
Sets a custom view matrix affector.
Parameters
affector The affector matrix.
Sets a custom view matrix affector. The matrix passed here, will be multiplied with the view matrix when it gets updated. This allows for custom camera setups like, for example, a reflection camera.
Parameters
affector The affector matrix.
Implements irr::scene::ICameraSceneNode.
Definition at line 93 of file CCameraSceneNode.cpp.
updateMatrices()
void irr::scene::CCameraSceneNode::updateMatrices () override virtual
Update.
update
Implements irr::scene::ICameraSceneNode.
Definition at line 255 of file CCameraSceneNode.cpp.
References irr::core::CMatrix4< T >::buildCameraLookAtMatrixLH(), irr::core::vector3d< T >::dotProduct(), irr::core::equals(), irr::video::ETS_VIEW, irr::scene::ISceneNode::getAbsolutePosition(), irr::scene::SViewFrustum::getTransform(), and irr::core::vector3d< T >::normalize().
Referenced by render().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CCameraSceneNode.h
lib/irrlichtmt/source/Irrlicht/CCameraSceneNode.cpp