Three Cubes Game: irr::gui::IGUIElement Class Reference
irr::gui::IGUIElement Class Reference
Base class of all GUI elements.
#include <IGUIElement.h>
Public Member Functions
IGUIElement (EGUI_ELEMENT_TYPE type, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle)
Constructor.
virtual ~IGUIElement ()
Destructor.
IGUIElement * getParent () const
Returns parent of this element.
core::rect< s32 > getRelativePosition () const
Returns the relative rectangle of this element.
void setRelativePosition (const core::rect< s32 > &r)
Sets the relative rectangle of this element.
void setRelativePosition (const core::position2di &position)
Sets the relative rectangle of this element, maintaining its current width and height.
void setRelativePositionProportional (const core::rect< f32 > &r)
Sets the relative rectangle of this element as a proportion of its parent's area.
core::rect< s32 > getAbsolutePosition () const
Gets the absolute rectangle of this element.
core::rect< s32 > getAbsoluteClippingRect () const
Returns the visible area of the element.
void setNotClipped (bool noClip)
Sets whether the element will ignore its parent's clipping rectangle.
bool isNotClipped () const
Gets whether the element will ignore its parent's clipping rectangle.
void setMaxSize (core::dimension2du size)
Sets the maximum size allowed for this element.
void setMinSize (core::dimension2du size)
Sets the minimum size allowed for this element.
void setAlignment (EGUI_ALIGNMENT left, EGUI_ALIGNMENT right, EGUI_ALIGNMENT top, EGUI_ALIGNMENT bottom)
The alignment defines how the borders of this element will be positioned when the parent element is resized.
EGUI_ALIGNMENT getAlignLeft () const
How left element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignRight () const
How right element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignTop () const
How top element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignBottom () const
How bottom element border is aligned when parent is resized.
virtual void updateAbsolutePosition ()
Updates the absolute position.
virtual IGUIElement * getElementFromPoint (const core::position2d< s32 > &point)
Returns the topmost GUI element at the specific position.
virtual bool isPointInside (const core::position2d< s32 > &point) const
Returns true if a point is within this element.
virtual void addChild (IGUIElement *child)
Adds a GUI element as new child of this element.
virtual void removeChild (IGUIElement *child)
Removes a child.
virtual void removeAllChildren ()
Removes all children.
virtual void remove ()
Removes this element from its parent.
virtual void draw ()
Draws the element and its children.
virtual void OnPostRender (u32 timeMs)
animate the element and its children.
virtual void move (core::position2d< s32 > absoluteMovement)
Moves this element.
virtual bool isVisible () const
Returns true if element is visible.
virtual bool isTrulyVisible () const
Check whether the element is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool visible)
Sets the visible state of this element.
virtual bool isSubElement () const
Returns true if this element was created as part of its parent control.
virtual void setSubElement (bool subElement)
Sets whether this control was created as part of its parent.
void setTabStop (bool enable)
If set to true, the focus will visit this element when using the tab key to cycle through elements.
bool isTabStop () const
Returns true if this element can be focused by navigating with the tab key.
void setTabOrder (s32 index)
Sets the priority of focus when using the tab key to navigate between a group of elements.
s32 getTabOrder () const
Returns the number in the tab order sequence.
void setTabGroup (bool isGroup)
Sets whether this element is a container for a group of elements which can be navigated using the tab key.
bool isTabGroup () const
Returns true if this element is a tab group.
IGUIElement * getTabGroup ()
Returns the container element which holds all elements in this element's tab group.
virtual bool isEnabled () const
Returns true if element is enabled.
virtual void setEnabled (bool enabled)
Sets the enabled state of this element.
virtual void setText (const wchar_t *text)
Sets the new caption of this element.
virtual const wchar_t * getText () const
Returns caption of this element.
virtual void setToolTipText (const wchar_t *text)
Sets the new caption of this element.
virtual const core::stringw & getToolTipText () const
Returns caption of this element.
virtual s32 getID () const
Returns id. Can be used to identify the element.
virtual void setID (s32 id)
Sets the id of this element.
bool OnEvent (const SEvent &event) override
Called if an event happened.
virtual bool bringToFront (IGUIElement *child)
Brings a child to front.
virtual bool sendToBack (IGUIElement *child)
Moves a child to the back, so it's siblings are drawn on top of it.
virtual const std::list< IGUIElement * > & getChildren () const
Returns list with children of this element.
virtual IGUIElement * getElementFromId (s32 id, bool searchchildren=false) const
Finds the first element with the given id.
bool isMyChild (IGUIElement *child) const
bool getNextElement (s32 startOrder, bool reverse, bool group, IGUIElement *&first, IGUIElement *&closest, bool includeInvisible=false, bool includeDisabled=false) const
searches elements to find the closest next element to tab to
EGUI_ELEMENT_TYPE getType () const
Returns the type of the gui element.
virtual bool hasType (EGUI_ELEMENT_TYPE type) const
Returns true if the gui element supports the given type.
virtual const c8 * getTypeName () const
Returns the type name of the gui element.
virtual const c8 * getName () const
Returns the name of the element.
virtual void setName (const c8 *name)
Sets the name of the element.
virtual void setName (const core::stringc &name)
Sets the name of the element.
virtual bool acceptsIME ()
Returns whether the element takes input from the IME.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::IEventReceiver
virtual ~IEventReceiver ()
Destructor.
Protected Member Functions
void addChildToEnd (IGUIElement *child)
void reorderChildren (std::list< IGUIElement * >::iterator from, std::list< IGUIElement * >::iterator to, const std::vector< IGUIElement * > &neworder)
void recalculateAbsolutePosition (bool recursive)
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Static Protected Member Functions
template<typename Iterator >
static size_t _fastSetChecksum (Iterator begin, Iterator end)
Protected Attributes
std::list< IGUIElement * > Children
List of all children of this element.
IGUIElement * Parent
Pointer to the parent.
std::list< IGUIElement * >::iterator ParentPos
Our position in the parent list. Only valid when Parent != nullptr.
core::rect< s32 > RelativeRect
relative rect of element
core::rect< s32 > AbsoluteRect
absolute rect of element
core::rect< s32 > AbsoluteClippingRect
absolute clipping rect of element
core::rect< s32 > DesiredRect
core::rect< s32 > LastParentRect
for calculating the difference when resizing parent
core::rect< f32 > ScaleRect
relative scale of the element inside its parent
core::dimension2du MaxSize
maximum and minimum size of the element
core::dimension2du MinSize
bool IsVisible
is visible?
bool IsEnabled
is enabled?
bool IsSubElement
is a part of a larger whole and should not be serialized?
bool NoClip
does this element ignore its parent's clipping rectangle?
core::stringw Text
caption
core::stringw ToolTipText
tooltip
core::stringc Name
users can set this for identifying the element by string
s32 ID
users can set this for identifying the element by integer
bool IsTabStop
tab stop like in windows
s32 TabOrder
tab order
bool IsTabGroup
tab groups are containers like windows, use ctrl+tab to navigate
EGUI_ALIGNMENT AlignLeft
tells the element how to act when its parent is resized
EGUI_ALIGNMENT AlignRight
EGUI_ALIGNMENT AlignTop
EGUI_ALIGNMENT AlignBottom
IGUIEnvironment * Environment
GUI Environment.
EGUI_ELEMENT_TYPE Type
type of element
Detailed Description
Base class of all GUI elements.
Definition at line 26 of file IGUIElement.h.
Member Function Documentation
bringToFront()
virtual bool irr::gui::IGUIElement::bringToFront (IGUIElement * child) inline virtual
Brings a child to front.
Returns
True if successful, false if not.
Definition at line 556 of file IGUIElement.h.
References Children, Parent, and ParentPos.
Referenced by irr::gui::CGUIEnvironment::drawAll().
getElementFromId()
virtual IGUIElement* irr::gui::IGUIElement::getElementFromId (s32 id, bool searchchildren = false) const inline virtual
Finds the first element with the given id.
Parameters
id Id to search for.
searchchildren Set this to true, if also children of this element may contain the element with the searched id and they should be searched too.
Returns
Returns the first element with the given id. If no element with this id was found, 0 is returned.
Definition at line 595 of file IGUIElement.h.
References Children, and getElementFromId().
Referenced by getElementFromId(), and GUIVolumeChange::OnEvent().
getElementFromPoint()
virtual IGUIElement* irr::gui::IGUIElement::getElementFromPoint (const core::position2d< s32 > & point) inline virtual
Returns the topmost GUI element at the specific position.
This will check this GUI element and all of its descendants, so it may return this GUI element. To check all GUI elements, call this function on device->getGUIEnvironment()->getRootGUIElement(). Note that the root element is the size of the screen, so doing so (with an on-screen point) will always return the root element if no other element is above it at that point.
Parameters
point The point at which to find a GUI element.
Returns
The topmost GUI element at that point, or 0 if there are no candidate elements at this point.
Definition at line 261 of file IGUIElement.h.
References Children, getElementFromPoint(), isPointInside(), and isVisible().
Referenced by getElementFromPoint(), GUIScrollContainer::OnEvent(), and GUIInventoryList::OnEvent().
getName()
virtual const c8* irr::gui::IGUIElement::getName () const inline virtual
Returns the name of the element.
Returns
Name as character string.
Definition at line 754 of file IGUIElement.h.
References irr::core::string< T >::c_str(), and Name.
getNextElement()
bool irr::gui::IGUIElement::getNextElement (s32 startOrder, bool reverse, bool group, IGUIElement *& first, IGUIElement *& closest, bool includeInvisible = false, bool includeDisabled = false) const inline
searches elements to find the closest next element to tab to
Parameters
startOrder The TabOrder of the current element, -1 if none
reverse true if searching for a lower number
group true if searching for a higher one
first element with the highest/lowest known tab order depending on search direction
closest the closest match, depending on tab order and direction
includeInvisible includes invisible elements in the search (default=false)
includeDisabled includes disabled elements in the search (default=false)
Returns
true if successfully found an element, false to continue searching/fail
Definition at line 642 of file IGUIElement.h.
References Children, and getTabOrder().
Referenced by irr::gui::CGUIEnvironment::getNextElement(), and setTabOrder().
getType()
EGUI_ELEMENT_TYPE irr::gui::IGUIElement::getType () const inline
Returns the type of the gui element.
This is needed for the .NET wrapper but will be used later for serializing and deserializing. If you wrote your own GUIElements, you need to set the type for your element as first parameter in the constructor of IGUIElement. For own (=unknown) elements, simply use EGUIET_ELEMENT as type
Definition at line 725 of file IGUIElement.h.
References Type.
Referenced by irr::gui::CGUIEnvironment::addListBox(), irr::gui::IGUITab::getNumber(), and GUIVolumeChange::OnEvent().
getTypeName()
virtual const c8* irr::gui::IGUIElement::getTypeName () const inline virtual
Returns the type name of the gui element.
This is needed serializing elements.
Reimplemented in GUITable.
Definition at line 747 of file IGUIElement.h.
References irr::gui::GUIElementTypeNames, and Type.
hasType()
virtual bool irr::gui::IGUIElement::hasType (EGUI_ELEMENT_TYPE type) const inline virtual
Returns true if the gui element supports the given type.
This is mostly used to check if you can cast a gui element to the class that goes with the type. Most gui elements will only support their own type, but if you derive your own classes from interfaces you can overload this function and add a check for the type of the base-class additionally. This allows for checks comparable to the dynamic_cast of c++ with enabled rtti. Note that you can't do that by calling BaseClass::hasType(type), but you have to do an explicit comparison check, because otherwise the base class usually just checks for the member variable Type which contains the type of your derived class.
Reimplemented in irr::gui::StaticText.
Definition at line 739 of file IGUIElement.h.
References Type.
isEnabled()
virtual bool irr::gui::IGUIElement::isEnabled () const inline virtual
Returns true if element is enabled.
Currently elements do not care about parent-states. So if you want to affect children you have to enable/disable them all. The only exception to this are sub-elements which also check their parent.
Definition at line 489 of file IGUIElement.h.
References getParent(), isEnabled(), IsEnabled, and isSubElement().
Referenced by irr::gui::CGUIEditBox::acceptsIME(), GUIEditBoxWithScrollBar::draw(), irr::gui::CGUIScrollBar::draw(), irr::gui::CGUIButton::draw(), GUIScrollBar::draw(), GUIButton::draw(), irr::gui::CGUICheckBox::draw(), irr::gui::CGUIComboBox::draw(), irr::gui::CGUIEditBox::draw(), irr::gui::GUISkin::drawColoredIcon(), irr::gui::CGUISkin::drawIcon(), irr::gui::CGUIButton::getActiveColor(), irr::gui::CGUIStaticText::getActiveColor(), irr::gui::CGUIEditBox::inputString(), isEnabled(), irr::gui::CGUIScrollBar::OnEvent(), irr::gui::CGUIButton::OnEvent(), GUIButton::OnEvent(), GUIScrollBar::OnEvent(), irr::gui::CGUICheckBox::OnEvent(), irr::gui::CGUIFileOpenDialog::OnEvent(), irr::gui::CGUIListBox::OnEvent(), irr::gui::CGUIComboBox::OnEvent(), irr::gui::CGUIEditBox::OnEvent(), irr::gui::CGUITabControl::OnEvent(), GUIEditBox::OnEvent(), GUITable::OnEvent(), irr::gui::CGUIEnvironment::postEventFromUser(), and irr::gui::CGUIScrollBar::refreshControls().
isMyChild()
bool irr::gui::IGUIElement::isMyChild (IGUIElement * child) const inline
returns true if the given element is a child of this one.
Parameters
child The child element to check
Definition at line 617 of file IGUIElement.h.
References Parent.
Referenced by irr::gui::CGUIComboBox::draw(), and irr::gui::CGUIComboBox::OnEvent().
isNotClipped()
bool irr::gui::IGUIElement::isNotClipped () const inline
Gets whether the element will ignore its parent's clipping rectangle.
Returns
true if the element is not clipped by its parent's clipping rectangle.
Definition at line 160 of file IGUIElement.h.
References NoClip.
isPointInside()
virtual bool irr::gui::IGUIElement::isPointInside (const core::position2d< s32 > & point) const inline virtual
Returns true if a point is within this element.
Elements with a shape other than a rectangle should override this method
Definition at line 290 of file IGUIElement.h.
References AbsoluteClippingRect, and irr::core::rect< T >::isPointInside().
Referenced by getElementFromPoint(), irr::gui::CGUIScrollBar::OnEvent(), GUIScrollBar::OnEvent(), irr::gui::CGUIListBox::OnEvent(), irr::gui::CGUIComboBox::OnEvent(), GUITable::OnEvent(), and GUIFormSpecMenu::OnEvent().
isTrulyVisible()
virtual bool irr::gui::IGUIElement::isTrulyVisible () const inline virtual
Check whether the element is truly visible, taking into accounts its parents' visibility.
Returns
true if the element and all its parents are visible, false if this or any parent element is invisible.
Definition at line 369 of file IGUIElement.h.
References isTrulyVisible(), IsVisible, and Parent.
Referenced by isTrulyVisible().
sendToBack()
virtual bool irr::gui::IGUIElement::sendToBack (IGUIElement * child) inline virtual
Moves a child to the back, so it's siblings are drawn on top of it.
Returns
True if successful, false if not.
Definition at line 570 of file IGUIElement.h.
References Children, Parent, and ParentPos.
Referenced by GUIButtonImage::GUIButtonImage(), and GUIButtonItemImage::GUIButtonItemImage().
setMaxSize()
void irr::gui::IGUIElement::setMaxSize (core::dimension2du size) inline
Sets the maximum size allowed for this element.
If set to 0,0, there is no maximum size
Definition at line 168 of file IGUIElement.h.
References MaxSize, and updateAbsolutePosition().
setName() [1/2]
virtual void irr::gui::IGUIElement::setName (const c8 * name) inline virtual
Sets the name of the element.
Parameters
name New name of the gui element.
Definition at line 762 of file IGUIElement.h.
References Name.
setName() [2/2]
virtual void irr::gui::IGUIElement::setName (const core::stringc & name) inline virtual
Sets the name of the element.
Parameters
name New name of the gui element.
Definition at line 770 of file IGUIElement.h.
References Name.
setNotClipped()
void irr::gui::IGUIElement::setNotClipped (bool noClip) inline
Sets whether the element will ignore its parent's clipping rectangle.
Parameters
noClip If true, the element will not be clipped by its parent's clipping rectangle.
Definition at line 151 of file IGUIElement.h.
References NoClip, and updateAbsolutePosition().
Referenced by irr::gui::CGUIButton::CGUIButton(), irr::gui::CGUIListBox::CGUIListBox(), irr::gui::CGUIScrollBar::CGUIScrollBar(), GUIButton::GUIButton(), and GUIButton::setFromStyle().
setRelativePosition() [1/2]
void irr::gui::IGUIElement::setRelativePosition (const core::position2di & position) inline
Sets the relative rectangle of this element, maintaining its current width and height.
Parameters
position The new relative position to set. Width and height will not be changed.
Definition at line 102 of file IGUIElement.h.
References irr::core::rect< T >::getSize(), irr::core::dimension2d< T >::Height, RelativeRect, setRelativePosition(), and irr::core::dimension2d< T >::Width.
setRelativePosition() [2/2]
void irr::gui::IGUIElement::setRelativePosition (const core::rect< s32 > & r) inline
Sets the relative rectangle of this element.
Parameters
r The absolute position to set
Definition at line 78 of file IGUIElement.h.
References AlignLeft, DesiredRect, irr::gui::EGUIA_SCALE, getAbsolutePosition(), irr::core::rect< T >::getSize(), irr::core::dimension2d< T >::Height, irr::core::rect< T >::LowerRightCorner, Parent, ScaleRect, updateAbsolutePosition(), irr::core::rect< T >::UpperLeftCorner, and irr::core::dimension2d< T >::Width.
Referenced by irr::gui::CGUIEnvironment::drawAll(), move(), irr::gui::CGUIEnvironment::OnPostRender(), irr::gui::CGUIScrollBar::refreshControls(), and setRelativePosition().
setRelativePositionProportional()
void irr::gui::IGUIElement::setRelativePositionProportional (const core::rect< f32 > & r) inline
Sets the relative rectangle of this element as a proportion of its parent's area.
Note
This method used to be 'void setRelativePosition(const core::rect<f32>& r)'
Parameters
r The rectangle to set, interpreted as a proportion of the parent's area. Meaningful values are in the range [0...1], unless you intend this element to spill outside its parent.
Definition at line 116 of file IGUIElement.h.
References DesiredRect, getAbsolutePosition(), irr::core::rect< T >::getSize(), irr::core::dimension2d< T >::Height, irr::core::rect< T >::LowerRightCorner, Parent, ScaleRect, updateAbsolutePosition(), irr::core::rect< T >::UpperLeftCorner, and irr::core::dimension2d< T >::Width.
setSubElement()
virtual void irr::gui::IGUIElement::setSubElement (bool subElement) inline virtual
Sets whether this control was created as part of its parent.
For example, it is true when a scrollbar is part of a listbox. SubElements are not saved to disk when calling guiEnvironment->saveGUI()
Definition at line 397 of file IGUIElement.h.
References IsSubElement.
Referenced by irr::gui::CGUIComboBox::CGUIComboBox(), irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog(), irr::gui::CGUIListBox::CGUIListBox(), irr::gui::CGUITabControl::CGUITabControl(), irr::gui::CGUIEnvironment::OnPostRender(), and irr::gui::CGUIScrollBar::refreshControls().
setTabGroup()
void irr::gui::IGUIElement::setTabGroup (bool isGroup) inline
Sets whether this element is a container for a group of elements which can be navigated using the tab key.
For example, windows are tab groups. Groups can be navigated using ctrl+tab, providing isTabStop is true.
Definition at line 459 of file IGUIElement.h.
References IsTabGroup.
Referenced by irr::gui::CGUIEnvironment::CGUIEnvironment(), and irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog().
setTabOrder()
void irr::gui::IGUIElement::setTabOrder (s32 index) inline
Sets the priority of focus when using the tab key to navigate between a group of elements.
See setTabGroup, isTabGroup and getTabGroup for information on tab groups. Elements with a lower number are focused first
Definition at line 422 of file IGUIElement.h.
References getNextElement(), getTabGroup(), getTabOrder(), IsTabGroup, Parent, and TabOrder.
Referenced by irr::gui::CGUIButton::CGUIButton(), irr::gui::CGUICheckBox::CGUICheckBox(), irr::gui::CGUIComboBox::CGUIComboBox(), irr::gui::CGUIEditBox::CGUIEditBox(), irr::gui::CGUIListBox::CGUIListBox(), irr::gui::CGUIScrollBar::CGUIScrollBar(), GUIButton::GUIButton(), and GUIEditBoxWithScrollBar::GUIEditBoxWithScrollBar().
setTabStop()
void irr::gui::IGUIElement::setTabStop (bool enable) inline
If set to true, the focus will visit this element when using the tab key to cycle through elements.
If this element is a tab group (see isTabGroup/setTabGroup) then ctrl+tab will be used instead.
Definition at line 406 of file IGUIElement.h.
References IsTabStop.
Referenced by irr::gui::CGUIButton::CGUIButton(), irr::gui::CGUICheckBox::CGUICheckBox(), irr::gui::CGUIComboBox::CGUIComboBox(), irr::gui::CGUIEditBox::CGUIEditBox(), irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog(), irr::gui::CGUIListBox::CGUIListBox(), irr::gui::CGUIScrollBar::CGUIScrollBar(), GUIButton::GUIButton(), GUIEditBoxWithScrollBar::GUIEditBoxWithScrollBar(), and irr::gui::CGUIScrollBar::refreshControls().
Member Data Documentation
DesiredRect
core::rect<s32> irr::gui::IGUIElement::DesiredRect protected
the rectangle the element would prefer to be, if it was not constrained by parent or max/min size
Definition at line 977 of file IGUIElement.h.
Referenced by move(), setAlignment(), setRelativePosition(), and setRelativePositionProportional().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IGUIElement.h