Three Cubes Game: irr::IReferenceCounted Class Reference
irr::IReferenceCounted Class Reference
Base class of most objects of the Irrlicht Engine.
#include <IReferenceCounted.h>
Public Member Functions
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Protected Member Functions
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Private Attributes
const c8 * DebugName
The debug name.
s32 ReferenceCounter
The reference counter. Mutable to do reference counting on const objects.
Detailed Description
Base class of most objects of the Irrlicht Engine.
This class provides reference counting through the methods grab() and drop(). It also is able to store a debug string for every instance of an object. Most objects of the Irrlicht Engine are derived from IReferenceCounted, and so they are reference counted.
When you create an object in the Irrlicht engine, calling a method which starts with 'create', an object is created, and you get a pointer to the new object. If you no longer need the object, you have to call drop(). This will destroy the object, if grab() was not called in another part of you program, because this part still needs the object. Note, that you only need to call drop() to the object, if you created it, and the method had a 'create' in it.
A simple example:
If you want to create a texture, you may want to call an imaginable method IDriver::createTexture. You call ITexture* texture = driver->createTexture(dimension2d<u32>(128, 128)); If you no longer need the texture, call texture->drop().
If you want to load a texture, you may want to call imaginable method IDriver::loadTexture. You do this like ITexture* texture = driver->loadTexture("example.jpg"); You will not have to drop the pointer to the loaded texture, because the name of the method does not start with 'create'. The texture is stored somewhere by the driver.
Definition at line 41 of file IReferenceCounted.h.
Member Function Documentation
drop()
bool irr::IReferenceCounted::drop () const inline
Drops the object. Decrements the reference counter by one.
The IReferenceCounted class provides a basic reference counting mechanism with its methods grab() and drop(). Most objects of the Irrlicht Engine are derived from IReferenceCounted, and so they are reference counted.
When you create an object in the Irrlicht engine, calling a method which starts with 'create', an object is created, and you get a pointer to the new object. If you no longer need the object, you have to call drop(). This will destroy the object, if grab() was not called in another part of you program, because this part still needs the object. Note, that you only need to call drop() to the object, if you created it, and the method had a 'create' in it.
A simple example:
If you want to create a texture, you may want to call an imaginable method IDriver::createTexture. You call ITexture* texture = driver->createTexture(dimension2d<u32>(128, 128)); If you no longer need the texture, call texture->drop(). If you want to load a texture, you may want to call imaginable method IDriver::loadTexture. You do this like ITexture* texture = driver->loadTexture("example.jpg"); You will not have to drop the pointer to the loaded texture, because the name of the method does not start with 'create'. The texture is stored somewhere by the driver.
Returns
True, if the object was deleted.
Definition at line 116 of file IReferenceCounted.h.
References ReferenceCounter.
Referenced by irr::scene::CSceneManager::addAnimatedMeshSceneNode(), irr::scene::CSceneManager::addBillboardSceneNode(), GUIButtonItemImage::addButton(), irr::gui::CGUIEnvironment::addButton(), GUIButton::addButton(), irr::scene::CSceneManager::addCameraSceneNode(), irr::gui::CGUIEnvironment::addCheckBox(), irr::gui::CGUIEnvironment::addComboBox(), irr::scene::CSceneManager::addDummyTransformationSceneNode(), irr::gui::CGUIEnvironment::addEditBox(), irr::scene::CSceneManager::addEmptySceneNode(), irr::gui::CGUIEnvironment::addFileOpenDialog(), irr::video::COpenGL3DriverBase::addHighLevelShaderMaterial(), irr::video::CNullDriver::addHighLevelShaderMaterialFromFiles(), irr::gui::CGUIEnvironment::addImage(), irr::scene::CSkinnedMesh::addJoints(), irr::gui::CGUIEnvironment::addListBox(), irr::scene::CSceneManager::addMeshSceneNode(), irr::video::COpenGL3DriverBase::addRenderTargetTexture(), irr::video::COpenGL3DriverBase::addRenderTargetTextureCubemap(), irr::gui::CGUIEnvironment::addScrollBar(), irr::video::CNullDriver::addShaderMaterialFromFiles(), irr::gui::CGUIEnvironment::addStaticText(), irr::gui::CGUIEnvironment::addTab(), irr::gui::CGUIEnvironment::addTabControl(), irr::gui::CGUITTFont::addTextSceneNode(), irr::video::CNullDriver::addTexture(), irr::video::CNullDriver::addTextureCubemap(), irr::gui::CGUIEnvironment::CGUIEnvironment(), irr::scene::SMesh::clear(), irr::gui::CGUIEnvironment::clear(), irr::io::CAttributes::clear(), irr::scene::CEmptySceneNode::clone(), irr::scene::CDummyTransformationSceneNode::clone(), irr::scene::CMeshSceneNode::clone(), irr::scene::CBillboardSceneNode::clone(), irr::scene::CAnimatedMeshSceneNode::clone(), irr::scene::CCameraSceneNode::clone(), irr::io::CZipReader::createAndOpenFile(), irr::gui::CGUIEnvironment::createImageList(), irr::scene::COBJMeshFileLoader::createMesh(), irr::scene::CXMeshFileLoader::createMesh(), irr::scene::CB3DMeshFileLoader::createMesh(), irr::scene::CMeshManipulator::createMeshCopy(), irr::video::createNullDriver(), irr::video::COpenGL3DriverBase::createScreenShot(), irr::gui::CGUITTFont::createTTFont(), TextureBuffer::ensureTexture(), irr::gui::CGUIFileOpenDialog::fillListBox(), TextureSource::generateImage(), irr::gui::CGUIEnvironment::getFont(), TextureSource::getPalette(), irr::video::CNullDriver::getTexture(), MenuTextureSource::getTexture(), irr::gui::CGUIFont::loadTexture(), irr::video::CNullDriver::loadTextureFromFile(), irr::video::COpenGLCoreTexture< TOpenGLDriver >::lock(), irr::gui::CGUIEnvironment::OnPostRender(), irr::video::CNullDriver::removeAllRenderTargets(), irr::gui::IGUIElement::removeChild(), irr::gui::CGUIEnvironment::removeFocus(), irr::video::CNullDriver::removeTexture(), irr::scene::CSceneManager::setActiveCamera(), irr::scene::CAnimatedMeshSceneNode::setAnimationEndCallback(), irr::gui::CGUIEnvironment::setFocus(), irr::gui::CGUISkin::setFont(), irr::gui::CGUIImage::setImage(), irr::gui::CGUIButton::setImage(), GUIButton::setImage(), irr::CIrrDeviceStub::setInputReceivingSceneManager(), irr::scene::CMeshSceneNode::setMesh(), irr::scene::CAnimatedMeshSceneNode::setMesh(), irr::gui::CGUIEditBox::setOverrideFont(), irr::gui::CGUIStaticText::setOverrideFont(), irr::gui::CGUIButton::setOverrideFont(), GUIButton::setOverrideFont(), GUIEditBox::setOverrideFont(), irr::gui::StaticText::setOverrideFont(), GUITable::setOverrideFont(), irr::scene::ISceneNode::setParent(), irr::gui::CGUIEnvironment::setSkin(), irr::gui::CGUISkin::setSpriteBank(), irr::gui::CGUIListBox::setSpriteBank(), GUIButton::setSpriteBank(), irr::gui::CGUIButton::setSpriteBank(), irr::video::COpenGLCoreRenderTarget< TOpenGLDriver, TOpenGLTexture >::setTextures(), irr::gui::SGUITTGlyph::unload(), irr::video::COpenGLCoreTexture< TOpenGLDriver >::unlock(), irr::gui::CGUITTGlyphPage::updateTexture(), irr::scene::CAnimatedMeshSceneNode::~CAnimatedMeshSceneNode(), irr::gui::CGUIButton::~CGUIButton(), irr::gui::CGUIEditBox::~CGUIEditBox(), irr::gui::CGUIEnvironment::~CGUIEnvironment(), irr::gui::CGUIFileOpenDialog::~CGUIFileOpenDialog(), irr::gui::CGUIFont::~CGUIFont(), irr::gui::CGUIImage::~CGUIImage(), irr::gui::CGUIImageList::~CGUIImageList(), irr::gui::CGUIListBox::~CGUIListBox(), irr::gui::CGUIScrollBar::~CGUIScrollBar(), irr::gui::CGUISkin::~CGUISkin(), irr::gui::CGUIStaticText::~CGUIStaticText(), irr::gui::CGUITabControl::~CGUITabControl(), irr::gui::CGUITTFont::~CGUITTFont(), irr::CIrrDeviceStub::~CIrrDeviceStub(), irr::scene::CMeshSceneNode::~CMeshSceneNode(), irr::video::CNullDriver::~CNullDriver(), irr::video::COpenGL3DriverBase::~COpenGL3DriverBase(), irr::scene::CSceneCollisionManager::~CSceneCollisionManager(), irr::scene::CSceneManager::~CSceneManager(), irr::io::CZipReader::~CZipReader(), GUIButton::~GUIButton(), GUIHyperText::~GUIHyperText(), irr::scene::SAnimatedMesh::~SAnimatedMesh(), irr::scene::SMesh::~SMesh(), and irr::gui::StaticText::~StaticText().
getDebugName()
const c8* irr::IReferenceCounted::getDebugName () const inline
Returns the debug name of the object.
The Debugname may only be set and changed by the object itself. This method should only be used in Debug mode.
Returns
Returns a string, previously set by setDebugName();
Definition at line 142 of file IReferenceCounted.h.
References DebugName.
Referenced by irr::scene::CAnimatedMeshSceneNode::render().
getReferenceCount()
s32 irr::IReferenceCounted::getReferenceCount () const inline
Get the reference count.
Returns
Current value of the reference counter.
Definition at line 133 of file IReferenceCounted.h.
References ReferenceCounter.
Referenced by irr::video::CNullDriver::updateAllHardwareBuffers().
grab()
void irr::IReferenceCounted::grab () const inline
Grabs the object. Increments the reference counter by one.
Someone who calls grab() to an object, should later also call drop() to it. If an object never gets as much drop() as grab() calls, it will never be destroyed. The IReferenceCounted class provides a basic reference counting mechanism with its methods grab() and drop(). Most objects of the Irrlicht Engine are derived from IReferenceCounted, and so they are reference counted.
When you create an object in the Irrlicht engine, calling a method which starts with 'create', an object is created, and you get a pointer to the new object. If you no longer need the object, you have to call drop(). This will destroy the object, if grab() was not called in another part of you program, because this part still needs the object. Note, that you only need to call drop() to the object, if you created it, and the method had a 'create' in it.
A simple example:
If you want to create a texture, you may want to call an imaginable method IDriver::createTexture. You call ITexture* texture = driver->createTexture(dimension2d<u32>(128, 128)); If you no longer need the texture, call texture->drop(). If you want to load a texture, you may want to call imaginable method IDriver::loadTexture. You do this like ITexture* texture = driver->loadTexture("example.jpg"); You will not have to drop the pointer to the loaded texture, because the name of the method does not start with 'create'. The texture is stored somewhere by the driver.
Definition at line 86 of file IReferenceCounted.h.
References ReferenceCounter.
Referenced by irr::scene::ISceneNode::addChild(), irr::video::CNullDriver::addExternalImageWriter(), irr::scene::CSceneManager::addExternalMeshLoader(), irr::io::CFileSystem::addFileArchive(), irr::gui::CGUIEnvironment::addFont(), irr::video::CNullDriver::addMaterialRenderer(), irr::scene::CMeshCache::addMesh(), irr::scene::SAnimatedMesh::addMesh(), irr::scene::SMesh::addMeshBuffer(), irr::video::CNullDriver::addOcclusionQuery(), irr::gui::CGUISpriteBank::addTexture(), irr::video::CNullDriver::addTexture(), irr::scene::CSceneManager::addToDeletionQueue(), irr::gui::CGUIEnvironment::addToDeletionQueue(), irr::gui::CGUIEditBox::CGUIEditBox(), irr::gui::CGUIEnvironment::CGUIEnvironment(), irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog(), irr::gui::CGUIFont::CGUIFont(), irr::gui::CGUIImageList::CGUIImageList(), irr::gui::CGUITabControl::CGUITabControl(), irr::gui::CGUITTFont::CGUITTFont(), irr::scene::CAnimatedMeshSceneNode::clone(), irr::video::CNullDriver::CNullDriver(), irr::video::COpenGL3DriverBase::COpenGL3DriverBase(), irr::gui::CGUIImageList::createImageList(), irr::video::CNullDriver::createRenderTargetTexture(), irr::scene::CSceneCollisionManager::CSceneCollisionManager(), irr::scene::CSceneManager::CSceneManager(), irr::io::CZipReader::CZipReader(), GUIEditBoxWithScrollBar::GUIEditBoxWithScrollBar(), irr::gui::CGUITabControl::insertTab(), irr::video::COpenGLCoreTexture< TOpenGLDriver >::lock(), irr::gui::CGUIEnvironment::OnPostRender(), irr::scene::CSceneManager::setActiveCamera(), irr::scene::CAnimatedMeshSceneNode::setAnimationEndCallback(), irr::gui::CGUIEnvironment::setFocus(), irr::gui::CGUISkin::setFont(), irr::gui::GUISkin::setFont(), GUIButtonImage::setFromStyle(), irr::gui::CGUIImage::setImage(), irr::gui::CGUIButton::setImage(), GUIButton::setImage(), irr::CIrrDeviceStub::setInputReceivingSceneManager(), irr::scene::CMeshSceneNode::setMesh(), irr::scene::CAnimatedMeshSceneNode::setMesh(), irr::gui::CGUIEditBox::setOverrideFont(), irr::gui::CGUIStaticText::setOverrideFont(), irr::gui::CGUIButton::setOverrideFont(), GUIButton::setOverrideFont(), GUIEditBox::setOverrideFont(), irr::gui::StaticText::setOverrideFont(), GUITable::setOverrideFont(), irr::scene::ISceneNode::setParent(), irr::gui::CGUIEnvironment::setSkin(), irr::gui::CGUISkin::setSpriteBank(), irr::gui::GUISkin::setSpriteBank(), irr::gui::CGUIListBox::setSpriteBank(), GUIButton::setSpriteBank(), irr::gui::CGUIButton::setSpriteBank(), irr::gui::CGUISpriteBank::setTexture(), and irr::video::COpenGLCoreRenderTarget< TOpenGLDriver, TOpenGLTexture >::setTextures().
setDebugName()
void irr::IReferenceCounted::setDebugName (const c8 * newName) inline protected
Sets the debug name of the object.
The Debugname may only be set and changed by the object itself. This method should only be used in Debug mode.
Parameters
newName New debug name to set.
Definition at line 153 of file IReferenceCounted.h.
References DebugName.
Referenced by irr::scene::CAnimatedMeshSceneNode::CAnimatedMeshSceneNode(), irr::io::CArchiveLoaderZIP::CArchiveLoaderZIP(), irr::scene::CB3DMeshFileLoader::CB3DMeshFileLoader(), irr::scene::CBillboardSceneNode::CBillboardSceneNode(), irr::scene::CBoneSceneNode::CBoneSceneNode(), irr::scene::CCameraSceneNode::CCameraSceneNode(), irr::scene::CDummyTransformationSceneNode::CDummyTransformationSceneNode(), irr::scene::CEmptySceneNode::CEmptySceneNode(), irr::io::CFileList::CFileList(), irr::io::CFileSystem::CFileSystem(), irr::gui::CGUIButton::CGUIButton(), irr::gui::CGUICheckBox::CGUICheckBox(), irr::gui::CGUIComboBox::CGUIComboBox(), irr::gui::CGUIEditBox::CGUIEditBox(), irr::gui::CGUIEnvironment::CGUIEnvironment(), irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog(), irr::gui::CGUIFont::CGUIFont(), irr::gui::CGUIImage::CGUIImage(), irr::gui::CGUIImageList::CGUIImageList(), irr::gui::CGUIListBox::CGUIListBox(), irr::gui::CGUIScrollBar::CGUIScrollBar(), irr::gui::CGUIStaticText::CGUIStaticText(), irr::gui::CGUITab::CGUITab(), irr::gui::CGUITabControl::CGUITabControl(), irr::gui::CGUITTFont::CGUITTFont(), irr::video::CImageLoaderBMP::CImageLoaderBMP(), irr::video::CImageLoaderJPG::CImageLoaderJPG(), irr::video::CImageWriterJPG::CImageWriterJPG(), irr::video::CImageWriterPNG::CImageWriterPNG(), irr::io::CMemoryReadFile::CMemoryReadFile(), irr::io::CMemoryWriteFile::CMemoryWriteFile(), irr::scene::CMeshBuffer< T >::CMeshBuffer(), irr::scene::CMeshSceneNode::CMeshSceneNode(), irr::video::CNullDriver::CNullDriver(), irr::scene::COBJMeshFileLoader::COBJMeshFileLoader(), irr::video::COpenGL3DriverBase::COpenGL3DriverBase(), irr::scene::CSceneCollisionManager::CSceneCollisionManager(), irr::scene::CSceneManager::CSceneManager(), irr::scene::CSkinnedMesh::CSkinnedMesh(), irr::scene::CXMeshFileLoader::CXMeshFileLoader(), irr::io::CZipReader::CZipReader(), GUIEditBoxWithScrollBar::GUIEditBoxWithScrollBar(), GUIHyperText::GUIHyperText(), irr::gui::IGUIElement::IGUIElement(), irr::scene::SAnimatedMesh::SAnimatedMesh(), irr::scene::SMesh::SMesh(), irr::scene::SSkinMeshBuffer::SSkinMeshBuffer(), and irr::gui::StaticText::StaticText().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IReferenceCounted.h