Three Cubes Game: irr::gui::CGUIListBox Class Reference
irr::gui::CGUIListBox Class Reference
Classes
struct ListItem
Public Member Functions
CGUIListBox (IGUIEnvironment *environment, IGUIElement *parent, s32 id, core::rect< s32 > rectangle, bool clip=true, bool drawBack=false, bool moveOverSelect=false)
constructor
virtual ~CGUIListBox ()
destructor
u32 getItemCount () const override
returns amount of list items
const wchar_t * getListItem (u32 id) const override
returns string of a list item. the id may be a value from 0 to itemCount-1
u32 addItem (const wchar_t *text) override
adds an list item, returns id of item
void clear () override
clears the list
s32 getSelected () const override
returns id of selected item. returns -1 if no item is selected.
void setSelected (s32 id) override
sets the selected item. Set this to -1 if no item should be selected
void setSelected (const wchar_t *item) override
sets the selected item. Set this to -1 if no item should be selected
bool OnEvent (const SEvent &event) override
called if an event happened.
void draw () override
draws the element and its children
u32 addItem (const wchar_t *text, s32 icon) override
adds an list item with an icon
s32 getIcon (u32 id) const override
Returns the icon of an item.
void removeItem (u32 id) override
removes an item from the list
s32 getItemAt (s32 xpos, s32 ypos) const override
get the the id of the item at the given absolute coordinates
void setSpriteBank (IGUISpriteBank *bank) override
void setAutoScrollEnabled (bool scroll) override
set whether the listbox should scroll to newly selected items
bool isAutoScrollEnabled () const override
returns true if automatic scrolling is enabled, false if not.
void updateAbsolutePosition () override
Update the position and size of the listbox, and update the scrollbar.
void setItemOverrideColor (u32 index, video::SColor color) override
set all item colors at given index to color
void setItemOverrideColor (u32 index, EGUI_LISTBOX_COLOR colorType, video::SColor color) override
set all item colors of specified type at given index to color
void clearItemOverrideColor (u32 index) override
clear all item colors at index
void clearItemOverrideColor (u32 index, EGUI_LISTBOX_COLOR colorType) override
clear item color at index for given colortype
bool hasItemOverrideColor (u32 index, EGUI_LISTBOX_COLOR colorType) const override
has the item at index its color overwritten?
video::SColor getItemOverrideColor (u32 index, EGUI_LISTBOX_COLOR colorType) const override
return the overwrite color at given item index.
video::SColor getItemDefaultColor (EGUI_LISTBOX_COLOR colorType) const override
return the default color which is used for the given colorType
void setItem (u32 index, const wchar_t *text, s32 icon) override
set the item at the given index
s32 insertItem (u32 index, const wchar_t *text, s32 icon) override
void swapItems (u32 index1, u32 index2) override
Swap the items at the given indices.
void setItemHeight (s32 height) override
set global itemHeight
void setDrawBackground (bool draw) override
Sets whether to draw the background.
IGUIScrollBar * getVerticalScrollBar () const override
Access the vertical scrollbar.
Public Member Functions inherited from irr::gui::IGUIListBox
IGUIListBox (IGUIEnvironment *environment, IGUIElement *parent, s32 id, core::rect< s32 > rectangle)
constructor
Public Member Functions inherited from irr::gui::IGUIElement
IGUIElement (EGUI_ELEMENT_TYPE type, IGUIEnvironment *environment, IGUIElement *parent, s32 id, const core::rect< s32 > &rectangle)
Constructor.
virtual ~IGUIElement ()
Destructor.
IGUIElement * getParent () const
Returns parent of this element.
core::rect< s32 > getRelativePosition () const
Returns the relative rectangle of this element.
void setRelativePosition (const core::rect< s32 > &r)
Sets the relative rectangle of this element.
void setRelativePosition (const core::position2di &position)
Sets the relative rectangle of this element, maintaining its current width and height.
void setRelativePositionProportional (const core::rect< f32 > &r)
Sets the relative rectangle of this element as a proportion of its parent's area.
core::rect< s32 > getAbsolutePosition () const
Gets the absolute rectangle of this element.
core::rect< s32 > getAbsoluteClippingRect () const
Returns the visible area of the element.
void setNotClipped (bool noClip)
Sets whether the element will ignore its parent's clipping rectangle.
bool isNotClipped () const
Gets whether the element will ignore its parent's clipping rectangle.
void setMaxSize (core::dimension2du size)
Sets the maximum size allowed for this element.
void setMinSize (core::dimension2du size)
Sets the minimum size allowed for this element.
void setAlignment (EGUI_ALIGNMENT left, EGUI_ALIGNMENT right, EGUI_ALIGNMENT top, EGUI_ALIGNMENT bottom)
The alignment defines how the borders of this element will be positioned when the parent element is resized.
EGUI_ALIGNMENT getAlignLeft () const
How left element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignRight () const
How right element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignTop () const
How top element border is aligned when parent is resized.
EGUI_ALIGNMENT getAlignBottom () const
How bottom element border is aligned when parent is resized.
virtual IGUIElement * getElementFromPoint (const core::position2d< s32 > &point)
Returns the topmost GUI element at the specific position.
virtual bool isPointInside (const core::position2d< s32 > &point) const
Returns true if a point is within this element.
virtual void addChild (IGUIElement *child)
Adds a GUI element as new child of this element.
virtual void removeChild (IGUIElement *child)
Removes a child.
virtual void removeAllChildren ()
Removes all children.
virtual void remove ()
Removes this element from its parent.
virtual void OnPostRender (u32 timeMs)
animate the element and its children.
virtual void move (core::position2d< s32 > absoluteMovement)
Moves this element.
virtual bool isVisible () const
Returns true if element is visible.
virtual bool isTrulyVisible () const
Check whether the element is truly visible, taking into accounts its parents' visibility.
virtual void setVisible (bool visible)
Sets the visible state of this element.
virtual bool isSubElement () const
Returns true if this element was created as part of its parent control.
virtual void setSubElement (bool subElement)
Sets whether this control was created as part of its parent.
void setTabStop (bool enable)
If set to true, the focus will visit this element when using the tab key to cycle through elements.
bool isTabStop () const
Returns true if this element can be focused by navigating with the tab key.
void setTabOrder (s32 index)
Sets the priority of focus when using the tab key to navigate between a group of elements.
s32 getTabOrder () const
Returns the number in the tab order sequence.
void setTabGroup (bool isGroup)
Sets whether this element is a container for a group of elements which can be navigated using the tab key.
bool isTabGroup () const
Returns true if this element is a tab group.
IGUIElement * getTabGroup ()
Returns the container element which holds all elements in this element's tab group.
virtual bool isEnabled () const
Returns true if element is enabled.
virtual void setEnabled (bool enabled)
Sets the enabled state of this element.
virtual void setText (const wchar_t *text)
Sets the new caption of this element.
virtual const wchar_t * getText () const
Returns caption of this element.
virtual void setToolTipText (const wchar_t *text)
Sets the new caption of this element.
virtual const core::stringw & getToolTipText () const
Returns caption of this element.
virtual s32 getID () const
Returns id. Can be used to identify the element.
virtual void setID (s32 id)
Sets the id of this element.
virtual bool bringToFront (IGUIElement *child)
Brings a child to front.
virtual bool sendToBack (IGUIElement *child)
Moves a child to the back, so it's siblings are drawn on top of it.
virtual const std::list< IGUIElement * > & getChildren () const
Returns list with children of this element.
virtual IGUIElement * getElementFromId (s32 id, bool searchchildren=false) const
Finds the first element with the given id.
bool isMyChild (IGUIElement *child) const
bool getNextElement (s32 startOrder, bool reverse, bool group, IGUIElement *&first, IGUIElement *&closest, bool includeInvisible=false, bool includeDisabled=false) const
searches elements to find the closest next element to tab to
EGUI_ELEMENT_TYPE getType () const
Returns the type of the gui element.
virtual bool hasType (EGUI_ELEMENT_TYPE type) const
Returns true if the gui element supports the given type.
virtual const c8 * getTypeName () const
Returns the type name of the gui element.
virtual const c8 * getName () const
Returns the name of the element.
virtual void setName (const c8 *name)
Sets the name of the element.
virtual void setName (const core::stringc &name)
Sets the name of the element.
virtual bool acceptsIME ()
Returns whether the element takes input from the IME.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Member Functions inherited from irr::IEventReceiver
virtual ~IEventReceiver ()
Destructor.
Private Member Functions
void recalculateItemHeight ()
void selectNew (s32 ypos, bool onlyHover=false)
void recalculateScrollPos ()
void updateScrollBarSize (s32 size)
void recalculateItemWidth (s32 icon)
bool getSerializationLabels (EGUI_LISTBOX_COLOR colorType, core::stringc &useColorLabel, core::stringc &colorLabel) const
Private Attributes
core::array< ListItem > Items
s32 Selected
s32 ItemHeight
s32 ItemHeightOverride
s32 TotalItemHeight
s32 ItemsIconWidth
gui::IGUIFont * Font
gui::IGUISpriteBank * IconBank
gui::IGUIScrollBar * ScrollBar
u32 selectTime
u32 LastKeyTime
core::stringw KeyBuffer
bool Selecting
bool DrawBack
bool MoveOverSelect
bool AutoScroll
bool HighlightWhenNotFocused
Additional Inherited Members
Protected Member Functions inherited from irr::gui::IGUIElement
void addChildToEnd (IGUIElement *child)
void reorderChildren (std::list< IGUIElement * >::iterator from, std::list< IGUIElement * >::iterator to, const std::vector< IGUIElement * > &neworder)
void recalculateAbsolutePosition (bool recursive)
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Static Protected Member Functions inherited from irr::gui::IGUIElement
template<typename Iterator >
static size_t _fastSetChecksum (Iterator begin, Iterator end)
Protected Attributes inherited from irr::gui::IGUIElement
std::list< IGUIElement * > Children
List of all children of this element.
IGUIElement * Parent
Pointer to the parent.
std::list< IGUIElement * >::iterator ParentPos
Our position in the parent list. Only valid when Parent != nullptr.
core::rect< s32 > RelativeRect
relative rect of element
core::rect< s32 > AbsoluteRect
absolute rect of element
core::rect< s32 > AbsoluteClippingRect
absolute clipping rect of element
core::rect< s32 > DesiredRect
core::rect< s32 > LastParentRect
for calculating the difference when resizing parent
core::rect< f32 > ScaleRect
relative scale of the element inside its parent
core::dimension2du MaxSize
maximum and minimum size of the element
core::dimension2du MinSize
bool IsVisible
is visible?
bool IsEnabled
is enabled?
bool IsSubElement
is a part of a larger whole and should not be serialized?
bool NoClip
does this element ignore its parent's clipping rectangle?
core::stringw Text
caption
core::stringw ToolTipText
tooltip
core::stringc Name
users can set this for identifying the element by string
s32 ID
users can set this for identifying the element by integer
bool IsTabStop
tab stop like in windows
s32 TabOrder
tab order
bool IsTabGroup
tab groups are containers like windows, use ctrl+tab to navigate
EGUI_ALIGNMENT AlignLeft
tells the element how to act when its parent is resized
EGUI_ALIGNMENT AlignRight
EGUI_ALIGNMENT AlignTop
EGUI_ALIGNMENT AlignBottom
IGUIEnvironment * Environment
GUI Environment.
EGUI_ELEMENT_TYPE Type
type of element
Detailed Description
Definition at line 19 of file CGUIListBox.h.
Member Function Documentation
addItem() [1/2]
u32 irr::gui::CGUIListBox::addItem (const wchar_t * text) override virtual
adds an list item, returns id of item
adds a list item, returns id of item
Implements irr::gui::IGUIListBox.
Definition at line 100 of file CGUIListBox.cpp.
addItem() [2/2]
u32 irr::gui::CGUIListBox::addItem (const wchar_t * text, s32 icon) override virtual
adds an list item with an icon
adds an list item with an icon
Parameters
text Text of list entry
icon Sprite index of the Icon within the current sprite bank. Set it to -1 if you want no icon
Returns
returns the id of the new created item
Implements irr::gui::IGUIListBox.
Definition at line 594 of file CGUIListBox.cpp.
getListItem()
const wchar_t * irr::gui::CGUIListBox::getListItem (u32 id) const override virtual
returns string of a list item. the id may be a value from 0 to itemCount-1
returns string of a list item. the may be a value from 0 to itemCount-1
Implements irr::gui::IGUIListBox.
Definition at line 80 of file CGUIListBox.cpp.
insertItem()
s32 irr::gui::CGUIListBox::insertItem (u32 index, const wchar_t * text, s32 icon) override virtual
Insert the item at the given index Return the index on success or -1 on failure.
Implements irr::gui::IGUIListBox.
Definition at line 719 of file CGUIListBox.cpp.
removeItem()
void irr::gui::CGUIListBox::removeItem (u32 id) override virtual
removes an item from the list
adds a list item, returns id of item
Implements irr::gui::IGUIListBox.
Definition at line 107 of file CGUIListBox.cpp.
References irr::os::Timer::getTime().
setSpriteBank()
void irr::gui::CGUIListBox::setSpriteBank (IGUISpriteBank * bank) override virtual
Sets the sprite bank which should be used to draw list icons. This font is set to the sprite bank of the built-in-font by default. A sprite can be displayed in front of every list item. An icon is an index within the icon sprite bank. Several default icons are available in the skin through getIcon
Implements irr::gui::IGUIListBox.
Definition at line 608 of file CGUIListBox.cpp.
References irr::IReferenceCounted::drop(), and irr::IReferenceCounted::grab().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CGUIListBox.h
lib/irrlichtmt/source/Irrlicht/CGUIListBox.cpp