Three Cubes Game: Game Class Reference
Game Class Reference
Classes
struct Flags
Public Member Functions
bool startup (bool *kill, InputHandler *input, RenderingEngine *rendering_engine, const GameStartData &game_params, std::string &error_message, bool *reconnect, ChatBackend *chat_backend)
void run ()
void shutdown ()
Protected Member Functions
bool init (const std::string &map_dir, const std::string &address, u16 port, const SubgameSpec &gamespec)
bool initSound ()
bool createSingleplayerServer (const std::string &map_dir, const SubgameSpec &gamespec, u16 port)
bool createClient (const GameStartData &start_data)
bool initGui ()
bool connectToServer (const GameStartData &start_data, bool *connect_ok, bool *aborted)
bool getServerContent (bool *aborted)
void updateInteractTimers (f32 dtime)
bool checkConnection ()
bool handleCallbacks ()
void processQueues ()
void updateProfilers (const RunStats &stats, const FpsControl &draw_times, f32 dtime)
void updateDebugState ()
void updateStats (RunStats *stats, const FpsControl &draw_times, f32 dtime)
void updateProfilerGraphs (ProfilerGraph *graph)
void processUserInput (f32 dtime)
void processKeyInput ()
void processItemSelection (u16 *new_playeritem)
void dropSelectedItem (bool single_item=false)
void openInventory ()
void openConsole (float scale, const wchar_t *line=NULL)
void toggleFreeMove ()
void toggleFreeMoveAlt ()
void togglePitchMove ()
void toggleFast ()
void toggleNoClip ()
void toggleCinematic ()
void toggleBlockBounds ()
void toggleAutoforward ()
void toggleMinimap (bool shift_pressed)
void toggleFog ()
void toggleDebug ()
void toggleUpdateCamera ()
void increaseViewRange ()
void decreaseViewRange ()
void toggleFullViewRange ()
void checkZoomEnabled ()
void updateCameraDirection (CameraOrientation *cam, float dtime)
void updateCameraOrientation (CameraOrientation *cam, float dtime)
void updatePlayerControl (const CameraOrientation &cam)
void step (f32 dtime)
void processClientEvents (CameraOrientation *cam)
void updateCamera (f32 dtime)
void updateSound (f32 dtime)
void processPlayerInteraction (f32 dtime, bool show_hud)
PointedThing updatePointedThing (const core::line3d< f32 > &shootline, bool liquids_pointable, bool look_for_object, const v3s16 &camera_offset)
void handlePointingAtNothing (const ItemStack &playerItem)
void handlePointingAtNode (const PointedThing &pointed, const ItemStack &selected_item, const ItemStack &hand_item, f32 dtime)
void handlePointingAtObject (const PointedThing &pointed, const ItemStack &playeritem, const v3f &player_position, bool show_debug)
void handleDigging (const PointedThing &pointed, const v3s16 &nodepos, const ItemStack &selected_item, const ItemStack &hand_item, f32 dtime)
void updateFrame (ProfilerGraph *graph, RunStats *stats, f32 dtime, const CameraOrientation &cam)
void updateShadows ()
void showOverlayMessage (const char *msg, float dtime, int percent, bool draw_clouds=true)
void readSettings ()
bool isKeyDown (GameKeyType k)
bool wasKeyDown (GameKeyType k)
bool wasKeyPressed (GameKeyType k)
bool wasKeyReleased (GameKeyType k)
Static Protected Member Functions
static void settingChangedCallback (const std::string &setting_name, void *data)
Private Member Functions
void showDeathFormspec ()
void showPauseMenu ()
void pauseAnimation ()
void resumeAnimation ()
void handleClientEvent_None (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_PlayerDamage (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_PlayerForceMove (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_Deathscreen (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_ShowFormSpec (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_ShowLocalFormSpec (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_HandleParticleEvent (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_HudAdd (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_HudRemove (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_HudChange (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_SetSky (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_SetSun (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_SetMoon (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_SetStars (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_OverrideDayNigthRatio (ClientEvent *event, CameraOrientation *cam)
void handleClientEvent_CloudParams (ClientEvent *event, CameraOrientation *cam)
void updateChat (f32 dtime)
bool nodePlacement (const ItemDefinition &selected_def, const ItemStack &selected_item, const v3s16 &nodepos, const v3s16 &neighborpos, const PointedThing &pointed, const NodeMetadata *meta)
f32 getSensitivityScaleFactor () const
ClientDynamicInfo getCurrentDynamicInfo () const
Private Attributes
InputHandler * input = nullptr
Client * client = nullptr
Server * server = nullptr
ClientDynamicInfo client_display_info {}
float dynamic_info_send_timer = 0
IWritableTextureSource * texture_src = nullptr
IWritableShaderSource * shader_src = nullptr
IWritableItemDefManager * itemdef_manager = nullptr
NodeDefManager * nodedef_manager = nullptr
GameOnDemandSoundFetcher soundfetcher
std::unique_ptr< ISoundManager > sound_manager
SoundMaker * soundmaker = nullptr
ChatBackend * chat_backend = nullptr
LogOutputBuffer m_chat_log_buf
EventManager * eventmgr = nullptr
QuicktuneShortcutter * quicktune = nullptr
std::unique_ptr< GameUI > m_game_ui
GUIChatConsole * gui_chat_console = nullptr
MapDrawControl * draw_control = nullptr
Camera * camera = nullptr
Clouds * clouds = nullptr
Sky * sky = nullptr
Hud * hud = nullptr
Minimap * mapper = nullptr
std::unordered_map< u32, u32 > m_hud_server_to_client
GameRunData runData
Flags m_flags
IrrlichtDevice * device
RenderingEngine * m_rendering_engine
video::IVideoDriver * driver
scene::ISceneManager * smgr
bool * kill
std::string * error_message
bool * reconnect_requested
scene::ISceneNode * skybox
PausedNodesList paused_animated_nodes
bool simple_singleplayer_mode
int crack_animation_length
IntervalLimiter profiler_interval
bool m_cache_doubletap_jump
bool m_cache_enable_clouds
bool m_cache_enable_joysticks
bool m_cache_enable_particles
bool m_cache_enable_fog
bool m_cache_enable_noclip
bool m_cache_enable_free_move
f32 m_cache_mouse_sensitivity
f32 m_cache_joystick_frustum_sensitivity
f32 m_repeat_place_time
f32 m_cache_cam_smoothing
f32 m_cache_fog_start
bool m_invert_mouse
bool m_enable_hotbar_mouse_wheel
bool m_invert_hotbar_mouse_wheel
bool m_first_loop_after_window_activation = false
bool m_camera_offset_changed = false
bool m_game_focused
bool m_does_lost_focus_pause_game = false
bool m_is_paused = false
Static Private Attributes
static const ClientEventHandler clientEventHandler [CLIENTEVENT_MAX]
Detailed Description
Definition at line 757 of file game.cpp.
Member Function Documentation
updatePointedThing()
PointedThing Game::updatePointedThing (const core::line3d< f32 > & shootline, bool liquids_pointable, bool look_for_object, const v3s16 & camera_offset) protected
Returns the object or node the player is pointing at. Also updates the selected thing in the Hud.
Parameters
[in] shootline the shootline, starting from the camera position. This also gives the maximal distance of the search.
[in] liquids_pointable if false, liquids are ignored
[in] look_for_object if false, objects are ignored
[in] camera_offset offset of the camera
[out] selected_object the selected object or NULL if not found
Definition at line 3394 of file game.cpp.
References irr::scene::ISceneNode::getAbsoluteTransformation(), irr::video::SColor::getBlue(), irr::video::SColor::getGreen(), MapNode::getNeighbors(), irr::video::SColor::getRed(), irr::core::CMatrix4< T >::getRotationDegrees(), ClientActiveObject::getSelectionBox(), PointedThing::intersection_normal, irr::core::aabbox3d< T >::MaxEdge, irr::core::aabbox3d< T >::MinEdge, PointedThing::node_undersurface, PointedThing::object_id, irr::core::PI, PointedThing::raw_intersection_normal, irr::video::SColor::setBlue(), irr::video::SColor::setGreen(), irr::video::SColor::setRed(), and PointedThing::type.
Member Data Documentation
clientEventHandler
const ClientEventHandler Game::clientEventHandler static private
Initial value:
= {
    {&Game::handleClientEvent_None},
    {&Game::handleClientEvent_PlayerDamage},
    {&Game::handleClientEvent_PlayerForceMove},
    {&Game::handleClientEvent_Deathscreen},
    {&Game::handleClientEvent_ShowFormSpec},
    {&Game::handleClientEvent_ShowLocalFormSpec},
    {&Game::handleClientEvent_HandleParticleEvent},
    {&Game::handleClientEvent_HandleParticleEvent},
    {&Game::handleClientEvent_HandleParticleEvent},
    {&Game::handleClientEvent_HudAdd},
    {&Game::handleClientEvent_HudRemove},
    {&Game::handleClientEvent_HudChange},
    {&Game::handleClientEvent_SetSky},
    {&Game::handleClientEvent_SetSun},
    {&Game::handleClientEvent_SetMoon},
    {&Game::handleClientEvent_SetStars},
    {&Game::handleClientEvent_OverrideDayNigthRatio},
    {&Game::handleClientEvent_CloudParams},
}
Definition at line 929 of file game.cpp.
The documentation for this class was generated from the following file:
src/client/game.cpp