Three Cubes Game: irr::gui::CGUIFont Class Reference
irr::gui::CGUIFont Class Reference
Classes
struct SFontArea
Public Member Functions
CGUIFont (IGUIEnvironment *env, const io::path &filename)
constructor
virtual ~CGUIFont ()
destructor
bool load (const io::path &filename)
loads a font from a texture file
bool load (io::IReadFile *file)
loads a font from a texture file
virtual void draw (const core::stringw &text, const core::rect< s32 > &position, video::SColor color, bool hcenter=false, bool vcenter=false, const core::rect< s32 > *clip=0) override
draws an text and clips it to the specified rectangle if wanted
core::dimension2d< u32 > getDimension (const wchar_t *text) const override
returns the dimension of a text
s32 getCharacterFromPos (const wchar_t *text, s32 pixel_x) const override
Calculates the index of the character in the text which is on a specific position.
EGUI_FONT_TYPE getType () const override
Returns the type of this font.
void setKerningWidth (s32 kerning) override
set an Pixel Offset on Drawing (scale position on width)
void setKerningHeight (s32 kerning) override
set an Pixel Offset on Drawing (scale position on height)
s32 getKerningWidth (const wchar_t *thisLetter=0, const wchar_t *previousLetter=0) const override
set an Pixel Offset on Drawing (scale position on width)
s32 getKerningHeight () const override
set an Pixel Offset on Drawing (scale position on height)
IGUISpriteBank * getSpriteBank () const override
gets the sprite bank
u32 getSpriteNoFromChar (const wchar_t *c) const override
returns the sprite number from a given character
void setInvisibleCharacters (const wchar_t *s) override
Define which characters should not be drawn by the font.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Member Functions
bool loadTexture (video::IImage *image, const io::path &name)
load & prepare font from ITexture
void readPositions (video::IImage *texture, s32 &lowerRightPositions)
s32 getAreaFromCharacter (const wchar_t c) const
void setMaxHeight ()
void pushTextureCreationFlags (bool(&flags)[3])
void popTextureCreationFlags (const bool(&flags)[3])
Private Attributes
core::array< SFontArea > Areas
std::map< wchar_t, s32 > CharacterMap
video::IVideoDriver * Driver
IGUISpriteBank * SpriteBank
IGUIEnvironment * Environment
u32 WrongCharacter
s32 MaxHeight
s32 GlobalKerningWidth
s32 GlobalKerningHeight
core::stringw Invisible
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Definition at line 28 of file CGUIFont.h.
Member Function Documentation
draw()
void irr::gui::CGUIFont::draw (const core::stringw & text, const core::rect< s32 > & position, video::SColor color, bool hcenter = false, bool vcenter = false, const core::rect< s32 > * clip = 0) override virtual
draws an text and clips it to the specified rectangle if wanted
draws some text and clips it to the specified rectangle if wanted
Implements irr::gui::IGUIFont.
Definition at line 492 of file CGUIFont.cpp.
References irr::core::rect< T >::clipAgainst(), irr::gui::IGUISpriteBank::draw2DSpriteBatch(), getDimension(), irr::core::rect< T >::getHeight(), irr::core::rect< T >::getWidth(), irr::core::dimension2d< T >::Height, irr::core::rect< T >::isValid(), irr::core::array< T >::push_back(), irr::core::rect< T >::UpperLeftCorner, and irr::core::dimension2d< T >::Width.
getDimension()
core::dimension2d< u32 > irr::gui::CGUIFont::getDimension (const wchar_t * text) const override virtual
returns the dimension of a text
returns the dimension of text
Implements irr::gui::IGUIFont.
Definition at line 451 of file CGUIFont.cpp.
References irr::core::dimension2d< T >::Height, and irr::core::dimension2d< T >::Width.
Referenced by draw().
load() [1/2]
bool irr::gui::CGUIFont::load (const io::path & filename)
loads a font from a texture file
loads a font file, native file needed, for texture parsing
Definition at line 247 of file CGUIFont.cpp.
References irr::video::IVideoDriver::createImageFromFile(), and loadTexture().
Referenced by irr::gui::CGUIEnvironment::getFont().
load() [2/2]
bool irr::gui::CGUIFont::load (io::IReadFile * file)
loads a font from a texture file
loads a font file, native file needed, for texture parsing
Definition at line 236 of file CGUIFont.cpp.
References irr::video::IVideoDriver::createImageFromFile(), and loadTexture().
setInvisibleCharacters()
void irr::gui::CGUIFont::setInvisibleCharacters (const wchar_t * s) override virtual
Define which characters should not be drawn by the font.
For example " " would not draw any space which is usually blank in most fonts.
Parameters
s String of symbols which are not send down to the videodriver
Implements irr::gui::IGUIFont.
Definition at line 444 of file CGUIFont.cpp.
Referenced by CGUIFont().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CGUIFont.h
lib/irrlichtmt/source/Irrlicht/CGUIFont.cpp