Three Cubes Game: FontEngine Class Reference
FontEngine Class Reference
Public Member Functions
FontEngine (gui::IGUIEnvironment *env)
irr::gui::IGUIFont * getFont (FontSpec spec)
irr::gui::IGUIFont * getFont (unsigned int font_size=FONT_SIZE_UNSPECIFIED, FontMode mode=FM_Unspecified)
unsigned int getTextHeight (const FontSpec &spec)
unsigned int getTextHeight (unsigned int font_size=FONT_SIZE_UNSPECIFIED, FontMode mode=FM_Unspecified)
unsigned int getTextWidth (const std::wstring &text, const FontSpec &spec)
unsigned int getTextWidth (const std::wstring &text, unsigned int font_size=FONT_SIZE_UNSPECIFIED, FontMode mode=FM_Unspecified)
unsigned int getTextWidth (const std::string &text, const FontSpec &spec)
unsigned int getTextWidth (const std::string &text, unsigned int font_size=FONT_SIZE_UNSPECIFIED, FontMode mode=FM_Unspecified)
unsigned int getLineHeight (const FontSpec &spec)
unsigned int getLineHeight (unsigned int font_size=FONT_SIZE_UNSPECIFIED, FontMode mode=FM_Unspecified)
unsigned int getDefaultFontSize ()
unsigned int getFontSize (FontMode mode)
void readSettings ()
Private Member Functions
irr::gui::IGUIFont * getFont (FontSpec spec, bool may_fail)
void updateFontCache ()
gui::IGUIFont * initFont (const FontSpec &spec)
void updateSkin ()
void cleanCache ()
DISABLE_CLASS_COPY (FontEngine)
Private Attributes
gui::IGUIEnvironment * m_env = nullptr
std::recursive_mutex m_font_mutex
std::map< unsigned int, irr::gui::IGUIFont * > m_font_cache [FM_MaxMode<< 2]
unsigned int m_default_size [FM_MaxMode]
bool m_default_bold = false
bool m_default_italic = false
Static Private Attributes
static const FontMode m_currentMode = FM_Standard
Detailed Description
Definition at line 59 of file fontengine.h.
Member Function Documentation
cleanCache()
void FontEngine::cleanCache () private
clean cache
Definition at line 78 of file fontengine.cpp.
References m_font_cache, and m_font_mutex.
Referenced by readSettings().
getDefaultFontSize()
unsigned int FontEngine::getDefaultFontSize ()
get default font size
Definition at line 160 of file fontengine.cpp.
References m_currentMode, and m_default_size.
getFontSize()
unsigned int FontEngine::getFontSize (FontMode mode)
get font size for a specific mode
Definition at line 165 of file fontengine.cpp.
References m_default_size.
getLineHeight()
unsigned int FontEngine::getLineHeight (const FontSpec & spec)
get line height for a specific font (including empty room between lines)
Definition at line 151 of file fontengine.cpp.
References irr::gui::IGUIFont::getDimension(), irr::gui::IGUIFont::getKerningHeight(), and irr::core::dimension2d< T >::Height.
getTextHeight() [1/2]
unsigned int FontEngine::getTextHeight (const FontSpec & spec)
get text height for a specific font
Definition at line 135 of file fontengine.cpp.
References irr::gui::IGUIFont::getDimension(), and irr::core::dimension2d< T >::Height.
Referenced by getTextHeight(), GUIEngine::GUIEngine(), GUIEngine::run(), and GUIEngine::updateTopLeftTextSize().
getTextHeight() [2/2]
unsigned int FontEngine::getTextHeight (unsigned int font_size = FONT_SIZE_UNSPECIFIED, FontMode mode = FM_Unspecified) inline
get text width if a text for a specific font
Definition at line 81 of file fontengine.h.
References getTextHeight(), and m_default_bold.
getTextWidth()
unsigned int FontEngine::getTextWidth (const std::wstring & text, unsigned int font_size = FONT_SIZE_UNSPECIFIED, FontMode mode = FM_Unspecified) inline
get text width if a text for a specific font
Definition at line 92 of file fontengine.h.
References m_default_bold.
initFont()
gui::IGUIFont * FontEngine::initFont (const FontSpec & spec) private
initialize a new TTF font
Definition at line 206 of file fontengine.cpp.
References m_env, and irr::gui::CGUITTFont::setFallback().
readSettings()
void FontEngine::readSettings ()
update internal parameters from settings
Definition at line 174 of file fontengine.cpp.
References cleanCache(), m_default_bold, m_default_size, updateFontCache(), and updateSkin().
updateFontCache()
void FontEngine::updateFontCache () private
update content of font cache in case of a setting change made it invalid
Definition at line 198 of file fontengine.cpp.
Referenced by readSettings().
updateSkin()
void FontEngine::updateSkin () private
update current minetest skin with font changes
Definition at line 189 of file fontengine.cpp.
References irr::gui::IGUIEnvironment::getSkin(), m_env, and irr::gui::IGUISkin::setFont().
Referenced by readSettings().
Member Data Documentation
m_currentMode
const FontMode FontEngine::m_currentMode = FM_Standard static private
default font engine mode (fixed)
Definition at line 164 of file fontengine.h.
Referenced by getDefaultFontSize().
m_default_bold
bool FontEngine::m_default_bold = false private
default bold and italic
Definition at line 160 of file fontengine.h.
Referenced by getTextHeight(), getTextWidth(), and readSettings().
m_default_size
unsigned int FontEngine::m_default_size[FM_MaxMode] private
default font size to use
Definition at line 157 of file fontengine.h.
Referenced by getDefaultFontSize(), getFontSize(), and readSettings().
m_env
gui::IGUIEnvironment* FontEngine::m_env = nullptr private
pointer to irrlicht gui environment
Definition at line 148 of file fontengine.h.
Referenced by initFont(), and updateSkin().
m_font_cache
std::map<unsigned int, irr::gui::IGUIFont*> FontEngine::m_font_cache[FM_MaxMode<< 2] private
internal storage for caching fonts of different size
Definition at line 154 of file fontengine.h.
Referenced by cleanCache().
m_font_mutex
std::recursive_mutex FontEngine::m_font_mutex private
mutex used to protect font init and cache
Definition at line 151 of file fontengine.h.
Referenced by cleanCache().
The documentation for this class was generated from the following files:
src/client/fontengine.h
src/client/fontengine.cpp