Three Cubes Game: irr::io::CFileList Class Reference
irr::io::CFileList Class Reference
Implementation of a file list.
#include <CFileList.h>
Public Member Functions
CFileList (const io::path &path, bool ignoreCase, bool ignorePaths)
Constructor.
virtual ~CFileList ()
Destructor.
u32 addItem (const io::path &fullPath, u32 offset, u32 size, bool isDirectory, u32 id=0) override
Add as a file or folder to the list.
void sort () override
Sorts the file list. You should call this after adding any items to the file list.
u32 getFileCount () const override
Returns the amount of files in the filelist.
const io::path & getFileName (u32 index) const override
Gets the name of a file in the list, based on an index.
const io::path & getFullFileName (u32 index) const override
Gets the full name of a file in the list, path included, based on an index.
u32 getID (u32 index) const override
Returns the ID of a file in the file list, based on an index.
bool isDirectory (u32 index) const override
Returns true if the file is a directory.
u32 getFileSize (u32 index) const override
Returns the size of a file.
u32 getFileOffset (u32 index) const override
Returns the offset of a file.
s32 findFile (const io::path &filename, bool isFolder) const override
Searches for a file or folder within the list, returns the index.
const io::path & getPath () const override
Returns the base path of the file list.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Protected Attributes
bool IgnorePaths
Ignore paths when adding or searching for files.
bool IgnoreCase
Ignore case when adding or searching for files.
io::path Path
Path to the file list.
core::array< SFileListEntry > Files
List of files.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Implementation of a file list.
Definition at line 66 of file CFileList.h.
Constructor & Destructor Documentation
CFileList()
irr::io::CFileList::CFileList (const io::path & path, bool ignoreCase, bool ignorePaths)
Constructor.
Parameters
path The path of this file archive
Definition at line 18 of file CFileList.cpp.
References Path, irr::core::string< T >::replace(), and irr::IReferenceCounted::setDebugName().
Member Function Documentation
addItem()
u32 irr::io::CFileList::addItem (const io::path & fullPath, u32 offset, u32 size, bool isDirectory, u32 id = 0) override virtual
Add as a file or folder to the list.
adds a file or folder
Parameters
fullPath The file name including path, up to the root of the file list.
isDirectory True if this is a directory rather than a file.
offset The offset where the file is stored in an archive
size The size of the file in bytes.
id The ID of the file in the archive which owns it
Implements irr::io::IFileList.
Definition at line 62 of file CFileList.cpp.
References irr::core::deletePathFromFilename(), Files, irr::io::SFileListEntry::FullName, irr::io::SFileListEntry::ID, IgnoreCase, IgnorePaths, irr::io::SFileListEntry::IsDirectory, isDirectory(), irr::core::string< T >::lastChar(), irr::core::string< T >::make_lower(), irr::io::SFileListEntry::Name, irr::io::SFileListEntry::Offset, irr::core::string< T >::replace(), irr::io::SFileListEntry::Size, irr::core::string< T >::size(), and irr::core::string< T >::validate().
Referenced by irr::io::CFileSystem::createFileList(), irr::io::CZipReader::scanGZipHeader(), and irr::io::CZipReader::scanZipHeader().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CFileList.h
lib/irrlichtmt/source/Irrlicht/CFileList.cpp