Three Cubes Game: irr::scene::ISceneManager Class Reference
irr::scene::ISceneManager Class Reference abstract
The Scene Manager manages scene nodes, mesh resources, cameras and all the other stuff.
#include <ISceneManager.h>
Public Member Functions
virtual IAnimatedMesh * getMesh (io::IReadFile *file)=0
Get pointer to an animateable mesh. Loads the file if not loaded already.
virtual IMeshCache * getMeshCache ()=0
Get interface to the mesh cache which is shared between all existing scene managers.
virtual video::IVideoDriver * getVideoDriver ()=0
Get the video driver.
virtual IAnimatedMeshSceneNode * addAnimatedMeshSceneNode (IAnimatedMesh *mesh, ISceneNode *parent=0, s32 id=-1, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f), bool alsoAddIfMeshPointerZero=false)=0
Adds a scene node for rendering an animated mesh model.
virtual IMeshSceneNode * addMeshSceneNode (IMesh *mesh, ISceneNode *parent=0, s32 id=-1, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &rotation=core::vector3df(0, 0, 0), const core::vector3df &scale=core::vector3df(1.0f, 1.0f, 1.0f), bool alsoAddIfMeshPointerZero=false)=0
Adds a scene node for rendering a static mesh.
virtual ICameraSceneNode * addCameraSceneNode (ISceneNode *parent=0, const core::vector3df &position=core::vector3df(0, 0, 0), const core::vector3df &lookat=core::vector3df(0, 0, 100), s32 id=-1, bool makeActive=true)=0
Adds a camera scene node to the scene graph and sets it as active camera.
virtual IBillboardSceneNode * addBillboardSceneNode (ISceneNode *parent=0, const core::dimension2d< f32 > &size=core::dimension2d< f32 >(10.0f, 10.0f), const core::vector3df &position=core::vector3df(0, 0, 0), s32 id=-1, video::SColor colorTop=0xFFFFFFFF, video::SColor colorBottom=0xFFFFFFFF)=0
Adds a billboard scene node to the scene graph.
virtual ISceneNode * addEmptySceneNode (ISceneNode *parent=0, s32 id=-1)=0
Adds an empty scene node to the scene graph.
virtual IDummyTransformationSceneNode * addDummyTransformationSceneNode (ISceneNode *parent=0, s32 id=-1)=0
Adds a dummy transformation scene node to the scene graph.
virtual ISceneNode * getRootSceneNode ()=0
Gets the root scene node.
virtual ISceneNode * getSceneNodeFromId (s32 id, ISceneNode *start=0)=0
Get the first scene node with the specified id.
virtual ISceneNode * getSceneNodeFromName (const c8 *name, ISceneNode *start=0)=0
Get the first scene node with the specified name.
virtual ISceneNode * getSceneNodeFromType (scene::ESCENE_NODE_TYPE type, ISceneNode *start=0)=0
Get the first scene node with the specified type.
virtual void getSceneNodesFromType (ESCENE_NODE_TYPE type, core::array< scene::ISceneNode * > &outNodes, ISceneNode *start=0)=0
Get scene nodes by type.
virtual ICameraSceneNode * getActiveCamera () const =0
Get the current active camera.
virtual void setActiveCamera (ICameraSceneNode *camera)=0
Sets the currently active camera.
virtual u32 registerNodeForRendering (ISceneNode *node, E_SCENE_NODE_RENDER_PASS pass=ESNRP_AUTOMATIC)=0
Registers a node for rendering it at a specific time.
virtual void clearAllRegisteredNodesForRendering ()=0
Clear all nodes which are currently registered for rendering.
virtual void drawAll ()=0
Draws all the scene nodes.
virtual void addExternalMeshLoader (IMeshLoader *externalLoader)=0
Adds an external mesh loader for extending the engine with new file formats.
virtual u32 getMeshLoaderCount () const =0
Returns the number of mesh loaders supported by Irrlicht at this time.
virtual IMeshLoader * getMeshLoader (u32 index) const =0
Retrieve the given mesh loader.
virtual ISceneCollisionManager * getSceneCollisionManager ()=0
Get pointer to the scene collision manager.
virtual IMeshManipulator * getMeshManipulator ()=0
Get pointer to the mesh manipulator.
virtual void addToDeletionQueue (ISceneNode *node)=0
Adds a scene node to the deletion queue.
virtual bool postEventFromUser (const SEvent &event)=0
Posts an input event to the environment.
virtual void clear ()=0
Clears the whole scene.
virtual io::IAttributes * getParameters ()=0
Get interface to the parameters set in this scene.
virtual E_SCENE_NODE_RENDER_PASS getSceneNodeRenderPass () const =0
Get current render pass.
virtual ISceneManager * createNewSceneManager (bool cloneContent=false)=0
Creates a new scene manager.
virtual IMeshWriter * createMeshWriter (EMESH_WRITER_TYPE type)=0
Get a mesh writer implementation if available.
virtual ISkinnedMesh * createSkinnedMesh ()=0
Get a skinned mesh, which is not available as header-only code.
virtual void setAmbientLight (const video::SColorf &ambientColor)=0
Sets ambient color of the scene.
virtual const video::SColorf & getAmbientLight () const =0
Get ambient color of the scene.
virtual E_SCENE_NODE_RENDER_PASS getCurrentRenderPass () const =0
Get current render pass.
virtual void setCurrentRenderPass (E_SCENE_NODE_RENDER_PASS nextPass)=0
Set current render pass.
virtual bool isCulled (const ISceneNode *node) const =0
Check if node is culled in current view frustum.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
The Scene Manager manages scene nodes, mesh resources, cameras and all the other stuff.
All Scene nodes can be created only here. A scene node is a node in the hierarchical scene graph. Every scene node may have children, which are other scene nodes. Children move relative the their parents position. If the parent of a node is not visible, its children won't be visible, too. In this way, it is for example easily possible to attach a light to a moving car or to place a walking character on a moving platform on a moving ship. The SceneManager is also able to load 3d mesh files of different formats. Take a look at getMesh() to find out what formats are supported. If these formats are not enough, use addExternalMeshLoader() to add new formats to the engine.
Definition at line 129 of file ISceneManager.h.
Member Function Documentation
addAnimatedMeshSceneNode()
virtual IAnimatedMeshSceneNode* irr::scene::ISceneManager::addAnimatedMeshSceneNode (IAnimatedMesh * mesh, ISceneNode * parent = 0, s32 id = -1, const core::vector3df & position = core::vector3df(0, 0, 0), const core::vector3df & rotation = core::vector3df(0, 0, 0), const core::vector3df & scale = core::vector3df(1.0f, 1.0f, 1.0f), bool alsoAddIfMeshPointerZero = false) pure virtual
Adds a scene node for rendering an animated mesh model.
Parameters
mesh Pointer to the loaded animated mesh to be displayed.
parent Parent of the scene node. Can be NULL if no parent.
id Id of the node. This id can be used to identify the scene node.
position Position of the space relative to its parent where the scene node will be placed.
rotation Initial rotation of the scene node.
scale Initial scale of the scene node.
alsoAddIfMeshPointerZero Add the scene node even if a 0 pointer is passed.
Returns
Pointer to the created scene node. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
addBillboardSceneNode()
virtual IBillboardSceneNode* irr::scene::ISceneManager::addBillboardSceneNode (ISceneNode * parent = 0, const core::dimension2d< f32 > & size = core::dimension2d< f32 >(10.0f, 10.0f), const core::vector3df & position = core::vector3df(0, 0, 0), s32 id = -1, video::SColor colorTop = 0xFFFFFFFF, video::SColor colorBottom = 0xFFFFFFFF) pure virtual
Adds a billboard scene node to the scene graph.
A billboard is like a 3d sprite: A 2d element, which always looks to the camera. It is usually used for things like explosions, fire, lensflares and things like that.
Parameters
parent Parent scene node of the billboard. Can be null. If the parent moves, the billboard will move too.
size Size of the billboard. This size is 2 dimensional because a billboard only has width and height.
position Position of the space relative to its parent where the billboard will be placed.
id An id of the node. This id can be used to identify the node.
colorTop The color of the vertices at the top of the billboard (default: white).
colorBottom The color of the vertices at the bottom of the billboard (default: white).
Returns
Pointer to the billboard if successful, otherwise NULL. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
addCameraSceneNode()
virtual ICameraSceneNode* irr::scene::ISceneManager::addCameraSceneNode (ISceneNode * parent = 0, const core::vector3df & position = core::vector3df(0, 0, 0), const core::vector3df & lookat = core::vector3df(0, 0, 100), s32 id = -1, bool makeActive = true) pure virtual
Adds a camera scene node to the scene graph and sets it as active camera.
This camera does not react on user input. If you want to move or animate it, use ISceneNode::setPosition(), ICameraSceneNode::setTarget() etc methods. By default, a camera's look at position (set with setTarget()) and its scene node rotation (set with setRotation()) are independent. If you want to be able to control the direction that the camera looks by using setRotation() then call ICameraSceneNode::bindTargetAndRotation(true) on it.
Parameters
position Position of the space relative to its parent where the camera will be placed.
lookat Position where the camera will look at. Also known as target.
parent Parent scene node of the camera. Can be null. If the parent moves, the camera will move too.
id id of the camera. This id can be used to identify the camera.
makeActive Flag whether this camera should become the active one. Make sure you always have one active camera.
Returns
Pointer to interface to camera if successful, otherwise 0. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
Referenced by GUIEngine::cloudInit().
addDummyTransformationSceneNode()
virtual IDummyTransformationSceneNode* irr::scene::ISceneManager::addDummyTransformationSceneNode (ISceneNode * parent = 0, s32 id = -1) pure virtual
Adds a dummy transformation scene node to the scene graph.
This scene node does not render itself, and does not respond to set/getPosition, set/getRotation and set/getScale. Its just a simple scene node that takes a matrix as relative transformation, making it possible to insert any transformation anywhere into the scene graph.
Returns
Pointer to the created scene node. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
addEmptySceneNode()
virtual ISceneNode* irr::scene::ISceneManager::addEmptySceneNode (ISceneNode * parent = 0, s32 id = -1) pure virtual
Adds an empty scene node to the scene graph.
Can be used for doing advanced transformations or structuring the scene graph.
Returns
Pointer to the created scene node. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
Referenced by irr::gui::CGUITTFont::addTextSceneNode(), and GUIScene::draw().
addExternalMeshLoader()
virtual void irr::scene::ISceneManager::addExternalMeshLoader (IMeshLoader * externalLoader) pure virtual
Adds an external mesh loader for extending the engine with new file formats.
If you want the engine to be extended with file formats it currently is not able to load (e.g. .cob), just implement the IMeshLoader interface in your loading class and add it with this method. Using this method it is also possible to override built-in mesh loaders with newer or updated versions without the need to recompile the engine.
Parameters
externalLoader Implementation of a new mesh loader.
Implemented in irr::scene::CSceneManager.
addMeshSceneNode()
virtual IMeshSceneNode* irr::scene::ISceneManager::addMeshSceneNode (IMesh * mesh, ISceneNode * parent = 0, s32 id = -1, const core::vector3df & position = core::vector3df(0, 0, 0), const core::vector3df & rotation = core::vector3df(0, 0, 0), const core::vector3df & scale = core::vector3df(1.0f, 1.0f, 1.0f), bool alsoAddIfMeshPointerZero = false) pure virtual
Adds a scene node for rendering a static mesh.
Parameters
mesh Pointer to the loaded static mesh to be displayed.
parent Parent of the scene node. Can be NULL if no parent.
id Id of the node. This id can be used to identify the scene node.
position Position of the space relative to its parent where the scene node will be placed.
rotation Initial rotation of the scene node.
scale Initial scale of the scene node.
alsoAddIfMeshPointerZero Add the scene node even if a 0 pointer is passed.
Returns
Pointer to the created scene node. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
Referenced by irr::gui::CGUITTFont::addTextSceneNode().
addToDeletionQueue()
virtual void irr::scene::ISceneManager::addToDeletionQueue (ISceneNode * node) pure virtual
Adds a scene node to the deletion queue.
The scene node is immediately deleted when it's secure. Which means when the scene node does not execute animators and things like that. This method is for example used for deleting scene nodes by their scene node animators. In most other cases, a ISceneNode::remove() call is enough, using this deletion queue is not necessary. See ISceneManager::createDeleteAnimator() for details.
Parameters
node Node to delete.
Implemented in irr::scene::CSceneManager.
clear()
virtual void irr::scene::ISceneManager::clear () pure virtual
Clears the whole scene.
All scene nodes are removed.
Implemented in irr::scene::CSceneManager.
clearAllRegisteredNodesForRendering()
virtual void irr::scene::ISceneManager::clearAllRegisteredNodesForRendering () pure virtual
Clear all nodes which are currently registered for rendering.
Usually you don't have to care about this as drawAll will clear nodes after rendering them. But sometimes you might have to manully reset this. For example when you deleted nodes between registering and rendering.
Implemented in irr::scene::CSceneManager.
createMeshWriter()
virtual IMeshWriter* irr::scene::ISceneManager::createMeshWriter (EMESH_WRITER_TYPE type) pure virtual
Get a mesh writer implementation if available.
Note: You need to drop() the pointer after use again, see IReferenceCounted::drop() for details.
Implemented in irr::scene::CSceneManager.
createNewSceneManager()
virtual ISceneManager* irr::scene::ISceneManager::createNewSceneManager (bool cloneContent = false) pure virtual
Creates a new scene manager.
This can be used to easily draw and/or store two independent scenes at the same time. The mesh cache will be shared between all existing scene managers, which means if you load a mesh in the original scene manager using for example getMesh(), the mesh will be available in all other scene managers too, without loading. The original/main scene manager will still be there and accessible via IrrlichtDevice::getSceneManager(). If you need input event in this new scene manager, for example for FPS cameras, you'll need to forward input to this manually: Just implement an IEventReceiver and call yourNewSceneManager->postEventFromUser(), and return true so that the original scene manager doesn't get the event. Otherwise, all input will go to the main scene manager automatically. If you no longer need the new scene manager, you should call ISceneManager::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
createSkinnedMesh()
virtual ISkinnedMesh* irr::scene::ISceneManager::createSkinnedMesh () pure virtual
Get a skinned mesh, which is not available as header-only code.
Note: You need to drop() the pointer after use again, see IReferenceCounted::drop() for details.
Implemented in irr::scene::CSceneManager.
drawAll()
virtual void irr::scene::ISceneManager::drawAll () pure virtual
Draws all the scene nodes.
This can only be invoked between IVideoDriver::beginScene() and IVideoDriver::endScene(). Please note that the scene is not only drawn when calling this, but also animated by existing scene node animators, culling of scene nodes is done, etc.
Implemented in irr::scene::CSceneManager.
Referenced by GUIEngine::cloudPreProcess(), GUIScene::draw(), and Draw3D::run().
getActiveCamera()
virtual ICameraSceneNode* irr::scene::ISceneManager::getActiveCamera () const pure virtual
Get the current active camera.
Returns
The active camera is returned. Note that this can be NULL, if there was no camera created yet. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
Referenced by GUIScene::draw(), irr::scene::CSceneCollisionManager::getRayFromScreenCoordinates(), irr::scene::CCameraSceneNode::OnRegisterSceneNode(), irr::scene::CBillboardSceneNode::render(), and Sky::render().
getMesh()
virtual IAnimatedMesh* irr::scene::ISceneManager::getMesh (io::IReadFile * file) pure virtual
Get pointer to an animateable mesh. Loads the file if not loaded already.
If you want to remove a loaded mesh from the cache again, use removeMesh(). Currently there are the following mesh formats supported:
Format Description
3D Studio (.3ds) Loader for 3D-Studio files which lots of 3D packages are able to export. Only static meshes are currently supported by this importer.
3D World Studio (.smf) Loader for Leadwerks SMF mesh files, a simple mesh format containing static geometry for games. The proprietary .STF texture format is not supported yet. This loader was originally written by Joseph Ellis.
Bliz Basic B3D (.b3d) Loader for blitz basic files, developed by Mark Sibly. This is the ideal animated mesh format for game characters as it is both rigidly defined and widely supported by modeling and animation software. As this format supports skeletal animations, an ISkinnedMesh will be returned by this importer.
Cartography shop 4 (.csm) Cartography Shop is a modeling program for creating architecture and calculating lighting. Irrlicht can directly import .csm files thanks to the IrrCSM library created by Saurav Mohapatra which is now integrated directly in Irrlicht.
Delgine DeleD (.dmf) DeleD (delgine.com) is a 3D editor and level-editor combined into one and is specifically designed for 3D game-development. With this loader, it is possible to directly load all geometry is as well as textures and lightmaps from .dmf files. To set texture and material paths, see scene::DMF_USE_MATERIALS_DIRS. It is also possible to flip the alpha texture by setting scene::DMF_FLIP_ALPHA_TEXTURES to true and to set the material transparent reference value by setting scene::DMF_ALPHA_CHANNEL_REF to a float between 0 and
The loader is based on Salvatore Russo's .dmf loader, I just changed some parts of it. Thanks to Salvatore for his work and for allowing me to use his code in Irrlicht and put it under Irrlicht's license. For newer and more enhanced versions of the loader, take a look at delgine.com.
DirectX (.x) Platform independent importer (so not D3D-only) for .x files. Most 3D packages can export these natively and there are several tools for them available, e.g. the Maya exporter included in the DX SDK. .x files can include skeletal animations and Irrlicht is able to play and display them, users can manipulate the joints via the ISkinnedMesh interface. Currently, Irrlicht only supports uncompressed .x files.
Half-Life model (.mdl) This loader opens Half-life 1 models, it was contributed by Fabio Concas and adapted by Thomas Alten.
LightWave (.lwo) Native to NewTek's LightWave 3D, the LWO format is well known and supported by many exporters. This loader will import LWO2 models including lightmaps, bumpmaps and reflection textures.
Maya (.obj) Most 3D software can create .obj files which contain static geometry without material data. The material files .mtl are also supported. This importer for Irrlicht can load them directly.
Milkshape (.ms3d) .MS3D files contain models and sometimes skeletal animations from the Milkshape 3D modeling and animation software. Like the other skeletal mesh loaders, joints are exposed via the ISkinnedMesh animated mesh type.
My3D (.my3d) .my3D is a flexible 3D file format. The My3DTools contains plug-ins to export .my3D files from several 3D packages. With this built-in importer, Irrlicht can read and display those files directly. This loader was written by Zhuck Dimitry who also created the whole My3DTools package.
OCT (.oct) The oct file format contains 3D geometry and lightmaps and can be loaded directly by Irrlicht. OCT files
can be created by FSRad, Paul Nette's radiosity processor or exported from Blender using OCTTools which can be found in the exporters/OCTTools directory of the SDK. Thanks to Murphy McCauley for creating all this.
OGRE Meshes (.mesh) Ogre .mesh files contain 3D data for the OGRE 3D engine. Irrlicht can read and display them directly with this importer. To define materials for the mesh, copy a .material file named like the corresponding .mesh file where the .mesh file is. (For example ogrehead.material for ogrehead.mesh). Thanks to Christian Stehno who wrote and contributed this loader.
Pulsar LMTools (.lmts) LMTools is a set of tools (Windows & Linux) for creating lightmaps. Irrlicht can directly read .lmts files thanks to
the importer created by Jonas Petersen. Notes for
this version of the loader:
It does not recognize/support user data in the *.lmts files.
The TGAs generated by LMTools don't work in Irrlicht for some reason (the textures are upside down). Opening and resaving them in a graphics app will solve the problem.
Quake 3 levels (.bsp) Quake 3 is a popular game by IDSoftware, and .pk3 files contain .bsp files and textures/lightmaps describing huge prelighted levels. Irrlicht can read .pk3 and .bsp files directly and thus render Quake 3 levels directly. Written by Nikolaus Gebhardt enhanced by Dean P. Macri with the curved surfaces feature.
Quake 2 models (.md2) Quake 2 models are characters with morph target animation. Irrlicht can read, display and animate them directly with this importer.
Quake 3 models (.md3) Quake 3 models are characters with morph target animation, they contain mount points for weapons and body parts and are typically made of several sections which are manually joined together.
Stanford Triangle (.ply) Invented by Stanford University and known as the native format of the infamous "Stanford Bunny" model, this is a popular static mesh format used by 3D scanning hardware and software. This loader supports extremely large models in both ASCII and binary format, but only has rudimentary material support in the form of vertex colors and texture coordinates.
Stereolithography (.stl) The STL format is used for rapid prototyping and computer-aided manufacturing, thus has no support for materials.
To load and display a mesh quickly, just do this:
SceneManager->addAnimatedMeshSceneNode(
   SceneManager->getMesh("yourmesh.3ds"));
If you would like to implement and add your own file format loader to Irrlicht, see addExternalMeshLoader().
Parameters
file File handle of the mesh to load.
Returns
Null if failed, otherwise pointer to the mesh. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
getMeshCache()
virtual IMeshCache* irr::scene::ISceneManager::getMeshCache () pure virtual
Get interface to the mesh cache which is shared between all existing scene managers.
With this interface, it is possible to manually add new loaded meshes (if ISceneManager::getMesh() is not sufficient), to remove them and to iterate through already loaded meshes.
Implemented in irr::scene::CSceneManager.
getMeshLoader()
virtual IMeshLoader* irr::scene::ISceneManager::getMeshLoader (u32 index) const pure virtual
Retrieve the given mesh loader.
Parameters
index The index of the loader to retrieve. This parameter is an 0-based array index.
Returns
A pointer to the specified loader, 0 if the index is incorrect.
Implemented in irr::scene::CSceneManager.
getMeshManipulator()
virtual IMeshManipulator* irr::scene::ISceneManager::getMeshManipulator () pure virtual
Get pointer to the mesh manipulator.
Returns
Pointer to the mesh manipulator This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
Referenced by irr::gui::CGUITTFont::addTextSceneNode(), and irr::scene::COBJMeshFileLoader::createMesh().
getParameters()
virtual io::IAttributes* irr::scene::ISceneManager::getParameters () pure virtual
Get interface to the parameters set in this scene.
String parameters can be used by plugins and mesh loaders. See COLLADA_CREATE_SCENE_INSTANCES and DMF_USE_MATERIALS_DIRS
Implemented in irr::scene::CSceneManager.
Referenced by irr::scene::COBJMeshFileLoader::createMesh().
getRootSceneNode()
virtual ISceneNode* irr::scene::ISceneManager::getRootSceneNode () pure virtual
Gets the root scene node.
This is the scene node which is parent of all scene nodes. The root scene node is a special scene node which only exists to manage all scene nodes. It will not be rendered and cannot be removed from the scene.
Returns
Pointer to the root scene node. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
Referenced by irr::gui::CGUITTFont::addTextSceneNode(), and RenderShadowMapStep::run().
getSceneCollisionManager()
virtual ISceneCollisionManager* irr::scene::ISceneManager::getSceneCollisionManager () pure virtual
Get pointer to the scene collision manager.
Returns
Pointer to the collision manager This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
getSceneNodeFromId()
virtual ISceneNode* irr::scene::ISceneManager::getSceneNodeFromId (s32 id, ISceneNode * start = 0) pure virtual
Get the first scene node with the specified id.
Parameters
id The id to search for
start Scene node to start from. All children of this scene node are searched. If null is specified, the root scene node is taken.
Returns
Pointer to the first scene node with this id, and null if no scene node could be found. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
getSceneNodeFromName()
virtual ISceneNode* irr::scene::ISceneManager::getSceneNodeFromName (const c8 * name, ISceneNode * start = 0) pure virtual
Get the first scene node with the specified name.
Parameters
name The name to search for
start Scene node to start from. All children of this scene node are searched. If null is specified, the root scene node is taken.
Returns
Pointer to the first scene node with this id, and null if no scene node could be found. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
getSceneNodeFromType()
virtual ISceneNode* irr::scene::ISceneManager::getSceneNodeFromType (scene::ESCENE_NODE_TYPE type, ISceneNode * start = 0) pure virtual
Get the first scene node with the specified type.
Parameters
type The type to search for
start Scene node to start from. All children of this scene node are searched. If null is specified, the root scene node is taken.
Returns
Pointer to the first scene node with this type, and null if no scene node could be found. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
getSceneNodeRenderPass()
virtual E_SCENE_NODE_RENDER_PASS irr::scene::ISceneManager::getSceneNodeRenderPass () const pure virtual
Get current render pass.
All scene nodes are being rendered in a specific order. First lights, cameras, sky boxes, solid geometry, and then transparent stuff. During the rendering process, scene nodes may want to know what the scene manager is rendering currently, because for example they registered for rendering twice, once for transparent geometry and once for solid. When knowing what rendering pass currently is active they can render the correct part of their geometry.
Implemented in irr::scene::CSceneManager.
Referenced by irr::scene::CMeshSceneNode::render(), irr::scene::CAnimatedMeshSceneNode::render(), Clouds::render(), and ClientMap::render().
getSceneNodesFromType()
virtual void irr::scene::ISceneManager::getSceneNodesFromType (ESCENE_NODE_TYPE type, core::array< scene::ISceneNode * > & outNodes, ISceneNode * start = 0) pure virtual
Get scene nodes by type.
Parameters
type Type of scene node to find (ESNT_ANY will return all child nodes).
outNodes results will be added to this array (outNodes is not cleared).
start Scene node to start from. This node and all children of this scene node are checked (recursively, so also children of children, etc). If null is specified, the root scene node is taken as start-node.
Implemented in irr::scene::CSceneManager.
getVideoDriver()
virtual video::IVideoDriver* irr::scene::ISceneManager::getVideoDriver () pure virtual
Get the video driver.
Returns
Pointer to the video Driver. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::scene::CSceneManager.
Referenced by irr::scene::CCameraSceneNode::CCameraSceneNode(), irr::scene::CMeshSceneNode::OnRegisterSceneNode(), irr::scene::CAnimatedMeshSceneNode::OnRegisterSceneNode(), irr::scene::CMeshSceneNode::render(), irr::scene::CBillboardSceneNode::render(), irr::scene::CAnimatedMeshSceneNode::render(), Sky::render(), Clouds::render(), Particle::render(), ClientMap::render(), and irr::scene::CCameraSceneNode::render().
isCulled()
virtual bool irr::scene::ISceneManager::isCulled (const ISceneNode * node) const pure virtual
Check if node is culled in current view frustum.
Please note that depending on the used culling method this check can be rather coarse, or slow. A positive result is correct, though, i.e. if this method returns true the node is positively not visible. The node might still be invisible even if this method returns false.
Parameters
node The scene node which is checked for culling.
Returns
True if node is not visible in the current scene, else false.
Implemented in irr::scene::CSceneManager.
postEventFromUser()
virtual bool irr::scene::ISceneManager::postEventFromUser (const SEvent & event) pure virtual
Posts an input event to the environment.
Usually you do not have to use this method, it is used by the internal engine.
Implemented in irr::scene::CSceneManager.
Referenced by irr::CIrrDeviceStub::postEventFromUser().
registerNodeForRendering()
virtual u32 irr::scene::ISceneManager::registerNodeForRendering (ISceneNode * node, E_SCENE_NODE_RENDER_PASS pass = ESNRP_AUTOMATIC) pure virtual
Registers a node for rendering it at a specific time.
This method should only be used by SceneNodes when they get a ISceneNode::OnRegisterSceneNode() call.
Parameters
node Node to register for drawing. Usually scene nodes would set 'this' as parameter here because they want to be drawn.
pass Specifies when the node wants to be drawn in relation to the other nodes. For example, if the node is a shadow, it usually wants to be drawn after all other nodes and will use ESNRP_SHADOW for this. See scene::E_SCENE_NODE_RENDER_PASS for details. Note: This is not a bitfield. If you want to register a note for several render passes, then call this function once for each pass.
Returns
scene will be rendered (passed culling)
Implemented in irr::scene::CSceneManager.
Referenced by irr::scene::CEmptySceneNode::OnRegisterSceneNode(), irr::scene::CMeshSceneNode::OnRegisterSceneNode(), irr::scene::CBillboardSceneNode::OnRegisterSceneNode(), irr::scene::CAnimatedMeshSceneNode::OnRegisterSceneNode(), Sky::OnRegisterSceneNode(), Clouds::OnRegisterSceneNode(), Particle::OnRegisterSceneNode(), ClientMap::OnRegisterSceneNode(), and irr::scene::CCameraSceneNode::OnRegisterSceneNode().
setActiveCamera()
virtual void irr::scene::ISceneManager::setActiveCamera (ICameraSceneNode * camera) pure virtual
Sets the currently active camera.
The previous active camera will be deactivated.
Parameters
camera The new camera which should be active.
Implemented in irr::scene::CSceneManager.
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/ISceneManager.h