Three Cubes Game: irr::video::IMaterialRendererServices Class Reference
irr::video::IMaterialRendererServices Class Reference abstract
Interface providing some methods for changing advanced, internal states of a IVideoDriver.
#include <IMaterialRendererServices.h>
Public Member Functions
virtual ~IMaterialRendererServices ()
Destructor.
virtual void setBasicRenderStates (const SMaterial &material, const SMaterial &lastMaterial, bool resetAllRenderstates)=0
Can be called by an IMaterialRenderer to make its work easier.
virtual s32 getVertexShaderConstantID (const c8 *name)=0
Return an index constant for the vertex shader based on a name.
virtual bool setVertexShaderConstant (s32 index, const f32 *floats, int count)=0
Sets a constant for the vertex shader based on a name.
virtual bool setVertexShaderConstant (s32 index, const s32 *ints, int count)=0
Int interface for the above.
virtual bool setVertexShaderConstant (s32 index, const u32 *ints, int count)=0
Uint interface for the above.
virtual void setVertexShaderConstant (const f32 *data, s32 startRegister, s32 constantAmount=1)=0
Sets a vertex shader constant.
virtual s32 getPixelShaderConstantID (const c8 *name)=0
Return an index constant for the pixel shader based on a name.
virtual bool setPixelShaderConstant (s32 index, const f32 *floats, int count)=0
Sets a constant for the pixel shader based on a name.
virtual bool setPixelShaderConstant (s32 index, const s32 *ints, int count)=0
Int interface for the above.
virtual bool setPixelShaderConstant (s32 index, const u32 *ints, int count)=0
Uint interface for the above.
virtual void setPixelShaderConstant (const f32 *data, s32 startRegister, s32 constantAmount=1)=0
Sets a pixel shader constant.
_IRR_DEPRECATED_ bool setVertexShaderConstant (const c8 *name, const f32 *floats, int count)
_IRR_DEPRECATED_ bool setVertexShaderConstant (const c8 *name, const s32 *ints, int count)
_IRR_DEPRECATED_ bool setPixelShaderConstant (const c8 *name, const f32 *floats, int count)
_IRR_DEPRECATED_ bool setPixelShaderConstant (const c8 *name, const s32 *ints, int count)
virtual IVideoDriver * getVideoDriver ()=0
Get pointer to the IVideoDriver interface.
Detailed Description
Interface providing some methods for changing advanced, internal states of a IVideoDriver.
Definition at line 20 of file IMaterialRendererServices.h.
Member Function Documentation
getVideoDriver()
virtual IVideoDriver* irr::video::IMaterialRendererServices::getVideoDriver () pure virtual
Get pointer to the IVideoDriver interface.
Returns
Pointer to the IVideoDriver interface
Implemented in irr::video::COpenGL3DriverBase, and irr::video::COpenGL3MaterialRenderer.
Referenced by irr::video::COpenGL3MaterialBaseCB::OnSetConstants(), irr::video::COpenGL3MaterialSolidCB::OnSetConstants(), and irr::video::COpenGL3MaterialOneTextureBlendCB::OnSetConstants().
setBasicRenderStates()
virtual void irr::video::IMaterialRendererServices::setBasicRenderStates (const SMaterial & material, const SMaterial & lastMaterial, bool resetAllRenderstates) pure virtual
Can be called by an IMaterialRenderer to make its work easier.
Sets all basic renderstates if needed. Basic render states are diffuse, ambient, specular, and emissive color, specular power, bilinear and trilinear filtering, wireframe mode, grouraudshading, lighting, zbuffer, zwriteenable, backfaceculling and fog enabling.
Parameters
material The new material to be used.
lastMaterial The material used until now.
resetAllRenderstates Set to true if all renderstates should be set, regardless of their current state.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::COpenGL3MaterialRenderer.
setPixelShaderConstant() [1/4]
_IRR_DEPRECATED_ bool irr::video::IMaterialRendererServices::setPixelShaderConstant (const c8 * name, const f32 * floats, int count) inline
Deprecated:
. This method may be removed by Irrlicht 2.0
Definition at line 131 of file IMaterialRendererServices.h.
References getPixelShaderConstantID(), and setPixelShaderConstant().
setPixelShaderConstant() [2/4]
_IRR_DEPRECATED_ bool irr::video::IMaterialRendererServices::setPixelShaderConstant (const c8 * name, const s32 * ints, int count) inline
Deprecated:
. This method may be removed by Irrlicht 2.0
Definition at line 137 of file IMaterialRendererServices.h.
References getPixelShaderConstantID(), and setPixelShaderConstant().
setPixelShaderConstant() [3/4]
virtual void irr::video::IMaterialRendererServices::setPixelShaderConstant (const f32 * data, s32 startRegister, s32 constantAmount = 1) pure virtual
Sets a pixel shader constant.
Can be used if you created a shader using pixel/vertex shader assembler or ARB_fragment_program or ARB_vertex_program.
Parameters
data Data to be set in the constants
startRegister First register to be set.
constantAmount Amount of registers to be set. One register consists of 4 floats.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::COpenGL3MaterialRenderer.
setPixelShaderConstant() [4/4]
virtual bool irr::video::IMaterialRendererServices::setPixelShaderConstant (s32 index, const f32 * floats, int count) pure virtual
Sets a constant for the pixel shader based on a name.
This can be used if you used a high level shader language like GLSL or HLSL to create a shader. See setVertexShaderConstant() for an example on how to use this.
Parameters
index Index of the variable
floats Pointer to array of floats
count Amount of floats in array.
Returns
True if successful.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::COpenGL3MaterialRenderer.
Referenced by irr::video::COpenGL3MaterialBaseCB::OnSetConstants(), irr::video::COpenGL3MaterialSolidCB::OnSetConstants(), irr::video::COpenGL3MaterialOneTextureBlendCB::OnSetConstants(), and setPixelShaderConstant().
setVertexShaderConstant() [1/4]
_IRR_DEPRECATED_ bool irr::video::IMaterialRendererServices::setVertexShaderConstant (const c8 * name, const f32 * floats, int count) inline
Deprecated:
. This method may be removed by Irrlicht 2.0
Definition at line 119 of file IMaterialRendererServices.h.
References getVertexShaderConstantID(), and setVertexShaderConstant().
setVertexShaderConstant() [2/4]
_IRR_DEPRECATED_ bool irr::video::IMaterialRendererServices::setVertexShaderConstant (const c8 * name, const s32 * ints, int count) inline
Deprecated:
. This method may be removed by Irrlicht 2.0
Definition at line 125 of file IMaterialRendererServices.h.
References getVertexShaderConstantID(), and setVertexShaderConstant().
setVertexShaderConstant() [3/4]
virtual void irr::video::IMaterialRendererServices::setVertexShaderConstant (const f32 * data, s32 startRegister, s32 constantAmount = 1) pure virtual
Sets a vertex shader constant.
Can be used if you created a shader using pixel/vertex shader assembler or ARB_fragment_program or ARB_vertex_program.
Parameters
data Data to be set in the constants
startRegister First register to be set
constantAmount Amount of registers to be set. One register consists of 4 floats.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::COpenGL3MaterialRenderer.
setVertexShaderConstant() [4/4]
virtual bool irr::video::IMaterialRendererServices::setVertexShaderConstant (s32 index, const f32 * floats, int count) pure virtual
Sets a constant for the vertex shader based on a name.
This can be used if you used a high level shader language like GLSL or HLSL to create a shader. Example: If you created a shader which has variables named 'mWorldViewProj' (containing the WorldViewProjection matrix) and another one named 'fTime' containing one float, you can set them in your IShaderConstantSetCallBack derived class like this:
virtual void OnSetConstants(video::IMaterialRendererServices* services, s32 userData)
{
    video::IVideoDriver* driver = services->getVideoDriver();
    f32 time = (f32)os::Timer::getTime()/100000.0f;
    services->setVertexShaderConstant("fTime", &time, 1);
    core::matrix4 worldViewProj(driver->getTransform(video::ETS_PROJECTION));
    worldViewProj *= driver->getTransform(video::ETS_VIEW);
    worldViewProj *= driver->getTransform(video::ETS_WORLD);
    services->setVertexShaderConstant("mWorldViewProj", worldViewProj.M, 16);
}
Parameters
index Index of the variable
floats Pointer to array of floats
count Amount of floats in array.
Returns
True if successful.
Implemented in irr::video::COpenGL3DriverBase, and irr::video::COpenGL3MaterialRenderer.
Referenced by setVertexShaderConstant().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IMaterialRendererServices.h