Three Cubes Game: irr::scene::CSkinnedMesh Class Reference
irr::scene::CSkinnedMesh Class Reference
Public Member Functions
CSkinnedMesh ()
constructor
virtual ~CSkinnedMesh ()
destructor
u32 getFrameCount () const override
returns the amount of frames. If the amount is 1, it is a static (=non animated) mesh.
f32 getAnimationSpeed () const override
Gets the default animation speed of the animated mesh.
void setAnimationSpeed (f32 fps) override
Gets the frame count of the animated mesh.
IMesh * getMesh (s32 frame, s32 detailLevel=255, s32 startFrameLoop=-1, s32 endFrameLoop=-1) override
returns the animated mesh based on a detail level (which is ignored)
void animateMesh (f32 frame, f32 blend) override
void skinMesh () override
Preforms a software skin on this mesh based of joint positions.
u32 getMeshBufferCount () const override
returns amount of mesh buffers.
IMeshBuffer * getMeshBuffer (u32 nr) const override
returns pointer to a mesh buffer
IMeshBuffer * getMeshBuffer (const video::SMaterial &material) const override
Returns pointer to a mesh buffer which fits a material.
const core::aabbox3d< f32 > & getBoundingBox () const override
returns an axis aligned bounding box
void setBoundingBox (const core::aabbox3df &box) override
set user axis aligned bounding box
void setMaterialFlag (video::E_MATERIAL_FLAG flag, bool newvalue) override
sets a flag of all contained materials to a new value
void setHardwareMappingHint (E_HARDWARE_MAPPING newMappingHint, E_BUFFER_TYPE buffer=EBT_VERTEX_AND_INDEX) override
set the hardware mapping hint, for driver
void setDirty (E_BUFFER_TYPE buffer=EBT_VERTEX_AND_INDEX) override
flags the meshbuffer as changed, reloads hardware buffers
E_ANIMATED_MESH_TYPE getMeshType () const override
Returns the type of the animated mesh.
u32 getJointCount () const override
Gets joint count.
const c8 * getJointName (u32 number) const override
Gets the name of a joint.
s32 getJointNumber (const c8 *name) const override
Gets a joint number from its name.
bool useAnimationFrom (const ISkinnedMesh *mesh) override
uses animation from another mesh
void updateNormalsWhenAnimating (bool on) override
void setInterpolationMode (E_INTERPOLATION_MODE mode) override
Sets Interpolation Mode.
void convertMeshToTangents () override
Convertes the mesh to contain tangent information.
bool isStatic () override
Does the mesh have no animation.
bool setHardwareSkinning (bool on) override
(This feature is not implemented in irrlicht yet)
void refreshJointCache () override
Refreshes vertex data cached in joints such as positions and normals.
void resetAnimation () override
Moves the mesh into static position.
core::array< SSkinMeshBuffer * > & getMeshBuffers () override
exposed for loaders to add mesh buffers
core::array< SJoint * > & getAllJoints () override
alternative method for adding joints
const core::array< SJoint * > & getAllJoints () const override
alternative method for adding joints
void finalize () override
loaders should call this after populating the mesh
SSkinMeshBuffer * addMeshBuffer () override
Adds a new meshbuffer to the mesh, access it as last one.
SJoint * addJoint (SJoint *parent=0) override
Adds a new joint to the mesh, access it as last one.
SPositionKey * addPositionKey (SJoint *joint) override
Adds a new position key to the mesh, access it as last one.
SRotationKey * addRotationKey (SJoint *joint) override
Adds a new rotation key to the mesh, access it as last one.
SScaleKey * addScaleKey (SJoint *joint) override
Adds a new scale key to the mesh, access it as last one.
SWeight * addWeight (SJoint *joint) override
Adds a new weight to the mesh, access it as last one.
virtual void updateBoundingBox (void)
void recoverJointsFromMesh (core::array< IBoneSceneNode * > &jointChildSceneNodes)
Recovers the joints from the mesh.
void transferJointsToMesh (const core::array< IBoneSceneNode * > &jointChildSceneNodes)
Tranfers the joint data to the mesh.
void transferOnlyJointsHintsToMesh (const core::array< IBoneSceneNode * > &jointChildSceneNodes)
Tranfers the joint hints to the mesh.
void addJoints (core::array< IBoneSceneNode * > &jointChildSceneNodes, IAnimatedMeshSceneNode *node, ISceneManager *smgr)
Creates an array of joints from this mesh as children of node.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Member Functions
void checkForAnimation ()
void normalizeWeights ()
void buildAllLocalAnimatedMatrices ()
void buildAllGlobalAnimatedMatrices (SJoint *Joint=0, SJoint *ParentJoint=0)
void getFrameData (f32 frame, SJoint *Node, core::vector3df &position, s32 &positionHint, core::vector3df &scale, s32 &scaleHint, core::quaternion &rotation, s32 &rotationHint)
void calculateGlobalMatrices (SJoint *Joint, SJoint *ParentJoint)
void skinJoint (SJoint *Joint, SJoint *ParentJoint)
void calculateTangents (core::vector3df &normal, core::vector3df &tangent, core::vector3df &binormal, const core::vector3df &vt1, const core::vector3df &vt2, const core::vector3df &vt3, const core::vector2df &tc1, const core::vector2df &tc2, const core::vector2df &tc3)
Private Attributes
core::array< SSkinMeshBuffer * > * SkinningBuffers
core::array< SSkinMeshBuffer * > LocalBuffers
core::array< SJoint * > AllJoints
core::array< SJoint * > RootJoints
core::array< core::array< char > > Vertices_Moved
core::aabbox3d< f32 > BoundingBox
f32 EndFrame
f32 FramesPerSecond
f32 LastAnimatedFrame
bool SkinnedLastFrame
E_INTERPOLATION_MODE InterpolationMode:8
bool HasAnimation
bool PreparedForSkinning
bool AnimateNormals
bool HardwareSkinning
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Definition at line 25 of file CSkinnedMesh.h.
Member Function Documentation
animateMesh()
void irr::scene::CSkinnedMesh::animateMesh (f32 frame, f32 blend) override virtual
Animates this mesh's joints based on frame input blend: {0-old position, 1-New position}
Implements irr::scene::ISkinnedMesh.
Definition at line 165 of file CSkinnedMesh.cpp.
References irr::core::lerp(), irr::core::array< T >::size(), and irr::core::quaternion::slerp().
Referenced by irr::scene::CAnimatedMeshSceneNode::animateJoints(), getMesh(), and irr::scene::CAnimatedMeshSceneNode::getMeshForCurrentFrame().
finalize()
void irr::scene::CSkinnedMesh::finalize () override virtual
loaders should call this after populating the mesh
called by loader after populating with mesh and bone data
Implements irr::scene::ISkinnedMesh.
Definition at line 989 of file CSkinnedMesh.cpp.
References irr::core::aabbox3d< T >::addInternalBox(), irr::ELL_DEBUG, irr::core::array< T >::getLast(), irr::core::array< T >::push_back(), irr::core::array< T >::push_front(), irr::core::aabbox3d< T >::reset(), and irr::core::array< T >::size().
Referenced by irr::scene::CXMeshFileLoader::createMesh(), and irr::scene::CB3DMeshFileLoader::createMesh().
getAnimationSpeed()
f32 irr::scene::CSkinnedMesh::getAnimationSpeed () const override virtual
Gets the default animation speed of the animated mesh.
Returns
Amount of frames per second. If the amount is 0, it is a static, non animated mesh.
Implements irr::scene::IAnimatedMesh.
Definition at line 130 of file CSkinnedMesh.cpp.
getFrameCount()
u32 irr::scene::CSkinnedMesh::getFrameCount () const override virtual
returns the amount of frames. If the amount is 1, it is a static (=non animated) mesh.
returns the amount of frames in milliseconds. If the amount is 1, it is a static (=non animated) mesh.
Implements irr::scene::IAnimatedMesh.
Definition at line 122 of file CSkinnedMesh.cpp.
getMesh()
IMesh * irr::scene::CSkinnedMesh::getMesh (s32 frame, s32 detailLevel = 255, s32 startFrameLoop = -1, s32 endFrameLoop = -1) override virtual
returns the animated mesh based on a detail level (which is ignored)
returns the animated mesh based on a detail level. 0 is the lowest, 255 the highest detail. Note, that some Meshes will ignore the detail level.
Implements irr::scene::IAnimatedMesh.
Definition at line 146 of file CSkinnedMesh.cpp.
References animateMesh(), and skinMesh().
getMeshBuffer()
IMeshBuffer * irr::scene::CSkinnedMesh::getMeshBuffer (const video::SMaterial & material) const override virtual
Returns pointer to a mesh buffer which fits a material.
Parameters
material material to search for
Returns
Returns the pointer to the mesh buffer or NULL if there is no such mesh buffer.
Implements irr::scene::IMesh.
Definition at line 668 of file CSkinnedMesh.cpp.
setAnimationSpeed()
void irr::scene::CSkinnedMesh::setAnimationSpeed (f32 fps) override virtual
Gets the frame count of the animated mesh.
Parameters
fps Frames per second to play the animation with. If the amount is 0, it is not animated. The actual speed is set in the scene node the mesh is instantiated in.
Implements irr::scene::IAnimatedMesh.
Definition at line 139 of file CSkinnedMesh.cpp.
updateNormalsWhenAnimating()
void irr::scene::CSkinnedMesh::updateNormalsWhenAnimating (bool on) override virtual
Update Normals when Animating False= Don't (default) True = Update normals, slower
Update Normals when Animating False= Don't animate them, faster True= Update normals (default)
Implements irr::scene::ISkinnedMesh.
Definition at line 754 of file CSkinnedMesh.cpp.
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CSkinnedMesh.h
lib/irrlichtmt/source/Irrlicht/CSkinnedMesh.cpp