Three Cubes Game: irr::CTimer Class Reference
irr::CTimer Class Reference
Device independent implementation of the timer.
#include <CTimer.h>
Public Member Functions
CTimer (bool usePerformanceTimer=true)
u32 getRealTime () const override
Returns current real time in milliseconds of the system.
RealTimeDate getRealTimeAndDate () const override
Get current time and date in calendar form.
u32 getTime () const override
Returns current virtual time in milliseconds.
void setTime (u32 time) override
sets current virtual time
void stop () override
Stops the game timer.
void start () override
Starts the game timer.
void setSpeed (f32 speed=1.0f) override
Sets the speed of the timer.
f32 getSpeed () const override
Returns current speed of the timer.
bool isStopped () const override
Returns if game timer is currently stopped.
void tick () override
Advances the virtual time.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Additional Inherited Members
Public Types inherited from irr::ITimer
enum EWeekday {
EWD_SUNDAY =0, EWD_MONDAY, EWD_TUESDAY, EWD_WEDNESDAY,
EWD_THURSDAY, EWD_FRIDAY, EWD_SATURDAY
}
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Device independent implementation of the timer.
Definition at line 14 of file CTimer.h.
Member Function Documentation
getRealTime()
u32 irr::CTimer::getRealTime () const inline override virtual
Returns current real time in milliseconds of the system.
This value does not start with 0 when the application starts. For example in one implementation the value returned could be the amount of milliseconds which have elapsed since the system was started.
Implements irr::ITimer.
Definition at line 27 of file CTimer.h.
References irr::os::Timer::getRealTime().
getSpeed()
f32 irr::CTimer::getSpeed () const inline override virtual
Returns current speed of the timer.
The speed is the factor with which the time is running faster or slower then the real system time.
Implements irr::ITimer.
Definition at line 82 of file CTimer.h.
References irr::os::Timer::getSpeed().
getTime()
u32 irr::CTimer::getTime () const inline override virtual
Returns current virtual time in milliseconds.
This value starts with 0 and can be manipulated using setTime(), stopTimer(), startTimer(), etc. This value depends on the set speed of the timer if the timer is stopped, etc. If you need the system time, use getRealTime()
Implements irr::ITimer.
Definition at line 42 of file CTimer.h.
References irr::os::Timer::getTime().
setSpeed()
void irr::CTimer::setSpeed (f32 speed = 1.0f) inline override virtual
Sets the speed of the timer.
The speed is the factor with which the time is running faster or slower then the real system time.
Implements irr::ITimer.
Definition at line 74 of file CTimer.h.
References irr::os::Timer::setSpeed().
start()
void irr::CTimer::start () inline override virtual
Starts the game timer.
The timer is reference counted, which means everything which calls stopTimer() will also have to call startTimer(), otherwise the timer may not start/stop corretly again.
Implements irr::ITimer.
Definition at line 66 of file CTimer.h.
References irr::os::Timer::startTimer().
stop()
void irr::CTimer::stop () inline override virtual
Stops the game timer.
The timer is reference counted, which means everything which calls stopTimer() will also have to call startTimer(), otherwise the timer may not start/stop corretly again.
Implements irr::ITimer.
Definition at line 57 of file CTimer.h.
References irr::os::Timer::stopTimer().
tick()
void irr::CTimer::tick () inline override virtual
Advances the virtual time.
Makes the virtual timer update the time value based on the real time. This is called automatically when calling IrrlichtDevice::run(), but you can call it manually if you don't use this method.
Implements irr::ITimer.
Definition at line 98 of file CTimer.h.
References irr::os::Timer::tick().
The documentation for this class was generated from the following file:
lib/irrlichtmt/source/Irrlicht/CTimer.h