Three Cubes Game: irr::gui::IGUIEnvironment Class Reference
irr::gui::IGUIEnvironment Class Reference abstract
GUI Environment. Used as factory and manager of all other GUI elements.
#include <IGUIEnvironment.h>
Public Member Functions
virtual void drawAll (bool useScreenSize=true)=0
Draws all gui elements by traversing the GUI environment starting at the root node.
virtual bool setFocus (IGUIElement *element)=0
Sets the focus to an element.
virtual IGUIElement * getFocus () const =0
Returns the element which holds the focus.
virtual IGUIElement * getHovered () const =0
Returns the element which was last under the mouse cursor.
virtual bool removeFocus (IGUIElement *element)=0
Removes the focus from an element.
virtual bool hasFocus (const IGUIElement *element, bool checkSubElements=false) const =0
Returns whether the element has focus.
virtual video::IVideoDriver * getVideoDriver () const =0
Returns the current video driver.
virtual io::IFileSystem * getFileSystem () const =0
Returns the file system.
virtual IOSOperator * getOSOperator () const =0
returns a pointer to the OS operator
virtual void clear ()=0
Removes all elements from the environment.
virtual bool postEventFromUser (const SEvent &event)=0
Posts an input event to the environment.
virtual void setUserEventReceiver (IEventReceiver *evr)=0
This sets a new event receiver for gui events.
virtual IGUISkin * getSkin () const =0
Returns pointer to the current gui skin.
virtual void setSkin (IGUISkin *skin)=0
Sets a new GUI Skin.
virtual IGUISkin * createSkin (EGUI_SKIN_TYPE type)=0
Creates a new GUI Skin based on a template.
virtual IGUIImageList * createImageList (video::ITexture *texture, core::dimension2d< s32 > imageSize, bool useAlphaChannel)=0
Creates the image list from the given texture.
virtual IGUIFont * getFont (const io::path &filename)=0
Returns pointer to the font with the specified filename.
virtual IGUIFont * addFont (const io::path &name, IGUIFont *font)=0
Adds an externally loaded font to the font list.
virtual void removeFont (IGUIFont *font)=0
remove loaded font
virtual IGUIFont * getBuiltInFont () const =0
Returns the default built-in font.
virtual IGUISpriteBank * getSpriteBank (const io::path &filename)=0
Returns pointer to the sprite bank which was added with addEmptySpriteBank.
virtual IGUISpriteBank * addEmptySpriteBank (const io::path &name)=0
Adds an empty sprite bank to the manager.
virtual IGUIElement * getRootGUIElement ()=0
Returns the root gui element.
virtual IGUIButton * addButton (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1, const wchar_t *text=0, const wchar_t *tooltiptext=0)=0
Adds a button element.
virtual IGUIScrollBar * addScrollBar (bool horizontal, const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1)=0
Adds a scrollbar.
virtual IGUIImage * addImage (video::ITexture *image, core::position2d< s32 > pos, bool useAlphaChannel=true, IGUIElement *parent=0, s32 id=-1, const wchar_t *text=0)=0
Adds an image element.
virtual IGUIImage * addImage (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1, const wchar_t *text=0, bool useAlphaChannel=true)=0
Adds an image element.
virtual IGUICheckBox * addCheckBox (bool checked, const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1, const wchar_t *text=0)=0
Adds a checkbox element.
virtual IGUIListBox * addListBox (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1, bool drawBackground=false)=0
Adds a list box element.
virtual IGUIFileOpenDialog * addFileOpenDialog (const wchar_t *title=0, bool modal=true, IGUIElement *parent=0, s32 id=-1, bool restoreCWD=false, io::path::char_type *startDir=0)=0
Adds a file open dialog.
virtual IGUIStaticText * addStaticText (const wchar_t *text, const core::rect< s32 > &rectangle, bool border=false, bool wordWrap=true, IGUIElement *parent=0, s32 id=-1, bool fillBackground=false)=0
Adds a static text.
virtual IGUIEditBox * addEditBox (const wchar_t *text, const core::rect< s32 > &rectangle, bool border=true, IGUIElement *parent=0, s32 id=-1)=0
Adds an edit box.
virtual IGUITabControl * addTabControl (const core::rect< s32 > &rectangle, IGUIElement *parent=0, bool fillbackground=false, bool border=true, s32 id=-1)=0
Adds a tab control to the environment.
virtual IGUITab * addTab (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1)=0
Adds tab to the environment.
virtual IGUIComboBox * addComboBox (const core::rect< s32 > &rectangle, IGUIElement *parent=0, s32 id=-1)=0
Adds a combo box to the environment.
virtual IGUIElement * getNextElement (bool reverse=false, bool group=false)=0
Find the next element which would be selected when pressing the tab-key.
virtual void setFocusBehavior (u32 flags)=0
Set the way the gui will handle automatic focus changes.
virtual u32 getFocusBehavior () const =0
Get the way the gui does handle focus changes.
virtual void addToDeletionQueue (IGUIElement *element)=0
Adds a IGUIElement to deletion queue.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
GUI Environment. Used as factory and manager of all other GUI elements.
This element can create the following events of type EGUI_EVENT_TYPE (which are passed on to focused sub-elements):
EGET_ELEMENT_FOCUS_LOST
EGET_ELEMENT_FOCUSED
EGET_ELEMENT_LEFT
EGET_ELEMENT_HOVERED
Definition at line 59 of file IGUIEnvironment.h.
Member Function Documentation
addButton()
virtual IGUIButton* irr::gui::IGUIEnvironment::addButton (const core::rect< s32 > & rectangle, IGUIElement * parent = 0, s32 id = -1, const wchar_t * text = 0, const wchar_t * tooltiptext = 0) pure virtual
Adds a button element.
Parameters
rectangle Rectangle specifying the borders of the button.
parent Parent gui element of the button.
id Id with which the gui element can be identified.
text Text displayed on the button.
tooltiptext Text displayed in the tooltip.
Returns
Pointer to the created button. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIComboBox::CGUIComboBox(), irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog(), and irr::gui::CGUITabControl::CGUITabControl().
addCheckBox()
virtual IGUICheckBox* irr::gui::IGUIEnvironment::addCheckBox (bool checked, const core::rect< s32 > & rectangle, IGUIElement * parent = 0, s32 id = -1, const wchar_t * text = 0) pure virtual
Adds a checkbox element.
Parameters
checked Define the initial state of the check box.
rectangle Rectangle specifying the borders of the check box.
parent Parent gui element of the check box.
id Id to identify the gui element.
text Title text of the check box.
Returns
Pointer to the created check box. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
addComboBox()
virtual IGUIComboBox* irr::gui::IGUIEnvironment::addComboBox (const core::rect< s32 > & rectangle, IGUIElement * parent = 0, s32 id = -1) pure virtual
Adds a combo box to the environment.
Parameters
rectangle Rectangle specifying the borders of the combo box.
parent Parent item of the element, e.g. a window. Set it to 0 to place the combo box directly in the environment.
id An identifier for the combo box.
Returns
Pointer to the created combo box. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
addEditBox()
virtual IGUIEditBox* irr::gui::IGUIEnvironment::addEditBox (const wchar_t * text, const core::rect< s32 > & rectangle, bool border = true, IGUIElement * parent = 0, s32 id = -1) pure virtual
Adds an edit box.
Supports Unicode input from every keyboard around the world, scrolling, copying and pasting (exchanging data with the clipboard directly), maximum character amount, marking, and all shortcuts like ctrl+X, ctrl+V, ctrl+C, shift+Left, shift+Right, Home, End, and so on.
Parameters
text Text to be displayed. Can be altered after creation by setText().
rectangle Rectangle specifying the borders of the edit box.
border Set to true if the edit box should have a 3d border.
parent Parent item of the element, e.g. a window. Set it to 0 to place the edit box directly in the environment.
id The ID of the element.
Returns
Pointer to the created edit box. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog().
addEmptySpriteBank()
virtual IGUISpriteBank* irr::gui::IGUIEnvironment::addEmptySpriteBank (const io::path & name) pure virtual
Adds an empty sprite bank to the manager.
Parameters
name Name of the new sprite bank.
Returns
Pointer to the sprite bank. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIFont::CGUIFont().
addFileOpenDialog()
virtual IGUIFileOpenDialog* irr::gui::IGUIEnvironment::addFileOpenDialog (const wchar_t * title = 0, bool modal = true, IGUIElement * parent = 0, s32 id = -1, bool restoreCWD = false, io::path::char_type * startDir = 0) pure virtual
Adds a file open dialog.
Parameters
title Text to be displayed as the title of the dialog.
modal Defines if the dialog is modal. This means, that all other gui elements which were created before the message box cannot be used until this messagebox is removed.
parent Parent gui element of the dialog.
id Id to identify the gui element.
restoreCWD If set to true, the current working directory will be restored after the dialog is closed in some way. Otherwise the working directory will be the one that the file dialog was last showing.
startDir Optional path for which the file dialog will be opened.
Returns
Pointer to the created file open dialog. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
addFont()
virtual IGUIFont* irr::gui::IGUIEnvironment::addFont (const io::path & name, IGUIFont * font) pure virtual
Adds an externally loaded font to the font list.
This method allows to attach an already loaded font to the list of existing fonts. The font is grabbed if non-null and adding was successful.
Parameters
name Name the font should be stored as.
font Pointer to font to add.
Returns
Pointer to the font stored. This can differ from given parameter if the name previously existed.
Implemented in irr::gui::CGUIEnvironment.
addImage() [1/2]
virtual IGUIImage* irr::gui::IGUIEnvironment::addImage (const core::rect< s32 > & rectangle, IGUIElement * parent = 0, s32 id = -1, const wchar_t * text = 0, bool useAlphaChannel = true) pure virtual
Adds an image element.
Use IGUIImage::setImage later to set the image to be displayed.
Parameters
rectangle Rectangle specifying the borders of the image.
parent Parent gui element of the image.
id Id to identify the gui element.
text Title text of the image (not displayed).
useAlphaChannel Sets if the image should use the alpha channel of the texture to draw itself.
Returns
Pointer to the created image element. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
addImage() [2/2]
virtual IGUIImage* irr::gui::IGUIEnvironment::addImage (video::ITexture * image, core::position2d< s32 > pos, bool useAlphaChannel = true, IGUIElement * parent = 0, s32 id = -1, const wchar_t * text = 0) pure virtual
Adds an image element.
Parameters
image Image to be displayed.
pos Position of the image. The width and height of the image is taken from the image.
useAlphaChannel Sets if the image should use the alpha channel of the texture to draw itself.
parent Parent gui element of the image.
id Id to identify the gui element.
text Title text of the image (not displayed).
Returns
Pointer to the created image element. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
addListBox()
virtual IGUIListBox* irr::gui::IGUIEnvironment::addListBox (const core::rect< s32 > & rectangle, IGUIElement * parent = 0, s32 id = -1, bool drawBackground = false) pure virtual
Adds a list box element.
Parameters
rectangle Rectangle specifying the borders of the list box.
parent Parent gui element of the list box.
id Id to identify the gui element.
drawBackground Flag whether the background should be drawn.
Returns
Pointer to the created list box. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog().
addScrollBar()
virtual IGUIScrollBar* irr::gui::IGUIEnvironment::addScrollBar (bool horizontal, const core::rect< s32 > & rectangle, IGUIElement * parent = 0, s32 id = -1) pure virtual
Adds a scrollbar.
Parameters
horizontal Specifies if the scroll bar is drawn horizontal or vertical.
rectangle Rectangle specifying the borders of the scrollbar.
parent Parent gui element of the scroll bar.
id Id to identify the gui element.
Returns
Pointer to the created scrollbar. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
addStaticText()
virtual IGUIStaticText* irr::gui::IGUIEnvironment::addStaticText (const wchar_t * text, const core::rect< s32 > & rectangle, bool border = false, bool wordWrap = true, IGUIElement * parent = 0, s32 id = -1, bool fillBackground = false) pure virtual
Adds a static text.
Parameters
text Text to be displayed. Can be altered after creation by SetText().
rectangle Rectangle specifying the borders of the static text
border Set to true if the static text should have a 3d border.
wordWrap Enable if the text should wrap into multiple lines.
parent Parent item of the element, e.g. a window.
id The ID of the element.
fillBackground Enable if the background shall be filled. Defaults to false.
Returns
Pointer to the created static text. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIComboBox::CGUIComboBox(), and GUIKeyChangeMenu::OnEvent().
addTab()
virtual IGUITab* irr::gui::IGUIEnvironment::addTab (const core::rect< s32 > & rectangle, IGUIElement * parent = 0, s32 id = -1) pure virtual
Adds tab to the environment.
You can use this element to group other elements. This is not used for creating tabs on tab controls, please use IGUITabControl::addTab() for this instead.
Parameters
rectangle Rectangle specifying the borders of the tab.
parent Parent item of the element, e.g. a window. Set it to 0 to place the tab directly in the environment.
id An identifier for the tab.
Returns
Pointer to the created tab. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
addTabControl()
virtual IGUITabControl* irr::gui::IGUIEnvironment::addTabControl (const core::rect< s32 > & rectangle, IGUIElement * parent = 0, bool fillbackground = false, bool border = true, s32 id = -1) pure virtual
Adds a tab control to the environment.
Parameters
rectangle Rectangle specifying the borders of the tab control.
parent Parent item of the element, e.g. a window. Set it to 0 to place the tab control directly in the environment.
fillbackground Specifies if the background of the tab control should be drawn.
border Specifies if a flat 3d border should be drawn. This is usually not necessary unless you place the control directly into the environment without a window as parent.
id An identifier for the tab control.
Returns
Pointer to the created tab control element. Returns 0 if an error occurred. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
addToDeletionQueue()
virtual void irr::gui::IGUIEnvironment::addToDeletionQueue (IGUIElement * element) pure virtual
Adds a IGUIElement to deletion queue.
Queued elements will be removed at the end of each drawAll call. Or latest in the destructor of the GUIEnvironment. This can be used to allow an element removing itself safely in a function iterating over gui elements, like an overloaded IGUIElement::draw or IGUIElement::OnPostRender function. Note that in general just calling IGUIElement::remove() is enough. Unless you create your own GUI elements removing themselves you won't need it.
Parameters
element Element to remove
Implemented in irr::gui::CGUIEnvironment.
createImageList()
virtual IGUIImageList* irr::gui::IGUIEnvironment::createImageList (video::ITexture * texture, core::dimension2d< s32 > imageSize, bool useAlphaChannel) pure virtual
Creates the image list from the given texture.
Parameters
texture Texture to split into images
imageSize Dimension of each image
useAlphaChannel Flag whether alpha channel of the texture should be honored.
Returns
Pointer to the font. Returns 0 if the font could not be loaded. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
createSkin()
virtual IGUISkin* irr::gui::IGUIEnvironment::createSkin (EGUI_SKIN_TYPE type) pure virtual
Creates a new GUI Skin based on a template.
Use setSkin() to set the created skin.
Parameters
type The type of the new skin.
Returns
Pointer to the created skin. If you no longer need it, you should call IGUISkin::drop(). See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
drawAll()
virtual void irr::gui::IGUIEnvironment::drawAll (bool useScreenSize = true) pure virtual
Draws all gui elements by traversing the GUI environment starting at the root node.
Parameters
When true ensure the GuiEnvironment (aka the RootGUIElement) has the same size as the current driver screensize. Can be set to false to control that size yourself, p.E when not the full size should be used for UI.
Implemented in irr::gui::CGUIEnvironment.
Referenced by DrawHUD::run(), and GUIEngine::run().
getBuiltInFont()
virtual IGUIFont* irr::gui::IGUIEnvironment::getBuiltInFont () const pure virtual
Returns the default built-in font.
Returns
Pointer to the default built-in font. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUITabControl::CGUITabControl().
getFileSystem()
virtual io::IFileSystem* irr::gui::IGUIEnvironment::getFileSystem () const pure virtual
Returns the file system.
Returns
Pointer to the file system.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog().
getFocus()
virtual IGUIElement* irr::gui::IGUIEnvironment::getFocus () const pure virtual
Returns the element which holds the focus.
Returns
Pointer to the element with focus.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::CIrrDeviceStub::acceptsIME(), and irr::gui::CGUIComboBox::draw().
getFocusBehavior()
virtual u32 irr::gui::IGUIEnvironment::getFocusBehavior () const pure virtual
Get the way the gui does handle focus changes.
Returns
A bitmask which is a combination of EFOCUS_FLAG flags.
Implemented in irr::gui::CGUIEnvironment.
getFont()
virtual IGUIFont* irr::gui::IGUIEnvironment::getFont (const io::path & filename) pure virtual
Returns pointer to the font with the specified filename.
Loads the font if it was not loaded before.
Parameters
filename Filename of the Font.
Returns
Pointer to the font. Returns 0 if the font could not be loaded. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
getHovered()
virtual IGUIElement* irr::gui::IGUIEnvironment::getHovered () const pure virtual
Returns the element which was last under the mouse cursor.
NOTE: This information is updated after the user-eventreceiver received it's mouse-events. To find the hovered element while catching mouse events you have to use instead: IGUIEnvironment::getRootGUIElement()->getElementFromPoint(mousePos);
Returns
Pointer to the element under the mouse.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIButton::draw(), and GUIButton::isHovered().
getNextElement()
virtual IGUIElement* irr::gui::IGUIEnvironment::getNextElement (bool reverse = false, bool group = false) pure virtual
Find the next element which would be selected when pressing the tab-key.
If you set the focus for the result you can manually force focus-changes like they would happen otherwise by the tab-keys.
Parameters
reverse When true it will search backward (toward lower TabOrder numbers, like shift+tab)
group When true it will search for the next tab-group (like ctrl+tab)
Implemented in irr::gui::CGUIEnvironment.
getOSOperator()
virtual IOSOperator* irr::gui::IGUIEnvironment::getOSOperator () const pure virtual
returns a pointer to the OS operator
Returns
Pointer to the OS operator.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIEditBox::CGUIEditBox(), GUIEditBoxWithScrollBar::GUIEditBoxWithScrollBar(), and GUIChatConsole::OnEvent().
getRootGUIElement()
virtual IGUIElement* irr::gui::IGUIEnvironment::getRootGUIElement () pure virtual
Returns the root gui element.
This is the first gui element, the (direct or indirect) parent of all other gui elements. It is a valid IGUIElement, with dimensions the same size as the screen.
Returns
Pointer to the root element of the GUI. The returned pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
Referenced by GUIButtonItemImage::addButton(), GUIButtonImage::addButton(), GUIButton::addButton(), GUIScene::draw(), and GUIInventoryList::OnEvent().
getSkin()
virtual IGUISkin* irr::gui::IGUIEnvironment::getSkin () const pure virtual
Returns pointer to the current gui skin.
Returns
Pointer to the GUI skin.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIStaticText::breakText(), GUIEditBoxWithScrollBar::calculateFrameRect(), irr::gui::CGUIEditBox::calculateFrameRect(), irr::gui::CGUITabControl::calculateScrollIndexFromActive(), GUIEditBoxWithScrollBar::calculateScrollPos(), irr::gui::CGUIComboBox::CGUIComboBox(), irr::gui::CGUIFileOpenDialog::CGUIFileOpenDialog(), irr::gui::CGUIListBox::CGUIListBox(), irr::gui::CGUIStaticText::CGUIStaticText(), irr::gui::CGUITab::CGUITab(), irr::gui::CGUITabControl::CGUITabControl(), GUIEditBoxWithScrollBar::createVScrollBar(), GUIEditBoxWithScrollBar::draw(), irr::gui::CGUIStaticText::draw(), irr::gui::CGUITab::draw(), irr::gui::CGUIScrollBar::draw(), irr::gui::CGUIButton::draw(), GUIScrollBar::draw(), GUIButton::draw(), irr::gui::CGUIImage::draw(), irr::gui::CGUICheckBox::draw(), GUIScene::draw(), irr::gui::CGUIFileOpenDialog::draw(), irr::gui::CGUIListBox::draw(), irr::gui::CGUIComboBox::draw(), irr::gui::StaticText::draw(), irr::gui::CGUIEditBox::draw(), irr::gui::CGUITabControl::draw(), GUITable::draw(), irr::gui::CGUIFileOpenDialog::fillListBox(), irr::gui::CGUIButton::getActiveColor(), irr::gui::CGUIStaticText::getActiveColor(), irr::gui::CGUIStaticText::getActiveFont(), irr::gui::CGUIEditBox::getActiveFont(), irr::gui::CGUIButton::getActiveFont(), GUIButton::getActiveFont(), GUIEditBox::getActiveFont(), irr::gui::StaticText::getActiveFont(), irr::gui::StaticText::getBackgroundColor(), irr::gui::CGUIListBox::getItemDefaultColor(), irr::gui::CGUITabControl::getTabAt(), irr::gui::CGUITab::getTextColor(), GUIButton::GUIButton(), GUIHyperText::GUIHyperText(), irr::gui::CGUITabControl::needScrollControl(), irr::gui::CGUIScrollBar::refreshControls(), GUIButton::setFromStyle(), GUITable::setOverrideFont(), FontEngine::updateSkin(), and irr::gui::StaticText::updateText().
getSpriteBank()
virtual IGUISpriteBank* irr::gui::IGUIEnvironment::getSpriteBank (const io::path & filename) pure virtual
Returns pointer to the sprite bank which was added with addEmptySpriteBank.
TODO: This should load files in the future, but not implemented so far.
Parameters
filename Name of a spritebank added with addEmptySpriteBank
Returns
Pointer to the sprite bank. Returns 0 if it could not be loaded. This pointer should not be dropped. See IReferenceCounted::drop() for more information.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIFont::CGUIFont().
getVideoDriver()
virtual video::IVideoDriver* irr::gui::IGUIEnvironment::getVideoDriver () const pure virtual
Returns the current video driver.
Returns
Pointer to the video driver.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::gui::CGUIFont::CGUIFont(), irr::gui::CGUITTFont::CGUITTFont(), GUIAnimatedImage::draw(), irr::gui::CGUIStaticText::draw(), GUIBackgroundImage::draw(), irr::gui::CGUIButton::draw(), GUIItemImage::draw(), GUIBox::draw(), GUIButton::draw(), irr::gui::CGUIImage::draw(), irr::gui::CGUICheckBox::draw(), GUIModalMenu::draw(), GUIChatConsole::draw(), GUIInventoryList::draw(), irr::gui::StaticText::draw(), irr::gui::CGUITabControl::draw(), GUIButtonImage::setFromStyle(), and GUIButton::setFromStyle().
hasFocus()
virtual bool irr::gui::IGUIEnvironment::hasFocus (const IGUIElement * element, bool checkSubElements = false) const pure virtual
Returns whether the element has focus.
Parameters
element Pointer to the element which is tested.
checkSubElements When true and focus is on a sub-element of element then it will still count as focused and return true
Returns
True if the element has focus, else false.
Implemented in irr::gui::CGUIEnvironment.
Referenced by GUIEditBoxWithScrollBar::draw(), irr::gui::CGUIButton::draw(), GUIButton::draw(), irr::gui::CGUIListBox::draw(), irr::gui::CGUIEditBox::draw(), GUIButton::isFocused(), irr::gui::CGUIScrollBar::OnEvent(), GUIScrollBar::OnEvent(), and irr::gui::CGUIComboBox::OnEvent().
postEventFromUser()
virtual bool irr::gui::IGUIEnvironment::postEventFromUser (const SEvent & event) pure virtual
Posts an input event to the environment.
Usually you do not have to use this method, it is used by the engine internally.
Parameters
event The event to post.
Returns
True if succeeded, else false.
Implemented in irr::gui::CGUIEnvironment.
Referenced by GUIScrollContainer::OnEvent(), and irr::CIrrDeviceStub::postEventFromUser().
removeFocus()
virtual bool irr::gui::IGUIEnvironment::removeFocus (IGUIElement * element) pure virtual
Removes the focus from an element.
Causes a EGET_ELEMENT_FOCUS_LOST event. If the event is absorbed then the focus will not be changed.
Parameters
element Pointer to the element which shall lose the focus.
Returns
True on success, false on failure
Implemented in irr::gui::CGUIEnvironment.
setFocus()
virtual bool irr::gui::IGUIEnvironment::setFocus (IGUIElement * element) pure virtual
Sets the focus to an element.
Causes a EGET_ELEMENT_FOCUS_LOST event followed by a EGET_ELEMENT_FOCUSED event. If someone absorbed either of the events, then the focus will not be changed.
Parameters
element Pointer to the element which shall get the focus.
Returns
True on success, false on failure
Implemented in irr::gui::CGUIEnvironment.
Referenced by GUIButton::OnEvent(), GUIScrollContainer::OnEvent(), GUIScrollBar::OnEvent(), GUIVolumeChange::OnEvent(), and GUIKeyChangeMenu::OnEvent().
setFocusBehavior()
virtual void irr::gui::IGUIEnvironment::setFocusBehavior (u32 flags) pure virtual
Set the way the gui will handle automatic focus changes.
The default is (EFF_SET_ON_LMOUSE_DOWN | EFF_SET_ON_TAB). with the left mouse button. This does not affect the setFocus function itself - users can still call that whenever they want on any element.
Parameters
flags A bitmask which is a combination of EFOCUS_FLAG flags.
Implemented in irr::gui::CGUIEnvironment.
setSkin()
virtual void irr::gui::IGUIEnvironment::setSkin (IGUISkin * skin) pure virtual
Sets a new GUI Skin.
You can use this to change the appearance of the whole GUI Environment. You can set one of the built-in skins or implement your own class derived from IGUISkin and enable it using this method. To set for example the built-in Windows classic skin, use the following code:
gui::IGUISkin* newskin = environment->createSkin(gui::EGST_WINDOWS_CLASSIC);
environment->setSkin(newskin);
newskin->drop();
Parameters
skin New skin to use.
Implemented in irr::gui::CGUIEnvironment.
setUserEventReceiver()
virtual void irr::gui::IGUIEnvironment::setUserEventReceiver (IEventReceiver * evr) pure virtual
This sets a new event receiver for gui events.
Usually you do not have to use this method, it is used by the engine internally.
Parameters
evr Pointer to the new receiver.
Implemented in irr::gui::CGUIEnvironment.
Referenced by irr::CIrrDeviceStub::setEventReceiver().
The documentation for this class was generated from the following file:
lib/irrlichtmt/include/IGUIEnvironment.h