Three Cubes Game: irr::io::CFileSystem Class Reference
irr::io::CFileSystem Class Reference
#include <CFileSystem.h>
Public Member Functions
CFileSystem ()
constructor
virtual ~CFileSystem ()
destructor
IReadFile * createAndOpenFile (const io::path &filename) override
opens a file for read access
IReadFile * createMemoryReadFile (const void *memory, s32 len, const io::path &fileName, bool deleteMemoryWhenDropped=false) override
Creates an IReadFile interface for accessing memory like a file.
IReadFile * createLimitReadFile (const io::path &fileName, IReadFile *alreadyOpenedFile, long pos, long areaSize) override
Creates an IReadFile interface for accessing files inside files.
IWriteFile * createMemoryWriteFile (void *memory, s32 len, const io::path &fileName, bool deleteMemoryWhenDropped=false) override
Creates an IWriteFile interface for accessing memory like a file.
IWriteFile * createAndWriteFile (const io::path &filename, bool append=false) override
Opens a file for write access.
virtual bool addFileArchive (const io::path &filename, bool ignoreCase=true, bool ignorePaths=true, E_FILE_ARCHIVE_TYPE archiveType=EFAT_UNKNOWN, const core::stringc &password="", IFileArchive **retArchive=0) override
Adds an archive to the file system.
virtual bool addFileArchive (IReadFile *file, bool ignoreCase=true, bool ignorePaths=true, E_FILE_ARCHIVE_TYPE archiveType=EFAT_UNKNOWN, const core::stringc &password="", IFileArchive **retArchive=0) override
Adds an archive to the file system.
bool addFileArchive (IFileArchive *archive) override
Adds an archive to the file system.
bool moveFileArchive (u32 sourceIndex, s32 relative) override
move the hirarchy of the filesystem. moves sourceIndex relative up or down
void addArchiveLoader (IArchiveLoader *loader) override
Adds an external archive loader to the engine.
u32 getArchiveLoaderCount () const override
Returns the total number of archive loaders added.
IArchiveLoader * getArchiveLoader (u32 index) const override
Gets the archive loader by index.
u32 getFileArchiveCount () const override
gets the file archive count
IFileArchive * getFileArchive (u32 index) override
gets an archive
bool removeFileArchive (u32 index) override
removes an archive from the file system.
bool removeFileArchive (const io::path &filename) override
removes an archive from the file system.
bool removeFileArchive (const IFileArchive *archive) override
Removes an archive from the file system.
const io::path & getWorkingDirectory () override
Returns the string of the current working directory.
bool changeWorkingDirectoryTo (const io::path &newDirectory) override
Changes the current Working Directory to the given string.
io::path getAbsolutePath (const io::path &filename) const override
Converts a relative path to an absolute (unique) path, resolving symbolic links.
io::path getFileDir (const io::path &filename) const override
Returns the directory a file is located in.
io::path getFileBasename (const io::path &filename, bool keepExtension=true) const override
io::path & flattenFilename (io::path &directory, const io::path &root="/") const override
flatten a path and file name for example: "/you/me/../." becomes "/you"
path getRelativeFilename (const path &filename, const path &directory) const override
Get the relative filename, relative to the given directory.
EFileSystemType setFileListSystem (EFileSystemType listType) override
Sets the current file systen type.
IFileList * createFileList () override
Creates a list of files and directories in the current working directory.
IFileList * createEmptyFileList (const io::path &path, bool ignoreCase, bool ignorePaths) override
Creates an empty filelist.
bool existFile (const io::path &filename) const override
determines if a file exists and would be able to be opened.
Public Member Functions inherited from irr::io::IFileSystem
virtual _IRR_DEPRECATED_ bool addZipFileArchive (const c8 *filename, bool ignoreCase=true, bool ignorePaths=true)
Adds a zip archive to the file system.
virtual _IRR_DEPRECATED_ bool addFolderFileArchive (const c8 *filename, bool ignoreCase=true, bool ignorePaths=true)
Adds an unzipped archive (or basedirectory with subdirectories..) to the file system.
virtual _IRR_DEPRECATED_ bool addPakFileArchive (const c8 *filename, bool ignoreCase=true, bool ignorePaths=true)
Adds a pak archive to the file system.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Private Attributes
EFileSystemType FileSystemType
Currently used FileSystemType.
io::path WorkingDirectory [2]
WorkingDirectory for Native and Virtual filesystems.
core::array< IArchiveLoader * > ArchiveLoader
currently attached ArchiveLoaders
core::array< IFileArchive * > FileArchives
currently attached Archives
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
FileSystem which uses normal files and one zipfile
Definition at line 21 of file CFileSystem.h.
Constructor & Destructor Documentation
CFileSystem()
irr::io::CFileSystem::CFileSystem ()
constructor
reset current working directory
Definition at line 46 of file CFileSystem.cpp.
References ArchiveLoader, getWorkingDirectory(), irr::IReferenceCounted::setDebugName(), and setFileListSystem().
Member Function Documentation
changeWorkingDirectoryTo()
bool irr::io::CFileSystem::changeWorkingDirectoryTo (const io::path & newDirectory) override virtual
Changes the current Working Directory to the given string.
Changes the current Working Directory to the string given. The string is operating system dependent. Under Windows it will look like this: "drive:\directory\sudirectory\"
Implements irr::io::IFileSystem.
Definition at line 497 of file CFileSystem.cpp.
References irr::core::string< T >::c_str(), FileSystemType, flattenFilename(), and WorkingDirectory.
createFileList()
IFileList * irr::io::CFileSystem::createFileList () override virtual
Creates a list of files and directories in the current working directory.
Creates a list of files and directories in the current working directory and returns it.
Construct from native filesystem
Windows version
Linux version
create file list for the virtual filesystem
add relative navigation
PWD
parent
merge archives
Implements irr::io::IFileSystem.
Definition at line 731 of file CFileSystem.cpp.
References irr::io::CFileList::addItem(), irr::core::string< T >::append(), irr::core::string< T >::c_str(), irr::core::string< T >::empty(), FileArchives, FileSystemType, getWorkingDirectory(), irr::core::isInSameDirectory(), irr::core::string< T >::lastChar(), irr::core::string< T >::replace(), irr::core::string< T >::size(), and irr::io::CFileList::sort().
createLimitReadFile()
IReadFile * irr::io::CFileSystem::createLimitReadFile (const io::path & fileName, IReadFile * alreadyOpenedFile, long pos, long areaSize) override virtual
Creates an IReadFile interface for accessing files inside files.
Creates an IReadFile interface for reading files inside files.
Implements irr::io::IFileSystem.
Definition at line 112 of file CFileSystem.cpp.
createMemoryReadFile()
IReadFile * irr::io::CFileSystem::createMemoryReadFile (const void * memory, s32 len, const io::path & fileName, bool deleteMemoryWhenDropped = false) override virtual
Creates an IReadFile interface for accessing memory like a file.
Creates an IReadFile interface for treating memory like a file.
Implements irr::io::IFileSystem.
Definition at line 101 of file CFileSystem.cpp.
createMemoryWriteFile()
IWriteFile * irr::io::CFileSystem::createMemoryWriteFile (void * memory, s32 len, const io::path & fileName, bool deleteMemoryWhenDropped = false) override virtual
Creates an IWriteFile interface for accessing memory like a file.
Creates an IReadFile interface for treating memory like a file.
Implements irr::io::IFileSystem.
Definition at line 123 of file CFileSystem.cpp.
getFileArchiveCount()
u32 irr::io::CFileSystem::getFileArchiveCount () const override virtual
gets the file archive count
gets an archive
Implements irr::io::IFileSystem.
Definition at line 438 of file CFileSystem.cpp.
References FileArchives.
Referenced by getFileArchive().
getFileBasename()
io::path irr::io::CFileSystem::getFileBasename (const io::path & filename, bool keepExtension = true) const override virtual
Returns the base part of a filename, i.e. the name without the directory part. If no directory is prefixed, the full name is returned.
Parameters
filename The file to get the basename from
returns the base part of a filename, i.e. all except for the directory part. If no directory path is prefixed, the full name is returned.
Implements irr::io::IFileSystem.
Definition at line 579 of file CFileSystem.cpp.
References irr::core::string< T >::findLast(), irr::core::max_(), irr::core::string< T >::size(), and irr::core::string< T >::subString().
getFileDir()
io::path irr::io::CFileSystem::getFileDir (const io::path & filename) const override virtual
Returns the directory a file is located in.
Parameters
filename The file to get the directory from
returns the directory part of a filename, i.e. all until the first slash or backslash, excluding it. If no directory path is prefixed, a '.' is returned.
Implements irr::io::IFileSystem.
Definition at line 563 of file CFileSystem.cpp.
References irr::core::string< T >::findLast(), irr::core::string< T >::size(), and irr::core::string< T >::subString().
The documentation for this class was generated from the following files:
lib/irrlichtmt/source/Irrlicht/CFileSystem.h
lib/irrlichtmt/source/Irrlicht/CFileSystem.cpp