Three Cubes Game: ConfigureOverrideMaterialTarget Class Reference
ConfigureOverrideMaterialTarget Class Reference
#include <anaglyph.h>
Public Member Functions
ConfigureOverrideMaterialTarget (RenderTarget *upstream, bool enable)
virtual void activate (PipelineContext &context) override
Public Member Functions inherited from RenderTarget
virtual void reset (PipelineContext &context) override
Private Attributes
RenderTarget * upstream
bool enable
Additional Inherited Members
Protected Attributes inherited from RenderTarget
bool m_clear {true}
Detailed Description
Enables or disables override material when activated
Definition at line 58 of file anaglyph.h.
Member Function Documentation
activate()
void ConfigureOverrideMaterialTarget::activate (PipelineContext & context) override virtual
Activate the render target and configure OpenGL state for the output. This is usually done by
See also
RenderStep implementations.
Reimplemented from RenderTarget.
Definition at line 59 of file anaglyph.cpp.
References RenderTarget::activate(), irr::video::SOverrideMaterial::Enabled, irr::video::IVideoDriver::getOverrideMaterial(), and irr::IrrlichtDevice::getVideoDriver().
The documentation for this class was generated from the following files:
src/client/render/anaglyph.h
src/client/render/anaglyph.cpp