Three Cubes Game: GUIEngine Class Reference
GUIEngine Class Reference
#include <guiEngine.h>
Classes
struct clouddata
Public Member Functions
GUIEngine (JoystickController *joystick, gui::IGUIElement *parent, RenderingEngine *rendering_engine, IMenuManager *menumgr, MainMenuData *data, bool &kill)
virtual ~GUIEngine ()
MainMenuScripting * getScriptIface ()
std::string getScriptDir ()
Private Member Functions
bool loadMainMenuScript ()
void run ()
void updateTopLeftTextSize ()
void setFormspecPrepend (const std::string &fs)
void drawBackground (video::IVideoDriver *driver)
void drawOverlay (video::IVideoDriver *driver)
void drawHeader (video::IVideoDriver *driver)
void drawFooter (video::IVideoDriver *driver)
bool setTexture (texture_layer layer, const std::string &texturepath, bool tile_image, unsigned int minsize)
void setTopleftText (const std::string &text)
void cloudInit ()
void cloudPreProcess ()
void cloudPostProcess (u32 frametime_min, IrrlichtDevice *device)
s32 playSound (const SimpleSoundSpec &spec)
void stopSound (s32 handle)
Static Private Member Functions
static bool downloadFile (const std::string &url, const std::string &target)
Private Attributes
RenderingEngine * m_rendering_engine = nullptr
gui::IGUIElement * m_parent = nullptr
IMenuManager * m_menumanager = nullptr
scene::ISceneManager * m_smgr = nullptr
MainMenuData * m_data = nullptr
std::unique_ptr< ISimpleTextureSource > m_texture_source
MenuMusicFetcher m_soundfetcher {}
std::unique_ptr< ISoundManager > m_sound_manager
FormspecFormSource * m_formspecgui = nullptr
TextDestGuiEngine * m_buttonhandler = nullptr
irr_ptr< GUIFormSpecMenu > m_menu
bool & m_kill
bool m_startgame = false
std::unique_ptr< MainMenuScripting > m_script
std::string m_scriptdir = ""
image_definition m_textures [TEX_LAYER_MAX]
irr::gui::IGUIStaticText * m_irr_toplefttext = nullptr
EnrichedString m_toplefttext
bool m_clouds_enabled = true
clouddata m_cloud
Friends
class ModApiMainMenu
class ModApiSound
Detailed Description
implementation of main menu based uppon formspecs
Definition at line 138 of file guiEngine.h.
Constructor & Destructor Documentation
GUIEngine()
GUIEngine::GUIEngine (JoystickController * joystick, gui::IGUIElement * parent, RenderingEngine * rendering_engine, IMenuManager * menumgr, MainMenuData * data, bool & kill)
default constructor
Parameters
dev device to draw at
parent parent gui element
menumgr manager to add menus to
smgr scene manager to add scene elements to
data struct to transfer data to main game handling
GUIEngine
Definition at line 128 of file guiEngine.cpp.
References FontEngine::getTextHeight(), loadMainMenuScript(), m_buttonhandler, m_data, m_formspecgui, m_irr_toplefttext, m_menu, m_menumanager, m_parent, m_script, m_sound_manager, m_soundfetcher, m_texture_source, m_textures, m_toplefttext, irr_ptr< ReferenceCounted, class >::reset(), and run().
~GUIEngine()
GUIEngine::~GUIEngine () virtual
default destructor
Definition at line 319 of file guiEngine.cpp.
References GUIEngine::clouddata::clouds, m_cloud, m_irr_toplefttext, m_script, m_sound_manager, m_texture_source, m_textures, irr::video::IVideoDriver::removeTexture(), irr_ptr< ReferenceCounted, class >::reset(), and irr::gui::IGUIElement::setText().
Member Function Documentation
cloudInit()
void GUIEngine::cloudInit () private
initialize cloud subsystem
Definition at line 340 of file guiEngine.cpp.
References irr::scene::ISceneManager::addCameraSceneNode(), GUIEngine::clouddata::camera, GUIEngine::clouddata::clouds, GUIEngine::clouddata::lasttime, m_cloud, m_smgr, and irr::scene::ICameraSceneNode::setFarValue().
Referenced by run().
cloudPostProcess()
void GUIEngine::cloudPostProcess (u32 frametime_min, IrrlichtDevice * device) private
do postprocessing for cloud subsystem
Definition at line 371 of file guiEngine.cpp.
References GUIEngine::clouddata::lasttime, m_cloud, and irr::IrrlichtDevice::sleep().
Referenced by run().
cloudPreProcess()
void GUIEngine::cloudPreProcess () private
do preprocessing for cloud subsystem
Definition at line 354 of file guiEngine.cpp.
References GUIEngine::clouddata::clouds, irr::scene::ISceneManager::drawAll(), GUIEngine::clouddata::dtime, GUIEngine::clouddata::lasttime, m_cloud, m_smgr, and Clouds::render().
Referenced by run().
downloadFile()
bool GUIEngine::downloadFile (const std::string & url, const std::string & target) static private
download a file using curl
Parameters
url url to download
target file to store to
Definition at line 564 of file guiEngine.cpp.
drawBackground()
void GUIEngine::drawBackground (video::IVideoDriver * driver) private
draw background layer
Parameters
driver to use for drawing
Definition at line 400 of file guiEngine.cpp.
References irr::video::IVideoDriver::draw2DRectangle(), irr::video::ITexture::getOriginalSize(), irr::video::IVideoDriver::getScreenSize(), m_textures, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
Referenced by run().
drawFooter()
void GUIEngine::drawFooter (video::IVideoDriver * driver) private
draw footer layer
Parameters
driver to use for drawing
Definition at line 506 of file guiEngine.cpp.
References irr::video::ITexture::getOriginalSize(), irr::video::IVideoDriver::getScreenSize(), irr::core::dimension2d< T >::Height, m_textures, irr::core::dimension2d< T >::Width, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
Referenced by run().
drawHeader()
void GUIEngine::drawHeader (video::IVideoDriver * driver) private
draw header layer
Parameters
driver to use for drawing
Definition at line 474 of file guiEngine.cpp.
References irr::video::ITexture::getOriginalSize(), irr::video::IVideoDriver::getScreenSize(), irr::core::dimension2d< T >::Height, m_textures, irr::core::dimension2d< T >::Width, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
Referenced by run().
drawOverlay()
void GUIEngine::drawOverlay (video::IVideoDriver * driver) private
draw overlay layer
Parameters
driver to use for drawing
Definition at line 455 of file guiEngine.cpp.
References irr::video::ITexture::getOriginalSize(), irr::video::IVideoDriver::getScreenSize(), m_textures, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
Referenced by run().
getScriptDir()
std::string GUIEngine::getScriptDir () inline
return dir of current menuscript
Definition at line 173 of file guiEngine.h.
References m_scriptdir.
getScriptIface()
MainMenuScripting* GUIEngine::getScriptIface () inline
return MainMenuScripting interface
Definition at line 165 of file guiEngine.h.
References m_script.
Referenced by TextDestGuiEngine::gotText().
loadMainMenuScript()
bool GUIEngine::loadMainMenuScript () private
find and run the main menu script
Definition at line 218 of file guiEngine.cpp.
References m_script, and m_scriptdir.
Referenced by GUIEngine().
playSound()
s32 GUIEngine::playSound (const SimpleSoundSpec & spec) private
start playing a sound and return handle
Definition at line 613 of file guiEngine.cpp.
References m_sound_manager.
run()
void GUIEngine::run () private
run main menu loop
Definition at line 242 of file guiEngine.cpp.
References irr::video::IVideoDriver::beginScene(), cloudInit(), cloudPostProcess(), cloudPreProcess(), irr::gui::IGUIEnvironment::drawAll(), drawBackground(), drawFooter(), drawHeader(), drawOverlay(), irr::video::IVideoDriver::endScene(), irr::video::IVideoDriver::getFog(), FontEngine::getTextHeight(), irr::IrrlichtDevice::isWindowFocused(), m_clouds_enabled, m_kill, m_menu, m_script, m_startgame, irr::video::IVideoDriver::setFog(), and updateTopLeftTextSize().
Referenced by GUIEngine().
setTexture()
bool GUIEngine::setTexture (texture_layer layer, const std::string & texturepath, bool tile_image, unsigned int minsize) private
load a texture for a specified layer
Parameters
layer draw layer to specify texture
texturepath full path of texture to load
Definition at line 538 of file guiEngine.cpp.
References irr::video::IVideoDriver::getTexture(), m_textures, and irr::video::IVideoDriver::removeTexture().
setTopleftText()
void GUIEngine::setTopleftText (const std::string & text) private
specify text to appear as top left string
Parameters
text to set
Definition at line 593 of file guiEngine.cpp.
References m_toplefttext, and updateTopLeftTextSize().
stopSound()
void GUIEngine::stopSound (s32 handle) private
stop playing a sound started with playSound()
Definition at line 620 of file guiEngine.cpp.
References m_sound_manager.
updateTopLeftTextSize()
void GUIEngine::updateTopLeftTextSize () private
update size of topleftext element
Definition at line 601 of file guiEngine.cpp.
References FontEngine::getTextHeight(), m_irr_toplefttext, m_toplefttext, and irr::gui::IGUIElement::remove().
Referenced by run(), and setTopleftText().
Friends And Related Function Documentation
ModApiMainMenu
friend class ModApiMainMenu friend
grant ModApiMainMenu access to private members
Definition at line 140 of file guiEngine.h.
Member Data Documentation
m_buttonhandler
TextDestGuiEngine* GUIEngine::m_buttonhandler = nullptr private
formspec input receiver
Definition at line 208 of file guiEngine.h.
Referenced by GUIEngine().
m_cloud
clouddata GUIEngine::m_cloud private
data used to draw clouds
Definition at line 298 of file guiEngine.h.
Referenced by cloudInit(), cloudPostProcess(), cloudPreProcess(), and ~GUIEngine().
m_clouds_enabled
bool GUIEngine::m_clouds_enabled = true private
is drawing of clouds enabled atm
Definition at line 296 of file guiEngine.h.
Referenced by run().
m_data
MainMenuData* GUIEngine::m_data = nullptr private
pointer to data beeing transfered back to main game handling
Definition at line 197 of file guiEngine.h.
Referenced by GUIEngine().
m_formspecgui
FormspecFormSource* GUIEngine::m_formspecgui = nullptr private
representation of form source to be used in mainmenu formspec
Definition at line 206 of file guiEngine.h.
Referenced by GUIEngine().
m_irr_toplefttext
irr::gui::IGUIStaticText* GUIEngine::m_irr_toplefttext = nullptr private
pointer to gui element shown at topleft corner
Definition at line 272 of file guiEngine.h.
Referenced by GUIEngine(), updateTopLeftTextSize(), and ~GUIEngine().
m_kill
bool& GUIEngine::m_kill private
reference to kill variable managed by SIGINT handler
Definition at line 213 of file guiEngine.h.
Referenced by run().
m_menu
irr_ptr<GUIFormSpecMenu> GUIEngine::m_menu private
the formspec menu
Definition at line 210 of file guiEngine.h.
Referenced by GUIEngine(), and run().
m_menumanager
IMenuManager* GUIEngine::m_menumanager = nullptr private
manager to add menus to
Definition at line 193 of file guiEngine.h.
Referenced by GUIEngine().
m_parent
gui::IGUIElement* GUIEngine::m_parent = nullptr private
parent gui element
Definition at line 191 of file guiEngine.h.
Referenced by GUIEngine().
m_script
std::unique_ptr<MainMenuScripting> GUIEngine::m_script private
scripting interface
Definition at line 219 of file guiEngine.h.
Referenced by getScriptIface(), GUIEngine(), loadMainMenuScript(), run(), and ~GUIEngine().
m_scriptdir
std::string GUIEngine::m_scriptdir = "" private
script basefolder
Definition at line 222 of file guiEngine.h.
Referenced by getScriptDir(), and loadMainMenuScript().
m_smgr
scene::ISceneManager* GUIEngine::m_smgr = nullptr private
scene manager to add scene elements to
Definition at line 195 of file guiEngine.h.
Referenced by cloudInit(), and cloudPreProcess().
m_sound_manager
std::unique_ptr<ISoundManager> GUIEngine::m_sound_manager private
sound manager
Definition at line 203 of file guiEngine.h.
Referenced by GUIEngine(), playSound(), stopSound(), and ~GUIEngine().
m_soundfetcher
MenuMusicFetcher GUIEngine::m_soundfetcher {} private
sound fetcher, used by sound manager
Definition at line 201 of file guiEngine.h.
Referenced by GUIEngine().
m_startgame
bool GUIEngine::m_startgame = false private
variable used to abort menu and return back to main game handling
Definition at line 216 of file guiEngine.h.
Referenced by run().
m_texture_source
std::unique_ptr<ISimpleTextureSource> GUIEngine::m_texture_source private
texture source
Definition at line 199 of file guiEngine.h.
Referenced by GUIEngine(), and ~GUIEngine().
m_textures
image_definition GUIEngine::m_textures[TEX_LAYER_MAX] private
array containing pointers to current specified texture layers
Definition at line 263 of file guiEngine.h.
Referenced by drawBackground(), drawFooter(), drawHeader(), drawOverlay(), GUIEngine(), setTexture(), and ~GUIEngine().
m_toplefttext
EnrichedString GUIEngine::m_toplefttext private
and text that is in it
Definition at line 274 of file guiEngine.h.
Referenced by GUIEngine(), setTopleftText(), and updateTopLeftTextSize().
The documentation for this class was generated from the following files:
src/gui/guiEngine.h
src/gui/guiEngine.cpp