Three Cubes Game: ClearDepthBufferTarget Class Reference
ClearDepthBufferTarget Class Reference
#include <anaglyph.h>
Public Member Functions
ClearDepthBufferTarget (RenderTarget *target)
ClearDepthBufferTarget.
void reset (PipelineContext &context) override
void activate (PipelineContext &context) override
Private Attributes
RenderTarget * target
Additional Inherited Members
Protected Attributes inherited from RenderTarget
bool m_clear {true}
Detailed Description
Resets depth buffer of the current render target
Definition at line 42 of file anaglyph.h.
Member Function Documentation
activate()
void ClearDepthBufferTarget::activate (PipelineContext & context) override virtual
Activate the render target and configure OpenGL state for the output. This is usually done by
See also
RenderStep implementations.
Reimplemented from RenderTarget.
Definition at line 48 of file anaglyph.cpp.
References RenderTarget::activate(), irr::video::IVideoDriver::clearBuffers(), and irr::IrrlichtDevice::getVideoDriver().
reset()
void ClearDepthBufferTarget::reset (PipelineContext & context) inline override virtual
Resets the state of the object for the next pipeline iteration
Reimplemented from RenderTarget.
Definition at line 47 of file anaglyph.h.
The documentation for this class was generated from the following files:
src/client/render/anaglyph.h
src/client/render/anaglyph.cpp