Three Cubes Game: RenderShadowMapStep Class Reference
RenderShadowMapStep Class Reference
Public Member Functions
virtual void run (PipelineContext &context) override
Public Member Functions inherited from TrivialRenderStep
virtual void setRenderSource (RenderSource *source) override
virtual void setRenderTarget (RenderTarget *target) override
virtual void reset (PipelineContext &) override
Detailed Description
Definition at line 76 of file plain.h.
Member Function Documentation
run()
void RenderShadowMapStep::run (PipelineContext & context) override virtual
Runs the step. This method is invoked by the pipeline.
Implements RenderStep.
Definition at line 88 of file plain.cpp.
References irr::scene::ISceneManager::getRootSceneNode(), irr::IrrlichtDevice::getSceneManager(), irr::ITimer::getTime(), irr::IrrlichtDevice::getTimer(), and irr::scene::ISceneNode::OnAnimate().
The documentation for this class was generated from the following files:
src/client/render/plain.h
src/client/render/plain.cpp