Three Cubes Game: ModConfiguration Class Reference
ModConfiguration Class Reference
#include <mod_configuration.h>
Public Member Functions
bool isConsistent () const
const std::vector< ModSpec > & getUnsatisfiedMods () const
const std::vector< ModSpec > & getMods () const
std::string getUnsatisfiedModsError () const
void addModsInPath (const std::string &path, const std::string &virtual_path)
void addMods (const std::vector< ModSpec > &new_mods)
void addGameMods (const SubgameSpec &gamespec)
void addModsFromConfig (const std::string &settings_path, const std::unordered_map< std::string, std::string > &modPaths)
void checkConflictsAndDeps ()
Private Member Functions
void resolveDependencies ()
Private Attributes
std::vector< ModSpec > m_sorted_mods
std::vector< ModSpec > m_unsatisfied_mods
std::unordered_set< std::string > m_name_conflicts
Detailed Description
ModConfiguration is a subset of installed mods. This class is used to resolve dependencies and return a sorted list of mods.
This class should not be extended from, but instead used as a component in other classes.
Definition at line 32 of file mod_configuration.h.
Member Function Documentation
addGameMods()
void ModConfiguration::addGameMods (const SubgameSpec & gamespec)
Adds game mods
Definition at line 112 of file mod_configuration.cpp.
References addModsInPath().
Referenced by ServerModManager::ServerModManager().
addMods()
void ModConfiguration::addMods (const std::vector< ModSpec > & new_mods)
Adds all mods in new_mods
Definition at line 52 of file mod_configuration.cpp.
Referenced by addModsFromConfig(), and addModsInPath().
addModsFromConfig()
void ModConfiguration::addModsFromConfig (const std::string & settings_path, const std::unordered_map< std::string, std::string > & modPaths)
Adds mods specified by a world.mt config
Parameters
settings_path Path to world.mt
modPaths Map from virtual name to mod path
Definition at line 119 of file mod_configuration.cpp.
References addMods().
Referenced by ServerModManager::ServerModManager().
addModsInPath()
void ModConfiguration::addModsInPath (const std::string & path, const std::string & virtual_path)
Adds all mods in the given path. used for games, modpacks and world-specific mods (worldmods-folders)
Parameters
path To search, should be absolute
virtual_path Virtual path for this directory, see comment in ModSpec
Definition at line 47 of file mod_configuration.cpp.
References addMods().
Referenced by addGameMods(), and ServerModManager::ServerModManager().
checkConflictsAndDeps()
void ModConfiguration::checkConflictsAndDeps ()
Call this function once all mods have been added
Definition at line 198 of file mod_configuration.cpp.
References resolveDependencies().
Referenced by ServerModManager::ServerModManager().
getMods()
const std::vector<ModSpec>& ModConfiguration::getMods () const inline
List of mods sorted such that they can be loaded in the given order with all dependencies being fulfilled.
I.e: every mod in this list has only dependencies on mods which appear earlier in the vector.
Definition at line 52 of file mod_configuration.h.
Referenced by ServerModManager::getModsMediaPaths().
isConsistent()
bool ModConfiguration::isConsistent () const inline
Returns
true if all dependencies are fulfilled.
Definition at line 38 of file mod_configuration.h.
resolveDependencies()
void ModConfiguration::resolveDependencies () private
move mods from m_unsatisfied_mods to m_sorted_mods in an order that satisfies dependencies
Definition at line 220 of file mod_configuration.cpp.
Referenced by checkConflictsAndDeps().
The documentation for this class was generated from the following files:
src/content/mod_configuration.h
src/content/mod_configuration.cpp