Three Cubes Game: irr::core Namespace Reference
irr::core Namespace Reference
Basic classes such as vectors, planes, arrays, lists, and so on can be found in this namespace.
Classes
class aabbox3d
Axis aligned bounding box in 3d dimensional space.
class array
Self reallocating template array (like stl vector) with additional features.
class CMatrix4
4x4 matrix. Mostly used as transformation matrix for 3d calculations.
class dimension2d
Specifies a 2 dimensional size.
union FloatIntUnion32
union inttofloat
class line2d
2D line between two points with intersection methods.
class line3d
3D line between two points with intersection methods.
class plane3d
Template plane class with some intersection testing methods.
class quaternion
Quaternion class for representing rotations.
class rect
Rectangle template.
class string
Very simple string class with some useful features.
class triangle3d
3d triangle template class for doing collision detection and other things.
class ustring16
UTF-16 string class.
class vector2d
2d vector template class with lots of operators and methods.
class vector3d
3d vector template class with lots of operators and methods.
Typedefs
typedef aabbox3d< f32 > aabbox3df
Typedef for a f32 3d bounding box.
typedef aabbox3d< s32 > aabbox3di
Typedef for an integer 3d bounding box.
typedef dimension2d< f32 > dimension2df
Typedef for an f32 dimension.
typedef dimension2d< u32 > dimension2du
Typedef for an unsigned integer dimension.
typedef dimension2d< s32 > dimension2di
Typedef for an integer dimension.
typedef string< c8 > stringc
Typedef for character strings.
typedef string< wchar_t > stringw
Typedef for wide character strings.
typedef ustring16 ustring
typedef line2d< f32 > line2df
Typedef for an f32 line.
typedef line2d< s32 > line2di
Typedef for an integer line.
typedef line3d< f32 > line3df
Typedef for an f32 line.
typedef line3d< s32 > line3di
Typedef for an integer line.
typedef CMatrix4< f32 > matrix4
Typedef for f32 matrix.
typedef plane3d< f32 > plane3df
Typedef for a f32 3d plane.
typedef plane3d< s32 > plane3di
Typedef for an integer 3d plane.
typedef vector2d< f32 > position2df
typedef vector2d< s32 > position2di
typedef rect< f32 > rectf
Rectangle with float values.
typedef rect< s32 > recti
Rectangle with int values.
typedef triangle3d< f32 > triangle3df
Typedef for a f32 3d triangle.
typedef triangle3d< s32 > triangle3di
Typedef for an integer 3d triangle.
typedef vector2d< f32 > vector2df
Typedef for f32 2d vector.
typedef vector2d< s32 > vector2di
Typedef for integer 2d vector.
typedef vector3d< f32 > vector3df
Typedef for a f32 3d vector.
typedef vector3d< s32 > vector3di
Typedef for an integer 3d vector.
Enumerations
enum EIntersectionRelation3D {
ISREL3D_FRONT = 0, ISREL3D_BACK, ISREL3D_PLANAR, ISREL3D_SPANNING,
ISREL3D_CLIPPED
}
Enumeration for intersection relations of 3d objects.
Functions
s32 isFileExtension (const io::path &filename, const io::path &ext0, const io::path &ext1, const io::path &ext2)
search if a filename has a proper extension
bool hasFileExtension (const io::path &filename, const io::path &ext0, const io::path &ext1="", const io::path &ext2="")
search if a filename has a proper extension
io::path & cutFilenameExtension (io::path &dest, const io::path &source)
cut the filename extension from a source file path and store it in a dest file path
io::path & getFileNameExtension (io::path &dest, const io::path &source)
get the filename extension from a file path
io::path & deletePathFromFilename (io::path &filename)
delete path from filename
io::path & deletePathFromPath (io::path &filename, s32 pathCount)
trim paths
s32 isInSameDirectory (const io::path &path, const io::path &file)
static void splitFilename (const io::path &name, io::path *path=0, io::path *filename=0, io::path *extension=0, bool make_lower=false)
splits a path into components
static io::path mergeFilename (const io::path &path, const io::path &filename, const io::path &extension="")
create a filename from components
bool isdigit (s32 c)
some standard function (to remove dependencies)
bool isspace (s32 c)
bool isupper (s32 c)
u32 strtoul10 (const char *in, const char **out=0)
Convert a simple string of base 10 digits into an unsigned 32 bit integer.
s32 strtol10 (const char *in, const char **out=0)
Convert a simple string of base 10 digits into a signed 32 bit integer.
u32 ctoul16 (char in)
Convert a hex-encoded character to an unsigned integer.
u32 strtoul16 (const char *in, const char **out=0)
Convert a simple string of base 16 digits into an unsigned 32 bit integer.
u32 strtoul8 (const char *in, const char **out=0)
Convert a simple string of base 8 digits into an unsigned 32 bit integer.
u32 strtoul_prefix (const char *in, const char **out=0)
Convert a C-style prefixed string (hex, oct, integer) into an unsigned 32 bit integer.
f32 strtof10 (const char *in, const char **out=0)
Converts a sequence of digits into a whole positive floating point value.
const char * fast_atof_move (const char *in, f32 &result)
Provides a fast function for converting a string into a float.
float fast_atof (const char *floatAsString, const char **out=0)
Convert a string to a floating point number.
f32 radToDeg (f32 radians)
Utility function to convert a radian value to degrees.
f64 radToDeg (f64 radians)
Utility function to convert a radian value to degrees.
f32 degToRad (f32 degrees)
Utility function to convert a degrees value to radians.
f64 degToRad (f64 degrees)
Utility function to convert a degrees value to radians.
template<class T >
const T & min_ (const T &a, const T &b)
returns minimum of two values. Own implementation to get rid of the STL (VS6 problems)
template<class T >
const T & min_ (const T &a, const T &b, const T &c)
returns minimum of three values. Own implementation to get rid of the STL (VS6 problems)
template<class T >
const T & max_ (const T &a, const T &b)
returns maximum of two values. Own implementation to get rid of the STL (VS6 problems)
template<class T >
const T & max_ (const T &a, const T &b, const T &c)
returns maximum of three values. Own implementation to get rid of the STL (VS6 problems)
template<class T >
T abs_ (const T &a)
returns abs of two values. Own implementation to get rid of STL (VS6 problems)
template<class T >
T lerp (const T &a, const T &b, const f32 t)
template<class T >
const T clamp (const T &value, const T &low, const T &high)
clamps a value between low and high
template<class T1 , class T2 >
void swap (T1 &a, T2 &b)
swaps the content of the passed parameters
template<class T >
T roundingError ()
template<>
f32 roundingError ()
template<class T >
T relativeErrorFactor ()
template<>
f32 relativeErrorFactor ()
template<class T >
bool equals (const T a, const T b, const T tolerance=roundingError< T >())
returns if a equals b, taking possible rounding errors into account
template<class T >
bool equalsRelative (const T a, const T b, const T factor=relativeErrorFactor< T >())
bool equalsByUlp (f32 a, f32 b, int maxUlpDiff)
We compare the difference in ULP's (spacing between floating-point numbers, aka ULP=1 means there exists no float between).
bool iszero (const f64 a, const f64 tolerance=ROUNDING_ERROR_f64)
returns if a equals zero, taking rounding errors into account
bool iszero (const f32 a, const f32 tolerance=ROUNDING_ERROR_f32)
returns if a equals zero, taking rounding errors into account
bool isnotzero (const f32 a, const f32 tolerance=ROUNDING_ERROR_f32)
returns if a equals not zero, taking rounding errors into account
bool iszero (const s32 a, const s32 tolerance=0)
returns if a equals zero, taking rounding errors into account
bool iszero (const u32 a, const u32 tolerance=0)
returns if a equals zero, taking rounding errors into account
bool iszero (const s64 a, const s64 tolerance=0)
returns if a equals zero, taking rounding errors into account
s32 s32_min (s32 a, s32 b)
s32 s32_max (s32 a, s32 b)
s32 s32_clamp (s32 value, s32 low, s32 high)
u32 IR (f32 x)
f32 FR (u32 x)
Floating-point representation of an integer value.
f32 FR (s32 x)
f32 round_ (f32 x)
REALINLINE f32 squareroot (const f32 f)
REALINLINE f64 squareroot (const f64 f)
REALINLINE s32 squareroot (const s32 f)
REALINLINE s64 squareroot (const s64 f)
REALINLINE f64 reciprocal_squareroot (const f64 x)
REALINLINE f32 reciprocal_squareroot (const f32 f)
REALINLINE s32 reciprocal_squareroot (const s32 x)
REALINLINE f32 reciprocal (const f32 f)
REALINLINE f64 reciprocal (const f64 f)
REALINLINE f32 reciprocal_approxim (const f32 f)
REALINLINE s32 floor32 (f32 x)
REALINLINE s32 ceil32 (f32 x)
REALINLINE s32 round32 (f32 x)
f32 f32_max3 (const f32 a, const f32 b, const f32 c)
f32 f32_min3 (const f32 a, const f32 b, const f32 c)
f32 fract (f32 x)
static size_t multibyteToWString (string< wchar_t > &destination, const char *source, u32 sourceSize)
Internally used by the other multibyteToWString functions.
static size_t wStringToMultibyte (string< c8 > &destination, const wchar_t *source, u32 sourceSize)
Same as multibyteToWString, but the other way around.
static u32 locale_lower (u32 x)
Returns a character converted to lower case.
static u32 locale_upper (u32 x)
Returns a character converted to upper case.
static size_t multibyteToWString (string< wchar_t > &destination, const core::string< c8 > &source)
Convert multibyte string to wide-character string.
static size_t multibyteToWString (string< wchar_t > &destination, const char *source)
Convert multibyte string to wide-character string.
static size_t wStringToMultibyte (string< c8 > &destination, const core::string< wchar_t > &source)
Same as multibyteToWString, but the other way around.
static size_t wStringToMultibyte (string< c8 > &destination, const wchar_t *source)
Same as multibyteToWString, but the other way around.
std::ostream & operator<< (std::ostream &out, const ustring16 &in)
Writes a ustring16 to an ostream.
std::wostream & operator<< (std::wostream &out, const ustring16 &in)
Writes a ustring16 to a wostream.
template<class T >
CMatrix4< T > operator* (const T scalar, const CMatrix4< T > &mat)
template<class S , class T >
vector2d< T > operator* (const S scalar, const vector2d< T > &vector)
template<class S , class T >
vector3d< T > operator* (const S scalar, const vector3d< T > &vector)
Function multiplying a scalar and a vector component-wise.
const matrix4 IdentityMatrix (matrix4::EM4CONST_IDENTITY)
Variables
const float fast_atof_table [17]
const s32 ROUNDING_ERROR_S32 = 0
Rounding error constant often used when comparing f32 values.
const s64 ROUNDING_ERROR_S64 = 0
const f32 ROUNDING_ERROR_f32 = 0.000001f
const f64 ROUNDING_ERROR_f64 = 0.00000001
const f32 PI = 3.14159265359f
Constant for PI.
const f32 RECIPROCAL_PI = 1.0f/PI
Constant for reciprocal of PI.
const f32 HALF_PI = PI/2.0f
Constant for half of PI.
const f64 PI64 = 3.1415926535897932384626433832795028841971693993751
Constant for 64bit PI.
const f64 RECIPROCAL_PI64 = 1.0/PI64
Constant for 64bit reciprocal of PI.
const f32 DEGTORAD = PI / 180.0f
32bit Constant for converting from degrees to radians
const f32 RADTODEG = 180.0f / PI
32bit constant for converting from radians to degrees (formally known as GRAD_PI)
const f64 DEGTORAD64 = PI64 / 180.0
64bit constant for converting from degrees to radians (formally known as GRAD_PI2)
const f64 RADTODEG64 = 180.0 / PI64
64bit constant for converting from radians to degrees
const IRRLICHT_API matrix4 IdentityMatrix
global const identity matrix
Detailed Description
Basic classes such as vectors, planes, arrays, lists, and so on can be found in this namespace.
Typedef Documentation
dimension2di
typedef dimension2d<s32> irr::core::dimension2di
Typedef for an integer dimension.
There are few cases where negative dimensions make sense. Please consider using dimension2du instead.
Definition at line 217 of file dimension2d.h.
position2df
typedef vector2d<f32> irr::core::position2df
Deprecated:
position2d is now a synonym for vector2d, but vector2d should be used directly.
Definition at line 21 of file position2d.h.
position2di
typedef vector2d<s32> irr::core::position2di
Deprecated:
position2d is now a synonym for vector2d, but vector2d should be used directly.
Definition at line 24 of file position2d.h.
Function Documentation
ctoul16()
u32 irr::core::ctoul16 (char in) inline
Convert a hex-encoded character to an unsigned integer.
Parameters
[in] in The digit to convert. Only digits 0 to 9 and chars A-F,a-f will be considered.
Returns
The unsigned integer value of the digit. 0xffffffff if the input is not hex
Definition at line 122 of file fast_atof.h.
degToRad() [1/2]
f32 irr::core::degToRad (f32 degrees) inline
Utility function to convert a degrees value to radians.
Provided as it can be clearer to write degToRad(X) than DEGTORAD * X
Parameters
degrees The degrees value to convert to radians.
Definition at line 82 of file irrMath.h.
References DEGTORAD.
degToRad() [2/2]
f64 irr::core::degToRad (f64 degrees) inline
Utility function to convert a degrees value to radians.
Provided as it can be clearer to write degToRad(X) than DEGTORAD * X
Parameters
degrees The degrees value to convert to radians.
Definition at line 91 of file irrMath.h.
References DEGTORAD64.
equalsRelative()
template<class T > bool irr::core::equalsRelative (const T a, const T b, const T factor = relativeErrorFactor<T>()) inline
returns if a equals b, taking relative error in form of factor this particular function does not involve any division.
Definition at line 227 of file irrMath.h.
References max_(), and min_().
Referenced by irr::core::vector2d< s16 >::nearlyParallel().
fast_atof()
float irr::core::fast_atof (const char * floatAsString, const char ** out = 0) inline
Convert a string to a floating point number.
Parameters
floatAsString The string to convert.
out Optional pointer to the first character in the string that wasn't used to create the float value.
Returns
Float value parsed from the input string
Definition at line 356 of file fast_atof.h.
References fast_atof_move().
Referenced by irr::scene::COBJMeshFileLoader::readColor(), irr::scene::COBJMeshFileLoader::readUV(), and irr::scene::COBJMeshFileLoader::readVec3().
fast_atof_move()
const char* irr::core::fast_atof_move (const char * in, f32 & result) inline
Provides a fast function for converting a string into a float.
This is not guaranteed to be as accurate as atof(), but is approximately 6 to 8 times as fast.
Parameters
[in] in The string to convert.
[out] result The resultant float will be written here.
Returns
Pointer to the first character in the string that wasn't used to create the float value.
Definition at line 306 of file fast_atof.h.
References strtof10(), and strtol10().
Referenced by fast_atof().
IR()
u32 irr::core::IR (f32 x) inline
code is taken from IceFPU Integer representation of a floating-point value.
Definition at line 353 of file irrMath.h.
Referenced by irr::core::CMatrix4< f32 >::isIdentity_integer_base().
isInSameDirectory()
s32 irr::core::isInSameDirectory (const io::path & path, const io::path & file) inline
looks if file is in the same directory of path. returns offset of directory. 0 means in same directory. 1 means file is direct child of path
Definition at line 114 of file coreutil.h.
References irr::core::string< T >::equalsn(), irr::core::string< T >::findNext(), and irr::core::string< T >::size().
Referenced by irr::io::CFileSystem::createFileList().
lerp()
template<class T > T irr::core::lerp (const T & a, const T & b, const f32 t) inline
returns linear interpolation of a and b with ratio t
Returns
: a if t==0, b if t==1, and the linear interpolation else
Definition at line 134 of file irrMath.h.
Referenced by irr::scene::CAnimatedMeshSceneNode::animateJoints(), and irr::scene::CSkinnedMesh::animateMesh().
multibyteToWString() [1/2]
static size_t irr::core::multibyteToWString (string< wchar_t > & destination, const char * source) inline static
Convert multibyte string to wide-character string.
Wrapper around mbstowcs from standard library, but directly writing to Irrlicht string class. What the function does exactly depends on the LC_CTYPE of the current c locale.
Parameters
destination Wide-character string receiving the converted source
source multibyte string
Returns
The number of wide characters written to destination, not including the eventual terminating null character or -1 when conversion failed.
Definition at line 939 of file irrString.h.
References multibyteToWString().
multibyteToWString() [2/2]
static size_t irr::core::multibyteToWString (string< wchar_t > & destination, const core::string< c8 > & source) inline static
Convert multibyte string to wide-character string.
Wrapper around mbstowcs from standard library, but directly using Irrlicht string class. What the function does exactly depends on the LC_CTYPE of the current c locale.
Parameters
destination Wide-character string receiving the converted source
source multibyte string
Returns
The number of wide characters written to destination, not including the eventual terminating null character or -1 when conversion failed
Definition at line 928 of file irrString.h.
References irr::core::string< T >::c_str(), multibyteToWString(), and irr::core::string< T >::size().
radToDeg() [1/2]
f32 irr::core::radToDeg (f32 radians) inline
Utility function to convert a radian value to degrees.
Provided as it can be clearer to write radToDeg(X) than RADTODEG * X
Parameters
radians The radians value to convert to degrees.
Definition at line 64 of file irrMath.h.
References RADTODEG.
radToDeg() [2/2]
f64 irr::core::radToDeg (f64 radians) inline
Utility function to convert a radian value to degrees.
Provided as it can be clearer to write radToDeg(X) than RADTODEG * X
Parameters
radians The radians value to convert to degrees.
Definition at line 73 of file irrMath.h.
References RADTODEG64.
strtof10()
f32 irr::core::strtof10 (const char * in, const char ** out = 0) inline
Converts a sequence of digits into a whole positive floating point value.
Only digits 0 to 9 are parsed. Parsing stops at any other character, including sign characters or a decimal point.
Parameters
in the sequence of digits to convert.
out (optional) will be set to point at the first non-converted character.
Returns
The whole positive floating point representation of the digit sequence.
Definition at line 255 of file fast_atof.h.
Referenced by fast_atof_move().
strtol10()
s32 irr::core::strtol10 (const char * in, const char ** out = 0) inline
Convert a simple string of base 10 digits into a signed 32 bit integer.
Parameters
[in] in The string of digits to convert. Only a leading - or + followed by digits 0 to 9 will be considered. Parsing stops at the first non-digit.
[out] out (optional) If provided, it will be set to point at the first character not used in the calculation.
Returns
The signed integer value of the digits. If the string specifies too many digits to encode in an s32 then +INT_MAX or -INT_MAX will be returned.
Definition at line 86 of file fast_atof.h.
References strtoul10().
Referenced by fast_atof_move().
strtoul10()
u32 irr::core::strtoul10 (const char * in, const char ** out = 0) inline
Convert a simple string of base 10 digits into an unsigned 32 bit integer.
Parameters
[in] in The string of digits to convert. No leading chars are allowed, only digits 0 to 9. Parsing stops at the first non-digit.
[out] out (optional) If provided, it will be set to point at the first character not used in the calculation.
Returns
The unsigned integer value of the digits. If the string specifies too many digits to encode in an u32 then INT_MAX will be returned.
Definition at line 46 of file fast_atof.h.
Referenced by irr::scene::COBJMeshFileLoader::createMesh(), irr::scene::CXMeshFileLoader::readFileIntoMemory(), strtol10(), and strtoul_prefix().
strtoul16()
u32 irr::core::strtoul16 (const char * in, const char ** out = 0) inline
Convert a simple string of base 16 digits into an unsigned 32 bit integer.
Parameters
[in] in The string of digits to convert. No leading chars are allowed, only digits 0 to 9 and chars A-F,a-f are allowed. Parsing stops at the first illegal char.
[out] out (optional) If provided, it will be set to point at the first character not used in the calculation.
Returns
The unsigned integer value of the digits. If the string specifies too many digits to encode in an u32 then INT_MAX will be returned.
Definition at line 143 of file fast_atof.h.
Referenced by strtoul_prefix().
strtoul8()
u32 irr::core::strtoul8 (const char * in, const char ** out = 0) inline
Convert a simple string of base 8 digits into an unsigned 32 bit integer.
Parameters
[in] in The string of digits to convert. No leading chars are allowed, only digits 0 to 7 are allowed. Parsing stops at the first illegal char.
[out] out (optional) If provided, it will be set to point at the first character not used in the calculation.
Returns
The unsigned integer value of the digits. If the string specifies too many digits to encode in an u32 then INT_MAX will be returned.
Definition at line 190 of file fast_atof.h.
Referenced by strtoul_prefix().
strtoul_prefix()
u32 irr::core::strtoul_prefix (const char * in, const char ** out = 0) inline
Convert a C-style prefixed string (hex, oct, integer) into an unsigned 32 bit integer.
Parameters
[in] in The string of digits to convert. If string starts with 0x the hex parser is used, if only leading 0 is used, oct parser is used. In all other cases, the usual unsigned parser is used.
[out] out (optional) If provided, it will be set to point at the first character not used in the calculation.
Returns
The unsigned integer value of the digits. If the string specifies too many digits to encode in an u32 then INT_MAX will be returned.
Definition at line 233 of file fast_atof.h.
References strtoul10(), strtoul16(), and strtoul8().
Variable Documentation
fast_atof_table
const float irr::core::fast_atof_table[17]
Initial value:
= {
    0.f,
    0.1f,
    0.01f,
    0.001f,
    0.0001f,
    0.00001f,
    0.000001f,
    0.0000001f,
    0.00000001f,
    0.000000001f,
    0.0000000001f,
    0.00000000001f,
    0.000000000001f,
    0.0000000000001f,
    0.00000000000001f,
    0.000000000000001f,
    0.0000000000000001f
}
Definition at line 18 of file fast_atof.h.