Three Cubes Game: irr Namespace Reference
irr Namespace Reference
Everything in the Irrlicht Engine can be found in this namespace.
Namespaces
core
Basic classes such as vectors, planes, arrays, lists, and so on can be found in this namespace.
gui
The gui namespace contains useful classes for easy creation of a graphical user interface.
io
This namespace provides interfaces for input/output: Reading and writing files, accessing zip archives, ...
scene
All scene management can be found in this namespace: Mesh loading, special scene nodes like octrees and billboards, ...
video
The video namespace contains classes for accessing the video driver. All 2d and 3d rendering is done here.
Classes
struct AbsRectangle
struct blitterTable
class CIrrDeviceStub
Stub for an Irrlicht Device implementation.
class CLogger
Class for logging messages, warnings and errors to stdout.
class COSOperator
The Operating system operator provides operation system specific methods and information.
class CTimer
Device independent implementation of the timer.
class IEventReceiver
Interface of an object which can receive events.
class ILogger
Interface for logging messages, warnings and errors.
class IOSOperator
The Operating system operator provides operation system specific methods and information.
class IReferenceCounted
Base class of most objects of the Irrlicht Engine.
class IrrlichtDevice
The Irrlicht device. You can create it with createDevice() or createDeviceEx().
class ITimer
Interface for getting and manipulating the virtual time.
struct SBlitJob
struct SEvent
SEvents hold information about an event. See irr::IEventReceiver for details on event handling.
struct SIrrlichtCreationParameters
Structure for holding Irrlicht Device creation parameters.
struct SJoystickInfo
Information on a joystick, returned from irr::IrrlichtDevice::activateJoysticks()
Typedefs
typedef IrrlichtDevice *IRRCALLCONV * funcptr_createDevice(video::E_DRIVER_TYPE driverType, const core::dimension2d< u32 > &windowSize, u32 bits, bool fullscreen, bool stencilbuffer, bool vsync, IEventReceiver *receiver)
typedef for Function Pointer
typedef IrrlichtDevice *IRRCALLCONV * funcptr_createDeviceEx(const SIrrlichtCreationParameters &parameters)
typedef for Function Pointer
typedef uint8_t u8
8 bit unsigned variable.
typedef int8_t s8
8 bit signed variable.
typedef char c8
8 bit character variable.
typedef uint16_t u16
16 bit unsigned variable.
typedef int16_t s16
16 bit signed variable.
typedef uint32_t u32
32 bit unsigned variable.
typedef int32_t s32
32 bit signed variable.
typedef uint64_t u64
64 bit unsigned variable.
typedef int64_t s64
64 bit signed variable.
typedef float f32
32 bit floating point variable.
typedef double f64
64 bit floating point variable.
typedef char fschar_t
Type name for character type used by the file system.
typedef char32_t uchar32_t
typedef char16_t uchar16_t
typedef char uchar8_t
typedef int f18
typedef void(* tExecuteBlit) (const SBlitJob *job)
Enumerations
enum E_DEVICE_TYPE {
EIDT_WIN32, EIDT_X11, EIDT_OSX, EIDT_SDL,
EIDT_BEST, EIDT_ANDROID
}
An enum for the different device types supported by the Irrlicht Engine.
enum EEVENT_TYPE {
EET_GUI_EVENT = 0, EET_MOUSE_INPUT_EVENT, EET_KEY_INPUT_EVENT, EET_STRING_INPUT_EVENT,
EET_TOUCH_INPUT_EVENT, EET_ACCELEROMETER_EVENT, EET_GYROSCOPE_EVENT, EET_DEVICE_MOTION_EVENT,
EET_JOYSTICK_INPUT_EVENT, EET_LOG_TEXT_EVENT, EET_USER_EVENT, EET_SYSTEM_EVENT,
EET_APPLICATION_EVENT, EGUIET_FORCE_32_BIT = 0x7fffffff
}
Enumeration for all event types there are.
enum EMOUSE_INPUT_EVENT {
EMIE_LMOUSE_PRESSED_DOWN = 0, EMIE_RMOUSE_PRESSED_DOWN, EMIE_MMOUSE_PRESSED_DOWN, EMIE_LMOUSE_LEFT_UP,
EMIE_RMOUSE_LEFT_UP, EMIE_MMOUSE_LEFT_UP, EMIE_MOUSE_MOVED, EMIE_MOUSE_WHEEL,
EMIE_LMOUSE_DOUBLE_CLICK, EMIE_RMOUSE_DOUBLE_CLICK, EMIE_MMOUSE_DOUBLE_CLICK, EMIE_LMOUSE_TRIPLE_CLICK,
EMIE_RMOUSE_TRIPLE_CLICK, EMIE_MMOUSE_TRIPLE_CLICK, EMIE_MOUSE_ENTER_CANVAS, EMIE_MOUSE_LEAVE_CANVAS,
EMIE_COUNT
}
Enumeration for all mouse input events.
enum E_MOUSE_BUTTON_STATE_MASK {
EMBSM_LEFT = 0x01, EMBSM_RIGHT = 0x02, EMBSM_MIDDLE = 0x04, EMBSM_EXTRA1 = 0x08,
EMBSM_EXTRA2 = 0x10, EMBSM_FORCE_32_BIT = 0x7fffffff
}
Masks for mouse button states.
enum ETOUCH_INPUT_EVENT { ETIE_PRESSED_DOWN = 0, ETIE_LEFT_UP, ETIE_MOVED, ETIE_COUNT }
Enumeration for all touch input events.
enum ESYSTEM_EVENT_TYPE { ESET_ANDROID_CMD = 0, ESET_COUNT }
enum EAPPLICATION_EVENT_TYPE {
EAET_WILL_RESUME = 0, EAET_DID_RESUME, EAET_WILL_PAUSE, EAET_DID_PAUSE,
EAET_WILL_TERMINATE, EAET_MEMORY_WARNING, EAET_COUNT
}
Enumeration for a commonly used application state events (it's useful mainly for mobile devices)
enum ELOG_LEVEL {
ELL_DEBUG, ELL_INFORMATION, ELL_WARNING, ELL_ERROR,
ELL_NONE
}
enum EKEY_CODE {
KEY_UNKNOWN = 0x0, KEY_LBUTTON = 0x01, KEY_RBUTTON = 0x02, KEY_CANCEL = 0x03,
KEY_MBUTTON = 0x04, KEY_XBUTTON1 = 0x05, KEY_XBUTTON2 = 0x06, KEY_BACK = 0x08,
KEY_TAB = 0x09, KEY_CLEAR = 0x0C, KEY_RETURN = 0x0D, KEY_SHIFT = 0x10,
KEY_CONTROL = 0x11, KEY_MENU = 0x12, KEY_PAUSE = 0x13, KEY_CAPITAL = 0x14,
KEY_KANA = 0x15, KEY_HANGUEL = 0x15, KEY_HANGUL = 0x15, KEY_JUNJA = 0x17,
KEY_FINAL = 0x18, KEY_HANJA = 0x19, KEY_KANJI = 0x19, KEY_ESCAPE = 0x1B,
KEY_CONVERT = 0x1C, KEY_NONCONVERT = 0x1D, KEY_ACCEPT = 0x1E, KEY_MODECHANGE = 0x1F,
KEY_SPACE = 0x20, KEY_PRIOR = 0x21, KEY_NEXT = 0x22, KEY_END = 0x23,
KEY_HOME = 0x24, KEY_LEFT = 0x25, KEY_UP = 0x26, KEY_RIGHT = 0x27,
KEY_DOWN = 0x28, KEY_SELECT = 0x29, KEY_PRINT = 0x2A, KEY_EXECUT = 0x2B,
KEY_SNAPSHOT = 0x2C, KEY_INSERT = 0x2D, KEY_DELETE = 0x2E, KEY_HELP = 0x2F,
KEY_KEY_0 = 0x30, KEY_KEY_1 = 0x31, KEY_KEY_2 = 0x32, KEY_KEY_3 = 0x33,
KEY_KEY_4 = 0x34, KEY_KEY_5 = 0x35, KEY_KEY_6 = 0x36, KEY_KEY_7 = 0x37,
KEY_KEY_8 = 0x38, KEY_KEY_9 = 0x39, KEY_KEY_A = 0x41, KEY_KEY_B = 0x42,
KEY_KEY_C = 0x43, KEY_KEY_D = 0x44, KEY_KEY_E = 0x45, KEY_KEY_F = 0x46,
KEY_KEY_G = 0x47, KEY_KEY_H = 0x48, KEY_KEY_I = 0x49, KEY_KEY_J = 0x4A,
KEY_KEY_K = 0x4B, KEY_KEY_L = 0x4C, KEY_KEY_M = 0x4D, KEY_KEY_N = 0x4E,
KEY_KEY_O = 0x4F, KEY_KEY_P = 0x50, KEY_KEY_Q = 0x51, KEY_KEY_R = 0x52,
KEY_KEY_S = 0x53, KEY_KEY_T = 0x54, KEY_KEY_U = 0x55, KEY_KEY_V = 0x56,
KEY_KEY_W = 0x57, KEY_KEY_X = 0x58, KEY_KEY_Y = 0x59, KEY_KEY_Z = 0x5A,
KEY_LWIN = 0x5B, KEY_RWIN = 0x5C, KEY_APPS = 0x5D, KEY_SLEEP = 0x5F,
KEY_NUMPAD0 = 0x60, KEY_NUMPAD1 = 0x61, KEY_NUMPAD2 = 0x62, KEY_NUMPAD3 = 0x63,
KEY_NUMPAD4 = 0x64, KEY_NUMPAD5 = 0x65, KEY_NUMPAD6 = 0x66, KEY_NUMPAD7 = 0x67,
KEY_NUMPAD8 = 0x68, KEY_NUMPAD9 = 0x69, KEY_MULTIPLY = 0x6A, KEY_ADD = 0x6B,
KEY_SEPARATOR = 0x6C, KEY_SUBTRACT = 0x6D, KEY_DECIMAL = 0x6E, KEY_DIVIDE = 0x6F,
KEY_F1 = 0x70, KEY_F2 = 0x71, KEY_F3 = 0x72, KEY_F4 = 0x73,
KEY_F5 = 0x74, KEY_F6 = 0x75, KEY_F7 = 0x76, KEY_F8 = 0x77,
KEY_F9 = 0x78, KEY_F10 = 0x79, KEY_F11 = 0x7A, KEY_F12 = 0x7B,
KEY_F13 = 0x7C, KEY_F14 = 0x7D, KEY_F15 = 0x7E, KEY_F16 = 0x7F,
KEY_F17 = 0x80, KEY_F18 = 0x81, KEY_F19 = 0x82, KEY_F20 = 0x83,
KEY_F21 = 0x84, KEY_F22 = 0x85, KEY_F23 = 0x86, KEY_F24 = 0x87,
KEY_NUMLOCK = 0x90, KEY_SCROLL = 0x91, KEY_LSHIFT = 0xA0, KEY_RSHIFT = 0xA1,
KEY_LCONTROL = 0xA2, KEY_RCONTROL = 0xA3, KEY_LMENU = 0xA4, KEY_RMENU = 0xA5,
KEY_BROWSER_BACK = 0xA6, KEY_BROWSER_FORWARD = 0xA7, KEY_BROWSER_REFRESH = 0xA8, KEY_BROWSER_STOP = 0xA9,
KEY_BROWSER_SEARCH = 0xAA, KEY_BROWSER_FAVORITES =0xAB, KEY_BROWSER_HOME = 0xAC, KEY_VOLUME_MUTE = 0xAD,
KEY_VOLUME_DOWN = 0xAE, KEY_VOLUME_UP = 0xAF, KEY_MEDIA_NEXT_TRACK = 0xB0, KEY_MEDIA_PREV_TRACK = 0xB1,
KEY_MEDIA_STOP = 0xB2, KEY_MEDIA_PLAY_PAUSE = 0xB3, KEY_OEM_1 = 0xBA, KEY_PLUS = 0xBB,
KEY_COMMA = 0xBC, KEY_MINUS = 0xBD, KEY_PERIOD = 0xBE, KEY_OEM_2 = 0xBF,
KEY_OEM_3 = 0xC0, KEY_OEM_4 = 0xDB, KEY_OEM_5 = 0xDC, KEY_OEM_6 = 0xDD,
KEY_OEM_7 = 0xDE, KEY_OEM_8 = 0xDF, KEY_OEM_AX = 0xE1, KEY_OEM_102 = 0xE2,
KEY_ATTN = 0xF6, KEY_CRSEL = 0xF7, KEY_EXSEL = 0xF8, KEY_EREOF = 0xF9,
KEY_PLAY = 0xFA, KEY_ZOOM = 0xFB, KEY_PA1 = 0xFD, KEY_OEM_CLEAR = 0xFE,
KEY_NONE = 0xFF, KEY_KEY_CODES_COUNT = 0x100
}
enum eClipCode {
CLIPCODE_EMPTY = 0, CLIPCODE_BOTTOM = 1, CLIPCODE_TOP = 2, CLIPCODE_LEFT = 4,
CLIPCODE_RIGHT = 8
}
enum eBlitter {
BLITTER_INVALID = 0, BLITTER_COLOR, BLITTER_COLOR_ALPHA, BLITTER_TEXTURE,
BLITTER_TEXTURE_ALPHA_BLEND, BLITTER_TEXTURE_ALPHA_COLOR_BLEND, BLITTER_TEXTURE_COMBINE_ALPHA
}
Functions
static io::path getExampleMediaPath ()
IRRLICHT_API IrrlichtDevice *IRRCALLCONV createDevice (video::E_DRIVER_TYPE driverType=video::EDT_OPENGL, const core::dimension2d< u32 > &windowSize=(core::dimension2d< u32 >(640, 480)), u32 bits=32, bool fullscreen=false, bool stencilbuffer=true, bool vsync=false, IEventReceiver *receiver=0)
Creates an Irrlicht device. The Irrlicht device is the root object for using the engine.
IRRLICHT_API IrrlichtDevice *IRRCALLCONV createDeviceEx (const SIrrlichtCreationParameters &parameters)
Creates an Irrlicht device with the option to specify advanced parameters.
u32 GetClipCode (const AbsRectangle &r, const core::position2d< s32 > &p)
void GetClip (AbsRectangle &clipping, video::IImage *t)
static u32 extractAlpha (const u32 c)
static u32 packAlpha (const u32 c)
u32 PixelLerp32 (const u32 source, const u32 value)
static void executeBlit_TextureCopy_x_to_x (const SBlitJob *job)
static void executeBlit_TextureCopy_32_to_16 (const SBlitJob *job)
static void executeBlit_TextureCopy_24_to_16 (const SBlitJob *job)
static void executeBlit_TextureCopy_16_to_32 (const SBlitJob *job)
static void executeBlit_TextureCopy_16_to_24 (const SBlitJob *job)
static void executeBlit_TextureCopy_24_to_32 (const SBlitJob *job)
static void executeBlit_TextureCopy_32_to_24 (const SBlitJob *job)
static void executeBlit_TextureBlend_16_to_16 (const SBlitJob *job)
static void executeBlit_TextureBlend_32_to_32 (const SBlitJob *job)
static void executeBlit_TextureBlendColor_16_to_16 (const SBlitJob *job)
static void executeBlit_TextureBlendColor_32_to_32 (const SBlitJob *job)
static void executeBlit_Color_16_to_16 (const SBlitJob *job)
static void executeBlit_Color_32_to_32 (const SBlitJob *job)
static void executeBlit_ColorAlpha_16_to_16 (const SBlitJob *job)
static void executeBlit_ColorAlpha_32_to_32 (const SBlitJob *job)
u16 PixelCombine16 (const u16 c2, const u16 c1)
static void executeBlit_TextureCombineColor_16_to_16 (const SBlitJob *job)
static void executeBlit_TextureCombineColor_16_to_24 (const SBlitJob *job)
u32 PixelCombine32 (const u32 c2, const u32 c1)
static void executeBlit_TextureCombineColor_32_to_24 (const SBlitJob *job)
static void executeBlit_TextureCombineColor_32_to_32 (const SBlitJob *job)
static tExecuteBlit getBlitter2 (eBlitter operation, const video::IImage *dest, const video::IImage *source)
void setClip (AbsRectangle &out, const core::rect< s32 > *clip, const video::IImage *tex, s32 passnative, const core::dimension2d< u32 > *tex_org)
static s32 Blit (eBlitter operation, video::IImage *dest, const core::rect< s32 > *destClipping, const core::position2d< s32 > *destPos, video::IImage *const source, const core::rect< s32 > *sourceClipping, u32 argb)
void memset32 (void *dest, const u32 value, size_t bytesize)
a more useful memset for pixel. dest must be aligned at least to 4 byte
void memset16 (void *dest, const u16 value, size_t bytesize)
a more useful memset for pixel. dest must be aligned at least to 2 byte
static s32 s32_log2_s32 (u32 in)
REALINLINE u32 PixelBlend32 (const u32 c2, const u32 c1, const u32 alpha)
u16 PixelBlend16 (const u16 c2, const u16 c1, const u16 alpha)
u16 PixelMul16 (const u16 c0, const u16 c1)
u16 PixelMul16_2 (u16 c0, u16 c1)
REALINLINE u32 PixelMul32 (const u32 c0, const u32 c1)
REALINLINE u32 PixelMul32_2 (const u32 c0, const u32 c1)
REALINLINE u32 PixelAdd32 (const u32 c2, const u32 c1)
u16 PixelBlend16 (const u16 c2, const u16 c1)
u32 PixelBlend32 (const u32 c2, const u32 c1)
bool intersect (AbsRectangle &dest, const AbsRectangle &a, const AbsRectangle &b)
2D Intersection test
void setShading (video::SColor &color, f32 s)
Sets the shading.
Variables
static const blitterTable blitTable []
Detailed Description
Everything in the Irrlicht Engine can be found in this namespace.
As of Irrlicht 1.6, position2d is a synonym for vector2d.
You should consider position2d to be deprecated, and use vector2d by preference.
Typedef Documentation
c8
typedef char irr::c8
8 bit character variable.
This is a typedef for char, it ensures portability of the engine.
Definition at line 21 of file irrTypes.h.
f32
typedef float irr::f32
32 bit floating point variable.
This is a typedef for float, it ensures portability of the engine.
Definition at line 50 of file irrTypes.h.
f64
typedef double irr::f64
64 bit floating point variable.
This is a typedef for double, it ensures portability of the engine.
Definition at line 54 of file irrTypes.h.
Enumeration Type Documentation
E_DEVICE_TYPE
enum irr::E_DEVICE_TYPE
An enum for the different device types supported by the Irrlicht Engine.
Enumerator
EIDT_WIN32
A device native to Microsoft Windows.
This device uses the Win32 API and works in all versions of Windows.
EIDT_X11
A device native to Unix style operating systems.
This device uses the X11 windowing system and works in Linux, Solaris, FreeBSD, OSX and other operating systems which support X11.
EIDT_OSX
A device native to Mac OSX.
This device uses Apple's Cocoa API and works in Mac OSX 10.2 and above.
EIDT_SDL
A device which uses Simple DirectMedia Layer.
The SDL device works under all platforms supported by SDL but first must be compiled in by setting the USE_SDL2 CMake option to ON
EIDT_BEST
This selection allows Irrlicht to choose the best device from the ones available.
If this selection is chosen then Irrlicht will try to use the IrrlichtDevice native to your operating system. If this is unavailable then the X11, SDL and then console device will be tried. This ensures that Irrlicht will run even if your platform is unsupported, although it may not be able to render anything.
EIDT_ANDROID
A device for Android platforms.
Best used with embedded devices and mobile systems. Does not need X11 or other graphical subsystems. May support hw-acceleration via OpenGL-ES
Definition at line 12 of file EDeviceTypes.h.
E_MOUSE_BUTTON_STATE_MASK
enum irr::E_MOUSE_BUTTON_STATE_MASK
Masks for mouse button states.
Enumerator
EMBSM_EXTRA1
currently only on windows
EMBSM_EXTRA2
currently only on windows
Definition at line 160 of file IEventReceiver.h.
EAPPLICATION_EVENT_TYPE
enum irr::EAPPLICATION_EVENT_TYPE
Enumeration for a commonly used application state events (it's useful mainly for mobile devices)
Enumerator
EAET_WILL_RESUME
The application will be resumed.
EAET_DID_RESUME
The application has been resumed.
EAET_WILL_PAUSE
The application will be paused.
EAET_DID_PAUSE
The application has been paused.
EAET_WILL_TERMINATE
The application will be terminated.
EAET_MEMORY_WARNING
The application received a memory warning.
EAET_COUNT
No real event, but to get number of event types.
Definition at line 203 of file IEventReceiver.h.
EEVENT_TYPE
enum irr::EEVENT_TYPE
Enumeration for all event types there are.
Enumerator
EET_GUI_EVENT
An event of the graphical user interface.
GUI events are created by the GUI environment or the GUI elements in response to mouse or keyboard events. When a GUI element receives an event it will either process it and return true, or pass the event to its parent. If an event is not absorbed before it reaches the root element then it will then be passed to the user receiver.
EET_MOUSE_INPUT_EVENT
A mouse input event.
Mouse events are created by the device and passed to IrrlichtDevice::postEventFromUser in response to mouse input received from the operating system. Mouse events are first passed to the user receiver, then to the GUI environment and its elements, then finally the input receiving scene manager where it is passed to the active camera.
EET_KEY_INPUT_EVENT
A key input event.
Like mouse events, keyboard events are created by the device and passed to IrrlichtDevice::postEventFromUser. They take the same path as mouse events.
EET_STRING_INPUT_EVENT
A string input event.
This event is created when multiple characters are sent at a time (e.g. using an IME).
EET_TOUCH_INPUT_EVENT
A touch input event.
EET_ACCELEROMETER_EVENT
A accelerometer event.
EET_GYROSCOPE_EVENT
A gyroscope event.
EET_DEVICE_MOTION_EVENT
A device motion event.
EET_JOYSTICK_INPUT_EVENT
A joystick (joypad, gamepad) input event.
Joystick events are created by polling all connected joysticks once per device run() and then passing the events to IrrlichtDevice::postEventFromUser. They take the same path as mouse events. Windows, SDL: Implemented. Linux: Implemented, with POV hat issues. MacOS / Other: Not yet implemented.
EET_LOG_TEXT_EVENT
A log event.
Log events are only passed to the user receiver if there is one. If they are absorbed by the user receiver then no text will be sent to the console.
EET_USER_EVENT
A user event with user data.
This is not used by Irrlicht and can be used to send user specific data though the system. The Irrlicht 'window handle' can be obtained from IrrlichtDevice::getExposedVideoData() The usage and behavior depends on the operating system: Windows: send a WM_USER message to the Irrlicht Window; the wParam and lParam will be used to populate the UserData1 and UserData2 members of the SUserEvent. Linux: send a ClientMessage via XSendEvent to the Irrlicht Window; the data.l[0] and data.l[1] members will be cast to s32 and used as UserData1 and UserData2. MacOS: Not yet implemented
EET_SYSTEM_EVENT
Pass on raw events from the OS.
EET_APPLICATION_EVENT
Application state events like a resume, pause etc.
EGUIET_FORCE_32_BIT
This enum is never used, it only forces the compiler to compile these enumeration values to 32 bit.
Definition at line 15 of file IEventReceiver.h.
ELOG_LEVEL
enum irr::ELOG_LEVEL
Possible log levels. When used has filter ELL_DEBUG means => log everything and ELL_NONE means => log (nearly) nothing. When used to print logging information ELL_DEBUG will have lowest priority while ELL_NONE messages are never filtered and always printed.
Enumerator
ELL_DEBUG
Used for printing information helpful in debugging.
ELL_INFORMATION
Useful information to print. For example hardware infos or something started/stopped.
ELL_WARNING
Warnings that something isn't as expected and can cause oddities.
ELL_ERROR
Something did go wrong.
ELL_NONE
Logs with ELL_NONE will never be filtered. And used as filter it will remove all logging except ELL_NONE messages.
Definition at line 17 of file ILogger.h.
EMOUSE_INPUT_EVENT
enum irr::EMOUSE_INPUT_EVENT
Enumeration for all mouse input events.
Enumerator
EMIE_LMOUSE_PRESSED_DOWN
Left mouse button was pressed down.
EMIE_RMOUSE_PRESSED_DOWN
Right mouse button was pressed down.
EMIE_MMOUSE_PRESSED_DOWN
Middle mouse button was pressed down.
EMIE_LMOUSE_LEFT_UP
Left mouse button was left up.
EMIE_RMOUSE_LEFT_UP
Right mouse button was left up.
EMIE_MMOUSE_LEFT_UP
Middle mouse button was left up.
EMIE_MOUSE_MOVED
The mouse cursor changed its position.
EMIE_MOUSE_WHEEL
The mouse wheel was moved. Use Wheel value in event data to find out in what direction and how fast.
EMIE_LMOUSE_DOUBLE_CLICK
Left mouse button double click. This event is generated after the second EMIE_LMOUSE_PRESSED_DOWN event.
EMIE_RMOUSE_DOUBLE_CLICK
Right mouse button double click. This event is generated after the second EMIE_RMOUSE_PRESSED_DOWN event.
EMIE_MMOUSE_DOUBLE_CLICK
Middle mouse button double click. This event is generated after the second EMIE_MMOUSE_PRESSED_DOWN event.
EMIE_LMOUSE_TRIPLE_CLICK
Left mouse button triple click. This event is generated after the third EMIE_LMOUSE_PRESSED_DOWN event.
EMIE_RMOUSE_TRIPLE_CLICK
Right mouse button triple click. This event is generated after the third EMIE_RMOUSE_PRESSED_DOWN event.
EMIE_MMOUSE_TRIPLE_CLICK
Middle mouse button triple click. This event is generated after the third EMIE_MMOUSE_PRESSED_DOWN event.
EMIE_MOUSE_ENTER_CANVAS
Mouse enters canvas used for rendering. Only generated on emscripten
EMIE_MOUSE_LEAVE_CANVAS
Mouse leaves canvas used for rendering. Only generated on emscripten
EMIE_COUNT
No real event. Just for convenience to get number of events.
Definition at line 96 of file IEventReceiver.h.
ESYSTEM_EVENT_TYPE
enum irr::ESYSTEM_EVENT_TYPE
Enumerator
ESET_ANDROID_CMD
From Android command handler for native activity messages.
ESET_COUNT
No real event, but to get number of event types.
Definition at line 191 of file IEventReceiver.h.
ETOUCH_INPUT_EVENT
enum irr::ETOUCH_INPUT_EVENT
Enumeration for all touch input events.
Enumerator
ETIE_PRESSED_DOWN
Touch was pressed down.
ETIE_LEFT_UP
Touch was left up.
ETIE_MOVED
The touch changed its position.
ETIE_COUNT
No real event. Just for convenience to get number of events.
Definition at line 176 of file IEventReceiver.h.
Function Documentation
Blit()
static s32 irr::Blit (eBlitter operation, video::IImage * dest, const core::rect< s32 > * destClipping, const core::position2d< s32 > * destPos, video::IImage *const source, const core::rect< s32 > * sourceClipping, u32 argb) static
a generic 2D Blitter
Definition at line 993 of file CBlit.h.
References irr::video::IImage::getBytesPerPixel(), irr::video::IImage::getData(), irr::video::IImage::getPitch(), and intersect().
Referenced by irr::video::CImage::copyTo(), and irr::video::CImage::copyToWithAlpha().
createDevice()
IRRLICHT_API IrrlichtDevice *IRRCALLCONV irr::createDevice (video::E_DRIVER_TYPE driverType = video::EDT_OPENGL, const core::dimension2d< u32 > & windowSize = (core::dimension2d<u32>(640,480)), u32 bits = 32, bool fullscreen = false, bool stencilbuffer = true, bool vsync = false, IEventReceiver * receiver = 0)
Creates an Irrlicht device. The Irrlicht device is the root object for using the engine.
stub for calling createDeviceEx
If you need more parameters to be passed to the creation of the Irrlicht Engine device, use the createDeviceEx() function.
Parameters
driverType Type of the video driver to use. This can currently be video::EDT_NULL, video::EDT_SOFTWARE, video::EDT_BURNINGSVIDEO, video::EDT_DIRECT3D9 and video::EDT_OPENGL.
windowSize Size of the window or the video mode in fullscreen mode.
bits Bits per pixel in fullscreen mode. Ignored if windowed mode.
fullscreen Should be set to true if the device should run in fullscreen. Otherwise the device runs in windowed mode.
stencilbuffer Specifies if the stencil buffer should be enabled. Set this to true, if you want the engine be able to draw stencil buffer shadows. Note that not all devices are able to use the stencil buffer. If they don't no shadows will be drawn.
vsync Specifies vertical synchronization: If set to true, the driver will wait for the vertical retrace period, otherwise not.
receiver A user created event receiver.
Returns
Returns pointer to the created IrrlichtDevice or null if the device could not be created.
Definition at line 39 of file Irrlicht.cpp.
References createDeviceEx().
createDeviceEx()
IRRLICHT_API IrrlichtDevice *IRRCALLCONV irr::createDeviceEx (const SIrrlichtCreationParameters & parameters)
Creates an Irrlicht device with the option to specify advanced parameters.
Usually you should used createDevice() for creating an Irrlicht Engine device. Use this function only if you wish to specify advanced parameters like a window handle in which the device should be created.
Parameters
parameters Structure containing advanced parameters for the creation of the device. See irr::SIrrlichtCreationParameters for details.
Returns
Returns pointer to the created IrrlichtDevice or null if the device could not be created.
Definition at line 58 of file Irrlicht.cpp.
References irr::SIrrlichtCreationParameters::DeviceType, irr::SIrrlichtCreationParameters::DriverType, irr::video::EDT_NULL, EIDT_ANDROID, EIDT_BEST, EIDT_OSX, EIDT_SDL, EIDT_WIN32, and EIDT_X11.
Referenced by createDevice().
executeBlit_TextureCombineColor_16_to_16()
static void irr::executeBlit_TextureCombineColor_16_to_16 (const SBlitJob * job) static
Combine alpha channels (increases alpha / reduces transparency)
Definition at line 651 of file CBlit.h.
References irr::video::A8R8G8B8toA1R5G5B5(), and PixelCombine16().
executeBlit_TextureCombineColor_16_to_24()
static void irr::executeBlit_TextureCombineColor_16_to_24 (const SBlitJob * job) static
Combine alpha channels (increases alpha / reduces transparency)
Definition at line 679 of file CBlit.h.
References irr::video::A1R5G5B5toA8R8G8B8(), irr::video::A8R8G8B8toA1R5G5B5(), and irr::video::getAlpha().
executeBlit_TextureCombineColor_32_to_24()
static void irr::executeBlit_TextureCombineColor_32_to_24 (const SBlitJob * job) static
Combine alpha channels (increases alpha / reduces transparency) Destination alpha is treated as full 255
Definition at line 791 of file CBlit.h.
References PixelCombine32().
executeBlit_TextureCombineColor_32_to_32()
static void irr::executeBlit_TextureCombineColor_32_to_32 (const SBlitJob * job) static
Combine alpha channels (increases alpha / reduces transparency)
Definition at line 844 of file CBlit.h.
References PixelCombine32().
PixelBlend16()
u16 irr::PixelBlend16 (const u16 c2, const u16 c1, const u16 alpha) inline
Pixel = dest * (1 - alpha) + source * alpha alpha [0;32]
Definition at line 149 of file SoftwareDriver2_helper.h.
PixelBlend32() [1/2]
u32 irr::PixelBlend32 (const u32 c2, const u32 c1) inline
Pixel = dest * (1 - SourceAlpha) + source * SourceAlpha (OpenGL blending)
Definition at line 240 of file SoftwareDriver2_helper.h.
PixelBlend32() [2/2]
REALINLINE u32 irr::PixelBlend32 (const u32 c2, const u32 c1, const u32 alpha)
Pixel = dest * (1 - alpha) + source * alpha alpha [0;256]
Definition at line 119 of file SoftwareDriver2_helper.h.
Referenced by irr::video::CImage::setPixel().
PixelCombine16()
u16 irr::PixelCombine16 (const u16 c2, const u16 c1) inline
Pixel => color = sourceAlpha > 0 ? source, else dest alpha = max(destAlpha, sourceAlpha)
Definition at line 640 of file CBlit.h.
References irr::video::getAlpha().
Referenced by executeBlit_TextureCombineColor_16_to_16().
PixelCombine32()
u32 irr::PixelCombine32 (const u32 c2, const u32 c1) inline
Pixel => color = dest * (1 - SourceAlpha) + source * SourceAlpha, alpha = destAlpha * (1 - SourceAlpha) + sourceAlpha
where "1" means "full scale" (255)
Definition at line 742 of file CBlit.h.
Referenced by executeBlit_TextureCombineColor_32_to_24(), and executeBlit_TextureCombineColor_32_to_32().
PixelLerp32()
u32 irr::PixelLerp32 (const u32 source, const u32 value) inline
Scale Color by (1/value) value 0 - 256 (alpha)
Definition at line 121 of file CBlit.h.
Variable Documentation
blitTable
const blitterTable irr::blitTable[] static
Initial value:
=
{
    { BLITTER_TEXTURE, -2, -2, executeBlit_TextureCopy_x_to_x },
    { BLITTER_TEXTURE, video::ECF_A1R5G5B5, video::ECF_A8R8G8B8, executeBlit_TextureCopy_32_to_16 },
    { BLITTER_TEXTURE, video::ECF_A1R5G5B5, video::ECF_R8G8B8, executeBlit_TextureCopy_24_to_16 },
    { BLITTER_TEXTURE, video::ECF_A8R8G8B8, video::ECF_A1R5G5B5, executeBlit_TextureCopy_16_to_32 },
    { BLITTER_TEXTURE, video::ECF_A8R8G8B8, video::ECF_R8G8B8, executeBlit_TextureCopy_24_to_32 },
    { BLITTER_TEXTURE, video::ECF_R8G8B8, video::ECF_A1R5G5B5, executeBlit_TextureCopy_16_to_24 },
    { BLITTER_TEXTURE, video::ECF_R8G8B8, video::ECF_A8R8G8B8, executeBlit_TextureCopy_32_to_24 },
    { BLITTER_TEXTURE_ALPHA_BLEND, video::ECF_A1R5G5B5, video::ECF_A1R5G5B5, executeBlit_TextureBlend_16_to_16 },
    { BLITTER_TEXTURE_ALPHA_BLEND, video::ECF_A8R8G8B8, video::ECF_A8R8G8B8, executeBlit_TextureBlend_32_to_32 },
    { BLITTER_TEXTURE_ALPHA_COLOR_BLEND, video::ECF_A1R5G5B5, video::ECF_A1R5G5B5, executeBlit_TextureBlendColor_16_to_16 },
    { BLITTER_TEXTURE_ALPHA_COLOR_BLEND, video::ECF_A8R8G8B8, video::ECF_A8R8G8B8, executeBlit_TextureBlendColor_32_to_32 },
    { BLITTER_COLOR, video::ECF_A1R5G5B5, -1, executeBlit_Color_16_to_16 },
    { BLITTER_COLOR, video::ECF_A8R8G8B8, -1, executeBlit_Color_32_to_32 },
    { BLITTER_COLOR_ALPHA, video::ECF_A1R5G5B5, -1, executeBlit_ColorAlpha_16_to_16 },
    { BLITTER_COLOR_ALPHA, video::ECF_A8R8G8B8, -1, executeBlit_ColorAlpha_32_to_32 },
    { BLITTER_TEXTURE_COMBINE_ALPHA, video::ECF_A8R8G8B8, video::ECF_A8R8G8B8, executeBlit_TextureCombineColor_32_to_32 },
    { BLITTER_TEXTURE_COMBINE_ALPHA, video::ECF_A8R8G8B8, video::ECF_R8G8B8, executeBlit_TextureCopy_24_to_32 },
    { BLITTER_TEXTURE_COMBINE_ALPHA, video::ECF_R8G8B8, video::ECF_A8R8G8B8, executeBlit_TextureCombineColor_32_to_24 },
    { BLITTER_TEXTURE_COMBINE_ALPHA, video::ECF_R8G8B8, video::ECF_R8G8B8, executeBlit_TextureCopy_x_to_x },
    { BLITTER_TEXTURE_COMBINE_ALPHA, video::ECF_A1R5G5B5, video::ECF_R8G8B8, executeBlit_TextureCopy_24_to_16 },
    { BLITTER_TEXTURE_COMBINE_ALPHA, video::ECF_A1R5G5B5, video::ECF_A1R5G5B5, executeBlit_TextureCombineColor_16_to_16 },
    { BLITTER_TEXTURE_COMBINE_ALPHA, video::ECF_A1R5G5B5, video::ECF_R8G8B8, executeBlit_TextureCopy_24_to_16 },
    { BLITTER_TEXTURE_COMBINE_ALPHA, video::ECF_R8G8B8, video::ECF_A1R5G5B5, executeBlit_TextureCombineColor_16_to_24 },
    { BLITTER_INVALID, -1, -1, 0 }
}
Definition at line 885 of file CBlit.h.