Three Cubes Game: irr::gui::SGUITTGlyph Struct Reference
irr::gui::SGUITTGlyph Struct Reference
Structure representing a single TrueType glyph.
#include <CGUITTFont.h>
Public Member Functions
SGUITTGlyph ()
Constructor.
DISABLE_CLASS_COPY (SGUITTGlyph)
SGUITTGlyph (SGUITTGlyph &&other)
This class would be trivially copyable except for the reference count on surface.
~SGUITTGlyph ()
Destructor.
void preload (u32 char_index, FT_Face face, video::IVideoDriver *driver, u32 font_size, const FT_Int32 loadFlags)
void unload ()
Unloads the glyph.
video::IImage * createGlyphImage (const FT_Bitmap &bits, video::IVideoDriver *driver) const
Creates the IImage object from the FT_Bitmap.
Public Attributes
bool isLoaded
If true, the glyph has been loaded.
u32 glyph_page
The page the glyph is on.
core::recti source_rect
The source rectangle for the glyph.
core::vector2di offset
The offset of glyph when drawn.
FT_Vector advance
Glyph advance information.
video::IImage * surface
CGUITTFont * parent
The pointer pointing to the parent (CGUITTFont)
Detailed Description
Structure representing a single TrueType glyph.
Definition at line 51 of file CGUITTFont.h.
Member Function Documentation
preload()
void irr::gui::SGUITTGlyph::preload (u32 char_index, FT_Face face, video::IVideoDriver * driver, u32 font_size, const FT_Int32 loadFlags)
Preload the glyph. The preload process occurs when the program tries to cache the glyph from FT_Library. However, it simply defines the SGUITTGlyph's properties and will only create the page textures if necessary. The actual creation of the textures should only occur right before the batch draw call.
Definition at line 156 of file CGUITTFont.cpp.
References advance, createGlyphImage(), irr::gui::CGUITTFont::createGlyphPage(), irr::gui::CGUITTFont::getLastGlyphPage(), irr::gui::CGUITTFont::getLastGlyphPageIndex(), irr::video::ITexture::getOriginalSize(), glyph_page, isLoaded, irr::core::rect< T >::LowerRightCorner, offset, parent, source_rect, surface, irr::core::rect< T >::UpperLeftCorner, irr::core::dimension2d< T >::Width, irr::core::vector2d< T >::X, and irr::core::vector2d< T >::Y.
Member Data Documentation
surface
video::IImage* irr::gui::SGUITTGlyph::surface mutable
This is just the temporary image holder. After this glyph is paged, it will be dropped.
Definition at line 112 of file CGUITTFont.h.
Referenced by preload(), unload(), and irr::gui::CGUITTGlyphPage::updateTexture().
The documentation for this struct was generated from the following files:
src/irrlicht_changes/CGUITTFont.h
src/irrlicht_changes/CGUITTFont.cpp