Three Cubes Game: irr::scene::SMesh Struct Reference
irr::scene::SMesh Struct Reference
Simple implementation of the IMesh interface.
#include <SMesh.h>
Public Member Functions
SMesh ()
constructor
virtual ~SMesh ()
destructor
virtual void clear ()
clean mesh
u32 getMeshBufferCount () const override
returns amount of mesh buffers.
IMeshBuffer * getMeshBuffer (u32 nr) const override
returns pointer to a mesh buffer
IMeshBuffer * getMeshBuffer (const video::SMaterial &material) const override
returns a meshbuffer which fits a material
const core::aabbox3d< f32 > & getBoundingBox () const override
returns an axis aligned bounding box
void setBoundingBox (const core::aabbox3df &box) override
set user axis aligned bounding box
void recalculateBoundingBox ()
recalculates the bounding box
void addMeshBuffer (IMeshBuffer *buf)
adds a MeshBuffer
void setMaterialFlag (video::E_MATERIAL_FLAG flag, bool newvalue) override
sets a flag of all contained materials to a new value
void setHardwareMappingHint (E_HARDWARE_MAPPING newMappingHint, E_BUFFER_TYPE buffer=EBT_VERTEX_AND_INDEX) override
set the hardware mapping hint, for driver
void setDirty (E_BUFFER_TYPE buffer=EBT_VERTEX_AND_INDEX) override
flags the meshbuffer as changed, reloads hardware buffers
Public Member Functions inherited from irr::scene::IMesh
virtual E_ANIMATED_MESH_TYPE getMeshType () const
Returns the type of the meshes.
Public Member Functions inherited from irr::IReferenceCounted
IReferenceCounted ()
Constructor.
virtual ~IReferenceCounted ()
Destructor.
void grab () const
Grabs the object. Increments the reference counter by one.
bool drop () const
Drops the object. Decrements the reference counter by one.
s32 getReferenceCount () const
Get the reference count.
const c8 * getDebugName () const
Returns the debug name of the object.
Public Attributes
core::array< IMeshBuffer * > MeshBuffers
The meshbuffers of this mesh.
core::aabbox3d< f32 > BoundingBox
The bounding box of this mesh.
Additional Inherited Members
Protected Member Functions inherited from irr::IReferenceCounted
void setDebugName (const c8 *newName)
Sets the debug name of the object.
Detailed Description
Simple implementation of the IMesh interface.
Definition at line 18 of file SMesh.h.
Member Function Documentation
addMeshBuffer()
void irr::scene::SMesh::addMeshBuffer (IMeshBuffer * buf) inline
adds a MeshBuffer
The bounding box is not updated automatically.
Definition at line 111 of file SMesh.h.
References irr::IReferenceCounted::grab(), and MeshBuffers.
Referenced by irr::scene::COBJMeshFileLoader::createMesh(), and irr::scene::CMeshManipulator::createMeshCopy().
getMeshBuffer()
IMeshBuffer* irr::scene::SMesh::getMeshBuffer (const video::SMaterial & material) const inline override virtual
returns a meshbuffer which fits a material
reverse search
Implements irr::scene::IMesh.
Definition at line 60 of file SMesh.h.
References MeshBuffers.
The documentation for this struct was generated from the following file:
lib/irrlichtmt/include/SMesh.h