Three Cubes Game: MapNode Struct Reference
MapNode Struct Reference
Public Member Functions
MapNode (content_t content, u8 a_param1=0, u8 a_param2=0) noexcept
bool operator== (const MapNode &other) const noexcept
content_t getContent () const noexcept
void setContent (content_t c) noexcept
u8 getParam1 () const noexcept
void setParam1 (u8 p) noexcept
u8 getParam2 () const noexcept
void setParam2 (u8 p) noexcept
void getColor (const ContentFeatures &f, video::SColor *color) const
void setLight (LightBank bank, u8 a_light, ContentLightingFlags f) noexcept
bool isLightDayNightEq (ContentLightingFlags f) const noexcept
u8 getLight (LightBank bank, ContentLightingFlags f) const noexcept
u8 getLightRaw (LightBank bank, ContentLightingFlags f) const noexcept
u8 getLightBlend (u32 daylight_factor, ContentLightingFlags f) const
u8 getFaceDir (const NodeDefManager *nodemgr, bool allow_wallmounted=false) const
u8 getWallMounted (const NodeDefManager *nodemgr) const
v3s16 getWallMountedDir (const NodeDefManager *nodemgr) const
u8 getDegRotate (const NodeDefManager *nodemgr) const
void rotateAlongYAxis (const NodeDefManager *nodemgr, Rotation rot)
u8 getNeighbors (v3s16 p, Map *map) const
void getNodeBoxes (const NodeDefManager *nodemgr, std::vector< aabb3f > *boxes, u8 neighbors=0) const
void getSelectionBoxes (const NodeDefManager *nodemg, std::vector< aabb3f > *boxes, u8 neighbors=0) const
void getCollisionBoxes (const NodeDefManager *nodemgr, std::vector< aabb3f > *boxes, u8 neighbors=0) const
u8 getMaxLevel (const NodeDefManager *nodemgr) const
u8 getLevel (const NodeDefManager *nodemgr) const
s8 setLevel (const NodeDefManager *nodemgr, s16 level=1)
s8 addLevel (const NodeDefManager *nodemgr, s16 add=1)
void serialize (u8 *dest, u8 version) const
void deSerialize (u8 *source, u8 version)
Static Public Member Functions
static u32 serializedLength (u8 version)
static SharedBuffer< u8 > serializeBulk (int version, const MapNode *nodes, u32 nodecount, u8 content_width, u8 params_width)
static void deSerializeBulk (std::istream &is, int version, MapNode *nodes, u32 nodecount, u8 content_width, u8 params_width)
Public Attributes
u16 param0
u8 param1
u8 param2
Private Member Functions
void deSerialize_pre22 (const u8 *source, u8 version)
Detailed Description
Definition at line 138 of file mapnode.h.
Member Function Documentation
getColor()
void MapNode::getColor (const ContentFeatures & f, video::SColor * color) const
Returns the color of the node.
Parameters
f content features of this node
color output, contains the node's color.
Definition at line 47 of file mapnode.cpp.
getDegRotate()
u8 MapNode::getDegRotate (const NodeDefManager * nodemgr) const
Returns
Rotation in range 0–239 (in 1.5° steps)
Definition at line 101 of file mapnode.cpp.
References NodeDefManager::get().
getLightRaw()
u8 MapNode::getLightRaw (LightBank bank, ContentLightingFlags f) const inline noexcept
Returns the node's light level from param1. If the node emits light, it is ignored.
Parameters
f the ContentLightingFlags of this node.
Definition at line 246 of file mapnode.h.
getNeighbors()
u8 MapNode::getNeighbors (v3s16 p, Map * map) const
Checks which neighbors does this node connect to.
Parameters
p coordinates of the node
Definition at line 474 of file mapnode.cpp.
References NodeDefManager::get(), irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
Referenced by Environment::continueRaycast(), and Game::updatePointedThing().
isLightDayNightEq()
bool MapNode::isLightDayNightEq (ContentLightingFlags f) const inline noexcept
Check if the light value for night differs from the light value for day.
Returns
If the light values are equal, returns true; otherwise false
Definition at line 230 of file mapnode.h.
The documentation for this struct was generated from the following files:
src/mapnode.h
src/mapnode.cpp