Three Cubes Game: irr::scene::SViewFrustum Struct Reference
irr::scene::SViewFrustum Struct Reference
Defines the view frustum. That's the space visible by the camera.
#include <SViewFrustum.h>
Public Types
enum VFPLANES {
VF_FAR_PLANE = 0, VF_NEAR_PLANE, VF_LEFT_PLANE, VF_RIGHT_PLANE,
VF_BOTTOM_PLANE, VF_TOP_PLANE, VF_PLANE_COUNT
}
Public Member Functions
SViewFrustum ()
Default Constructor.
SViewFrustum (const SViewFrustum &other)
Copy Constructor.
SViewFrustum (const core::matrix4 &mat, bool zClipFromZero)
This constructor creates a view frustum based on a projection and/or view matrix.
void setFrom (const core::matrix4 &mat, bool zClipFromZero)
This constructor creates a view frustum based on a projection and/or view matrix.
void transform (const core::matrix4 &mat)
transforms the frustum by the matrix
core::vector3df getFarLeftUp () const
returns the point which is on the far left upper corner inside the the view frustum.
core::vector3df getFarLeftDown () const
returns the point which is on the far left bottom corner inside the the view frustum.
core::vector3df getFarRightUp () const
returns the point which is on the far right top corner inside the the view frustum.
core::vector3df getFarRightDown () const
returns the point which is on the far right bottom corner inside the the view frustum.
core::vector3df getNearLeftUp () const
returns the point which is on the near left upper corner inside the the view frustum.
core::vector3df getNearLeftDown () const
returns the point which is on the near left bottom corner inside the the view frustum.
core::vector3df getNearRightUp () const
returns the point which is on the near right top corner inside the the view frustum.
core::vector3df getNearRightDown () const
returns the point which is on the near right bottom corner inside the the view frustum.
const core::aabbox3d< f32 > & getBoundingBox () const
returns a bounding box enclosing the whole view frustum
void recalculateBoundingBox ()
recalculates the bounding box and sphere based on the planes
float getBoundingRadius () const
get the bounding sphere's radius (of an optimized sphere, not the AABB's)
core::vector3df getBoundingCenter () const
get the bounding sphere's radius (of an optimized sphere, not the AABB's)
void setFarNearDistance (float distance)
the cam should tell the frustum the distance between far and near
core::matrix4 & getTransform (video::E_TRANSFORMATION_STATE state)
get the given state's matrix based on frustum E_TRANSFORMATION_STATE
const core::matrix4 & getTransform (video::E_TRANSFORMATION_STATE state) const
get the given state's matrix based on frustum E_TRANSFORMATION_STATE
bool clipLine (core::line3d< f32 > &line) const
clips a line to the view frustum.
Public Attributes
core::vector3df cameraPosition
the position of the camera
core::plane3d< f32 > planes [VF_PLANE_COUNT]
all planes enclosing the view frustum.
core::aabbox3d< f32 > boundingBox
bounding box around the view frustum
Private Types
enum E_TRANSFORMATION_STATE_FRUSTUM { ETS_VIEW = 0, ETS_PROJECTION = 1, ETS_COUNT_FRUSTUM }
Hold a copy of important transform matrices.
Private Member Functions
void recalculateBoundingSphere ()
recalculates the bounding sphere based on the planes
Private Attributes
core::matrix4 Matrices [ETS_COUNT_FRUSTUM]
Hold a copy of important transform matrices.
float BoundingRadius
float FarNearDistance
core::vector3df BoundingCenter
Detailed Description
Defines the view frustum. That's the space visible by the camera.
The view frustum is enclosed by 6 planes. These six planes share eight points. A bounding box around these eight points is also stored in this structure.
Definition at line 25 of file SViewFrustum.h.
Member Enumeration Documentation
VFPLANES
enum irr::scene::SViewFrustum::VFPLANES
Enumerator
VF_FAR_PLANE
Far plane of the frustum. That is the plane furthest away from the eye.
VF_NEAR_PLANE
Near plane of the frustum. That is the plane nearest to the eye.
VF_LEFT_PLANE
Left plane of the frustum.
VF_RIGHT_PLANE
Right plane of the frustum.
VF_BOTTOM_PLANE
Bottom plane of the frustum.
VF_TOP_PLANE
Top plane of the frustum.
VF_PLANE_COUNT
Amount of planes enclosing the view frustum. Should be 6.
Definition at line 27 of file SViewFrustum.h.
Constructor & Destructor Documentation
SViewFrustum()
irr::scene::SViewFrustum::SViewFrustum (const SViewFrustum & other) inline
Copy Constructor.
Copy constructor ViewFrustum
Definition at line 147 of file SViewFrustum.h.
References boundingBox, cameraPosition, Matrices, planes, and VF_PLANE_COUNT.
Member Function Documentation
clipLine()
bool irr::scene::SViewFrustum::clipLine (core::line3d< f32 > & line) const inline
clips a line to the view frustum.
Clips a line to the frustum.
Returns
True if the line was clipped, false if not
Definition at line 397 of file SViewFrustum.h.
References irr::core::plane3d< T >::getKnownIntersectionWithLine(), planes, and VF_PLANE_COUNT.
getTransform() [1/2]
core::matrix4 & irr::scene::SViewFrustum::getTransform (video::E_TRANSFORMATION_STATE state) inline
get the given state's matrix based on frustum E_TRANSFORMATION_STATE
View Frustum depends on Projection & View Matrix
Definition at line 363 of file SViewFrustum.h.
References irr::video::ETS_PROJECTION, irr::video::ETS_VIEW, and Matrices.
Referenced by irr::scene::CCameraSceneNode::getProjectionMatrix(), irr::scene::CCameraSceneNode::getViewMatrix(), irr::scene::CCameraSceneNode::render(), irr::scene::CCameraSceneNode::setProjectionMatrix(), and irr::scene::CCameraSceneNode::updateMatrices().
getTransform() [2/2]
const core::matrix4 & irr::scene::SViewFrustum::getTransform (video::E_TRANSFORMATION_STATE state) const inline
get the given state's matrix based on frustum E_TRANSFORMATION_STATE
View Frustum depends on Projection & View Matrix
Definition at line 381 of file SViewFrustum.h.
References irr::video::ETS_PROJECTION, irr::video::ETS_VIEW, and Matrices.
setFrom()
void irr::scene::SViewFrustum::setFrom (const core::matrix4 & mat, bool zClipFromZero) inline
This constructor creates a view frustum based on a projection and/or view matrix.
This constructor creates a view frustum based on a projection and/or view matrix.
Definition at line 297 of file SViewFrustum.h.
References irr::core::plane3d< T >::D, irr::core::plane3d< T >::Normal, planes, recalculateBoundingBox(), VF_BOTTOM_PLANE, VF_FAR_PLANE, VF_LEFT_PLANE, VF_NEAR_PLANE, VF_PLANE_COUNT, VF_RIGHT_PLANE, VF_TOP_PLANE, irr::core::vector3d< T >::X, irr::core::vector3d< T >::Y, and irr::core::vector3d< T >::Z.
Referenced by SViewFrustum().
transform()
void irr::scene::SViewFrustum::transform (const core::matrix4 & mat) inline
transforms the frustum by the matrix
Parameters
mat Matrix by which the view frustum is transformed.
Definition at line 170 of file SViewFrustum.h.
References cameraPosition, planes, recalculateBoundingBox(), irr::core::CMatrix4< T >::transformPlane(), irr::core::CMatrix4< T >::transformVect(), and VF_PLANE_COUNT.
Referenced by irr::scene::CSceneManager::isCulled().
The documentation for this struct was generated from the following file:
lib/irrlichtmt/include/SViewFrustum.h